define({
	root: ({
		viewer: {
			loading: {
				step1: "LOADING APPLICATION",
				step2: "LOADING DATA",
				step3: "INITIALIZING THE TOUR",
				fail: "Sorry, Map Tour loading failed",
				failButton: "Retry"
			},
			errors: {
				boxTitle: "An error has occurred",
				invalidConfig: "Fatal error: Invalid configuration",
				invalidConfigOwner: "Fatal error: Invalid configuration (authorized owner required)",
				invalidConfigNoWebmap: "Fatal error: Invalid configuration (web map and authorized owner required)",
				createMap: "Unable to create map",
				invalidApp: "Fatal error: The application cannot be loaded",
				noLayer: "The web map does not contain a valid data layer for Map Tour.",
				noLayerNoHostedFS: "The web map does not contain a valid data layer for Map Tour and you don't have the required privileges to create an hosted Feature Service.",
				noLayerMobile: "Welcome to the Map Tour web application. The application is not configured. The Map Tour builder is not supported on mobile devices.",
				noLayerView: "Welcome to the Map Tour web application.<br />The application is not configured yet.",
				noBuilderWebmapData: "The Map Tour builder can’t be used on this web map because it doesn’t use a Feature Service. <br /><br />You can still share your map with your audience, but you won't be able to change the logo and some other settings which the builder lets you change. <br /><br />If you want to change those settings with your existing map, you can use the downloadable version of this template and host it on your own web server.",
				appSave: "Error saving the web application",
				mapSave: "Error saving the web map",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "You are not authorized to configure this application",
				oldBrowserTitle: "Browser not fully supported",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "The Map Tour builder is not supported on Internet Explorer 10 on Windows 7. You have to <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manually force document mode to Internet Explorer 9 standards</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>downgrade to Internet Explore 9</a> or upgrade to Windows 8.",
				oldBrowserExplain: "This browser doesn't support automatic thumbnail generation from the images you upload into your map tour. You can create a map tour using this browser, but you will have to provide a separate thumbnail image for each of the images you upload.",
				oldBrowserExplain2: "To improve your experience, <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activate Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserClose: "Close"
			},
			mobileHTML: {
				showIntro: "SHOW INTRO",
				hideIntro: "HIDE INTRO",
				navList: "List",
				navMap: "Map",
				navInfo: "Info"
			},
			desktopHTML: {
				storymapsText: "A story map",
				builderButton: "Switch to builder mode"
			},
			builderHTML: {
				panelHeader: "APPLICATION CONFIGURATION",
				buttonSave: "SAVE",
				buttonDiscard: "CANCEL",
				buttonSettings: "Settings",
				buttonView: "View mode",
				buttonOrganize: "Organize",
				buttonAdd: "Add",
				modalCancel: "Cancel",
				modalApply: "Apply",
				organizeHeader: "Organize the tour",
				organizeGeneralCaption: "Use drag and drop to sort tour points",
				organizeDelete: "Delete",
				organizeHide: "Hide",
				addMaxPointReached: "You have reached the maximum number of points authorized by the icons set and cannot add another tour point.<br /><br />Note that if you delete existing points, you will need to reload the application.",
				addMaxPointReachedMobile: "Sorry, you have reached the maximum number of authorized points and cannot add that picture.",
				addClose: "Close",
				addHeader: "Add a new tour point",
				addTabPicture: "Picture",
				addTabInformation: "Information",
				addTabLocation: "Location",
				addSelectCaption: "Select or drop picture",		
				addSelectCaptionNoFileReader: "Select picture",	
				addChangePhoto: "Change picture and thumbnail",
				addPictureResolutionIntro: "The picture resolution is higher than required:",
				addPictureResolutionOldBrowser: "The picture resolution is higher than required. Optimize the Map Tour experience by specifying a resolution lower than %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Change picture resolution to %RESOLUTION%",
				addPictureResolutionKeep: "Keep the original resolution of %RESOLUTION%",
				addSelectThumbnail: "Select thumbnail",
				addNoThumbSelected: "No thumbnail selected",
				addThumbSelected: "Selected",
				addCameraSettingsHeader: "CAMERA SETTINGS",
				addThumbnailHeader: "THUMBNAIL",
				addLabelName: "Name",
				addLabelDescription: "Caption",
				addTextPlaceholder: "Type something",
				addLocatePlaceholder: "Locate an address or a place",
				addPinColor: "Color",
				addLatitude: "Latitude",
				addLongitude: "Longitude",
				addLatitudePlaceholder: "e.g. 34.056",
				addLongitudePlaceholder: "e.g. -117.195",
				addUploading: "Uploading tour point",
				addSave: "Add tour point",
				addMobileUploading: "Uploading picture",
				addMobileName: "Enter a name",
				addMobileNameMandatory: "Error, please enter a name.",
				addMobileError: "Sorry, something has gone wrong",
				settingsHeader: "Application settings",
				settingsTabLayout: "Layout",
				settingsTabColor: "Colors",
				settingsTabLogo: "Header",
				settingsTabFields: "Data",
				settingsTabExtent: "Extent",
				settingsTabZoom: "Zoom Level",
				settingsLayoutExplain: "Select the application layout between the two provided.",
				settingsLayoutProfessional: "Three-panel Layout",
				settingsLayoutModern: "Integrated Layout",
				settingsLayoutSelected: "Selected layout",
				settingsLayoutSelect: "Select this layout",
				settingsColorExplain: "Change appearance by choosing a pre-defined theme, or create your own.",
				settingsLabelColor: "Header, content and footer colors",
				settingsLogoExplain: "Customize the header logo (maximum is 250 x 50px).",
				settingsLogoEsri: "Esri logo",
				settingsLogoNone: "No logo",
				settingsLogoCustom: "Custom logo",
				settingsLogoCustomPlaceholder: "Image URL",
				settingsLogoCustomTargetPlaceholder: "Click-through link",
				settingsLogoSocialExplain: "Customize the header top right link.",
				settingsLogoSocialText: "Text",
				settingsLogoSocialLink: "Link",
				settingsDataFieldsExplain: "Select photo name, caption and color fields.",
				settingsDataFieldsError: "The application cannot determine the appropriate name, caption or color data. Please select the fields to be used here. These settings can be changed at a later time.",
				settingsFieldsLabelName: "Name",
				settingsFieldsLabelDescription: "Caption",
				settingsFieldsLabelColor: "Color",
				settingsExtentExplain: "Set the Map Tour initial extent through the interactive map below.",
				settingsExtentExplainBottom: "That extent is used only if it include the first tour point. The value is persisted through the web map initial extent.",
				settingsExtentDrawBtn: "Draw a new extent",
				settingsExtentModifyBtn: "Edit the current extent",
				settingsExtentApplyBtn: "Apply on main map",
				settingsZoomExplain: "Set zoom for story points following introduction (optional).",
				settingsLabelZoom: "Scale/level",
				settingsZoomFirstValue: "None",
				settingsFieldError : "Please select a field in each list",
				dataHeader: "Application data",
				dataExplain: "Your web map does not contain a feature service. Complete this dialog to <strong>create a hosted feature service</strong> within your ArcGIS.com organization account.<br /><br />The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />The application will only be viewable by you until you share it with others. <strong>Once your Map Tour is ready, share it through the application item page.</strong> The system will ask you if you want to update your Feature Service sharing privileges. This is required for your users to access your data. You will remain the only one with editing privileges.",
				dataNameLbl: "Service name",
				dataFolderListLbl: "Folder",
				dataFolderListFetching: "Fetching folders ...",
				dataRootFolder: "Root",
				dataNameError: "Enter a name for the feature service",
				dataFolderError: "Select a valid folder",
				dataSrcContainsInvalidChar: "The feature service name contains one or more invalid characters (-, <, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "A service with that name already exists within the organization. Please choose a different name.",
				dataBtnClose: "Cancel the tour",
				dataBtnSave: "Create the service",
				dataFooterProgress: "Creation in progress",
				dataFooterSucceed: "Creation succeeded. Loading",
				dataFooterError: "Creation failed. Please try again",
				tabError: "Please check for errors in all tabs",
				introRecordBtn: "Intro",
				introRecordActivate: "Use the first point as an introduction"
			},
			addPopupJS: {
				uploadingPicture: "Uploading picture",
				uploadSuccess: "Upload successful",
				uploadError: "Error uploading the picture",
				notJpg: "Please choose a jpeg photo to upload",
				errorNoPhoto: "Choose an image to upload",
				errorNoThumbnail: "Choose a thumbnail to upload",
				errorNoName: "Enter a name for this tour point",
				errorNoDescription: "Enter a caption for this tour point",
				errorNoLocation: "Set a location for this tour point"
			},
			builderJS: {
				noPendingChange: "No pending change",
				unSavedChangeSingular: "1 unsaved change",
				unSavedChangePlural: "unsaved changes",
				popoverDiscard: "Are you sure to want to discard any unsaved changes?",
				yes: "Yes",
				no: "No",
				popoverLoseSave: "By opening the viewer, you will lose any unsaved changes",
				ok: "Ok",
				popoverSaveWhenDone: "Don't forget to save when you are done",
				closeWithPendingChange: "Are you sure to want to confirm the action ? Your changes will be lost.",
				gotIt: "Ok",
				savingApplication: "Saving application",
				saveSuccess: "Application saved successfully",
				saveError: "Save failed, please try again",
				dragColorPicker: "Move me around<br />or change my color",
				dataWarningExtent: "You have data outside of the web map extent. Those data won't be used as tour points, change map extent if you want to use them.",
				dataWarningVisibi: "Your Map Tour layer is not visible at the current web map extent. Confirm your Map Tour layer is visible with a %MAPSIZE% large map.",
				dataWarningEdit: "Edit web map",
				dataWarningClose: "Close",
				signIn: "Please sign in with an account on",
				signInTwo: "to save the application."
			},
			organizePopupJS: {
				messageStart: "You have chosen to delete",
				messageSinglePoint: "one tour point",
				messageMultiPoint: "tour points",
				messagePermantRemove: "This will permanently remove the",
				messageRecord: "record",
				messageRecordPlural: "records",
				messageConfirm: "from your database. Do you want to continue?",
				labelButtonShow: "Show",
				labelButtonHide: "Hide"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "Uploading picture and thumbnail",
				popoverUploadingThumbnail: "Uploading thumbnail",
				popoverUploadSuccessful: "Upload successful",
				popoverUploadError: "Upload failed, please try again",
				changePicAndThumb: "Change picture",
				changeThumb: "Change thumbnail",
				selectPic: "Change picture",
				selectThumb: "Change thumbnail",
				uploadPicAndThumb: "Apply"
			},
			headerJS:{
				editMe: "Edit me !",
				templateTitle: "Set template title",
				templateSubtitle: "Set template subtitle"
			},
			crossFaderJS:{
				setPicture: "Set picture title",
				setCaption: "Set picture caption"
			}
        }
    }),
	"ar":1,
	"da":1,
	"de":1,
	"es":1,
	"fr":1,
	"he":1,
	"it":1,
	"ja":1,
	"ko":1,
	"lt":1,
	"nl":1,
	"nb":1,
	"pl":1,
	"pt-br":1,
	"pt-pt":1,
	"ro":1,
	"ru":1,
	"sv":1,
	"zh-cn":1
});
