define({
  "viewer": {
    "loading": {
      "step1": "IELĀDĒ STĀSTU",
      "step2": "IELĀDĒ DATUS",
      "step3": "IZPILDA TŪRI",
      "loadBuilder": "PĀRSLĒGT UZ BUILDER MODE",
      "redirectSignIn": "NOVIRZA UZ PIERAKSTĪŠANĀS LAPU",
      "redirectSignIn2": "(pēc pierakstīšanās jūs tiksiet novirzīti uz šejieni)",
      "fail": "Atvainojiet, Map Tour ielādēšanas neveiksme",
      "failButton": "Atkārtot"
    },
    "errors": {
      "boxTitle": "Kļūda",
      "portalSelf": "Fatāla kļūda: neizdevās iegūt portāla konfigurāciju",
      "invalidConfig": "Fatāla kļūda: konfigurācijas neveiksme",
      "invalidConfigOwner": "Fatāla kļūda: konfigurācijas neveiksme (nepieciešams autorizēts īpašnieks)",
      "invalidConfigNoWebmap": "Fatāla kļūda: konfigurācijas neveiksme (nav norādīta web karte vai aplikācijas identifikators index.html failā)",
      "invalidConfigNoAppDev": "URL parametros nav norādīts Web kartēšanas aplikācijas identifikators vai Web karte (?appid= vai ?webmap=). Izstrādes režīmā lapā index.html ir ignorēta appid un webmap konfigurācija.",
      "createMap": "Nevar izveidot karti",
      "invalidApp": "Fatāla kļūda: stāstu nevar ielādēt",
      "noLayer": "Web karte nesatur derīgu datu slāni priekš Map Tour.",
      "noLayerMobile": "Map Tour veidotājs nav atbalstīts šim displeja izmēram. Ja iespējams, mainiet pārlūkprogrammas izmēru tā, lai piekļūtu veidotājam, vai veidojiet savu stāstu ierīcē ar lielāku ekrānu.",
      "noLayerMobile2": "Lai izmantotu Map Tour veidotāju, pagrieziet ierīcē ainavas orientāciju.",
      "noLayerView": "Laipni lūdzam tīmekļa lietotnē Map Tour!<br />Stāsts vēl nav konfigurēts.",
      "appSave": "Saglabājot stāstu, radās kļūda",
      "mapSave": "Kļūda, saglabājot web karti",
      "featureServiceLoad": "Kļūda ielādējot elementu servisu",
      "notAuthorized": "Jūs neesat pilnvarots piekļūt šim stāstam",
      "notAuthorizedBuilder": "Jums nav autorizācijas izmantot Map Tour veidotāju.",
      "oldBrowserTitle": "Pārlūks netiek pilnībā atbalstīts",
      "noBuilderIE8": "Map Tour veidotājs neatbalsta Internet Explorer pirms 9 versiju.",
      "ie10Win7Explain": "Map Tour interaktīvais veidotājs nav atbalstīts ar Internet Explorer 10 uz Windows 7, kad datu avots ir Feature Service ar piesaistēm. Lai lietotu Feature Service ar piesaistēm, jums vajag <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuāli piespiest dokumenta režīmu uz Internet Explorer 9 standartu</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>pazemināt uz Internet Explore 9</a> vai uzlabot uz Windows 8.",
      "oldBrowserExplain": "Šis pārlūks neatbalsta automātisku sīktēlu radīšanu no attēliem, ko jūs augšupielādējat jūsu map tour. Jūs varat izveidot map tour, izmantojot šo pārlūku, bet jums būs jāsniedz atsevišķs sīktēls par katru no augšupielādētiem attēliem .",
      "oldBrowserExplain2": "Lai uzlabotu jūsu pieredzi, <a href='http://browsehappy.com/' target='_blank'>jaunina jūsu pārlūku</a> vai <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivizē Google Chrome Frame priekš Internet Explorer</a>.",
      "oldBrowserExplain3": "The Map Tour veidotājs nedarbojas ar Internet Explorer 10 uz Windows XP.",
      "oldBrowserClose": "Aizvērt",
      "noViewerIE2": "Jūs mēģināt skatīt šo stāstu, izmantojot vecāku, neatbalstītu pārlūku. Var gadīties, ka nedarbojas kāds elements vai rodas citas neparedzētas problēmas. Iesakām jaunināt uz Internet Explorer 11 vai izmantot citu pārlūku, piemēram, Chrome.",
      "noViewerIE3": "No 2017. gada beigām šo stāstu vairs nevarēs ielādēt šajā pārlūkā. Pēc tam šī stāsta skatīšanai ir jāizmanto atbalstīts pārlūks.",
      "attention": "Uzmanību!"
    },
    "mobileHTML": {
      "showIntro": "RĀDĪT VIRSRAKSTU",
      "hideIntro": "PASLĒPT VIRSRAKSTU",
      "navList": "Saraksts",
      "navMap": "Karte",
      "navInfo": "Mediji",
      "introStartBtn": "Starts"
    },
    "desktopHTML": {
      "storymapsText": "Stāstu karte",
      "builderButton": "Pārslēgties uz veidotāja režīmu",
      "facebookTooltip": "Koplietot Facebook",
      "twitterTooltip": "Koplietot Twitter",
      "bitlyTooltip": "Iegūt īso saiti",
      "bitlyStartIndex": "Saite uz pašreizējo vietu",
      "tooltipAutoplayDisabled": "Tas nav pieejams automātiskās demonstrēšanas režīmā",
      "autoplayLabel": "Automātiskās demonstrēšanas režīms",
      "autoplayExplain1": "Automātiskās demonstrēšanas režīms darbosies jūsu stāstā ar regulāriem intervāliem. Tas ir izcili piemērots stendiem vai publiskās demonstrēšanas monitoram, bet ņemiet vērā, ka citās situācijās šis režīms var padarīt stāstu grūtāk izlasāmu. Šī funkcija netiek atbalstīta maza izmēra displejos.",
      "autoplayExplain2": "Pēc šī režīma aktivizēšanas ir pieejamas vadīklas stāsta demonstrēšanai/apturēšanai un navigācijas ātruma regulēšanai.",
      "takeTourText": "Skatīt tūri",
      "backToStart": "Atpakaļ uz sākumu"
    },
    "builderHTML": {
      "panelHeader": "STĀSTA KONFIGURĒŠANA",
      "buttonSave": "SAGLABĀT",
      "buttonSettings": "Iestatījumi",
      "buttonShare": "Koplietot",
      "buttonView": "Skata režīms",
      "buttonItem": "Atvērt web aplikācijas vienību",
      "buttonHelp": "Palīdzība",
      "buttonOrganize": "Organizē",
      "buttonOrganizeAndCover": "Tūres punktu organizēšana un titullapas pievienošana",
      "buttonAdd": "Pievienot",
      "buttonImport": "Importēt",
      "buttonImportDisabled": "Izmantojot attēlu augšupielādi, importēšana nav pieejama. Lūdzu, noklikšķiniet uz Pievienot, lai augšupielādētu attēlu.",
      "dataEditionDisabled": "Datu rediģēšana šajā CSV datu avotā ir atspējota",
      "dataSourceWarning": "Kartes tūres datu slānis ir mainīts. Ja elementa ID nav vienādi, ir nepieciešams atiestatīts rīkojumu un slēptās norādes, izmantojot <b>Organizēt</b>. Ja lauku nosaukumi atšķiras, lauku iestatījumus ir nepieciešams atiestatīt <b>datu cilnē Iestatījumi</b>.",
      "organizeWarning": "Viens vai vairāki punkti pievienoti ārpus interaktīvā veidotāja ir paslēpti.",
      "dataPicError0a": "Ši tūre ietver <b>%NB%</b> neatbisltošu bildes URL.",
      "dataPicError0b": "Šī tūre var ietvert <b>%NB%</b> neatbilstošu bildes URL.",
      "dataPicError1": "Map Tour tagad pieprasa, lai attēla URL beidzas ar vienu no sekojošiem paplašinājumiem: .jp(e)g, .png, .gif vai .bmp.",
      "dataPicError2": "Šī prasība neietekmēs jau eksistējošās publicētās Map Tour. Lai gan, lai izmantotu inerkatīvo veidotāju, jums jāatrisina URL jautājums, veicot vienu no divām darbībām:",
      "dataPicError3": "Rediģēt URL",
      "dataPicError4": "Tas pievienos <i>#isImage</i> neatbalstītu attēlu vietrāžu URL beigām. Lielākā daļa serveru atbalsta URL piedēkļus. Tomēr, kad esat veicis šo darbību, jums ir jāpārbauda, vai atjauninātie attēlu vietrāži URL ir funkcionāli, pārvietojoties pa jūsu norādēm. Ja katra attēlu var ielādēt, tagad variet saglabāt Kartes tūri. Ja<b>attēli ir bojāti, nesaglabājiet Kartes tūri</b>. Tā vietā pārlādējiet veidotāju un veiciet otro darbību.",
      "dataPicError5": "Limitēt tūri uz attēliem",
      "dataPicError6": "Šī opcija liks uzskatīt visus URL par attēliem, bet nebūs iespējams pievienot video, izmantojot interaktīvo veidotāju. Šī darbība ir atgriezeniska, ja nākotnē izlemsiet pievienot video.",
      "dataPicError7": "Jūsu Kartes tūre ir ierobežota ar attēliem, nevar izmantot video. Ja izvēlaties noņemt šo ierobežojumu, pirms Kartes tūres saglabāšanas pārbaudiet, vai attēli joprojām tiek pareizi ielādēti. Ja nepieciešams, šo ierobežojumu varēsit atjaunot vēlāk.",
      "dataPicError8": "Noņemt attēlu ierobežojumu",
      "dataPicError9": "Ja šie URL norāda uz video, jūs varat ignorēt šo brīdinājumu, ja tie norāda uz attēliem, jums jāveic viena no sekojošām divām darbībām:",
      "modalCancel": "Atcelt",
      "modalApply": "Lietot",
      "organizeHeader": "Organizē tūri",
      "organizeGeneralCaption": "Izmantot vilkt un nomest, lai kārtotu maršruta punktus",
      "organizeDelete": "Izdzēst",
      "organizeHide": "Paslēpt",
      "organizeReset": "Atiestatīt kārtību un slēptos punktus",
      "addMaxPointReached": "Jūs esat sasniedzis maksimālo punktu skaitu, kas ir pilnvarots ikonu iestatījumos, un nevarat pievienot citu tūres punktu.<br /><br />Ja izdzēsīsiet esošos punktus, stāsts būs jāielādē atkārtoti.",
      "addMaxPointReachedMobile": "Atvainojiet, jūs esat sasniedzis maksimālo autorizēto punktu skaitu un nevarat pievienot šo bildi.",
      "addClose": "Aizvērt",
      "addHeader": "Pievienot jaunu tūres punktu",
      "addTabPicture": "Mediji",
      "addTabInformation": "Informācija",
      "addTabLocation": "Izvietojums",
      "addSelectCaption": "Izvēlieties vai iemetiet bildi",
      "addNoteVideo": "Apskatiet Palīdzību, lai uzzinātu instrukcijas kā izmantot video",
      "addSelectCaptionNoFileReader": "Izvēlieties attēlu",
      "addChangePhoto": "Mainīt bildi un sīkattēlu",
      "addPictureResolutionIntro": "Attēla rezolūcija ir lielāka nekā nepieciešams:",
      "addPictureResolutionOldBrowser": "Attēla rezolūcija ir lielāka nekā nepieciešams. Optimizēt Map Tour pieredzi, norādot zemāku rezolūciju nekā %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Mainīt attēla rezolūciju uz %RESOLUTION%",
      "addPictureResolutionKeep": "Paturēt oriģinālo rezolūciju %RESOLUTION%",
      "addSelectThumbnail": "Izvēlēties sīktēlu",
      "addNoThumbSelected": "Nav izvēlēts sīktēls",
      "addThumbSelected": "Izvēlētais",
      "addCameraSettingsHeader": "KAMERAS IESTATĪJUMI",
      "addThumbnailHeader": "SĪKTĒLS",
      "addLabelPicUrl": "Bilde",
      "addLabelThumbUrl": "Sīktēls",
      "addTextPlaceholderUrl": "Ievadiet attēla URL",
      "addTextPlaceholderUrl2": "Ievadiet YouTube lapas URL",
      "addTextPlaceholderUrl3": "Ievadiet Vimeo lapas URL",
      "addTextPlaceholderUrl4": "Ievadiet iedarinātā video URL",
      "addLabelVideo": "Video",
      "addMediaVideoOther": "Citi",
      "addMediaVideoHelp": "Pārbaudiet URL un iegūstiet noklusējuma sīkattēlu",
      "addMediaVideoHelpTooltip1": "Pārbaude izdevās",
      "addMediaVideoHelpTooltip2": "Pārbaude neizdevās",
      "addMediaVideoHelpTooltip4": "Atrodiet opciju lai iedarinātu video un kopējiet video URL kas ir redzams kodā",
      "addLabelName": "Nosaukums",
      "addLabelDescription": "Virsraksts",
      "addTextPlaceholder": "Rakstīt kaut ko",
      "addLocatePlaceholder": "Atrast adresi vai vietu",
      "addPinColor": "Krāsa",
      "addLatitude": "Platums",
      "addLongitude": "Garums",
      "addLatitudePlaceholder": "piem. 34.056",
      "addLongitudePlaceholder": "piem. -117.195",
      "addUploading": "Augšupielādējot tūres punktu",
      "addSave": "Pievienot tūres punktu",
      "addMobileUploading": "Augšupielādē bildi",
      "addMobileName": "Ievadiet nosaukumu",
      "addMobileNameMandatory": "Kļūda, lūdzu, ievadiet nosaukumu.",
      "addMobileError": "Atvainojiet, kaut kas ir nogājis greizi",
      "settingsHeader": "Iestatījumi",
      "settingsTabLayout": "Izkārtojums",
      "settingsTabColor": "Krāsas",
      "settingsTabLogo": "Galvene",
      "settingsTabFields": "Dati",
      "settingsTabExtent": "Pārklājums",
      "settingsTabZoom": "Mērogmaiņas līmenis",
      "settingsLayoutExplain": "Atlasiet vēlamo izkārtojumu.",
      "settingsLayoutProfessional": "Trīs paneļi",
      "settingsLayoutModern": "Integrēts",
      "settingsLayoutSidePanel": "Sāna panelis",
      "settingsLayoutSelected": "Izvēlētais izkārtojums",
      "settingsLayoutNew": "Jaunums!",
      "settingsLayoutSelect": "Atlasīt",
      "settingsLayoutNote": "Ņemiet vērā, ka punktiem, kuriem izmantoti video, virsraksti vienmēr būs novietoti zem video, pat ja šī izvēlne būs atiezīmēta.",
      "settingsLayoutLocBtn": "Attēlot pogu 'Atrast izvietojumu'",
      "settingsLayoutLocBtnHelp": "Atbalstīts vairākumā pārlūku. Tiek parādīts tikai tad, kad stāsta kartei piekļūst, izmantojot HTTPS. Netiek parādīts, ja stāsts ir iedarināts.",
      "settingsColorExplain": "Mainīt izskatu, izvēloties iepriekš noteiktu tēmu, vai izveidojot savu.",
      "settingsLabelColor": "Galvenes, satura un kājenes krāsas",
      "settingsLogoExplain": "Pielāgot galvenes logotipu (maksimums  ir 250 x 50piks).",
      "settingsLogoEsri": "Esri logotips",
      "settingsLogoNone": "Nav logotipa",
      "settingsLogoCustom": "Pielāgots logotips",
      "settingsLogoCustomPlaceholder": "Attēla URL",
      "settingsLogoCustomTargetPlaceholder": "Klikšķis caur saiti",
      "settingsLogoSocialExplain": "Pielāgot galvenes labās augšējās saites.",
      "settingsLogoSocialText": "Teksts",
      "settingsLogoSocialLink": "Saite",
      "settingsLogoSocialDisabled": "Administrators ir atspējojis šo iezīmi",
      "settingsDataFieldsExplain": "Izvēlieties foto nosaukumu, uzrakstu un krāsu laukus.",
      "settingsDataFieldsError": "Aplikācija nevar noteikt piemērotu nosaukumu, uzrakstu vai krāsu datus. Lūdzu, izvēlieties laukus ko šeit izmantot. Šos iestatījumus var mainīt vēlāk.",
      "settingsFieldsLabelName": "Nosaukums",
      "settingsFieldsLabelDescription": "Uzraksts",
      "settingsFieldsLabelColor": "Krāsa",
      "settingsFieldsReset": "Atiestātīt lauku atlasi",
      "settingsExtentExplain": "Iestatīt Kartes tūres sākotnējo pārklājumu, izmantojot interaktīvo karti zemāk.",
      "settingsExtentExplainBottom": "Jūsu definētais pārklājums modificēs kartes galveno pārklājumu. Ņemiet vērā, ka šis pārklājums netiek izmantots, ja tas neietver pirmo tūres punktu. Tādā gadījumā tūre tiks atvērta pirmajā norādē.",
      "settingsExtentDateLineError": "Pārklājums nevar būt pāri 180Â° meridiāna garumam.",
      "settingsExtentDateLineError2": "Kļūda aprēķinot pārklājumu",
      "settingsExtentDrawBtn": "Zīmēt jaunu pārklājumu",
      "settingsExtentModifyBtn": "Rediģēt pārklājumu",
      "settingsExtentApplyBtn": "Priekšskatīt Map Tour",
      "settingsExtentUseMainMap": "Lietot Map Tour pārklājumu",
      "settingsZoomExplain": "Iestatīt mērogmaiņu stāstu punktiem (pēc izvēles).",
      "settingsLabelZoom": "Mērogs/līmenis",
      "settingsZoomFirstValue": "Neviens",
      "settingsFieldError": "Lūdzu, izvēlieties lauku katrā sarakstā",
      "dataTitle": "Viesota Map Tour slāņa izveide",
      "dataExplain": "Jūsu attēliem un tūres punktiem tiks izveidots jauns elementu slānis. Tūres slānis netiks koplietots ne ar vienu citu, ja vien nekoplietosiet savu karšu tūri.",
      "dataExplainPortal": "Ja elementa slānis netiek veiksmīgi izveidots, sazinieties ar ArcGIS administratoru.",
      "dataNameLbl": "Slāņa nosaukums",
      "dataFolderListLbl": "Mape",
      "dataFolderListFetching": "Mapju ienešana ...",
      "dataRootFolder": "Sakne",
      "dataNameError": "Ievadiet nosaukumu elementu servisam",
      "dataFolderError": "Izvēlieties derīgu mapi",
      "dataSrcContainsInvalidChar": "Elementu servisa nosaukums satur vienu vai vairākas nederīgas rakstzīmes (-, <, >, #, %, :, \", ?, &, +, /, or ).",
      "dataSrvAlreadyExistsError": "Serviss ar šādu nosaukumu jau pastāv organizācijā. Lūdzu, izvēlieties citu nosaukumu.",
      "dataBtnSave": "Slāņa izveide",
      "dataFooterProgress": "Izveide notiek",
      "dataFooterSucceed": "Izveide izdevās. Ielādē",
      "dataFooterError": "Izveide neizdevās. Lūdzu, mēģiniet vēlreiz",
      "tabError": "Lūdzu pārbaudīt kļūdas visās cilnēs",
      "introRecordBtn": "Ievads",
      "introRecordActivate": "Izmantojiet pirmo punktu, kā ievadu (neparādās karuselī)",
      "coverRecordActivate": "Izmantot pirmo punktu kā titullapu",
      "coverBuilder": "Titullapas konfigurācija",
      "cover": "Vāks",
      "showCover": "Rādīt vāku",
      "editCover": "Labot vāku",
      "coverNoVideo": "Vāka multivide neatbalsta video saturu. Izvēlieties attēlu.",
      "coverPreview": "Lai skatītu titullapu, saglabājiet stāstu un pēc tam priekšskatiet to, izmantojot pogu Skatīt stāstu.",
      "thirdPartyTerms": "Izmantojot šo trešās puses pakalpojumu, jūs piekrītat tā lietošanas noteikumiem. "
    },
    "addPopupJS": {
      "uploadingPicture": "Augšupielādē attēlu",
      "uploadSuccess": "Augšupielāde veiksmīga",
      "uploadError": "Kļūda, augšupielādējot attēlu",
      "uploadError2": "Kļūda pievienojot elementu (nederīgs html tags)",
      "notJpg": "Lūdzu, izvēlieties jpeg foto, lai augšupielādētu",
      "errorNoPhoto": "Izvēlieties attēlu, lai augšupielādētu",
      "errorNoThumbnail": "Izvēlieties sīktēlu, lai augšupielādētu",
      "errorInvalidPicUrl": "Ievadiet derīgu attēla URL. Sākas ar https. Beidzas ar jpg, png, gif vai bmp vai beidziet URL ar '#isImage', lai ignorētu šo noteikumu.",
      "errorInvalidThumbUrl": "Ievadiet derīgu sīktēlu (sākas ar https://, beidzas ar jpg, png, gif vai bmp).",
      "errorInvalidVideoUrl": "Ievadiet derīgu video URL (sākas ar https://)",
      "errorNoName": "Ievadiet nosaukumu šim tūres punktam",
      "errorNoDescription": "Ievadiet uzrakstu šim tūres punktam",
      "errorNoLocation": "Iestatiet izvietojumu šim tūres punktam"
    },
    "builderJS": {
      "noPendingChange": "Nav nesaglabātu izmaiņu",
      "unSavedChangeSingular": "1 nesaglabāta izmaiņa",
      "unSavedChangePlural": "nesaglabātas izmaiņas",
      "shareStatus1": "Tūre nav saglabāta",
      "shareStatus2": "Tūre ir publiski koplietota",
      "shareStatus3": "Tūre ir koplietota ar organizāciju",
      "shareStatus4": "Tūre nav koplietota",
      "popoverDiscard": "Vai esat pārliecināts, ka vēlaties izmest visas nesaglabātās izmaiņas?",
      "yes": "Jā",
      "no": "Nē",
      "popoverLoseSave": "Atverot skatītāju, jūs zaudēsiet visas nesaglabātās izmaiņas",
      "ok": "Labi",
      "popoverSaveWhenDone": "Neaizmirstiet saglabāt, kad jūs pabeidzat",
      "closeWithPendingChange": "Vai tiešām vēlaties apstiprināt darbību? Jūsu izmaiņas tiks zaudētas.",
      "gotIt": "Labi",
      "savingApplication": "Saglabā stāstu",
      "saveSuccess": "Stāsts ir saglabāts",
      "saveError": "Saglabāt neizdevās, lūdzu, mēģiniet vēlreiz",
      "saveError2": "Saglabāšana neizdevās nederīga html taga dēļ vārdā vai aprakstā",
      "saveError3": "Virsraksts nevar būt tukšs",
      "dragColorPicker": "Pārvietot man apkārt<br />vai mainīt manu krāsu",
      "dataWarningExtent": "Jums ir dati web kartes pārklājuma ārpusē. Šie dati netiks izmantoti kā tūres punkti, izmainiet kartes pārklājumu, ja jūs vēlaties tos izmantot.",
      "dataWarningVisibi": "Jūsu Map Tour slānis nav redzams pašreizējā web kartes pārklājumā. Apstipriniet, ka jūsu Map Tour slānis ir redzams ar %MAPSIZE% lielā kartē.",
      "dataWarningEdit": "Rediģēt web karti",
      "dataWarningClose": "Aizvērt",
      "signIn": "Lūdzu, pierakstieties kontā uz",
      "signInTwo": "lai saglabātu stāstu.",
      "switchBM": "Mainīt pamatkarti"
    },
    "organizePopupJS": {
      "messageStart": "Jūs esat izvēlējies izdzēst",
      "messageSinglePoint": "vienu tūres punktu",
      "messageMultiPoint": "tūres punkti",
      "messagePermantRemove": "Tas neatgriezeniski izņems",
      "messageRecord": "ieraksts",
      "messageRecordPlural": "ieraksti",
      "messageConfirm": "no jūsu datubāzes. Vai vēlaties turpināt?",
      "labelButtonShow": "Parādīt",
      "labelButtonHide": "Paslēpt"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Tas neatgriezeniski izdzēstu bildi un sīktēlu",
      "popoverDeleteWarningThumb": "Tas neatgriezeniski izdzēstu sīktēlu",
      "popoverUploadingPhoto": "Augšupielādē bildi un sīktēlu",
      "popoverUploadingThumbnail": "Augšupielādē sīktēlu",
      "popoverUploadSuccessful": "Augšupielāde veiksmīga",
      "popoverUploadError": "Augšupielādes neveiksme, lūdzu, mēģiniet vēlreiz",
      "changePicAndThumb": "Mainīt bildi",
      "changeThumb": "Mainīt sīktēlu",
      "selectPic": "Mainīt mediju",
      "selectThumb": "Mainīt sīktēlu",
      "uploadPicAndThumb": "Lietot"
    },
    "headerJS": {
      "editMe": "Rediģē mani!",
      "templateTitle": "Iestatīt virsrakstu",
      "templateSubtitle": "Iestatīt apakšvirsrakstu",
      "edit": "Labot"
    },
    "crossFaderJS": {
      "setPicture": "Iestatīt bildes virsrakstu",
      "setCaption": "Iestatīt bildes uzrakstu"
    },
    "importPopup": {
      "title": "Importēt",
      "prevBtn": "Atpakaļ",
      "nextBtn": "Nākošais"
    },
    "importPopupHome": {
      "header": "Kur ir jūsu bildes uzglabātas?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "attēli",
      "videos": "video",
      "disabled": "Administrators ir atspējojis šo iezīmi",
      "disabledPortal": "Šim līdzeklim nepieciešams, lai portālam būtu viesošanas serveris. Sazinieties ar portāla ArcGIS administratoru.",
      "header1": "Jūsu attēliem jābūt publiski koplietotiem.",
      "header2": "Imports būs limitēts uz pirmajiem %NB1% %MEDIA%.",
      "emptyDataset": "Kļūda, nav atrastas bildes",
      "footerImport": "Importēt",
      "selectAlbum": "Izvēlieties publisku albumu",
      "selectAlbum2": "Izvēlieties albumu",
      "pleaseChoose": "Lūdzu, izvēlieties",
      "userLookup": "Uzmeklēt",
      "userLookingup": "Meklēšanai",
      "csv": "Atsauce uz CSV",
      "advanced": "Papildus opcijas",
      "advancedScratchLbl": "Sākt jaunu tūri",
      "advancedScratchTip": "Izveidojiet tukšu tūri, kurā varat pievienot tūres punktus. Jūsu multividei jau ir jābūt tiešsaistē. Šī opcija neatbalsta savu attēlu augšupielādi.",
      "advancedCSVLbl": "Importēt tūres datus no CSV faila",
      "advancedCSVTip": "Importējiet savas tūres saturu no CSV faila, kurā iekļautas atsauces uz jūsu tiešsaistes multividi. Šī opcija neatbalsta savu attēlu augšupielādi.",
      "advancedCommonTip": "Nepieciešams, lai jūsu attēli un video jau atrodas tiešsaistē.",
      "select": "Veikt izvēli",
      "locUse": "Lietot bilžu ģeoizvietojumu",
      "locExplain": "Jūs varat nevēlēties izmantot attēla novietojumus, jo tie var būt mantoti no albuma, kā rezultātā visas fotogrāfijas būs vienā un tajā pašā vietā.",
      "locExplain2": "Jūs varat nevēlēties izmantot video novietojumus, jo tie var būt mantoti no lietotāja iestatījumiem, kā rezultātā visi video būs vienā un tajā pašā vietā."
    },
    "viewFlickr": {
      "title": "Flickr imports",
      "header": "Ievadiet jūsu Flickr lietotāja vārdu un izvēlieties albums vai atslēgas vārds, ko importēt.",
      "userInputLbl": "Ievadiet Lietotāja vārdu",
      "signInMsg2": "Lietotājs nav atrasts",
      "selectSet": "Izvēlieties albumu",
      "selectTag": "vai izvēlieties atslēgas vārdu",
      "footerImportTag": "Importēt izvēlēto atslēgas vārdu",
      "footerImportSet": "Importēt izvēlēto albumu"
    },
    "viewFacebook": {
      "title": "Facebook imports",
      "header": "Autentificējaties ar savu Facebook lietotāja kontu vai izmantojat publisko lapu. Privātos albumus var izmantot, lai radītu publisko Map Tour, kas neprasīs Facebook lietotāja autentifikāciju un kas ļaus komentāriem un patīk palikt privātiem.",
      "leftHeader": "Facebook Lietotājs",
      "rightHeader": "Facebook Lapa",
      "pageExplain": "Facebook lapa ir publisks zīmols/produkts vai slavenība, piem., <b>esrigis</b>. Jūs varat saņemt lapas nosaukumu, pēc pirmās '/' lapas URL.",
      "pageInputLbl": "Ievadiet lapas nosaukumu",
      "lookupMsgError": "Lapa nav atrasta"
    },
    "viewPicasa": {
      "title": "Google+ imports",
      "header": "Ievadiet savu e-pasta adresi vai savu ID",
      "userInputLbl": "E-pasta adrese vai Picasa/Google+ ID",
      "signInMsg2": "Konts nav atrasts",
      "signInMsg3": "Nav publiska albuma",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Uzziniet vairāk</a>",
      "howToFind2": "Iekopējiet ciparus starp jebkuras Picasa lapas pirmo un otro '/'"
    },
    "viewCSV": {
      "title": "CSV imports",
      "uploadBtn": "Izvēlieties vai nometiet CSV failu",
      "resultHeaderEmpty": "CSV ir tukšs",
      "resultHeaderSuccess": "Ielādēti %NB_POINTS% punkti",
      "resultHasBeenLimited": "Imports ir limitēts ar pirmo %VAL1% norāda uz %VAL2% ievērot limitu %VAL3% punktus par katru tūri",
      "browserSupport": "Jūsu pārlūks neatbalsta, lai izmantotu CSV jums ir <a href='http://browsehappy.com/' target='_blank'>jāatjaunina jūsu pārlūks</a> vai lietojiet ArcGIS.com web kartes skatītāju (skat. Palīdzību).",
      "errorLatLng": "Platuma un Garuma lauki nav atrasti. Iespējamās platuma vērtības ir: <i>%LAT%</i> un garuma: <i>%LONG%</i>.",
      "errorFieldsExplain": "Ielādēšana neizdevās, jo šādi obligātie lauki nav atrasti",
      "errorFieldsName": "<b>Nosaukums</b> iespējamās vērtības ir: %VAL%",
      "errorFieldsDesc": "<b>Apraksts</b> iespējamās vērtības ir: %VAL%",
      "errorFieldsUrl": "<b>Bildes URL</b> iespējamās vērtības ir: %VAL%",
      "errorFieldsThumb": "<b>Sīktēla URL</b> iespējamās vērtības ir: %VAL%",
      "errorFields2Explain": "Ielādēšana neizdevās, jo CSV neizmanto tos pašus atribūtus, nekā slānis priekš sekojošajiem atribūtiem",
      "errorFields2Name": "<b>Nosaukums</b> lieto %VAL1% vietā %VAL2%",
      "errorFields2Desc": "<b>Apraksts</b> lieto %VAL1%vietā %VAL2%",
      "errorFields2Url": "<b>Bildes URL</b> lieto %VAL1% vietā %VAL2%",
      "errorFields2Thumb": "<b>Sīktēla URL</b> lieto %VAL1% vietā %VAL2%",
      "resultFieldsAll": "Visi atribūti ir importēti",
      "resultFieldsNotAll": "Šādi atribūti nav importēti, jo tie nepastāv kartes slānī",
      "resultFieldsNotAll2": "Sekojošie atribūti tiks importēti",
      "footerNextBtnResult": "Imports uz web karti",
      "footerProgress": "Imports progresā",
      "footerSucceed": "Imports sekmīgs. Ielādē"
    },
    "viewYoutube": {
      "title": "YouTube imports",
      "header": "Ievadiet YouTube lietotāja vārdu, lai atrastu publiski koplietotus video.",
      "pageInputLbl": "Ievadiet YouTube lietotāja vārdu",
      "lookupMsgError": "Lietotājs nav atrasts",
      "howToFind": "Kā atrast YouTube lietotāja vārdu",
      "howToFind2": "Lietotāja vārds ir attēlots zem video",
      "found": "Atrasts",
      "noData": "Nav atrasti publiski video"
    },
    "viewGeoTag": {
      "title": "Izvēlieties un nosakiet izvietojumu jūsu attēliem/video",
      "header": "Izvietotās vienības tiks importētas. Noklikšķiniet uz jebkuriem neizvietotiem vienumiem, kurus vēlaties importēt, lai tos atrastu.",
      "headerMore": "Palīdzība",
      "headerExplain": "Noklikšķinot uz pogas <b>Importēt</b>, tiks importēti tikai attēli vai video, kas uzskaitīti cilnē <b>Atrasts</b>.<br><br> Ģeogrāfiskā novietojuma informācija, kas saglabāta attēlos vai video, tiek importēta automātiski, ja tai var piekļūt. Visas vienības bez ģeogrāfiskā novietojuma ir uzskaitītas cilnē <b>Jāatrod</b>. Lai atrastu šajā cilnē norādīto vienību, noklikšķiniet uz tās un pēc tam kartē noklikšķiniet uz vajadzīgā novietojuma.<br> <br> Lai noņemtu vienību no cilnes <b>Atrasts</b>, lai tā netiktu importēta, noklikšķiniet uz pogas Neimportēt, ko redzēsit, pārvietojot kursoru uz šīs vienības.<br> <br> Padoms: ja jūsu datu nesēja ģeogrāfiskā novietojuma informācija netiek importēta, pārbaudiet sava konta privātuma iestatījumus. Piemēram, Flickr konta iestatījumos pārliecinieties, vai EXIF dati nav paslēpti. Turklāt, ja Flickr privātuma opcija, lai importētu EXIF datus jaunām augšupielādēm, ir izslēgta (pēc noklusējuma) ģeogrāfiskais novietojums netiks saglabātas Flickr jūsu attēliem, ja vien tos neaugšupielādēsit vēlreiz vai manuāli norādīsit to novietojumu Flickr.",
      "leftPanelTab1": "Lai atrastu",
      "leftPanelTab2": "Atrodas",
      "clickOrTap": "Noklikšķiniet uz kartes, lai atrastu",
      "clearLoc": "Notīrīt izvietojumus",
      "clickDrop": "Neimportē",
      "footerImport": "Importēt",
      "footerProgress": "Imports progresā",
      "footerSucceed": "Imports sekmīgs. Ielādē...",
      "loading": "Ielādē",
      "error": "Attēla izvietojuma importēšana neizdevās, ģeoizvietojumi tika ignorēti."
    },
    "initPopup": {
      "title": "Laipni lūdzam Map Tour Veidotājā",
      "prevBtn": "Atpakaļ",
      "nextBtn": "Nākošais"
    },
    "initPopupHome": {
      "header1": "Kur ir jūsu attēli vai video?",
      "header2": "Šis asistents palīdzēs jums veidot Map Tour no attēliem, kas jau glabājas tiešsaistē vai tie tiks importēti jūsu ArcGIS Online for Organizations kontā.",
      "title1": "Tās jau atrodas tiešsaistē",
      "title2": "Man nepieciešams augšupielādēt attēlus",
      "hostedFSTooltip": "Augšupielādējiet attēlus un saglabājiet tos savā tūrē (video saturs netiek neatbalstīts).",
      "hostedFsNA": "Jums jābūt publicētājam vai jādarbojas citā lomā, kam ir tiesības publicēt viesotus elementu slāņus. Sazinieties ar ArcGIS administratoru.",
      "hostedFsNA2": "Pieejams tikai ar ArcGIS Online abonementu. <a href='%LINK%'>Reģistrēties bezmaksas izmēģinājumam</a>",
      "footer1": "Kad tas ir izdarīts, neaizmirstiet dalīties ar jūsu Map Tour ar jūsu auditoriju, izmantojot aplikācijas vienības lapu.",
      "footer3": "Lejupielādēt CSV šablonu",
      "footer4": "\"Saglabājiet kā\" ja tas nelejupielādējas",
      "footer4bis": "Izmantojiet labo pogu un\"Saglabāt kā\" ja nesākas lejupielāde",
      "footer5": "Uzziniet vairāk",
      "footerProgress": "Izveide notiek",
      "footerSucceed": "Izveide sekmīga. Ielādē..."
    },
    "helpPopup": {
      "title": "Palīdzība",
      "close": "Aizvērt",
      "tab1": {
        "title": "Ievads",
        "moreInfo": "Lai iegūtu papildinformāciju",
        "infoSites": "Apmeklējiet <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>Kartes tūres sadaļu</a> <a href='https://storymaps.arcgis.com' target='_blank'>Esri Kartes stāsta tīmekļa vietnē.</a>",
        "mtFAQ": "Skatīt <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Kartes tūres BUJ (FAQ).</a>",
        "myStories": "Varat pārvaldīt savas Kartes tūres un pārbaudīt, vai tajās nav radušās kļūdas — apmeklējiet tīmekļa vietnes sadaļu <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Mani stāsti</a>.",
        "div1": "Map Tour šablons ir noformēts, lai prezentētu ģeogrāfisku informāciju, ja ir pārliecinoši fotogrāfiskie vai mediju elementi stāstam, ko jūs vēlaties pastāstīt.",
        "div2": "Veidne rada pievilcīgu, viegli izmantojamu tīmekļa lietotni, kas ļauj kartē numurētā secībā attēlot nelielu vietu kopu, ko lietotāji var pārlūkot. Veidne ir paredzēta izmantošanai jebkurā tīmekļa pārlūkprogrammā jebkurā ierīcē, tostarp viedtālruņos un planšetdatoros. <br /><br />",
        "div42": "Lai skatītu citu lietotāju veidoto kartes tūru piemērus, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>apmeklējiet galeriju</a> <a href='https://storymaps.arcgis.com/' target='_blank'>Kartes stāstu tīmekļa vietnē</a>. Varat arī sekot mums Twitter (<a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>).",
        "div5": "Mēs vēlētos dzirdēt jūsu atsauksmes. Informējiet mūs par problēmām un jums nepieciešamajiem jaunajiem elementiem, apmeklējot Story Maps forumu <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet.</a>"
      },
      "tab2": {
        "title": "Dati",
        "div1": "Veidojot kartes tūri, ir svarīgi izvēlēties vietu, kur tiks glabāti attēli. Kartes tūrē varat izmantot attēlus, kas saglabāti fotoattēlu kopīgošanas servisos vai jebkurā tīmekļa serverī, kā arī varat izmantot attēlus, kas augšupielādēti no diska.",
        "div1a": "Aplūkojiet pēdējo sadaļu šajā tabulatorā, lai uzzinātu par atbalstītajiem attēlu un video formātiem.",
        "div2": "Interaktīvais veidotājs dod jums divas iespējas apstrādāt attēlus jūsu Map Tour:",
        "div3": "<ul><li>Jūs varat izmantot <b>attēlus, kas jau ir tiešsaistē</b>, piemēram, attēlus Flickr vai Google+, vai attēlus, kas tiek glabāti jūsu tīmekļa serverī. Uz šiem attēliem tiks izveidotas atsauces jūsu lietotnē Map Tour, izmantojot to vietrāžus URL.</li><li>Jūs varat arī<b>augšupielādēt fotogrāfijas no sava datora</b> tieši lietotnē Map Tour. Šādai augšupielādes opcijai ir nepieciešams ArcGIS uzturēšanas abonements un izdevēja vai administratora tiesības, jo jums automātiski tiks izveidots viesots elementu serviss, kurā fotogrāfijas tiek saglabātas kā pielikumi.</li></ul>",
        "div4": "Galvenie lietošanas gadījumi ir:",
        "div4b": "<b>Jūsu fotoattēli vēl netiek viesoti</b>, un jums ir ArcGIS abonements: viesots elementu serviss ir labākā izvēle. Tāpat kā publiski pieejamos fotoattēlu kopīgošanas servisos, arī šeit jūsu attēli tiks optimizēti, lai to ielāde būtu ātra, turklāt iegūsiet piekļuvi visām ArcGIS Platform administrācijas un datu pārvaldības iespējām.",
        "div5": "<b>Jūs neesat Organizācijas biedrs</b>: Jums vispirms jāaugšupielādē savas bildes foto koplietošanas mājas lapā, vai uz jūsu web serveri. Tad veidotājs palīdzēs izmantot šīs bildes, kas turpmāk tiks viesotas savā oriģinālajā izvietojumā.",
        "div6": "<b>Jūs meklējat, lai atkārtoti lietotu esošo Feature Service</b> kas glabā jūsu bildes kā piesaistes, vai kas atsaucas uz ārējām bildēm: skatiet detalizētāku nodaļu apakšā.",
        "div7": "<b>Jūs esat iepriekšējās versijas lietotājs</b> Map Tour šablonam un jau ir jūsu CSV, kas atsaucas jūsu bildēm un sīktēliem: jums būs iespēja importēt un uzlabot savus datus. Veidotājs atbalsta tikai CSV, kas lieto plat/gar laukus; uz adresēm balstīts CSV var tikt turpināts lietot caur jūsu web karti (skatīt nodaļu zemāk).",
        "div8": "Importē no tiešsaistes foto koplietošanas servisu",
        "div9a": "Facebook atbalsts ir pārtraukts, ${learn}.",
        "learn": "uzzināt vairāk",
        "div9": "Importa operācijas atsaucas uz attēliem, kas tiek viesoti, saglabājot to URL web kartes elementu kolekcijā. Attēli netiek saglabāti ArcGIS Online. Ja viesotiem attēliem nevar piekļūt, tie nebūs pieejami Map Tour un jūs redzēsiet 'Attēls nav pieejams' attēlu. Atkarībā no attēlu servisu sniedzēja, Map Tour tiks vai netiks importēts nosaukums, apraksts un attēla izvietojums. Šie atribūti tiek glabāti web kartē un jebkādi labojumi uz tiešsaistes servisiem netiks atspoguļoti Map Tour.",
        "div10": "Uzglabā bildes uz web servera",
        "div11": "Ja izvēlaties uzņemt attēlus savā tīmekļa serverī (tā vietā, lai piekļūtu attēliem Flickr vai Google+, vai augšupielādējot tos tieši savā tūrē), jums būs manuāli jāizveido attēlu sīktēli. Pilnas izšķirtspējas attēlu izmantošana sīktēlam izraisīs nekvalitatīvu veiktspēju. Skatiet šos <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>BUJ</a>, lai saņemtu padomus par attēlu izmēra maiņu, ja varēsit tiem tieši piekļūt tīmeklī, izmantojot vietrāžus URL.",
        "div12": "Esošu ĢIS datu izmantošana",
        "div13": "Jebkuru elementu servisu, CSV failu vai shape failu, kurā ietverti punkti, var izmantot kā Map Tour datu avotu, ja tas ietver lietojumprogrammai nepieciešamo lauku kopu. Datu avots ir jāpievieno kā ArcGIS tīmekļa kartes slānis un pēc tam jākopīgo karte, izveidojot Map Tour ekskursiju.",
        "div14": "Tālāk norādītas atbalstītās lauku nosaukumu vērtības (vērtības nav reģistrjutīgas).",
        "div151": "Nosaukums",
        "div152": "Apraksts",
        "div153": "Bilde",
        "div154": "Sīktēls",
        "div155": "Krāsa ",
        "div16": "Ja lietotne neatrod atbilstošus laukus lietojot elementu servisu, skatītājs nestrādās, līdz jūs konfigurēsiet laukus lietošanai caur veidotāju. CSV un shape failu slāņiem, kas pievienoti web kartei, jābūt visiem nepieciešamajiem laukiem, pretējā gadījumā veidotājs nestrādās.",
        "div162": "Izmantojot elementu servisu kas glabā attēlus kā piesaistes, <b>tiks izmantoti tikai tie elementi kuriem ir divas piesaistes</b>. Pirmā piesaiste definē galveno attēlu, otrā definē sīkattēlu.",
        "div17": "Attēlu un sīktēlu lauki ir obligāti elementu servisam bez piesaistēm un pēc izvēles (bet ļoti ieteicami) elementu servisam ar piesaistēm. Ja jūsu servisam ir iespējotas piesaistes, veidotājs ļaus jums augšupielādēt bildes kā piesaistes. Ja nē, jums būs tikai iespēja rediģēt bilžu un sīktēlu URL.",
        "div172": "Ja tādi būs, vienmēr tiks izmantoti attēlu un sīkattēlu lauki un elemetu servisa piesaistes netiks pieprasītas.",
        "div173": "Piemēra CSV un shape faili var tikt lejupielādēti no",
        "div174": "Lai iegūtu papildinformāciju par esošo GIS datu izmantošanu, skatiet šos <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>BUJ</a>.",
        "div18": "Rada viesotu elementu servisu no CSV vai shape faila",
        "div19": "Kad jūs izveidojat elementu servisu no CSV vai shape faila, piesaistes nav iespējotas pēc noklusējuma. Lai tās iespējotu, atveriet elementu servisa detaļu lapu, noklikšķiniet uz nelielas bultiņas slāņa sadaļā, un jūs redzēsiet šo opciju. Pēc tam Map Tour turpinās izmantot attēlus un sīktēlus, uz ko jūs atsaucaties caur atribūtiem. Pēc izvēles, ja jūs vēlaties augšupielādēt savas bildes kā elementu servisa piesaistes, jums būs iespēja to darīt caur divām pogām uz bildes paneļa (\"Mainīt attēlu\" un \"Mainīt sīkattēlu\").",
        "div20": "Atbalstītie attēlu un video formāti",
        "div21": "Ja piekļūstat attēliem Flickr vai Google +, Kartes tūre automātiski piekļūst šiem attēliem kā. jpg failiem. Ja attēlus augšupielādējat Kartes tūres veidotājā, attēliem ir jābūt. jpg vai. jpeg formātā. Ja atsaucat attēlus tieši tīmeklī, izmantojot savus vietrāžus URL, atbalstītie attēlu formāti ir .jpg, .jpeg, .png, .gif un .bmp. YouTube video tiek atbalstīti tieši.",
        "div22": "Map Tour veidne nesatur videopleijeri, tādēļ jāizmanto ārējs videopleijers, ko nodrošina video viesošanas serviss (atrodiet opciju lai iedarinātu video un iekopētu doto URL dotajā kodā) Ja vēlaties viesot video pats, jūs varat izveidot HTML lapu, kas satur videopleijeri, piemēram, <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Ineraktīvais veidotājs nenodrošina dialogu, lai iekļautu video, gadījumos kad izmanto elementu servisu ar piesaistēm, bet ir iespējams to izdarīt rediģējot datus ārpus inerkatīvā veidotāja. Arcgis.com kartes pārlūkā, ja modificējat attēla laukus, lai norādītu ārēju video, un pievienojat speciālu parametru URL beigās (#isVideo), jūsu medijs tiks uzkatīs par video.",
        "div24": "Atcerieties, ka jums nepieciešami divas derīgas attēla piesaistes vai punkts netiks izmantots. Nav iespējams izmantoto video, izmantojot elementu servisa piesaistes bez attēla un sīkattēla laukiem."
      },
      "tab3": {
        "title": "Pielāgošana",
        "div1": "Veidotājs nodrošina vairākas pielāgošanas opcijas, kas ir pieejamas, izmantojot SETTINGS pogu, kas ir augšējā panelī. Ja jūs nevarat atrast sagaidīto opciju, mēs nodrošinām arī lejupielādējamu versija, ko varat izvietot uz jūsu web servera un uzlabot, lai atbilstu jūsu vajadzībām.",
        "div2": "Mēs iesakām izmantot viesoto versiju, ja vien:",
        "div3": "<li>Tas nepiedāvā UI pielāgošanu, kādu vēlaties, piemēram, izmantojot galvenes fona attēlu</li><li>Jūs esat programmētājs un jūs vēlaties uzlabot aplikāciju.</li>",
        "div4": "Lejupielādējamā versija var tikt konfigurēta izmantojot web karti vai web kartēšanas aplikācijas identifikatoru. Galvenie lietošanas gadījumi ir:",
        "div41": "Jūs veidojat kartes tūri izmantojot interaktīvo veidotāju viesotā vidē un konfigurējat šablonu ar web kartēšanas aplikācijas identifikatoru. Tiks piemēroti iestatījumi, kurus jūs definējat ar interaktīvo veidotāju.",
        "div42": "Jūs veidoja web karti ārpus interaktīvā veidotāja un konfigurējat šablonu ar web kartes identifikatoru. Jums būs jālasa dokumentācija, lai uzzinātu kā konfigurēt šablonu.",
        "div43": "Atcerieties, ka interaktīvais veidotājs ir pieejams lejupielādēšanas versijā, bet ar dažiem tehniskiem ierobežojumiem pārlūkam Internet Explorer vecākām verijām par 10.",
        "div5": "Lai lejupielādētu pašu jaunāko šablona versiju un uzzinātu vairāk kā to izmantot, apmeklējiet <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub projektu lapa</a>."
      },
      "tab4": {
        "title": "Padomi",
        "div0": "Atbalstītie pārlūki",
        "div0a": "Map Tour pārlūks tiek atbalstīts uz IE8 un augstāka versija. Interaktīvais veidotājs tiek atbalstīts uz IE9 un augstāka versija. Mēs veicam aktīvu testēšanu visos galvenajos pārlūkos, bet gadījumā ja sastopaties ar kādām grūtībām, iesakām izmantot Chrome pārlūku.",
        "div0b": "Ja jūs saskaraties ar grūtībām, lūdzu ziņojiet. Tikmēr veidojot Map Tour izmantojot CSV šablonu jūs minimizēsiet jūsu mijiedarbību ar veidotāja interfeisu.",
        "div1": "Attēli",
        "div2": "Lai gan vienā Kartes tūrē var izmantot dažādu izmēru, formu un orientācijas attēlus, mēs iesakām attēlu ainavorientāciju, nevis portreta orientāciju. Attēli ar 4:3 proporciju atbilst vislabāk. Trīs paneļos un integrētajos izkārtojumos, kuros virsraksts pārklājas ar attēlu, izmantojot portreta orientāciju, attēls var tikt aizēnots ar virsrakstu. Trīs paneļos un integrētajos izkārtojumos ieteicams izmantot vienādu izmēru un formu visiem attēliem, ja iespējams. Šādā veidā, dodoties tūrē, lietotāja uzmanību nenovērsīs dažādā izmēra attēli.",
        "div2a": "Mēs iesakām maksimālo attēla izmēru 1000 pikseļi platumā un 750 pikseļi garumā galvenajam attēlam un 140x93 sīkattēlam.",
        "div3": "Formatē jūsu uzrakstu tekstu, izmantojot HTML tagus",
        "div4": "Varat ievadīt HTML birku parakstos, lai definētu formatējumu un saites. Piemēram, zaļu hipersaiti var pievienot ar šādām birkām:",
        "div4aa": "<b> Izveidojiet titullapu Sāna paneļa tūrei </b> <br> Sāna paneļa izkārtojums atbalsta izvēles titullapu, lai varētu piesaistīt auditorijas jūsu uzmanību ar lielisku izskatu, pilnekrāna attēlu. Lai konfigurētu Sāna paneļa tūres titullapu, vispirms pievienojiet dažus vai visus punktus. Pēc tam noklikšķiniet uz pogas Organizēt, un dialoglodziņā, kas parādās, pārliecinieties, vai tūres punkts, ko vēlaties izmantot, lai definētu titullapu, ir pirmais punkts jūsu tūrē. Pēc tam noklikšķiniet uz lodziņa “Izmantot pirmo punktu kā titullapu” šajā dialoglodziņā. Pirmā tūres punkta nosaukums kļūs par titullapā redzamo virsrakstu, šī punkta virsraksts kļūs par apakšvirsrakstu, un šī punkta attēls tiks izmantots kā titullapas attēls. Titullapā video netiek atbalstīts. Lai iegūtu papildinformāciju, skatiet šos <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>BUJ</a>.</a>",
        "div4a": "Ierakstiet labu apakšvirsrakstu jūsu tūrei",
        "div4b": "Nepieciešams laiks, lai uzrakstītu neatvairāmu savas tūres apakšvirsrakstu. Apakšvirsraksts ir labs veids, kā uzzīmēt cilvēkus savā tūrē un pastāstīt, ko viņi tajā atklās. Tā ir arī laba vieta, kur pastāst savai auditorijai par valsti vai zemi, kurā atrodas tūre. Piemēram, nepieņemiet, ka cilvēki zina, kur atrodas pilsēta vai mazpilsēta jūsu tūrē. Neveidojiet apakšvirsrakstus pārāk garus. Ja nespējat izdomāt labu apakšvirsrakstu, atstājiet to tukšu. Atšķirībā no Trīs paneļiem un Integrētajiem izkārtojumiem, Sāna paneļa izkārtojums neatbalsta apakšvirsrakstu galvenē. Ja Sāna paneļa izkārtojumā izmantojat titullapas opciju, titullapā tiek parādīts pirmā punkta virsraksts, un tas kalpo par jūsu tūres apakšvirsrakstu.",
        "div5": "Atbalstot slāņus",
        "div6": "Ja nepieciešams, variet paplašināt kontekstu, pievienojot papildu atbalsta slāņus. Šie slāņi var saturēt citus ģeogrāfiskos elementus, kurus vēlaties parādīt kartē papildus Kartes tūres punktiem, piemēram, pētāmā teritorija, pastaigu vai braukšanas maršruti, kas savieno jūsu tūres punktus utt. Kartes tūres veidne parāda šos papildu atbalsta slāņus, izmantojot tīmekļa kartē norādīto simbolu, bet visi slāņiem definētie uznirstošie logi netiek atbalstīti. Lai tūrei pievienotu atbalsta slāņus, saglabājiet savu darbu un aizveriet Kartes tūres veidotāju. Pēc tam atveriet tūrē izmantoto tīmekļa karti. To var atrast sadaļā ArcGIS Mans saturs vai tīmekļa vietnes Kartes stāsti sadaļā Mani stāsti.",
        "div7": "Turiet jūsu ceļojumu īsu un saldu",
        "div8": "Tūres limits ir 99 punkti. Protams, vairums Map Tours, būs ievērojami īsāks nekā minētie 99 punkti. Nesagaidiet, ka jūsu auditorija vēlas apskatīt pārāk daudz tūres punktus. Jūs variet uzkatīt šo tēmu par saistošu, bet nepieņemiet, ka pārējais vairums arī!",
        "div10": "Iedarināts režims",
        "div11": "Ja vēlaties iedarināt sagatavi citā tīmekļa vietnē ar iframe, pievienojot izvēles parametru \"&embed\" URL saites beigās tiks noņemta galvene.",
        "div12": "Neizmantojiet šauru iFrame platumu, kas izraisa kartes tūres pārslēgšanos uz savu adaptīvo mazā displeja skatu, kas ir tas pats skats, kas tiek izmantots mobilajās ierīcēs. Lai lietošanu padarītu maksimāli vienkāršu, brīdī, kad veicat kartes iegulšanu, mēs vienmēr iesakām nodrošināt saiti blakus iegultajai tūrei, lai lietotāji var palaist tūri pilnekrāna režīmā."
      },
      "tab5": {
        "title": "Publicē",
        "div1": "Kad esat pabeiguši, neaizmirstiet koplietot jūsu Map Tour ar jūsu auditoriju, izmantojot KOPLIETOT pogu vai ArcGIS Online aplikācijas vienības lapā.",
        "div2a": "Koplietot tūri caur veidotāju",
        "div2b": "KOPLIETOT poga jauninās aplikāciju un web kartes vienības. Ja jūsu tūres dati tiek glabāti elementu servisa vienībā, tā arī tiks jaunināta. Ja esat pievienojis citus slāņus izmantojot ArcGIS.com kartes skatītāju, tie netiks jaunināti. šis var rezultēt, ka tūre netiek koplietota kā jūs sagaidījāt. Vienības, kurām jau ir nepieciešamās (vai vairāk) privilēģijas netiks jauninātas.",
        "div2c": "Koplietot tūri izmantojot ArcGIS Online",
        "div2d": "Kad jūs koplietojat aplikāciju izmantojot ArcGIS Online, ja nepieciešams tiks pieprasīts jaunināt jebkurus atkarīgus resursus  (web karti, elementu servisu, noformējuma slānis), kas nav koplietoti tādā pat veidā. Ja kartes tūre ir publiska un viens no tās resursiem nav koplietots ar jūsu auditoriju, lietotāji tiks pāradresēti uz ArcGIS Online pieteikšanās lapu.",
        "div3t": "Elementu servisa drošība",
        "div3a": "Ja jūs izmantojat viesotu elementu servisu, izveidotu caur Map Tour veidotāju, aplikācija pārvalda servisa drošību priekš jums un jums paliks tikai rediģēšanas privilēģijas, pat tad, ja jūs koplietosiet servisu publiski.",
        "div3t2": "Pirms koplietot jūsu tūri ar publiku.",
        "div3": "Pārliecinieties, ka tūre darbojas, ja jūs neesat pieteicies savā ArcGIS.com kontā. URL, kuru jūs izmantosiet, nedrīkst pārsūtīt uz pieteikšanās lapu vai veidotāja režīmu.",
        "div4": "Tā ir laba doma apskatīt kā izskatās jūsu kartes tūre uz iPad, kas atrodas ainavas orientācijā, lai pārliecinātos ka tā izkatās labi uz šīs populārās ierīces. Tas palīdzēs jums ieraudzīt vai virsraksti nenosedz pārāk daudz no attēla. Tas arī ļaus ieraudzīt vai jūsu apakšvirsraksts iederas un nav pārāk garš vai tas netiek apgriezts.",
        "div5a": "Ieteikumi meklēšanai",
        "div5b": "Lai palīdzētu cilvēkiem atrast jūsu kartes tūri ArcGIS Online, mēs iesakām pievienot tagu 'kartes tūre' jūsu aplikācijas vienības lapā (nevis jūsu web kartes vienības lapā), tā pat kā pavalsts vai provinces, kur jūsu tūre atrodas, tagus, valsts nosaukumu, ja tā atrodas ārpus ASV un tematiskos tagus, kā piemēram, publiskā māksla, tūristu ceļvedis, vēsturiskās vietas. Šie tagi palīdzēs arī mums- Esri atrast lieliskus piemērus tūrēm, kuras varam attēlot galerijās un veicināt sociālajos tīklos. Tāpat iesakām augšupielādēt skaistus sīkattēlus aplikācijas vienības lapā, kā piemēram, tūres mazus sīkattēlus vai kādu no tās attēliem. Šis attēls tiek lietots automātiski, ja jūsu kartes tūre tiek pievienota ArcGIS Online galerijai."
      }
    },
    "share": {
      "firstSaveTitle": "Tūre ir saglabāta",
      "manageStory": "Pārvaldiet savu stāstu",
      "manageStoryA1": "Padoms: Varat izmantot %LINK1%, lai pārbaudītu savu stāstu uz kļūdām, mainītu tā koplietošanu, padarītu to par labu sociālajos medijos utt. Uzziniet vairāk par Maniem stāstiem %LINK2%.",
      "manageStoryA1V1": "Mani stāsti",
      "manageStoryA1V2": "šeit",
      "shareTitle": "Koplietot jūsu tūri",
      "sharePrivateHeader": "Jūsu tūre nav koplietota, vai vēlaties to koplietot?",
      "sharePrivateBtn1": "Koplietot publiski",
      "sharePrivateBtn2": "Koplietot ar Organizāciju",
      "sharePrivateProgress": "Notiek koplietošana...",
      "sharePrivateErr": "Neizdevās koplietot, mēģiniet vēlreiz vai",
      "sharePrivateOk": "Kopīgošana atjaunināta, ielādē...",
      "sharePreviewAsUser": "Priekšskatījums",
      "shareHeader1": "Jūsu tūre ir <strong>publiski pieejama</strong>.",
      "shareHeader2": "Jūsu tūre ir pieejama jūsu organizācijas biedriem (nepieciešama pieteikšanās).",
      "shareLinkHeader": "Koplietot jūsu tūri",
      "shareLinkOpen": "ATVĒRTS",
      "shareA1": "Izmantojiet %SHAREIMG% <a href='%LINK1%' target='_blank'>aplikācijas vienības lapā</a>. Ja vēlaties atcelt Web kartes kopīgošanu, izmantojiet <a href='%LINK2%' target='_blank'>Web kartes vienības lapu</a>.",
      "shareWarning": "%WITH% koplietošana ir atspējota, jo jūs neesat <a href='%LINK%' target='_blank'>web kartes</a> īpašnieks.",
      "shareWarningWith1": "publiski",
      "shareWarningWith2": "publiski un organizācijā",
      "viewStory": "Skatīt stāstu"
    },
    "locator": {
      "error": "Atrašanās vieta nav pieejama"
    },
    "saveErrorSocial": {
      "title": "Sociālās multivides kopīgošanas atjaunināšana",
      "panel1": "Ir uzlabots jūsu stāsta izskats sociālajā multividē, bet jūsu ArcGIS Web lietotnes vienības virsraksts atšķiras no stāsta virsraksta.",
      "panel1tooltip": "Kad būsiet definējis virsrakstu, kopsavilkumu un sīktēla attēlu, jūsu stāsts izskatīsies šādi:",
      "panel2": "Kādu virsrakstu vēlaties izmantot sociālajā multividē:",
      "panel2q1": "Stāsta virsraksts (ieteicams)",
      "panel2q1tooltip": "Ja izvēlēsieties šo opciju, vienības virsraksts tiks modificēts tā, lai atbilstu stāsta virsrakstam, un veidotājā tiks sinhronizētas tālākās izmaiņas.",
      "panel2q2": "Vienības virsraksts",
      "panel3": "Ja sociālajā multividē vēlaties vēl vairāk uzlabot stāsta izskatu, izmantojiet ${MYSTORIES}, lai pievienotu kopsavilkumu un sīktēla attēlu.",
      "panel4": "Vairs nerādīt brīdinājumus par šo stāstu",
      "mystories": "Mani stāsti",
      "btnSave": "Saglabāt"
    },
    "bannerNotification": {
      "learnMore": "Uzzināt vairāk",
      "close": "Aizvērt",
      "dontShowAgain": "Nerādīt šo ziņojumu vēlreiz"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Svarīgs ziņojums par tīmekļa drošību un Kartes stāstiem (Story Maps)",
      "s1h1": "Esri uzlabo Kartes stāstu drošību",
      "s1p1": "Jūsu Kartes stāsti dzīvo tīmeklī, un tīmekļa kopiena vienmēr strādā, lai nodrošinātu un uzlabotu drošību. HTTPS, kas nodrošina drošu savienojumu ar internetā pārraidītu saturu, tiek parādīts kā paredzētais veids, kā piekļūt tīmekļa saturam. Lielākā daļa moderno pārlūku tagad parāda brīdinājuma ziņojumus, ja tiek izmantots HTTP, nevis HTTPS. Šī jaunā standarta dēļ mēs stingri iesakām izmantot HTTPS saites Kartes stāstu autorēšanai un koplietošanai, kā arī izmantot HTTPS vietrāžus URL, iegulstot tīmekļa saturu vai sasaistot ar attēliem Kartes stāstā.",
      "s1p2": "Praktiski runājot, tas nozīmē, ka Kartes stāstam un visam tā saturam (ieskaitot attēlus, slāņus, iegultās lietotnes un tīmekļa vietnes), ir jānodrošina piekļuve, izmantojot saites, kas sākas ar HTTPS, nevis HTTP. Tas nodrošina labāko pieredzi jūsu lasītājiem, jo lielākā daļa tīmekļa pārlūku norāda, ka jūsu stāsti ir droši.",
      "s2h1": "Kas man jādara?",
      "s2p1": "Esri strādā, lai padarītu to par vienkāršu pāreju Kartes stāsta autoriem un lasītājiem. Kartes stāstu veidotājos un Manos stāstos ir pieejami rīki, kas jums palīdzēs atrast nedrošo saturu (HTTP) jūsu stāstos un sniegs ieteikumus, kā to risināt. Lūdzu, pārbaudiet savus stāstus uz nedrošu saturu un pēc iespējas ātrāk atjauniniet HTTPS.",
      "action1": "Aizvērt",
      "action2": "Pārbaudīt manus stāstus tūlīt",
      "action3": "Uzziniet vairāk"
    },
    "embedBar": {
      "share": "Kopīgošana",
      "fullScreen": "Pilnekrāna režīms",
      "enlarge": "Palielināt",
      "newTab": "Atvēriet jaunā cilnē",
      "tagline": "Kartes stāsts",
      "exitFullScreen": "Iziet no pilnekrāna režīma"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Vai varam jums kaut ko pajautāt? Tas palīdzēs veidot Kartes stāstu nākotni.",
      "s1h1": "Dalieties savās domās, veidojiet nākotni",
      "s1p1": "Jūsu ieguldījums ir viens no mūsu svarīgākajiem atsauksmju avotiem, pastāstot vairāk, jūs palīdzēsiet mums uzlabot Kartes stāstus. Mēs būtu pateicīgi, ja jūs varētu piedalīties šajā trīs minūšu aptaujā.",
      "s2p1": "Kā vienmēr, paldies, ka izmantojat Esri Kartes stāstus!",
      "action1": "Aizvērt",
      "action2": "Aizpildīt aptauju"
    },
    "licenseChange2018": {
      "noAccess": "Jūsu kontam (%USER_NAME%) nav licences, lai atvērtu Kartes stāstu, kas nav publisks. Pieprasiet savas organizācijas administratoram piešķirt jums lietotāja veidu, kurā iekļauts Story Map vai papildinājumlietotņu Essential Apps licence."
    }
  }
});