define(
	 ({
		viewer: {
			loading: {
				step1: "IELĀDĒ APLIKĀCIJU",
				step2: "IELĀDĒ DATUS",
				step3: "IZPILDA TŪRI",
				loadBuilder: "PĀRSLĒGT UZ BUILDER MODE",
				redirectSignIn: "NOVIRZA UZ PIERAKSTĪŠANĀS LAPU",
				redirectSignIn2: "(pēc pierakstīšanās jūs tiksiet novirzīti uz šejieni)",
				fail: "Atvainojiet, Map Tour ielādēšanas neveiksme",
				failButton: "Atkārtot"
			},
			errors: {
				boxTitle: "Kļūda",
				portalSelf: "Fatāla kļūda: neizdevās iegūt portāla konfigurāciju",
				invalidConfig: "Fatāla kļūda: konfigurācijas neveiksme",
				invalidConfigOwner: "Fatāla kļūda: konfigurācijas neveiksme (nepieciešams autorizēts īpašnieks)",
				invalidConfigNoWebmap: "Fatāla kļūda: konfigurācijas neveiksme (nav norādīta web karte vai aplikācijas identifikators index.html failā)",
				createMap: "Nevar izveidot karti",
				invalidApp: "Fatāla kļūda: aplikāciju nevar ielādēt",
				noLayer: "Web karte nesatur derīgu datu slāni priekš Map Tour.",
				noLayerMobile: "Laipni lūdzam Map Tour web aplikācijā. Aplikācija nav konfigurēta. Map Tour veidotājs netiek atbalstīts uz mobilajām ierīcēm.",
				noLayerView: "Laipni lūdzam Map Tour web aplikācijā.<br />Aplikācija nav vēl konfigurēta.",
				appSave: "Kļūda, saglabājot web aplikāciju",
				mapSave: "Kļūda, saglabājot web karti",
				featureServiceLoad: "Kļūda ielādējot elementu servisu",
				notAuthorized: "Jums nav atļauts piekļūt šai aplikācijai",
				oldBrowserTitle: "Pārlūks netiek pilnībā atbalstīts",
				noBuilderIE8: "Map Tour veidotājs neatbalsta Internet Explorer pirms 9 versiju.",
				ie10Win7Explain: "Map Tour interaktīvais veidotājs nav atbalstīts ar Internet Explorer 10 uz Windows 7, kad datu avots ir Feature Service ar piesaistēm. Lai lietotu Feature Service ar piesaistēm, jums vajag <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuāli piespiest dokumenta režīmu uz Internet Explorer 9 standartu</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>pazemināt uz Internet Explore 9</a> vai uzlabot uz Windows 8.",
				oldBrowserExplain: "Šis pārlūks neatbalsta automātisku sīktēlu radīšanu no attēliem, ko jūs augšupielādējat jūsu map tour. Jūs varat izveidot map tour, izmantojot šo pārlūku, bet jums būs jāsniedz atsevišķs sīktēls par katru no augšupielādētiem attēliem .",
				oldBrowserExplain2: "Lai uzlabotu jūsu pieredzi, <a href='http://browsehappy.com/' target='_blank'>jaunina jūsu pārlūku</a> vai <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivizē Google Chrome Frame priekš Internet Explorer</a>.",
				oldBrowserExplain3: "The Map Tour veidotājs nedarbojas ar Internet Explorer 10 uz Windows XP.",
				oldBrowserClose: "Aizvērt"
			},
			mobileHTML: {
				showIntro: "RĀDĪT VIRSRAKSTU",
				hideIntro: "PASLĒPT VIRSRAKSTU",
				navList: "Saraksts",
				navMap: "Karte",
				navInfo: "Mediji",
				introStartBtn: "Starts"
			},
			desktopHTML: {
				storymapsText: "Stāstu karte",
				builderButton: "Pārslēgties uz veidotāja režīmu",
				facebookTooltip: "Koplietot Facebook",
				twitterTooltip: "Koplietot Twitter",
				bitlyTooltip: "Iegūt īso saiti",
				bitlyStartIndex: "Saite uz pašreizējo vietu"
			},
			builderHTML: {
				panelHeader: "APLIKĀCIJAS KONFIGURĀCIJA",
				buttonSave: "SAGLABĀT",
				buttonSettings: "Iestatījumi",
				buttonShare: "Koplietot",
				buttonView: "Skata režīms",
				buttonItem: "Atvērt web aplikācijas vienību",
				buttonHelp: "Palīdzība",
				buttonOrganize: "Organizē",
				buttonAdd: "Pievienot",
				buttonImport: "Importēt",
				buttonImportDisabled: "Imports nav iespējams, lietojot  Feature Service ar piesaistēm",
				dataEditionDisabled: "Datu rediģēšana ir atspējota CSV datu avotam",
				dataSourceWarning: "Map Tour datu slānis ir mainījies. Ja elementu ID nav tāds pat, jums jāatiestata kārtība un slēptie punkti caur <b>Organizēt</b>. Ja atšķiras lauku nosaukumi, jums jāatiestata lauku iestatījumi zem <b>datu cilnes Iestatījumos</b>.",
				organizeWarning: "Viens vai vairāki punkti pievienoti ārpus interaktīvā veidotāja ir paslēpti.",
				dataPicError0a: "Ši tūre ietver <b>%NB%</b> neatbisltošu bildes URL.",
				dataPicError0b: "Šī tūre var ietvert <b>%NB%</b> neatbilstošu bildes URL.",
				dataPicError1: "Map Tour tagad pieprasa, lai attēla URL beidzas ar vienu no sekojošiem paplašinājumiem: .jp(e)g, .png, .gif vai .bmp.",
				dataPicError2: "Šī prasība neietekmēs jau eksistējošās publicētās Map Tour. Lai gan, lai izmantotu inerkatīvo veidotāju, jums jāatrisina URL jautājums, veicot vienu no divām darbībām:",
				dataPicError3: "Rediģēt URL",
				dataPicError4: "Tas pievienos <i>#isImage</i> neatbalstītā URL galā. Lielākā daļa serveru atbalsta URL pielikumus. Lai gan, līdzko jūs esat veikuši šo darbību, jums jāpārliecinās, ka koriģētā attēla URL funkcionē, naviģējot caur punktiem. Ja katrs attēls ielādējas, jūs varat saglabāt Map Tour. Ja <b>attēli neielādējas, nesaglabājiet Map Tour</b>. Tā vietā pārlādējiet veidotāju un veiciet otru darbību.",
				dataPicError5: "Limitēt tūri uz attēliem",
				dataPicError6: "Ši izvēlne liks uzkatīt visus URL par attēliem, bet nebūs iespējams pievienot video izmantojot interaktīvo veidotāju. Ši darbība ir atgriezeniska, ja jūs izlemsiet pievienot video nākotnē.",
				dataPicError7: "Map Tour ir ierobežots lietot attēlus, video nevar tikt izmantots. Ja izvēlaties noņemt šo ierobežojumu, pārbaudiet vai attēli ielādējas korekti pirms saglabāt Map Tour. Jus varēsiet atjaunot šo ierobežojumu vēlāk, ja tas būs nepieciešams.",
				dataPicError8: "noņemt attēlu ierobežojumu",
				dataPicError9: "Ja šie URL norāda uz video, jūs varat ignorēt šo brīdinājumu, ja tie norāda uz attēliem, jums jāveic viena no sekojošām divām darbībām:",
				modalCancel: "Atcelt",
				modalApply: "Lietot",
				organizeHeader: "Organizē tūri",
				organizeGeneralCaption: "Izmantot vilkt un nomest, lai kārtotu maršruta punktus",
				organizeDelete: "Izdzēst",
				organizeHide: "Paslēpt",
				organizeReset: "Atiestatīt kārtību un slēptos punktus",
				addMaxPointReached: "Jūs esat sasniedzis maksimālo punktu skaitu, ko pilnvarojuši  ikonu iestatījumi un nevarat pievienot citu tūres punktu.<br/><br/>Ņemiet vērā, ja jūs izdzēstu esošos punktus, jums būtu nepieciešams pārlādēt aplikāciju.",
				addMaxPointReachedMobile: "Atvainojiet, jūs esat sasniedzis maksimālo autorizēto punktu skaitu un nevarat pievienot šo bildi.",
				addClose: "Aizvērt",
				addHeader: "Pievienot jaunu tūres punktu",
				addTabPicture: "Mediji",
				addTabInformation: "Informācija",
				addTabLocation: "Izvietojums",
				addSelectCaption: "Izvēlieties vai iemetiet bildi",
				addNoteVideo: "Apskatiet Palīdzību, lai uzzinātu instrukcijas kā izmantot video",		
				addSelectCaptionNoFileReader: "Izvēlieties attēlu",	
				addChangePhoto: "Mainīt bildi un sīkattēlu",
				addPictureResolutionIntro: "Attēla rezolūcija ir lielāka nekā nepieciešams:",
				addPictureResolutionOldBrowser: "Attēla rezolūcija ir lielāka nekā nepieciešams. Optimizēt Map Tour pieredzi, norādot zemāku rezolūciju nekā %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Mainīt attēla rezolūciju uz %RESOLUTION%",
				addPictureResolutionKeep: "Paturēt oriģinālo rezolūciju %RESOLUTION%",
				addSelectThumbnail: "Izvēlēties sīktēlu",
				addNoThumbSelected: "Nav izvēlēts sīktēls",
				addThumbSelected: "Izvēlētais",
				addCameraSettingsHeader: "KAMERAS IESTATĪJUMI",
				addThumbnailHeader: "SĪKTĒLS",
				addLabelPicUrl: "Bilde",
				addLabelThumbUrl: "Sīktēls",
				addTextPlaceholderUrl: "Ievadiet attēla URL",
				addTextPlaceholderUrl2: "Ievadiet YouTube lapas URL",
				addTextPlaceholderUrl3: "Ievadiet Vimeo lapas URL",
				addTextPlaceholderUrl4: "Ievadiet iedarinātā video URL",
				addLabelVideo: "Video",
				addMediaVideoOther: "Citi",
				addMediaVideoHelp: "Pārbaudiet URL un iegūstiet noklusējuma sīkattēlu",
				addMediaVideoHelpTooltip1: "Pārbaude izdevās",
				addMediaVideoHelpTooltip2: "Pārbaude neizdevās",
				addMediaVideoHelpTooltip4: "Atrodiet opciju lai iedarinātu video un kopējiet video URL kas ir redzams kodā",
				addLabelName: "Nosaukums",
				addLabelDescription: "Uzraksts",
				addTextPlaceholder: "Rakstīt kaut ko",
				addLocatePlaceholder: "Atrast adresi vai vietu",
				addPinColor: "Krāsa",
				addLatitude: "Platums",
				addLongitude: "Garums",
				addLatitudePlaceholder: "piem. 34.056",
				addLongitudePlaceholder: "piem. -117.195",
				addUploading: "Augšupielādējot tūres punktu",
				addSave: "Pievienot tūres punktu",
				addMobileUploading: "Augšupielādē bildi",
				addMobileName: "Ievadiet nosaukumu",
				addMobileNameMandatory: "Kļūda, lūdzu, ievadiet nosaukumu.",
				addMobileError: "Atvainojiet, kaut kas ir nogājis greizi",
				settingsHeader: "Aplikācijas iestatījumi",
				settingsTabLayout: "Izkārtojums",
				settingsTabColor: "Krāsas",
				settingsTabLogo: "Galvene",
				settingsTabFields: "Dati",
				settingsTabExtent: "Pārklājums",
				settingsTabZoom: "Mērogmaiņas līmenis",
				settingsLayoutExplain: "Izvēlieties vēlamo aplikācijas izkārtojumu.",
				settingsLayoutProfessional: "Trīs paneļu izkārtojums",
				settingsLayoutModern: "Integrētais izkārtojums",
				settingsLayoutSelected: "Izvēlētais izkārtojums",
				settingsLayoutSelect: "Izvēlieties šo izkārtojumu",
				settingsLayoutNote: "Ņemiet vērā, ka punktiem, kuriem izmantoti video, plakāti vienmēr būs novietoti zem video, pat ja šī izvēlne būs atiezīmēta.",
				settingsLayoutLocBtn: "Attēlot pogu \'Atrast izvietojumu\'",
				settingsLayoutLocBtnHelp: "Šī funkcionalitāte tiek atbalstīta uz biežāk lietotajām mobilājām ierīcēm un darbvirsmas pārlūkiem (Internet Explorer 9).",
				settingsColorExplain: "Mainīt izskatu, izvēloties iepriekš noteiktu tēmu, vai izveidojot savu.",
				settingsLabelColor: "Galvenes, satura un kājenes krāsas",
				settingsLogoExplain: "Pielāgot galvenes logotipu (maksimums  ir 250 x 50piks).",
				settingsLogoEsri: "Esri logotips",
				settingsLogoNone: "Nav logotipa",
				settingsLogoCustom: "Pielāgots logotips",
				settingsLogoCustomPlaceholder: "Attēla URL",
				settingsLogoCustomTargetPlaceholder: "Klikšķis caur saiti",
				settingsLogoSocialExplain: "Pielāgot galvenes labās augšējās saites.",
				settingsLogoSocialText: "Teksts",
				settingsLogoSocialLink: "Saite",
				settingsLogoSocialDisabled: "Administrators ir atspējojis šo iezīmi",
				settingsDataFieldsExplain: "Izvēlieties foto nosaukumu, uzrakstu un krāsu laukus.",
				settingsDataFieldsError: "Aplikācija nevar noteikt piemērotu nosaukumu, uzrakstu vai krāsu datus. Lūdzu, izvēlieties laukus ko šeit izmantot. Šos iestatījumus var mainīt vēlāk.",
				settingsFieldsLabelName: "Nosaukums",
				settingsFieldsLabelDescription: "Uzraksts",
				settingsFieldsLabelColor: "Krāsa",
				settingsFieldsReset: "Atiestātīt lauku atlasi",
				settingsExtentExplain: "Iestatīt Map Tour sākotnējo pārklājumu, izmantojot interaktīvo karti zemāk.",
				settingsExtentExplainBottom: "Pārklājums, kas tiek definēts, modificēs jūsu web kartes sākotnējo pārklājumu. Ņemiet vērā, ka šis pārklājums netiks izmantots, ja ras nesatur pirmo tūres punktu. Šajā gadījumā tūre atvērsies iecentrēta uz pirmo punktu.",
				settingsExtentDateLineError: "Pārklājums nevar būt pāri 180Â° meridiāna garumam.",
				settingsExtentDateLineError2: "Kļūda aprēķinot pārklājumu",
				settingsExtentDrawBtn: "Zīmēt jaunu pārklājumu",
				settingsExtentModifyBtn: "Rediģēt pārklājumu",
				settingsExtentApplyBtn: "Priekšskatīt Map Tour",
				settingsExtentUseMainMap: "Lietot Map Tour pārklājumu",
				settingsZoomExplain: "Iestatīt mērogmaiņu stāstu punktiem, kas seko pēc ievada (pēc izvēles).",
				settingsLabelZoom: "Mērogs/līmenis",
				settingsZoomFirstValue: "Neviens",
				settingsFieldError: "Lūdzu, izvēlieties lauku katrā sarakstā",
				dataTitle: "ArcGIS Online viesošana",
				dataExplain: "Elementu serviss tiks pievienots jūsu web kartei. Tas netiks koplietots ar ikvienu un tikai jums būs privilēģijas pievienot, rediģēt un dzēst.<br /><br />Atcerieties, ja jūs koplietosiet aplikāciju izmantojot vienības lapu, sistēma jautās vai vēlaties koplietot elementu servisu. Tas ir nepieciešams solis. Jūs paliekat vienīgais kuram būs rediģēšanas privilēģijas.",
				dataNameLbl: "Servisa nosaukums",
				dataFolderListLbl: "Mape",
				dataFolderListFetching: "Mapju ienešana ...",
				dataRootFolder: "Sakne",
				dataNameError: "Ievadiet nosaukumu elementu servisam",
				dataFolderError: "Izvēlieties derīgu mapi",
				dataSrcContainsInvalidChar: "Elementu servisa nosaukums satur vienu vai vairākas nederīgas rakstzīmes (-, <, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "Serviss ar šādu nosaukumu jau pastāv organizācijā. Lūdzu, izvēlieties citu nosaukumu.",
				dataBtnSave: "Izveidot servisu",
				dataFooterProgress: "Izveide notiek",
				dataFooterSucceed: "Izveide izdevās. Ielādē",
				dataFooterError: "Izveide neizdevās. Lūdzu, mēģiniet vēlreiz",
				tabError: "Lūdzu pārbaudīt kļūdas visās cilnēs",
				introRecordBtn: "Ievads",
				introRecordActivate: "Izmantojiet pirmo punktu, kā ievadu (neparādās karuselī)"
			},
			addPopupJS: {
				uploadingPicture: "Augšupielādē attēlu",
				uploadSuccess: "Augšupielāde veiksmīga",
				uploadError: "Kļūda, augšupielādējot attēlu",
				uploadError2: "Kļūda pievienojot elementu (nederīgs html tags)",
				notJpg: "Lūdzu, izvēlieties jpeg foto, lai augšupielādētu",
				errorNoPhoto: "Izvēlieties attēlu, lai augšupielādētu",
				errorNoThumbnail: "Izvēlieties sīktēlu, lai augšupielādētu",
				errorInvalidPicUrl: "Ievadiet derīgu bildi (sākas ar http(s)://, beidzas ar jpg, png, gif vai bmp). URL var beigties ar '#isImage', lai ignorētu šo noteikumu.",
				errorInvalidThumbUrl: "Ievadiet derīgu sīktēlu (sākas ar http(s)://, beidzas ar jpg, png, gif vai bmp).",
				errorInvalidVideoUrl: "Ievadiet derīgu video URL (sākas ar http(s)://)",
				errorNoName: "Ievadiet nosaukumu šim tūres punktam",
				errorNoDescription: "Ievadiet uzrakstu šim tūres punktam",
				errorNoLocation: "Iestatiet izvietojumu šim tūres punktam"
			},
			builderJS: {
				noPendingChange: "Nav nesaglabātu izmaiņu",
				unSavedChangeSingular: "1 nesaglabāta izmaiņa",
				unSavedChangePlural: "nesaglabātas izmaiņas",
				shareStatus1: "Tūre nav saglabāta",
				shareStatus2: "Tūre ir publiski koplietota",
				shareStatus3: "Tūre ir koplietota ar organizāciju",
				shareStatus4: "Tūre nav koplietota",
				popoverDiscard: "Vai esat pārliecināts, ka vēlaties izmest visas nesaglabātās izmaiņas?",
				yes: "Jā",
				no: "Nē",
				popoverLoseSave: "Atverot skatītāju, jūs zaudēsiet visas nesaglabātās izmaiņas",
				ok: "Labi",
				popoverSaveWhenDone: "Neaizmirstiet saglabāt, kad jūs pabeidzat",
				closeWithPendingChange: "Vai esat pārliecināts, ka vēlaties apstiprināt darbību? Jūsu izmaiņas tiks zaudētas.",
				gotIt: "Labi",
				savingApplication: "Saglabā aplikāciju",
				saveSuccess: "Aplikācija saglabāta veiksmīgi",
				saveError: "Saglabāt neizdevās, lūdzu, mēģiniet vēlreiz",
				saveError2: "Saglabāšana neizdevās nederīga html taga dēļ vārdā vai aprakstā",
				saveError3: "Virsraksts nevar būt tukšs",
				dragColorPicker: "Pārvietot man apkārt<br />vai mainīt manu krāsu",
				dataWarningExtent: "Jums ir dati web kartes pārklājuma ārpusē. Šie dati netiks izmantoti kā tūres punkti, izmainiet kartes pārklājumu, ja jūs vēlaties tos izmantot.",
				dataWarningVisibi: "Jūsu Map Tour slānis nav redzams pašreizējā web kartes pārklājumā. Apstipriniet, ka jūsu Map Tour slānis ir redzams ar %MAPSIZE% lielā kartē.",
				dataWarningEdit: "Rediģēt web karti",
				dataWarningClose: "Aizvērt",
				signIn: "Lūdzu, pierakstieties kontā uz",
				signInTwo: "lai saglabātu aplikāciju.",
				switchBM: "Mainīt pamatkarti"
			},
			organizePopupJS: {
				messageStart: "Jūs esat izvēlējies izdzēst",
				messageSinglePoint: "vienu tūres punktu",
				messageMultiPoint: "tūres punkti",
				messagePermantRemove: "Tas neatgriezeniski izņems",
				messageRecord: "ieraksts",
				messageRecordPlural: "ieraksti",
				messageConfirm: "no jūsu datubāzes. Vai vēlaties turpināt?",
				labelButtonShow: "Parādīt",
				labelButtonHide: "Paslēpt"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Tas neatgriezeniski izdzēstu bildi un sīktēlu",
				popoverDeleteWarningThumb: "Tas neatgriezeniski izdzēstu sīktēlu",
				popoverUploadingPhoto: "Augšupielādē bildi un sīktēlu",
				popoverUploadingThumbnail: "Augšupielādē sīktēlu",
				popoverUploadSuccessful: "Augšupielāde veiksmīga",
				popoverUploadError: "Augšupielādes neveiksme, lūdzu, mēģiniet vēlreiz",
				changePicAndThumb: "Mainīt bildi",
				changeThumb: "Mainīt sīktēlu",
				selectPic: "Mainīt mediju",
				selectThumb: "Mainīt sīktēlu",
				uploadPicAndThumb: "Lietot"
			},
			headerJS:{
				editMe: "Rediģē mani!",
				templateTitle: "Iestatīt šablona virsrakstu",
				templateSubtitle: "Iestatīt šablona apakšvirsrakstu"
			},
			crossFaderJS:{
				setPicture: "Iestatīt bildes virsrakstu",
				setCaption: "Iestatīt bildes uzrakstu"
			},
			importPopup: {
				title: "Importēt",
				prevBtn: "Atpakaļ",
				nextBtn: "Nākošais"
			},
			importPopupHome: {
				header: "Kur ir jūsu bildes uzglabātas?"
			},
			onlinePhotoSharingCommon: {
				pictures: "attēli",
				videos: "video",
				disabled: "Administrators ir atspējojis šo iezīmi",
				disabledPortal: "Ši iezīme ir atiespējota Portal for ArcGIS",
				header1: "Jūsu attēliem jābūt publiski koplietotiem.",
				header2: "Imports būs limitēts uz pirmajiem %NB1% %MEDIA%.",
				emptyDataset: "Kļūda, nav atrastas bildes",
				footerImport: "Importēt",
				selectAlbum: "Izvēlieties publisku albumu",
				selectAlbum2: "Izvēlieties albumu",
				pleaseChoose: "Lūdzu, izvēlieties",
				userLookup: "Uzmeklēt",
				userLookingup: "Meklēšanai",
				csv: "Atsauce uz CSV",
				advanced: "Papildus opcijas",
				advancedScratchLbl: "Sākt jaunu tūri",
				advancedScratchTip: "Izveidojiet tukšu tūri, kuru jūs varēsiet aizpildīt manuāli izmantojot vedni.",
				advancedCSVLbl: "Importēt tūres datus no CSV faila",
				advancedCSVTip: "Importēt tūres saturu no CSV faila",
				advancedCommonTip: "Nepieciešams, lai jūsu attēli un video jau atrodas tiešsaistē.",
				select: "Veikt izvēli",
				locUse: "Lietot bilžu ģeoizvietojumu",
				locExplain: "Jūs varat nevēlēties izmantot bildes atrašanās vietu, jo tā var būt mantota no albuma, kā rezultātā visas fotogrāfijas būs vienā un tajā pašā vietā.",
				locExplain2: "Jūs varat nevēlēties izmantot video atrašanās vietu, jo tā var būt mantota no lietotāja iestatījumiem, kā rezultātā visi video būs vienā un tajā pašā vietā."
			},
			viewFlickr: {
				title: "Flickr imports",
				header: "Ievadiet jūsu Flickr lietotāja vārdu un izvēlieties Foto kopa vai Tagi, ko importēt.",
				userInputLbl: "Ievadiet Lietotāja vārdu",
				signInMsg2: "Lietotājs nav atrasts",
				selectSet: "Izvēlieties Foto iestatījumu",
				selectTag: "vai izvēlieties Tagu",
				footerImportTag: "Importēt izvēlēto Tagu",
				footerImportSet: "Importēt izvēlēto iestatījumu"
			},
			viewFacebook: {
				title: "Facebook impots",
				header: "Autentificējaties ar savu Facebook lietotāja kontu vai izmantojat publisko lapu. Privātos albumus var izmantot, lai radītu publisko Map Tour, kas neprasīs Facebook lietotāja autentifikāciju un kas ļaus komentāriem un patīk palikt privātiem.",
				leftHeader: "Facebook Lietotājs",
				rightHeader: "Facebook Lapa",
				pageExplain: "Facebook lapa ir publisks zīmols/produkts vai slavenība, piem., <b>esrigis</b>. Jūs varat saņemt lapas nosaukumu, pēc pirmās \'/\' lapas URL.",
				pageInputLbl: "Ievadiet lapas nosaukumu",
				lookupMsgError: "Lapa nav atrasta"
			},
			viewPicasa: {
				title: "Picasa/Google+ imports",
				header: "Ievadiet epastu vai ID no jūsu Picasa vai Google+ konta.",
				userInputLbl: "Ievadiet epastu vai ID",
				signInMsg2: "Konts nav atrasts",
				signInMsg3: "Nav publiska albuma",
				howToFind: "Kā atrast Picasa vai Google+ konta ID",
				howToFind2: "Kopēt ciparus starp pirmo un otro \'/\' no jebkura Picasa vai G+ lapa"
			},
			viewCSV: {
				title: "CSV imports",
				uploadBtn: "Izvēlieties vai nometiet CSV failu",
				resultHeaderEmpty: "CSV ir tukšs",
				resultHeaderSuccess: "Sekmīgi ielādēja %NB_POINTS% punktus",
				resultHasBeenLimited: "Imports ir limitēts ar pirmo %VAL1% norāda uz %VAL2% ievērot limitu %VAL3% punktus par katru tūri",
				browserSupport: "Jūsu pārlūks neatbalsta, lai izmantotu CSV jums ir <a href='http://browsehappy.com/' target='_blank'>jāatjaunina jūsu pārlūks</a> vai lietojiet ArcGIS.com web kartes skatītāju (skat. Palīdzību).",
				errorLatLng: "Platuma un Garuma lauki nav atrasti. Iespējamās platuma vērtības ir: <i>%LAT%</i> un garuma: <i>%LONG%</i>.",
				errorFieldsExplain: "Ielādēšana neizdevās, jo šādi obligātie lauki nav atrasti",
				errorFieldsName: "<b>Nosaukums</b> iespējamās vērtības ir: %VAL%",
				errorFieldsDesc: "<b>Apraksts</b> iespējamās vērtības ir: %VAL%",
				errorFieldsUrl: "<b>Bildes URL</b> iespējamās vērtības ir: %VAL%",
				errorFieldsThumb: "<b>Sīktēla URL</b> iespējamās vērtības ir: %VAL%",
				errorFields2Explain: "Ielādēšana neizdevās, jo CSV neizmanto tos pašus atribūtus, nekā slānis priekš sekojošajiem atribūtiem",
				errorFields2Name: "<b>Nosaukums</b> lieto %VAL1% vietā %VAL2%",
				errorFields2Desc: "<b>Apraksts</b> lieto %VAL1%vietā %VAL2%",
				errorFields2Url: "<b>Bildes URL</b> lieto %VAL1% vietā %VAL2%",
				errorFields2Thumb: "<b>Sīktēla URL</b> lieto %VAL1% vietā %VAL2%",
				resultFieldsAll: "Visi atribūti ir importēti",
				resultFieldsNotAll: "Šādi atribūti nav importēti, jo tie nepastāv kartes slānī",
				resultFieldsNotAll2: "Sekojošie atribūti tiks importēti",
				footerNextBtnResult: "Imports uz web karti",
				footerProgress: "Imports progresā",
				footerSucceed: "Imports sekmīgs. Ielādē"
			},
			viewYoutube: {
				title: "YouTube imports",
				header: "Ievadiet YouTube lietotāja vārdu, lai atrastu publiski koplietotus video.",
				pageInputLbl: "Ievadiet YouTube lietotāja vārdu",
				lookupMsgError: "Lietotājs nav atrasts",
				howToFind: "Kā atrast YouTube lietotāja vārdu",
				howToFind2: "Lietotāja vārds ir attēlots zem video",
				found: "Atrasts",
				noData: "Nav atrasti publiski video"
			},
			viewGeoTag: {
				title: "Izvēlieties un nosakiet izvietojumu jūsu attēliem/video",
				header: "Lai atrastu, noklikšķiniet vai pieskarieties attēliem, ko vēlaties importēt.",
				headerMore: "Kāpēc manas bildes/video nav ģeoizvietoti?",
				headerExplain: "Ja jūsu attēliem ir derīgs izvietojums, tie tiks automātiski izvietoti uz kartes un uzskaitīti otrajā cilnē.<br /><br />Pēc noklusējuma Picasa un Flickr neizmanto bilžu EXIF izvietojuma metadatus, pārbaudiet Flickr/Picasa iestatījumus zem Privacy cilnes, lai iespējotu bildes atrašanās izmantošanu. Jūs varat pilnībā ievest atpakaļ savus attēlus Flickr/Picasa.<br /><br />Priekš Facebook, jums ir jāiet uz katra attēla, jānoklikšķina uz Rediģēt un jāizvēlas izvietojums starp ieteiktajām izvēlēm, kas balstās uz bildes EXIF metadatiem.",
				leftPanelTab1: "Lai atrastu",
				leftPanelTab2: "Atrodas",
				clickOrTap: "Noklikšķiniet vai pieskarieties kartei, lai atrastu",
				clearLoc: "Notīrīt izvietojumus",
				clickDrop: "Neimportē",
				footerImport: "Importēt",
				footerProgress: "Imports progresā",
				footerSucceed: "Imports sekmīgs. Ielādē...",
				loading: "Ielādē",
				error: "Attēla izvietojuma importēšana neizdevās, ģeoizvietojumi tika ignorēti."
			},
			initPopup: {
				title: "Laipni lūdzam Map Tour Veidotājā",
				prevBtn: "Atpakaļ",
				nextBtn: "Nākošais"
			},
			initPopupHome: {
				header1: "Kur ir jūsu attēli vai video?",
				header2: "Šis asistents palīdzēs jums veidot Map Tour no attēliem, kas jau glabājas tiešsaistē vai tie tiks importēti jūsu ArcGIS Online for Organizations kontā.",
				title1: "Tās jau atrodas tiešsaistē",
				title2: "Man nepieciešams augšupielādēt attēlus",
				hostedFSTooltip: "Izmantojiet ArcGIS Online, lai viesotu savus attēlus (neatbalsta video).",
				hostedFsNA: "Pieejams tikai ArcGIS for Organizations izdevēja un aministratora lietotājiem",
				footer1: "Kad tas ir izdarīts, neaizmirstiet dalīties ar jūsu Map Tour ar jūsu auditoriju, izmantojot aplikācijas vienības lapu.",
				footer3: "Lejupielādēt CSV šablonu",
				footer4: "\"Saglabājiet kā\" ja tas nelejupielādējas",
				footer4bis: "Izmantojiet labo pogu un\"Saglabāt kā\" ja nesākas lejupielāde",
				footer5: "Uzziniet vairāk",
				footerProgress: "Izveide notiek",
				footerSucceed: "Izveide sekmīga. Ielādē..."
			},
			helpPopup: {
				title: "Palīdzība",
				close: "Aizvērt",
				tab1: {
					title: "Ievads",
					div1: "Map Tour šablons ir noformēts, lai prezentētu ģeogrāfisku informāciju, ja ir pārliecinoši fotogrāfiskie vai mediju elementi stāstam, ko jūs vēlaties pastāstīt.",
					div2: "Šablons producē pievilcīgu, viegli izmantojamu web aplikāciju, kas ļauj jums prezentēt nelielu vietu komplektu kartē numurētas secībā, caur kuru lietotāji to var pārlūkot. Šablons ir paredzēts izmantošanai jebkurā web pārlūkā uz jebkuras ierīces, ieskaitot viedtālruņus un planšetdatorus. <br /><br />Te ir piemērs aplikācijai, kuras jūs varat izveidot:",
					div4: "<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Map Tour</a>.",
					div42: "Lai apskatītu karšu ceļvežus, kurus veidojuši citi lietotāji, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>apmeklējiet galeriju</a> tīmekļa vietnē <a href='http://storymaps.arcgis.com/' target='_blank'>Story Maps</a>. Jūs varat sekot mums arī Twitter lapā <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
					div5: "Mēs labprāt vēlētos dzirdēt jūsu atsauksmes! Neatkarīgi no tā vai jums ir jautājumi, vēlaties pieprasit jaunu elementu, vai uzskatāt , ka esat atradis kļūdu, lūdzu apmeklējiet <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps lietotāju forums</a>."
				},
				tab2: {
					title: "Dati",
					div1: "Galvenais elements, kas ir jāievēro, būvējot Map Tour, ir izvēlēties, kur tiks glabātas bildes. Map Tour varat izmantot bildes, kas saglabātas uz galvenajiem foto koplietošanas servisiem, jebkurā web serverī vai kā piesaiste elementu servisam.",
					div1a: "Aplūkojiet pēdējo sadaļu šajā tabulatorā, lai uzzinātu par atbalstītajiem attēlu un video formātiem.",
					div2: "Interaktīvais veidotājs dod jums divas iespējas apstrādāt attēlus jūsu Map Tour:",
					div3: "<ul><li>Jūs varat lietot <b>fotoattēlus, kas jau ir tiešsaistē</b>, piemēram, attēlus, kas glabājas foto koplietošanas vietnēs kā Flickr, vai saglabātos attēlus savā tīmekļa vietnē. Šiem attēliem būs atsauce jūsu kartes ceļvedī, izmantojot to vietrāžus URL</li><li>Jūs varat arī <b>augšupielādēt fotoattēlus no datora</b> tieši kartes ceļvedī. Lai veiktu augšupielādi, nepieciešams ArcGIS for Organizations konts vai administratora privilēģijas, jo jums tiek automātiski izveidots viesotu elementu pakalpojums, kur jūsu fotoattēli tiek glabāti kā pielikumi</li></ul>",
					div4: "Galvenie lietošanas gadījumi ir:",
					div4b: "<b>Jūsu fotoattēli vēl netiek viesoti,</b> un jums ir ArcGIS for Organizations konts: izmantot viesotu elementu pakalpojumu ir jūsu labākā izvēle. Līdzīgi publiskajiem fotoattēlu koplietošanas pakalpojumiem mēs optimizēsim jūsu attēlus, lai izveidotu ātri ielādējamus attēlus, un jums būs piekļuve visām ArcGIS platformas administrēšanas un datu pārvaldības iespējām.",
					div5: "<b>Jūs neesat Organizācijas biedrs</b>: Jums vispirms jāaugšupielādē savas bildes foto koplietošanas mājas lapā, vai uz jūsu web serveri. Tad veidotājs palīdzēs izmantot šīs bildes, kas turpmāk tiks viesotas savā oriģinālajā izvietojumā.",
					div6: "<b>Jūs meklējat, lai atkārtoti lietotu esošo Feature Service</b> kas glabā jūsu bildes kā piesaistes, vai kas atsaucas uz ārējām bildēm: skatiet detalizētāku nodaļu apakšā.",
					div7: "<b>Jūs esat iepriekšējās versijas lietotājs</b> Map Tour šablonam un jau ir jūsu CSV, kas atsaucas jūsu bildēm un sīktēliem: jums būs iespēja importēt un uzlabot savus datus. Veidotājs atbalsta tikai CSV, kas lieto plat/gar laukus; uz adresēm balstīts CSV var tikt turpināts lietot caur jūsu web karti (skatīt nodaļu zemāk).",
					div8: "Importē no tiešsaistes foto koplietošanas servisu",
					div9: "Importa operācijas atsaucas uz attēliem, kas tiek viesoti, saglabājot to URL web kartes elementu kolekcijā. Attēli netiek saglabāti ArcGIS Online. Ja viesotiem attēliem nevar piekļūt, tie nebūs pieejami Map Tour un jūs redzēsiet \'Attēls nav pieejams\' attēlu. Atkarībā no attēlu servisu sniedzēja, Map Tour tiks vai netiks importēts nosaukums, apraksts un attēla izvietojums. Šie atribūti tiek glabāti web kartē un jebkādi labojumi uz tiešsaistes servisiem netiks atspoguļoti Map Tour.",
					div10: "Uzglabā bildes uz web servera",
					div11: "Ja vēlaties viesot bildes pats, jums būs manuāli jāizveido sīktēli jūsu attēliem. Izmantojot pilnas rezolūcijas bildes priekš sīktēliem radīs sliktu sniegumu. Šī iemesla dēļ mēs noteikti iesakām, ka jūs izmantojat tiešsaistes foto koplietošanas servisus vai elementu servisu, kas to veiks jūsu vietā.",
					div12: "Lieto eksistējošu Feature Service vai Shapefile",
					div13: "Jebkurš punktu elementu serviss vai shape fails var tikt lietots kā Map Tour datu avots. Jums vienkārši ir jāpievieno to kā slāni savā web kartē, izmantojot arcgis.com kartes pārlūku. Ja aplikācija atrod gaidītos atribūtus jūsu slānī, visa veidotāja funkcionalitāte būs pieejama.",
					div14: "Iespējamās lauku nosaukumu vērtības ir (reģistrjūtīgas):",
					div151: "Nosaukums",
					div152: "Apraksts",
					div153: "Bilde",
					div154: "Sīktēls",
					div155: "Krāsa ",
					div16: "Ja aplikācija neatrod atbilstošus laukus lietojot elementu servisu, skatītājs nestrādās, līdz jūs konfigurēsiet laukus lietošanai caur veidotāju. CSV un shape failu slāņiem, kas pievienoti web kartei, jābūt visiem nepieciešamajiem laukiem, pretējā gadījumā veidotājs nestrādās.",
					div162: "Izmantojot elementu servisu kas glabā attēlus kā piesaistes, <b>tiks izmantoti tikai tie elementi kuriem ir divas piesaistes</b>. Pirmā piesaiste definē galveno attēlu, otrā definē sīkattēlu.",
					div17: "Attēlu un sīktēlu lauki ir obligāti elementu servisam bez piesaistēm un pēc izvēles (bet ļoti ieteicami) elementu servisam ar piesaistēm. Ja jūsu servisam ir iespējotas piesaistes, veidotājs ļaus jums augšupielādēt bildes kā piesaistes. Ja nē, jums būs tikai iespēja rediģēt bilžu un sīktēlu URL.",
					div172: "Ja tādi būs, vienmēr tiks izmantoti attēlu un sīkattēlu lauki un elemetu servisa piesaistes netiks pieprasītas.",
					div173: "Piemēra CSV un shape faili var tikt lejupielādēti no",
					div18: "Rada viesotu elementu servisu no CSV vai shape faila",
					div19: "Kad jūs izveidojat elementu servisu no CSV vai shape faila, piesaistes nav iespējotas pēc noklusējuma. Lai tās iespējotu, atveriet elementu servisa detaļu lapu, noklikšķiniet uz nelielas bultiņas slāņa sadaļā, un jūs redzēsiet šo opciju. Pēc tam Map Tour turpinās izmantot attēlus un sīktēlus, uz ko jūs atsaucaties caur atribūtiem. Pēc izvēles, ja jūs vēlaties augšupielādēt savas bildes kā elementu servisa piesaistes, jums būs iespēja to darīt caur divām pogām uz bildes paneļa (\"Mainīt attēlu\" un \"Mainīt sīkattēlu\").",
					div20: "Atbalstītie attēlu un video formāti",
					div21: "Atbalstītie attēlu formāti: <b>.jpg, .jpeg, .png, .gif un .bmp</b>. Ja jūsu medijs nebeidzas ar šādu paplašinājumu, Map Tour uzskatīs to par video, izņemot gadījumu, ja izmanto elementu servisu (skatīt zemāk).",
					div22: "Map Tour šablons nesatur videopleijeri, tādēļ jāizmanto ārējs videopleijers, ko nodrošina video viesošanas serviss (atrodiet opciju lai iedarinātu video un iekopētu doto URL dotajā kodā) Ja vēlaties viesot video pats, jūs varat izveidot HTML lapu, kas satur videopleijeri, piemēram, <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Ineraktīvais veidotājs nenodrošina dialogu, lai iekļautu video, gadījumos kad izmanto elementu servisu ar piesaistēm, bet ir iespējams to izdarīt rediģējot datus ārpus inerkatīvā veidotāja. Arcgis.com kartes pārlūkā, ja modificējat attēla laukus, lai norādītu ārēju video, un pievienojat speciālu parametru URL beigās (#isVideo), jūsu medijs tiks uzkatīs par video.",
					div24: "Atcerieties, ka jums nepieciešami divas derīgas attēla piesaistes vai punkts netiks izmantots. Nav iespējams izmantoto video, izmantojot elementu servisa piesaistes bez attēla un sīkattēla laukiem."
				},
				tab3: {
					title: "Pielāgošana",
					div1: "Veidotājs nodrošina vairākas pielāgošanas opcijas, kas ir pieejamas, izmantojot SETTINGS pogu, kas ir augšējā panelī. Ja jūs nevarat atrast sagaidīto opciju, mēs nodrošinām arī lejupielādējamu versija, ko varat izvietot uz jūsu web servera un uzlabot, lai atbilstu jūsu vajadzībām.",
					div2: "Mēs iesakām izmantot viesoto versiju, ja vien:",
					div3: "<li>Tas nepiedāvā UI pielāgošanu, kādu vēlaties, piemēram, izmantojot galvenes fona attēlu</li><li>Jūs esat programmētājs un jūs vēlaties uzlabot aplikāciju.</li>",
					div4: "Lejupielādējamā versija var tikt konfigurēta izmantojot web karti vai web kartēšanas aplikācijas identifikatoru. Galvenie lietošanas gadījumi ir:",
					div41: "Jūs veidojat kartes tūri izmantojot interaktīvo veidotāju viesotā vidē un konfigurējat šablonu ar web kartēšanas aplikācijas identifikatoru. Tiks piemēroti iestatījumi, kurus jūs definējat ar interaktīvo veidotāju.",
					div42: "Jūs veidoja web karti ārpus interaktīvā veidotāja un konfigurējat šablonu ar web kartes identifikatoru. Jums būs jālasa dokumentācija, lai uzzinātu kā konfigurēt šablonu.",
					div43: "Atcerieties, ka interaktīvais veidotājs ir pieejams lejupielādēšanas versijā, bet ar dažiem tehniskiem ierobežojumiem pārlūkam Internet Explorer vecākām verijām par 10.",
					div5: "Lai lejupielādētu pašu jaunāko šablona versiju un uzzinātu vairāk kā to izmantot, apmeklējiet <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub projektu lapa</a>."
				},
				tab4: {
					title: "Padomi",
					div0: "Atbalstītie pārlūki",
					div0a: "Map Tour pārlūks tiek atbalstīts uz IE8 un augstāka versija. Interaktīvais veidotājs tiek atbalstīts uz IE9 un augstāka versija. Mēs veicam aktīvu testēšanu visos galvenajos pārlūkos, bet gadījumā ja sastopaties ar kādām grūtībām, iesakām izmantot Chrome pārlūku.",
					div0b: "Ja jūs saskaraties ar grūtībām, lūdzu ziņojiet. Tikmēr veidojot Map Tour izmantojot CSV šablonu jūs minimizēsiet jūsu mijiedarbību ar veidotāja interfeisu.",
					div1: "Bildes",
					div2: "Mēs iesakām fotogrāfijām ainavas orientāciju, nevis portreta. Fotogrāfijas ar attiecību 4:3 der vislabāk. Portreta orientācijas attēlus var izmantot, bet uz mazākiem ekrāniem, piemēram, iPad, daudz foto var aptumšot ar uzrakstu, teksts aizņem vairāk vietas, kad tas tiek parādīts garā laukumā, salīdzinot ar platu laukumu. Lai gan dažāda lieluma, formas un orientācijas attēlus var izmantot vienā Map Tour, mēs iesakām izmantot tieši tādu pašu izmēru un formu visiem attēliem. Tādā veidā, lietotājs neapjuks saktoties uz dažāda izmēra attēliem, kad tie seko tūrei.",
					div2a: "Mēs iesakām maksimālo attēla izmēru 1000 pikseļi platumā un 750 pikseļi garumā galvenajam attēlam un 140x93 sīkattēlam.",
					div3: "Formatē jūsu uzrakstu tekstu, izmantojot HTML tagus",
					div4: "Galvenes un attēla nosaukums/paraksts var ietvert HTML tagus, lai definētu formatējumu un saites. Piemēram, šis kods pievieno dzeltenu saiti:",
					div4a: "Ierakstiet labu apakšvirsrakstu jūsu tūrei",
					div4b: "Atvēliet laiku, lai uzrakstītu saistošu apakšvirsrakstu savai tūrei. Apakšvirsraksts ir labs paņēmiens, kā piesaistīt cilvēkus tūrei un pastāstīt, ko viņi te uzzinās. Apakšvirsraksts ir arī piemērots, lai pavēstītu mērķauditorijai, kurā valstī izvietota jūsu tūre. Piemēram, neuzskatiet, ka cilvēki zinās jūsu tūres pilsētas vai ciemata izvietojumu. Virsrakstu var formatēt, izmantojot HTML tagus, piemēram, iekļaujot saites. Tomēr nepadariet virsrakstu pārāk garu. Mazākos pārlūkprogrammu logos vai iPad tas var neietilpt vai tikt apgriezts. Ja jūs nevarat izdomāt labu apakšvirsrakstu, tad atstājiet šo vietu tukšu.",
					div5: "Atbalstot slāņus",
					div6: "Jūs varat pievienot papildu atbalsta slāņus, lai nodrošinātu kontekstu Map Tour. Šie slāņi var saturēt citus ģeogrāfiskos elementus, kurus jūs vēlaties attēlot kartē paplidus Map Tour punktiem, kā piemēram, studiju areālu, iešanas vai braukšanas maršrutu, kas savieno jūsu maršruta punktus, utt. Map Tour šablons parāda šos papildu atbalsta slāņus, izmantojot jūsu norādīto simboliku šajā web kartē, bet uznirstošie logi nav pieejami.",
					div7: "Turiet jūsu ceļojumu īsu un saldu",
					div8: "Tūres limits ir 99 punkti. Protams, vairums Map Tours, būs ievērojami īsāks nekā minētie 99 punkti. Nesagaidiet, ka jūsu auditorija vēlas apskatīt pārāk daudz tūres punktus. Jūs variet uzkatīt šo tēmu par saistošu, bet nepieņemiet, ka pārējais vairums arī!",
					div9: "Lai uzzinātu vairāk, skatiet <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>detalizēts gids</a>.",
					div10: "Iedarināts režims",
					div11: "Ja vēlaties iedarināt šablonu citā web vietnē imantojot iframe, pievienojot izvēles parametru \"&embed\" URL saites beigās tiks noņemta galvene. Šads režīms var tikt iestatīs lejupielādējamajai versijai caur konfigurācijas failu.",
					div12: "Izvairieties izmantot šauru iFrame platumu, kas izraisīs kartes tūres pārslēgšanos uz tās attiecīgo pieksāriena bāzēto maza ekrāna izkārtojumu. Lai maksimizētu lietošanas vienkāršumu, kad jūs iedarināt kartes tūri, mēs iesakām vienmēr norādīt saiti blakus  iedarinātai tūrei, lai lietotājs var palaist tūri pilnekrāna režīmā." 
				},
				tab5: {
					title: "Publicē",
					div1: "Kad esat pabeiguši, neaizmirstiet koplietot jūsu Map Tour ar jūsu auditoriju, izmantojot KOPLIETOT pogu vai ArcGIS Online aplikācijas vienības lapā.",
					div2a: "Koplietot tūri caur veidotāju",
					div2b: "KOPLIETOT poga jauninās aplikāciju un web kartes vienības. Ja jūsu tūres dati tiek glabāti elementu servisa vienībā, tā arī tiks jaunināta. Ja esat pievienojis citus slāņus izmantojot ArcGIS.com kartes skatītāju, tie netiks jaunināti. šis var rezultēt, ka tūre netiek koplietota kā jūs sagaidījāt. Vienības, kurām jau ir nepieciešamās (vai vairāk) privilēģijas netiks jauninātas.",
					div2c: "Koplietot tūri izmantojot ArcGIS Online",
					div2d: "Kad jūs koplietojat aplikāciju izmantojot ArcGIS Online, ja nepieciešams tiks pieprasīts jaunināt jebkurus atkarīgus resursus  (web karti, elementu servisu, noformējuma slānis), kas nav koplietoti tādā pat veidā. Ja kartes tūre ir publiska un viens no tās resursiem nav koplietots ar jūsu auditoriju, lietotāji tiks pāradresēti uz ArcGIS Online pieteikšanās lapu.",
					div3t: "Elementu servisa drošība",
					div3a: "Ja jūs izmantojat viesotu elementu servisu, izveidotu caur Map Tour veidotāju, aplikācija pārvalda servisa drošību priekš jums un jums paliks tikai rediģēšanas privilēģijas, pat tad, ja jūs koplietosiet servisu publiski.",
					div3t2: "Pirms koplietot jūsu tūri ar publiku.",
					div3: "Pārliecinieties, ka tūre darbojas, ja jūs neesat pieteicies savā ArcGIS.com kontā. URL, kuru jūs izmantosiet, nedrīkst pārsūtīt uz pieteikšanās lapu vai veidotāja režīmu.",
					div4: "Tā ir laba doma apskatīt kā izskatās jūsu kartes tūre uz iPad, kas atrodas ainavas orientācijā, lai pārliecinātos ka tā izkatās labi uz šīs populārās ierīces. Tas palīdzēs jums ieraudzīt vai virsraksti nenosedz pārāk daudz no attēla. Tas arī ļaus ieraudzīt vai jūsu apakšvirsraksts iederas un nav pārāk garš vai tas netiek apgriezts.",
					div5a: "Ieteikumi meklēšanai",
					div5b: "Lai palīdzētu cilvēkiem atrast jūsu kartes tūri ArcGIS Online, mēs iesakām pievienot tagu \'kartes tūre\' jūsu aplikācijas vienības lapā (nevis jūsu web kartes vienības lapā), tā pat kā pavalsts vai provinces, kur jūsu tūre atrodas, tagus, valsts nosaukumu, ja tā atrodas ārpus ASV un tematiskos tagus, kā piemēram, publiskā māksla, tūristu ceļvedis, vēsturiskās vietas. Šie tagi palīdzēs arī mums- Esri atrast lieliskus piemērus tūrēm, kuras varam attēlot galerijās un veicināt sociālajos tīklos. Tāpat iesakām augšupielādēt skaistus sīkattēlus aplikācijas vienības lapā, kā piemēram, tūres mazus sīkattēlus vai kādu no tās attēliem. Šis attēls tiek lietots automātiski, ja jūsu kartes tūre tiek pievienota ArcGIS Online galerijai."
				}
			},
			share: {
				firstSaveTitle: "Tūre veiksmīgi saglabāta",
				firstSaveHeader: "Jūsu tūre nav saglabāta ArcGIS Online. Lūdzu izlasiet sekojošas atbildes uz biežāk uzdotajiem jautājumiem.",
				firstSaveA1: "Ja jūs neesat pazīstams ar ArcGIS Online vai vēlaties īsinājumikonu, lai piekļūtu autorēšanas saskarnei, jūs varat saglabāt sekojošu saiti: %LINK1%",
				firstSaveA1bis: "Tūri var atrast arī jūsu <a href='%LINK2%' target='_blank'>ArcGIS Online satura mapē</a>.",
				firstSaveQ2: "Vai mana tūre ir koplietota?",
				firstSaveA2: "Pašlaik jūsu tūre nav koplietota. Lai to koplietotu izmantojiet pogu KOPLIETOT.",
				shareTitle: "Koplietot jūsu tūri",
				sharePrivateHeader: "Jūsu tūre nav koplietota, vai vēlaties to koplietot?",
				sharePrivateBtn1: "Koplietot publiski",
				sharePrivateBtn2: "Koplietot ar Organizāciju",
				sharePrivateProgress: "Notiek koplietošana...",
				sharePrivateErr: "Neizdevās koplietot, mēģiniet vēlreiz vai",
				sharePrivateOk: "Koplietošana veiksmīgi atjaunināta, ielādē...",
				sharePreviewAsUser: "Priekšskatījums",
				shareHeader1: "Jūsu tūre ir <strong>publiski pieejama</strong>.",
				shareHeader2: "Jūsu tūre ir pieejama jūsu organizācijas biedriem (nepieciešama pieteikšanās).",
				shareLinkHeader: "Koplietojiet tūri ar jūsu auditoriju",
				shareLinkOpen: "ATVĒRTS",
				shareQ1Opt1: "Kā paturēt tūri privātu?",
				shareQ1Opt2: "Kā es varu saglabāt tūri privātu vai koplietot publiski?",
				shareA1: "Izmantojiet %SHAREIMG% <a href='%LINK1%' target='_blank'>aplikācijas vienības lapā</a>. Ja jūs vēlaties pārtraukt koplietot web karti, izmantojiet <a href='%LINK2%' target='_blank'>web kartes vienības lapu</a>.",
				shareA1bis: "Ja jūs vēlaties pārtraukt koplietot elementu servisu, izmantojiet <a href='%LINK1%' target='_blank'>elementu servisa vienības lapu</a>.",
				shareQ2: "Kā es varu rediģēt tūri vēlāk?",
				shareQ2bis: "Kā es varu nokļūt atpakaļ uz autorēšanas interfeisu?",
				shareA2div1: "Saglabājiet un izmantojiet atkal sekojošu saiti %LINK1% vai izmantojiet <a href='%LINK2%' target='_blank'>aplikācijas vienības lapu</a>.",
				shareA2div2: "Kā aplikācijas īpašnieks, kad esat pierakstījies ArcGIS.com, aplikācija satur pogu, lai atvērtu to interaktīvajā veidotājā:",				
				shareQ3: "Kur tiek glabāti dati?",
				shareA3: "Ceļveža konfigurācija tiek glabāta <a href='%LINK1%' target='_blank'>šajā tīmekļa kartes elementā</a> un <a href='%LINK2%' target='_blank'>šajā tīmekļa aplikācijas elementā</a>. Flickr, Picasa un Facebook attēlu un YouTube videoklipu atsauces ir norādītas attiecīgajās vietnēs un netiek dublētas ArcGIS Online.",
				shareWarning: "%WITH% koplietošana ir atspējota, jo jūs neesat <a href='%LINK%' target='_blank'>web kartes</a> īpašnieks.",
				shareWarningWith1: "publiski",
				shareWarningWith2: "publiski un organizācijā"
			}
        }
    })
);
