define(
({
		viewer: {
			loading: {
				step1: "IELĀDĒ APLIKĀCIJU",
				step2: "IELĀDĒ DATUS",
				step3: "IZPILDA TŪRI",
				fail: "Atvainojiet, Map Tour ielādēšanas neveiksme",
				failButton: "Atkārtot"
			},
			errors: {
				boxTitle: "Kļūda",
				invalidConfig: "Fatāla kļūda: konfigurācijas neveiksme",
				invalidConfigOwner: "Fatāla kļūda: konfigurācijas neveiksme (nepieciešams autorizēts īpašnieks)",
				invalidConfigNoWebmap: "Fatāla kļūda: konfigurācijas neveiksme (nepieciešama web karte un autorizēts īpašnieks)",
				createMap: "Nevar izveidot karti",
				invalidApp: "Fatāla kļūda: aplikāciju nevar ielādēt",
				noLayer: "Web karte nesatur derīgu datu slāni priekš Map Tour.",
				noLayerNoHostedFS: "Web karte nesatur derīgu datu slāni priekš Map Tour, un jums nav nepieciešamo privilēģiju, lai izveidotu hosted Feature Service.",
				noLayerMobile: "Laipni lūdzam Map Tour web aplikācijā. Aplikācija nav konfigurēta. Map Tour veidotājs netiek atbalstīts uz mobilajām ierīcēm.",
				noLayerView: "Laipni lūdzam Map Tour web aplikācijā.<br />Aplikācija nav vēl konfigurēta.",
				noBuilderWebmapData: "Map Tour veidotājs nav atbalstīts ar web kartē iespējotiem datiem. Lai lietotu veidotāju, jums ir jālieto Feature Service. Lai lietotu jūsu aktuālo datu slāni, jums ir jāizmanto lejupielādējamā Map Tour versija.",
				appSave: "Kļūda, saglabājot web aplikāciju",
				mapSave: "Kļūda, saglabājot web karti",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "Jums nav atļauts konfigurēt šo aplikāciju",
				oldBrowserTitle: "Pārlūks netiek pilnībā atbalstīts",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "Map Tour veidotājs nav atbalstīts ar Internet Explorer 10 uz Windows 7. Jums vajag <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuāli piespiest dokumenta režīmu uz Internet Explorer 9 standartu</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>pazemināt uz Internet Explore 9</a> vai uzlabot uz Windows 8.",
				oldBrowserExplain: "Šis pārlūks neatbalsta automātisku sīktēlu radīšanu no attēliem, ko jūs augšupielādējat jūsu map tour. Jūs varat izveidot map tour, izmantojot šo pārlūku, bet jums būs jāsniedz atsevišķs sīktēls par katru no augšupielādētiem attēliem .",
				oldBrowserExplain2: "Lai uzlabotu jūsu pieredzi, <a href='http://browsehappy.com/' target='_blank'>jaunina jūsu pārlūku</a> vai <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivizē Google Chrome Frame priekš Internet Explorer</a>.",
				oldBrowserClose: "Aizvērt"
			},
			mobileHTML: {
				showIntro: "RĀDĪT INTRO",
				hideIntro: "PASLĒPT INTRO",
				navList: "Saraksts",
				navMap: "Karte",
				navInfo: "Informācija"
			},
			desktopHTML: {
				storymapsText: "Stāstu karte",
				builderButton: "Pārslēgties uz veidotāja režīmu"
			},
			builderHTML: {
				panelHeader: "APLIKĀCIJAS KONFIGURĀCIJA",
				buttonSave: "SAGLABĀT",
				buttonDiscard: "ATCELT",
				buttonSettings: "Iestatījumi",
				buttonView: "Skata režīms",
				buttonOrganize: "Organizē",
				buttonAdd: "Pievienot",
				modalCancel: "Atcelt",
				modalApply: "Lietot",
				organizeHeader: "Organizē tūri",
				organizeGeneralCaption: "Izmantot vilkt un nomest, lai kārtotu maršruta punktus",
				organizeDelete: "Izdzēst",
				organizeHide: "Paslēpt",
				addMaxPointReached: "Jūs esat sasniedzis maksimālo punktu skaitu, ko pilnvarojuši  ikonu iestatījumi un nevarat pievienot citu tūres punktu.<br/><br/>Ņemiet vērā, ja jūs izdzēstu esošos punktus, jums būtu nepieciešams pārlādēt aplikāciju.",
				addMaxPointReachedMobile: "Atvainojiet, jūs esat sasniedzis maksimālo autorizēto punktu skaitu un nevarat pievienot šo attēlu.",
				addClose: "Aizvērt",
				addHeader: "Pievienot jaunu tūres punktu",
				addTabPicture: "Attēls",
				addTabInformation: "Informācija",
				addTabLocation: "Izvietojums",
				addSelectCaption: "Izvēlieties izkrītošu attēlu",
				addSelectCaptionNoFileReader: "Izvēlieties attēlu",
				addChangePhoto: "Mainiet attēlu un sīktēlu",
				addPictureResolutionIntro: "Attēla rezolūcija ir lielāka nekā nepieciešams:",
				addPictureResolutionOldBrowser: "Attēla rezolūcija ir lielāka nekā nepieciešams. Optimizēt Map Tour pieredzi, norādot zemāku rezolūciju nekā %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Mainīt attēla rezolūciju uz %RESOLUTION%",
				addPictureResolutionKeep: "Paturēt oriģinālo rezolūciju %RESOLUTION%",
				addSelectThumbnail: "Izvēlēties sīktēlu",
				addNoThumbSelected: "Nav izvēlēts sīktēls",
				addThumbSelected: "Izvēlētais",
				addCameraSettingsHeader: "KAMERAS IESTATĪJUMI",
				addThumbnailHeader: "SĪKTĒLS",
				addLabelName: "Nosaukums",
				addLabelDescription: "Uzraksts",
				addTextPlaceholder: "Rakstīt kaut ko",
				addLocatePlaceholder: "Atrast adresi vai vietu",
				addPinColor: "Krāsa",
				addLatitude: "Platums",
				addLongitude: "Garums",
				addLatitudePlaceholder: "piem. 34.056",
				addLongitudePlaceholder: "piem. -117.195",
				addUploading: "Augšupielādējot tūres punktu",
				addSave: "Pievienot tūres punktu",
				addMobileUploading: "Augšupielādē attēlu",
				addMobileName: "Ievadiet nosaukumu",
				addMobileNameMandatory: "Kļūda, lūdzu, ievadiet nosaukumu.",
				addMobileError: "Atvainojiet, kaut kas ir nogājis greizi",
				settingsHeader: "Aplikācijas iestatījumi",
				settingsTabLayout: "Izkārtojums",
				settingsTabColor: "Krāsas",
				settingsTabLogo: "Galvene",
				settingsTabFields: "Dati",
				settingsTabExtent: "Pārklājums",
				settingsTabZoom: "Mērogmaiņas līmenis",
				settingsLayoutExplain: "Izvēlieties aplikācijas izkārtojumu starp diviem paredzētajiem .",
				settingsLayoutProfessional: "Trīs paneļu izkārtojums",
				settingsLayoutModern: "Integrētais izkārtojums",
				settingsLayoutSelected: "Izvēlētais izkārtojums",
				settingsLayoutSelect: "Izvēlieties šo izkārtojumu",
				settingsColorExplain: "Mainīt izskatu, izvēloties iepriekš noteiktu tēmu, vai izveidojot savu.",
				settingsLabelColor: "Galvenes, satura un kājenes krāsas",
				settingsLogoExplain: "Pielāgot galvenes logotipu (maksimums  ir 250 x 50piks).",
				settingsLogoEsri: "Esri logotips",
				settingsLogoNone: "Nav logotipa",
				settingsLogoCustom: "Pielāgots logotips",
				settingsLogoCustomPlaceholder: "Attēla URL",
				settingsLogoCustomTargetPlaceholder: "Klikšķis caur saiti",
				settingsLogoSocialExplain: "Pielāgot galvenes labās augšējās saites.",
				settingsLogoSocialText: "Teksts",
				settingsLogoSocialLink: "Saite",
				settingsDataFieldsExplain: "Izvēlieties foto nosaukumu, uzrakstu un krāsu laukus.",
				settingsDataFieldsError: "Aplikācija nevar noteikt piemērotu nosaukumu, uzrakstu vai krāsu datus. Lūdzu, izvēlieties laukus ko šeit izmantot. Šos iestatījumus var mainīt vēlāk.",
				settingsFieldsLabelName: "Nosaukums",
				settingsFieldsLabelDescription: "Uzraksts",
				settingsFieldsLabelColor: "Krāsa",
				settingsExtentExplain: "Iestatīt Map Tour sākotnējo pārklājumu, izmantojot interaktīvo karti zemāk.",
				settingsExtentExplainBottom: "Pārklājums tiek izmantots tikai tad, ja tas ietver sevī pirmo ceļojumu punktu. Vērtība saglabājās caur web kartes sākotnējo pārklājumu.",
				settingsExtentDrawBtn: "Zīmēt jaunu pārklājumu",
				settingsExtentModifyBtn: "Rediģēt pašreizējo pārklājumu",
				settingsExtentApplyBtn: "Lietot galvenajā kartē",
				settingsZoomExplain: "Iestatīt mērogmaiņu stāstu punktiem, kas seko pēc ievada (pēc izvēles).",
				settingsLabelZoom: "Mērogs/līmenis",
				settingsZoomFirstValue: "Neviens",
				settingsFieldError : "Lūdzu, izvēlieties lauku katrā sarakstā",
				dataHeader: "Aplikāciju dati",
				dataExplain: "Jūsu web karte nesatur elementu servisu. Aizpildiet šo dialogu, lai izveidotu hosted elementu servisu jūsu ArcGIS.com organizācijas kontā. Elementu serviss tiks pievienots jūsu web kartei un koplietots publiski, bet tikai jums būs privilēģijas pievienot/rediģēt un dzēst.<br /><br />Aplikācija būs tikai skatāma, kamēr jūs koplietosiet to ar citiem. <strong>Tiklīdz jūsu Map Tour būs gatava, koplietojiet aplikāciju caur vienības lapu.</strong>",
				dataNameLbl: "Servisa nosaukums",
				dataFolderListLbl: "Mape",
				dataFolderListFetching: "Mapju ienešana ...",
				dataRootFolder: "Sakne",
				dataNameError: "Ievadiet nosaukumu elementu servisam",
				dataFolderError: "Izvēlieties derīgu mapi",
				dataSrcContainsInvalidChar: "Elementu servisa nosaukums satur vienu vai vairākas nederīgas rakstzīmes (<, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "Serviss ar šādu nosaukumu jau pastāv organizācijā. Lūdzu, izvēlieties citu nosaukumu.",
				dataBtnClose: "Atcelt tūri",
				dataBtnSave: "Izveidot servisu",
				dataFooterProgress: "Izveide notiek",
				dataFooterSucceed: "Izveide izdevās. Ielādē",
				dataFooterError: "Izveide neizdevās. Lūdzu, mēģiniet vēlreiz",
				tabError: "Lūdzu pārbaudīt kļūdas visās cilnēs",
				introRecordBtn: "Intro",
				introRecordActivate: "Izmantojiet pirmo punktu, kā ievadu"
			},
			addPopupJS: {
				uploadingPicture: "Augšupielādē attēlu",
				uploadSuccess: "Augšupielāde veiksmīga",
				uploadError: "Kļūda, augšupielādējot attēlu",
				notJpg: "Lūdzu, izvēlieties jpeg foto, lai augšupielādētu",
				errorNoPhoto: "Izvēlieties attēlu, lai augšupielādētu",
				errorNoThumbnail: "Izvēlieties sīktēlu, lai augšupielādētu",
				errorNoName: "Ievadiet nosaukumu šim tūres punktam",
				errorNoDescription: "Ievadiet uzrakstu šim tūres punktam",
				errorNoLocation: "Iestatiet izvietojumu šim tūres punktam"
			},
			builderJS: {
				noPendingChange: "Nav neizpildītu izmaiņu",
				unSavedChangeSingular: "1 nesaglabāta izmaiņa",
				unSavedChangePlural: "nesaglabātas izmaiņas",
				popoverDiscard: "Vai esat pārliecināts, ka vēlaties izmest visas nesaglabātās izmaiņas?",
				yes: "Jā",
				no: "Nē",
				popoverLoseSave: "Atverot skatītāju, jūs zaudēsiet visas nesaglabātās izmaiņas",
				ok: "Labi",
				popoverSaveWhenDone: "Neaizmirstiet saglabāt, kad jūs pabeidzat",
				closeWithPendingChange: "Vai esat pārliecināts, ka vēlaties apstiprināt darbību? Jūsu izmaiņas tiks zaudētas.",
				gotIt: "Labi",
				savingApplication: "Saglabā aplikāciju",
				saveSuccess: "Aplikācija saglabāta veiksmīgi",
				saveError: "Saglabāt neizdevās, lūdzu, mēģiniet vēlreiz",
				dragColorPicker: "Pārvietot man apkārt<br />vai mainīt manu krāsu",
				dataWarningExtent: "Jums ir dati web kartes pārklājuma ārpusē. Šie dati netiks izmantoti kā tūres punkti, izmainiet kartes pārklājumu, ja jūs vēlaties tos izmantot.",
				dataWarningVisibi: "Jūsu Map Tour slānis nav redzams pašreizējā web kartes pārklājumā. Apstipriniet, ka jūsu Map Tour slānis ir redzams ar %MAPSIZE% lielā kartē.",
				dataWarningEdit: "Rediģēt web karti",
				dataWarningClose: "Aizvērt",
				signIn: "Lūdzu, pierakstieties kontā uz",
				signInTwo: "lai saglabātu aplikāciju."
			},
			organizePopupJS: {
				messageStart: "Jūs esat izvēlējušies izdzēst",
				messageSinglePoint: "vienu tūres punktu",
				messageMultiPoint: "tūres punkti",
				messagePermantRemove: "Tas neatgriezeniski izņems",
				messageRecord: "ieraksts",
				messageRecordPlural: "ieraksti",
				messageConfirm: "no jūsu datubāzes. Vai vēlaties turpināt?",
				labelButtonShow: "Parādīt",
				labelButtonHide: "Paslēpt"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "Augšupielādē attēlu un sīktēlu",
				popoverUploadingThumbnail: "Augšupielādē sīktēlu",
				popoverUploadSuccessful: "Augšupielāde veiksmīga",
				popoverUploadError: "Augšupielādes neveiksme, lūdzu, mēģiniet vēlreiz",
				changePicAndThumb: "Mainīt attēlu",
				changeThumb: "Mainīt sīktēlu",
				selectPic: "Mainīt attēlu",
				selectThumb: "Mainīt sīktēlu",
				uploadPicAndThumb: "Lietot"
			},
			headerJS:{
				editMe: "Rediģē mani !",
				templateTitle: "Iestatīt šablona virsrakstu",
				templateSubtitle: "Iestatīt šablona apakšvirsrakstu"
			},
			crossFaderJS:{
				setPicture: "Iestatīt attēla virsrakstu",
				setCaption: "Iestatīt attēla uzrakstu"
			}
        }
    })
);
