define(
({
		viewer: {
			loading: {
				step1: "RAKENDUSE LAADIMINE",
				step2: "ANDMETE LAADIMINE",
				step3: "ALUSTAN TUURI",
				fail: "Kaardi tuuri laadimine ebaõnnestus. Vabandame.",
				failButton: "Proovi uuesti"
			},
			errors: {
				boxTitle: "Esines tõrge",
				invalidConfig: "Totaalne viga: vigane konfiguratsioon",
				invalidConfigOwner: "Totaalne viga: vigane konfiguratsioon (vajalik on autoriseeritud omanik)",
				invalidConfigNoWebmap: "Totaalne viga: Vigane konfiguratsioon (vajalik on veebikaart ja autoriseeritud omanik)",
				createMap: "Võimetu kaarti koostama",
				invalidApp: "Totaalne viga: Rakendust ei saa laadida",
				noLayer: "Veebikaart ei sisalda kaardi tuuri jaoks sobivat kihti.",
				noLayerNoHostedFS: "Veebikaart ei sisalda kaardi tuuri jaoks sobilikku kihti ning seetõttu puuduvad Teil vajalikud õigused luua majutatud objektiteenust.",
				noLayerMobile: "Tere tulemast kaardi tuuri veebirakendusse! Antud rakendus ei ole seadistatav. Kaardi tuuri redigeerimine ei ole mobiilsetes seadmetes toetatud.",
				noLayerView: "Tere tulemast kaardi tuuri veebirakendusse!<br />Antud rakendus ei ole veel seadistatud.",
				noBuilderWebmapData: "Kaardi tuuri koostaja ei ole veebikaardil põimitud andmetega toetatud. Tuuri koostaja kasutamiseks peaksite valima objektiteenuse. Reaalse kihi kasutamiseks peaksite kasutama allalaaditavat Kaardi tuuri versiooni.",
				appSave: "Viga veebirakenduse salvestamisel",
				mapSave: "Viga veebikaardi salvestamisel",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "Te ei ole selle rakenduse konfigureerimiseks autoriseeritud",
				oldBrowserTitle: "Brauser ei ole täielikult toetatud",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "Kaardi tuuri koostamine ei ole toetatud Windows 7 operatsioonisüsteemis kasutatava Internet Explorer 10 brauseriga. Vajadusel peate <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>käsitsi muutma dokumendi ülesehitust Internet Explorer 9 standardite alusel</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>Migreeri brauser Internet Explorer 9 versioonile</a> või uuenda operatsioonisüsteem Windows 8 platvormile.",
				oldBrowserExplain: "Antud brauser ei toeta automaatset pisipiltide koostamist pildiandmetest, mis on laaditud tuuri kirjeldavale kaardile. Teil on võimalik koostada kaart selles brauseris kasutamiseks, kuid peate omistama igale üles laetud pildile asjakohase pisipildi.",
				oldBrowserExplain2: "Oskuste parendamiseks, <a href='http://browsehappy.com/' target='_blank'>uuendage enda brauserit</a> or <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>Google Chrome Frame for Internet Explorer aktiveerimiseks</a>.",
				oldBrowserClose: "Sulge"
			},
			mobileHTML: {
				showIntro: "KUVA INTRO",
				hideIntro: "PEIDA INTRO",
				navList: "Loend",
				navMap: "Kaart",
				navInfo: "Info"
			},
			desktopHTML: {
				storymapsText: "Kaardilugu",
				builderButton: "Vaheta koostamise režiimile"
			},
			builderHTML: {
				panelHeader: "RAKENDUSE KONFIGURATSIOON",
				buttonSave: "SALVESTA",
				buttonDiscard: "TÜHISTA",
				buttonSettings: "Seaded",
				buttonView: "Vaaterežiim",
				buttonOrganize: "Paiguta",
				buttonAdd: "Lisa",
				modalCancel: "Tühista",
				modalApply: "Kehtesta",
				organizeHeader: "Organiseeri tuuri",
				organizeGeneralCaption: "Kasuta tuuri punktide sorteerimisel haaramise ja lohistamise meetodit",
				organizeDelete: "Kustuta",
				organizeHide: "Peida",
				addMaxPointReached: "Olete jõudnud ikoonide poolt autoriseeritud kogumi maksimaalse arvu punktideni ning ei saa rohkem tuuri punkte lisada.<br /><br />Pidage meeles, et kui kustutate juba olemasolevaid punkte, peate taaskäivitama ka rakenduse.",
				addMaxPointReachedMobile: "Olete jõudnud maksimaalse arvu autoriseeritud punktideni ning ei saa seda pilti lisada. Vabandame.",
				addClose: "Sulge",
				addHeader: "Lisa uus tuuri punkt",
				addTabPicture: "Pilt",
				addTabInformation: "Info",
				addTabLocation: "Asukoht",
				addSelectCaption: "Vali või haara pilt",
				addSelectCaptionNoFileReader: "Vali pilt",
				addChangePhoto: "Muuda pilt ja pisipilt",
				addPictureResolutionIntro: "Pildi resolutsioon on nõutavast suurem:",
				addPictureResolutionOldBrowser: "Pildi resolutsioon on nõutavast suurem. Optimeeri kaardi tuuri sisu, määrates resolutsiooni madalamana kui %SOOVITUSLIK_RES%.",
				addPictureResolutionResize: "Muuda pildi resolutsioon %RESOLUTSIOON%",
				addPictureResolutionKeep: "Säilita algne resolutsioon %RESOLUTSIOON%",
				addSelectThumbnail: "Vali pisipilt",
				addNoThumbSelected: "Ühtegi pisipilti ei ole valitud",
				addThumbSelected: "Valitud",
				addCameraSettingsHeader: "KAAMERA SEADED",
				addThumbnailHeader: "PISIPILT",
				addLabelName: "Nimi",
				addLabelDescription: "Alapealkiri",
				addTextPlaceholder: "Kirjuta midagi",
				addLocatePlaceholder: "Märgi aadress või asukoht",
				addPinColor: "Värv",
				addLatitude: "Laius",
				addLongitude: "Pikkus",
				addLatitudePlaceholder: "nt 34.056",
				addLongitudePlaceholder: "nt -117.195",
				addUploading: "Laadin tuuri punkti",
				addSave: "Lisa tuuri punkt",
				addMobileUploading: "Laen pilti",
				addMobileName: "Sisesta nimi",
				addMobileNameMandatory: "Viga, palun sisesta nimi.",
				addMobileError: "Midagi läks valesti. Vabandame.",
				settingsHeader: "Rakenduse seaded",
				settingsTabLayout: "Kujundus",
				settingsTabColor: "Värvid",
				settingsTabLogo: "Päis",
				settingsTabFields: "Andmed",
				settingsTabExtent: "Kuvaulatus",
				settingsTabZoom: "Suumimise tase",
				settingsLayoutExplain: "Vali rakenduse kujundus kahe variandi vahel.",
				settingsLayoutProfessional: "Kolme paneeliga kujundus",
				settingsLayoutModern: "Integreeritud kujundus",
				settingsLayoutSelected: "Valitud kujundus",
				settingsLayoutSelect: "Vali see kujundus",
				settingsColorExplain: "Muuda väljanägemist, valides selleks puhuks eelnevalt määratud teema või koostades ise uue.",
				settingsLabelColor: "Päise, sisu ja jaluse värvid",
				settingsLogoExplain: "Kohanda päise logo (maksimum on 250 x 50px).",
				settingsLogoEsri: "Esri logo",
				settingsLogoNone: "Logo puudub",
				settingsLogoCustom: "Valikuline logo",
				settingsLogoCustomPlaceholder: "Pildi URL",
				settingsLogoCustomTargetPlaceholder: "Kliki läbi lingi",
				settingsLogoSocialExplain: "Kohanda päist ülemise paremal pool asuva lingi kaudu.",
				settingsLogoSocialText: "Tekst",
				settingsLogoSocialLink: "Link",
				settingsDataFieldsExplain: "Vali foto nime, selgitava teksti ja värvi väljad.",
				settingsDataFieldsError: "Rakendus ei suuda määrata sobivat nime, selgitavat teksti ega värvi andmeid. Palun valige siin kasutamiseks vastavad väljad. Vastavad parameetrid on hiljem muudetavad.",
				settingsFieldsLabelName: "Nimi",
				settingsFieldsLabelDescription: "Alapealkiri",
				settingsFieldsLabelColor: "Värv",
				settingsExtentExplain: "Määrake Kaardi tuuri sisemine kuvaulatus läbi alloleva interaktiivse kaardi.",
				settingsExtentExplainBottom: "Antud kuvaulatust kasutatakse vaid juhul, kui see sisaldab esimest tuuri punkti. Väärtus on püsiv läbi veebikaardi sisemise kuvaulatuse.",
				settingsExtentDrawBtn: "Joonista uus ulatus",
				settingsExtentModifyBtn: "Muuda praegust ulatust",
				settingsExtentApplyBtn: "Kehtesta peamisele kaardile",
				settingsZoomExplain: "Määra looga seotud punktidele suum järgeva juhisega (valikuline).",
				settingsLabelZoom: "Mõõtkava/tase",
				settingsZoomFirstValue: "Puudub",
				settingsFieldError : "Palun vali väli igas loendis",
				dataHeader: "Rakenduse andmed",
				dataExplain: "Teie veebikaart ei sisalda objektiteenust. Lõpeta see dialoog, et koostada Teie ArcGIS.com organisatsiooni konto alla majutatud objektiteenus. Objektiteenus lisatakse Teie veebikaardile ja jagatakse avalikult, kuid ainult juhul kui Teil on lisamise/muutmise ja kustutamise õigused.<br /><br />Rakendus on Teie poolt vaadatav hetkeni, kuni jagate selle teistele kasutajatele. <strong>Kui kaardi tuur on valmis, jagage rakendus läbi sisu lehe.</strong>",
				dataNameLbl: "Teenuse nimi",
				dataFolderListLbl: "Kaust",
				dataFolderListFetching: "Haaran kaustu ...",
				dataRootFolder: "Juur",
				dataNameError: "Sisesta objektiteenusele nimi",
				dataFolderError: "Vali sobilik kaust",
				dataSrcContainsInvalidChar: "Objektiteenuse nimi sisaldab ühte või mitut vigast tähemärki (<, >, #, %, :, \", ?, &, +, / või \).",
				dataSrvAlreadyExistsError: "Sama nimega teenus on Teie organisatsioonis juba olemas. Palun valige teistsugune nimi.",
				dataBtnClose: "Tühista tuur",
				dataBtnSave: "Koosta teenus",
				dataFooterProgress: "Koostamine käib",
				dataFooterSucceed: "Koostamine on lõpetatud. Laadin",
				dataFooterError: "Koostamine ei õnnestunud. Proovi uuesti",
				tabError: "Palun kontrolli vigu kõigis osades",
				introRecordBtn: "Intro",
				introRecordActivate: "Kasuta esimest punkti tutvustusena"
			},
			addPopupJS: {
				uploadingPicture: "Laen pilti",
				uploadSuccess: "Laadimine õnnestus",
				uploadError: "Viga pildi laadimisel",
				notJpg: "Laadimiseks vali palun jpeg formaadis pilt",
				errorNoPhoto: "Vali pilt laadimiseks",
				errorNoThumbnail: "Vali pisipilt laadimiseks",
				errorNoName: "Sisesta selle tuuri punktile nimetus",
				errorNoDescription: "Sisesta selle tuuri punktile selgitav tekst",
				errorNoLocation: "Määra selle tuuri punktile asukoht"
			},
			builderJS: {
				noPendingChange: "Ühtegi muudatust ei ole ootel",
				unSavedChangeSingular: "1 mittesalvestatud muudatus",
				unSavedChangePlural: "mittesalvestatud muudatused",
				popoverDiscard: "Olete kindel, et soovite loobuda salvestamata muudatustest?",
				yes: "Jah",
				no: "Ei",
				popoverLoseSave: "Kui avate sirvija, siis kaotate kõik salvestamata muudatused",
				ok: "Ok",
				popoverSaveWhenDone: "Ärge unustage salvestada, kui olete lõpetanud",
				closeWithPendingChange: "Olete kindel, et soovite tegevuse kinnitada? Teie tehtud muudatused võivad kaduma minna.",
				gotIt: "Ok",
				savingApplication: "Salvestan rakenduse",
				saveSuccess: "Rakenduse salvestamine õnnestus",
				saveError: "Salvestamine ebaõnnestus, palun proovi uuesti",
				dragColorPicker: "Paigutage mind ümber<br />või muutke minu värvi",
				dataWarningExtent: "Teie andmed on väljaspool veebikaardi ulatust. Neid andmeid ei saa kasutada tuuri punktidena, mistõttu vahetage nende kasutamiseks kaardi ulatust.",
				dataWarningVisibi: "Teie kaardi tuur ei ole praeguse veebikaardi ulatuses nähtav. Veenduge, et Teie kaardi tuuri kiht on nähtav %KAARDI SUURUS% suuremal kaardil.",
				dataWarningEdit: "Muuda veebikaarti",
				dataWarningClose: "Sulge",
				signIn: "Palun logige konto kaudu sisse",
				signInTwo: ", et salvestada rakendus."
			},
			organizePopupJS: {
				messageStart: "Olete valinud kustutamiseks",
				messageSinglePoint: "ühe tuuri punkti",
				messageMultiPoint: "tuuri punkti",
				messagePermantRemove: "See eemaldab jäädavalt",
				messageRecord: "kirje",
				messageRecordPlural: "kirjed",
				messageConfirm: "Teie andmebaasist. Soovite jätkata?",
				labelButtonShow: "Näita",
				labelButtonHide: "Peida"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "Laadin pilti ja pisipilti",
				popoverUploadingThumbnail: "Laadin pisipilti",
				popoverUploadSuccessful: "Laadimine õnnestus",
				popoverUploadError: "Laadimine ebaõnnestus, palun proovi uuesti",
				changePicAndThumb: "Vaheta pilt",
				changeThumb: "Vaheta pisipilt",
				selectPic: "Vaheta pilt",
				selectThumb: "Vaheta pisipilt",
				uploadPicAndThumb: "Kehtesta"
			},
			headerJS:{
				editMe: "Muuda mind !",
				templateTitle: "Määra mallile pealkiri",
				templateSubtitle: "Määra mallile alampealkiri"
			},
			crossFaderJS:{
				setPicture: "Määra pildile pealkiri",
				setCaption: "Määra pildile selgitav tekst"
			}
        }
    })
);
