define(
	 ({
		viewer: {
			loading: {
				step1: "RAKENDUSE LAADIMINE",
				step2: "ANDMETE LAADIMINE",
				step3: "ALUSTAN TUURI",
				loadBuilder: "LÜLITU KOOSTAMISREŽIIMILE",
				redirectSignIn: "SUUNAN ÜMBER SISSELOGIMISE LEHELE",
				redirectSignIn2: "(Teid suunatakse peale sisselogimist siia)",
				fail: "Kaardi tuuri laadimine ebaõnnestus. Vabandame.",
				failButton: "Proovi uuesti"
			},
			errors: {
				boxTitle: "Esines tõrge",
				portalSelf: "Totaalne viga: Portaali seadistuse hankimine nurjus",
				invalidConfig: "Totaalne viga: vigane konfiguratsioon",
				invalidConfigOwner: "Totaalne viga: vigane konfiguratsioon (vajalik on autoriseeritud omanik)",
				invalidConfigNoWebmap: "Totaalne viga: Vigane konfiguratsioon (veebikaart või rakenduse tuvastaja ei ole index.html all määratud)",
				createMap: "Võimetu kaarti koostama",
				invalidApp: "Totaalne viga: Rakendust ei saa laadida",
				noLayer: "Veebikaart ei sisalda kaardi tuuri jaoks sobivat kihti.",
				noLayerMobile: "Tere tulemast kaardi tuuri veebirakendusse! Antud rakendus ei ole seadistatav. Kaardi tuuri redigeerimine ei ole mobiilsetes seadmetes toetatud.",
				noLayerView: "Tere tulemast kaardi tuuri veebirakendusse!<br />Antud rakendus ei ole veel seadistatud.",
				appSave: "Viga veebirakenduse salvestamisel",
				mapSave: "Viga veebikaardi salvestamisel",
				featureServiceLoad: "Viga objektiteenuse laadimisel",
				notAuthorized: "Te ei ole sellele rakendusele ligipääsuks autoriseeritud",
				oldBrowserTitle: "Brauser ei ole täielikult toetatud",
				noBuilderIE8: "Kaardi tuuri koostaja ei ole toetatud varasemaga, kui Internet Explorer 9 versiooniga.",
				ie10Win7Explain: "Kaardi tuuri interaktiivne koostaja ei ole toetatud Windows 7 operatsioonisüsteemis kasutatava Internet Explorer 10 brauseriga, kui andmeallikas on manustega objektiteenus. Manustega objektiteenuste kasutamiseks peate <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>käsitsi muutma dokumendi ülesehitust Internet Explorer 9 standardite alusel</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'> Migreeri brauser Internet Explorer 9 versioonile </a> või uuenda operatsioonisüsteem Windows 8 platvormile.",
				oldBrowserExplain: "Antud brauser ei toeta automaatset pisipiltide koostamist pildiandmetest, mis on laaditud tuuri kirjeldavale kaardile. Teil on võimalik koostada kaart selles brauseris kasutamiseks, kuid peate omistama igale üles laetud pildile asjakohase pisipildi.",
				oldBrowserExplain2: "Oskuste parendamiseks, <a href='http://browsehappy.com/' target='_blank'>uuendage oma brauserit</a> või <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>Google Chrome Frame for Internet Explorer aktiveerimiseks</a>.",
				oldBrowserExplain3: "Kaardi tuuri koostaja ei tööta Windows XP operatsioonisüsteemi Internet Explorer 10 versiooniga.",
				oldBrowserClose: "Sulge"
			},
			mobileHTML: {
				showIntro: "KUVA PEALKIRI",
				hideIntro: "PEIDA PEALKIRI",
				navList: "Loend",
				navMap: "Kaart",
				navInfo: "Meedia",
				introStartBtn: "Algus"
			},
			desktopHTML: {
				storymapsText: "Kaardilugu",
				builderButton: "Vaheta muutmise režiimile",
				facebookTooltip: "Jaga Facebookis",
				twitterTooltip: "Jaga Twitteris",
				bitlyTooltip: "Hangi lühike link",
				bitlyStartIndex: "Link hetke asukohale"
			},
			builderHTML: {
				panelHeader: "RAKENDUSE KONFIGURATSIOON",
				buttonSave: "SALVESTA",
				buttonSettings: "Seaded",
				buttonShare: "Jaga",
				buttonView: "Vaaterežiim",
				buttonItem: "Ava veebirakenduse sisu",
				buttonHelp: "Abi",
				buttonOrganize: "Paiguta",
				buttonAdd: "Lisa",
				buttonImport: "Impordi",
				buttonImportDisabled: "Importimine ei ole kasutatav manustega objektiteenuste juures",
				dataEditionDisabled: "Andmete muutmine ei toimi CSV andmeallika puhul",
				dataSourceWarning: "Kaardituuri andmete kiht on muutunud. Kui objektide ID väärtused ei ole samaväärsed, on Teil targem järjekord lähtestada ja peita punktid <b>Paiguta</b> kaudu. Kui väljanimed on erinevad, on Teil targem väljade omadused lähtestada <b>andmete sakk Seaded</b> kaudu.",
				organizeWarning: "Üks või mitu interaktiivsest koostajast väljapoole lisatud punkti on peidetud.",
				dataPicError0a: "Kaardituur sisaldab <b>%NB%</b> mittevastavaid piltide aadresse.",
				dataPicError0b: "Kaardituuris võib sisalduda <b>%NB%</b> mittevastavaid piltide aadresse.",
				dataPicError1: "Kaardituurile on sobilikud piltide aadressid, mis lõppevad laiendustega: .jp(e)g, .png, .gif või .bmp.",
				dataPicError2: "Nõue ei mõjuta teie eksisteerivat publitseeritud kaardituuri, kuid interaktiivse looja kasutamiseks peate esmalt lahendama aadressi küsimused, tehes ühte järgnevatest tegevustest:",
				dataPicError3: "Muuda aadresse",
				dataPicError4: "See lisab <i>#isImage</i> mitte toetatud piltide aadresside lõppu. Enamik servereid toetab aadressi täiendeid. Kuid peale selle tegevuse sooritamist kontrollige punktide vahel navigeerides, et uuendatud piltide aadressid on toimivad. Kui kõik pildid laadivad end kenasti üles, siis võite kaardituuri salvestada. Kui <b>pildid ei ilmu, ärge salvestage kaardituuri</b>. Selle asemel laadige looja uuesti ning tehke teine toiming.",
				dataPicError5: "Piira tuur piltidele",
				dataPicError6: "See valik tähendab, et kõiki aadresse käsitletakse piltidena, kuid teil ei ole võimalik lisada videod interaktiivse looja kaudu. See toiming on tagasi võetav kui otsustate lisada videoid tulevikus.",
				dataPicError7: "Teie kaardituur on piiratud ainult piltidele, videoid ei saa lisada. Kui eemaldate selle piirangu, siis kontrollige, et Teie pildid ikka laevad korrektselt enne kaardituuri salvestamist. Teil on vajadusel võimalik taastada seda piirangut hiljem.",
				dataPicError8: "Eemalda piltide piirang",
				dataPicError9: "Kui need aadressid viitavad videomaterjalile, siis võite ignoreerida seda hoiatust. Kui need viitavad piltidele, siis palun teostage üht järgnevatest toimingutest:",
				modalCancel: "Tühista",
				modalApply: "Kehtesta",
				organizeHeader: "Organiseeri tuuri",
				organizeGeneralCaption: "Kasuta tuuri punktide sorteerimisel haaramise ja lohistamise meetodit",
				organizeDelete: "Kustuta",
				organizeHide: "Peida",
				organizeReset: "Lähtesta järjekord ja peida punktid",
				addMaxPointReached: "Olete jõudnud ikoonide poolt autoriseeritud kogumi maksimaalse arvu punktideni ning ei saa rohkem tuuri punkte lisada.<br /><br />Pidage meeles, et kui kustutate juba olemasolevaid punkte, peate taaskäivitama ka rakenduse.",
				addMaxPointReachedMobile: "Olete jõudnud maksimaalse arvu autoriseeritud punktideni ning ei saa seda pilti lisada. Vabandame.",
				addClose: "Sulge",
				addHeader: "Lisa uus tuuri punkt",
				addTabPicture: "Meedia",
				addTabInformation: "Info",
				addTabLocation: "Asukoht",
				addSelectCaption: "Vali või haara pilt",
				addNoteVideo: "Videomaterjali kasutamiseks tutvu tehnilise abi sisuga",		
				addSelectCaptionNoFileReader: "Vali pilt",	
				addChangePhoto: "Vali pilt ja pisipilt",
				addPictureResolutionIntro: "Pildi resolutsioon on nõutavast suurem:",
				addPictureResolutionOldBrowser: "Pildi resolutsioon on nõutavast suurem. Optimeeri kaardi tuuri sisu, määrates resolutsiooni madalamana kui %SOOVITUSLIK_RES%.",
				addPictureResolutionResize: "Muuda pildi resolutsioon %RESOLUTSIOON%",
				addPictureResolutionKeep: "Säilita algne resolutsioon %RESOLUTSIOON%",
				addSelectThumbnail: "Vali pisipilt",
				addNoThumbSelected: "Ühtegi pisipilti ei ole valitud",
				addThumbSelected: "Valitud",
				addCameraSettingsHeader: "KAAMERA SEADED",
				addThumbnailHeader: "PISIPILT",
				addLabelPicUrl: "Pilt",
				addLabelThumbUrl: "Pisipilt",
				addTextPlaceholderUrl: "Sisesta pildi URL",
				addTextPlaceholderUrl2: "Sisesta YouTube lehe URL",
				addTextPlaceholderUrl3: "Sisesta Vimeo lehe URL",
				addTextPlaceholderUrl4: "Sisesta videoga seotud saidi URL",
				addLabelVideo: "Video",
				addMediaVideoOther: "Muu",
				addMediaVideoHelp: "Kontrolli URL-i ja hangi vaikimisi pisipilt",
				addMediaVideoHelpTooltip1: "Kontrollimine õnnestus",
				addMediaVideoHelpTooltip2: "Kontrollimine nurjus",
				addMediaVideoHelpTooltip4: "Leia võimalus põimida video ja kopeerida video URL, mis esineb koodis",
				addLabelName: "Nimi",
				addLabelDescription: "Alapealkiri",
				addTextPlaceholder: "Kirjuta siia midagi",
				addLocatePlaceholder: "Märgi aadress või asukoht",
				addPinColor: "Värv",
				addLatitude: "Laius",
				addLongitude: "Pikkus",
				addLatitudePlaceholder: "nt 34.056",
				addLongitudePlaceholder: "nt -117.195",
				addUploading: "Laadin tuuri punkti",
				addSave: "Lisa tuuri punkt",
				addMobileUploading: "Laen pilti",
				addMobileName: "Sisesta nimi",
				addMobileNameMandatory: "Viga, palun sisesta nimi.",
				addMobileError: "Midagi läks valesti. Vabandame.",
				settingsHeader: "Rakenduse seaded",
				settingsTabLayout: "Kujundus",
				settingsTabColor: "Värvid",
				settingsTabLogo: "Päis",
				settingsTabFields: "Andmed",
				settingsTabExtent: "Kuvaulatus",
				settingsTabZoom: "Suumimise tase",
				settingsLayoutExplain: "Vali meelepärane rakenduse kujundus.",
				settingsLayoutProfessional: "Kolme paneeliga kujundus",
				settingsLayoutModern: "Integreeritud kujundus",
				settingsLayoutSelected: "Valitud kujundus",
				settingsLayoutSelect: "Vali see kujundus",
				settingsLayoutNote: "Pange tähele, et videoid kasutavad punktid paigutatakse vastava plakatina video alla ka situatsioonis, kui antud valik on välja lülitatud.",
				settingsLayoutLocBtn: "Kuva \'Määra asukoht\' nupp",
				settingsLayoutLocBtnHelp: "Antud funktsionaalsus on toetatud enamikes mobiilsetes seadmetes ja veebibrauserites (Internet Explorer 9).",
				settingsColorExplain: "Muuda väljanägemist, valides selleks puhuks eelnevalt määratud teema või koostades ise uue.",
				settingsLabelColor: "Päise, sisu ja jaluse värvid",
				settingsLogoExplain: "Kohanda päise logo (maksimum on 250 x 50px).",
				settingsLogoEsri: "Esri logo",
				settingsLogoNone: "Logo puudub",
				settingsLogoCustom: "Valikuline logo",
				settingsLogoCustomPlaceholder: "Pildi URL",
				settingsLogoCustomTargetPlaceholder: "Kliki läbi lingi",
				settingsLogoSocialExplain: "Kohanda päist ülemise paremal pool asuva lingi kaudu.",
				settingsLogoSocialText: "Tekst",
				settingsLogoSocialLink: "Link",
				settingsLogoSocialDisabled: "See funktsionaalsus on administraatori poolt välja lülitatud",
				settingsDataFieldsExplain: "Vali foto nime, selgitava teksti ja värvi väljad.",
				settingsDataFieldsError: "Rakendus ei suuda määrata sobivat nime, selgitavat teksti ega värvi andmeid. Palun valige siin kasutamiseks vastavad väljad. Vastavad parameetrid on hiljem muudetavad.",
				settingsFieldsLabelName: "Nimi",
				settingsFieldsLabelDescription: "Alapealkiri",
				settingsFieldsLabelColor: "Värv",
				settingsFieldsReset: "Lähtesta väljade valik",
				settingsExtentExplain: "Määrake kaardi tuuri sisemine kuvaulatus läbi alloleva interaktiivse kaardi.",
				settingsExtentExplainBottom: "Teie määratud kuvaulatus muudab veebikaardi sisemist ulatust. Pange tähele, et seda ulatust ei kasutata, kui see ei ole esimeses tuuri punktis. Sel juhul paigutatakse tuuri avamine esimese punkti alusel.",
				settingsExtentDateLineError: "Ulatus ei saa ületada 180° pikkuskraadi",
				settingsExtentDateLineError2: "Viga ulatuse arvutamisel",
				settingsExtentDrawBtn: "Joonista uus ulatus",
				settingsExtentModifyBtn: "Muuda ulatust",
				settingsExtentApplyBtn: "Kaardituuri eelvaade",
				settingsExtentUseMainMap: "Kasuta kaardituuri kuvaulatust",
				settingsZoomExplain: "Määra looga seotud punktidele suum järgneva juhisega (valikuline).",
				settingsLabelZoom: "Mõõtkava/tase",
				settingsZoomFirstValue: "Puudub",
				settingsFieldError: "Palun vali väli igale loendile",
				dataTitle: "ArcGIS Online majutus",
				dataExplain: "Objektiteenus lisatakse Teie veebikaardile. Seda ei jagata kõigiga ning ainult Teil on õigus andmeid lisada, muuta ja kustutada. <br /><br />Pange tähele, et kui te jagate rakendust läbi sisu lehe, siis süsteem küsib Teilt samuti objektiteenuse jagamise kohta. See on kohustuslik samm. Teil säilivad ainuisikuliselt muutmisõigused.",
				dataNameLbl: "Teenuse nimi",
				dataFolderListLbl: "Kaust",
				dataFolderListFetching: "Haaran kaustu ...",
				dataRootFolder: "Juur",
				dataNameError: "Sisesta objektiteenusele nimi",
				dataFolderError: "Vali sobilik kaust",
				dataSrcContainsInvalidChar: "Objektiteenuse nimi sisaldab ühte või mitut vigast tähemärki (-, <, >, #, %, :, \", ?, &, +, / või \).",
				dataSrvAlreadyExistsError: "Sama nimega teenus on Teie organisatsioonis juba olemas. Palun valige mõni muu nimi.",
				dataBtnSave: "Koosta teenus",
				dataFooterProgress: "Koostamine käib",
				dataFooterSucceed: "Koostamine on lõpetatud. Laadin",
				dataFooterError: "Koostamine ei õnnestunud. Proovi uuesti",
				tabError: "Palun kontrolli vigu kõigis osades",
				introRecordBtn: "Intro",
				introRecordActivate: "Kasuta esimest punkti tutvustusena (ei ilmu karussellis)"
			},
			addPopupJS: {
				uploadingPicture: "Laen pilti",
				uploadSuccess: "Laadimine õnnestus",
				uploadError: "Viga pildi laadimisel",
				uploadError2: "Viga objekti lisamisel (vigane html tag)",
				notJpg: "Laadimiseks vali palun JPEG-formaadis pilt",
				errorNoPhoto: "Vali pilt laadimiseks",
				errorNoThumbnail: "Vali pisipilt laadimiseks",
				errorInvalidPicUrl: "Sisesta korrektne pilt (algab http(s)://, lõpeb laiendusega jpg, png, gif või bmp). Võite pildi aadressi lõppu lisada '#isImage', mis on eelneva reegli ülene.",
				errorInvalidThumbUrl: "Sisesta korrektne eelvaate pilt (algab http(s)://, lõpeb laiendusega jpg, png, gif või bmp).",
				errorInvalidVideoUrl: "Sisesta kehtiv video URL (algus stiilis http(s)://)",
				errorNoName: "Sisesta selle tuuri punktile nimetus",
				errorNoDescription: "Sisesta selle tuuri punktile selgitav tekst",
				errorNoLocation: "Määra selle tuuri punktile asukoht"
			},
			builderJS: {
				noPendingChange: "Salvestamata muudatused puuduvad",
				unSavedChangeSingular: "1 mittesalvestatud muudatus",
				unSavedChangePlural: "mittesalvestatud muudatust",
				shareStatus1: "Tuur ei ole salvestatud",
				shareStatus2: "Tuur on jagatud avalikult",
				shareStatus3: "Tuur on jagatud organisatsioonis",
				shareStatus4: "Tuur ei ole jagatud",
				popoverDiscard: "Olete kindel, et soovite loobuda salvestamata muudatustest?",
				yes: "Jah",
				no: "Ei",
				popoverLoseSave: "Kui avate sirvija, siis kaotate kõik salvestamata muudatused",
				ok: "Ok",
				popoverSaveWhenDone: "Ärge unustage salvestada, kui olete lõpetanud",
				closeWithPendingChange: "Olete kindel, et soovite tegevuse kinnitada? Teie tehtud muudatused võivad kaduma minna.",
				gotIt: "Ok",
				savingApplication: "Salvestan rakendust",
				saveSuccess: "Rakenduse salvestamine õnnestus",
				saveError: "Salvestamine ebaõnnestus, palun proovi uuesti",
				saveError2: "Salvestamine nurjus vigase html tagi tõttu nimes või kirjelduses",
				saveError3: "Pealkiri ei saa olla tühi",
				dragColorPicker: "Paigutage mind ümber<br />või muutke minu värvi",
				dataWarningExtent: "Teie andmed on väljaspool veebikaardi ulatust. Neid andmeid ei saa kasutada tuuri punktidena, mistõttu vahetage nende kasutamiseks kaardi ulatust.",
				dataWarningVisibi: "Teie kaardi tuur ei ole praeguse veebikaardi ulatuses nähtav. Veenduge, et Teie kaardi tuuri kiht on nähtav %KAARDI SUURUS% suuremal kaardil.",
				dataWarningEdit: "Muuda veebikaarti",
				dataWarningClose: "Sulge",
				signIn: "Palun logige konto kaudu sisse",
				signInTwo: ", et salvestada rakendus.",
				switchBM: "Muuda aluskaarti"
			},
			organizePopupJS: {
				messageStart: "Olete valinud kustutamiseks",
				messageSinglePoint: "ühe tuuri punkti",
				messageMultiPoint: "tuuri punktid",
				messagePermantRemove: "See eemaldab jäädavalt",
				messageRecord: "kirje",
				messageRecordPlural: "kirjed",
				messageConfirm: "Teie andmebaasist. Soovite jätkata?",
				labelButtonShow: "Näita",
				labelButtonHide: "Peida"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "See kustutab jäädavalt pildi ja pisipildi",
				popoverDeleteWarningThumb: "See kustutab jäädavalt pisipildi",
				popoverUploadingPhoto: "Laadin pilti ja pisipilti",
				popoverUploadingThumbnail: "Laadin pisipilti",
				popoverUploadSuccessful: "Laadimine õnnestus",
				popoverUploadError: "Laadimine ebaõnnestus, palun proovi uuesti",
				changePicAndThumb: "Vaheta pilt",
				changeThumb: "Vaheta pisipilt",
				selectPic: "Vaheta meedia",
				selectThumb: "Vaheta pisipilt",
				uploadPicAndThumb: "Kehtesta"
			},
			headerJS:{
				editMe: "Muuda mind!",
				templateTitle: "Määra mallile pealkiri",
				templateSubtitle: "Määra mallile alampealkiri"
			},
			crossFaderJS:{
				setPicture: "Määra pildile pealkiri",
				setCaption: "Määra pildile selgitav tekst"
			},
			importPopup: {
				title: "Impordi",
				prevBtn: "Tagasi",
				nextBtn: "Järgmine"
			},
			importPopupHome: {
				header: "Kus sa oma pilte hoiad?"
			},
			onlinePhotoSharingCommon: {
				pictures: "pildid",
				videos: "videod",
				disabled: "See funktsioon on administraatori poolt välja lülitatud",
				disabledPortal: "Võimalus on blokeeritud Portal for ArcGIS lahenduses",
				header1: "Teie pildid peavad olema jagatud avalikult.",
				header2: "Importimine on limiteeritud esimeste %NB1% %MEDIA%.",
				emptyDataset: "Viga, pilte ei leitud",
				footerImport: "Impordi",
				selectAlbum: "Vali avalik album",
				selectAlbum2: "Vali album",
				pleaseChoose: "Palun vali",
				userLookup: "Otsi üles",
				userLookingup: "Otsin üles",
				csv: "CSV failis viidatud",
				advanced: "Täiendavad võimalused",
				advancedScratchLbl: "Alusta uut tuuri",
				advancedScratchTip: "Loo tühi tuur, mille saate täita viisardi abil.",
				advancedCSVLbl: "Impordi tuuri andmed CSV failist",
				advancedCSVTip: "Impordi oma tuuri sisu CSV failist.",
				advancedCommonTip: "See nõuab, et teie pildid ja videod oleks juba veebis üleval.",
				select: "Koosta valik",
				locUse: "Kasuta piltide ruumilist asukohta",
				locExplain: "Sa ei pruugi soovida kasutada piltide asukohta, sest need on pärit albumist ning tulemuseks on see, et kõigi piltide asukoht on sama.",
				locExplain2: "Sa ei pruugi soovida kasutada videote asukohta, sest need on pärit sama kasutaja seadetest ning tulemuseks on see, et kõigi videote asukoht on sama."
			},
			viewFlickr: {
				title: "Flickr import",
				header: "Sisesta oma Flickri kasutajanimi ja vali fotokogum või märksõna, mida soovid importida.",
				userInputLbl: "Sisesta kasutajanimi",
				signInMsg2: "Kasutajat ei leitud",
				selectSet: "Vali fotokogum",
				selectTag: "või vali märksõna",
				footerImportTag: "Impordi valitud märksõna",
				footerImportSet: "Impordi valitud kogum"
			},
			viewFacebook: {
				title: "Facebook import",
				header: "Tuvasta isik oma Facebooki kasutajanimega või kasuta avalikku lehte. Privaatseid albumeid saab kasutada avaliku kaardi tuuri tegemisel, mis ei eelda isiku tuvastamist Facebooki kasutajanimega, mis võimaldab hoida kommentaare ja meeldimisi privaatsena.",
				leftHeader: "Facebooki kasutajanimi",
				rightHeader: "Facebooki leht",
				pageExplain: "Facebooki leht on avalik kaubamärk/toode nagu <b>esrigis</b>. Saad lehe nime pärast esimest \'/\' lehekülje URL-il.",
				pageInputLbl: "Sisesta lehe nimi",
				lookupMsgError: "Lehte ei leitud"
			},
			viewPicasa: {
				title: "Picasa/Google+ import",
				header: "Sisesta e-mail või oma Picasa ID või Google+ konto.",
				userInputLbl: "Sisesta e-mail või ID",
				signInMsg2: "Kontot ei leitud",
				signInMsg3: "Avalikku albumit pole",
				howToFind: "Kuidas leida Picasa või Google+ konto ID-d",
				howToFind2: "Kopeeri numbrikohad esimese ja teise \'/\' vahelt Picasa või G+ lehelt"
			},
			viewCSV: {
				title: "CSV import",
				uploadBtn: "Vali või haara CSV fail",
				resultHeaderEmpty: "CSV fail on tühi",
				resultHeaderSuccess: "Edukalt laeti %NB_POINTS% punkti",
				resultHasBeenLimited: "Importimine on limiteeritud esimese %VAL1% punktini %VAL2% punktist, et hoida piiri %VAL3% punkti tuuri kohta",
				browserSupport: "Teie brauserit ei toetata, CSV failide tarbeks <a href='http://browsehappy.com/' target='_blank'>uuenda brauserit</a> või kasuta ArcGIS.com veebikaardi sirvijat (vt Abi).",
				errorLatLng: "Laiuse ja pikkuse veerge ei leitud. Võimalikud laiuskraadi väärtused on: <i>%LAT%</i> ja pikkuskraadi väärtused on: <i>%LONG%</i>.",
				errorFieldsExplain: "Laadimine nurjus, kuna sobivaid veerge ei leitud",
				errorFieldsName: "<b>Nimi</b> võimalikud väärtused on: %VAL%",
				errorFieldsDesc: "<b>Kirjeldus</b> võimalikud väärtused on: %VAL%",
				errorFieldsUrl: "<b>Pildi URL</b> võimalikud väärtused on: %VAL%",
				errorFieldsThumb: "<b>Pisipildi URL</b> võimalikud väärtused on: %VAL%",
				errorFields2Explain: "Laadimine nurjus, kuna CSV fail ei kasuta samu atribuute kui kiht järgmiste atribuutide tarbeks",
				errorFields2Name: "<b>Nimi</b> kasuta %VAL1% mitte %VAL2%",
				errorFields2Desc: "<b>Kirjeldus</b> kasuta %VAL1% mitte %VAL2%",
				errorFields2Url: "<b>Pildi URL> kasuta %VAL1% mitte %VAL2%",
				errorFields2Thumb: "<b>Pisipildi URL</b> kasuta %VAL1% mitte %VAL2%",
				resultFieldsAll: "Kõik atribuudid on imporditud",
				resultFieldsNotAll: "Järgnevad atribuudid ei ole imporditud, kuna neid ei eksisteeri kaardikihis",
				resultFieldsNotAll2: "Järgnevad atribuudid on imporditud",
				footerNextBtnResult: "Impordi veebikaarti",
				footerProgress: "Toimub importimine",
				footerSucceed: "Importimine õnnestus. Laadin"
			},
			viewYoutube: {
				title: "Youtube import",
				header: "Sisesta YouTube kasutajanimi, et leida avalikult jagatud videoid.",
				pageInputLbl: "Sisesta YouTube kasutajanimi",
				lookupMsgError: "Kasutajat ei leitud",
				howToFind: "Kuidas leida YouTube’i kasutajanime",
				howToFind2: "Kasutajanime kuvatakse videote all",
				found: "Leitud",
				noData: "Avalikke videoid ei leitud"
			},
			viewGeoTag: {
				title: "Vali ja positsioneeri oma pildid/videod",
				header: "Klikkige või puudutage pilte, mida soovite nende paigutamiseks importida.",
				headerMore: "Miks minu pildid/videod ei ole ruumiliselt paigutatud?",
				headerExplain: "Kui piltidel on kehtiv asukoht, märgitakse need automaatselt kaardile ja teise saki all olevasse loendisse.<br /><br />Vaikimisi Picasa ega Flickr piltide EXIF metainfot ei kasutada, kontrolli Flickri/Picasa seadeid privaatsuse seadetest, et see võimaldada. Võib juhtuda, et pead kogu Flickri/Picasa impordi  uuesti läbi tegema.<br /><br />Facebookis pead liikuma igale pildile, aktiveerima Muuda ning valima asukoha soovituslike valikute vahel, mis põhinevad pildiandmete EXIF sisul.",
				leftPanelTab1: "Paiguta",
				leftPanelTab2: "Paigutatud",
				clickOrTap: "Paigutamiseks klikkige kaardil või puudutage kaarti",
				clearLoc: "Tühista asukohad",
				clickDrop: "Ära impordi",
				footerImport: "Impordi",
				footerProgress: "Toimub importimine",
				footerSucceed: "Importimine õnnestus. Laadin...",
				loading: "Laen",
				error: "Piltide ruumiliste asukohtade import ebaõnnestus, asukohti ignoreeriti."
			},
			initPopup: {
				title: "Tere tulemast kaardi tuuri koostajasse",
				prevBtn: "Tagasi",
				nextBtn: "Järgmine"
			},
			initPopupHome: {
				header1: "Kus paiknevad Teie pildid või videod?",
				header2: "See nõustaja abistab sind kaardi tuuri loomisel, kasutades selleks  kas veebis olemasolevaid pilte või importides pildid sinu ArcGIS Online for Organizations kontole.",
				title1: "Need on juba veebis üleval",
				title2: "Ma pean oma pildid üles laadima",
				hostedFSTooltip: "Kasuta ArcGIS Online keskkonda, et majutada oma pilte (ei toeta videoid).",
				hostedFsNA: "Kättesaadav ainult nendele ArcGIS for Organizations kasutajatele, kellel on avaldaja ja administraatori õigused.",
				footer1: "Kui oled valmis, ära unusta oma kaarti rakenduste lehe kaudu teistega jagada.",
				footer3: "Laadi alla CSV mall",
				footer4: "\"Salvesta nimega\" kui ei saa alla laadida",
				footer4bis: "Kasuta paremat klikki ja \"Salvesta kui\" kui allalaadimine ei käivitu",
				footer5: "Loe lähemalt",
				footerProgress: "Koostamine käib",
				footerSucceed: "Koostamine oli edukas. Laadin..."
			},
			helpPopup: {
				title: "Abi",
				close: "Sulge",
				tab1: {
					title: "Tutvustus",
					div1: "Kaardi tuuri mall on loodud geograafilise teabe esitamiseks kujul, kus siduvaks elemendiks on jutustatavale loole fotod või muu meedia sisu.",
					div2: "Mall loob atraktiivse ja lihtsasti kasutatava veebirakenduse, mille abil saate väikesel hulgal paiku numbrilises järjestuses kaardil esitada. Mall on välja töötatud mistahes tüüpi veebibrauseris või nutiseadmes kasutamiseks. <br /><br />Siin on näide rakendusest, mille sarnast saate ka ise luua:",
					div4: "<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs kaardituur</a>.",
					div42: "Kui soovite vaadata näiteid teiste kasutajate loodavatest kaardituuridest, külastage <a href='http://storymaps.arcgis.com/' target='_blank'>kaardilugude veebisaidil</a> asuvat <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>galeriid</a>. Samuti saate meid jälgida Twitteri kanalis <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
					div5: "Ootame Teie tagasisidet!  Kui Teil on küsimusi, soovite küsida uusi võimalusi või arvate, et olete leidnud vea, siis palun külastage meid <a href='http://links.esri.com/storymaps/forum' target='_blank'>kaardilugude kasutajate foorumis</a>."
				},
				tab2: {
					title: "Andmed",
					div1: "Kaardi tuuri loomisel tuleb eelkõige silmas pidada kohta, kuhu pildid salvestatakse. Kaardi tuuri loomisel saab kasutada pilte, mis asuvad peamistes fotopankades, mistahes veebiserveris või objektiteenuste manustena.",
					div1a: "Vaata selle vahelehe viimast sektsiooni piltide ja videote toetatud formaatide osas.",
					div2: "Interaktiivne koostaja käib tuuri piltide haldamisega seoses välja kaks valikut:",
					div3: "<ul><li>Saate kasutada <b>veebis olevaid fotosid</b> (nt fotojagamissaidil Flickr või teie enda veebilehel talletatavaid pilte). Nendele piltidele viidatakse teie kaardituuril URL-ide kaudu.</li><li>Samuti saate <b>oma arvutist pilte üles laadida</b>. Selle üleslaadimissuvandi kasutamiseks peab Teil olema ArcGIS for Organizations konto ning publitseerija või administraatori õigused, kuna Teie jaoks luuakse automaatselt majutatav objektiteenus, kus Teie fotosid talletatakse manustena.</li></ul>",
					div4: "Peamised kasutusjuhud on:",
					div4b: "<b>Teie fotosid ei majutata</b> veel ja Teil on ArcGIS for Organizations konto. Kõige mõistlikum oleks kasutada majutatavat objektiteenust. Sarnaselt avalike fotojagamise teenustega optimeeritakse ka siin pildid selliselt, et neid saab kiiresti üles laadida ja Teil on juurdepääs ArcGIS-i platvormi administraatori- ja andmehalduse funktsioonidele.",
					div5: "<b>Te ei ole organisatsiooni liige</b>: esmalt pead pildid laadima fotode jagamise keskkonda või enda veebiserverisse. Seejärel aitab Teid tuuri looja, et saaksite kasutada neid pilte, mida jätkuvalt algses asukohas hoitakse.",
					div6: "<b>Otsid olemasoleva objektiteenuse korduvkasutust,</b> mis hoiaks pilte manustena või viitaks välistele asukohtadele: vaata täpsustavat lõiku allpool.",
					div7: "<b>Oled varasema versiooni kaardi tuuri malli kasutaja</b> ja seal on juba CSV, mis viitab sinu piltidele ja pisipiltidele: sul on võimalus importida ja täiustada oma andmeid. Tuuri looja toetab vaid CSV faili, mis sisaldab pikkuse ja laiuse veergu, aadressipõhist CSV faili saab samuti kasutada sinu veebikaardi kaudu (vt lõiku allpool).",
					div8: "Impordin veebipõhisest fotode jagamise teenustest",
					div9: "Importimise toiming viitab juba majutatud piltidele, mis on salvestatud nende URL-ide veebikaardi objektide kollektsioonis. Pilte ei hoita ArcGIS Online all. Kui piltide lingid on vigased, ei kuvata neid ka kaardi tuuri aknas ja kuvatakse teadet \"Pilt ei ole kättesaadav\". Sõltuvalt fototeenuse pakkujast, kaardi tuur ei pruugi importida piltide nime, kirjeldust ja asukohta. Neid atribuute hoitakse veebikaardil ning tehtavad muudatused ei kajastu kaardi tuuri sisus.",
					div10: "Haldan pilte veebiserveris",
					div11: "Kui soovid pilte ise majutada, pead käsitsi looma ka pisipildid. Kui kasutad pisipiltide loomiseks piltide täisresolutsiooni, siis tulemus kõige parem ei tule. Seetõttu soovitame kasutada veebipõhiseid fotode jagamise teenuseid või objektiteenuseid.",
					div12: "Kasutan olemasolevat objektiteenust või vormifaili",
					div13: "Mistahes objektiteenuse või vormifaili punkt on kasutatav kaardi tuuri andmeallikana. Pead vaid lisama selle kihina enda veebikaardile arcgis.com kaardiakna kaudu. Juhul, kui rakendus leiab sinu kihist vajalikud atribuudid, on kõik funktsioonid ka kasutatavad.",
					div14: "Võimalikud väärtused väljade nimedeks on (tõstutundlikud):",
					div151: "Nimi",
					div152: "Kirjeldus",
					div153: "Pilt",
					div154: "Pisipilt",
					div155: "Värv ",
					div16: "Kui rakendus ei leia objektiteenusest sobivaid veerge, siis vaateaken ei toimi seni, kuni veerud tekivad. CSV- ja Shape-faili kihi lisamine veebikaardile eeldab kõiki vajalikke veerge, sest vastasel korral rakenduse koostamine ei toimi.",
					div162: "Kui kasutate manuste hoidmiseks majutusteenust, <b>siis kasutatakse ainult nähtuseid, millel on kaks manust</b>. Esimene manus defineerib peamise pildi ja teine manus pisipildi.",
					div17: "Pildi ja pisipildi veerud on esmatähtsad manusteta objektiteenuses ja valikulised (aga tungivalt soovitatavad) manustega objektiteenuste korral. Kui teenuses on manused lubatud, lubab koostaja pildid üles laadida manustena. Kui ei, saad muuta vaid pildi ja pisipildi URL-i.",
					div172: "Pildi ja eelvaate välju kasutatakse alati nende olemasolu korra ja majutusteenuse manuseid ei pärita.",
					div173: "Näidiskujul CSV- ja Shape-faili saab alla laadida",
					div18: "Koostan majutatud objektiteenuse CSV- või Shape-failist",
					div19: "Kui lood majutatud objektiteenuse CSV- või Shape failist, siis manused ei ole vaikimisi toetatud. Selleks saad avada objektiteenuse sisu lehe, klikkida väikesel noolekesel ning siis on vastav valik ka nähtav. Jätkub kaardituuri piltide ja pisipiltide kasutamine, millele oled atribuutide kaudu viidanud. Valikuliselt võib pilte laadida ka objektiteenuse manustena, seda saad teha kahe pildipaneelil asuva nupu abil (\"Muuda pilti\" ja \"Muuda pisipilti\").",
					div20: "Toetatud pildiformaadid ja videod",
					div21: "Toetatud pildiformaadid on <b>.jpg, .jpeg, .png, .gif ja .bmp</b>. Kui Teie meedia ei lõpe sellise laiendusega, siis kaardituur eeldab, et tegemist on videoga, välja arvatud siis, kui tegemist on majutusteenusega (vt allpool).",
					div22: "Kaardituuri mall ei sisalda videopleierit, seega peate kasutama välist videopleierit oma videote majutuse teenusest (leidke sealt võimalused video kaasamiseks ja kopeerige vastav aadress antud koodis). Kui soovite majutada oma videoid ise, siis võite luua HTML lehe, mis sisaldab videomängijat nagu näiteks: <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Interaktiivne kaardituuri looja ei paku dialoogi videote lisamiseks majutusteenuse manustena, aga seda on võimalik teostada redigeerides oma andmeid väljaspool interaktiivset loojat. Arcgis.com kaardil võite muuta pildi välja ning suunata väärtused välistele videotele, lisades spetsiaalse parameetri video aadressi lõppu (#isVideo), seejärel käsitletakse seda meediat videona.",
					div24: "Pange tähele, et vajate kaht sobilikku pildimanust või Teie punkte ei kasutata. Videoklipi kasutamine majutusteenuse manustena ei ole võimalik ilma pildi- ja eelvaateväljata."
				},
				tab3: {
					title: "Kohandamine",
					div1: "Koostaja võimaldab mitmeid kohandamise valikuid, mis on kättesaadavad läbi ülemises paneelis oleva SEADED nupu. Kui sa ei leia vajalikku valikut, võib kasutada ka allalaaditavat versiooni, mille saad integreerida enda veebiserverisse ning kohandada seda vastavalt oma vajadustele.",
					div2: "Soovitame kasutada majutatud versiooni, välja arvatud:",
					div3: "<li>See ei paku kasutajaliidese seadistamist nagu näiteks päise taustapildi kasutus</li><li>Kui oled arendaja ning soovid rakendust omalt poolt täiustada.</li>",
					div4: "Allalaaditav versioon on konfigureeritav läbi veebikaardi või veebikaardi rakenduse keskkonna kaudu. Peamised kasutusjuhud on järgnevad:",
					div41: "Te ehitate oma kaardituuri kasutades interaktiivset loojat majutatud keskkonnas ja konfigureerite malli kaardirakenduse identifikaatoriga. Rakendatakse sätted, mille olete defineerinud interaktiivse loojaga.",
					div42: "Te loote oma kaardituuri väljaspool interaktiivset loojat ja konfigureerite malli kaardi identifikaatoriga. Te peate lugema dokumentatsiooni, et saada infot malli konfigureerimise kohta.",
					div43: "Pane tähele et interaktiivne looja on saadaval allalaetava versioonina aga mõningaste tehniliste piirangutega veebibrauserites nagu Internet Explorer vanemad versioonid kui 10.",
					div5: "Uusima malli versiooni allalaadimiseks ja kasutamise info saamiseks külasta <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub projekti lehte</a>."
				},
				tab4: {
					title: "Vihjed",
					div0: "Toetatud veebibrauserid",
					div0a: "Kaardituuri vaataja on toetatud IE8+. Interaktiivne looja on toetatud IE9+. Me testime aktiivselt kõiki enimlevinud veebibrausereid, aga kui Teil esineb tõrkeid, siis soovitame kasutada Chrome’i veebibrauserit.",
					div0b: "Kui Teil esineb tõrkeid, siis andke palun meile teada. Vahepeal proovige CSV malliga oma kaardituuri luua, kuna nii vähendate oma suhtluse interaktiivse looja keskkonnaga minimaalseks.",
					div1: "Pildid",
					div2: "Soovitame kasutada horisontaalset paigutust. Kuvasuhtega 4:3 fotod sobivad kõige paremini. Vertikaalpaigutus ei sobi väiksemate ekraanide korral nagu iPad,  pilt võib selgitava teksti varju jääda, sest tekst võtab rohkem ruumi, kui see kuvatakse kitsal ja mitte laial alal. Kuigi erinevate suuruste, kujude ja paigutusega pilte võib ühe ja sama kaardi tuuri loomisel kasutada, soovitame kasutada täpselt sama suurust ja vormi kõigi piltide korral. Sellisel juhul on kasutajal infot lihtsam jälgida.",
					div2a: "Soovitame maksimaalseks pildi suuruseks 1000 pikslit laiust x 750 pikslit pikkust põhipiltidele ning 140x93 pisipiltidele.",
					div3: "Vormindan selgitava teksti HTML märgenditega",
					div4: "Päis ja pildi pealkiri võivad sisaldada HTML teeke defineerimaks kujundust ja linke. Näiteks see kood lisab kollase lingi:",
					div4a: "Kirjuta sobiv alampealkiri oma tuurile",
					div4b: "Võtke aega, et leida sobiv alapealkiri oma tuurile. Alapealkiri on hea moodus haarata inimesi oma tuuriga ning jutustada neile sisust. Samuti on see hea koht rääkimaks oma külalistele antud kaardi asukohast. Näiteks ärge eeldage, et inimesed teavad millises linnas või külas antud tuur paikneb. Teie pealkiri võib omada HTML formaati, näiteks sisaldada linke. Samas ärge muutke pealkirja liiga pikaks. Väiksemates veebibrauserite akendes või tahvlites ei pruugi see mahtuda täielikult ekraanile ja lõigatakse osaliselt. Kui te ei oska mõelda head alapealkirja, siis jätke see tühjaks.",
					div5: "Toetatud kihid",
					div6: "Saad kaardile lisada täiendavaid toetatud kihte, et pakkuda sisu kaardituurile. Need kihid võivad sisaldada muid geograafilisi nähtusi, mida soovite kuvada lisaks kaardituuri punktidele. Näiteks uurimusalad, kõndimise või sõidu teekond, mis ühendab tuuri punkte jne. Mall kuvab abistavad lisakihid veebikaardil täpsustatud kirjelduse alusel, aga hüpikaknad ei ole kättesaadavad.",
					div7: "Hoia tuuri sisu lühikese ja löövana",
					div8: "Ühes tuuris võib olla kuni 99 punkti. Enamik tuure on loomulikult lühemad. Ära oota, et külastajad on valmis läbi käima liiga arvukalt tuuripunkte. Sinu arvates võib teema olla äärmiselt huvitav, kuid ära eelda, et nemad sama arvavad!",
					div9: "Lisainfo saamiseks külastage <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>detailset juhist</a>.",
					div10: "Kinnitusrežiim",
					div11: "Kui te soovite lisada malli mõnele teisele veebilehele iframe abil, siis lisage valikuline parameeter \"&embed\" aadressi lõppu, et eemaldada päis. Selle võimaluse võib seadistada samuti alla laetavale versioonile läbi konfiguratsioonifaili.",
					div12: "Proovige mitte kasutada kitsaid iFrame laiusi, mis põhjustavad teie tuuri automaatselt ümberlülituma väiksemale puutetundlikule ekraanile mõeldud kujundusele.  Kasutusmugavuse maksimeerimiseks. Kui olete põiminud kaardituuri oma sisu sisse, siis soovitame ikkagi lisada ka juurde lingi, et tuuri kasutajad saaksid avada tuuri täisekraanil." 
				},
				tab5: {
					title: "Publitseerin",
					div1: "Kui oled valmis, ära unusta tulemust jagada suurema auditooriumiga läbi JAGA nupu või ArcGIS Online konkreetse sisu lehe kaudu.",
					div2a: "Tuuri jagamine läbi vastava ehitaja",
					div2b: "JAGA nupp uuendab rakendust ja veebikaardi sisu. Kui teie andmed on salvestatud objektiteenusena, siis ka see uuendatakse. Kui olete lisanud muid kihte läbi ArcGIS.com kaardirakenduse, siis neid ei uuendata. Selle tulemusena võib kaardi jagatav tulemus näida oodatust teistsugune. Sisu millel on juba piisavalt (või rohkem) õiguseid, ei uuendata.",
					div2c: "Tuuri jagamine läbi ArcGIS Online keskkonna",
					div2d: "Kui jagate rakendust ArcGIS Online keskkonna kaudu, siis on vajalik uuendada kõiki sõltuvaid ressursse (veebikaart, objektiteenus, kujunduse kiht), mis ei ole samal viisil jagatud. Kui kaardituur on avalik ja üks teie ressurssidest ei ole kõigiga jagatud, siis suunatakse kasutajad ArcGIS Online’i sisselogimislehele.",
					div3t: "Objektiteenuse turvalisus",
					div3a: "Kui kasutate kaardi tuuri koostaja kaudu loodud majutatud objektiteenust, haldab rakendus teenuse turvalisust Teie eest ning Teie jääte ainsaks muutmisõigustega kasutajaks (ka juhul, kui teenus on avalik).",
					div3t2: "Enne oma tuuri jagamist laiema ringiga",
					div3: "Kontrollige, et tuur toimib kenasti ka siis kui te ei ole ArcGIS.com kontole sisse logitud. URL, mida kavatsete välja jagada, ei tohiks suunata sisselogimise lehele ega rakenduse loomise režiimi.",
					div4: "Kasulik on vaadata, kuidas kaardituur paistab iPad horisontaalses paigutuses, et olla kindel selle sobilikkuses sellele populaarsele seadmele. Selle kaudu saate parema ülevaate, millal pealkirjad katavad liiga suure osa piltidest. Samuti annab see infot, kas alapealkiri mahub ega ole liiga pikk, et seda lõigataks.",
					div5a: "Soovitus otsinguks",
					div5b: "Et aidata teistel kasutajatel ArcGIS Online otsingu kaudu oma kaardituuri leida, siis me soovitame, et te lisaksite \’Story map\’ märksõna kaardituuri sisu lehele (mitte veebikaardi sisu lehele), koos märksõnadega nagu tuuri asukoht, linn, riik ja temaatilised märksõnad nagu \'avalik kunst\', \'turisti kaart\' ja \'ajaloolised kohad\'. Need märksõnad aitavad ka meid, Esri inimesi, leidmaks lahedaid uusi näiteid tuuridest, mida saame promoda oma galeriides ja sotsiaalmeedias. Samuti soovitame teil laadida üles hea väljanägemisega pisipilt galeriile rakenduse sisu lehelt, nagu näiteks väike ekraanipilt tuurist või üks pilt sellest. Seda pilti kasutatakse automaatselt kui teie kaart lisatakse ArcGIS Online galeriisse."
				}
			},
			share: {
				firstSaveTitle: "Tuur edukalt salvestatud",
				firstSaveHeader: "Teie tuur on nüüd ArcGIS Online keskkonda salvestatud. Palun lugege järgnevaid vastuseid KKK\'st",
				firstSaveA1: "Kui te ei ole tuttav ArcGIS Online keskkonnaga või soovite otseteed redigeerimise liidesele, siis võite salvestada järgmise lingi: %LINK1%",
				firstSaveA1bis: "Tuuri võib leida samuti teie <a href='%LINK2%' target='_blank'>ArcGIS Online sisu kaustast</a>.",
				firstSaveQ2: "Kas mu tuur on jagatud?",
				firstSaveA2: "Hetkel ei ole teie tuur jagatud. Selle jagamiseks kasuta JAGA nuppu.",
				shareTitle: "Jaga oma tuuri",
				sharePrivateHeader: "Teie tuur ei ole jagatud, kas soovite seda jagada?",
				sharePrivateBtn1: "Jaga avalikult",
				sharePrivateBtn2: "Jaga oma organisatsiooniga",
				sharePrivateProgress: "Jagamine töös...",
				sharePrivateErr: "Jagamine ebaõnnestus, proovi uuesti või",
				sharePrivateOk: "Jagamine uuendatud edukalt, laen...",
				sharePreviewAsUser: "Eelvaade",
				shareHeader1: "Teie tuur on <strong>avalikult ligipääsetav</strong>.",
				shareHeader2: "Teie tuur on saadaval teie organisatsiooni liikmetele (sisselogimine nõutud).",
				shareLinkHeader: "Jaga tuuri oma inimestega",
				shareLinkOpen: "AVA",
				shareQ1Opt1: "Kuidas hoida tuuri privaatsena?",
				shareQ1Opt2: "Kuidas ma saan hoida tuuri privaatsena või jagada avalikult?",
				shareA1: "Kasutage %SHAREIMG% <a href='%LINK1%' target='_blank'>rakenduse sisu lehel</a>. Kui soovite samuti eemaldada veebikaardilt jagamist, siis kasutage selleks <a href='%LINK2%' target='_blank'>veebikaardi sisu lehte</a>.",
				shareA1bis: "Kui soovite jagamise eemaldada ka objektiteenuselt, kasutage <a href='%LINK1%' target='_blank'>objektiteenuse sisu lehte</a>.",
				shareQ2: "Kuidas ma muudan tuuri hiljem?",
				shareQ2bis: "Kuidas ma pääsen tagasi loomise liidesesse?",
				shareA2div1: "Salvestage ja taaskasutage järgnevat linki %LINK1% või kasutage <a href='%LINK2%' target='_blank'>rakenduse sisu lehte</a>.",
				shareA2div2: "Rakenduse omanikuna, ArcGIS.com sisselogituna, sisaldab rakendus nuppu interaktiivse looja avamiseks.",				
				shareQ3: "Kus on andmed majutatud?",
				shareA3: "Tuuri konfiguratsioon on salvestatud <a href='%LINK1%' target='_blank'>selle veebikaardi sisus</a> ja <a href='%LINK2%' target='_blank'>selle veebirakenduse sisus</a>. Flickri, Picasa ja Facebooki piltidele ning YouTube’i videotele viidatakse endiselt nende vastavatel saitidel ja neid ei kopeerita ArcGIS Online’i keskkonda.",
				shareWarning: "%WITH% jagamine on keelatud, kuna Te ei ole <a href='%LINK%' target='_blank'>veebikaardi</a> omanik.",
				shareWarningWith1: "avalikult",
				shareWarningWith2: "avalikult ja organisatsiooniga"
			}
        }
    })
);
