define({
  "viewer": {
    "loading": {
      "step1": "LOO LAADIMINE",
      "step2": "ANDMETE LAADIMINE",
      "step3": "ALUSTAN TUURI",
      "loadBuilder": "LÜLITU KOOSTAMISREŽIIMILE",
      "redirectSignIn": "SUUNAN ÜMBER SISSELOGIMISE LEHELE",
      "redirectSignIn2": "(Teid suunatakse peale sisselogimist siia)",
      "fail": "Kaardi tuuri laadimine ebaõnnestus. Vabandame.",
      "failButton": "Proovi uuesti"
    },
    "errors": {
      "boxTitle": "Esines tõrge",
      "portalSelf": "Totaalne viga: Portaali seadistuse hankimine nurjus",
      "invalidConfig": "Totaalne viga: vigane konfiguratsioon",
      "invalidConfigOwner": "Totaalne viga: vigane konfiguratsioon (vajalik on autoriseeritud omanik)",
      "invalidConfigNoWebmap": "Totaalne viga: Vigane konfiguratsioon (veebikaart või rakenduse tuvastaja ei ole index.html all määratud)",
      "invalidConfigNoAppDev": "Veebikaardi rakenduse identifikaatorit ega veebikaarti pole URL-i parameetrites (?appid= or ?webmap=) määratud. Faili index.html AppID ja veebikaardi konfiguratsioon on arendusrežiimis ignoreeritud.",
      "createMap": "Võimetu kaarti koostama",
      "invalidApp": "Pöördumatu tõrge. Lugu ei saa laadida",
      "noLayer": "Veebikaart ei sisalda kaardi tuuri jaoks sobivat kihti.",
      "noLayerMobile": "Selle kuvasuuruse korral kaardituuri koosturit ei toetata. Võimaluse korral muutke koosturile juurdepääsemiseks oma brauseri suurust või looge oma lugu suurema ekraaniga seadmes.",
      "noLayerMobile2": "Kaardituuri koosturi kasutamiseks pöörake oma seadet ja kasutage horisontaalpaigutust.",
      "noLayerView": "Tere tulemast kaardituuri veebirakendusse.<br />Lugu pole veel konfigureeritud.",
      "appSave": "Loo salvestamisel ilmnes tõrge",
      "mapSave": "Viga veebikaardi salvestamisel",
      "featureServiceLoad": "Viga objektiteenuse laadimisel",
      "notAuthorized": "Teil puudub õigus sellele loole juurde pääseda",
      "notAuthorizedBuilder": "Teil pole õigust kaardituuri koosturit kasutada.",
      "oldBrowserTitle": "Brauser ei ole täielikult toetatud",
      "noBuilderIE8": "Kaardi tuuri koostaja ei ole toetatud varasemaga, kui Internet Explorer 9 versiooniga.",
      "ie10Win7Explain": "Kaardi tuuri interaktiivne koostaja ei ole toetatud Windows 7 operatsioonisüsteemis kasutatava Internet Explorer 10 brauseriga, kui andmeallikas on manustega objektiteenus. Manustega objektiteenuste kasutamiseks peate <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>käsitsi muutma dokumendi ülesehitust Internet Explorer 9 standardite alusel</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'> Migreeri brauser Internet Explorer 9 versioonile </a> või uuenda operatsioonisüsteem Windows 8 platvormile.",
      "oldBrowserExplain": "Antud brauser ei toeta automaatset pisipiltide koostamist pildiandmetest, mis on laaditud tuuri kirjeldavale kaardile. Teil on võimalik koostada kaart selles brauseris kasutamiseks, kuid peate omistama igale üles laetud pildile asjakohase pisipildi.",
      "oldBrowserExplain2": "Oskuste parendamiseks, <a href='http://browsehappy.com/' target='_blank'>uuendage oma brauserit</a> või <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>Google Chrome Frame for Internet Explorer aktiveerimiseks</a>.",
      "oldBrowserExplain3": "Kaardi tuuri koostaja ei tööta Windows XP operatsioonisüsteemi Internet Explorer 10 versiooniga.",
      "oldBrowserClose": "Sulge",
      "noViewerIE2": "Püüate seda lugu vaadata vanemas brauseris, mida ei toetata. Mõned funktsioonid ei pruugi töötada ning ilmneda võib ootamatuid probleeme. Soovitame kasutada brauserit Internet Explorer 11 või mõnda muud brauserit (nt Chrome).",
      "noViewerIE3": "2017. aasta lõpus seda lugu selles brauseris enam ei laadita. Siis peate selle loo vaatamiseks kasutama toetatud brauserit.",
      "attention": "Tähelepanu!"
    },
    "mobileHTML": {
      "showIntro": "KUVA PEALKIRI",
      "hideIntro": "PEIDA PEALKIRI",
      "navList": "Loend",
      "navMap": "Kaart",
      "navInfo": "Meedia",
      "introStartBtn": "Algus"
    },
    "desktopHTML": {
      "storymapsText": "Kaardilugu",
      "builderButton": "Vaheta muutmise režiimile",
      "facebookTooltip": "Jaga Facebookis",
      "twitterTooltip": "Jaga Twitteris",
      "bitlyTooltip": "Hangi lühike link",
      "bitlyStartIndex": "Link hetke asukohale",
      "tooltipAutoplayDisabled": "See pole automaatesituse režiimis saadaval",
      "autoplayLabel": "Automaatesituse režiim",
      "autoplayExplain1": "Automaatesituse režiimis keritakse teie lugu kindla ajavahemiku järel edasi. Seda on hea kasutada kioskite või avalike kohtade ekraanidel, kuid arvestage, et muudel juhtudel võib see raskendada teie loo lugemist. See funktsioon pole väikestel ekraanidel toetatud.",
      "autoplayExplain2": "Kui see režiim on aktiveeritud, saate kasutada loo esitamise või peatamise ja liikumiskiiruse reguleerimise juhtelemente.",
      "takeTourText": "Tutvu võimalustega",
      "backToStart": "Tagasi algusesse"
    },
    "builderHTML": {
      "panelHeader": "LOO KONFIGUREERIMINE",
      "buttonSave": "SALVESTA",
      "buttonSettings": "Seaded",
      "buttonShare": "Jaga",
      "buttonView": "Vaaterežiim",
      "buttonItem": "Ava veebirakenduse sisu",
      "buttonHelp": "Abi",
      "buttonOrganize": "Paiguta",
      "buttonOrganizeAndCover": "Tuuripunktide korraldamine ja esilehe lisamine",
      "buttonAdd": "Lisa",
      "buttonImport": "Impordi",
      "buttonImportDisabled": "Piltide üleslaadimise kasutamisel pole importimisfunktsioon saadaval. Pildi üleslaadimiseks klõpsake nuppu Lisa.",
      "dataEditionDisabled": "Selle CSV andmeallika andmete muutmine on keelatud.",
      "dataSourceWarning": "Kaardiloo tuuri andmekihti on muudetud. Kui objektide ID-d pole samad, peate järjestuse ja peidetud punktid funktsiooni <b>Korralda</b> kaudu lähtestama. Erinevate väljanimede korral peate väljasätted lähtestama <b>sätete akna andmete vahekaardil</b>.",
      "organizeWarning": "Üks või mitu interaktiivsest koostajast väljapoole lisatud punkti on peidetud.",
      "dataPicError0a": "Kaardituur sisaldab <b>%NB%</b> mittevastavaid piltide aadresse.",
      "dataPicError0b": "Kaardituuris võib sisalduda <b>%NB%</b> mittevastavaid piltide aadresse.",
      "dataPicError1": "Kaardituurile on sobilikud piltide aadressid, mis lõppevad laiendustega: .jp(e)g, .png, .gif või .bmp.",
      "dataPicError2": "Nõue ei mõjuta teie eksisteerivat publitseeritud kaardituuri, kuid interaktiivse looja kasutamiseks peate esmalt lahendama aadressi küsimused, tehes ühte järgnevatest tegevustest:",
      "dataPicError3": "Muuda aadresse",
      "dataPicError4": "See toiming lisab mittetoetatud pildi-URL-ide lõppu <i>#isImage</i>. Enamik servereid toetab URL-i täiendeid. Siiski peaksite pärast selle toimingu tegemist veenduma, et värskendatud pildi-URL-id töötavad. Selleks liikuge läbi punktide. Kui kõik pildid laaditakse, saate kaardiloo tuuri nüüd salvestada. Kui <b>pilte ei laadita, ärge salvestage kaardiloo tuuri</b>. Selle asemel laadige koostur uuesti ja tehke teine toiming.",
      "dataPicError5": "Piira tuur piltidele",
      "dataPicError6": "See valik tähendab, et kõiki aadresse käsitletakse piltidena, kuid te ei saa interaktiivse koosturi kaudu videoid lisada. Kui otsustate edaspidi siiski mõne video lisada, saate selle toimingu tagasi võtta.",
      "dataPicError7": "Teie kaardiloo tuuris saab kasutada üksnes pilte. Videoid ei saa kasutada. Kui otsustate selle piirangu eemaldada, kontrollige enne kaardiloo tuuri salvestamist, kas pildid laaditakse õigesti. Vajaduse korral saate selle piirangu hiljem taastada.",
      "dataPicError8": "Eemalda piltide piirang",
      "dataPicError9": "Kui need URL-id viitavad videomaterjalile, võite seda hoiatust ignoreerida. Kui need viitavad piltidele, siis tehke ühte järgmistest.",
      "modalCancel": "Tühista",
      "modalApply": "Kehtesta",
      "organizeHeader": "Organiseeri tuuri",
      "organizeGeneralCaption": "Kasuta tuuri punktide sorteerimisel haaramise ja lohistamise meetodit",
      "organizeDelete": "Kustuta",
      "organizeHide": "Peida",
      "organizeReset": "Lähtesta järjekord ja peida punktid",
      "addMaxPointReached": "Olete jõudnud ikoonikogumi poolt lubatud maksimaalse arvu punktideni ning ei saa rohkem tuuripunkte lisada.<br /><br />Kui kustutate olemasolevad punktid, peate loo uuesti laadima.",
      "addMaxPointReachedMobile": "Olete jõudnud maksimaalse arvu autoriseeritud punktideni ning ei saa seda pilti lisada. Vabandame.",
      "addClose": "Sulge",
      "addHeader": "Lisa uus tuuri punkt",
      "addTabPicture": "Meedia",
      "addTabInformation": "Info",
      "addTabLocation": "Asukoht",
      "addSelectCaption": "Vali või haara pilt",
      "addNoteVideo": "Videomaterjali kasutamiseks tutvu tehnilise abi sisuga",
      "addSelectCaptionNoFileReader": "Vali pilt",
      "addChangePhoto": "Vali pilt ja pisipilt",
      "addPictureResolutionIntro": "Pildi resolutsioon on nõutavast suurem:",
      "addPictureResolutionOldBrowser": "Pildi resolutsioon on nõutavast suurem. Optimeeri kaardi tuuri sisu, määrates resolutsiooni madalamana kui %SOOVITUSLIK_RES%.",
      "addPictureResolutionResize": "Muuda pildi resolutsioon %RESOLUTSIOON%",
      "addPictureResolutionKeep": "Säilita algne resolutsioon %RESOLUTSIOON%",
      "addSelectThumbnail": "Vali pisipilt",
      "addNoThumbSelected": "Ühtegi pisipilti ei ole valitud",
      "addThumbSelected": "Valitud",
      "addCameraSettingsHeader": "KAAMERA SEADED",
      "addThumbnailHeader": "PISIPILT",
      "addLabelPicUrl": "Pilt",
      "addLabelThumbUrl": "Pisipilt",
      "addTextPlaceholderUrl": "Sisesta pildi URL",
      "addTextPlaceholderUrl2": "Sisesta YouTube lehe URL",
      "addTextPlaceholderUrl3": "Sisesta Vimeo lehe URL",
      "addTextPlaceholderUrl4": "Sisesta videoga seotud saidi URL",
      "addLabelVideo": "Video",
      "addMediaVideoOther": "Muu",
      "addMediaVideoHelp": "Kontrolli URL-i ja hangi vaikimisi pisipilt",
      "addMediaVideoHelpTooltip1": "Kontrollimine õnnestus",
      "addMediaVideoHelpTooltip2": "Kontrollimine nurjus",
      "addMediaVideoHelpTooltip4": "Leia võimalus põimida video ja kopeerida video URL, mis esineb koodis",
      "addLabelName": "Nimi",
      "addLabelDescription": "Alapealkiri",
      "addTextPlaceholder": "Kirjuta siia midagi",
      "addLocatePlaceholder": "Märgi aadress või asukoht",
      "addPinColor": "Värv",
      "addLatitude": "Laius",
      "addLongitude": "Pikkus",
      "addLatitudePlaceholder": "nt 34.056",
      "addLongitudePlaceholder": "nt -117.195",
      "addUploading": "Laadin tuuri punkti",
      "addSave": "Lisa tuuri punkt",
      "addMobileUploading": "Laen pilti",
      "addMobileName": "Sisesta nimi",
      "addMobileNameMandatory": "Viga, palun sisesta nimi.",
      "addMobileError": "Midagi läks valesti. Vabandame.",
      "settingsHeader": "Sätted",
      "settingsTabLayout": "Kujundus",
      "settingsTabColor": "Värvid",
      "settingsTabLogo": "Päis",
      "settingsTabFields": "Andmed",
      "settingsTabExtent": "Kuvaulatus",
      "settingsTabZoom": "Suumimise tase",
      "settingsLayoutExplain": "Valige meelepärane paigutus.",
      "settingsLayoutProfessional": "Kolme paneeliga",
      "settingsLayoutModern": "Integreeritud",
      "settingsLayoutSidePanel": "Külgpaneel",
      "settingsLayoutSelected": "Valitud kujundus",
      "settingsLayoutNew": "Uus!",
      "settingsLayoutSelect": "Vali",
      "settingsLayoutNote": "Pange tähele, et videoid kasutavate punktide korral paigutatakse pealdis video alla ka siis, kui see valik on välja lülitatud.",
      "settingsLayoutLocBtn": "Kuva 'Määra asukoht' nupp",
      "settingsLayoutLocBtnHelp": "Toetatud enamikes brauserites. Kuvatakse ainult juhul, kui kaardilugu avatakse HTTPS-i kaudu. Ei kuvata, kui lugu on manustatud.",
      "settingsColorExplain": "Muuda väljanägemist, valides selleks puhuks eelnevalt määratud teema või koostades ise uue.",
      "settingsLabelColor": "Päise, sisu ja jaluse värvid",
      "settingsLogoExplain": "Kohanda päise logo (maksimum on 250 x 50px).",
      "settingsLogoEsri": "Esri logo",
      "settingsLogoNone": "Logo puudub",
      "settingsLogoCustom": "Valikuline logo",
      "settingsLogoCustomPlaceholder": "Pildi URL",
      "settingsLogoCustomTargetPlaceholder": "Kliki läbi lingi",
      "settingsLogoSocialExplain": "Kohanda päist ülemise paremal pool asuva lingi kaudu.",
      "settingsLogoSocialText": "Tekst",
      "settingsLogoSocialLink": "Link",
      "settingsLogoSocialDisabled": "See funktsionaalsus on administraatori poolt välja lülitatud",
      "settingsDataFieldsExplain": "Vali foto nime, selgitava teksti ja värvi väljad.",
      "settingsDataFieldsError": "Rakendus ei suuda määrata sobivat nime, selgitavat teksti ega värvi andmeid. Palun valige siin kasutamiseks vastavad väljad. Vastavad parameetrid on hiljem muudetavad.",
      "settingsFieldsLabelName": "Nimi",
      "settingsFieldsLabelDescription": "Alapealkiri",
      "settingsFieldsLabelColor": "Värv",
      "settingsFieldsReset": "Lähtesta väljade valik",
      "settingsExtentExplain": "Määrake kaardiloo tuuri avalehe ulatus allpool oleva interaktiivse kaardi kaudu.",
      "settingsExtentExplainBottom": "Määratletav ulatus muudab teie kaardi avalehe ulatust. Võtke arvesse, et seda ulatust ei kasutata, kui see ei hõlma tuuri esimest punkti. Sel juhul avatakse tuur esimesele punktile tsentreerituna.",
      "settingsExtentDateLineError": "Ulatus ei saa ületada 180° pikkuskraadi",
      "settingsExtentDateLineError2": "Viga ulatuse arvutamisel",
      "settingsExtentDrawBtn": "Joonista uus ulatus",
      "settingsExtentModifyBtn": "Muuda ulatust",
      "settingsExtentApplyBtn": "Kaardituuri eelvaade",
      "settingsExtentUseMainMap": "Kasuta kaardituuri kuvaulatust",
      "settingsZoomExplain": "Määra looga seotud punktidele suum (valikuline).",
      "settingsLabelZoom": "Mõõtkava/tase",
      "settingsZoomFirstValue": "Puudub",
      "settingsFieldError": "Palun vali väli igale loendile",
      "dataTitle": "Looge majutatud kaardi tuurikiht",
      "dataExplain": "Teie piltide ja tuuripunktide jaoks luuakse uus objektikiht. Tuurikihti ei jagata juhul, kui te ei jaga oma kaardituuri.",
      "dataExplainPortal": "Kui objektikihti ei looda, võtke ühendust oma ArcGIS-i administraatoriga.",
      "dataNameLbl": "Kihi nimi",
      "dataFolderListLbl": "Kaust",
      "dataFolderListFetching": "Haaran kaustu ...",
      "dataRootFolder": "Juur",
      "dataNameError": "Sisesta objektiteenusele nimi",
      "dataFolderError": "Vali sobilik kaust",
      "dataSrcContainsInvalidChar": "Objektiteenuse nimi sisaldab ühte või mitut vigast tähemärki (-, <, >, #, %, :, \", ?, &, +, / või ).",
      "dataSrvAlreadyExistsError": "Sama nimega teenus on Teie organisatsioonis juba olemas. Palun valige mõni muu nimi.",
      "dataBtnSave": "Looge kiht",
      "dataFooterProgress": "Koostamine käib",
      "dataFooterSucceed": "Koostamine on lõpetatud. Laadin",
      "dataFooterError": "Koostamine ei õnnestunud. Proovi uuesti",
      "tabError": "Palun kontrolli vigu kõigis osades",
      "introRecordBtn": "Intro",
      "introRecordActivate": "Kasuta esimest punkti tutvustusena (ei ilmu karussellis)",
      "coverRecordActivate": "Kasuta esimest punkti esilehena",
      "coverBuilder": "Esilehe konfigureerimine",
      "cover": "Esileht",
      "showCover": "Kuva esileht",
      "editCover": "Muuda esilehte",
      "coverNoVideo": "Videot esilehe meediumina ei toetata. Valige palun pilt.",
      "coverPreview": "Esilehe vaatamiseks salvestage lugu ja seejärel avage selle eelvaade nupuga Kuva lugu.",
      "thirdPartyTerms": "Kolmanda osapoole pakutava teenuse kasutamisel nõustute selle teenusetingimustega: "
    },
    "addPopupJS": {
      "uploadingPicture": "Laen pilti",
      "uploadSuccess": "Laadimine õnnestus",
      "uploadError": "Viga pildi laadimisel",
      "uploadError2": "Viga objekti lisamisel (vigane html tag)",
      "notJpg": "Laadimiseks vali palun JPEG-formaadis pilt",
      "errorNoPhoto": "Vali pilt laadimiseks",
      "errorNoThumbnail": "Vali pisipilt laadimiseks",
      "errorInvalidPicUrl": "Sisestage kehtiv pildi URL. Selle alguses peab olema https. URL-i lõpus peab olema jpg, png, gif või bmp. Selle reegli alistamiseks lisage URL-i lõppu #isImage (ilma punktita).",
      "errorInvalidThumbUrl": "Sisestage õige pisipilt (URL-i alguses peab olema https:// ja lõpus failinimelaiend jpg, png, gif või bmp).",
      "errorInvalidVideoUrl": "Sisestage õige video URL (alguses peab olema https://).",
      "errorNoName": "Sisesta selle tuuri punktile nimetus",
      "errorNoDescription": "Sisesta selle tuuri punktile selgitav tekst",
      "errorNoLocation": "Määra selle tuuri punktile asukoht"
    },
    "builderJS": {
      "noPendingChange": "Salvestamata muudatused puuduvad",
      "unSavedChangeSingular": "1 mittesalvestatud muudatus",
      "unSavedChangePlural": "mittesalvestatud muudatust",
      "shareStatus1": "Tuur ei ole salvestatud",
      "shareStatus2": "Tuur on jagatud avalikult",
      "shareStatus3": "Tuur on jagatud organisatsioonis",
      "shareStatus4": "Tuur ei ole jagatud",
      "popoverDiscard": "Olete kindel, et soovite loobuda salvestamata muudatustest?",
      "yes": "Jah",
      "no": "Ei",
      "popoverLoseSave": "Kui avate sirvija, siis kaotate kõik salvestamata muudatused",
      "ok": "Ok",
      "popoverSaveWhenDone": "Ärge unustage salvestada, kui olete lõpetanud",
      "closeWithPendingChange": "Kas soovite selle toimingu kindlasti kinnitada? Teie muudatused lähevad kaotsi.",
      "gotIt": "Ok",
      "savingApplication": "Loo salvestamine",
      "saveSuccess": "Lugu on salvestatud",
      "saveError": "Salvestamine ebaõnnestus, palun proovi uuesti",
      "saveError2": "Salvestamine nurjus vigase html tagi tõttu nimes või kirjelduses",
      "saveError3": "Pealkiri ei saa olla tühi",
      "dragColorPicker": "Paigutage mind ümber<br />või muutke minu värvi",
      "dataWarningExtent": "Teie andmed on väljaspool veebikaardi ulatust. Neid andmeid ei saa kasutada tuuri punktidena, mistõttu vahetage nende kasutamiseks kaardi ulatust.",
      "dataWarningVisibi": "Teie kaardi tuur ei ole praeguse veebikaardi ulatuses nähtav. Veenduge, et Teie kaardi tuuri kiht on nähtav %KAARDI SUURUS% suuremal kaardil.",
      "dataWarningEdit": "Muuda veebikaarti",
      "dataWarningClose": "Sulge",
      "signIn": "Palun logige konto kaudu sisse",
      "signInTwo": "loo salvestamiseks.",
      "switchBM": "Muuda aluskaarti"
    },
    "organizePopupJS": {
      "messageStart": "Olete valinud kustutamiseks",
      "messageSinglePoint": "ühe tuuri punkti",
      "messageMultiPoint": "tuuri punktid",
      "messagePermantRemove": "See eemaldab jäädavalt",
      "messageRecord": "kirje",
      "messageRecordPlural": "kirjed",
      "messageConfirm": "Teie andmebaasist. Soovite jätkata?",
      "labelButtonShow": "Näita",
      "labelButtonHide": "Peida"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "See kustutab jäädavalt pildi ja pisipildi",
      "popoverDeleteWarningThumb": "See kustutab jäädavalt pisipildi",
      "popoverUploadingPhoto": "Laadin pilti ja pisipilti",
      "popoverUploadingThumbnail": "Laadin pisipilti",
      "popoverUploadSuccessful": "Laadimine õnnestus",
      "popoverUploadError": "Laadimine ebaõnnestus, palun proovi uuesti",
      "changePicAndThumb": "Vaheta pilt",
      "changeThumb": "Vaheta pisipilt",
      "selectPic": "Vaheta meedia",
      "selectThumb": "Vaheta pisipilt",
      "uploadPicAndThumb": "Kehtesta"
    },
    "headerJS": {
      "editMe": "Muuda mind!",
      "templateTitle": "Määra pealkiri",
      "templateSubtitle": "Määra alampealkiri",
      "edit": "Muuda"
    },
    "crossFaderJS": {
      "setPicture": "Määra pildile pealkiri",
      "setCaption": "Määra pildile selgitav tekst"
    },
    "importPopup": {
      "title": "Impordi",
      "prevBtn": "Tagasi",
      "nextBtn": "Järgmine"
    },
    "importPopupHome": {
      "header": "Kus sa oma pilte hoiad?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "pildid",
      "videos": "videod",
      "disabled": "See funktsioon on administraatori poolt välja lülitatud",
      "disabledPortal": "Selle funktsiooni kasutamiseks on nõutav, et portaalil oleks majutusserver. Võtke ühendust Portal for ArcGIS-i administraatoriga.",
      "header1": "Teie pildid peavad olema jagatud avalikult.",
      "header2": "Importimine on limiteeritud esimeste %NB1% %MEDIA%.",
      "emptyDataset": "Viga, pilte ei leitud",
      "footerImport": "Impordi",
      "selectAlbum": "Vali avalik album",
      "selectAlbum2": "Vali album",
      "pleaseChoose": "Palun vali",
      "userLookup": "Otsi üles",
      "userLookingup": "Otsin üles",
      "csv": "CSV failis viidatud",
      "advanced": "Täiendavad võimalused",
      "advancedScratchLbl": "Alusta uut tuuri",
      "advancedScratchTip": "Looge tühi tuur, millele saate lisada tuuripunkte. Meedium peab olema juba veebis. See valik ei toeta piltide üleslaadimist.",
      "advancedCSVLbl": "Impordi tuuri andmed CSV failist",
      "advancedCSVTip": "Importige tuuri sisu CSV-failist, mis viitab teie veebis olevale meediumile. See valik ei toeta piltide üleslaadimist.",
      "advancedCommonTip": "See nõuab, et teie pildid ja videod oleks juba veebis üleval.",
      "select": "Koosta valik",
      "locUse": "Kasuta piltide ruumilist asukohta",
      "locExplain": "On võimalik, et piltide asukohta pole mõistlik kasutada, kuna need võivad pärineda albumist ning tulemuseks on see, et kõigi fotode asukoht on sama.",
      "locExplain2": "On võimalik, et videote asukohta pole mõistlik kasutada, kuna need võivad pärineda kasutaja sätetest ning tulemuseks on see, et kõigi videote asukoht on sama."
    },
    "viewFlickr": {
      "title": "Flickr import",
      "header": "Piltide importimiseks sisestage oma Flickri kasutajanimi ja valige soovitud album või märksõna.",
      "userInputLbl": "Sisesta kasutajanimi",
      "signInMsg2": "Kasutajat ei leitud",
      "selectSet": "Valige album",
      "selectTag": "või vali märksõna",
      "footerImportTag": "Impordi valitud märksõna",
      "footerImportSet": "Importige valitud album"
    },
    "viewFacebook": {
      "title": "Facebook import",
      "header": "Tuvasta isik oma Facebooki kasutajanimega või kasuta avalikku lehte. Privaatseid albumeid saab kasutada avaliku kaardi tuuri tegemisel, mis ei eelda isiku tuvastamist Facebooki kasutajanimega, mis võimaldab hoida kommentaare ja meeldimisi privaatsena.",
      "leftHeader": "Facebooki kasutajanimi",
      "rightHeader": "Facebooki leht",
      "pageExplain": "Facebooki leht on avalik kaubamärk/toode nagu <b>esrigis</b>. Saad lehe nime pärast esimest '/' lehekülje URL-il.",
      "pageInputLbl": "Sisesta lehe nimi",
      "lookupMsgError": "Lehte ei leitud"
    },
    "viewPicasa": {
      "title": "Google+ import",
      "header": "Sisestage oma e-posti aadress või ID.",
      "userInputLbl": "e-post või Picasa/Google+ ID",
      "signInMsg2": "Kontot ei leitud",
      "signInMsg3": "Avalikku albumit pole",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Lisateave</a>",
      "howToFind2": "Kopeerige mis tahes Picasa lehe esimese ja teise kaldkriipsu vahel asuvad numbrikohad"
    },
    "viewCSV": {
      "title": "CSV import",
      "uploadBtn": "Vali või haara CSV fail",
      "resultHeaderEmpty": "CSV fail on tühi",
      "resultHeaderSuccess": "Laaditud punkte: %NB_POINTS%",
      "resultHasBeenLimited": "Importimine on limiteeritud esimese %VAL1% punktini %VAL2% punktist, et hoida piiri %VAL3% punkti tuuri kohta",
      "browserSupport": "Teie brauserit ei toetata, CSV failide tarbeks <a href='http://browsehappy.com/' target='_blank'>uuenda brauserit</a> või kasuta ArcGIS.com veebikaardi sirvijat (vt Abi).",
      "errorLatLng": "Laiuse ja pikkuse veerge ei leitud. Võimalikud laiuskraadi väärtused on: <i>%LAT%</i> ja pikkuskraadi väärtused on: <i>%LONG%</i>.",
      "errorFieldsExplain": "Laadimine nurjus, kuna järgmisi nõutavaid välju ei leitud",
      "errorFieldsName": "<b>Nimi</b> võimalikud väärtused on: %VAL%",
      "errorFieldsDesc": "<b>Kirjeldus</b> võimalikud väärtused on: %VAL%",
      "errorFieldsUrl": "<b>Pildi URL</b> võimalikud väärtused on: %VAL%",
      "errorFieldsThumb": "<b>Pisipildi URL</b> võimalikud väärtused on: %VAL%",
      "errorFields2Explain": "Laadimine nurjus, kuna CSV fail ei kasuta samu atribuute kui kiht järgmiste atribuutide tarbeks",
      "errorFields2Name": "<b>Nimi</b> kasuta %VAL1% mitte %VAL2%",
      "errorFields2Desc": "<b>Kirjeldus</b> kasuta %VAL1% mitte %VAL2%",
      "errorFields2Url": "<b>Pildi URL> kasuta %VAL1% mitte %VAL2%",
      "errorFields2Thumb": "<b>Pisipildi URL</b> kasuta %VAL1% mitte %VAL2%",
      "resultFieldsAll": "Kõik atribuudid on imporditud",
      "resultFieldsNotAll": "Järgmisi atribuute ei imporditud, kuna neid pole kaardikihis olemas",
      "resultFieldsNotAll2": "Järgnevad atribuudid on imporditud",
      "footerNextBtnResult": "Impordi veebikaarti",
      "footerProgress": "Toimub importimine",
      "footerSucceed": "Importimine õnnestus. Laadin"
    },
    "viewYoutube": {
      "title": "Youtube import",
      "header": "Sisesta YouTube kasutajanimi, et leida avalikult jagatud videoid.",
      "pageInputLbl": "Sisesta YouTube kasutajanimi",
      "lookupMsgError": "Kasutajat ei leitud",
      "howToFind": "Kuidas leida YouTube’i kasutajanime",
      "howToFind2": "Kasutajanime kuvatakse videote all",
      "found": "Leitud",
      "noData": "Avalikke videoid ei leitud"
    },
    "viewGeoTag": {
      "title": "Vali ja positsioneeri oma pildid/videod",
      "header": "Leitud üksused imporditakse. Klõpsake määramata asukohaga üksusi, mida soovite importida, et nende asukohad kaardil määrata.",
      "headerMore": "Abi",
      "headerExplain": "Kui klõpsate nuppu <b>Impordi</b>, imporditakse üksnes vahekaardil <b>Leitud</b> loetletud pildid või videod.<br><br>Piltide või videotega koos talletatud geoasukoha teave imporditakse automaatselt, kui see on juurdepääsetav. Üksused, millel pole geoasukohta määratud, on ära toodud vahekaardil <b>Asukoha määramiseks</b>. Sellel vahekaardil loetletud üksuse asukoha määramiseks klõpsake seda ja seejärel klõpsake kaardil soovitud asukohta.<br><br>Kui soovite üksuse vahekaardilt <b>Leitud</b> eemaldada, et seda ei imporditaks, klõpsake nuppu Ära impordi, mis kuvatakse, kui viite kursori sellele üksusele.<br><br>Näpunäide. Kui teile endale kuuluvate meediumifailide geoasukoha teavet ei impordita, vaadake üle oma konto privaatsussätted. Näiteks veenduge, et teie Flickri konto sätetes ei oleks EXIF-andmed peidetud. Kui Flickri privaatsussätetes on üleslaaditud piltide EXIF-andmete importimine välja lülitatud (see on vaikesäte), ei talletata Flickris teie piltide geoasukohti. Selle teabe talletamiseks peate pildid uuesti üles laadima või nende asukohad Flickris käsitsi määrama.",
      "leftPanelTab1": "Paiguta",
      "leftPanelTab2": "Paigutatud",
      "clickOrTap": "Asukoha määramiseks klõpsake kaarti",
      "clearLoc": "Tühista asukohad",
      "clickDrop": "Ära impordi",
      "footerImport": "Impordi",
      "footerProgress": "Toimub importimine",
      "footerSucceed": "Importimine õnnestus. Laadin...",
      "loading": "Laen",
      "error": "Piltide ruumiliste asukohtade import ebaõnnestus, asukohti ignoreeriti."
    },
    "initPopup": {
      "title": "Tere tulemast kaardi tuuri koostajasse",
      "prevBtn": "Tagasi",
      "nextBtn": "Järgmine"
    },
    "initPopupHome": {
      "header1": "Kus paiknevad Teie pildid või videod?",
      "header2": "See nõustaja abistab sind kaardi tuuri loomisel, kasutades selleks  kas veebis olemasolevaid pilte või importides pildid sinu ArcGIS Online for Organizations kontole.",
      "title1": "Need on juba veebis üleval",
      "title2": "Ma pean oma pildid üles laadima",
      "hostedFSTooltip": "Laadige pildid üles ja hoidke neid tuuris (videot ei toeta).",
      "hostedFsNA": "Peate olema publitseerija rollis või mõnes muus rollis, millel on õigused majutatud objektikihte avaldada. Võtke ühendust ArcGIS-i administraatoriga.",
      "hostedFsNA2": "Saadaval ainult ArcGIS Online'i tellimusega. <a href='%LINK%'>Registreeru tasuta prooviversiooni hankimiseks</a>",
      "footer1": "Kui oled valmis, ära unusta oma kaarti rakenduste lehe kaudu teistega jagada.",
      "footer3": "Laadi alla CSV mall",
      "footer4": "\"Salvesta nimega\" kui ei saa alla laadida",
      "footer4bis": "Kasuta paremat klikki ja \"Salvesta kui\" kui allalaadimine ei käivitu",
      "footer5": "Loe lähemalt",
      "footerProgress": "Koostamine käib",
      "footerSucceed": "Koostamine oli edukas. Laadin..."
    },
    "helpPopup": {
      "title": "Abi",
      "close": "Sulge",
      "tab1": {
        "title": "Tutvustus",
        "moreInfo": "Lisateabe saamiseks",
        "infoSites": "avage <a href='https://storymaps.arcgis.com' target='_blank'>Esri kaardilugude</a> veebilehe <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>kaardituuri jaotis</a>.",
        "mtFAQ": "Lugege <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>kaardiloo tuuri KKK-d</a>.",
        "myStories": "Veebilehe jaotises <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Minu lood</a> saate kaardituure hallata ja neid vigade osas kontrollida.",
        "div1": "Kaardi tuuri mall on loodud geograafilise teabe esitamiseks kujul, kus siduvaks elemendiks on jutustatavale loole fotod või muu meedia sisu.",
        "div2": "Mall loob pilkupüüdva ja kergesti kasutatava veebirakenduse, mille abil saate väikesel hulgal paiku numbrilises järjestuses kaardil esitada ja mida kasutajad saavad sirvida. Mall on välja töötatud mistahes tüüpi veebibrauseris või seadmes (sh nutitelefonis ja tahvelarvutis) kasutamiseks. <br /><br />",
        "div42": "Teiste kasutajate loodud kaardituuride näidete vaatamiseks <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>külastage galeriid</a> <a href='https://storymaps.arcgis.com/' target='_blank'>Kaardilugude veebilehel</a>. Saate meid jälgida ka Twitteris: <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Soovime kuulda teie arvamust! Andke meile teada, millised probleemid teil on või milliseid uusi funktsioone te soovite, külastades kaardilugude foorumit <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonetis.</a>"
      },
      "tab2": {
        "title": "Andmed",
        "div1": "Kaardituuri loomisel tuleb eelkõige silmas pidada kohta, kuhu pildid salvestatakse. Kaardituuri loomisel saab kasutada pilte, mis asuvad fotode jagamise keskkondades, mistahes veebiserveris või mis laaditakse üles kettalt.",
        "div1a": "Vaata selle vahelehe viimast sektsiooni piltide ja videote toetatud formaatide osas.",
        "div2": "Interaktiivne koostaja käib tuuri piltide haldamisega seoses välja kaks valikut:",
        "div3": "<ul><li>Kasutada saate <b>fotosid, mis on juba veebi üles laaditud</b>, näiteks pilte, mis on talletatud Flickris või Google+ kontol või teie enda veebiserveris. Teie kaardiloo tuuris viidatakse neile piltidele nende URL-ide kaudu.</li><li>Soovi korral saate ka <b>fotod oma arvutist üles laadida</b> otse kaardituuri. Selle üleslaadimisvariandi kasutamiseks peab teil olema ArcGIS-i tellimus ning avaldaja või administraatori õigused, kuna teie jaoks luuakse automaatselt hostitud objektide teenus, kus teie fotod talletatakse manustena.</li></ul>",
        "div4": "Peamised kasutusjuhud on:",
        "div4b": "<b>Teie fotod on veel majutamata</b> ning teil on ArcGIS Online tellimus: sobiv valik oleks kasutada majutusteenust. Analoogiliselt nagu fotode jagamise keskkondades, optimeeritakse ka siin pilte selliselt, et laadida neid kiiresti üles, kasutades selleks ArcGIS platvormi andmehalduse ja administreerimise oskusi.",
        "div5": "<b>Te ei ole organisatsiooni liige</b>: esmalt pead pildid laadima fotode jagamise keskkonda või enda veebiserverisse. Seejärel aitab Teid tuuri looja, et saaksite kasutada neid pilte, mida jätkuvalt algses asukohas hoitakse.",
        "div6": "<b>Otsid olemasoleva objektiteenuse korduvkasutust,</b> mis hoiaks pilte manustena või viitaks välistele asukohtadele: vaata täpsustavat lõiku allpool.",
        "div7": "<b>Oled varasema versiooni kaardi tuuri malli kasutaja</b> ja seal on juba CSV, mis viitab sinu piltidele ja pisipiltidele: sul on võimalus importida ja täiustada oma andmeid. Tuuri looja toetab vaid CSV faili, mis sisaldab pikkuse ja laiuse veergu, aadressipõhist CSV faili saab samuti kasutada sinu veebikaardi kaudu (vt lõiku allpool).",
        "div8": "Impordin veebipõhisest fotode jagamise teenustest",
        "div9a": "Facebooki tuge ei pakuta enam, ${learn}.",
        "learn": "lisateave",
        "div9": "Importimise toiming viitab juba majutatud piltidele, mis on salvestatud nende URL-ide veebikaardi objektide kollektsioonis. Pilte ei hoita ArcGIS Online all. Kui piltide lingid on vigased, ei kuvata neid ka kaardi tuuri aknas ja kuvatakse teadet \"Pilt ei ole kättesaadav\". Sõltuvalt fototeenuse pakkujast, kaardi tuur ei pruugi importida piltide nime, kirjeldust ja asukohta. Neid atribuute hoitakse veebikaardil ning tehtavad muudatused ei kajastu kaardi tuuri sisus.",
        "div10": "Haldan pilte veebiserveris",
        "div11": "Kui otsustate oma pildid majutada enda veebiserveris (mitte kasutada Flickris või Google+ kontol asuvaid pilte või otse tuuri üles laaditud pilte), peate pisipildid ehk eelvaated oma piltide jaoks käsitsi looma. Täissuuruses piltide kasutamine eelvaate jaoks pole soovitatav, kuna sel juhul laaditakse pildid aeglaselt. Sellest <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>KKK-st</a> leiate näpunäiteid piltide suuruse muutmiseks, kui kavatsete neile veebis otse URL-i kaudu juurde pääseda.",
        "div12": "Olemasolevate GIS-i andmete kasutamine",
        "div13": "Kaardituuri andmeallikana saab kasutada igasugust punkte sisaldavat objektiteenust, CSV-faili või Shape faili, kui see sisaldab sellist väljakomplekti, mida rakendus eeldab. Teil tuleb see lisada kihina ArcGIS-i veebikaardile ja seejärel kaarti jagada, luues kaardituuri.",
        "div14": "Väljanimedena toetatakse väärtusi (tõstutundlikud):",
        "div151": "Nimi",
        "div152": "Kirjeldus",
        "div153": "Pilt",
        "div154": "Pisipilt",
        "div155": "Värv ",
        "div16": "Kui rakendus ei leia objektiteenusest sobivaid veerge, siis vaateaken ei toimi seni, kuni veerud tekivad. CSV- ja Shape-faili kihi lisamine veebikaardile eeldab kõiki vajalikke veerge, sest vastasel korral rakenduse koostamine ei toimi.",
        "div162": "Kui kasutate manuste hoidmiseks majutusteenust, <b>siis kasutatakse ainult nähtuseid, millel on kaks manust</b>. Esimene manus defineerib peamise pildi ja teine manus pisipildi.",
        "div17": "Pildi ja pisipildi veerud on esmatähtsad manusteta objektiteenuses ja valikulised (aga tungivalt soovitatavad) manustega objektiteenuste korral. Kui teenuses on manused lubatud, lubab koostaja pildid üles laadida manustena. Kui ei, saad muuta vaid pildi ja pisipildi URL-i.",
        "div172": "Pildi ja eelvaate välju kasutatakse alati nende olemasolu korra ja majutusteenuse manuseid ei pärita.",
        "div173": "Näidiskujul CSV- ja Shape-faili saab alla laadida",
        "div174": "Olemasolevate GIS-i andmete kasutamise kohta leiate lisateavet sellest <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>KKK-st</a>.",
        "div18": "Koostan majutatud objektiteenuse CSV- või Shape-failist",
        "div19": "Kui lood majutatud objektiteenuse CSV- või Shape failist, siis manused ei ole vaikimisi toetatud. Selleks saad avada objektiteenuse sisu lehe, klikkida väikesel noolekesel ning siis on vastav valik ka nähtav. Jätkub kaardituuri piltide ja pisipiltide kasutamine, millele oled atribuutide kaudu viidanud. Valikuliselt võib pilte laadida ka objektiteenuse manustena, seda saad teha kahe pildipaneelil asuva nupu abil (\"Muuda pilti\" ja \"Muuda pisipilti\").",
        "div20": "Toetatud pildiformaadid ja videod",
        "div21": "Flickri või Google+ piltide kasutamise korral tõlgendab kaardiloo tuur neid pilte automaatselt JPG-failidena. Kaardiloo tuuri koosturi kaudu üleslaaditavad pildid peavad olema JPG- või JPEG-vormingus. Kui viitate veebis asuvatele piltidele otse pildi URL-i kaudu, on toetatud pildivormingud järgmised: .jpg, .jpeg, .png, .gif ja .bmp. YouTube’i videod on toetatud otse.",
        "div22": "Kaardituuri mall ei sisalda videopleierit, seega peate kasutama välist videopleierit oma videote majutuse teenusest (leidke sealt võimalused video kaasamiseks ja kopeerige vastav aadress antud koodis). Kui soovite majutada oma videoid ise, siis võite luua HTML lehe, mis sisaldab videomängijat nagu näiteks: <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Interaktiivne kaardituuri looja ei paku dialoogi videote lisamiseks majutusteenuse manustena, aga seda on võimalik teostada redigeerides oma andmeid väljaspool interaktiivset loojat. Arcgis.com kaardil võite muuta pildi välja ning suunata väärtused välistele videotele, lisades spetsiaalse parameetri video aadressi lõppu (#isVideo), seejärel käsitletakse seda meediat videona.",
        "div24": "Pange tähele, et vajate kaht sobilikku pildimanust või Teie punkte ei kasutata. Videoklipi kasutamine majutusteenuse manustena ei ole võimalik ilma pildi- ja eelvaateväljata."
      },
      "tab3": {
        "title": "Kohandamine",
        "div1": "Koostaja võimaldab mitmeid kohandamise valikuid, mis on kättesaadavad läbi ülemises paneelis oleva SEADED nupu. Kui sa ei leia vajalikku valikut, võib kasutada ka allalaaditavat versiooni, mille saad integreerida enda veebiserverisse ning kohandada seda vastavalt oma vajadustele.",
        "div2": "Soovitame kasutada majutatud versiooni, välja arvatud:",
        "div3": "<li>See ei paku kasutajaliidese seadistamist nagu näiteks päise taustapildi kasutus</li><li>Kui oled arendaja ning soovid rakendust omalt poolt täiustada.</li>",
        "div4": "Allalaaditav versioon on konfigureeritav läbi veebikaardi või veebikaardi rakenduse keskkonna kaudu. Peamised kasutusjuhud on järgnevad:",
        "div41": "Te ehitate oma kaardituuri kasutades interaktiivset loojat majutatud keskkonnas ja konfigureerite malli kaardirakenduse identifikaatoriga. Rakendatakse sätted, mille olete defineerinud interaktiivse loojaga.",
        "div42": "Te loote oma kaardituuri väljaspool interaktiivset loojat ja konfigureerite malli kaardi identifikaatoriga. Te peate lugema dokumentatsiooni, et saada infot malli konfigureerimise kohta.",
        "div43": "Pane tähele et interaktiivne looja on saadaval allalaetava versioonina aga mõningaste tehniliste piirangutega veebibrauserites nagu Internet Explorer vanemad versioonid kui 10.",
        "div5": "Uusima malli versiooni allalaadimiseks ja kasutamise info saamiseks külasta <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub projekti lehte</a>."
      },
      "tab4": {
        "title": "Vihjed",
        "div0": "Toetatud veebibrauserid",
        "div0a": "Kaardituuri vaataja on toetatud IE8+. Interaktiivne looja on toetatud IE9+. Me testime aktiivselt kõiki enimlevinud veebibrausereid, aga kui Teil esineb tõrkeid, siis soovitame kasutada Chrome’i veebibrauserit.",
        "div0b": "Kui Teil esineb tõrkeid, siis andke palun meile teada. Vahepeal proovige CSV malliga oma kaardituuri luua, kuna nii vähendate oma suhtluse interaktiivse looja keskkonnaga minimaalseks.",
        "div1": "Pildid",
        "div2": "Ehkki ühes kaardiloo tuuris saab kasutada erineva suuruse, kuju ja suunaga pilte, soovitame vertikaalpaigutuse („portree“) asemel kasutada horisontaalpaigutusega („maastik“) pilte. Kõige paremini sobivad pildid kuvasuhtega 4:3. Kolme paneeliga või integreeritud paigutuse korral, kus pealdis ehk pildiallkiri kattub pildiga, võib vertikaalpaigutusega piltide kasutamine viia selleni, et suur osa pildist jääb pealdise alla. Kui vähegi võimalik, soovitame kolme paneeliga ja integreeritud paigutuse korral kindlasti kasutada pilte, mis oleksid ühesuurused ja sama kujuga. Sel viisil ei hakka piltide erinev kuju kasutajat tuuri läbimisel häirima.",
        "div2a": "Soovitame maksimaalseks pildi suuruseks 1000 pikslit laiust x 750 pikslit pikkust põhipiltidele ning 140x93 pisipiltidele.",
        "div3": "Vormindan selgitava teksti HTML märgenditega",
        "div4": "Tiitritesse saab vorminduse ja linkide määratlemiseks sisestada HTML-märgendeid. Näiteks need märgendid lisavad rohelise hüperlingi:",
        "div4aa": "<b>Looge oma külgpaneeliga tuuri jaoks esileht</b><br>Külgpaneeliga paigutus toetab esilehe lisamise võimalust. Sel viisil saate publiku tähelepanu tõmmata atraktiivse täisekraanpildiga. Külgpaneeliga tuuri jaoks esilehe konfigureerimiseks lisage esmalt tuuri vähemalt osa punkte. Seejärel klõpsake nuppu Korralda. Kuvatavas dialoogis veenduge, et tuuripunkt, mida soovite kasutada esilehe määratlemiseks, oleks tuuris esimene punkt. Märkige dialoogis ruut „Kasuta esimest punkti esilehena“. Esimese tuuripunkti nimest saab esilehel kuvatav pealkiri, selle punkti pealdisest saab alampealkiri ja punkti pilti kasutatakse esilehe pildina. Videot ei saa esilehe jaoks kasutada. Lisateavet leiate sellest <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>KKK-st</a>.</a>",
        "div4a": "Kirjuta sobiv alampealkiri oma tuurile",
        "div4b": "Pühendage tuuri jaoks paeluva alampealkirja koostamisele piisavalt aega. Alampealkiri aitab inimestes teie tuuri vastu huvi tekitada ja annab neile teada, mida tuur sisaldab. Samuti on see hea koht, kus vaatajatele teada anda, millises riigis või piirkonnas tuur aset leiab. Ärge eeldage, et inimesed teavad, kus teie tuuris käsitletav linn või asula asub. Alampealkiri ei tohiks siiski olla liiga pikk. Kui te ei suuda head alampealkirja välja mõelda, jätke see ära. Erinevalt kolme paneeliga ja integreeritud paigutusest ei toeta külgpaneeliga paigutus alampealkirja kasutamist päises. Kui kasutate külgpaneeliga paigutuses esilehe valikut, kuvatakse teie tuuri esimese punkti pealdis esilehel ja seega täidab see teie tuuri alampealkirja ülesannet.",
        "div5": "Toetatud kihid",
        "div6": "Soovi korral saate kaardiloo tuurile konteksti pakkumiseks tugikihte lisada. Need kihid võivad sisaldada muid geograafilisi objekte, mida soovite kaardil lisaks kaardiloo tuuri punktidele näidata, näiteks uuritav ala, tuuri punkte ühendav jalutus- või autosõidumarsruut jne. Kaardiloo tuuri mallis kuvatakse need täiendavad kihid teie veebikaardil määratud sümbolitega, kuid kihtide jaoks määratletud hüpikuid ei toetata. Tuuri jaoks täiendavate kihtide lisamiseks salvestage oma töö ja sulgege kaardiloo tuuri koostur. Seejärel avage oma tuuris kasutatav veebikaart. Kaardi leiate ArcGIS-i lehelt „Minu sisu“ või kaardilugude veebisaidi jaotise „Minu lood“ kaudu.",
        "div7": "Hoia tuuri sisu lühikese ja löövana",
        "div8": "Ühes tuuris võib olla kuni 99 punkti. Enamik tuure on loomulikult lühemad. Ära oota, et külastajad on valmis läbi käima liiga arvukalt tuuripunkte. Sinu arvates võib teema olla äärmiselt huvitav, kuid ära eelda, et nemad sama arvavad!",
        "div10": "Kinnitusrežiim",
        "div11": "Kui te soovite lisada malli mõnele teisele veebilehele iframe’i abil, siis lisage päise eemaldamiseks aadressi lõppu valikuline parameeter \"&embed\".",
        "div12": "Ärge kasutage kitsast iFrame’i, mis aktiveerib kaardiloo tuuri väikese ekraani vaate ehk sama vaate, mida tuuri jaoks kasutatakse mobiilsideseadmetes. Kasutuse hõlbustamiseks soovitame kaardituuri manustamisel alati lisada manustatud tuurile ka lingi, et kasutajad saaksid tuuri avada täisekraanvaates."
      },
      "tab5": {
        "title": "Publitseerin",
        "div1": "Kui oled valmis, ära unusta tulemust jagada suurema auditooriumiga läbi JAGA nupu või ArcGIS Online konkreetse sisu lehe kaudu.",
        "div2a": "Tuuri jagamine läbi vastava ehitaja",
        "div2b": "JAGA nupp uuendab rakendust ja veebikaardi sisu. Kui teie andmed on salvestatud objektiteenusena, siis ka see uuendatakse. Kui olete lisanud muid kihte läbi ArcGIS.com kaardirakenduse, siis neid ei uuendata. Selle tulemusena võib kaardi jagatav tulemus näida oodatust teistsugune. Sisu millel on juba piisavalt (või rohkem) õiguseid, ei uuendata.",
        "div2c": "Tuuri jagamine läbi ArcGIS Online keskkonna",
        "div2d": "Kui jagate rakendust ArcGIS Online keskkonna kaudu, siis on vajalik uuendada kõiki sõltuvaid ressursse (veebikaart, objektiteenus, kujunduse kiht), mis ei ole samal viisil jagatud. Kui kaardituur on avalik ja üks teie ressurssidest ei ole kõigiga jagatud, siis suunatakse kasutajad ArcGIS Online’i sisselogimislehele.",
        "div3t": "Objektiteenuse turvalisus",
        "div3a": "Kui kasutate kaardi tuuri koostaja kaudu loodud majutatud objektiteenust, haldab rakendus teenuse turvalisust Teie eest ning Teie jääte ainsaks muutmisõigustega kasutajaks (ka juhul, kui teenus on avalik).",
        "div3t2": "Enne oma tuuri jagamist laiema ringiga",
        "div3": "Kontrollige, et tuur toimib kenasti ka siis kui te ei ole ArcGIS.com kontole sisse logitud. URL, mida kavatsete välja jagada, ei tohiks suunata sisselogimise lehele ega rakenduse loomise režiimi.",
        "div4": "Kasulik on vaadata, kuidas kaardituur paistab iPad horisontaalses paigutuses, et olla kindel selle sobilikkuses sellele populaarsele seadmele. Selle kaudu saate parema ülevaate, millal pealkirjad katavad liiga suure osa piltidest. Samuti annab see infot, kas alapealkiri mahub ega ole liiga pikk, et seda lõigataks.",
        "div5a": "Soovitus otsinguks",
        "div5b": "Et aidata teistel kasutajatel ArcGIS Online otsingu kaudu oma kaardituuri leida, siis me soovitame, et te lisaksite ’Story map’ märksõna kaardituuri sisu lehele (mitte veebikaardi sisu lehele), koos märksõnadega nagu tuuri asukoht, linn, riik ja temaatilised märksõnad nagu 'avalik kunst', 'turisti kaart' ja 'ajaloolised kohad'. Need märksõnad aitavad ka meid, Esri inimesi, leidmaks lahedaid uusi näiteid tuuridest, mida saame promoda oma galeriides ja sotsiaalmeedias. Samuti soovitame teil laadida üles hea väljanägemisega pisipilt galeriile rakenduse sisu lehelt, nagu näiteks väike ekraanipilt tuurist või üks pilt sellest. Seda pilti kasutatakse automaatselt kui teie kaart lisatakse ArcGIS Online galeriisse."
      }
    },
    "share": {
      "firstSaveTitle": "Tuur on salvestatud",
      "manageStory": "Hallake oma lugu",
      "manageStoryA1": "Näpunäide: lehel %LINK1% saate kontrollida, kas tuuris on vigu, muuta selle jagamissätteid, anda sellele sotsiaalmeediasaitidel kasutamiseks sobiv välimus jne. Lisateavet funktsiooni „Minu lood“ kohta leiate %LINK2%.",
      "manageStoryA1V1": "Minu lood",
      "manageStoryA1V2": "siit",
      "shareTitle": "Jaga oma tuuri",
      "sharePrivateHeader": "Teie tuur ei ole jagatud, kas soovite seda jagada?",
      "sharePrivateBtn1": "Jaga avalikult",
      "sharePrivateBtn2": "Jaga oma organisatsiooniga",
      "sharePrivateProgress": "Jagamine töös...",
      "sharePrivateErr": "Jagamine ebaõnnestus, proovi uuesti või",
      "sharePrivateOk": "Jagamist on värskendatud, laadimine...",
      "sharePreviewAsUser": "Eelvaade",
      "shareHeader1": "Teie tuur on <strong>avalikult ligipääsetav</strong>.",
      "shareHeader2": "Teie tuur on saadaval teie organisatsiooni liikmetele (sisselogimine nõutud).",
      "shareLinkHeader": "Jagage oma tuuri",
      "shareLinkOpen": "AVA",
      "shareA1": "Kasutage nuppu %SHAREIMG% <a href='%LINK1%' target='_blank'>rakenduse üksuse lehel</a>. Kui soovite tühistada ka veebikaardi jagamise, siis kasutage <a href='%LINK2%' target='_blank'>veebikaardi üksuse lehte</a>.",
      "shareWarning": "%WITH% jagamine on keelatud, kuna Te ei ole <a href='%LINK%' target='_blank'>veebikaardi</a> omanik.",
      "shareWarningWith1": "avalikult",
      "shareWarningWith2": "avalikult ja organisatsiooniga",
      "viewStory": "Kuva lugu"
    },
    "locator": {
      "error": "Asukoht pole kättesaadav"
    },
    "saveErrorSocial": {
      "title": "Sotsiaalmeedias jagamise värskendus",
      "panel1": "Teie loo ilmet on sotsiaalmeedias täiustatud, kuid teie ArcGIS-i veebirakenduse üksuse pealkiri ei ühti teie loo pealkirjaga.",
      "panel1tooltip": "Kui lisate pealkirja, kokkuvõtte ja pisipildi, näeb teie lugu välja järgmine:",
      "panel2": "Millist pealkirja soovite sotsiaalmeedias kasutada:",
      "panel2q1": "Loo pealkiri (soovitatav)",
      "panel2q1tooltip": "Selle suvandi valimisel muudetakse teie üksuse pealkiri loo pealkirjaga samasuguseks ning sünkroonitakse täiendavad koosturis tehtud muudatused.",
      "panel2q2": "Üksuse pealkiri",
      "panel3": "Selleks et oma loo ilmet sotsiaalmeedias veelgi täiustada, kasutage portaali ${MYSTORIES}, et lisada kokkuvõte ja pisipilt.",
      "panel4": "Ära hoiata mind enam selle loo puhul",
      "mystories": "Minu lood",
      "btnSave": "Salvesta"
    },
    "bannerNotification": {
      "learnMore": "Lisateave",
      "close": "Sule",
      "dontShowAgain": "Ära kuva enam seda teadet"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Oluline teade veebiturvalisuse ja kaardilugude kohta",
      "s1h1": "Esri tegeleb kaardilugude turvalisuse tõstmisega",
      "s1p1": "Teie kaardilugude kodu on veebis. Veebikogukond tegeleb pidevalt aina paremate turbemeetmete väljatöötamise ja kasutusele võtmisega. Veebisisule juurdepääsuks kasutatakse üha enam HTTPS-i, mis pakub sisu edastamiseks Internetis turvalist ühendust. Enamik tänapäevaseid brausereid kuvab nüüd hoiatuse, kui HTTPS-i asemel on kasutatud HTTP-d. Selle uue standardi tõttu soovitame teil kindlasti kasutada kaardilugude koostamiseks ja jagamiseks HTTPS-linke ning kaardiloos veebisisu manustamise või piltidega linkimise korral üksnes HTTPS-protokolli kasutavaid URL-e.",
      "s1p2": "Sisuliselt tähendab see, et kaardilugu ja kogu selle sisu (sh pildid, kihid, manustatud rakendused ja veebisaidid) peaksid juurdepääsu lubamiseks kasutama linke, mille alguses on HTTP asemel HTTPS. Kuna enamik brausereid annab sel juhul märku, et teie lood on turvalised, on kasutajatel teie lugude vaatamisel kindlam tunne.",
      "s2h1": "Mida ma pean tegema?",
      "s2p1": "Esri loodab teha selle ülemineku kaardilugude koostajate ja lugejate jaoks lihtsaks. Kaardilugude koosturites ja lehel Minu lood on nüüd saadaval tööriistad, mis aitavad teil oma lugudest üles leida ebaturvalist sisu (HTTP) ja pakuvad soovitusi probleemi lahendamiseks. Kontrollige lood üle ja viige ebaturvaline sisu esimesel võimalusel üle HTTPS-i kasutamisele.",
      "action1": "Sule",
      "action2": "Kontrolli minu lugusid kohe",
      "action3": "Lisateave"
    },
    "embedBar": {
      "share": "Jaga",
      "fullScreen": "Täisekraan",
      "enlarge": "Kasvav",
      "newTab": "Avatakse uuel vahelehel",
      "tagline": "Kaardilugu",
      "exitFullScreen": "Välju täisekraanist"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Kas tohime teilt midagi küsida? See aitab vormida kaardilugude tulevikku.",
      "s1h1": "Teie mõtted aitavad vormida tulevikku",
      "s1p1": "Teie arvamused on meie kõige olulisem tagasiside allikas. Mida rohkem me teie kohta teame, seda paremaks saame kaardilugude funktsiooni edaspidi muuta. Meil oleks väga hea meel, kui leiaksite mõne minuti, et vastata järgmise lühikese uuringu küsimustele.",
      "s2p1": "Täname teid Esri kaardilugude kasutamise eest!",
      "action1": "Sule",
      "action2": "Vasta küsitlusele"
    }
  }
});