define(
({
		viewer: {
			loading: {
				step1: "تحميل التطبيق",
				step2: "تحميل البيانات",
				step3: "بدأ الجولة",
				fail: "عفواً، فشل أثناء تحميل جولة داخل الخريطة",
				failButton: "إعادة المحاولة"
			},
			errors: {
				boxTitle: "حدث خطأ",
				invalidConfig: "خطأ فادح: تكوين غير صحيح",
				invalidConfigOwner: "خطأ فادح: تكوين غير صحيح (يتطلب المالك المُخول)",
				invalidConfigNoWebmap: "خطأ فادح: تكوين غير صحيح (يتطلب خريطة الويب والمالك المُخول)",
				createMap: "يتعذر إنشاء الخريطة",
				invalidApp: "خطأ فادح: لا يمكن تحميل التطبيق",
				noLayer: "لا تحتوي خريطة الويب على طبقة بيانات صحيحة لجولة داخل الخريطة.",
				noLayerNoHostedFS: "لا تتضمن خريطة الويب طبقة بيانات صحيحة لـ Map Tour ولا تملك الامتيازات المطلوبة لإنشاء خدمة المعالم المستضافة.",
				noLayerMobile: "مرحباً بك في تطبيق الويب جولة داخل الخريطة. لم يتم تكوين التطبيق. لم يتم دعم منشئ جولة داخل الخريطة في أجهزة الجوال.",
				noLayerView: "مرحباً بك في تطبيق الويب جولة داخل الخريطة.<br />لم يتم تكوين التطبيق بعد.",
				noBuilderWebmapData: "منشئ Map Tour غير مدعوم على البيانات المضمنة لخريطة الويب. لاستخدام المنشئ، يجب استخدام خدمة المعالم. لاستخدام طبقة البيانات الفعلية، يجب استخدام الإصدار القابل للتنزيل من Map Tour.",
				appSave: "خطأ اثناء حفظ تطبيق الويب",
				mapSave: "خطأ أثناء حفظ خريطة الويب",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "أنت لست مخولاً لتكوين التطبيق",
				oldBrowserTitle: "التصفح غير مدعم بالكامل",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "منشئ Map Tour غير مدعوم على Internet Explorer 10  على نظام التشغيل Windows 7. يجب <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'> فرض وضع المستند إلى معايير Internet Explorer 9 يدويًا </a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'> الرجوع إلى Internet Explore 9</a>  أو الترقية إلى Windows 8.",
				oldBrowserExplain: "لا يدعم هذا المستعرض إنشاء الصورة المصغرة تلقائيًا من الصور التي قمت بتحميلها على جولة الخريطة. يمكن إنشاء جولة الخريطة باستخدام هذا المستعرض، ولكن يجب توفير صورة مصغرة منفصلة لكل من الصور التي قمت بتحميلها.",
				oldBrowserExplain2: "لتحسين القدرات، <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>قم بتنشيط إطار Google Chrome من أجل Internet Explorer</a>.",
				oldBrowserClose: "إغلاق"
			},
			mobileHTML: {
				showIntro: "عرض المقدمة",
				hideIntro: "إخفاء المقدمة",
				navList: "قائمة",
				navMap: "خريطة",
				navInfo: "معلومات"
			},
			desktopHTML: {
				storymapsText: "قصة داخل خريطة",
				builderButton: "الانتقال إلى وضع المنشئ"
			},
			builderHTML: {
				panelHeader: "تكوين التطبيق",
				buttonSave: "حفظ",
				buttonDiscard: "إلغاء الأمر",
				buttonSettings: "الإعدادات",
				buttonView: "عرض الوضع",
				buttonOrganize: "ترتيب",
				buttonAdd: "إضافة",
				modalCancel: "إلغاء الأمر",
				modalApply: "تطبيق",
				organizeHeader: "ترتيب الجولة",
				organizeGeneralCaption: "استخدام السحب والإفلات لفرز نقاط الجولة",
				organizeDelete: "حذف",
				organizeHide: "إخفاء",
				addMaxPointReached: "لقد تم الوصول إلى أقصى عدد من النقاط والمخولة عن طريق مجموعة الرموز ولا يمكن إضافة نقطة أخرى للجولة.<br /><br />لاحظ أن إذا تم حذف النقاط الحالية، فسوف تحتاج إلى إعادة تحميل التطبيق.",
				addMaxPointReachedMobile: "نأسف، وصلت إلى الحد الأقصى من النقاط المخولة ويتعذر إضافة هذه الصورة.",
				addClose: "إغلاق",
				addHeader: "إضافة نقطة جديدة للجولة",
				addTabPicture: "صورة",
				addTabInformation: "معلومات",
				addTabLocation: "موقع",
				addSelectCaption: "تحديد الصورة أو إفلاتها",
				addSelectCaptionNoFileReader: "تحديد الصورة",
				addChangePhoto: "تغير الصورة والصورة المصغرة",
				addPictureResolutionIntro: "دقة الصورة أعلى من ما هو مطلوب:",
				addPictureResolutionOldBrowser: "دقة الصورة أعلى مما هو مطلوب. قم بتحسين أداء الجولة داخل الخريطة عن طريق تحديد الدقة الأقل من %RECOMMENDED_RES%.",
				addPictureResolutionResize: "تغيير دقة الصورة إلى %RESOLUTION%",
				addPictureResolutionKeep: "الحفاظ على الدقة الأصلية %RESOLUTION%",
				addSelectThumbnail: "حدد الصورة المُصغرة",
				addNoThumbSelected: "لم يتم تحديد صورة مُصغرة",
				addThumbSelected: "مُحددة",
				addCameraSettingsHeader: "إعدادات الكاميرا",
				addThumbnailHeader: "صورة مُصغرة",
				addLabelName: "الاسم",
				addLabelDescription: "تسمية وضيحية",
				addTextPlaceholder: "أكتب شيء",
				addLocatePlaceholder: "تحديد عنوان أو مكان",
				addPinColor: "لون",
				addLatitude: "خط عرض",
				addLongitude: "خط طول",
				addLatitudePlaceholder: "مثال 34.056",
				addLongitudePlaceholder: "مثال -117.195",
				addUploading: "تحميل نقطة الجولة",
				addSave: "إضافة نقطة الجولة",
				addMobileUploading: "تحميل الصورة",
				addMobileName: "أدخل الاسم",
				addMobileNameMandatory: "خطأ، الرجاء إدخال الاسم",
				addMobileError: "نأسف، يوجد خطأ ما",
				settingsHeader: "إعدادات التطبيق",
				settingsTabLayout: "المخطط",
				settingsTabColor: "ألوان",
				settingsTabLogo: "رأس الصفحة",
				settingsTabFields: "البيانات",
				settingsTabExtent: "المدى",
				settingsTabZoom: "مستوى التكبير أو التصغير",
				settingsLayoutExplain: "تحديد مخطط التطبيق بين الأثنين المتوفرين.",
				settingsLayoutProfessional: "مخطط ثلاثي اللوحات",
				settingsLayoutModern: "مخطط متكامل",
				settingsLayoutSelected: "مخطط محدد",
				settingsLayoutSelect: "حدد هذا المخطط",
				settingsColorExplain: "تغيير الظهور عن طريق اختيار نسق مُعرف من قبل أو إنشاء الخاص بك.",
				settingsLabelColor: "ألوان الرأس والمحتوى والذيل",
				settingsLogoExplain: "تخصيص شعار (الحد الأقصى 250 x 50 px).",
				settingsLogoEsri: "شعار Esri",
				settingsLogoNone: "لا يوجد شعار",
				settingsLogoCustom: "تخصيص الشعار",
				settingsLogoCustomPlaceholder: "عنوان URL للصورة",
				settingsLogoCustomTargetPlaceholder: "انقر فوق الرابط",
				settingsLogoSocialExplain: "تخصيص عنوان الرابط الموجود أعلى اليمين.",
				settingsLogoSocialText: "النص",
				settingsLogoSocialLink: "رابط",
				settingsDataFieldsExplain: "تحديد اسم الصورة والتسمية التوضيحية وحقول الألوان.",
				settingsDataFieldsError: "لم يقم التطبيق بتحديد اسم التطبيق والتسمية التوضيحية وبيانات الألوان. يرجى تحديد الحقول لاستخدامها هنا. ويمكن تغيير الإعدادات في وقت لاحق.",
				settingsFieldsLabelName: "الاسم",
				settingsFieldsLabelDescription: "تسمية وضيحية",
				settingsFieldsLabelColor: "لون",
				settingsExtentExplain: "تعيين النطاق الأولي لـ Map Tour خلال الخريطة التفاعلية الموضحة أدناه.",
				settingsExtentExplainBottom: "يتم استخدام النطاق فقط إذا تضمن نقطة الجولة الأولى. استمرت هذه القيمة خلال النطاق الأولي لخريطة الويب.",
				settingsExtentDrawBtn: "ارسم النطاق الجديد",
				settingsExtentModifyBtn: "تحرير النطاق الحالي",
				settingsExtentApplyBtn: "التطبيق على الخريطة الرئيسية",
				settingsZoomExplain: "تحديد التكبير أو التصغير لنقاط القصة التي تلحق بالمقدمة (اختياري).",
				settingsLabelZoom: "المقياس/ المستوى",
				settingsZoomFirstValue: "لا شيء",
				settingsFieldError : "يرجى تحديد حقل في كل قائمة",
				dataHeader: "بيانات التطبيق",
				dataExplain: "لا تتضمن خريطة الويب خدمة المعالم. أكمل هذا الحوار لإنشاء خدمة المعالم المستضافة داخل حساب ArcGIS.com على المنظمة. سيتم إضافة خدمة المعالم إلى خريطة الويب ومشاركتها بشكل عام لكن يجب القيام بإضافة/تحرير وحذف الامتيازات. <br /><br /> سيكون التطبيق قابل للإظهار حتى تتمكن من مشاركته مع الآخرين.<strong> بمجرد استعداد Map Tour قم بمشاركة التطبيق خلال صفحة العناصر.</strong>",
				dataNameLbl: "اسم الخدمة",
				dataFolderListLbl: "المجلد",
				dataFolderListFetching: "جارِ البحث عن المجلدات...",
				dataRootFolder: "الجذر",
				dataNameError: "أدخل الاسم لخدمة المعلم",
				dataFolderError: "حدد المجلد الصحيح",
				dataSrcContainsInvalidChar: "يحتوي اسم خدمة المعلم على حرف غير صحيح أو أكثر  (<, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "يتواجد اسم الخدمة من قبل داخل المؤسسة. يرجى اختيار اسم مختلف.",
				dataBtnClose: "إلغاء الجولة",
				dataBtnSave: "إنشاء الخدمة",
				dataFooterProgress: "الإنشاء قيد التقدم",
				dataFooterSucceed: "تم نجاح الإنشاء. جارِ التحميل",
				dataFooterError: "خطأ أثناء الإنشاء. يرجى المحاولة مرة أخرى",
				tabError: "يرجي التحقق من وجود أخطاء في جميع علامات التبويب",
				introRecordBtn: "مقدمة",
				introRecordActivate: "استخدم النقطة الأولى كمقدمة"
			},
			addPopupJS: {
				uploadingPicture: "تحميل الصورة",
				uploadSuccess: "تحميل غير ناجح",
				uploadError: "خطأ أثناء تحميل الصورة",
				notJpg: "يرجى اختيار صورة jpeg للتحميل",
				errorNoPhoto: "اختر الصورة للتحميل",
				errorNoThumbnail: "اختر الصورة المُصغرة للتحميل",
				errorNoName: "ادخل اسم لنقطة الجولة",
				errorNoDescription: "ادخل تسمية توضيحية لنقطة الجولة",
				errorNoLocation: "تحديد الموقع لنقطة الجولة"
			},
			builderJS: {
				noPendingChange: "لا يوجد تغيير معلق",
				unSavedChangeSingular: "1 تغيير غير محفوظ",
				unSavedChangePlural: "تغييرات غير محفوظة",
				popoverDiscard: "هل تريد تجاهل أية تغييرات غير محفوظة؟",
				yes: "نعم",
				no: "لا",
				popoverLoseSave: "عند فتح العارض، سوف تخسر أية تغييرات غير محفوظة",
				ok: "موافق",
				popoverSaveWhenDone: "لا تنسى الحفظ بعد الانتهاء",
				closeWithPendingChange: "هل تريد تأكيد الإجراء؟ سوف تخسر جميع التغييرات.",
				gotIt: "موافق",
				savingApplication: "حفظ التطبيق",
				saveSuccess: "تم حفظ التطبيق بنجاح",
				saveError: "حدث فشل أثناء الحفظ، يرجى المحاولة مرة أخرى",
				dragColorPicker: "تحرك في المحيط<br />أو تغيير اللون",
				dataWarningExtent: "لديك بيانات خارج مدى خريطة الويب.ولن يتم استخدام تلك البيانات باعتبارها نقاط الجولة، ثم قم بتغيير مدى الخريطة إذا كنت تود استخدامها.",
				dataWarningVisibi: "طبقة الجولة داخل الخريطة غير مرئية داخل مدى خريطة الويب الحالي. تأكد أن طبقة جولة داخل الخريطة مرئية مع الخريطة الكبيرة %MAPSIZE%.",
				dataWarningEdit: "تحرير خريطة الويب",
				dataWarningClose: "إغلاق",
				signIn: "يرجى تسجيل الدخول بحساب داخل",
				signInTwo: "لحفظ التطبيق"
			},
			organizePopupJS: {
				messageStart: "قد تم الاختيار للحذف",
				messageSinglePoint: "نقطة الجولة الوحيدة",
				messageMultiPoint: "نقاط الجولة",
				messagePermantRemove: "ودائماً سوف تقوم بحذف",
				messageRecord: "تسجيل",
				messageRecordPlural: "تسجيلات",
				messageConfirm: "من قاعدة البيانات. هل تريد المتابعة؟",
				labelButtonShow: "إظهار",
				labelButtonHide: "إخفاء"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "تحميل الصورة والصورة المُصغرة",
				popoverUploadingThumbnail: "تحميل الصورة المُصغرة",
				popoverUploadSuccessful: "تحميل غير ناجح",
				popoverUploadError: "فشل أثناء التحميل، يرجى المحاولة مرة أخرى",
				changePicAndThumb: "تغير الصورة",
				changeThumb: "تغيير الصورة المُصغرة",
				selectPic: "تغير الصورة",
				selectThumb: "تغيير الصورة المُصغرة",
				uploadPicAndThumb: "تطبيق"
			},
			headerJS:{
				editMe: "حررني !",
				templateTitle: "تحديد عنوان القالب",
				templateSubtitle: "تحديد العنوان الفرعي للقالب"
			},
			crossFaderJS:{
				setPicture: "تحديد عنوان الصورة",
				setCaption: "تحديد التسمية التوضيحية للصورة"
			}
        }
    })
);
