define(
({
		viewer: {
			loading: {
				step1: "INDLÆSER APPLIKATION",
				step2: "INDLÆSER DATA",
				step3: "STARTER TUREN",
				loadBuilder: "SKIFTER TIL BUILDER-TILSTAND",
				fail: "Beklager, indlæsning af Map Tour mislykkedes",
				failButton: "Prøv igen"
			},
			errors: {
				boxTitle: "Der opstod en fejl",
				portalSelf: "Uoprettelig fejl: Kunne ikke hente portalkonfiguration",
				invalidConfig: "Uoprettelig fejl: Ugyldig konfiguration",
				invalidConfigOwner: "Uoprettelig fejl: Ugyldig konfiguration (autoriseret ejer kræves)",
				invalidConfigNoWebmap: "Uoprettelig fejl: Ugyldig konfiguration (webkort- eller applikationsidentifikator er ikke angivet i index.html)",
				createMap: "Kan ikke oprette kort",
				invalidApp: "Uoprettelig fejl: Applikationen kan ikke indlæses",
				noLayer: "Webkort indeholder ikke et gyldigt datalag for kortturen.",
				noLayerMobile: "Velkommen til Map Tour-webapplikationen. Applikationen er ikke konfigureret. Map Tour builder-programmet understøttes ikke på mobile enheder.",
				noLayerView: "Velkommen til Map Tour-webapplikationen.<br />Applikationen er endnu ikke konfigureret.",
				appSave: "Fejl ved lagring af webapplikationen",
				mapSave: "Fejl ved lagring af webkortet",
				featureServiceLoad: "Fejl under indlæsning af featuretjeneste",
				notAuthorized: "Du er ikke autoriseret til at få adgang til denne applikation",
				oldBrowserTitle: "Browser understøttes ikke fuldt ud",
				noBuilderIE8: "Map Tour-builderprogrammet understøttes ikke for Internet Explorer før version 9.",
				ie10Win7Explain: "Map Tour-builderprogammet understøttes ikke i Internet Explorer 10 på Windows 7, når datakilden er en featuretjeneste med vedhæftninger. Hvs du vil bruge en featuretjenste med vedhæftninger, skal du <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuelt tvinge dokumenenttilstanden til at følge Internet Explorer 9-standarden</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>nedgradere til Internet Explorer 9</a> eller opgradere til Windows 8.",
				oldBrowserExplain: "Denne browser understøtter ikke automatisk miniaturegenerering af de billeder, du overfører til din korttur. Du kan oprette en korttur med denne browser, men du skal oprette et separat miniaturebillede for hvert af de billeder, du overfører.",
				oldBrowserExplain2: "For at forbedre din oplevelse skal du <a href='http://browsehappy.com/' target='_blank'>opgradere din browser</a> eller <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivere Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserExplain3: "Map Tour-builder fungerer ikke med Internet Explorer 10 på Windows XP.",
				oldBrowserClose: "Luk"
			},
			mobileHTML: {
				showIntro: "VIS TITEL",
				hideIntro: "SKJUL TITEL",
				navList: "Liste",
				navMap: "Kort",
				navInfo: "Billeder",
				introStartBtn: "Start"
			},
			desktopHTML: {
				storymapsText: "Et historiekort",
				builderButton: "Skift til builder-tilstand",
				bitlyTooltip: "Hent et kortere link til applikationen"
			},
			builderHTML: {
				panelHeader: "APPLIKATIONSKONFIGURATION",
				buttonSave: "GEM",
				buttonDiscard: "ANNULLÉR",
				buttonSettings: "Indstillinger",
				buttonView: "Visningstilstand",
				buttonItem: "Åbn webapplikationselement",
				buttonHelp: "Hjælp",
				buttonOrganize: "Organis\ér",
				buttonAdd: "Tilføj",
				buttonImport: "Import\ér",
				buttonImportDisabled: "Import er ikke tilgængelig, når du bruger en featuretjeneste med vedhæftninger.",
				dataEditionDisabled: "Dataredigering er deaktiveret på CSV-datakilden",
				dataSourceWarning: "Datalaget til kortturen er ændret. Hvis objekt-ID\'et ikke er det samme, skal du nulstille rækkefølgen og de skjulte punkter med <b>Organis\ér</b>. Hvis feltnavnene er forskellige, skal du nulstille feltindstillingerne under<b>datafanen i Indstillinger</b>.",
				dataPicError0a: "Denne tour omfatter <b>%NB%</b> ikke-kompatible billed-URL\'er.",
				dataPicError0b: "Denne tour omfatter <b>%NB%</b> ikke-kompatible billed-URL\'er.",
				dataPicError1: "Map Tour kræver nu, at billed-URL\'er slutter med \ét af følgende filtypenavne: .jp(e)g, .png, .gif eller .bmp.",
				dataPicError2: "Dette krav vil ikke få nogen indflydelse på din eksisterende publicerede Map Tour. Men for at kunne bruge det interaktive builder-program skal du først løse URL-problemet ved at udføre \én af følgende to handlinger:",
				dataPicError3: "Redig\ér URL\'er",
				dataPicError4: "Dette vil føje <i>#isPicture</i> til slutningen af ikke-understøttede billed-URL\'er. De fleste servere understøtter URL-tilknytninger. Men når du har udført denne handling, skal du kontrollere, at de opdaterede billed-URL\ér fungerer ved at navigere gennem dine punkter. Hvis alle billeder indlæses, kan du gemme din Map Tour. Hvis <b>billederne er ødelagte, skal du ikke gemme din Map Tour</b>. Genindlæs i stedet builder-programmet, og udfør den anden handling.",
				dataPicError5: "Begræns turen til billeder",
				dataPicError6: "Denne indstiling medfører, at alle URL\ér bliver betragtet som billeder, men du vil ikke kunne tilføje videoer med det interaktive builder-program. Denne handling kan fortrydes, hvis du på et tidspunkt i fremtiden beslutter at tilføje videoer.",
				dataPicError7: "Din Map Tour er begrænset til billeder, videoer kan ikke benyttes. Hvis du vælger at fjerne denne begrænsning, skal du kontrollere, at dine billeder fortsat indlæses korrekt, før du gemmer din Map Tour. Du kan gendanne denne begrænsning på et senere tidspunkt, hvis det bliver nødvendigt.",
				dataPicError8: "Fjern billedbegrænsningen",
				dataPicError9: "Hvis disse URL\ér peger på videoer, kan du se bort fra denne advarsel. Hvis de peger på billeder, skal du udføre \én af følgende to handlinger:",
				modalCancel: "Annull\ér",
				modalApply: "Anvend",
				organizeHeader: "Organisér turen",
				organizeGeneralCaption: "Brug træk og slip til at sortere turpunkter",
				organizeDelete: "Slet",
				organizeHide: "Skjul",
				organizeReset: "Nulstil rækkefølge og skjulte punkter",
				addMaxPointReached: "Du har nået det maksimale antal punkter, der er autoriseret af de indstillede ikoner, og du kan ikke tilføje endnu et turpunkt.<br /><br />Bemærk, at hvis du sletter eksisterende punkter, skal du genindlæse applikationen.",
				addMaxPointReachedMobile: "Beklager, du har nået det maksimale antal autoriserede points og kan ikke tilføje dette billede.",
				addClose: "Luk",
				addHeader: "Tilføj et nyt turpunkt",
				addTabPicture: "Medier",
				addTabInformation: "Oplysninger",
				addTabLocation: "Sted",
				addSelectCaption: "Vælg eller slet billede",
				addNoteVideo: "Se Hjælp for at få vejledning i brugen af videoer",		
				addSelectCaptionNoFileReader: "Vælg billede",
				addChangePhoto: "Redigér billede og miniature",
				addPictureResolutionIntro: "Billedopløsningen er højere end krævet:",
				addPictureResolutionOldBrowser: "Billedopløsningen er højere end krævet. Optimér Map Tour-oplevelsen ved at indstille en opløsning, der er lavere end %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Skift billedopløsning til %RESOLUTION%",
				addPictureResolutionKeep: "Behold den oprindelige opløsning på %RESOLUTION%",
				addSelectThumbnail: "Vælg miniaturebillede",
				addNoThumbSelected: "Intet miniaturebillede valgt",
				addThumbSelected: "Valgt",
				addCameraSettingsHeader: "KAMERAINDSTILLLINGER",
				addThumbnailHeader: "MINIATUREBILLEDE",
				addLabelPicUrl: "Billede",
				addLabelThumbUrl: "Miniature",
				addTextPlaceholderUrl: "Indtast en billed-URL",
				addTextPlaceholderUrl2: "Indtast en Youtube-side-URL",
				addTextPlaceholderUrl3: "Indtast en Vimeo-side-URL",
				addTextPlaceholderUrl4: "Indtast en URL, der er indlejret i en video",
				addLabelVideo: "Video",
				addMediaVideoOther: "Andet",
				addMediaVideoHelp: "Kontroll\ér URL\'en, og hent standardminiaturen",
				addMediaVideoHelpTooltip1: "Kontrol lykkedes",
				addMediaVideoHelpTooltip2: "Kontrol mislykkedes",
				addMediaVideoHelpTooltip4: "Find indstillingen til indlejring af videoen, og kopi\ér video-URL\'en, der findes i koden",
				addLabelName: "Navn",
				addLabelDescription: "Billedtekst",
				addTextPlaceholder: "Skriv noget",
				addLocatePlaceholder: "Find en adresse eller et sted",
				addPinColor: "Farve",
				addLatitude: "Breddegrad",
				addLongitude: "Længdegrad",
				addLatitudePlaceholder: "f.eks. 34,056",
				addLongitudePlaceholder: "f.eks. -117,195",
				addUploading: "Overfører turpunkt",
				addSave: "Tilføj turpunkt",
				addMobileUploading: "Overfører billede",
				addMobileName: "Angiv et navn",
				addMobileNameMandatory: "Fejl, angiv et navn.",
				addMobileError: "Beklager, noget er gået galt",
				settingsHeader: "Applikationsindstillinger",
				settingsTabLayout: "Layout",
				settingsTabColor: "Farver",
				settingsTabLogo: "Logo",
				settingsTabFields: "Data",
				settingsTabExtent: "Område",
				settingsTabZoom: "Zoomniveau",
				settingsLayoutExplain: "Vælg det ønskede applikationslayout.",
				settingsLayoutProfessional: "Layout med tre paneler",
				settingsLayoutModern: "Integreret layout",
				settingsLayoutSelected: "Vælg layout",
				settingsLayoutSelect: "Vælg dette layout",
				settingsLayoutNote: "Bemærk, at ved punkter, der benytter videoer, vil opslaget altid være placeret under videoen, selvom denne indstilling ikke er markeret.",
				settingsColorExplain: "Skift udseende ved at vælge et foruddefineret tema eller ved at oprette dit eget.",
				settingsLabelColor: "Farver på toptekster, indhold og bundtekster",
				settingsLogoExplain: "Tilpas toptekstlogoet  (maks. 250 x 50 pixel).",
				settingsLogoEsri: "Esri-logo",
				settingsLogoNone: "Intet logo",
				settingsLogoCustom: "Brugerdefineret logo",
				settingsLogoCustomPlaceholder: "Billede-URL",
				settingsLogoCustomTargetPlaceholder: "Klik gennem-link",
				settingsLogoSocialExplain: "Tilpas header-linket øverst til højre.",
				settingsLogoSocialText: "Tekst",
				settingsLogoSocialLink: "Link",
				settingsLogoSocialDisabled: "Dette objekt er blevet deaktiveret af administratoren",
				settingsDataFieldsExplain: "Vælg fotonavn, billedtekst og farvefelter.",
				settingsDataFieldsError: "Applikationen kan ikke fastsætte et passende navn, billedtekst eller farvedata. Vælg de felter, der skal bruges her. Disse indstillinger kan ændres på et senere tidspunkt.",
				settingsFieldsLabelName: "Navn",
				settingsFieldsLabelDescription: "Billedtekst",
				settingsFieldsLabelColor: "Farve",
				settingsFieldsReset: "Nulstil feltvalget",
				settingsExtentExplain: "Indstil startudstrækningen for kortturen via det interaktive kort nedenfor.",
				settingsExtentExplainBottom: "Den udstrækning, du definerer, vil ændre din første webkortudstrækning. Bemærk, at denne udstrækning ikke bruges, hvis den ikke indeholder det første turpunkt. Hvis det er tilfældet, åbnes turen som centreret på det første punkt.",
				settingsExtentDateLineError: "Udstrækningen må ikke krydse meridianen på længdegraden 180°",
				settingsExtentDateLineError2: "Fejl ved behandlingen af udstrækningen",
				settingsExtentDrawBtn: "Tegn ny udstrækning",
				settingsExtentModifyBtn: "Redigér udstrækningen",
				settingsExtentApplyBtn: "Vis på Map Tour",
				settingsExtentUseMainMap: "Brug Map Tour-udstrækning",
				settingsZoomExplain: "Indstil zoom for historiepunkter efter introduktionen (valgfrit).",
				settingsLabelZoom: "Skala/niveau",
				settingsZoomFirstValue: "Ingen",
				settingsFieldError: "Marker et felt i hver liste",
				dataExplain: "Featuretjenesten føjes til dit webkort. Det deles ikke med nogen, og du er den eneste, der har tilføjelses-, ændrings- og sletterettigheder.<br /><br />Hvis du ændrer rettighederne for deling af applikationen, spørger programmet dig, om du vil opdatere konfigurationen for deling af din featuretjeneste. Dette kræves, for at dine brugere kan få adgang til dine data. Du vil fortsat være den eneste med redigeringsrettigheder.",
				dataNameLbl: "Tjenestenavn",
				dataFolderListLbl: "Mappe",
				dataFolderListFetching: "Henter mapper...",
				dataRootFolder: "Rod",
				dataNameError: "Indtast et navn for featuretjenesten",
				dataFolderError: "Vælg en gyldig mappe",
				dataSrcContainsInvalidChar: "Navnet på featuretjenesten indeholder et eller flere ugyldige tegn (-, <, >, #, %, :, \", ?, &, +, / eller \).",
				dataSrvAlreadyExistsError: "Der findes allerede en tjeneste med dette navn i organisationen. Vælg et andet navn.",
				dataBtnSave: "Opret tjenesten",
				dataFooterProgress: "Oprettelse i gang",
				dataFooterSucceed: "Oprettelse lykkedes. Indlæser",
				dataFooterError: "Oprettelse mislykkedes. Prøv igen",
				tabError: "Kontrollér for fejl på alle faner",
				introRecordBtn: "Introduktion",
				introRecordActivate: "Brug det første punkt som introduktion (vises ikke i karrusellen)"
			},
			addPopupJS: {
				uploadingPicture: "Overfører billede",
				uploadSuccess: "Overførsel lykkedes",
				uploadError: "Fejl ved overførsel af billede",
				notJpg: "Vælg et jpeg-foto at overføre",
				errorNoPhoto: "Vælg et billede at overføre",
				errorNoThumbnail: "Vælg et miniaturebillede at overføre",
				errorInvalidPicUrl: "Indtast en gyldig billed-URL (begynder med http(s)://, slutter med jpg, png, gif eller bmp). Du kan slutte URL\'en med \'#isPicture\' for at tilsidesætte denne regel.",
				errorInvalidThumbUrl: "Indtast en gyldig miniature-URL (begynder med http(s)://, slutter med jpg, png, gif eller bmp).",
				errorInvalidVideoUrl: "Indtast en gyldig video-URL (starter med http(s)://)",
				errorNoName: "Angiv et navn for dette turpunkt",
				errorNoDescription: "Angiv en billedtekst for dette turpunkt",
				errorNoLocation: "Indstil en position for dette turpunkt"
			},
			builderJS: {
				noPendingChange: "Ingen ventende ændringer",
				unSavedChangeSingular: "1 ikke-gemt ændring",
				unSavedChangePlural: "ikke-gemte ændringer",
				popoverDiscard: "Er du sikker på, at du vil slette nogle ikke-gemte ændringer?",
				yes: "Ja",
				no: "Nej",
				popoverLoseSave: "Ved at åbne viseren mister du eventuelle ikke-gemte ændringer",
				ok: "OK",
				popoverSaveWhenDone: "Glem ikke at gemme, når du er færdig",
				closeWithPendingChange: "Er du sikker på, at du vil bekræfte denne handling? Dine ændringer vil gå tabt.",
				gotIt: "OK",
				savingApplication: "Gemmer applikation",
				saveSuccess: "Applikation gemt med succes",
				saveError: "Lagring mislykkedes, prøv igen",
				dragColorPicker: "Flyt mig rundt,<br />eller skift min farve",
				dataWarningExtent: "Du har data uden for webkortudstrækningen. Disse data vil ikke blive brugt som turpunkter. Du skal ændre kortudstrækningen, hvis du vil bruge dem.",
				dataWarningVisibi: "Dit Map Tour-lag er ikke synligt med den aktuelle webkortudstrækning. Bekræft, at dit Map Tour-lag vil være synligt med et %MAPSIZE% større kort.",
				dataWarningEdit: "Redigér webkort",
				dataWarningClose: "Luk",
				signIn: "Log ind med en konto på",
				signInTwo: "for at gemme applikationen."
			},
			organizePopupJS: {
				messageStart: "Du har valgt at slette",
				messageSinglePoint: "ét turpunkt",
				messageMultiPoint: "turpunkter",
				messagePermantRemove: "Dette vil permanent fjerne",
				messageRecord: "post",
				messageRecordPlural: "poster",
				messageConfirm: "fra din database. Vil du fortsætte?",
				labelButtonShow: "Vis",
				labelButtonHide: "Skjul"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Dette vil slette billedet og miniaturen permanent",
				popoverDeleteWarningThumb: "Dette vil slette miniaturen permanent",
				popoverUploadingPhoto: "Overfører billede og miniaturebillede",
				popoverUploadingThumbnail: "Overfører miniaturebillede",
				popoverUploadSuccessful: "Overførsel lykkedes",
				popoverUploadError: "Overførsel mislykkedes, prøv igen",
				changePicAndThumb: "Redigér billede",
				changeThumb: "Redigér miniaturebillede",
				selectPic: "Redig\ér medier",
				selectThumb: "Redig\ér miniaturebillede",
				uploadPicAndThumb: "Anvend"
			},
			headerJS:{
				editMe: "Redig\ér mig!",
				templateTitle: "Indstil skabelontitel",
				templateSubtitle: "Indstil skabelonundertitel"
			},
			crossFaderJS:{
				setPicture: "Indstil billedtitel",
				setCaption: "Indstil billedtekst"
			},
			importPopup: {
				title: "Import\ér",
				prevBtn: "Tilbage",
				nextBtn: "Næste"
			},
			importPopupHome: {
				header: "Hvor er dine billeder lagret?"
			},
			onlinePhotoSharingCommon: {
				disabled: "Dette objekt er blevet deaktiveret af administratoren",
				disabledPortal: "Dette objekt er deaktiveret på Portal for ArcGIS",
				header1: "Billederne skal være delt med offentligheden.",
				header2: "Importen begrænses til %NB1% billeder for at overholde grænsen på %NB2% punkter pr. tour.",
				emptyDataset: "Fejl, der blev ikke fundet nogen billeder",
				footerImport: "Import\ér",
				selectAlbum: "Vælg et offentligt album",
				selectAlbum2: "Vælg et album",
				pleaseChoose: "Vælg",
				userLookup: "Slå op",
				userLookingup: "Slår op",
				csv: "Refereres til i en CSV-fil",
				fromScratch: "Start forfra",
				select: "Foretag en markering",
				locUse: "Brug billedplacering",
				locExplain: "Det er ikke sikkert, du vil benytte billedplacering, da den kan arves fra albummet, hvilket resulterer i, at alle fotos placeres samme sted."
			},
			viewFlickr: {
				header: "Indtast et Flickr-brugernavn, og vælg et fotosæt eller et nøgleord, der skal importeres.",
				userInputLbl: "Indtast et brugernavn",
				signInMsg2: "Bruger ikke fundet",
				selectSet: "Vælg et fotosæt",
				selectTag: "eller vælg et nøgleord",
				footerImportTag: "Import\ér det valgte nøgleord",
				footerImportSet: "Import\ér det valgte sæt"
			},
			viewFacebook: {
				header: "Godkend med en Facebook-konto eller brug en offentlig side. Private albums kan bruges til at oprette en offentlig Map Tour, der ikke kræver Facebook-brugergodkendelse, hvilket giver mulighed for at bevare kommentarer og \"likes\" privat.",
				leftHeader: "Facebook-bruger",
				rightHeader: "Facebook-side",
				pageExplain: "En Facebook-side er et offentligt varemærke//produkt eller en celebritet ligesom <b>esrigis</b>. Du kan få sidenavnet efter den første \'\/\' i sidens URL.",
				pageInputLbl: "Indtast et sidenavn",
				lookupMsgError: "Side ikke fundet"
			},
			viewPicasa: {
				header: "Indtast e-mail eller ID for en Picasa eller Google+-konto.",
				userInputLbl: "Indtast e-mail eller ID",
				signInMsg2: "Kontoen kunne ikke findes",
				howToFind: "Sådan findes et konto-ID",
				howToFind2: "Kopier tal mellem første og anden \'\/\' på Picasa eller en G+-side"
			},
			viewCSV: {
				uploadBtn: "Mark\ér eller slip en CSV-fil",
				resultHeaderEmpty: "CSV-filen er tom",
				resultHeaderSuccess: "Der er indlæst %NB_POINTS% punkter",
				resultHasBeenLimited: "Importen blev begrænset til de første %VAL1% punkter ud af %VAL2% for at overholde grænsen på %VAL3% punkter pr. tur",
				browserSupport: "Din browser understøttes ikke. Hvis du vil bruge en CSV-fil, skal du <a href='http://browsehappy.com/' target='_blank'>opgradere din browser</a> eller bruge ArcGIS.com-webkortviser (se Hjælp).",
				errorLatLng: "Der blev ikke fundet bredde- og længdegradsfelter. Mulige værdier for breddegrad er: <i>%LAT%</i> pg for længdegrad: <i>%LONG%</i>.",
				errorFieldsExplain: "Indlæsningen mislykkedes, de følgende påkrævede felter ikke blev fundet",
				errorFieldsName: "<b>Navn</b> mulige værdier er: %VAL%",
				errorFieldsDesc: "<b>Beskrivelse</b> mulige værdier er: %VAL%",
				errorFieldsUrl: "<b>Billed-URL</b> mulige værdier er: %VAL%",
				errorFieldsThumb: "<b>Miniature-URL</b> mulige værdier er: %VAL%",
				errorFields2Explain: "Indlæsningen mislykkedes, da CSV-filen ikke ikke bruger samme attributter som laget for følgende attributter",
				errorFields2Name: "<b>Navn</b> brug %VAL1% i stedet for %VAL2%",
				errorFields2Desc: "<b>Beskrivelse</b> brug %VAL1% i stedet for %VAL2%",
				errorFields2Url: "<b>Billed-URL</b> brug %VAL1% i stedet for %VAL2%",
				errorFields2Thumb: "<b>Miniature-URL</b> brug %VAL1% i stedet for %VAL2%",
				resultFieldsAll: "Alle attributter er importeret",
				resultFieldsNotAll: "Følgende attributter er ikke importeret, da de ikke eksisterer i kortlaget",
				resultFieldsNotAll2: "Følgende attributter er  importeret",
				footerNextBtnResult: "Import\ér til webkortet",
				footerProgress: "Import i gang",
				footerSucceed: "Import lykkedes. Indlæser"
			},
			viewGeoTag: {
				header: "Klik eller tryk på de billeder, du vil importere, for at finde dem.",
				headerMore: "Hvorfor kan mine billeder ikke findes?",
				headerExplain: "Hvis dine billeders placering er gyldig, findes de automatisk på kortet og vises på listen på andet faneblad.<br /><br />Som standard udnytter Picasa og Flickr ikke billedernes EXIF-placeringsmetadata. Marker afkrydsningsfeltet ud for Flickr/Picasa-indstillinger på fanebladet Fortroligt for at aktivere brug af billeders placeringsdata. Du kan muligvis være nødt til at skulle importere dine billeder til Flickr/Picasa igen.<br /><br />Mht. Facebook skal du gå til hver enkelt billede, klikke på Rediger og markere placeringen blandt de mulige valg, der er baseret på billedernes EXIF-metadata.",
				leftPanelTab1: "Skal findes",
				leftPanelTab2: "Fundet",
				clickOrTap: "Klik eller tryk på kortet for at finde",
				clickDrop: "Import\ér ikke",
				footerImport: "Import\ér",
				footerProgress: "Import i gang",
				footerSucceed: "Import lykkedes. Indlæser...",
				loading: "Indlæser",
				error: "Import af billedplacering mislykkedes, placeringer er blevet tilsidesat."
			},
			initPopup: {
				title: "Velkommen til Map Tour Builder",
				prevBtn: "Tilbage",
				nextBtn: "Næste"
			},
			initPopupHome: {
				header2: "Denne assistent hjælper dig med at oprette en Map Tour på grundlag af billeder, der allerede er lagret online, eller også importerer den dem til din ArcGIS Online for Organization-konto.",
				title1: "Mine billeder \"hostes\" allerede",
				title2: "Jeg skal \"hoste\" mine billeder",
				hostedFsNA: "Kun tilgængelig for udgiver- og administratorbrugere på ArcGIS for Organization",
				footer1: "Når du er færdig, skal du huske at dele din Map Tour med dit publikum gennem siden for applikationselementer.",
				footer2: "Map Tour-hjælp",
				footer3: "Download CSV-skabelonen",
				footer4: "\"Gem som\" hvis den ikke overføres",
				footerProgress: "Oprettelse i gang",
				footerSucceed: "Oprettelse lykkedes. Indlæser..."
			},
			helpPopup: {
				title: "Hjælp",
				close: "Luk",
				tab1: {
					title: "Introduktion",
					div1: "Map Tour-skabelonen er lavet til at præsentere geografisk information, der hvor der er et spændende fotografisk element, der passer til din historie.",
					div2: "Skabelonen producerer en attraktiv, letanvendlig webapplikation, der gør det muligt at præsentere en række steder på et kort i en nummereret rækkefølge, som brugere kan gennemse. Skabelonen er beregnet til at blive brugt i alle webbrowsere og på alle enheder, herunder smartphones og tablets.",
					div3: "Dette hjælp-emne vil guide dig gennem trinene for publicering af Map Tours såsom:",
					div4: "<ul><li><a href='http://storymaps.esri.com/stories/demo/map_tour/?webmap=7190edafe7464cb19c1caf1360cd6ee5' target='_blank'>Palm Springs Map Tour</a></li><li><a href='http://story.maps.arcgis.com/apps/MapTour/index.html?appid=4d6054b109ce482d88588d5c06a7a478' target='_blank'>Hollands bedste mountainbike-ruter</a></li><li><a href='http://ugis.esri.com/LA_River_Tour/' target='_blank'>Los Angeles River Map Tour</a></li></ul>",
					div5: "Vi hører gerne fra dig. Du må meget gerne dele din Map Tour med os:",
					div6: "<ul><li><a href='mailto:storymaps@esri.com' target='_blank'>storymaps@esri.com</a></li><li><a href='http://storymaps.esri.com/home/' target='_blank'>StoryMaps Website</a></li><li><a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a></li></ul>",
					div7: "Har du fundet en fejl, eller vil du foreslå en ny funktion? Fortæl os det ved at oprette en sag på <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub-projektsiden</a>."
				},
				tab2: {
					title: "Data",
					div1: "Det vigtigste, du skal overveje, når du skal oprette en Map Tour, er hvor dine billeder skal lagres. En Map Tour kan bruge billeder, der er lagret på større fotodelingstjenester, webservere eller som vedhæftede filer på en featuretjeneste.",
					div1a: "Se det sidste afsnit på denne fane for at få oplysninger om understøttede formater og videoer.",
					div2: "Det interaktive builder-program indeholder to muligheder til håndtering af billeder i din Map Tour:",
					div3: "<ul><li>Du kan bruge <b>fotos, der allerede er online</b>, f.eks. billeder, der er gemt på et fotodelings-websted som Flickr, eller billeder, der er gemt på dit eget websted. Der vil være referencer til disse billeder i din Map Tour via deres URL\'er.</li><li>Du kan også <b>overføre billeder fra din computer</b> direkte til din Map Tour. Denne mulighed kræver, at du har et ArcGIS Online-abonnement, og at du har udgiver- eller administratorrettigheder, fordi der automatisk oprettes en \"hosted\" featuretjeneste til dig, hvor dine fotos gemmes som vedhæftninger.</li></ul>",
					div4: "Typiske brugerscenarier:",
					div4b: "<b>Dine billeder er ikke \"hosted\"</b> endnu, og du har et ArcGIS Online-abonnement: Det er dit bedste valg at benytte en \"hosted\" featuretjeneste. Ligesom på offentlige fotodelingstjenester vil vi optimere dine billeder med henblik på at oprette billeder, der indlæses hurtigt, og du får adgang til alle administrations- og datahåndteringsfunktionerne på ArcGIS-platformen.",
					div5: "<b>Du er ikke medlem af en organisation</b>: Du skal først overføre dine billeder til et fotodelings-websted eller til din egen webserver. Builder-programmet hjælper dig med at anvende disse billeder, der fortsat vil være \"hosted\" på deres oprindelige placering.",
					div6: "<b>Du vil gerne genbruge en eksisterende featuretjeneste,</b> som gemmer dine billeder som vedhæftede filer, eller som henviser til eksterne billeder: Se afsnittet med detaljerede oplysninger nedenfor.",
					div7: "<b>Du bruger en tidligere version</b> af Map Tour-skabelonen og har allerede en CSV-fil, der henviser til dine billeder og miniaturer: Du kan importere den og forfine dine data. Builder-programmet understøtter kun CSV-filer, der benytter længde- og breddegradsfelter. Adressebaserede CSV-filer kan fortsat benyttes via dit webkort (se nedenfor).",
					div8: "Import fra online fotodelingstjenester",
					div9: "Denne import-handling henviser til billeder, der allerede er \"hosted\" ved at gemme deres URL\'er i en samling af webkorttjenester. Billederne gemmes ikke på ArcGIS Online. Hvis du ikke kan få adgang til de \"hostede\" billeder, vil de ikke være tilgængelige i din Map Tour, og du får vist et billede med teksten \'Billedet er ikke tilgængeligt\'. Det afhænger af tjenesteudbyderen, om din Map Tour importerer navn, beskrivelse og placering for billederne. Disse attributter gemmes i webkortet, og eventuelle redigeringer af online-tjenesten vises ikke i Map Tour.",
					div10: "Lagring af billeder på en web-server",
					div11: "Hvis du vælger selv at \"hoste\" billederne, skal du manuelt oprette miniaturebilleder til dine billeder. Hvis du bruger billeder med fuld opløsning til miniaturebillederne, bliver de ikke gode. Vi anbefaler derfor, at du bruger en online fotodelingstjeneste eller en featuretjeneste til dette.",
					div12: "Brug af en eksisterende featuretjeneste eller shapefil",
					div13: "Alle punkt-featuretjenester og shapefiler kan bruges som Map Tour-datakilde. Du skal blot tilføje dem som et lag i dit webkort via ArcGIS.com-kortviseren. Hvis applikationen finder de forventede attributter i dine lag, vil alle builder-funktioner være tilgængelige.",
					div14: "De forventede felter er (forskel på store og små bogstaver):",
					div151: "Navn",
					div152: "Beskrivelse",
					div153: "Billede",
					div154: "Miniature",
					div155: "Farve (valgfri)",
					div16: "Felterne Navn og Beskrivelse er obligatoriske. Hvis applikationen ikke finder matchende felter, når der benyttes en featuretjeneste, virker viewer-programmet ikke, før du konfigurerer de felter, der skal benyttes via builder-programmet. CSV- og shapefil-lag, der er føjet til webkortet, skal have alle de obligatoriske felter, ellers fungerer builder-programmet ikke.",
					div162: "Når du anvender en featuretjeneste, der gemmer billeder som vedhæftede filer, <b>er det kun objekter med to vedhæftninger, der benyttes</b>. Den første vedhæftning definerer hovedbilledet, og den anden definerer miniaturen.",
					div17: "Billed- og miniaturefelterne er obligatoriske for featuretjenester uden vedhæftninger og valgfrie (men anbefalede) for featuretjenester med vedhæftninger. Hvis din tjeneste har vedhæftninger aktiveret, kan du overføre billeder som vedhæftede filer med builder-programmet. Hvis ikke, kan du kun redigere billed- og miniature-URL\'erne.",
					div172: "Billed- og miniaturefelterne vil, når de findes, altid blive brugt, og der vil ikke blive anmodet om featuretjenestens vedhæftninger.",
					div173: "Eksempel-CSV-filer og shapefiler kan overføres fra",
					div18: "Opretter en \"hosted\" featuretjeneste ud fra en CSV- eller shapefil",
					div19: "Når du opretter en \"hosted\" featuretjeneste på basis af en CSV- eller shapefil, er vedhæftninger ikke aktiveret som standard. Hvis du vil aktivere dem, skal du åbne featuretjenestens oplysningsside og klikke på den lille pil på lagsektionen for at få indstillingen vist. Map Tour\'en vil fortsat bruge de billeder og miniaturer, du har refereret til via attributter. Hvis du vil overføre dine billeder som  featuretjeneste-vedhæftninger, kan du gøre det vha. to knapper på billedpanelet (\"Redig\ér billede\" og \"Redig\ér miniature\").",
					div20: "Understøttede billedformater og videoer",
					div21: "Understøttede billedformater er: <b>.jpg, .jpeg, .png, .gif og .bmp</b>. Hvis dit medie ikke slutter med en af disse filtypenavne, vil Map Tour betragte mediet som en video, undtagen når du bruger en featuretjeneste (se nedenfor).",
					div22: "Map Tour-skabelonen indeholder ikke en videoafspiller, så du skal bruge den eksterne videoafspiller, som leveres af din foretrukne værtstjeneste for videoindhold (find indstillingen til indlejring af videoen, og kopi\ér den URL, der findes i den givne kode). Hvis du selv ønsker at \"hoste\" videoen, kan du oprette en HTML-side, der indeholder en videoafspiller som f.eks. <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Det interaktive builder-program indeholder ikke nogen dialogboks, som kan benyttes til at inkludere videoer, når du bruger featuretjenester med vedhæftninger, men det er muligt at gøre dette ved at redigere dine data uden for det interaktive builder-program. I ArcGIS-kortviseren vil dit medie blive betragtet som en video, hvis du redigerer billedfelterne, så de peger på en ekstern video og tilføjer en særlig parameter i slutningen af din URL (#isVideo).",
					div24: "Bemærk, at du fortsat skal have to gyldige vedhæftede billeder, ellers vil punktet ikke blive anvendt. Du kan ikke bruge videoer, når du benytter featuretjeneste-vedhæftninger uden billed- og miniaturefelter."
				},
				tab3: {
					title: "Tilpasning",
					div1: "Map Tour builder indeholder flere muligheder for tilpasning, der er tilgængelige via knappen INDSTILLINGER i toppanelet. Hvis du ikke kan finde den indstilling, du skal bruge, findes der også en version, der kan downloades til din webserver, hvor du kan bruge den til de indstillinger, du ønsker.",
					div2: "Vi anbefaler, at du bruger den \"hostede\" version, medmindre:",
					div3: "<li>Den ikke indeholder den UI-tilpasning, du ønsker, f.eks. brug af et baggrundsbillede til overskiften</li><li>Du er udvikler, og du ønsker at forbedre applikationen.</li>",
					div4: "Den overførbare version kan konfigureres via en webkort- eller en webkortapplikationsidentifikator. De primære brugssituationer er:",
					div41: "Du opretter din map tour med det interaktive builder-program i værtsmiljøet og konfigurerer skabelonen med et webkortapplikations-ID. De indstillinger, du har defineret med det interaktive builder-program, vil blive anvendt.",
					div42: "Du opretter din map tour uden for det interaktive builder-program og konfigurerer skabelonen med et webkort-ID. Du skal læse dokumentationen for at lære, hvordan du konfigurerer skabelonen.",
					div43: "Bemærk, at det interaktive builder-program er tilgængeligt i en version, der kan overføres, men at der er nogle tekniske begrænsninger for browsere, f.eks. Internet Explorer, der er ældre end version 10.",
					div5: "Se også <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub-projektside</a> for at få flere oplysninger om den version, der kan downloades."
				},
				tab4: {
					title: "Tips",
					div0: "Understøttede browsere",
					div0a: "Map Tour-viewer-programmet understøttes af IE8+. Det interaktive builder-program understøttes af IE9+. Vi tester programmet i alle de store browsere, men hvis du kommer ud for vanskeligheder, anbefaler vi, at du bruger Chrome.",
					div0b: "Giv os gerne besked, hvis du kommer ud for vanskeligheder. I mellemtiden vil du, når du opretter din Map Tour ved hjælp af CSV-skabelonen, minimere din interaktion med builder-programmets grænseflade.",
					div1: "Billeder",
					div2: "Vi anbefaler, at du benytter liggende format til dine fotos i stedet for stående format. Stående format kan benyttes, men på mindre skærme som iPad vil en stor del af billedet måske blive skjult af billedteksten (tekst fylder mere, når den vises på et opretstående område sammenlignet med et bredt område). Skønt billeder med forskellig størrelse, form og orientering kan benyttes i den samme Map Tour, anbefaler vi, at du bruger præcis samme størrelse og form til alle billeder. Så bliver brugeren ikke distraheret af billeder med forskellig størrelse, når de følger tour\'en.",
					div2a: "Hvis du selv \"hoster\" billederne, anbefaler vi, at du benytter en maksimal opløsning på <b>1090x725</b> for de almindelige billeder og <b>140x93</b> for miniaturer.",
					div3: "Formatering af din billedtekst vha. HTML-tags",
					div4: "Overskrifts- og billedtitlen/-teksten kan indeholde HTML-tags, der definerer formatering og links. For eksempel tilføjer denne kode et gult link:",
					div5: "Understøttende lag",
					div6: "Du kan tilføje flere understøttende lag, der giver yderligere kontekst til din Map Tour. Disse lag kan indeholde andre geografiske objekter, som du ønsker, at kortet skal vise som supplement til Map Tour-punkterne, såsom et undersøgelsesområde, en gå- eller kørerute, der forbinder dine tour-punkter osv. Map Tour-skabelonen viser disse supplerende supportlag vha. den symbologi, du angiver i webkortet, men pop-up-vinduerne er ikke tilgængelige.",
					div7: "Pas på, din tour ikke bliver for lang",
					div8: "Der er en begrænsning på 99 punkter pr. tour. De fleste Map Tours vil naturligvis være væsentligt kortere end dette. Publikum har som regel ikke lyst til at gå igennem alt for mange tour-punkter. Det er ikke sikkert, de finder dit emne lige så spændende, som du gør!",
					div9: "Se <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>detaljeret vejledning</a> for at få flere oplysninger.",
					div10: "Indlejringstilstand",
					div11: "Hvis du ønsker at indlejre skabelonen på et andet websted via en iframe, fjernes overskriften, hvis du tilføjer den valgfrie parameter \"&embed\" i slutningen af URL\'en. Du kan også benytte denne tilstand i den version, der kan overføres, ved at bruge konfigurationsfilen." 
				},
				tab5: {
					title: "Udgivelse",
					div1: "Når du er færdig, så husk at dele din Map Tour med dit publikum via applikationens oplysningsside i ArcGIS Online. I løbet af denne proces vil ArcGIS Online muligvis spørge, om du vil opdatere eventuelle afhængige ressourcer (webkort, featuretjenester), der ikke deles på samme måde. Hvis din Map Tour er offentlig, og en af dine ressourcer ikke deles med dit publikum, bliver brugerne omdirigeret til ArcGIS Online-loginsiden.",
					div2: "Hvis du bruger en \"hosted\" featuretjeneste, der er oprettet med Map Tour-builder-programmet, håndterer applikationen tjenestens sikkerhed for dig , og du er den eneste, der har redigeringsrettigheder, også når tjenesten er delt med offentligheden.",
					div3: "Inden du deler en Map Tour med offentligheden, skal du sikre dig, at den fungerer, når du ikke er logget på din ArcGIS.com-konto.",
					div4: "Det er en god id\é at tjekke, hvordan din map tour ser ud på en iPad, der holdes vandret. Dette kan hjælpe dig med at se, om dine billedtekster dækker for meget af billederne."
				}
			}
        }
    })
);
