define({
  "viewer": {
    "loading": {
      "step1": "NALAGANJE ZGODBE",
      "step2": "NALAGANJE PODATKOV",
      "step3": "INICIALIZIRANJE POTOPISA",
      "loadBuilder": "PREKLAPLJANJE NA GRADITELJSKI NAČIN",
      "redirectSignIn": "PREUSMERJANJE NA STRAN ZA PRIJAVO",
      "redirectSignIn2": "(sem boste preusmerjeni po prijavi)",
      "fail": "Oprostite, nalaganje Potopisne karte ni uspelo",
      "failButton": "Poskusite znova"
    },
    "errors": {
      "boxTitle": "Prišlo je do napake",
      "portalSelf": "Usodna napaka: Konfiguracije portala ni mogoče pridobiti",
      "invalidConfig": "Usodna napaka: Neveljavna konfiguracija",
      "invalidConfigOwner": "Usodna napaka: Neveljavna konfiguracija (zahtevana je avtorizacija lastnika)",
      "invalidConfigNoWebmap": "Usodna napaka: Neveljavna konfiguracija (spletna karta ali identifikator aplikacije ni določen v index.html)",
      "invalidConfigNoAppDev": "Identifikator aplikacije za spletno kartiranje ali spletna karta ni določena v parametrih URL (?appid= or ?webmap=). V razvijalskem načinu sta prezrti konfiguraciji za appid in spletno karto v index.html.",
      "createMap": "Karte ni mogoče ustvariti",
      "invalidApp": "Usodna napaka. Zgodbe ni mogoče naložiti",
      "noLayer": "Spletna karta ne vsebuje veljavnega podatkovnega sloja za Potopisno karto.",
      "noLayerMobile": "Graditelj Potopisne karte pri tej velikosti prikaza ni podprt. Če je mogoče, ponovno nastavite svoj brskalnik za dostop do graditelja ali izdelajte svojo zgodbo na napravi z večjim zaslonom.",
      "noLayerMobile2": "Obrnite svojo napravo v ležeči položaj, da boste lahko uporabili graditelja Potopisne karte.",
      "noLayerView": "Dobrodošli v spletni aplikaciji Potopisne karte.<br />Zgodba še ni konfigurirana.",
      "appSave": "Napaka pri shranjevanju zgodbe",
      "mapSave": "Napaka pri shranjevanju spletne karte",
      "featureServiceLoad": "Napaka pri nalaganju geoobjektne storitve",
      "notAuthorized": "Niste pooblaščeni za dostop do te zgodbe",
      "notAuthorizedBuilder": "Niste pooblaščeni za uporabo graditelja Potopisne karte.",
      "oldBrowserTitle": "Brskalnik ni v celoti podprt",
      "noBuilderIE8": "Internet Explorer pred različico 9 ne podpira graditelja Potopisne karte.",
      "ie10Win7Explain": "Ko je vir podatkov geoobjektna storitev s prilogami, Internet Explorer 10 na Windows 7 ne podpira interaktivnega graditelja Potopisne karte. Za uporabo geoobjektne storitve s prilogami je treba <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>ročno vsiliti način za dokumente za standarde Internet Explorerja 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>ga zamenjati s starejšo različico Internet Explorer 9</a> ali nadgraditi na Windows 8.",
      "oldBrowserExplain": "Ta brskalnik ne podpira samodejnega ustvarjanja sličic iz slik, ki jih naložite na svojo potopisno karto. Potopisno karto lahko ustvarite s tem brskalnikom, vendar boste morali zagotoviti ločeno sličico za posamezne slike, ki jih nalagate.",
      "oldBrowserExplain2": "Za boljšo izkušnjo <a href='http://browsehappy.com/' target='_blank'>nadgradite svoj brskalnik</a> ali <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivirajte Google Chrome Frame za Internet Explorer</a>.",
      "oldBrowserExplain3": "Graditelj Potopisne karte ne deluje z brskalnikom Internet Explorer 10 na Windows XP.",
      "oldBrowserClose": "Zapri",
      "noViewerIE2": "To zgodbo si želite ogledati s staro, nepodprto različico brskalnika. Morda nekatere funkcionalnosti ne bodo delovale ali pa bo prišlo do drugih nepričakovanih težav. Predlagamo, da ga nadgradite na Internet Explorer 11 ali uporabite drug brskalnik, recimo Chrome.",
      "noViewerIE3": "Konec leta 2017 se ta zgodba v tem brskalniku ne bo več naložila. Takrat boste za ogled te zgodbe morali uporabiti podprti brskalnik.",
      "attention": "Pozor!"
    },
    "mobileHTML": {
      "showIntro": "POKAŽI IME",
      "hideIntro": "SKRIJ IME",
      "navList": "Seznam",
      "navMap": "Karta",
      "navInfo": "Mediji",
      "introStartBtn": "Začetek"
    },
    "desktopHTML": {
      "storymapsText": "Karta z zgodbo",
      "builderButton": "Preklopite na graditeljski način",
      "facebookTooltip": "Deli na Facebooku",
      "twitterTooltip": "Deli na Twitterju",
      "bitlyTooltip": "Pridobi kratko povezavo",
      "bitlyStartIndex": "Povezava do trenutnega kraja",
      "tooltipAutoplayDisabled": "Ni na voljo v načinu samodejnega predvajanja",
      "autoplayLabel": "Način samodejnega predvajanja",
      "autoplayExplain1": "Način samodejnega predvajanja bo vašo zgodbo prikazoval v rednih intervalih. To je idealno za kiosk ali javno prikazovan zaslon, vendar vedite, da bo zgodbe v drugih situacijah morda težje brati. Ta funkcionalnost ni podprta na majhnih zaslonih.",
      "autoplayExplain2": "Ko je ta način dejaven, so prikazani ukazi za predvajanje/začasno ustavitev zgodbe in prilagoditev hitrosti navigacije."
    },
    "builderHTML": {
      "panelHeader": "KONFIGURACIJA ZGODBE",
      "buttonSave": "SHRANI",
      "buttonSettings": "Nastavitve",
      "buttonShare": "Deli",
      "buttonView": "Način prikaza",
      "buttonItem": "Odprite element spletne aplikacije",
      "buttonHelp": "Pomoč",
      "buttonOrganize": "Organiziraj",
      "buttonAdd": "Dodaj",
      "buttonImport": "Uvozi",
      "buttonImportDisabled": "Ko uporabljate geoobjektno storitev s prilogami, uvoz ni na voljo",
      "dataEditionDisabled": "Na tem podatkovnem viru CSV je urejanje podatkov onemogočeno",
      "dataSourceWarning": "Podatkovni sloj Potopisna karta se je spremenil. Če ID-ji geoobjektov niso enaki, morate ponastaviti vrstni red in skriti točke prek možnosti <b>Organiziraj</b>. Če se imena polj razlikujejo, morate ponastaviti nastavitve polj na <b>zavihku s podatki v nastavitvah</b>.",
      "organizeWarning": "Ena ali več točk, dodanih zunaj interaktivnega graditelja je skritih.",
      "dataPicError0a": "Ta potopis vključuje <b>%NB%</b> URL-je slik, ki niso skladni.",
      "dataPicError0b": "Ta potopis lahko vključuje <b>%NB%</b> URL-je slik, ki niso skladni.",
      "dataPicError1": "Potopisna karta zdaj zahteva, da se URL slike konča z eno od naslednjih pripon: .jp(e)g, .png, .gif ali .bmp.",
      "dataPicError2": "Ta zahteva ne bo vplivala na obstoječo objavljeno Potopisno karto. Da bi lahko uporabili interaktivnega graditelja, morate najprej razrešiti težavo z URL-jem z enim od naslednjih dejanj:",
      "dataPicError3": "Uredi URL-je",
      "dataPicError4": "To bo dodalo <i>#isImage</i> na konec URL-ja nepodprte slike. Večina strežnikov podpira dodatke URL-ja. Ko izvedete to dejanje, morate preveriti, ali posodobljeni URL-ji slike delujejo, tako da se premikate čez točke. Če se vse slike naložijo, lahko shranite Potopisno karto. Če <b>se slike ne prikazujejo, Potopisne karte ne shranjujte</b>. Namesto tega ponovno naložite graditelja in izvedite drugo dejanje.",
      "dataPicError5": "Omeji potopis na slike",
      "dataPicError6": "Ta možnost povzroči, da so vsi URL-ji obravnavani kot slike, vendar z interaktivnim graditeljem ne boste mogli dodajati videoposnetkov. To dejanje je mogoče razveljaviti, če se v prihodnosti odločite dodati videoposnetek.",
      "dataPicError7": "Vaša Potopisna karta je bila omejena na slike, videov ni mogoče uporabiti. Če se odločite odstraniti to omejitev, pred shranjevanjem Potopisne karte preverite, ali se slike še vedno pravilno nalagajo. Omejitev lahko pozneje po potrebi znova povrnete.",
      "dataPicError8": "Odstranite omejitev za slike",
      "dataPicError9": "Če ti URL-ji kažejo na videoposnetke, lahko to opozorilo prezrete. Če kažejo na sliko, je treba izvesti eno od naslednjih dejanj:",
      "modalCancel": "Prekliči",
      "modalApply": "Uporabi",
      "organizeHeader": "Organiziraj potopis",
      "organizeGeneralCaption": "Uporabite povleci in spusti za razvrščanje točk potopisa",
      "organizeDelete": "Izbriši",
      "organizeHide": "Skrij",
      "organizeReset": "Ponastavi vrstni red in skrite točke",
      "addMaxPointReached": "Dosegli ste največje število točk, za katerega ste pooblaščeni glede na nabor ikon, zato ne morete dodati drugih točk potopisa. <br /><br />Če boste izbrisali obstoječe točke, boste morali ponovno naložiti zgodbo.",
      "addMaxPointReachedMobile": "Oprostite, dosegli ste največje število točk, za katerega ste pooblaščeni, in ne morete dodati te slike.",
      "addClose": "Zapri",
      "addHeader": "Dodaj novo točko potopisa",
      "addTabPicture": "Omrežja",
      "addTabInformation": "Informacije",
      "addTabLocation": "Lokacija",
      "addSelectCaption": "Izberi ali spusti sliko",
      "addNoteVideo": "Za navodila o uporabi videoposnetkov glejte Pomoč",
      "addSelectCaptionNoFileReader": "Izberite sliko",
      "addChangePhoto": "Spremeni sliko in sličico",
      "addPictureResolutionIntro": "Ločljivost slike je večja od zahtevane:",
      "addPictureResolutionOldBrowser": "Ločljivost slike je večja od zahtevane. Optimizirajte izkušnjo Potopisne karte tako, da določite ločljivost, manjšo od %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Spremeni ločljivost slike na %RESOLUTION%",
      "addPictureResolutionKeep": "Ohrani izvirno ločljivost %RESOLUTION%",
      "addSelectThumbnail": "Izberi sličico",
      "addNoThumbSelected": "Nobena sličica ni izbrana",
      "addThumbSelected": "Izbrano",
      "addCameraSettingsHeader": "NASTAVITVE KAMERE",
      "addThumbnailHeader": "SLIČICA",
      "addLabelPicUrl": "Slika",
      "addLabelThumbUrl": "Sličica",
      "addTextPlaceholderUrl": "Vnesite URL slike",
      "addTextPlaceholderUrl2": "Vnesite URL YouTube strani",
      "addTextPlaceholderUrl3": "Vnesite URL Vimeo strani",
      "addTextPlaceholderUrl4": "Vnesite URL vdelanega videa",
      "addLabelVideo": "Videoposnetek",
      "addMediaVideoOther": "Drugo",
      "addMediaVideoHelp": "Preverite URL in pridobite privzeto sličico",
      "addMediaVideoHelpTooltip1": "Preverjanje je uspelo",
      "addMediaVideoHelpTooltip2": "Preverjanje ni uspelo",
      "addMediaVideoHelpTooltip4": "Poiščite možnost za vdelavo videoposnetka in kopirajte URL videoposnetka, ki je v kodi",
      "addLabelName": "Ime",
      "addLabelDescription": "Napis",
      "addTextPlaceholder": "Napišite nekaj",
      "addLocatePlaceholder": "Najdite naslov ali kraj",
      "addPinColor": "Barva",
      "addLatitude": "Geografska širina",
      "addLongitude": "Geografska dolžina",
      "addLatitudePlaceholder": "npr. 34,056",
      "addLongitudePlaceholder": "npr. -117,195",
      "addUploading": "Nalaganje točke potopisa",
      "addSave": "Dodaj točko potopisa",
      "addMobileUploading": "Nalaganje slike",
      "addMobileName": "Vnesite ime",
      "addMobileNameMandatory": "Napaka, vnesite ime.",
      "addMobileError": "Oprostite, nekaj ni bilo v redu",
      "settingsHeader": "Nastavitve zgodbe",
      "settingsTabLayout": "Postavitev",
      "settingsTabColor": "Barve",
      "settingsTabLogo": "Glava",
      "settingsTabFields": "Podatki",
      "settingsTabExtent": "Obseg",
      "settingsTabZoom": "Stopnja povečave",
      "settingsLayoutExplain": "Izberite postavitev, ki jo želite",
      "settingsLayoutProfessional": "Triploščna postavitev",
      "settingsLayoutModern": "Integrirana postavitev",
      "settingsLayoutSelected": "Izberite postavitev",
      "settingsLayoutSelect": "Izberi to postavitev",
      "settingsLayoutNote": "Bodite pozorni na to, da bo pri točkah z videi pod njimi vedno plakat, tudi če ta možnost ni obkljukana.",
      "settingsLayoutLocBtn": "Prikaži gumb »Najdi«",
      "settingsLayoutLocBtnHelp": "Podprto pri večini brskalnikov. Prikaže se samo v primeru dostopanja do karte z zgodbo prek HTTPS. Ne prikaže se, če je zgodba vdelana.",
      "settingsColorExplain": "Spremenite videz z izbiro predhodno določene teme ali ustvarite svojo.",
      "settingsLabelColor": "Barve glave, vsebine in noge",
      "settingsLogoExplain": "Prilagodite logotip glave (največja velikost 250 x 50 px).",
      "settingsLogoEsri": "Logotip Esri",
      "settingsLogoNone": "Brez logotipa",
      "settingsLogoCustom": "Logotip po meri",
      "settingsLogoCustomPlaceholder": "URL slike",
      "settingsLogoCustomTargetPlaceholder": "Zunanja povezava",
      "settingsLogoSocialExplain": "Prilagodite spletno povezavo v zgornjem desnem kotu glave.",
      "settingsLogoSocialText": "Besedilo",
      "settingsLogoSocialLink": "Povezava",
      "settingsLogoSocialDisabled": "Administrator je onemogočil to funkcionalnost",
      "settingsDataFieldsExplain": "Izberite polja ime fotografije, napis in barva.",
      "settingsDataFieldsError": "Aplikacija ne more določiti ustreznih podatkov za ime, napis ali barvo. Izberite polja, ki bodo uporabljena. Te nastavitve lahko pozneje spremenite.",
      "settingsFieldsLabelName": "Ime",
      "settingsFieldsLabelDescription": "Napis",
      "settingsFieldsLabelColor": "Barva",
      "settingsFieldsReset": "Ponastavite izbiro polj",
      "settingsExtentExplain": "Nastavite začetni obseg Potopisne karte s spodnjo interaktivno karto.",
      "settingsExtentExplainBottom": "Obseg, ki ga določite, bo spremenil začetni obseg vaše spletne karte. Ta obseg ne bo uporabljen, če ne vsebuje prve točke potopisa. V tem primeru se bo potopis odprl z začetno točko v središču.",
      "settingsExtentDateLineError": "Obseg se ne more raztezati preko poldnevnika 180° geografske dolžine.",
      "settingsExtentDateLineError2": "Napaka pri računanju obsega",
      "settingsExtentDrawBtn": "Narišite nov obseg",
      "settingsExtentModifyBtn": "Uredi obseg",
      "settingsExtentApplyBtn": "Predogled Potopisne karte",
      "settingsExtentUseMainMap": "Uporabi obseg Potopisne karte",
      "settingsZoomExplain": "Nastavi povečavo za točke zgodbe po uvodu (izbirno)",
      "settingsLabelZoom": "Merilo/stopnja",
      "settingsZoomFirstValue": "Brez",
      "settingsFieldError": "Izberite polje na posameznem seznamu",
      "dataTitle": "Ustvarite gostujoči sloj Potopisne karte",
      "dataExplain": "Za vaše slike in točke potopisa bo ustvarjen nov geoobjektni sloj. Sloj potopisa ne bo deljen z nikomer, razen če vi delite svojo Potopisno karto.",
      "dataExplainPortal": "To funkcionalnost zahteva Portal for ArcGIS 10.4. Če ne morete ustvariti geoobjektnega sloja, se obrnite na administratorja ArcGIS.",
      "dataNameLbl": "Ime sloja",
      "dataFolderListLbl": "Mapa",
      "dataFolderListFetching": "Pridobivanje map ...",
      "dataRootFolder": "Koren",
      "dataNameError": "Vnesite ime za geoobjektno storitev",
      "dataFolderError": "Izberite veljavno mapo",
      "dataSrcContainsInvalidChar": "Ime geoobjektne storitve vsebuje enega ali več neveljavnih znakov (-, <, >, #, %, :, \", ?, &, +, / ali ).",
      "dataSrvAlreadyExistsError": "Storitev s tem imenom v organizaciji že obstaja. Izberite drugo ime.",
      "dataBtnSave": "Ustvari sloj",
      "dataFooterProgress": "Ustvarjanje poteka",
      "dataFooterSucceed": "Ustvarjanje je uspelo. Nalaganje",
      "dataFooterError": "Ustvarjanje ni uspelo. Poskusite znova",
      "tabError": "Preverite napake na vseh zavihkih",
      "introRecordBtn": "Uvod",
      "introRecordActivate": "Prvo točko uporabi kot uvod (se ne pojavi v vrtiljaku)"
    },
    "addPopupJS": {
      "uploadingPicture": "Nalaganje slike",
      "uploadSuccess": "Nalaganje je uspelo",
      "uploadError": "Napaka pri nalaganju slike",
      "uploadError2": "Napaka pri nalaganju geoobjekta (neveljavna oznaka html)",
      "notJpg": "Izberite fotografijo jpeg za nalaganje",
      "errorNoPhoto": "Izberite sliko za nalaganje",
      "errorNoThumbnail": "Izberite sličico za nalaganje",
      "errorInvalidPicUrl": "Vnesite veljavno sliko (začne se s http(s)://, konča z jpg, png, gif ali bmp). URL lahko končate z »#isImage« da preglasite to pravilo.",
      "errorInvalidThumbUrl": "Vnesite veljavno sličico (začne se s http(s)://, konča z jpg, png, gif ali bmp).",
      "errorInvalidVideoUrl": "Vnesite veljaven URL videa (začne se s http(s)://)",
      "errorNoName": "Vnesite ime za to točko potopisa",
      "errorNoDescription": "Vnesite napis za to točko potopisa",
      "errorNoLocation": "Nastavite lokacijo za to točko pohoda"
    },
    "builderJS": {
      "noPendingChange": "Ni neshranjenih sprememb",
      "unSavedChangeSingular": "1 neshranjena sprememba",
      "unSavedChangePlural": "neshranjene spremembe",
      "shareStatus1": "Potopis ni shranjen",
      "shareStatus2": "Potopis je deljen javno",
      "shareStatus3": "Potopis je deljen znotraj organizacije",
      "shareStatus4": "Potopis ni deljen",
      "popoverDiscard": "Ste prepričani, da želite zavreči neshranjene spremembe?",
      "yes": "Da",
      "no": "Ne",
      "popoverLoseSave": "Če odprete pregledovalnik, boste izgubili vse neshranjene spremembe",
      "ok": "V redu",
      "popoverSaveWhenDone": "Ne pozabite shraniti, ko končate",
      "closeWithPendingChange": "Ste prepričani, da želite potrditi dejanje? Vaše spremembe bodo izgubljene.",
      "gotIt": "V redu",
      "savingApplication": "Shranjevanje zgodbe",
      "saveSuccess": "Zgodba je shranjena",
      "saveError": "Shranjevanje ni uspelo, poskusite znova",
      "saveError2": "Shranjevanje ni uspelo zaradi neveljavne oznake html v imenu ali opisu",
      "saveError3": "Ime ne sme biti prazno",
      "dragColorPicker": "Premikaj me naokrog<br />ali mi spremeni barvo",
      "dataWarningExtent": "Vaši podatki so zunaj obsega karte. Ti podatki ne bodo uporabljeni kot točke potopisa. Spremenite obseg karte, če jih želite uporabiti.",
      "dataWarningVisibi": "Vaš sloj Potopisna karta pri trenutnem obsegu karte ni viden. Potrdite, da je vaš sloj Potopisna karta viden na večji karti %MAPSIZE%.",
      "dataWarningEdit": "Uredi spletno karto",
      "dataWarningClose": "Zapri",
      "signIn": "Prijavite se z računom v",
      "signInTwo": "za shranjevanje zgodbe.",
      "switchBM": "Spremeni temeljno karto"
    },
    "organizePopupJS": {
      "messageStart": "Izbrali ste brisanje",
      "messageSinglePoint": "ena točka potopisa",
      "messageMultiPoint": "točke potopisa",
      "messagePermantRemove": "To bo trajno odstranilo",
      "messageRecord": "zapis",
      "messageRecordPlural": "zapisi",
      "messageConfirm": "iz vaše podatkovne baze. Želite nadaljevati?",
      "labelButtonShow": "Prikaži",
      "labelButtonHide": "Skrij"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "To bo trajno izbrisalo sliko in sličico",
      "popoverDeleteWarningThumb": "To bo trajno izbrisalo sličico",
      "popoverUploadingPhoto": "Nalaganje slike in sličice",
      "popoverUploadingThumbnail": "Nalaganje sličice",
      "popoverUploadSuccessful": "Nalaganje je uspelo",
      "popoverUploadError": "Nalaganje ni uspelo, poskusite znova",
      "changePicAndThumb": "Spremeni sliko",
      "changeThumb": "Spremeni sličico",
      "selectPic": "Spremeni medije",
      "selectThumb": "Spremeni sličico",
      "uploadPicAndThumb": "Uporabi"
    },
    "headerJS": {
      "editMe": "Uredi me!",
      "templateTitle": "Nastavi ime predloge",
      "templateSubtitle": "Nastavi podnaslov predloge"
    },
    "crossFaderJS": {
      "setPicture": "Nastavi ime slike",
      "setCaption": "Nastavi napis slike"
    },
    "importPopup": {
      "title": "Uvozi",
      "prevBtn": "Nazaj",
      "nextBtn": "Naprej"
    },
    "importPopupHome": {
      "header": "Kje so shranjene vaše slike?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "slike",
      "videos": "videoposnetki",
      "disabled": "Administrator je onemogočil to funkcionalnost",
      "disabledPortal": "To funkcionalnost zahteva gostujoči strežnik portala. Obrnite se na administratorja portala Portal for ArcGIS.",
      "header1": "Vaše slike morajo biti javno deljene.",
      "header2": "Uvoz bo omejen na prvem %NB1% %MEDIA%.",
      "emptyDataset": "Napaka, slike niso bile najdene",
      "footerImport": "Uvozi",
      "selectAlbum": "Izberi javni album",
      "selectAlbum2": "Izberi album",
      "pleaseChoose": "Izberite",
      "userLookup": "Poišči",
      "userLookingup": "Iskanje",
      "csv": "Sklic na CSV",
      "advanced": "Napredne možnosti",
      "advancedScratchLbl": "Začni nov Potopis",
      "advancedScratchTip": "Ustvarite prazen Potopis, ki ga boste lahko ročno dopolnili s pomočjo čarovnika.",
      "advancedCSVLbl": "Uvozi podatke o pohodu iz datoteke CSV",
      "advancedCSVTip": "Uvozi vsebino potopisa iz datoteke CSV.",
      "advancedCommonTip": "Slike in videoposnetki morajo že biti na spletu.",
      "select": "Izberite",
      "locUse": "Uporabi geolokacijo slik",
      "locExplain": "Morda ne boste želeli uporabiti lokacij slik, ker so lahko podedovane od albuma, kar pomeni, da so vse fotografije na isti lokaciji.",
      "locExplain2": "Morda ne boste želeli uporabiti lokacij videov, ker so lahko podedovane od uporabniških nastavitev, kar pomeni, da so vsi videi na isti lokaciji."
    },
    "viewFlickr": {
      "title": "Uvoz iz Flickrja",
      "header": "Vnesite svoje uporabniško ime iz Flickrja in izberite nabor fotografij ali oznake za uvoz.",
      "userInputLbl": "Vnesite uporabniško ime",
      "signInMsg2": "Uporabnik ni najden",
      "selectSet": "Izberite nabor fotografij",
      "selectTag": "ali izberite oznako",
      "footerImportTag": "Uvozite izbrano oznako",
      "footerImportSet": "Uvozite izbrani nabor"
    },
    "viewFacebook": {
      "title": "Uvoz iz Facebooka",
      "header": "Pristnost potrdite s svojim uporabniškim računom na Facebooku ali uporabite javno stran. Za ustvarjanje javne Potopisne karte lahko uporabite zasebne albume, ki ne zahtevajo preverjanja pristnosti s Facebookom, kar omogoča, da komentarji in všečki ostanejo zasebni.",
      "leftHeader": "Uporabnik Facebooka",
      "rightHeader": "Stran Facebooka",
      "pageExplain": "Facebookova stran je javna blagovna znamka/izdelek ali znani subjekt, kot je <b>esrigis</b>. Ime strani vidite po prvem znaku »/« v URL-ju strani.",
      "pageInputLbl": "Vnesite ime strani",
      "lookupMsgError": "Stran ni najdena"
    },
    "viewPicasa": {
      "title": "Uvoz Picase",
      "header": "Vnesite svojo e-pošto ali Id Picase",
      "userInputLbl": "E-pošta ali id Picase",
      "signInMsg2": "Račun ni najden",
      "signInMsg3": "Ni javnega albuma",
      "howToFind": "Kako poiskati id Picase",
      "howToFind2": "Kopirajte številke med prvim in drugim znakom »/« katerekoli strani Picase"
    },
    "viewCSV": {
      "title": "Uvoz CSV",
      "uploadBtn": "Izberite ali spustite datoteko CSV",
      "resultHeaderEmpty": "CSV je prazen",
      "resultHeaderSuccess": "Naloženih %NB_POINTS% točk",
      "resultHasBeenLimited": "Uvoz je bil omejen na prvih %VAL1% točk od %VAL2% zaradi upoštevanja omejitve %VAL3% točk na potopis",
      "browserSupport": "Vaš brskalnik ni podprt. Za uporabo CSV morate <a href='http://browsehappy.com/' target='_blank'>nadgraditi svoj brskalnik</a> ali uporabiti spletni pregledovalnik kart ArcGIS.com (glejte Pomoč).",
      "errorLatLng": "Polji za geografsko širino in geografsko dolžino nista najdeni. Možne vrednosti za geografsko širino so: <i>%LAT%</i> in za geografsko dolžino: <i>%LONG%</i>.",
      "errorFieldsExplain": "Nalaganje ni uspelo, ker naslednja obvezna polja niso bila najdena",
      "errorFieldsName": "<b>Ime</b> možne vrednosti so: %VAL%",
      "errorFieldsDesc": "<b>Opis</b> možne vrednosti so: %VAL%",
      "errorFieldsUrl": "<b>URL slike</b> možne vrednosti so: %VAL%",
      "errorFieldsThumb": "<b>URL sličice</b> možne vrednosti so: %VAL%",
      "errorFields2Explain": "Nalaganje ni uspelo, ker CSV za naslednje atribute ne uporablja istih atributov kot sloj",
      "errorFields2Name": "<b>Ime</b> uporabi %VAL1%, namesto %VAL2%",
      "errorFields2Desc": "<b>Opis</b> uporabi %VAL1%, namesto %VAL2%",
      "errorFields2Url": "<b>URl slike</b> uporabi %VAL1%, namesto %VAL2%",
      "errorFields2Thumb": "<b>URL sličice</b> uporabi %VAL1%, namesto %VAL2%",
      "resultFieldsAll": "Vsi atributi so bili uvoženi",
      "resultFieldsNotAll": "Naslednji atributi niso bili uvoženi, ker v kartnem sloju ne obstajajo",
      "resultFieldsNotAll2": "Naslednji atributi so bili uvoženi",
      "footerNextBtnResult": "Uvoz na spletno karto",
      "footerProgress": "Uvoz poteka",
      "footerSucceed": "Uvoz je uspel. Nalaganje"
    },
    "viewYoutube": {
      "title": "uvoz z YouTubea",
      "header": "Vnesite uporabniško ime za YouTube, da poiščete javno deljene videooposnetke.",
      "pageInputLbl": "Vnesite uporabniško ime za YouTube",
      "lookupMsgError": "Uporabnik ni najden",
      "howToFind": "Kako poiskati uporabniško ime za YouTube",
      "howToFind2": "Uporabniško ime je prikazano pod videoposnetki",
      "found": "Najdeno",
      "noData": "Javni videoposnetki niso najdeni"
    },
    "viewGeoTag": {
      "title": "Izberite in poiščite svoje slike/videoposnetke",
      "header": "Kliknite ali tapnite slike, ki jih želite uvoziti, da jih najdete.",
      "headerMore": "Zakaj moje slike/videoposnetki niso geoolocirani?",
      "headerExplain": "Če imajo vaše slike veljavne geolokacije, bodo samodejno najdene na karti in navedene na drugem zavihku.<br /><br />Picasa in Flickr metapodatkov o geoolokaciji EXIF pri uvozu slik ne shranjujeta privzeto. Preverite nastavitve zasebnosti Picase/Flickrja, da omogočite uvoz geolokacije slik in njihovo uporabo z zunanjimi aplikacijami. Morda boste za uporabo geolokacije EXIF svoje obstoječe slike morali ponovno uvoziti v Flickr/Picaso.<br /><br />Na Facebooku morate klikniti posamezno sliko in klikniti Uredi ter Izberi lokacijo.",
      "leftPanelTab1": "Najti",
      "leftPanelTab2": "Najdeno",
      "clickOrTap": "Kliknite ali tapnite karto za iskanje",
      "clearLoc": "Počisti lokacije",
      "clickDrop": "Ne uvozi",
      "footerImport": "Uvozi",
      "footerProgress": "Uvoz poteka",
      "footerSucceed": "Uvoz je uspel. Nalaganje ...",
      "loading": "Nalaganje",
      "error": "Uvoz geolokacij slik ni uspel, geolokacije so bile prezrte."
    },
    "initPopup": {
      "title": "Dobrodošli v graditelju Potopisne karte",
      "prevBtn": "Nazaj",
      "nextBtn": "Naprej"
    },
    "initPopupHome": {
      "header1": "Kje so vaše slike ali videoposnetki?",
      "header2": "Ta pomočnik vam bo pomagal izdelati Potopisno karto iz medijev, ki so že shranjeni na spletu ali pa jih bo uvozil v vaš račun ArcGIS Online for Organizations.",
      "title1": "So že na spletu",
      "title2": "Naložiti moram svoje slike",
      "hostedFSTooltip": "Naložite svoje slike in jih shranite v sloj Potopisna karta (ne podpira videov).",
      "hostedFsNA": "Imeti morate vlogo izdajatelja ali drugo vlogo s pravicami za objavljanje gostujočih geoobjektnih slojev. Obrnite se na administratorja ArcGIS.",
      "hostedFsNA2": "Na voljo samo z naročnino ArcGIS Online. <a href='%LINK%'>Prijavite se za brezplačno preskusno različico</a>",
      "footer1": "Ko končate, ne pozabite deliti svoje Potopisne karte s svojim občinstvom prek strani elementov aplikacije.",
      "footer3": "Prenesi predlogo CSV",
      "footer4": "Če se ne prenese, uporabite »Shrani kot«",
      "footer4bis": "Če se prenos ne začne, uporabite desni klik in »Shrani kot«",
      "footer5": "Izvedite več",
      "footerProgress": "Ustvarjanje poteka",
      "footerSucceed": "Ustvarjanje je uspelo. Nalaganje ..."
    },
    "helpPopup": {
      "title": "Pomoč",
      "close": "Zapri",
      "tab1": {
        "title": "Uvod",
        "div1": "Predloga Potopisna karta je namenjena predstavitvi geografskih informacij, ko obstaja zanimiv fotografski ali medijski element zgodbe, ki jo želite povedati.",
        "div2": "Predloga ustvari privlačno spletno aplikacijo, ki je preprosta za uporabo, in vam omogoča predstavitev majhnega nabora krajev na karti v številčnem zaporedju, po katerem lahko brskajo uporabniki. Predloga je oblikovana tako, da jo je mogoče uporabiti v vseh spletnih brskalnikih na različnih napravah, vključno s pametnimi telefoni in tablicami. <br /><br />",
        "div42": "Za ogled primerov potopisnih kart, ki jih ustvarjajo drugi uporabniki, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>obiščite galerijo</a> na <a href='http://storymaps.arcgis.com/' target='_blank'>spletnem mestu Karte z zgodbo</a>. Sledite nam lahko tudi na Twitterju na <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Veseli bomo, če se nam oglasite! Če imate vprašanje, želite novo funkcionalnost ali mislite, da ste naleteli na napako, obiščite forum uporabnikov <a href='http://links.esri.com/storymaps/forum' target='_blank'>Story Maps User Forum</a>."
      },
      "tab2": {
        "title": "Podatki",
        "div1": "Glavni element, ki ga morate imeti v mislih pri izdelavi Potopisne karte, je izbira, kam bodo shranjene vaše slike. V Potopisni karti lahko uporabite slike, shranjene na večjih storitvah za deljenje fotografij, na vseh spletnih strežnikih ali kot priloge geoobjektnih storitev.",
        "div1a": "Za podrobnosti o podprtih formatih slik in videoposnetkov glejte zadnji odsek tega zavihka.",
        "div2": "Interaktivni graditelj vam ponuja dve možnosti za ravnanje s slikami v Potopisni karti:",
        "div3": "<ul><li>Uporabite lahko <b>fotografije, ki so že na spletu</b>, kot so slike, shranjene na spletnem mestu, kot je Flickr, ali slike, shranjene na vašem spletnem mestu. Na te slike se boste v Potopisni karti sklicevali z njihovimi URL-ji.</li><li>Prav tako lahko <b>naložite fotografije s svojega računalnika</b> neposredno v svojo Potopisno karto. Za to možnost nalaganja morate imeti račun ArcGIS for Organizations in pravice izdajatelja ali administratorja, ker se za vas samodejno ustvari gostujoča geoobjektna storitev, v kateri so fotografije shranjene kot priloge.</li></ul>",
        "div4": "Glavni primeri uporabe so:",
        "div4b": "<b>Vaše fotografije še niso gostovane</b> in imate račun ArcGIS for Organizations: uporaba gostujoče geoobjektne storitve je najboljša izbira za vas. Kot javne storitve za deljenje fotografij bomo tudi mi optimizirali vaše slike, da ustvarimo slike, ki se hitro nalagajo, in imeli boste dostop do vse administracije in zmožnosti upravljanja podatkov platforme ArcGIS.",
        "div5": "<b>Niste član organizacije</b>: Najprej morate svoje slike naložiti na spletno mesto za deljenje fotografij ali na lastni spletni strežnik. Graditelj vam bo pomagal uporabiti te slike, ki bodo še naprej gostovale na svoji izvirni lokaciji.",
        "div6": "<b>Ponovno želite uporabiti obstoječo geoobjektno storitev</b>, ki shranjuje vaše slike kot priloge ali ki se sklicuje na zunanje slike: podrobnosti glejte spodaj.",
        "div7": "<b>Ste uporabnik prejšnje različice</b> predloge Potopisne karte in že imate svoj CSV, ki se sklicuje na vaše slike in sličice: Lahko ga boste uvozili in natančno določili svoje podatke. Graditev podpira samo CSV-je, ki uporabljajo polja geografske širine/dolžine; CSV-ji, ki temeljijo na naslovih, se lahko še naprej uporabljajo prek spletne karte (glejte spodnji razdelek).",
        "div8": "Uvoz iz spletne storitve za deljenje fotografij",
        "div9a": "Podpora za Facebook je prekinjena, ${learn}.",
        "learn": "Izvedite več",
        "div9": "Operacija uvoza se sklicuje na slike, ki že gostujejo, tako da njihove URL-je shranjuje v zbirko geoobjektov spletne karte. Slike niso shranjene v ArcGIS Online. Če do gostujočih slik ni mogoče dostopiti, v Potopisni karti ne bodo na voljo in videli boste sliko »Slika ni na voljo«. Izbrani ponudnik storitev za slike Potopisne karte morda ne bo uvozil imena, opisa in lokacije slike. Ti atributi so shranjeni na spletni karti, urejanja na spletni storitvi pa se ne bodo odražala v Potopisni karti.",
        "div10": "Shranjevanje slik na spletnem strežniku",
        "div11": "Če se odločite, da boste sami gostili slike, boste morali zanje ročno izdelati sličice. Uporaba slik s polno ločljivostjo za sličice se bo kazala v slabši učinkovitosti delovanja. Zato vam toplo priporočamo uporabo spletnih storitev za deljenje fotografij ali geoobjektno storitev, ki bo to storila namesto vas.",
        "div12": "Uporabite obstoječo geoobjektno storitev ali shapefile",
        "div13": "Vse točkovne geoobjektne storitve ali shapefile so lahko uporabljeni kot podatkovni viri Potopisne karte. Le dodati jih morate kot sloj na svojo spletno karto preko pregledovalnika kart arcgis.com. Če aplikacija v vašem sloju najde pričakovane atribute, bodo vse funkcionalnosti na voljo.",
        "div14": "Možne vrednosti za imena polj so (razlikovanje velikih in malih črk):",
        "div151": "Ime",
        "div152": "Opis",
        "div153": "Slika",
        "div154": "Sličica",
        "div155": "Barva ",
        "div16": "Če aplikacija pri uporabi geoobjektne storitve ne najde ujemajočih se polj, pregledovalnik ne bo deloval, dokler ne konfigurirate polj, ki bodo uporabljena v graditelju. Sloji CSV shapefile, dodani spletni karti, morajo vsebovati zahtevana polja ali pa graditelj ne bo deloval.",
        "div162": "Med uporabo geoobjektne storitve, ki slike shranjuje kot priloge, <b>bodo uporabljeni samo geoobjekti z dvema prilogama</b>. Prva priloga določa glavno sliko, druga priloga pa določa sličico.",
        "div17": "Polji slika in sličica sta obvezni za geoobjektne storitve brez prilog in izbirni (vendar močno priporočljivi) za geoobjektne storitve s prilogami. Če ima vaša storitev omogočene priloge, vam bo graditelj dovolil nalagati slike kot priloge. Če ne, boste URL-je slik in sličic lahko samo urejali.",
        "div172": "Če so prisotna, bodo polja za slike in sličice vedno uporabljena in za priloge geoobjektnih storitev ne bodo opravljene poizvedbe.",
        "div173": "Primere CSV-jev in shapefileov je mogoče prenesti z",
        "div18": "Ustvarjam gostujočo geoobjektno storitev iz CSV-ja ali shapefilea",
        "div19": "Ko ustvarite gostujočo geoobjektno storitev iz CSV-ja ali shapefilea, priloge niso omogočene privzeto. Da jih omogočite, odprite stran s podrobnostmi geoobjektne storitve, kliknite majhno puščico v razdelku sloja in zagledali boste to možnost. Potopisna karta bo še naprej uporabljala slike in sličice, na katere ste se sklicevali z atributi. Izbirno, če želite svoje slike naložiti kot priloge geoobjektnih storitev, boste to lahko naredili z dvema gumboma na plošči slike (»Spremeni sliko« in »Spremeni sličico«).",
        "div20": "Podprti formati slik in videoposnetkov",
        "div21": "Podprti formati slik so: <b>.jpg, .jpeg, .png, .gif in .bmp</b>. Če se vaš medij ne konča s temi končnicami, jih bo Potopisna karta imela za video, razen pri uporabi geoobjektne storitve (glejte spodaj).",
        "div22": "Predloga Potopisna karta ne vključuje video predvajalnika, zato morate uporabiti zunanjega ponudnika predvajanja videov, ki ga zagotavlja vaša najljubša storitev za gostovanje videov (poiščite možnost za vdelavo videa in kopirajte URL v dano kodo). Če želite sami gostiti video, lahko ustvarite stran HTML, ki vsebuje predvajalnik videov, kot je <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Ta interaktivni graditelj ne ponuja pogovornega okna za vključevanje videoposnetka pri uporabi geoobjektne storitve s prilogami, vendar je to mogoče narediti, če podatke urejate zunaj interaktivnega graditelja. Če v pregledovalniku kart arcgis.com spremenite polja za slike, da kažejo na zunanji videoposnetek, in dodate posebne parametre na konec URL-ja (#isVideo), bo vaš medij obravnavan kot videoposnetek.",
        "div24": "Ne pozabite, da še vedno potrebujete dve veljavni slikovni prilogi ali pa točka ne bo uporabljena. Med uporabo prilog geoobjektne storitve ni mogoče uporabiti videoposnetkov brez polj za sliko in sličico."
      },
      "tab3": {
        "title": "Prilagoditev",
        "div1": "Graditelj ponuja več možnosti prilagoditev, do katerih je mogoče dostopiti z gumbom NASTAVITVE na zgornji plošči. Če ne najdete možnosti, ki jo pričakujete, vam ponujamo tudi različico za prenos, ki jo lahko namestite na svojem spletnem strežniku in izboljšate tako, da ustreza vašim potrebam.",
        "div2": "Priporočamo uporabo gostovane različice, razen v primeru, da:",
        "div3": "<li>Ne ponuja prilagoditve uporabniškega vmesnika, ki jo želite, kot je uporaba slike za ozadje glave.</li><li>Če ste razvijalec in želite izboljšati aplikacijo.</li>",
        "div4": "Različico za prenos je mogoče konfigurirati s spletno karto ali identifikacijo aplikacije za spletno kartiranje. Glavni primeri uporabe so:",
        "div41": "Svojo potopisno karto izdelate z interaktivnim graditeljem v gostujočem okolju in konfigurirate predlogo z identifikatorjem aplikacije za spletno kartiranje. Uporabljene bodo nastavitve, ki ste jih določili z interaktivnim graditeljem.",
        "div42": "Svojo spletno karto izdelajte zunaj interaktivnega graditelja in konfigurirajte predlogo z identifikatorjem spletne karte. Da se boste naučili, kako konfigurirati predlogo, boste morali prebrati dokumentacijo.",
        "div43": "Interaktivni graditelj je na voljo kot različica za prenos, vendar z nekaterimi tehničnimi omejitvami na brskalnikih, kot so Internet Explorer, starejši od različice 10.",
        "div5": "Za prenos najnovejše različice predloge in več informacij o tem, kako jo uporabljati, obiščite <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>stran projekta GitHub</a>."
      },
      "tab4": {
        "title": "Namigi",
        "div0": "Podprti brskalniki",
        "div0a": "Pregledovalnik Potopisna karta podpira IE8+. Interaktivni graditelj podpira IE9+. Dejavno ga preizkušamo na vseh večjih brskalnikih, če pa naletite na težave, vam priporočamo, da uporabite Chrome.",
        "div0b": "Če naletite na težave, nam to sporočite. V vmesnem času boste interakcijo z vmesnikom graditelja zmanjšali, če Potopisno karto izdelate s predlogo CSV.",
        "div1": "Slike",
        "div2": "Namesto pokončne priporočamo ležečo usmerjenost fotografij. Najbolj ustrezne so fotografije z razmerjem 4:3. Slike z ležečo usmerjenostjo so lahko uporabljene, vendar jih bodo na manjših zaslonih, kot je zaslon iPada, morda prekrili napisi (besedilo zavzame več prostora, ko je prikazano na visokem območju, kot pa na širokem območju). Čeprav so lahko v eni Potopisni karti uporabljene slike različnih velikosti, oblik in usmerjenosti, priporočamo uporabo enake velikosti in oblike za vse slike. Tako uporabnikov med sledenjem potopisu ne bodo motile različne velikosti fotografij.",
        "div2a": "Največja priporočljiva velikost slike je 1000 pikslov širine x 750 pikslov višine za glavne slike in 140 x 93 za sličice.",
        "div3": "Formatiranje besedila napisa z oznakami HTML",
        "div4": "Glava in ime/napis slike lahko vsebujeta oznake HTML za določanje oblikovanja in povezav. Na primer, ta koda doda rumeno povezavo:",
        "div4a": "Napišite dober podnaslov za svoj potopis",
        "div4b": "Vzemite si čas, da napišete privlačen podnaslov za svoj potopis. Z dobrim podnaslovom privabite ljudi na svoj potopis in jim poveste, kaj bodo na njem odkrili. Na tem mestu je dobro, da svojemu občinstvu poveste, v kateri državi se odvija potopis. Na primer, ne predvidevajte, da ljudje vedo, kje se nahaja mesto vašega potopisa. Vaš napis je lahko oblikovan z uporabo oznak HTML, recimo z vključevanjem povezav. Pazite, da podnaslov ne bo predolg. V manjših oknih brskalnikov ali na iPadu morda ne bo dovolj prostora in bo porezan. Če se ne morete domisliti dobrega podnaslova, ga pustite praznega.",
        "div5": "Pomožni sloji",
        "div6": "Za dodajanje konteksta lahko Potopisni karti dodate pomožne sloje. Ti lahko vključujejo druge geografske geoobjekte, za katere želite, da jih karta prikazuje poleg točk Potopisne karte, kot so študijska območja, pot za pešce ali vožnjo, povezava vaših točk potopisa itd. Predloga Potopisne karte prikazuje te dodatne pomožne sloje s simbologijo, ki jo določite na spletni karti, pojavna okna pa niso na voljo.",
        "div7": "Naj bo vaš potopis kratek in prijeten",
        "div8": "En potopis ima lahko 99 točk. Večina potopisnih kart bo seveda veliko krajših. Ne pričakujte, da bo vaše občinstvo želelo prehoditi prek veliko točk. Morda se vam vaša tema zdi fascinantna, vendar ne pričakujte, da se bo zdela tudi njim!",
        "div10": "Način vdelave",
        "div11": "Če želite prek iframa vdelati predlogo na drugo spletno mesto, bo dodajanje parametra »&embed« na konec URL-ja odstranilo glavo. Ta način je mogoče nastaviti tudi v različici za prenos prek datoteke za konfiguracijo.",
        "div12": "Izogibajte se uporabi ozkega iFrama, zaradi katerega se bo potopisna karta preklopila na postavitev za majhen zaslon na dotik. Tako bo uporaba lažja. Ko vdelate potopisno karto, vedno priporočamo, da kljub temu poleg vdelanega potopisa zagotovite še povezavo, da ga lahko uporabniki zaženejo na celotnem zaslonu."
      },
      "tab5": {
        "title": "Objavljanje",
        "div1": "Ko končate, ne pozabite svoje Potopisne karte deliti s svojim občinstvom z gumbom DELI ali stranjo elementov aplikacije v ArcGIS Online.",
        "div2a": "Deljenje potopisa prek graditelja",
        "div2b": "Gumb DELI bo posodobil aplikacijo in elemente spletne karte. Če so podatki vašega Potopisa shranjeni v elementu geoobjektne storitve, bodo tudi ti posodobljeni. Če ste dodali druge sloje prek pregledovalnika karte ArcGIS.com, ne bodo posodobljeni. Zaradi tega Potopis morda ne bo deljen, kot ste pričakovali. Elementi, ki že imajo potrebne pravice (ali več pravic), ne bodo posodobljeni.",
        "div2c": "Deljenje Potopisa preko ArcGIS Online",
        "div2d": "Ko delite aplikacijo prek ArcGIS Online, bo od vas po potrebi zahtevala posodobitev vseh povezanih virov (spletna karta, geoobjektna storitev, okrasni sloj), ki niso deljeni na enak način. Če je Potopisna karta javna in eden od vaših virov ni deljen z vašim občinstvom, bodo uporabniki preusmerjeni na stran za prijavo ArcGIS Online.",
        "div3t": "Varnost geoobjektne storitve",
        "div3a": "Če uporabljate gostujočo geoobjektno storitev, ustvarjeno z graditeljem Potopisnih kart, aplikacija upravlja varnost storitve za vas in boste ostali edini s pravicami urejanja, tudi če storitev delite javno.",
        "div3t2": "Pred deljenjem vašega Potopisa z občinstvom",
        "div3": "Prepričajte se, da Potopis dobro deluje tudi, ko niste prijavljeni s svojim računom ArcGIS.com. URL, ki ga boste uporabili, ne bi smel preusmerjati na stran za prijavo ali na graditeljski način.",
        "div4": "Dobro je preveriti, kako je vaš potopis videti na iPadu v ležečem položaju, da se prepričate, da je na tej priljubljeni napravi videti prav. To vam lahko pomaga preveriti, ali vaši napisi prekrivajo prevelik del slik. Prav tako vam omogoča preveriti, ali podnapisi ustrezajo in morda niso predolgi, da ne bi bili porezani.",
        "div5a": "Priporočila za iskanje",
        "div5b": "Da bi ljudem pomagali poiskati vašo Potopisno karto, če iščejo po ArcGIS Online, priporočamo, da dodate oznako »karta z zgodbo« na stran elementov aplikacije potopisne karte (ne na stran elementov spletne karte) skupaj z oznakami, kot so ime države ali province, v kateri se nahaja potopis, ime države, če je zunaj ZDA, in tematske oznake, kot so »umetnine na javnih mestih«, »turistični vodič« ali »zgodovinski kraji«. Te oznake pomagajo tudi nam v podjetju Esri, da najdemo nove primere super potopisov, ki jih lahko predstavimo v naših galerijah ali promoviramo na družbenih omrežjih. Prav tako priporočamo, da na stran elementov aplikacije naložite lepo grafiko sličice, kot je recimo majhen posnetek zaslona potopisa ali ena od slik v njem. Ta slika je uporabljena samodejno, če je vaša potopisna karta dodana v galerijo ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Potopis je shranjen",
      "manageStory": "Upravljajte svojo zgodbo",
      "manageStoryA1": "Namig: Za preverjanje napak v svoji zgodbi in spreminjanje načina deljenja njenih sestavnih delov, lahko uporabite %LINK1%. Možnost Moje zgodbe vam pomaga, da je vaša zgodba videti dobro, ko jo delite na družbenih omrežjih. Več o drugih uporabnih možnostih Mojih zgodb boste izvedeli na %LINK2%.",
      "manageStoryA1V1": "Moje zgodbe",
      "manageStoryA1V2": "objave na blogu",
      "shareTitle": "Delite svoj Potopis",
      "sharePrivateHeader": "Vaš Potopis ni deljen, ga želite deliti?",
      "sharePrivateBtn1": "Deli javno",
      "sharePrivateBtn2": "Deli z mojo organizacijo",
      "sharePrivateProgress": "Deljenje v teku ...",
      "sharePrivateErr": "Deljenje ni uspelo, poskusite znova ali",
      "sharePrivateOk": "Deljenje posodobljeno, nalaganje ...",
      "sharePreviewAsUser": "Predogled",
      "shareHeader1": "Vaš Potopis je <strong>javno dostopen</strong>.",
      "shareHeader2": "Vaš Potopis je dostopen članom vaše organizacije (obvezna je prijava).",
      "shareLinkHeader": "Delite svoj Potopis",
      "shareLinkOpen": "ODPRI",
      "shareA1": "Uporabite %SHAREIMG% na <a href='%LINK1%' target='_blank'>strani elementov aplikacije</a>. Če želite prenehati deliti spletno karto, uporabite <a href='%LINK2%' target='_blank'>spletno stran elementa karte</a>.",
      "shareWarning": "Deljenje %WITH% je onemogočeno, ker niste lastnik <a href='%LINK%' target='_blank'>spletne karte</a>.",
      "shareWarningWith1": "javno",
      "shareWarningWith2": "javno in z organizacijo"
    },
    "locator": {
      "error": "Lokacija ni na voljo"
    },
    "saveErrorSocial": {
      "title": "Posodobitev deljenja na družbenih omrežjih",
      "panel1": "Prisotnost vaše zgodbe na družbenih omrežjih je izboljšana, vendar ime elementa vaše spletne aplikacije ArcGIS ni enako imenu vaše zgodbe.",
      "panel1tooltip": "Z določitvijo imena, povzetka in sličice bo vaša zgodba videti tako:",
      "panel2": "Katero ime želite uporabiti na družbenih omrežjih:",
      "panel2q1": "Ime zgodbe (priporočeno)",
      "panel2q1tooltip": "Če izberete to možnost, se bo ime vašega elementa spremenilo zaradi ujemanja z imenom vaše zgodbe, dodatne spremembe pa bodo sinhronizirane v graditelju.",
      "panel2q2": "Naslov elementa",
      "panel3": "Za nadaljnje izboljševanje videza vaše zgodbe na družbenih omrežjih uporabite ${MYSTORIES} in dodajte povzetek in sličico.",
      "panel4": "Ne opozarjaj me več za to zgodbo",
      "mystories": "Moje zgodbe",
      "btnSave": "Shrani"
    }
  }
});