define({
  "viewer": {
    "loading": {
      "step1": "NAČÍTÁNÍ PŘÍBĚHU",
      "step2": "NAHRÁVÁNÍ DAT",
      "step3": "SPOUŠTĚNÍ PROHLÍDKY",
      "loadBuilder": "PŘEPÍNÁNÍ DO REŽIMU TVORBY",
      "redirectSignIn": "PROBÍHÁ PŘESMĚROVÁNÍ NA PŘIHLAŠOVACÍ STRÁNKU",
      "redirectSignIn2": "(budete sem přesměrováni po přihlášení)",
      "fail": "Nepodařilo se bohužel načíst prohlídku mapy.",
      "failButton": "Zkusit znovu"
    },
    "errors": {
      "boxTitle": "Nastala chyba.",
      "portalSelf": "Závažná chyba: Nepodařilo se získat konfiguraci portálu.",
      "invalidConfig": "Závažná chyba: Neplatná konfigurace",
      "invalidConfigOwner": "Závažná chyba: Neplatná konfigurace (vyžadován autorizovaný vlastník)",
      "invalidConfigNoWebmap": "Závažná chyba: Neplatná konfigurace (v index.html není specifikována webová mapa nebo identifikátor aplikace)",
      "invalidConfigNoAppDev": "V parametrech adresy URL nebyl zadán identifikátor webové mapovací aplikace ani identifikátor webové mapy (?appid= nebo ?webmap=). V režimu vývoje jsou ID aplikace a konfigurace webové mapy v souboru index.html ignorovány.",
      "createMap": "Nelze vytvořit mapu",
      "invalidApp": "Závažná chyba: Příběh nelze načíst",
      "noLayer": "Webová mapa neobsahuje platnou datovou vrstvu k prohlídce mapy.",
      "noLayerMobile": "Nástroj pro tvorbu příběhu podle šablony pro prohlídku mapy není v této velikosti zobrazení podporován. Pokud je to možné, zvětšete velikost prohlížeče nebo příběh vytvořte na zařízení s větší obrazovkou.",
      "noLayerMobile2": "Aby bylo možné použít nástroj pro tvorbu prohlídky mapy, otočte své zařízení na šířku.",
      "noLayerView": "Vítejte ve webové aplikaci prohlídky mapy.<br />Příběh zatím není nakonfigurován.",
      "appSave": "Chyba při ukládání příběhu",
      "mapSave": "Chyba při ukládání webové mapy",
      "featureServiceLoad": "Chyba při načítání služby Feature Service",
      "notAuthorized": "Nejste oprávněni přistupovat k tomuto příběhu",
      "notAuthorizedBuilder": "Nejste oprávněni používat nástroj pro tvorbu prohlídky mapy.",
      "oldBrowserTitle": "Prohlížeč není plně podporován.",
      "noBuilderIE8": "Nástroj pro tvorbu prohlídek map není podporován programem Internet Explorer verze nižší než 9.",
      "ie10Win7Explain": "Interaktivní nástroj pro tvorbu prohlídek map není podporován prohlížečem Internet Explorer 10 ve Windows 7, pokud je zdrojem dat služba Feature Service s přílohami. Chcete-li použít službu Feature Service s přílohami, bude nutné <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuálně přepnout režim dokumentu na standardy Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>downgradovat na Internet Explorer 9</a> nebo upgradovat na Windows 8.",
      "oldBrowserExplain": "Váš prohlížeč nepodporuje automatickou tvorbu miniatur z obrázků nahraných do prohlídky mapy. Prohlídku mapy lze v prohlížeči vytvořit, bude však nutné ke každému nahranému obrázku dodat samostatnou miniaturu.",
      "oldBrowserExplain2": "Pro plynulejší chod <a href='http://browsehappy.com/' target='_blank'>stáhněte jiný prohlížeč</a> nebo <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>nainstalujte Google Chrome Frame pro Internet Explorer</a>.",
      "oldBrowserExplain3": "Nástroj pro tvorbu prohlídek map nefunguje v prohlížeči Internet Explorer 10 ve Windows XP.",
      "oldBrowserClose": "Zavřít",
      "noViewerIE2": "Pokoušíte se tento příběh prohlížet pomocí staršího, nepodporovaného prohlížeče. Některé funkce nemusí fungovat nebo se mohou vyskytnout jiné nečekané problémy. Doporučujeme přejít na Internet Explorer 11 nebo použít jiný prohlížeč, například Chrome.",
      "noViewerIE3": "Koncem roku 2017 se tento příběh v tomto prohlížeči již nenačte. K jeho prohlížení bude nutné použít podporovaný prohlížeč.",
      "attention": "Upozornění!"
    },
    "mobileHTML": {
      "showIntro": "ZOBRAZIT NADPIS",
      "hideIntro": "SKRÝT NADPIS",
      "navList": "Seznam",
      "navMap": "Mapa",
      "navInfo": "Média",
      "introStartBtn": "Spustit"
    },
    "desktopHTML": {
      "storymapsText": "Mapa s příběhem",
      "builderButton": "Přepnout do režimu tvorby",
      "facebookTooltip": "Sdílet na Facebooku",
      "twitterTooltip": "Sdílet na Twitteru",
      "bitlyTooltip": "Získat krátký odkaz",
      "bitlyStartIndex": "Odkaz na současné místo",
      "tooltipAutoplayDisabled": "Není k dispozici v režimu automatického přehrávání.",
      "autoplayLabel": "Režim automatického přehrávání",
      "autoplayExplain1": "Režim automatického přehrávání bude příběhem procházet v pravidelných intervalech. Ideální pro použití na výstavních stáncích nebo veřejných monitorech, buďte si však vědomi toho, že to v některých případech může znesnadnit čtení příběhu. Tato funkce není podporována na malých obrazovkách.",
      "autoplayExplain2": "Je-li tento režim aktivní, budou k dispozici ovládací prvky ke spuštění/pozastavení přehrávání příběhu a k nastavení rychlosti procházení.",
      "takeTourText": "Zahájit prohlídku",
      "backToStart": "Zpět na Start"
    },
    "builderHTML": {
      "panelHeader": "KONFIGURACE PŘÍBĚHU",
      "buttonSave": "ULOŽIT",
      "buttonSettings": "Nastavení",
      "buttonShare": "Sdílet",
      "buttonView": "Režim prohlížení",
      "buttonItem": "Otevřít položku webové aplikace",
      "buttonHelp": "Nápověda",
      "buttonOrganize": "Organizovat",
      "buttonAdd": "Přidat",
      "buttonImport": "Import",
      "buttonImportDisabled": "Import není dostupný, pokud je využívána služba Feature Service s přílohami.",
      "dataEditionDisabled": "Úprava dat je u tohoto zdroje dat ve formátu CSV zakázána.",
      "dataSourceWarning": "Vrstva prohlídky mapy se změnila. Nejsou-li ID prvků stejná, musíte resetovat pořadí a skryté body pomocí volby <b>Organizovat</b>. Pokud se liší názvy polí, musíte resetovat nastavení polí v <b>záložce dat v Nastavení</b>.",
      "organizeWarning": "Jeden nebo více bodů přidaných mimo interaktivní nástroj pro tvorbu jsou skryty.",
      "dataPicError0a": "Tato prohlídka obsahuje <b>%NB%</b> nevyhovujících URL obrázků.",
      "dataPicError0b": "Tato prohlídka může obsahovat <b>%NB%</b> nevyhovujících URL obrázků.",
      "dataPicError1": "Prohlídky map nyní vyžadují, aby URL obrázků měly jednu z těchto přípon: jp(e)g, png, gif nebo bmp.",
      "dataPicError2": "Tento požadavek nebude mít vliv na existující publikované prohlídky mapy. Aby však bylo možné používat interaktivní nástroj pro tvorbu, je nutné nejprve vyřešit problém s URL provedením jedné z následujících akcí:",
      "dataPicError3": "Upravit URL",
      "dataPicError4": "Tato možnost přidá na konec adres URL nepodporovaných obrázků parametr <i>#isImage</i>. Většina serverů dodatky k adresám URL podporuje. Po provedení této akce je vhodné si navigací mezi body ověřit, zda jsou aktualizované URL obrázků funkční. Pokud se všechny obrázky načtou, můžete prohlídku mapy uložit. Pokud jsou <b>některé obrázky nefunkční, neukládejte prohlídku mapy</b>. Namísto toho znovu načtěte nástroj pro tvorbu a proveďte druhou nabídnutou akci.",
      "dataPicError5": "Omezit prohlídku na obrázky",
      "dataPicError6": "Tato možnost způsobí, že budou všechny URL adresy považovány za obrázky. Pomocí interaktivního nástroje pro tvorbu však nebude možné přidávat videa. Pokud se v budoucnosti rozhodnete přidávat videa, lze tuto akci vrátit zpět.",
      "dataPicError7": "Vaše prohlídka mapy byla omezena na obrázky, není možné používat videa. Pokud se rozhodnete toto omezení odebrat, před uložením prohlídky se ujistěte, že se všechny obrázky stále správně načítají. V případě potřeby budete moci toto omezení později znovu obnovit.",
      "dataPicError8": "Odebrat omezení na obrázky",
      "dataPicError9": "Pokud tyto URL adresy odkazují na videa, můžete toto upozornění ignorovat. Pokud odkazují na obrázky, je nutné provést jednu z následujících akcí:",
      "modalCancel": "Storno",
      "modalApply": "Použít",
      "organizeHeader": "Organizovat prohlídku",
      "organizeGeneralCaption": "Uspořádejte body prohlídky jejich přetáhnutím.",
      "organizeDelete": "Smazat",
      "organizeHide": "Skrýt",
      "organizeReset": "Resetovat pořadí a skryté body.",
      "addMaxPointReached": "Dosáhli jste maximálního počtu bodů autorizovaných sadou ikon a nemůžete již přidat další bod prohlídky.<br /><br />Vymažete-li již existující body, budete muset příběh otevřít znovu.",
      "addMaxPointReachedMobile": "Omlouváme se, dosáhli jste maximálního počtu autorizovaných bodů a tento obrázek proto nemůžete přidat.",
      "addClose": "Zavřít",
      "addHeader": "Přidat nový bod prohlídky",
      "addTabPicture": "Média",
      "addTabInformation": "Informace",
      "addTabLocation": "Umístění",
      "addSelectCaption": "Vyberte nebo přetáhněte obrázek.",
      "addNoteVideo": "Více informací o používání videí naleznete v nápovědě",
      "addSelectCaptionNoFileReader": "Vybrat obrázek",
      "addChangePhoto": "Změnit obrázek a miniaturu",
      "addPictureResolutionIntro": "Rozlišení obrázku je příliš vysoké.",
      "addPictureResolutionOldBrowser": "Rozlišení obrázku je příliš vysoké. Optimalizujte chod prohlídky mapy použitím rozlišení, které je nižší než %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Změnit rozlišení obrázku na %RESOLUTION%",
      "addPictureResolutionKeep": "Ponechat původní rozlišení %RESOLUTION%",
      "addSelectThumbnail": "Vybrat miniaturu",
      "addNoThumbSelected": "Není vybrána žádná miniatura",
      "addThumbSelected": "Vybrána",
      "addCameraSettingsHeader": "NASTAVENÍ FOTOAPARÁTU",
      "addThumbnailHeader": "MINIATURA",
      "addLabelPicUrl": "Obrázek",
      "addLabelThumbUrl": "Miniatura",
      "addTextPlaceholderUrl": "Zadejte URL obrázku.",
      "addTextPlaceholderUrl2": "Zadejte adresu URL YouTube stránky.",
      "addTextPlaceholderUrl3": "Zadejte URL stránky Vimeo.",
      "addTextPlaceholderUrl4": "Zadejte URL pro vložení videa.",
      "addLabelVideo": "Video",
      "addMediaVideoOther": "Jiné",
      "addMediaVideoHelp": "Zkontrolovat URL a získat výchozí miniaturu",
      "addMediaVideoHelpTooltip1": "Kontrola byla úspěšná.",
      "addMediaVideoHelpTooltip2": "Kontrola se nezdařila.",
      "addMediaVideoHelpTooltip4": "Najděte možnost vložení videa a zkopírujte URL videa, které se nachází v kódu",
      "addLabelName": "Název",
      "addLabelDescription": "Popisek",
      "addTextPlaceholder": "Napište zde něco",
      "addLocatePlaceholder": "Najít adresu nebo místo",
      "addPinColor": "Barva",
      "addLatitude": "Zeměpisná šířka",
      "addLongitude": "Zeměpisná délka",
      "addLatitudePlaceholder": "např. 34,056",
      "addLongitudePlaceholder": "např. -117,195",
      "addUploading": "Nahrávání bodu prohlídky",
      "addSave": "Přidat bod prohlídky",
      "addMobileUploading": "Nahrávání obrázku",
      "addMobileName": "Zadejte jméno",
      "addMobileNameMandatory": "Chyba, zadejte prosím název.",
      "addMobileError": "Omlouváme se, někde se stala chyba.",
      "settingsHeader": "Nastavení příběhu",
      "settingsTabLayout": "Rozvržení",
      "settingsTabColor": "Barvy",
      "settingsTabLogo": "Záhlaví",
      "settingsTabFields": "Data",
      "settingsTabExtent": "Rozsah",
      "settingsTabZoom": "Úroveň přiblížení",
      "settingsLayoutExplain": "Vyberte požadované rozvržení.",
      "settingsLayoutProfessional": "Trojpanel",
      "settingsLayoutModern": "Integrovaný",
      "settingsLayoutSidePanel": "Postranní panel",
      "settingsLayoutSelected": "Vybrané rozvržení",
      "settingsLayoutNew": "Novinka!",
      "settingsLayoutSelect": "Výběr (Select)",
      "settingsLayoutNote": "Při používání videí na bodech bude pod videem vždy poutač, i když tato možnost není zaškrtnuta.",
      "settingsLayoutLocBtn": "Zobrazit tlačítko 'Lokalizovat'",
      "settingsLayoutLocBtnHelp": "Podporováno většinou prohlížečů. Zobrazuje se pouze, pokud se k mapě s příběhem přistupuje přes HTTPS. Nezobrazuje se, pokud je příběh vložený.",
      "settingsColorExplain": "Změňte vzhled volbou přednastaveného motivu, nebo si vytvořte svůj vlastní.",
      "settingsLabelColor": "Barvy záhlaví, obsahu a zápatí",
      "settingsLogoExplain": "Přizpůsobte logo v záhlaví (maximum je 250 × 50 px).",
      "settingsLogoEsri": "Logo Esri",
      "settingsLogoNone": "Bez loga",
      "settingsLogoCustom": "Vlastní logo",
      "settingsLogoCustomPlaceholder": "URL obrázku",
      "settingsLogoCustomTargetPlaceholder": "Odkaz při kliknutí na obrázek",
      "settingsLogoSocialExplain": "Upravit odkaz v pravé horní části záhlaví.",
      "settingsLogoSocialText": "Text",
      "settingsLogoSocialLink": "Odkaz",
      "settingsLogoSocialDisabled": "Tato funkce byla zakázána administrátorem.",
      "settingsDataFieldsExplain": "Vyberte pole názvu, popisku a barvy.",
      "settingsDataFieldsError": "Aplikace nedokáže určit vhodná data názvu, popisku nebo barvy. Zvolte prosím pole, která mají být použita. Toto nastavení lze kdykoliv změnit.",
      "settingsFieldsLabelName": "Název",
      "settingsFieldsLabelDescription": "Popisek",
      "settingsFieldsLabelColor": "Barva",
      "settingsFieldsReset": "Resetovat výběr polí.",
      "settingsExtentExplain": "Prostřednictvím následující interaktivní mapy nastavte výchozí rozsah prohlídky mapy.",
      "settingsExtentExplainBottom": "Vámi definovaný rozsah upraví počáteční rozsah vaší webové mapy. Pokud rozsah neobsahuje první bod prohlídky, nepoužije se. Prohlídka se v takovém případě otevře vycentrovaná na první bod.",
      "settingsExtentDateLineError": "Rozsah nesmí přesahovat 180° zeměpisné délky.",
      "settingsExtentDateLineError2": "Při výpočtu rozsahu došlo k chybě.",
      "settingsExtentDrawBtn": "Určit nový rozsah",
      "settingsExtentModifyBtn": "Upravit rozsah",
      "settingsExtentApplyBtn": "Zobrazit náhled na prohlídce mapy",
      "settingsExtentUseMainMap": "Použít rozsah prohlídky mapy",
      "settingsZoomExplain": "Nastavit přiblížení bodů příběhu (volitelné).",
      "settingsLabelZoom": "Měřítko/úroveň",
      "settingsZoomFirstValue": "Žádné",
      "settingsFieldError": "Vyberte pole v každém seznamu.",
      "dataTitle": "Vytvořit hostovanou vrstvu prohlídky mapy",
      "dataExplain": "Pro vaše obrázky a body prohlídky bude vytvořena nová vrstva prvků. Tato vrstva prohlídky nebude s nikým sdílena, nebudete-li také sdílet prohlídku mapy.",
      "dataExplainPortal": "Tento prvek vyžaduje Portal for ArcGIS 10.4, Pokud se vám nedaří vytvořit vrstvu prvků, obraťte se na svého správce ArcGIS.",
      "dataNameLbl": "Jméno vrstvy",
      "dataFolderListLbl": "Složka",
      "dataFolderListFetching": "Načítání složek…",
      "dataRootFolder": "Kořenový adresář",
      "dataNameError": "Zadejte název služby Feature Service",
      "dataFolderError": "Vyberte platnou složku",
      "dataSrcContainsInvalidChar": "Jméno služby obsahuje jeden nebo několik neplatných znaků (-, <, >, #, %, :, \", ?, &, +, /, nebo ).",
      "dataSrvAlreadyExistsError": "Služba s tímto jménem už v mapách organizace existuje. Zvolte prosím jiné jméno.",
      "dataBtnSave": "Vytvořit vrstvu",
      "dataFooterProgress": "Služba se vytváří",
      "dataFooterSucceed": "Vytvoření se podařilo. Načítání",
      "dataFooterError": "Vytvoření se nezdařilo. Zkuste to znovu.",
      "tabError": "Zkontrolujte prosím, nejsou-li v záložkách chyby.",
      "introRecordBtn": "Úvod",
      "introRecordActivate": "Použít první bod jako úvod (nezobrazuje se v karuselu)",
      "coverRecordActivate": "Použít první bod jako úvodní stránku",
      "coverBuilder": "Konfigurace úvodní stránky",
      "cover": "Obal",
      "showCover": "Ukázat úvodní stránku",
      "editCover": "Editovat úvodní stránku",
      "coverNoVideo": "Na úvodní stránce nelze použít video. Prosím vyberte obrázek.",
      "coverPreview": "Pokud si chcete prohlédnout úvodní stránku, uložte svůj příběh a otevřete náhled pomocí tlačítka Sdílet."
    },
    "addPopupJS": {
      "uploadingPicture": "Nahrávání obrázku",
      "uploadSuccess": "Nahrání proběhlo úspěšně.",
      "uploadError": "Při nahrávání obrázku nastala chyba.",
      "uploadError2": "Chyba při přidávání prvku (neplatný HTML tag)",
      "notJpg": "Vyberte prosím soubor jpeg, který chcete nahrát.",
      "errorNoPhoto": "Vyberte obrázek, který chcete nahrát.",
      "errorNoThumbnail": "Vyberte miniaturu, kterou chcete nahrát.",
      "errorInvalidPicUrl": "Zadejte platný obrázek (začíná http(s):// a končí příponou jpg, png, gif nebo bmp). Chcete-li tento požadavek potlačit, vložte na konec URL parametr #isImage.",
      "errorInvalidThumbUrl": "Zadejte platnou miniaturu (začíná http(s):// a končí příponou jpg, png, gif nebo bmp).",
      "errorInvalidVideoUrl": "Zadejte platnou adresu URL videa (začíná http(s)://).",
      "errorNoName": "Zadejte jméno tohoto bodu prohlídky.",
      "errorNoDescription": "Zadejte popisek tohoto bodu prohlídky.",
      "errorNoLocation": "Nastavte umístění tohoto bodu prohlídky."
    },
    "builderJS": {
      "noPendingChange": "Žádná neuložená změna",
      "unSavedChangeSingular": "1 neuložená změna",
      "unSavedChangePlural": "neuložených změn",
      "shareStatus1": "Prohlídka není uložena",
      "shareStatus2": "Prohlídka je veřejně sdílena",
      "shareStatus3": "Prohlídka je sdílena v rámci organizace",
      "shareStatus4": "Prohlídka není sdílena",
      "popoverDiscard": "Určitě chcete přijít o všechny neuložené změny?",
      "yes": "Ano",
      "no": "Ne",
      "popoverLoseSave": "Otevřením tohoto prohlížeče přijdete o všechny neuložené změny.",
      "ok": "OK",
      "popoverSaveWhenDone": "Až budete hotovi, nezapomeňte provedené změny uložit.",
      "closeWithPendingChange": "Určitě chcete potvrdit tuto akci? Vaše změny nebudou uloženy.",
      "gotIt": "OK",
      "savingApplication": "Ukládání příběhu",
      "saveSuccess": "Příběh uložen",
      "saveError": "Uložení se nezdařilo, zkuste to znovu.",
      "saveError2": "Ukládání selhalo kvůli neplatnému HTML tagu v názvu nebo popisu.",
      "saveError3": "Název nesmí být prázdný",
      "dragColorPicker": "Přesuň<br />nebo změň  barvu.",
      "dataWarningExtent": "Některá data se nachází mimo rozsah webové mapy. Tato data nebudou použita jako body prohlídky. Chcete-li je použít, změňte rozsah mapy.",
      "dataWarningVisibi": "Vrstva prohlídky mapy není při současném rozsahu webové mapy viditelná. Ujistěte se, že je vrstva prohlídky mapy viditelná v mapě o velikosti %MAPSIZE%.",
      "dataWarningEdit": "Upravit webovou mapu",
      "dataWarningClose": "Zavřít",
      "signIn": "Přihlaste se pomocí účtu na",
      "signInTwo": "pro uložení příběhu.",
      "switchBM": "Změnit podkladovou mapu"
    },
    "organizePopupJS": {
      "messageStart": "Přejete si odstranit",
      "messageSinglePoint": "bod prohlídky",
      "messageMultiPoint": "body prohlídky",
      "messagePermantRemove": "Tato činnost nevratně odstraní",
      "messageRecord": "záznam",
      "messageRecordPlural": "záznamy",
      "messageConfirm": "z vaší databáze. Přejete si pokračovat?",
      "labelButtonShow": "Zobrazit",
      "labelButtonHide": "Skrýt"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Tato činnost nevratně odstraní obrázek a miniaturu.",
      "popoverDeleteWarningThumb": "Tato činnost nevratně odstraní miniaturu.",
      "popoverUploadingPhoto": "Nahrávání obrázku a miniatury",
      "popoverUploadingThumbnail": "Nahrávání miniatury",
      "popoverUploadSuccessful": "Nahrání proběhlo úspěšně.",
      "popoverUploadError": "Nahrání se nezdařilo, zkuste to znovu.",
      "changePicAndThumb": "Změnit obrázek",
      "changeThumb": "Změnit miniaturu",
      "selectPic": "Změnit média",
      "selectThumb": "Změnit miniaturu",
      "uploadPicAndThumb": "Použít"
    },
    "headerJS": {
      "editMe": "Edituj mě!",
      "templateTitle": "Nastavit název šablony",
      "templateSubtitle": "Nastavit podnadpis šablony",
      "edit": "Upravit"
    },
    "crossFaderJS": {
      "setPicture": "Nastavit název obrázku",
      "setCaption": "Nastavit popisek obrázku"
    },
    "importPopup": {
      "title": "Import",
      "prevBtn": "Zpět",
      "nextBtn": "Další"
    },
    "importPopupHome": {
      "header": "Kde máte obrázky uloženy?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "obrázky",
      "videos": "videa",
      "disabled": "Tato funkce byla zakázána administrátorem.",
      "disabledPortal": "Tato součást vyžaduje, aby měl portál hostující server. Obraťte se na svého správce pro Portal for ArcGIS.",
      "header1": "Vaše obrázky musí být sdíleny veřejně.",
      "header2": "Import bude omezen na prvních %NB1% %MEDIA%.",
      "emptyDataset": "Chyba: nebyly nalezeny žádné obrázky",
      "footerImport": "Import",
      "selectAlbum": "Vybrat veřejné album",
      "selectAlbum2": "Vybrat album",
      "pleaseChoose": "Prosím vyberte.",
      "userLookup": "Vyhledat",
      "userLookingup": "Vyhledávání",
      "csv": "Odkazováno ze souboru CSV",
      "advanced": "Pokročilé možnosti",
      "advancedScratchLbl": "Začít novou prohlídku",
      "advancedScratchTip": "Vytvořte prázdnou prohlídku, do které budete přidávat prohlídkové body. Vaše média už musí být online. Tato možnost nepodporuje nahrávání obrázků.",
      "advancedCSVLbl": "Importovat data prohlídky ze souboru CSV",
      "advancedCSVTip": "Importujte obsah své prohlídky ze souboru CSV, který odkazuje na vaše média online. Tato možnost nepodporuje nahrávání obrázků.",
      "advancedCommonTip": "Je nutné, aby obrázky a videa už byly online.",
      "select": "Provést výběr",
      "locUse": "Používat geo-umístění obrázků",
      "locExplain": "Používat lokaci obrázků nemusí být vždy vhodné, protože může být převzata z alba. Všechny obrázky by tak byly umístěny ve stejné lokaci.",
      "locExplain2": "Používat lokaci videí nemusí být vždy vhodné, protože může být převzata z uživatelských nastavení. Všechna videa by tak byla umístěna ve stejné lokaci."
    },
    "viewFlickr": {
      "title": "Import z Flickru",
      "header": "Zadejte své uživatelské jméno ve službě Flickr a vyberte sadu fotografií nebo značku k importu.",
      "userInputLbl": "Zadat uživatelské jméno",
      "signInMsg2": "Uživatel nenalezen",
      "selectSet": "Vybrat sadu fotografií",
      "selectTag": "nebo Vybrat značku",
      "footerImportTag": "Importovat vybranou značku",
      "footerImportSet": "Importovat vybranou sadu"
    },
    "viewFacebook": {
      "title": "Import z Facebooku",
      "header": "Proveďte ověření prostřednictvím svého uživatelského účtu Facebook nebo použijte veřejnou stránku. Soukromá alba lze využívat k vytváření veřejných prohlídek map, které nevyžadují ověření uživatele ve službě Facebook. Díky tomu zůstávají komentáře a označení tlačítkem To se mi líbí neveřejné.",
      "leftHeader": "Uživatel služby Facebook",
      "rightHeader": "Stránka služby Facebook",
      "pageExplain": "Stránka služby Facebook představuje veřejnou značku či službu nebo známou osobnost, jako je například <b>esrigis</b>. Název stránky začíná za prvním lomítkem (/) v URL adrese stránky.",
      "pageInputLbl": "Zadat název stránky",
      "lookupMsgError": "Stránka nenalezena"
    },
    "viewPicasa": {
      "title": "Import Picasa",
      "header": "Zadejte svou e-mailovou adresu nebo identifikátor služby Picasa.",
      "userInputLbl": "E-mail nebo identifikátor služby Picasa",
      "signInMsg2": "Účet nenalezen",
      "signInMsg3": "Žádné veřejné album",
      "howToFind": "Jak zjistit identifikátor služby Picasa",
      "howToFind2": "Zkopírujte čísla mezi prvním a druhým znakem „/“ na libovolné stránce služby Picasa"
    },
    "viewCSV": {
      "title": "Import CSV",
      "uploadBtn": "Vybrat nebo přetáhnout soubor CSV",
      "resultHeaderEmpty": "Soubor CSV je prázdný",
      "resultHeaderSuccess": "Načteno %NB_POINTS% bodů",
      "resultHasBeenLimited": "Import byl omezen na prvních %VAL1% bodů z %VAL2%, aby byl dodržen limit %VAL3% bodů na prohlídku.",
      "browserSupport": "Váš prohlížeč není podporován. Chcete-li používat formát CSV, bude nutné <a href='http://browsehappy.com/' target='_blank'>upgradovat prohlížeč</a> nebo použít webový prohlížeč map ArcGIS.com (viz nápověda).",
      "errorLatLng": "Pole pro zeměpisnou šířku a délku nebyly nalezeny. Možné hodnoty pro zeměpisnou šířku jsou <i>%LAT%</i> a pro délku <i>%LONG%</i>.",
      "errorFieldsExplain": "Načtení se nezdařilo, protože nebyla nalezena následující pole:",
      "errorFieldsName": "<b>Název</b>, možné hodnoty: %VAL%",
      "errorFieldsDesc": "<b>Popis</b>, možné hodnoty: %VAL%",
      "errorFieldsUrl": "<b>URL obrázku</b>, možné hodnoty: %VAL%",
      "errorFieldsThumb": "<b>URL miniatury</b>, možné hodnoty: %VAL%",
      "errorFields2Explain": "Načtení se nezdařilo, protože soubor CSV nepoužívá stejné atributy, jako vrstva pro následující atributy.",
      "errorFields2Name": "<b>Název</b> – použijte hodnotu %VAL1% místo hodnoty %VAL2%",
      "errorFields2Desc": "<b>Popis</b> – použijte hodnotu %VAL1% místo hodnoty %VAL2%",
      "errorFields2Url": "<b>URL obrázku</b> – použijte hodnotu %VAL1% místo hodnoty %VAL2%",
      "errorFields2Thumb": "<b>URL miniatury</b> – použijte hodnotu %VAL1% místo hodnoty %VAL2%",
      "resultFieldsAll": "Všechny atributy byly importovány.",
      "resultFieldsNotAll": "Následující atributy nebyly importovány, protože v mapové vrstvě neexistují.",
      "resultFieldsNotAll2": "Byly importovány následující atributy:",
      "footerNextBtnResult": "Import do webové mapy",
      "footerProgress": "Probíhá import",
      "footerSucceed": "Import byl úspěšný. Načítání"
    },
    "viewYoutube": {
      "title": "Import z YouTube",
      "header": "Zadejte uživatelské jméno YouTube, abyste našli veřejně sdílená videa.",
      "pageInputLbl": "Zadejte uživatelské jméno YouTube.",
      "lookupMsgError": "Uživatel nenalezen",
      "howToFind": "Jak najít uživatelské jméno YouTube",
      "howToFind2": "Uživatelské jméno se zobrazuje pod videi",
      "found": "Nalezeno",
      "noData": "Nenalezena žádná veřejná videa"
    },
    "viewGeoTag": {
      "title": "Vyberte a lokalizujte své obrázky/videa",
      "header": "Klikněte nebo klepněte na obrázky, které chcete importovat, abyste je našli.",
      "headerMore": "Proč nejsou mé obrázky/videa geolokalizovány?",
      "headerExplain": "Pokud vaše snímky mají platnou geolokaci, budou automaticky umístěny na mapě a uvedeny v druhé kartě.<br /><br />Služby Picasa a Flickr ve výchozím nastavení při importu obrázků neukládají geolokační metadata EXIF. Zkontrolujte, zda je v nastavení soukromí služby Picasa/Flickr povolen import geolokace snímků a použití externí aplikací. Je možné, že budete muset své stávající snímky do služby Flickr/Picasa znovu naimportovat, aby bylo možné využít jejich geolokační metadata EXIF.",
      "leftPanelTab1": "Umístit",
      "leftPanelTab2": "Umístěno",
      "clickOrTap": "Kliknutím nebo klepnutím na mapu provedete umístění.",
      "clearLoc": "Smazat umístění",
      "clickDrop": "Neimportovat",
      "footerImport": "Import",
      "footerProgress": "Probíhá import",
      "footerSucceed": "Import byl úspěšný. Načítání…",
      "loading": "Načítání",
      "error": "Nezdařil se import geo-umístění obrázků, geo-umístění byla ignorována."
    },
    "initPopup": {
      "title": "Vítejte v Nástroji pro tvorbu prohlídek map",
      "prevBtn": "Zpět",
      "nextBtn": "Další"
    },
    "initPopupHome": {
      "header1": "Kde jsou vaše obrázky nebo videa?",
      "header2": "Tento asistent vám pomůže vytvořit prohlídku mapy z médií, která jsou již uložena online, případně je importuje do vašeho účtu ArcGIS Online pro organizace.",
      "title1": "Jsou již online",
      "title2": "Potřebuji nahrát své obrázky",
      "hostedFSTooltip": "Nahrajte obrázky a uložte je do své prohlídky (nepodporuje video).",
      "hostedFsNA": "Musíte být tvůrce nebo mít jinou roli s oprávněním zveřejňovat hostované vrstvy prvků. Obraťte se na svého správce ArcGIS.",
      "hostedFsNA2": "K dispozici pouze s předplatným ArcGIS Online. <a href='%LINK%'>Zaregistrujte si bezplatnou zkušební verzi</a>",
      "footer1": "Až budete hotovi, nezapomeňte prohlídku mapy sdílet se svým publikem na stránce položek aplikace.",
      "footer3": "Stáhnout šablony CSV",
      "footer4": "Pokud se nestáhne, zvolte možnost \"Uložit jako\".",
      "footer4bis": "Pokud se stahování nespustí, použijte kliknutí pravým tlačítkem a  \"Uložit jako\"",
      "footer5": "Více informací",
      "footerProgress": "Probíhá vytváření",
      "footerSucceed": "Úspěšně vytvořeno. Načítání..."
    },
    "helpPopup": {
      "title": "Nápověda",
      "close": "Zavřít",
      "tab1": {
        "title": "Úvod",
        "moreInfo": "Další informace",
        "infoSites": "Navštivte sekci <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>Prohlídka mapy</a> na <a href='https://storymaps.arcgis.com' target='_blank'>webové stránce map s příběhem společnosti Esri.</a>",
        "mtFAQ": "<a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Často kladené dotazy o prohlídce mapy.</a>",
        "myStories": "Na této webové stránce v sekci <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Moje příběhy</a> můžete spravovat a kontrolovat správnost svých prohlídek map.",
        "div1": "Tato šablona prohlídky mapy je navržena pro prezentaci geografických informací, pokud k příběhu, který chcete vyprávět, existuje atraktivní fotografický nebo mediální prvek.",
        "div2": "Pomocí šablony lze vytvořit atraktivní a snadno ovladatelnou webovou aplikaci umožňující umístit na mapu malou sadu míst v číslované sekvenci, kterou mohou uživatelé procházet. Šablona je navržena k použití v libovolném webovém prohlížeči na všech zařízeních včetně chytrých telefonů a tabletů. <br /><br />",
        "div42": "Chcete-li vidět, jaké prohlídky map vytváří jiní uživatelé, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>navštivte galerii</a> na <a href='https://storymaps.arcgis.com/' target='_blank'>webové stránce map s příběhem</a>. Můžete nás také sledovat na Twitteru na <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Zajímá nás váš názor! Můžete nás informovat o problémech s aplikacemi a o nových funkcích, které byste si přáli využívat ve fóru map s příběhem na <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet.</a>"
      },
      "tab2": {
        "title": "Data",
        "div1": "Hlavním aspektem, který je třeba při vytváření prohlídky mapy zvážit, je výběr úložiště obrázků. Prohlídky map mohou využívat obrázky uložené prostřednictvím služeb pro sdílení fotografií nebo obrázky nacházející se na libovolném webovém serveru nebo na disku.",
        "div1a": "Podrobné informace o podporovaných formátech obrázků a videa naleznete v poslední části této karty.",
        "div2": "Interaktivní nástroj pro tvorbu vám dává dvě možnosti, jak v prohlídce mapy zpracovávat obrázky:",
        "div3": "<ul><li>Můžete použít <b>fotografie, které již jsou online</b>, například snímky uložené ve službě pro sdílení fotografií jako Flickr, nebo snímky uložené na vašem vlastním webu. Tyto snímky budou vloženy do vaší mapové prohlídky jako odkazy, prostřednictvím jejich adres URL.</li><li>Přímo do prohlídky mapy můžete také <b>nahrávat fotografie z vašeho počítače</b>. Tato možnost nahrávání vyžaduje předplatné ArcGIS a oprávnění vydavatele nebo administrátora, protože automaticky vytvoří hostovanou feature službu, ve které se fotografie uloží jako přílohy.</li></ul>",
        "div4": "Využití se najde hlavně v těchto případech:",
        "div4b": "<b>Fotografie ještě nemáte hostované</b> a máte předplatné ArcGIS: Využití služby hostování je pro vás nejlepší možnost. Stejně jako veřejné služby pro sdílení fotografií vaše obrázky optimalizujeme, aby se rychle načítaly. Budete mít přístup ke všem možnostem administrace a správy dat platformy ArcGIS.",
        "div5": "<b>Nejste členem organizace</b>: Nejprve bude nutné nahrát obrázky na web pro sdílení fotografií nebo na vlastní webový server. Nástroj pro tvorbu vám pak pomůže použít tyto obrázky, které budou dál uloženy v původním umístění.",
        "div6": "<b>Chcete znovu využít stávající Feature Service</b>, ve které jsou obrázky uloženy jako přílohy nebo která odkazuje na externě uložené obrázky. Podrobný návod najdete v příslušné části níže.",
        "div7": "<b>Využíváte předchozí verzi</b> šablony prohlídky mapy a již máte soubor CSV, který odkazuje na příslušné obrázky a miniatury. Budete moci importovat a doplnit data. Nástroj pro tvorbu podporuje pouze soubory CSV, které využívají pole zeměpisné šířky a délky. Soubory CSV využívající adresy je mohou nadále používat prostřednictvím webové mapy (viz příslušná část níže).",
        "div8": "Import ze služeb pro online sdílení fotografií",
        "div9a": "Podpora Facebooku byla ukončena, ${learn}.",
        "learn": "další informace",
        "div9": "Operace importu odkazuje na hostované obrázky uložením jejich URL adresy ve sbírce prvků webové mapy. Obrázky nejsou uloženy ve službě ArcGIS Online. Pokud hostované obrázky nejsou přístupné, nebudou se v prohlídce mapy zobrazovat. Místo nich se zobrazí zpráva „Obrázek není k dispozici“. V závislosti na poskytovateli služeb obrázků nemusí prohlídka mapy importovat název, popis a umístění obrázků. Tyto atributy jsou uloženy ve webové mapě a případné úpravy online služeb se v prohlídce mapy nijak neprojeví.",
        "div10": "Obrázky uložené na webovém serveru",
        "div11": "Pokud se rozhodnete hostovat svoje obrázky sami, budete muset manuálně vytvořit náhledy obrázků. Použití obrázků s plným rozlišením pro náhledy přináší špatné výsledky. Pro tipy týkající se velikosti vašich obrázků, pokud k nim budete přistupovat na webu přímo prostřednictvím adresy URL – viz <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>často kladené dotazy</a>.",
        "div12": "Použití stávajících dat GIS",
        "div13": "Jakákoli služba, soubor CSV nebo soubor obsahující body může posloužit jako zdroj dat pro prohlídku mapy, pokud tento zdroj obsahuje soubor polí požadovaný aplikací. Je nutné ho přidat jako vrstvu do webové mapy platformy ArcGIS a poté sdílet mapu vytvořením prohlídky mapy.",
        "div14": "Podporované hodnoty pro název pole jsou (malá a velká písmena se nerozlišují):",
        "div151": "Název",
        "div152": "Popis",
        "div153": "Obrázek",
        "div154": "Miniatura",
        "div155": "Barva ",
        "div16": "Pokud aplikace při použití služby Feature Service nenajde odpovídající pole, nebude prohlížeč fungovat, dokud pole pro použití  nenakonfigurujete nástrojem pro tvorbu. Vrstvy CSV a shapefile přidané do webové mapy musí obsahovat všechna požadovaná pole, jinak nebude nástroj pro tvorbu fungovat.",
        "div162": "Při používání feature service, která obrázky ukládá jako přílohy, <b>budou použity pouze prvky se dvěma přílohami</b>. První příloha určuje hlavní obrázek, druhá příloha určuje miniaturu.",
        "div17": "Pole obrázku a miniatury jsou povinná pro feature service bez příloh. Pro feature service s přílohami jsou volitelné (ale důrazně je doporučujeme). Pokud máte ve službě povolené přílohy, nástroj pro tvorbu vám umožní nahrávat obrázky jako přílohy. V opačném případě budete moci pouze editovat adresu URL obrázku a miniatury.",
        "div172": "Pokud jsou pole obrázku a miniatury přítomny, budou vždy použity a přílohy feature service nebudou dotazovány.",
        "div173": "Vzorové soubory CSV a shapefile můžete stáhnout z",
        "div18": "Vytváření hostovaných Feature Service ze souboru CSV nebo shapefile",
        "div19": "Při vytváření hostovaných služeb Feature Service ze souboru CSV nebo shapefile nejsou přílohy ve výchozím nastavení povoleny. Chcete-li je povolit, otevřete stránku podrobností služby Feature Service a klikněte na malou šipku v sekci vrstev. Daná možnost se zobrazí. Prohlídka map bude nadále používat obrázky a miniatury, na které odkazujete prostřednictvím atributů. Pokud chcete obrázky nahrát jako přílohy služby Feature Service, bude to možno provést volitelně dvěma tlačítky na panelu obrázků (Změnit obrázek a Změnit miniaturu).",
        "div20": "Podporované formáty obrázků a videí",
        "div21": "Podporované formáty obrázků: <b>jpg, jpeg, png, gif a bmp</b>. Pokud multimediální soubor nekončí touto příponou, bude jej prohlídka mapy považovat za video (mimo případy, kdy je používána služba Feature Service, viz níže).",
        "div22": "Šablona prohlídky mapy neobsahuje přehrávač videí, je nutné použít externí přehrávač videí poskytovaný některou službou pro hosting videí (najděte možnost vložení videa a zkopírujte adresu URL obsaženou v daném kódu). Chcete-li videa hostovat sami, můžete vytvořit html stránku, která obsahuje přehrávač videí jako např. <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Interaktivní nástroj pro tvorbu neobsahuje dialogové rozhraní pro přidání videa při používání feature service s přílohami, ale je možné tak učinit úpravou vašich dat mimo nástroj pro tvorbu. Pokud ve webovém prohlížeči na stránkách arcgis.com upravíte pole obrázků tak, aby odkazovala na externí video, a přidáte na konec adresy URL speciální parametr (#isVideo), budou vaše média považována za video.",
        "div24": "Mějte na paměti, že je stále nutné mít dvě platné přílohy s obrázky, jinak bod nebude použit. U příloh služby Feature Service bez polí pro obrázek a miniaturu nelze používat videa."
      },
      "tab3": {
        "title": "Přizpůsobení",
        "div1": "Nástroj pro tvorbu nabízí několik možností přizpůsobení, které jsou dostupné po kliknutí na tlačítko NASTAVENÍ v horním panelu. Pokud nenajdete možnost, kterou očekáváte, nabízíme také verzi ke stažení, kterou můžete implementovat na svůj webový server a upravit podle svých potřeb.",
        "div2": "Hostovanou verzi doporučujeme s výjimkou následujících případů:",
        "div3": "<li>Nenabízí požadované přizpůsobení uživatelského rozhraní, jako je například obrázek pozadí záhlaví.</li><li>Jste vývojář a chcete si aplikaci upravit.</li>",
        "div4": "Verzi ke stažení lze nakonfigurovat prostřednictvím webové mapy nebo identifikátoru aplikace webového mapování. Hlavní způsoby použití jsou:",
        "div41": "Svou prohlídku mapy tvoříte pomocí interaktivního nástroje pro tvorbu v hostovaném prostředí a šablonu konfigurujete pomocí identifikátoru aplikace webového mapování. Budou použita nastavení určena interaktivním nástrojem pro tvorbu.",
        "div42": "Svou prohlídku mapy tvoříte mimo interaktivní nástroj pro tvorbu a šablonu konfigurujete pomocí identifikátoru webových map. V dokumentaci se dozvíte, jak šablonu konfigurovat.",
        "div43": "Mějte na paměti, že interaktivní nástroj pro tvorbu je dostupný ve stažitelné verzi. Obsahuje však některá technická omezení ohledně prohlížečů, jako je například Internet Explorer ve verzi starší než 10.",
        "div5": "Chcete-li stáhnout nejnovější verzi šablony a získat informace o tom, jak ji použít, navštivte <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>projektovou stránku GitHub</a>."
      },
      "tab4": {
        "title": "Tipy",
        "div0": "Podporované prohlížeče",
        "div0a": "Zobrazování prohlídek map je podporováno v IE8+. Interaktivní nástroj pro tvorbu je podporován v IE9+. Produkty aktivně testujeme ve všech hlavních prohlížečích, nicméně v případě potíží doporučujeme používat Chrome.",
        "div0b": "Narazíte-li na jakékoli potíže, dejte nám vědět. Prozatím bude při vytváření prohlídky mapy pomocí CSV šablony minimalizována vaše interakce s rozhraním nástroje pro tvorbu.",
        "div1": "Snímky",
        "div2": "Přestože ve stejné prohlídce mapy lze použít obrázky s různou velikostí, tvarem a orientací, doporučujeme orientaci na šířku, nikoli na výšku. Obrázky s poměrem stran 4 : 3 vypadají nejlépe. Použití obrázků s orientací na výšku v trojpanelu nebo integrovaném uspořádání, kdy popisek přesahuje do obrázku, může vést k zakrytí obrázku popiskem. V trojpanelu a integrovaném uspořádání doporučujeme použít pokud možno stejnou velikost a tvar pro všechny obrázky. Během prohlídky tak nebude uživatele rozptylovat různá velikost obrázků.",
        "div2a": "Jako maximální velikost obrázku doporučujeme 1000 pixelů na šířku × 750 pixelů na výšku pro hlavní obrázky a 140×93 pixelů pro miniatury.",
        "div3": "Formátování textu popisku značkami HTML",
        "div4": "Do svých popisků můžete vkládat HTML značky pro definice formátování a odkazů. Následující značky například přidávají zelený odkaz:",
        "div4a": "Napište pro svou prohlídku vhodný podnadpis",
        "div4b": "Dejte si práci s vymyšlením přitažlivého podtitulku pro svoji prohlídku. Podtitulek je dobrým způsobem, jak upoutat pozornost lidí k Vaší prohlídce a říct jim, co od ní mohou čekat. V podtitulku můžete také sdělit svému publiku, v které zemi se prohlídka nachází. Například nepředpokládejte, že lidé budou vědět, kde leží město, ve kterém se nachází vaše prohlídka. Na druhou stranu by podtitulek neměl být příliš dlouhý. Pokud vás nenapadá dobrý podtitulek, nechte pole prázdné. Podtitulek, který se objevuje na úvodní straně v uspořádání postranního panelu, je popiskem prvního bodu Vaší prohlídky (pokud jste v dialogu Uspořádání nastavili možnost použití obsahu prvního bodu jako úvodní strany).",
        "div5": "Podpůrné vrstvy",
        "div6": "Do mapy můžete přidat další podpůrné vrstvy, abyste zasadili prohlídku mapy do kontextu. Tyto vrstvy mohou obsahovat jiné geografické prvky, které chcete zobrazovat v mapě mimo body prohlídky. Sem patří například studijní oblast, pěší nebo jízdní trasa spojující vaše body prohlídky atd. Šablona prohlídky mapy zobrazuje tyto další podpůrné vrstvy pomocí symbolů, které si zvolíte ve webové mapě. Vyskakovací okna ovšem nejsou k dispozici. Pokud chcete přidat podpůrné vrstvy do prohlídky, uložte svoji práci a zavřete nástroj pro tvorbu prohlídky mapy. Poté otevřete webovou mapu použitou ve Vaší prohlídce. Tu najdete v sekci Můj obsah na platformě ArcGis nebo pomocí sekce Moje příběhy na webové stránce map s příběhem.",
        "div7": "Prohlídka by měla být krátká a poutavá",
        "div8": "Prohlídka může obsahovat nejvýše 99 bodů. Většina prohlídek bude ale samozřejmě výrazně kratší. Předpokládejte, že publikum nemá zájem procházet příliš mnoho bodů. Vám možná téma připadá fascinující, ale to nemusí automaticky platit pro všechny.",
        "div10": "Režim vkládání",
        "div11": "Chcete-li vložit šablonu do jiné webové stránky pomocí iframe, přidáním volitelného parametru \"&embed\" na konec adresy URL odstraníte záhlaví.",
        "div12": "Vyhněte se použití iFrame úzké šířky, který pro maximální zjednodušení používání přepne prohlídku mapy do rozvržení pro malé dotykové displeje. Pro maximální pohodlí uživatele vždy doporučujeme při vkládání prohlídky mapy navíc poskytnout odkaz, aby uživatelé prohlídku mohli spustit na celé obrazovce."
      },
      "tab5": {
        "title": "Publikování",
        "div1": "Až budete hotovi, nezapomeňte prohlídku mapy sdílet se svým publikem pomocí tlačítka SDÍLET nebo na stránce položek aplikace v ArcGIS Online.",
        "div2a": "Sdílení prohlídky v nástroji pro tvorbu",
        "div2b": "Tlačítko SDÍLET aktualizuje položky aplikace a webové mapy. Pokud jsou vaše data prohlídky uložena v položce služby Feature Service, bude také aktualizována. Pokud jste přidali další vrstvy v prohlížeči map ArcGIS.com, nebudou aktualizovány. To může mít za následek, že prohlídka nebude sdílena podle očekávání. Položky, které již mají vyžadovaná (nebo vyšší) oprávnění, nebudou aktualizovány.",
        "div2c": "Sdílení prohlídky přes ArcGIS Online",
        "div2d": "Sdílíte-li aplikaci přes ArcGIS Online, budete v případě potřeby požádáni, abyste aktualizovali související zdroje (webovou mapu, službu Feature Service, dekorační vrstvu), které nejsou sdíleny stejným způsobem. Pokud je prohlídka mapy veřejná a jeden z vašich zdrojů není sdílen s uživateli, uživatelé budou přesměrováni na přihlašovací stránku ArcGIS Online.",
        "div3t": "Bezpečnost Feature Service",
        "div3a": "Pokud používáte hostovanou feature service vytvořenou nástrojem pro tvorbu prohlídek map, bude za vás aplikace spravovat zabezpečení služby. Zůstanete jediným uživatelem s oprávněním k editaci, i kdy budete službu sdílet veřejně.",
        "div3t2": "Před sdílením prohlídky s vaším publikem",
        "div3": "Ujistěte se, že prohlídka funguje správně, i když nejste přihlášeni do svého účtu ArcGIS.com. Adresa URL, kterou použijete, by vás neměla přesměrovat na přihlašovací stránku nebo do režimu nástroje pro tvorbu.",
        "div4": "Je dobré vyzkoušet, jak vaše prohlídka mapy vypadá na iPadu při orientaci na šířku, abyste měli jistotu, že se na tomto oblíbeném zařízení zobrazuje správně. Můžete tak zkontrolovat, zda popisky nepřekrývají příliš velkou část obrázků. Také uvidíte, zda je podnadpis vyhovující a zobrazuje se celý.",
        "div5a": "Doporučení pro vyhledávání",
        "div5b": "Abyste lidem pomohli najít vaši prohlídku mapy při vyhledávání v ArcGIS Online, doporučujeme přidat klíčové slovo 'mapa s příběhem', na stránce položek aplikace vaší prohlídky mapy (nikoli na stránce položek vaší webové mapy), spolu s dalšími klíčovými slovy, jako např. název státu nebo provincie, kde je prohlídka umístěna, název země, pokud se nachází mimo USA, a tematická klíčová slova jako např. 'veřejné umění', 'turistický průvodce' nebo 'historická místa'. Tato klíčová slova také pomohou nám ve společnosti Esri najít zajímavé nové příklady prohlídek, které můžeme ukázat v našich galeriích a propagovat přes sociální média. Také doporučujeme, abyste na svou stránku položek aplikace nahráli hezkou grafickou miniaturu, např. malý snímek obrazovky z prohlídky nebo jeden z obrázků, které se v ní nacházejí. Tento obrázek se automaticky použije, pokud bude vaše mapa přidána do galerie ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Prohlídka uložena",
      "manageStory": "Spravujte svůj příběh",
      "manageStoryA1": "Tip: Sekci %LINK1% můžete použít k vyhledání chyb ve vašem příběhu a změně způsobu sdílení jeho součástí. Sekce Moje příběhy také pomáhá vylepšit vzhled příběhu při sdílení na sociálních sítích. Více informací o dalších užitečných funkcích sekce Moje příběhy naleznete v těchto %LINK2%.",
      "manageStoryA1V1": "Moje příběhy",
      "manageStoryA1V2": "příspěvcích na blogu",
      "shareTitle": "Sdílet vaši prohlídku",
      "sharePrivateHeader": "Vaše prohlídka není sdílená, chcete ji sdílet?",
      "sharePrivateBtn1": "Sdílet veřejně",
      "sharePrivateBtn2": "Sdílet s mou organizací",
      "sharePrivateProgress": "Probíhá sdílení…",
      "sharePrivateErr": "Sdílení se nezdařillo, zkuste to znovu nebo",
      "sharePrivateOk": "Sdílení aktualizováno, načítání…",
      "sharePreviewAsUser": "Náhled",
      "shareHeader1": "Vaše prohlídka je <strong>veřejně přístupná</strong>.",
      "shareHeader2": "Vaše prohlídka je přístupná členům vaší organizace (je vyžadováno přihlášení).",
      "shareLinkHeader": "Sdílet vaši prohlídku",
      "shareLinkOpen": "OTEVŘENO",
      "shareA1": "Použijte %SHAREIMG% na <a href='%LINK1%' target='_blank'>stránce položky aplikace</a>. Pokud také chcete zrušit sdílení webové mapy, použijte <a href='%LINK2%' target='_blank'>stránku položky webové mapy</a>.",
      "shareWarning": "Sdílení %WITH% bylo zakázáno, protože nejste vlastníkem <a href='%LINK%' target='_blank'>webové mapy</a>.",
      "shareWarningWith1": "veřejně",
      "shareWarningWith2": "veřejně a s organizací"
    },
    "locator": {
      "error": "Umístění není k dispozici"
    },
    "saveErrorSocial": {
      "title": "Aktualizace sdílení na sociálních sítích",
      "panel1": "Vzhled vašeho příběhu na sociálních sítích byl aktualizován, název položky webové aplikace ArcGIS se však neshoduje s názvem vašeho příběhu.",
      "panel1tooltip": "Pokud definujete název, shrnutí a náhledový obrázek, váš příběh bude vypadat následovně:",
      "panel2": "Název, který chcete použít na sociálních sítích:",
      "panel2q1": "Název příběhu (doporučeno)",
      "panel2q1tooltip": "Pokud zvolíte tuto možnost, název položky se změní tak, aby se shodoval s názvem příběhu, a následující změny provedené v nástroji pro tvorbu se synchronizují.",
      "panel2q2": "Název položky",
      "panel3": "Chcete-li dále vylepšit vzhled příběhu na sociálních sítích, přejděte na ${MYSTORIES} a přidejte shrnutí a náhledový obrázek.",
      "panel4": "Příště již neupozorňovat u tohoto příběhu",
      "mystories": "Moje příběhy",
      "btnSave": "Uložit"
    },
    "bannerNotification": {
      "learnMore": "Více informací",
      "close": "Zavřít",
      "dontShowAgain": "Toto hlášení příště nezobrazovat"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Důležité upozornění týkající se webové bezpečnosti a map s příběhem",
      "s1h1": "Společnost Esri zvyšuje zabezpečení map s příběhem",
      "s1p1": "Vaše mapy s příběhem živě na webu a webová komunita neustále pracují na tom, jak zajistit a implementovat lepší zabezpečení. Protokol HTTPS, který poskytuje bezpečné připojení k obsahu šířenému po internetu, se profiluje jako běžný způsob přístupu k webovému obsahu. Většina moderních prohlížečů dnes zobrazuje varování, když internetová adresa používá protokol HTTP místo HTTPS. Kvůli tomuto vznikajícímu standardu bude nutné, počínaje updatem ArcGIS Online v červnu 2018, aby vaše mapy s příběhem používaly protokol HTTPS.",
      "s1p2": "V praxi to znamená, že přístup k mapě s příběhem a veškerému jejímu obsahu (včetně obrázků, vrstev, připojených aplikací a webových stránek) musí probíhat prostřednictvím odkazů, které začínají řetězcem HTTPS místo HTTP. Zajistíte tak svým čtenářům ten nejlepší možný zážitek, jelikož většina webových prohlížečů bude hlásit, že vaše příběhy používají zabezpečené připojení.",
      "s2h1": "Co mám udělat?",
      "s2p1": "Společnost Esri pracuje na tom, aby pro autory map s příběhem a čtenáře tento přechod proběhl hladce. V nástrojích pro tvorbu map s příběhem a aplikaci Moje příběhy jsou nyní k dispozici pomůcky, které vám umožní najít nezabezpečený obsah (HTTP) ve vašich příbězích a které vám poradí, jak postupovat dál. Zkontrolujte prosím zabezpečení svých příběhů a přejděte na protokol HTTPS do června 2018.",
      "action1": "Zavřít",
      "action2": "Chci si prohlédnout svoje příběhy",
      "action3": "Více informací"
    }
  }
});