define({
  "viewer": {
    "loading": {
      "step1": "UČITAVANJE PRIČE",
      "step2": "UČITAVANJE PODATAKA",
      "step3": "POKRETANJE TURE",
      "loadBuilder": "MENJANJE NA REŽIM ZA IZRADU",
      "redirectSignIn": "PREUSMERAVANJE NA STRANICU ZA PRIJAVLJIVANJE",
      "redirectSignIn2": "(nakon što se prijavite bićete preusmereni ovde)",
      "fail": "Žao nam je, učitavanje ture mape nije uspelo",
      "failButton": "Pokušajte ponovo"
    },
    "errors": {
      "boxTitle": "Došlo je do greške",
      "portalSelf": "Kritična greška: dobijanje konfiguracije portala nije uspelo",
      "invalidConfig": "Kritična greška: nevažeća konfiguracija",
      "invalidConfigOwner": "Kritična greška: nevažeća konfiguracija (zahteva se ovlašćeni vlasnik)",
      "invalidConfigNoWebmap": "Kritična greška: nevažeća konfiguracija (identifikator veb mape ili aplikacije nije određen u index.html)",
      "invalidConfigNoAppDev": "Identifikator web mapping aplikacije ili veb mapa nisu određeni u parametrima URL adrese (?appid= ili ?webmap=). U razvojnom režimu ID aplikacije ili konfiguracija veb mape na stranici index.html su zanemareni.",
      "createMap": "Kreiranje mape nije moguće",
      "invalidApp": "Neotkloniva greška: učitavanje priče nije moguće",
      "noLayer": "Veb mapa ne sadrži validan sloj sa podacima u turi mape.",
      "noLayerMobile": "Alatka za izradu ture mape nije podržana na ovoj veličini ekrana. Ako je moguće, promenite veličinu pregledača da pristupite alatki za izradu ili izradite priču na uređaju sa većim ekranom.",
      "noLayerMobile2": "Rotirajte uređaj u položeni položaj da koristite alatku za izradu ture mape.",
      "noLayerView": "Dobrodošli u veb aplikaciju ture mape.<br />Priča još nije konfigurisana.",
      "appSave": "Greška pri čuvanju priče",
      "mapSave": "Greška pri čuvanju veb mape",
      "featureServiceLoad": "Greška pri učitavanju servisa geoobjekata",
      "notAuthorized": "Nemate ovlašćenje da pristupite ovoj priči",
      "notAuthorizedBuilder": "Nemate ovlašćenje da koristite alatku za izradu ture mape.",
      "oldBrowserTitle": "Pregledač nije u potpunosti podržan",
      "noBuilderIE8": "Alatka za izradu ture mape nije podržana na pregledaču Internet Explorer pre verzije 9.",
      "ie10Win7Explain": "Interaktivna alatka za izradu ture mape nije podržana na Internet Explorer 10 verziji na Windows 7 operativnom sistemu kada je izvor podataka servis geoobjekata sa prilozima. Da biste koristili servis geoobjekata sa prilozima, morate da <a target=’_blank’ href=’http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx’>ručno promenite režim dokumenta na standarde verzije Internet Explorer 9</a>, <a target=’_blank’ href=’http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml’>vratite se na prethodnu verziju programa Internet Explorer 9</a> ili ažurirate operativni sistem na verziju Windows 8.",
      "oldBrowserExplain": "Ovaj pregledač ne podržava automatsko generisanje sličice iz snimaka koje otpremite na turu mape. Možete da kreirate mapu koristeći pregledač, ali moraćete da obezbedite odvojenu sličicu za svaki snimak koji otpremite.",
      "oldBrowserExplain2": "Da biste poboljšali iskustvo, <a href=’http://browsehappy.com/’ target=’_blank’>ažurirajte pregledač</a> ili <a href=’http://www.google.com/chromeframe/?redirect=true’ target=’_blank’>aktivirajte Google Chrome Frame za Internet Explorer</a>.",
      "oldBrowserExplain3": "Alatka za izradu ture mape ne radi sa programom Internet Explorer 10 na Windows XP operativnom sistemu",
      "oldBrowserClose": "Zatvori"
    },
    "mobileHTML": {
      "showIntro": "PRIKAŽI NASLOV",
      "hideIntro": "SAKRIJ NASLOV",
      "navList": "Lista",
      "navMap": "Mapa",
      "navInfo": "Mediji",
      "introStartBtn": "Pokretanje"
    },
    "desktopHTML": {
      "storymapsText": "Story mapa",
      "builderButton": "Promeni na režim alatke za izradu",
      "facebookTooltip": "Podelite na mreži Facebook",
      "twitterTooltip": "Podelite na mreži Twitter",
      "bitlyTooltip": "Nabavi kratki link",
      "bitlyStartIndex": "Link do trenutnog mesta",
      "tooltipAutoplayDisabled": "Ovo nije dostupno u režimu automatske reprodukcije",
      "autoplayLabel": "Režim automatske reprodukcije",
      "autoplayExplain1": "Režim automatske reprodukcije će ići kroz priču uobičajenim intervalom. Ovo je idealno na terminalima ili javim ekranima, ali imajte u vidu da u drugim situacijama čitanje priče može da bude otežano. Ova funkcija nije podržana na ekranima malih dimenzija.",
      "autoplayExplain2": "Kada je ovaj režim aktiviran, postoje kontrole da se priča reprodukuje/pauzira i da se prilagodi brzina navigacije."
    },
    "builderHTML": {
      "panelHeader": "KONFIGURACIJA PRIČE",
      "buttonSave": "SAČUVAJ",
      "buttonSettings": "Postavke",
      "buttonShare": "Podeli",
      "buttonView": "Režim prikaza",
      "buttonItem": "Otvori stavku veb aplikacije",
      "buttonHelp": "Pomoć",
      "buttonOrganize": "Organizujte",
      "buttonAdd": "Dodaj",
      "buttonImport": "Uvezi",
      "buttonImportDisabled": "Uvoz nije dostupan kada se koristi servis geoobjekata sa prilozima",
      "dataEditionDisabled": "Uređivanje podataka je onemogućeno na ovom CSV izvoru podataka",
      "dataSourceWarning": "Sloj podataka ture mape je promenjen. Ako ID vrednosti geoobjekata nisu iste, morate da poništite raspored i skrivene tačke preko <b>Organizuj</b>. Ako se nazivi polja razlikuju, morate da poništite postavke polja pod <b>karticom podataka u postavkama</b>.",
      "organizeWarning": "Jedna ili više tačaka dodatih izvan interaktivne alatke za izradu su skrivene.",
      "dataPicError0a": "Ova tura uključuje <b>%NB%</b> neusaglašeni URL slike.",
      "dataPicError0b": "Ova tura može da uključuje <b>%NB%</b> neusaglašeni URL slike.",
      "dataPicError1": "Tura mape sada zahteva da se URL slike završava jednom od sledećih oznaka tipa datoteke: jp(e)g, .png, .gif ili .bmp.",
      "dataPicError2": "Ovaj zahtev neće uticati na postojeće objavljene ture mape. Međutim, da biste koristili interaktivnu alatku za izradu, morate prvo da rešite spornu stavku sa URL adresom i to tako što ćete uraditi jednu od ove dve radnje:",
      "dataPicError3": "Uredite URL adrese",
      "dataPicError4": "Ovo će dodati <i>#isImage</i> na kraj nepodržane URL adrese slike. Većina servera podržava URL dodatke. Međutim, kada jednom izvršite tu radnju, treba da proverite da li su ažurirane URL adrese slika funkcionalne navigacijom kroz tačke. Ako se svaka slika učita, možete da sačuvate turu mape. Ako su <b>slike oštećene, nemojte da čuvate turu mape</b>. Umesto toga, ponovo učitajte alatku za izradu i izvršite drugu radnju.",
      "dataPicError5": "Ograničite turu na slike",
      "dataPicError6": "Pomoću ove opcije sve URL adrese će biti prepoznate kao slike, ali neće moći da dodate video zapise putem interaktivne alatke za izradu. Ovu radnju možete da opozovete ako u budućnosti odlučite da dodate video zapis.",
      "dataPicError7": "Vaša tura mape će biti ograničena na slike, a video zapisi ne mogu da budu korišćeni. Ako odlučite da uklonite to ograničenje, proverite da li se slike i dalje učitavaju pravilno pre nego što sačuvate turu mape. Ako vam kasnije zatreba, to ograničenje možete da vratite.",
      "dataPicError8": "Ukloni ograničenje na slike",
      "dataPicError9": "Ako ove URL adrese vode ka video zapisu, možete da zanemarite ovo upozorenje; ako vode do slike, morate da izvršite jednu od dve navedene radnje:",
      "modalCancel": "Otkaži",
      "modalApply": "Primeni",
      "organizeHeader": "Organizuj turu",
      "organizeGeneralCaption": "Koristite opciju „prevuci i otpusti“ da složite tačke ture",
      "organizeDelete": "Obriši",
      "organizeHide": "Sakrij",
      "organizeReset": "Poništite raspored i skrivene tačke",
      "addMaxPointReached": "Dostigli ste maksimalan broj tačaka dozvoljenih postavljenim ikonama i dodavanje još jedne tačke ture nije moguće.<br /><br />Imajte u vidu da ćete morati da ponovo učitate priču ako obrišete postojeće tačke.",
      "addMaxPointReachedMobile": "Žao nam je, dostignut je maksimalan broj dozvoljenih tačaka i slika ne može da bude dodata.",
      "addClose": "Zatvori",
      "addHeader": "Dodaj novu tačku ture",
      "addTabPicture": "Mediji",
      "addTabInformation": "Informacije",
      "addTabLocation": "Lokacija",
      "addSelectCaption": "Izaberite ili otpustite sliku",
      "addNoteVideo": "Konsultujte „Pomoć“ za instrukcije o korišćenju video zapisa",
      "addSelectCaptionNoFileReader": "Izaberi sliku",
      "addChangePhoto": "Promeni sliku i sličicu",
      "addPictureResolutionIntro": "Rezolucija slike je veća nego što je zahtevano:",
      "addPictureResolutionOldBrowser": "Rezolucija slike je veća nego što je zahtevano. Optimizujte iskustvo ture mape zadavanjem rezolucije niže od %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Promeni rezoluciju slike na %RESOLUTION%",
      "addPictureResolutionKeep": "Zadrži originalnu rezoluciju od %RESOLUTION%",
      "addSelectThumbnail": "Izaberi sličicu",
      "addNoThumbSelected": "Nema izabrane sličice",
      "addThumbSelected": "Izabrano",
      "addCameraSettingsHeader": "POSTAVKE KAMERE",
      "addThumbnailHeader": "SLIČICA",
      "addLabelPicUrl": "Slika",
      "addLabelThumbUrl": "Sličica",
      "addTextPlaceholderUrl": "Unesite URL adresu snimka",
      "addTextPlaceholderUrl2": "Unesite URL adresu YouTube stranice",
      "addTextPlaceholderUrl3": "Unesite URL adresu Vimeo stranice",
      "addTextPlaceholderUrl4": "Unesite ugrađenu URL adresu video zapisa",
      "addLabelVideo": "Video zapis",
      "addMediaVideoOther": "Ostalo",
      "addMediaVideoHelp": "Proverite URL adresu i pribavite podrazumevanu sličicu",
      "addMediaVideoHelpTooltip1": "Provera je uspela",
      "addMediaVideoHelpTooltip2": "Provera nije uspela",
      "addMediaVideoHelpTooltip4": "Pronađite opciju da ugradite video zapis i kopirate URL adresu video zapisa koja je prisutna u kôdu",
      "addLabelName": "Naziv",
      "addLabelDescription": "Natpis",
      "addTextPlaceholder": "Ukucajte nešto",
      "addLocatePlaceholder": "Locirajte adresu ili mesto",
      "addPinColor": "Boja",
      "addLatitude": "Geografska širina",
      "addLongitude": "Geografska dužina",
      "addLatitudePlaceholder": "npr. 34.056",
      "addLongitudePlaceholder": "npr. -117.195",
      "addUploading": "Otpremanje tačke ture",
      "addSave": "Dodajte tačku ture",
      "addMobileUploading": "Otpremanje slike",
      "addMobileName": "Unesite ime",
      "addMobileNameMandatory": "Greška, unesite ime.",
      "addMobileError": "Žao nam je, došlo je do greške",
      "settingsHeader": "Postavke priče",
      "settingsTabLayout": "Raspored",
      "settingsTabColor": "Boje",
      "settingsTabLogo": "Zaglavlje",
      "settingsTabFields": "Podaci",
      "settingsTabExtent": "Obuhvat",
      "settingsTabZoom": "Nivo zumiranja",
      "settingsLayoutExplain": "Izaberite raspored koji želite.",
      "settingsLayoutProfessional": "Raspored trodelnog panela",
      "settingsLayoutModern": "Integrisani raspored",
      "settingsLayoutSelected": "Izabrani raspored",
      "settingsLayoutSelect": "Izaberi ovaj raspored",
      "settingsLayoutNote": "Imajte u vidu pri korišćenju video zapisa na tačkama da je obaveštenje uvek smešteno ispod video zapisa čak i ako je ta opcija označena kao nepotvrđena.",
      "settingsLayoutLocBtn": "Prikaži „Lociraj“ dugme",
      "settingsLayoutLocBtnHelp": "Ta funkcionalnost je podržana na većini pregledača mobilnih uređaja i desktop računara (Internet Explorer 9).",
      "settingsColorExplain": "Promenite izgled odabirom predefinisane teme ili kreirajte sopstvenu.",
      "settingsLabelColor": "Boje zaglavlja, sadržaja i podnožja stranice",
      "settingsLogoExplain": "Prilagodite logotip zaglavlja (maksimalna veličina je 250 x 50px).",
      "settingsLogoEsri": "Esri logotip",
      "settingsLogoNone": "Nema logotipa",
      "settingsLogoCustom": "Prilagođeni logotip",
      "settingsLogoCustomPlaceholder": "URL adresa snimka",
      "settingsLogoCustomTargetPlaceholder": "Link za brojač klikova",
      "settingsLogoSocialExplain": "Prilagodite link iz gornjeg desnog dela zaglavlja.",
      "settingsLogoSocialText": "Tekst",
      "settingsLogoSocialLink": "Link",
      "settingsLogoSocialDisabled": "Ova funkcija je onemogućena od strane administratora",
      "settingsDataFieldsExplain": "Izaberite ime fotografije, natpis i polja boje.",
      "settingsDataFieldsError": "Aplikacija ne može da odredi odgovarajuće ime, natpis ili podatke o boji. Izaberite polja koje će ovde biti korišćena. Ove postavke kasnije mogu da budu promenjene.",
      "settingsFieldsLabelName": "Naziv",
      "settingsFieldsLabelDescription": "Natpis",
      "settingsFieldsLabelColor": "Boja",
      "settingsFieldsReset": "Poništi izbor polja",
      "settingsExtentExplain": "Postavi početni obuhvat ture mape kroz interaktivnu mapu ispod.",
      "settingsExtentExplainBottom": "Obuhvat koji definišete će da izmeni početni obuhvat veb mape. Imajte u vidu da ukoliko koristite serije brzog prevlačenja taj obuhvat neće biti korišćen.",
      "settingsExtentDateLineError": "Obuhvat ne može da bude preko meridijana od 180Â° geografske širine",
      "settingsExtentDateLineError2": "Greška pri obračunavanju obuhvata",
      "settingsExtentDrawBtn": "Nacrtajte novi obuhvat",
      "settingsExtentModifyBtn": "Izmenite obuhvat",
      "settingsExtentApplyBtn": "Pregledaj na turi mape",
      "settingsExtentUseMainMap": "Koristite obuhvat ture mape",
      "settingsZoomExplain": "Podesite zumiranje na tačke priče koje prate uvod (opciono).",
      "settingsLabelZoom": "Razmera/nivo",
      "settingsZoomFirstValue": "Ništa",
      "settingsFieldError": "Izaberite polje u svakoj listi",
      "dataTitle": "Kreirajte hostovani sloj ture mape",
      "dataExplain": "Novi sloj geoobjekata će biti kreiran za snimke i tačke ture. Sloj ture neće biti podeljen ni sa kim osim ako ne podelite turu mape.",
      "dataExplainPortal": "Ova funkcionalnost zahteva Portal for ArcGIS 10.4. Ako ne uspete da kreirate sloj geoobjekata, kontaktirajte ArcGIS administratora.",
      "dataNameLbl": "Ime sloja",
      "dataFolderListLbl": "Fascikla",
      "dataFolderListFetching": "Dobavljanje fascikli...",
      "dataRootFolder": "Koren",
      "dataNameError": "Unesite ime servisa geoobjekata",
      "dataFolderError": "Izaberite validnu fasciklu",
      "dataSrcContainsInvalidChar": "Ime servisa geoobjekata sadrži jedan ili više nevažećih karaktera (-, <, >, #, %, :, \", ?, &, +, /, ili ).",
      "dataSrvAlreadyExistsError": "Servis sa tim imenom već postoji u organizaciji. Izaberite drugo ime.",
      "dataBtnSave": "Kreiraj sloj",
      "dataFooterProgress": "Kreiranje u toku",
      "dataFooterSucceed": "Kreiranje je uspelo. Učitavanje",
      "dataFooterError": "Kreiranje nije uspelo. Pokušajte ponovo",
      "tabError": "Proverite u svim karticama da li ima grešaka",
      "introRecordBtn": "Uvod",
      "introRecordActivate": "Koristite prvu tačku kao uvod (ne pojavljuje se u vrteški)"
    },
    "addPopupJS": {
      "uploadingPicture": "Otpremanje slike",
      "uploadSuccess": "Otpremanje je uspešno",
      "uploadError": "Došlo je do greške pri otpremanju slike",
      "uploadError2": "Došlo je do greške pri dodavanju geoobjekta (nevažeća html oznaka)",
      "notJpg": "Odaberite jpeg fotografiju za otpremanje",
      "errorNoPhoto": "Odaberite snimak za otpremanje",
      "errorNoThumbnail": "Odaberite sličicu za otpremanje",
      "errorInvalidPicUrl": "Unesite validnu sliku (počinje sa http(s)://, završava se sa jpg, png, gif ili bmp). Možete da završite URL adresu sa ‘#isImage’ da izmenite to pravilo.",
      "errorInvalidThumbUrl": "Unesite validnu sličicu (počinje sa http(s)://, završava se sa jpg, png, gif ili bmp).",
      "errorInvalidVideoUrl": "Unesite validnu URL adresu video zapisa (počinje sa http(s)://)",
      "errorNoName": "Unesite ime za ovu tačku ture",
      "errorNoDescription": "Unesite natpis za ovu tačku ture",
      "errorNoLocation": "Podesite lokaciju za ovu tačku ture"
    },
    "builderJS": {
      "noPendingChange": "Nema nesačuvanih izmena",
      "unSavedChangeSingular": "1 nesačuvana izmena",
      "unSavedChangePlural": "nesačuvane izmene",
      "shareStatus1": "Tura nije sačuvana",
      "shareStatus2": "Tura je javno podeljena",
      "shareStatus3": "Tura je podeljena sa organizacijom",
      "shareStatus4": "Tura nije podeljena",
      "popoverDiscard": "Želite li da odbacite sve nesačuvane promene?",
      "yes": "Da",
      "no": "Ne",
      "popoverLoseSave": "Otvaranjem preglednika izgubićete sve nesačuvane izmene",
      "ok": "U redu",
      "popoverSaveWhenDone": "Ne zaboravite da sačuvate kada završite",
      "closeWithPendingChange": "Želite li da potvrdite ovu radnju? Promene će biti izgubljene.",
      "gotIt": "U redu",
      "savingApplication": "Čuvanje priče",
      "saveSuccess": "Priča je sačuvana",
      "saveError": "Čuvanje nije uspelo, pokušajte ponovo",
      "saveError2": "Čuvanje nije uspelo zbog nevažeće html oznake u imenu ili opisu",
      "saveError3": "Naslov ne može da bude prazan",
      "dragColorPicker": "Pomeraj me okolo<br />ili izmeni boju",
      "dataWarningExtent": "Neki podaci se nalaze van obuhvata veb mape. Ti podaci neće biti korišćeni kao tačke ture; promenite obuhvat mape ako želite da ih koristite.",
      "dataWarningVisibi": "Sloj ture mape nije vidljiv na trenutnom obuhvatu mape. Proverite da li je sloj ture mape vidljiv pomoću %MAPSIZE% velike mape.",
      "dataWarningEdit": "Uredite veb mapu",
      "dataWarningClose": "Zatvori",
      "signIn": "Prijavite se na nalog da biste",
      "signInTwo": "sačuvali priču.",
      "switchBM": "Promenite pozadinsku mapu"
    },
    "organizePopupJS": {
      "messageStart": "Izabrali ste brisanje",
      "messageSinglePoint": "jedne tačke ture",
      "messageMultiPoint": "tačaka ture",
      "messagePermantRemove": "Ovim će se trajno ukloniti",
      "messageRecord": "podatak",
      "messageRecordPlural": "podaci",
      "messageConfirm": "iz baze podataka. Želite li da nastavite?",
      "labelButtonShow": "Prikaži",
      "labelButtonHide": "Sakrij"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Ovim se trajno brišu slika i sličica",
      "popoverDeleteWarningThumb": "Ovim se trajno briše sličica",
      "popoverUploadingPhoto": "Otpremanje slike i sličice",
      "popoverUploadingThumbnail": "Otpremanje sličice",
      "popoverUploadSuccessful": "Otpremanje je uspešno",
      "popoverUploadError": "Otpremanje nije uspelo, pokušajte ponovo",
      "changePicAndThumb": "Promeni sliku",
      "changeThumb": "Promeni sličicu",
      "selectPic": "Promeni medij",
      "selectThumb": "Promeni sličicu",
      "uploadPicAndThumb": "Primeni"
    },
    "headerJS": {
      "editMe": "Izmeni me!",
      "templateTitle": "Postavi naslov šablona",
      "templateSubtitle": "Postavi podnaslov šablona"
    },
    "crossFaderJS": {
      "setPicture": "Postavi naslov slike",
      "setCaption": "Postavi natpis slike"
    },
    "importPopup": {
      "title": "Uvezi",
      "prevBtn": "Nazad",
      "nextBtn": "Sledeće"
    },
    "importPopupHome": {
      "header": "Gde se skladište vaše slike?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "slike",
      "videos": "video zapisi",
      "disabled": "Ova funkcija je onemogućena od strane administratora",
      "disabledPortal": "Ova funkcija zahteva da portal ima ArcGIS Data Store konfigurisan kao bazu podataka za upravljanje. Kontaktirajte administratora portala Portal for ArcGIS.",
      "header1": "Vaše slike moraju da budu javno podeljene.",
      "header2": "Uvoz će da bude ograničen na prvih %NB1% %MEDIA%.",
      "emptyDataset": "Greška, slike nisu nađene",
      "footerImport": "Uvezi",
      "selectAlbum": "Izaberi javni album",
      "selectAlbum2": "Izaberi album",
      "pleaseChoose": "Izaberite",
      "userLookup": "Potraži",
      "userLookingup": "Pronalaženje",
      "csv": "Naveden u CSV datoteci",
      "advanced": "Napredne opcije",
      "advancedScratchLbl": "Pokreni novu turu",
      "advancedScratchTip": "Kreirajte praznu turu koju ćete moći ručno da popunite.",
      "advancedCSVLbl": "Uvezi podatke ture iz CSV datoteke",
      "advancedCSVTip": "Uvezite podatke vaše ture iz CSV datoteke.",
      "advancedCommonTip": "Neophodno je da vaši snimci i video zapisi budu na mreži.",
      "select": "Napravi izbor",
      "locUse": "Koristi geografsku lokaciju slike",
      "locExplain": "Možda ne želite da koristite lokaciju slika pošto one mogu da budu nasleđene iz albuma, što bi kao rezultat imalo da sve slike budu na istoj lokaciji.",
      "locExplain2": "Možda ne želite da koristite lokaciju video zapisa pošto oni mogu da budu nasleđeni iz postavki korisnika, što bi kao rezultat imalo da svi video zapisi budu na istoj lokaciji."
    },
    "viewFlickr": {
      "title": "Uvoz sa mreže Flickr",
      "header": "Unesite vaše Flickr korisničko ime i izaberite skup fotografija ili oznaku koje želite da uvezete.",
      "userInputLbl": "Unesite korisničko ime",
      "signInMsg2": "Korisnik nije pronađen",
      "selectSet": "Izaberite skup fotografija",
      "selectTag": "ili izaberite oznaku",
      "footerImportTag": "Uvezi izabranu oznaku",
      "footerImportSet": "Uvezi izabrani skup"
    },
    "viewFacebook": {
      "title": "Uvoz sa mreže Facebook",
      "header": "Potvrdite identitet putem vašeg Facebook korisničkog naloga ili koristite javnu stranicu. Privatni albumi mogu da budu korišćeni za kreiranje javnih tura mape koje ne zahtevaju potvrdu identiteta korisnika na mreži Facebook, što omogućava da komentari i sviđanja ostanu privatni.",
      "leftHeader": "Facebook korisnik",
      "rightHeader": "Facebook stranica",
      "pageExplain": "Facebook stranica je javni brend/proizvod ili svetski poznat <b>esrigis</b>. Možete da dobijete naziv stranice nakon prve ‘/’u URL adresi stranice.",
      "pageInputLbl": "Unesite ime stranice",
      "lookupMsgError": "Stranica nije pronađena"
    },
    "viewPicasa": {
      "title": "Uvoz sa Picasa/Google+",
      "header": "Unesite adresu e-pošte ili ID svog Picasa ili Google+ naloga.",
      "userInputLbl": "Unesite e-poštu ili ID",
      "signInMsg2": "Nalog nije pronađen",
      "signInMsg3": "Nema javnog albuma",
      "howToFind": "Kako da pronađete ID naloga za stranicu Picasa ili Google+",
      "howToFind2": "Kopirajte cifre između prvog i drugog ‘/’ na Picasa ili Google+ stranici"
    },
    "viewCSV": {
      "title": "Uvoz iz CSV",
      "uploadBtn": "Izaberite ili otpustite CSV datoteku",
      "resultHeaderEmpty": "CSV datoteka je prazna",
      "resultHeaderSuccess": "Učitano %NB_POINTS% tačaka",
      "resultHasBeenLimited": "Uvoz je ograničen na prvih %VAL1% od %VAL2% tačaka da bi se poštovalo ograničenje od %VAL3% tačaka po turi",
      "browserSupport": "Pregledač nije podržan, da biste koristili CSV morate da <a href=’http://browsehappy.com/’ target=’_blank’>ažurirate pretraživač</a> ili da koristite preglednik mape veb stranice ArcGIS.com (pogledajte „Pomoć“).",
      "errorLatLng": "Nisu pronađena polja geografske širine i dužine. Moguće vrednosti za geografsku širinu su: <i>%LAT%</i> a za geografsku dužinu: <i>%LONG%</i>.",
      "errorFieldsExplain": "Učitavanje nije uspelo jer sledeća obavezna polja nisu pronađena",
      "errorFieldsName": "<b>Ime</b> moguće vrednosti su: %VAL%",
      "errorFieldsDesc": "<b>Opis</b> moguće vrednosti su: %VAL%",
      "errorFieldsUrl": "<b>Slika</b> moguće vrednosti su: %VAL%",
      "errorFieldsThumb": "<b>Sličica</b> moguće vrednosti su: %VAL%",
      "errorFields2Explain": "Učitavanje nije uspelo jer CSV datoteka ne koristi iste atribute kao sloj za sledeće atribute",
      "errorFields2Name": "<b>Ime</b> koristi %VAL1% umesto %VAL2%",
      "errorFields2Desc": "<b>Opis</b> koristi %VAL1% umesto %VAL2%",
      "errorFields2Url": "<b>Slika</b> koristi %VAL1% umesto %VAL2%",
      "errorFields2Thumb": "<b>Sličica</b> koristi %VAL1% umesto %VAL2%",
      "resultFieldsAll": "Svi atributi su uvezeni",
      "resultFieldsNotAll": "Sledeći atributi nisu uvezeni jer ne postoje u sloju mape",
      "resultFieldsNotAll2": "Sledeći atributi su uvezeni",
      "footerNextBtnResult": "Uvezi u veb mapu",
      "footerProgress": "Uvoz u toku",
      "footerSucceed": "Uvoz je uspeo. Učitavanje"
    },
    "viewYoutube": {
      "title": "Uvoz sa stranice YouTube",
      "header": "Unesite YouTube korisničko ime da biste pronašli javno podeljene video zapise.",
      "pageInputLbl": "Unesite YouTube korisničko ime",
      "lookupMsgError": "Korisnik nije pronađen",
      "howToFind": "Kako da pronađete YouTube korisničko ime",
      "howToFind2": "Korisničko ime je prikazano ispod video zapisa",
      "found": "Pronađeno",
      "noData": "Nijedan javni video zapis nije pronađen"
    },
    "viewGeoTag": {
      "title": "Izaberite i locirajte snimke/video zapise",
      "header": "Kliknite ili dodirnite slike koje želite da uvezete da biste ih locirali.",
      "headerMore": "Zašto moji snimci/video zapisi nemaju geografsku lokaciju?",
      "headerExplain": "Ako vaše slike imaju validnu geografsku lokaciju, one će da budu automatski locirane na mapi i navedene pod drugom karticom.<br /><br />Podrazumevano, Picasa i Flickr ne skladište geografsku lokaciju EXIF metapodataka kada uvozite slike. Proverite postavke privatnosti na Picasa/Flickr stranici da omogućite uvoz geografske lokacije slika i korišćenje u spoljnim aplikacijama. Možda ćete morati ponovo da uvezete postojeće slike na Flickr/Picasa stranicu da bi geografska lokacija EXIF bila korišćena.<br /><br />Na Facebook stranici morate da idete na svaku sliku, kliknete na „Izmeni“ i izaberete lokaciju.",
      "leftPanelTab1": "Da locirate",
      "leftPanelTab2": "Locirano",
      "clickOrTap": "Kliknite ili dodirnite mapu da locirate",
      "clearLoc": "Izbriši lokacije",
      "clickDrop": "Ne vrši uvoz",
      "footerImport": "Uvezi",
      "footerProgress": "Uvoz u toku",
      "footerSucceed": "Uvoz je uspeo. Učitavanje...",
      "loading": "Učitavanje",
      "error": "Uvoz geografske lokacije slika nije uspeo, geografske lokacije su zanemarene."
    },
    "initPopup": {
      "title": "Dobrodošli u alatku za izradu ture mape",
      "prevBtn": "Nazad",
      "nextBtn": "Sledeće"
    },
    "initPopupHome": {
      "header1": "Gde su vaši snimci ili video zapisi?",
      "header2": "Pomoćnik će vam pomoći da kreirate mapu ture od medija koji su već uskladišteni na mreži ili će da ih uveze na vaš organizacioni nalog na ArcGIS Online.",
      "title1": "Već su na mreži",
      "title2": "Moram da otpremim snimke",
      "hostedFSTooltip": "Otpremite snimke i skladištite ih u sloju ture mape (video zapis nije podržan).",
      "hostedFsNA": "Morate da budete objavljivač ili da imate drugu ulogu sa privilegijom objavljivanja hostovanih slojeva geoobjekata. Kontaktirajte ArcGIS administratora.",
      "hostedFsNA2": "Dostupno samo uz ArcGIS Online pretplatu. <a href=’%LINK%’>Upišite se za besplatnu probnu verziju</a>",
      "footer1": "Kada završite, ne zaboravite da podelite turu mape sa korisnicima preko stranice stavke aplikacije.",
      "footer3": "Preuzmi CSV šablon",
      "footer4": "„Sačuvaj kao“ ako ne bude preuzeto",
      "footer4bis": "Ako preuzimanje ne otpočne, kliknite desnim klikom i odaberite opciju „Sačuvaj kao“",
      "footer5": "Saznaj više",
      "footerProgress": "Kreiranje u toku",
      "footerSucceed": "Kreiranje je uspelo. Učitavanje..."
    },
    "helpPopup": {
      "title": "Pomoć",
      "close": "Zatvori",
      "tab1": {
        "title": "Uvod",
        "div1": "Šablon ture mape je namenjen za predstavljanje geografskih informacija gde postoji živopisna fotografija ili element medija u vezi sa pričom koju želite da ispričate.",
        "div2": "Šablon pravi zanimljivu veb aplikaciju koja je jednostavna za korišćenj-e i omogućava vam da predstavite mali skup mesta na mapi u numerisanom nizu koji korisnici mogu da pregledaju. Šablon je namenjen da se koristi u bilo kom veb pregledaču na bilo kom uređaju, uključujući pametne telefone ili tablet uređaje. <br /><br />",
        "div42": "Da biste videli primere tura mape koje drugi korisnici kreiraju, <a href=’http://links.esri.com/storymaps/map_tour_gallery’ target=’_blank’>posetite galeriju</a> na <a href=’http://storymaps.arcgis.com/’ target=’_blank’>veb stranici Story mapa</a>. Takođe, možete da nas pratite putem mreže Twitter na <a href=’https://twitter.com/EsriStoryMaps’ target=’_blank’>@EsriStoryMaps</a>.",
        "div5": "Voleli bismo da vas čujemo! Bilo da imate pitanje, želite da tražite novu funkciju, ili samo mislite da ste pronašli grešku, posetite <a href=’http://links.esri.com/storymaps/forum’ target=’_blank’>korisnički forum Story mapa</a>."
      },
      "tab2": {
        "title": "Podaci",
        "div1": "Glavni element koji treba uzeti u razmatranje prilikom izrade ture mape je odabir lokacije za skladištenje slika. Tura mape može da koristi slike uskladištene na većim servisima za deljenje fotografija, na bilo kom serveru ili iz priloga servisa geoobjekata.",
        "div1a": "Pogledajte poslednji odeljak ove kartice za detalje o podržanim formatima slika i video zapisa.",
        "div2": "Interaktivna alatka za izradu pruža dve opcije za upravljanje snimcima u turi mape:",
        "div3": "<ul><li>Možete da koristite <b>fotografije koje su već na mreži</b>, kao što su snimci uskladišteni na veb stranicama za deljenje fotografija, kao što je Flickr, ili slike uskladištene na vašoj veb stranici. Ovi snimci će biti navedeni u turi mape putem URL adresa.</li><li>Takođe možete da <b>otpremite fotografije sa računara</b> direktno na turu mape. Ova opcija otpremanja zahteva da imate ArcGIS nalog za organizacije i privilegije objavljivača ili administratora, jer se hostovani servisi geoobjekata automatski kreiraju kao skladište u kome se vaše fotografije čuvaju kao prilozi.</li></ul>",
        "div4": "Glavni slučajevi upotrebe su:",
        "div4b": "<b>Vaše fotografije nisu hostovane</b> i imate organizacioni ArcGIS nalog: korišćenje hostovanog servisa geoobjekata je najbolji izbor. Kao i javni servisi za deljenje fotografija, mi ćemo optimizovati vaše slike da bismo kreirali snimke koji se brzo učitavaju i imaćete pristup svim mogućnostima upravljanja administracijom i podacima preko ArcGIS platforme.",
        "div5": "<b>Niste član organizacije</b>: Najpre morate da otpremite fotografije na veb stranicu za deljenje fotografija ili na vaš veb server. Alatka za izradu će vam pomoći da koristite ove slike koje će i dalje biti hostovane na početnoj lokaciji.",
        "div6": "<b>Želite da ponovo koristite postojeći servis geoobjekata</b> koji skladišti fotografije kao priloge ili koji se odnosi na spoljne slike: pogledajte odeljak sa više detalja ispod.",
        "div7": "<b>Korisnik ste prethodne verzije</b> šablona ture mape i već imate CSV datoteku koja je povezana sa slikama i sličicama: moći ćete da uvozite i suzite obim podataka. Alatka za izradu podržava samo CSV datoteke koje koriste polja geografske širine/dužine; CSV datoteke zasnovane na adresi mogu da se koriste putem veb mape (pogledajte odeljak ispod).",
        "div8": "Uvoz sa servisa za deljenje fotografija na mreži",
        "div9": "Operacija uvoza odnosi se samo na slike koje su već hostovane skladištenjem njihovih URL adresa u kolekciji geoobjekata na veb mapi. Slike nisu uskladištene na ArcGIS Online platformi. Ako nije moguć pristup hostovanim slikama, one neće biti dostupne na turi mape i videćete snimak „Slika nije dostupna“. U zavisnosti od dobavljača servisa fotografija, tura mape može da ne uvozi ime, opis i lokaciju slika. Ti atributi se skladište na veb mapi i bilo koje izmene na servisima na mreži neće biti prikazane na turi mape.",
        "div10": "Skladištenje slika na veb serveru",
        "div11": "Ako odaberete da samo hostujete slike, moraćete ručno da kreirate sličice slika. Korišćenje pune rezolucije slika za sličice će rezultirati lošim učinkom. Iz tog razloga, izričito preporučujemo korišćenje servisa za deljenje fotografija na mreži ili servisa geoobjekta koji će to uraditi za vas.",
        "div12": "Korišćenje postojećeg servisa geoobjekata ili „shapefile“ datoteke",
        "div13": "Bilo koji servis tačkastog geoobjekta ili „shapefile“ datoteka mogu da budu korišćeni kao izvor podataka u turi mape. Potrebno je samo da ih dodate kao sloj u veb mapu pomoću arcgis.com preglednika mape. Ako aplikacija u sloju prepozna očekivane atribute, sve funkcionalnosti alatke za izradu će biti dostupne.",
        "div14": "Moguće vrednosti za nazive polja su (ne razlikuje mala i velika slova):",
        "div151": "Naziv",
        "div152": "Opis",
        "div153": "Slika",
        "div154": "Sličica",
        "div155": "Boja ",
        "div16": "Ako aplikacija ne pronađe podudarajuća polja kada koristi servis geoobjekata, preglednik neće raditi dok ne konfigurišete polja koja će se koristiti preko alatke za izradu. Slojevi CSV i „shapefile“ datoteke dodati veb mapi moraju da imaju sva neophodna polja ili alatka za izradu neće raditi.",
        "div162": "Kada koristite servis geoobjekata koji skladišti slike kao priloge, <b>samo geoobjekti sa dva priloga će biti korišćeni</b>. Prvi prilog definiše glavnu sliku, a drugi prilog definiše sličicu.",
        "div17": "Polja slike i sličice su obavezna za servise geoobjekata bez priloga i opciona (ali izričito se preporučuju) za servise geoobjekata sa prilozima. Ako servis ima omogućene priloge, alatka za izradu će dozvoliti da otpremite slike kao priloge. Ako nema, moći ćete samo da uređujete URL adrese slike i sličice.",
        "div172": "Kada su prisutna polja slike i sličice, uvek će da budu korišćena, a upit za priloge servisa geoobjekta neće da bude izvršen.",
        "div173": "Primeri datoteka CSV i „shapefile“ mogu da se preuzmu sa",
        "div18": "Kreiranje hostovanog servisa geoobjekta od CSV i „shapefile“ datoteke",
        "div19": "Kada kreirate hostovani servis geoobjekata pomoću CSV i „shapefile“ datoteka, prema podrazumevanim postavkama prilozi neće biti omogućeni. Da biste ih omogućili, otvorite stranicu detalja servisa, kliknite na strelicu na odeljku sloja i videćete tu opciju. Tura mape će nastaviti da koristi slike i sličice koje ste povezali preko atributa. Opciono, ako želite da otpremite slike kao priloge servisa geoobjekata, moći ćete to da uradite pomoću dva dugmeta na tabli slika („Promeni sliku“ i „Promeni sličicu“).",
        "div20": "Podržani formati slika i video zapisa",
        "div21": "Podržani formati slika su: <b>.jpg, .jpeg, .png, .gif i .bmp</b>. Ako se vaši mediji ne završavaju tom ektenzijom, tura mape će ih prepoznati kao video zapis, osim ako se ne koristi servis geoobjekata (pogledajte ispod).",
        "div22": "Šablon ture mape ne uključuje program za reprodukciju video zapisa, pa morate da koristite spoljni program za reprodukciju video zapisa omogućen od strane vašeg omiljenog servisa za hostovanje video zapisa (pronađite opciju da ugradite video zapis i kopirajte URL adresu u dȃti kôd). Ako želite da sami hostujete video zapis, možete da kreirate HTML stranicu koja sadrži program za reprodukciju video zapisa kao <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Interaktivna alatka za izradu ne omogućava dijalog za uključivanje video zapisa kada se koristi servis geoobjekata sa prilozima, ali je moguće da se to uradi uređivanjem podataka van interaktivne alatke za izradu. Ako izmenite polja slike da pokazuju na spoljni video zapis i dodate posebne parametre na kraj URL adrese (#isVideo) na arcgis.com pregledniku mape, smatraće se da je vaš medijski sadržaj video zapis.",
        "div24": "Imajte u vidu da i dalje morate da imate dva validna priloga slike ili pokazivanje neće biti korišćeno. Nije moguće korišćenje video zapisa kada se koristi prilog servisa geoobjekata bez polja slike i sličice."
      },
      "tab3": {
        "title": "Prilagođavanje",
        "div1": "Alatka za izradu omogućava nekoliko opcija prilagođavanja kojima se pristupa preko dugmeta POSTAVKE na gornjem panelu. Ako ne pronađete opciju koju tražite, takođe obezbeđujemo verziju koja može da se preuzme i koju možete da stavite u upotrebu na vašem veb serveru i da je poboljšate da se prilagodi vašim potrebama.",
        "div2": "Preporučujemo da koristite hostovanu verziju osim ako:",
        "div3": "<Line>ne nudi prilagođavanje korisničkog interfejsa koje želite, kao što je korišćenje snimka kao pozadine zaglavlja.</li><li>Vi ste programer i želite da poboljšate aplikaciju.</li>",
        "div4": "Verzija koja se preuzima može da bude konfigurisana kroz veb mapu ili identifikator web mapping aplikacije. Glavni slučajevi upotrebe su:",
        "div41": "Izrada ture mape korišćenjem interaktivne alatke za izradu u hostovanom okruženju i konfigurisanje šablona pomoću identifikatora web mapping aplikacije. Postavke koje ste definisali pomoću interaktivne alatke za izradu biće primenjene.",
        "div42": "Izrada veb mape van interaktivne alatke za izradu i konfigurisanje šablona pomoću identifikatora veb mape. Moraćete da pročitate dokumentaciju da biste naučili kako da konfigurišete šablon.",
        "div43": "Imajte u vidu da je interaktivna alatka za izradu dostupna u verziji za preuzimanje ali uz određena tehnička ograničenja na pregledačima kao što su Internet Explorer u verzijama ranijim od 10.",
        "div5": "Da preuzmete najnoviju verziju šablona i naučite više o tome kako da ga koristite, posetite <a href=’https://github.com/Esri/map-tour-storytelling-template-js’ target=’_blank’>stranicu projekta GitHub</a>."
      },
      "tab4": {
        "title": "Saveti",
        "div0": "Podržani pregledači",
        "div0a": "Preglednik ture mape je podržan na IE8+. Interaktivna alatka za izradu je podržana na IE9+. Aktivno testiramo je testiramo u svim važnijim pregledačima, ali ako iskusite neke poteškoće, preporučujemo da koristite Chrome.",
        "div0b": "Ako iskusite neke poteškoće, obavestite nas. U međuvremenu, izradom veb mape korišćenjem CSV šablona, svešćete na minimalni nivo interakciju sa interfejsom alatke za izradu.",
        "div1": "Slike",
        "div2": "Preporučujemo položenu orijentaciju fotografija umesto uspravne orijentacije. Fotografije sa 4:3 odnosom širine i visine se najbolje uklapaju. Položena orijentacija snimaka može da bude korišćena ali na manjim ekranima, kao što je iPad, veći deo fotografije može da bude prikriven natpisom (tekst zauzima više mesta kada je prikazan na visokim površinama u poređenju sa širokim površinama). Iako snimci različitih veličina, oblika i orijentacije mogu da budu korišćeni u turi mape, preporučujemo da koristite uvek istu veličinu i oblik za sve snimke. Na ovaj način korisniku neće odvraćati pažnju snimci različitih veličina dok prati turu.",
        "div2a": "Preporučujemo maksimalnu veličinu snimka od 1000 piksela širine i 750 piksela visine za glavne slike i 140x93 za sličice.",
        "div3": "Oblikovanje teksta natpisa korišćenjem HTML oznaka",
        "div4": "Zaglavlje i naslov/natpis slike mogu da uključuju HTML oznake da bi definisali oblikovanje teksta i linkova. Na primer, ovaj kod dodaje žuti link:",
        "div4a": "Napišite dobar podnaslov za turu",
        "div4b": "Uložite vreme u pisanje zanimljivog podnaslova za turu. Podnaslov je dobar način da privučete ljude ka vašoj turi i kažete im šta će otkriti tokom nje. Takođe, to je dobar način da saopštite čitaocima o zemlji ili državi u koju je tura smeštena. Na primer, nemojte da pretpostavljate da ljudi znaju gde su smešteni grad ili naselje u vašoj turi. Tekst natpisa takođe može da bude oblikovan korišćenjem HTML oznaka, kao što su uključivanje veza. Ipak, nemojte da natpis bude predugačak. Na manjim prozorima pregledača ili na uređaju iPad možda ne bude mogao da stane ceo natpis pa će biti isečen. Ako ne možete da smislite dobar podnaslov, ostavite prazno.",
        "div5": "Podržani slojevi",
        "div6": "Možete da dodate dodatne podržane slojeve da obezbedite kontekst turi mape. Ovi slojevi mogu da sadrže druge geografske geoobjekte koje želite da prikažete na tačkama ture mape, kao što je oblast izučavanja, ruta pešačenja ili vožnje, povezivanje tačaka ture, itd. Šablon ture mape prikazuje ove dodatne podržane slojeve koristeći simbologiju koju ste odredili u veb mapi, ali iskačući prozori nisu dostupni.",
        "div7": "Neka vaša tura bude kratka i slatka",
        "div8": "Postoji granica od 99 tačaka po turi. Naravno, većina tura mape je kraća od toga. Nemojte da očekujete da čitaoci žele da prolaze kroz previše tačaka ture. Možda ste vi fascinirani temom, ali nemojte da pretpostavljate da će i oni biti!",
        "div10": "Ugradi režim",
        "div11": "Ako želite da ugradite šablon na drugu veb lokaciju putem iframe dokumenta, dodavanje opcionog parametra „&embed“ na kraju URL adrese će ukloniti zaglavlje. Taj režim takođe može da bude postavljen u verziji za preuzimanje putem konfiguracione datoteke.",
        "div12": "Izbegavajte korišćenje iFrame dokumenta uske širine koji uzrokuje se da tura mape prebaci na raspored za mali ekran koji se odaziva na dodir. Da biste što više pojednostavili korišćenje, kada ugrađujete turu mape, uvek preporučujemo da obezbedite link pored ugrađene ture tako da korisnici mogu da pokrenu turu preko celog ekrana."
      },
      "tab5": {
        "title": "Objavljivanje",
        "div1": "Kada završite, ne zaboravite da podelite turu mape sa korisnicima preko PODELI dugmeta ili stanice stavke aplikacije na ArcGIS Online.",
        "div2a": "Deljenje ture putem alatke za izradu",
        "div2b": "Dugme PODELI će ažurirati stavke aplikacije i veb mape. Ako su podaci ture uskladišteni na stavci servisa geoobjekata, i ona će biti ažurirana. Ako ste dodali druge slojeve putem preglednika mape na ArcGIS.com, oni neće biti ažurirani. Ovo može da rezultira da tura ne bude podeljena kako ste očekivali. Stavke koje već imaju neophodne (ili više) privilegije neće biti ažurirane.",
        "div2c": "Deljenje ture putem ArcGIS Online",
        "div2d": "Kada delite aplikaciju putem ArcGIS Online, ako je potrebno biće vam postavljeno pitanje da li želite da ažurirate bilo koje zavisne resurse (veb mapu, servis geoobjekata, sloj dekoracije) koji nisu podeljeni na isti način. Ako je tura mape javna a jedan od vaših resursa nije podeljen sa vašim korisnicima, oni će biti preusmereni na ArcGIS Online stranicu za prijavljivanje.",
        "div3t": "Bezbednost servisa geoobjekata",
        "div3a": "Ako koristite hostovane servise geoobjekata kreirane pomoću alatke za izradu ture mape, aplikacija upravlja bezbednošću usluge za vas i jedino ćete vi imati privilegije izmena, čak i ako je podelite javno.",
        "div3t2": "Pre nego što podelite turu sa korisnicima",
        "div3": "Postarajte se da tura dobro radi kada niste prijavljeni putem svog ArcGIS.com naloga. URL adresa koju ćete da koristite ne sme da preusmerava na stranicu za prijavljivanje ili režim alatke za izradu.",
        "div4": "Dobra je ideja da pogledate kako tura mape izgleda na iPad uređaju u položenom položaju da biste se uverili da izgleda dobro na ovom popularnom uređaju. Ovo može da vam pomogne da vidite da li natpisi prekrivaju preveliki deo slika. Takođe, omogućava da vidite uklapanje podnaslova i da li su odsečeni jer su predugački.",
        "div5a": "Preporuke za pretragu",
        "div5b": "Da biste pomogli ljudima da nađu vašu turu mape ako pretražuju ArcGIS Online, preporučujemo da dodate oznaku „story map“ u vašu stranicu stavke aplikacije ture mape (ne na stranicu stavke veb mape), zajedno sa oznakama kao što su naziv države ili provincije gde je tura smeštena, naziv države ako je smeštena izvan SAD i tematske oznake kao što su „javna umetnost“, „turistički vodič“ ili „istorijska mesta“ Ove oznake nama u Esri kompaniji takođe pomažu da pronađemo nove primere tura koje možemo da prikažemo u našoj galeriji i da ih promovišemo putem društvenih medija. Takođe preporučujemo da u stranicu stavke aplikacije otpremite grafiku sličice koja lepo izgleda, kao što je na primer mali snimak ekrana ture ili jedna od slika iz nje. Ova slika se automatski koristi ako je vaša tura mape dodata u ArcGIS Online galeriju."
      }
    },
    "share": {
      "firstSaveTitle": "Tura je sačuvana",
      "manageStory": "Upravljaj pričom",
      "manageStoryA1": "Savet: možete da koristite %LINK1% da proverite da li priča ima greške i promenite kako se njene komponente dele. Lista „Moje priče“ takođe pomaže da učinite da vaša priča dobro izgleda kada se podeli na društvenim mrežama. Možete da saznate više o ostalim korisnim funkcijama liste „Moje priče“ ovde %LINK2%.",
      "manageStoryA1V1": "Moje priče",
      "manageStoryA1V2": "Poruke na blogu",
      "shareTitle": "Podelite turu",
      "sharePrivateHeader": "Tura nije podeljena, da li želite da je podelite?",
      "sharePrivateBtn1": "Podelite javno",
      "sharePrivateBtn2": "Podelite sa vašom organizacijom",
      "sharePrivateProgress": "Deljenje u toku...",
      "sharePrivateErr": "Deljenje nije uspelo, pokušajte ponovo ili",
      "sharePrivateOk": "Deljenje je ažurirano, učitavanje...",
      "sharePreviewAsUser": "Pregledaj",
      "shareHeader1": "Vaša tura je <strong>javno dostupna</strong>.",
      "shareHeader2": "Turi mogu da pristupe članovi organizacije (prijavljivanje je neophodno).",
      "shareLinkHeader": "Podelite turu",
      "shareLinkOpen": "OTVORI",
      "shareA1": "Koristite %SHAREIMG% na <a href=’%LINK1%’ target=’_blank’>stranici stavke aplikacije</a>. Ako želite da ukinete deljenje veb mape, koristite <a href=’%LINK2%’ target=’_blank’>stranicu stavke veb mape</a>.",
      "shareWarning": "Deljenje %WITH% je onemogućeno jer niste vlasnik <a href=’%LINK%’ target=’_blank’>veb mape</a>.",
      "shareWarningWith1": "javno",
      "shareWarningWith2": "javno i sa organizacijom"
    },
    "locator": {
      "error": "Lokacija nije dostupna"
    },
    "saveErrorSocial": {
      "title": "Ažuriranje deljenja na društvenim medijima",
      "panel1": "Izgled vaše priče na društvenim medijima je poboljšan, ali naslov vaše stavke ArcGIS veb aplikacije nije isti kao naslov vaše priče.",
      "panel1tooltip": "Određivanjem naslova, rezimea i sličice, vaša priča će izgledati ovako:",
      "panel2": "Koji naslov biste želeli da koristite na društvenim medijima:",
      "panel2q1": "Naslov priče (preporučeno)",
      "panel2q1tooltip": "Odabirom ove opcije naslov vaše stavke će biti izmenjen da se podudara sa naslovom vaše priče i dalje promene u alatki za izradu će biti sinhronizovane.",
      "panel2q2": "Naslov stavke",
      "panel3": "Da biste dodatno poboljšali izgled priče na društvenim medijima, koristite ${MYSTORIES} da dodate rezime i snimak sličice.",
      "panel4": "Nemoj ponovo da me upozoravaš na ovu priču",
      "mystories": "Moje priče",
      "btnSave": "Sačuvaj"
    }
  }
});