define({
  "viewer": {
    "loading": {
      "step1": "正在載入故事",
      "step2": "正在載入資料",
      "step3": "正在初始化瀏覽",
      "loadBuilder": "切換到建構器模式",
      "redirectSignIn": "重新導向到登錄頁面",
      "redirectSignIn2": "(登錄後您將重新導向到此處)",
      "fail": "抱歉，Map Tour 載入失敗",
      "failButton": "重試"
    },
    "errors": {
      "boxTitle": "發生錯誤",
      "portalSelf": "嚴重錯誤: 取得入口網站設定失敗",
      "invalidConfig": "嚴重錯誤: 無效的設定",
      "invalidConfigOwner": "嚴重錯誤: 無效的設定(需要授權的擁有者)",
      "invalidConfigNoWebmap": "嚴重錯誤: 無效的設定(index.html 中未指定 web 地圖或應用程式識別碼)",
      "invalidConfigNoAppDev": "未在 URL 參數（?appid= 或 ?webmap=）中指定 Web 製圖應用程式識別碼或 Web 地圖。在開發模式中，會忽略 index.html 中的 appid 和 webmap 配置。",
      "createMap": "無法建立地圖",
      "invalidApp": "嚴重錯誤: 無法載入故事",
      "noLayer": "Web 地圖不包含用於 Map Tour 的有效資料圖層。",
      "noLayerMobile": "Map Tour 建構器不支援此顯示大小。如果可行，請重新調整瀏覽器大小來存取建立器，或請在裝置上使用較大的畫面建立您的故事。",
      "noLayerMobile2": "請將裝置旋轉為橫向以使用 Map Tour 建立器。",
      "noLayerView": "歡迎使用 Map Tour Web 應用程式。<br />尚未設定該故事。",
      "appSave": "儲存故事時出錯",
      "mapSave": "儲存 web 地圖時出錯",
      "featureServiceLoad": "載入圖徵服務時出錯",
      "notAuthorized": "您未取得存取該故事的授權",
      "notAuthorizedBuilder": "您未取得使用 Map Tour 建立器的授權。",
      "oldBrowserTitle": "瀏覽器的部分功能不受支援",
      "noBuilderIE8": "第 9 版之前的 Internet Explorer 不支援 Map Tour 建構器。",
      "ie10Win7Explain": "當資料來源是帶有附件的圖徵服務時，Windows 7 上的 Internet Explorer 10 不支援 Map Tour 建構器。若要使用帶有附件的圖徵服務，需要<a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>手動使文件模式符合 Internet Explorer 9 標準</a>，<a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>降級為 Internet Explorer 9</a> 或升級為 Windows 8。",
      "oldBrowserExplain": "此瀏覽器不支援從上傳到 Map Tour 的圖像所自動生成縮圖。可使用此瀏覽器建立一個 Map Tour，但需要為每個上傳的圖像分別提供縮圖。",
      "oldBrowserExplain2": "為了提昇體驗，請<a href='http://browsehappy.com/' target='_blank'>升級瀏覽器</a>或<a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>啟動用於 Internet Explore 的 Google Chrome Frame</a>。",
      "oldBrowserExplain3": "Map Tour 建構器不適用於 Windows XP 上的 Internet Explorer 10。",
      "oldBrowserClose": "關閉",
      "noViewerIE2": "您正在嘗試使用較舊、不支援的瀏覽器來檢視此故事。可能有未運作的圖徵或發生其他非預期的問題。我們建議您升級至 Internet Explorer 11 或使用其他瀏覽器，例如 Chrome。",
      "noViewerIE3": "在 2017 年末，無法再於此瀏覽器上載入此故事。到時您必須使用支援的瀏覽器來檢視此故事。",
      "attention": "注意!"
    },
    "mobileHTML": {
      "showIntro": "顯示標題",
      "hideIntro": "隱藏標題",
      "navList": "清單",
      "navMap": "地圖",
      "navInfo": "媒體",
      "introStartBtn": "開始"
    },
    "desktopHTML": {
      "storymapsText": "故事地圖",
      "builderButton": "切換到建構器模式",
      "facebookTooltip": "在 Facebook 上分享",
      "twitterTooltip": "在 Twitter 上分享",
      "bitlyTooltip": "取得短連結",
      "bitlyStartIndex": "到目前地點的連結",
      "tooltipAutoplayDisabled": "這不適用於自動播放模式",
      "autoplayLabel": "自動播放模式",
      "autoplayExplain1": "自動播放模式將以一定間隔向前播放您的故事。這很適用於書報攤或公共顯示器，但請注意，在其他情況下可能會使得故事更難閱讀。此圖徵不支援小畫面。",
      "autoplayExplain2": "啟用此模式時，可使用控制項來播放/暫停故事和調整瀏覽速度。",
      "takeTourText": "進行導覽",
      "backToStart": "返回開頭"
    },
    "builderHTML": {
      "panelHeader": "故事設定",
      "buttonSave": "儲存",
      "buttonSettings": "設定",
      "buttonShare": "分享",
      "buttonView": "檢視模式",
      "buttonItem": "開啟 Web 應用程式項目",
      "buttonHelp": "說明",
      "buttonOrganize": "組織",
      "buttonOrganizeAndCover": "組織導覽點和新增封面頁",
      "buttonAdd": "新增",
      "buttonImport": "匯入",
      "buttonImportDisabled": "使用圖片上傳時無法使用匯入。 請按一下「新增」以上傳圖片。",
      "dataEditionDisabled": "已在此 CSV 資料來源上停用資料編輯",
      "dataSourceWarning": "Map Tour 資料圖層已變更。 如果圖徵 ID 不同，您必須透過<b>組織</b>重設順序和隱藏點。 如果欄位名稱不同，您必須在<b>設定的資料頁籤</b>下重設欄位設定。",
      "organizeWarning": "在隱藏互動式建構器之外新增一個或多個點。",
      "dataPicError0a": "此導覽包括 <b>%NB%</b> 個不符合規範的圖片 URL。",
      "dataPicError0b": "此導覽可能包括 <b>%NB%</b> 個不符合規範的圖片 URL。",
      "dataPicError1": "現在 Map Tour 要求圖片 URL 以下列任一副檔名為結尾: .jp(e)g、.png、.gif 或 .bmp。",
      "dataPicError2": "該要求不會影響現有已發佈的 Map Tour。但是，為了使用互動式建構器，您必須先執行以下兩種操作之一解決 URL 問題:",
      "dataPicError3": "編輯 URL",
      "dataPicError4": "此動作將在不受支援的圖片 URL 結尾新增 <i>#isImage</i>。 大多數伺服器都支援 URL 附加字尾。 但在執行該動作後，應導覽各站點以確認更新的圖片 URL 是否運作正常。 如果各圖片均可載入，現在即可儲存 Map Tour。 如果<b>圖片已損壞，則不要儲存 Map Tour</b>。 請重新載入建立器並執行第二個動作。",
      "dataPicError5": "限制對圖片的導覽",
      "dataPicError6": "此選項導致所有 URL 都被視為圖片，但您無法使用互動式建立器新增影片。 如果您以後決定新增影片，可以撤消此動作。",
      "dataPicError7": "您的 Map Tour 已限制為圖片，無法使用影片。 如果選擇移除該限制，請在儲存 Map Tour 前檢查您的圖片載入是否仍正確。 如有需要，您可以在稍後恢復該限制。",
      "dataPicError8": "移除圖片限制",
      "dataPicError9": "如果這些 URL 指向影片，您可以忽略此警告，如果指向圖片，則需要執行以下兩種操作之一:",
      "modalCancel": "取消",
      "modalApply": "套用",
      "organizeHeader": "組織導覽",
      "organizeGeneralCaption": "使用拖放功能進行導覽點分類",
      "organizeDelete": "刪除",
      "organizeHide": "隱藏",
      "organizeReset": "重設順序和隱藏點",
      "addMaxPointReached": "已達到圖示集允許的最多點數，無法再新增更多的導覽點。<br /><br />請注意，如果刪除現有的點，必須重新載入故事。",
      "addMaxPointReachedMobile": "抱歉，已達到授權點的最大數目，無法新增該圖片。",
      "addClose": "關閉",
      "addHeader": "新增新導覽點",
      "addTabPicture": "媒體",
      "addTabInformation": "資訊",
      "addTabLocation": "位置",
      "addSelectCaption": "選擇或拖放圖片",
      "addNoteVideo": "有關使用影片的說明，請查看說明",
      "addSelectCaptionNoFileReader": "選擇圖片",
      "addChangePhoto": "變更圖片和縮圖",
      "addPictureResolutionIntro": "圖片解析度高於所要求值:",
      "addPictureResolutionOldBrowser": "圖片解析度高於所要求值。請指定一個低於 %RECOMMENDED_RES% 的解析度，以便最佳化 Map Tour 體驗。",
      "addPictureResolutionResize": "將圖片解析度變更為 %RESOLUTION%",
      "addPictureResolutionKeep": "保持原始解析度 %RESOLUTION%",
      "addSelectThumbnail": "選擇縮圖",
      "addNoThumbSelected": "未選擇縮圖",
      "addThumbSelected": "選取",
      "addCameraSettingsHeader": "照相機設定",
      "addThumbnailHeader": "縮圖",
      "addLabelPicUrl": "圖片",
      "addLabelThumbUrl": "縮圖",
      "addTextPlaceholderUrl": "輸入圖像 URL",
      "addTextPlaceholderUrl2": "輸入 YouTube 頁面 URL",
      "addTextPlaceholderUrl3": "輸入 Vimeo 頁面 URL",
      "addTextPlaceholderUrl4": "輸入影片嵌入 URL",
      "addLabelVideo": "影片",
      "addMediaVideoOther": "其他",
      "addMediaVideoHelp": "檢查 URL 並取得預設縮圖",
      "addMediaVideoHelpTooltip1": "檢查成功",
      "addMediaVideoHelpTooltip2": "檢查失敗",
      "addMediaVideoHelpTooltip4": "找尋嵌入影片的選項並複製代碼中出現的影片 URL",
      "addLabelName": "名稱",
      "addLabelDescription": "說明文字",
      "addTextPlaceholder": "輸入內容",
      "addLocatePlaceholder": "查詢地址或地點",
      "addPinColor": "顏色",
      "addLatitude": "緯度",
      "addLongitude": "經度",
      "addLatitudePlaceholder": "例如 34.056",
      "addLongitudePlaceholder": "例如 -117.195",
      "addUploading": "上傳導覽點",
      "addSave": "新增導覽點",
      "addMobileUploading": "正在上傳圖片",
      "addMobileName": "輸入名稱",
      "addMobileNameMandatory": "錯誤，請輸入名稱。",
      "addMobileError": "抱歉，出現一些問題",
      "settingsHeader": "設定",
      "settingsTabLayout": "版面設定",
      "settingsTabColor": "顏色",
      "settingsTabLogo": "頁眉",
      "settingsTabFields": "資料",
      "settingsTabExtent": "範圍",
      "settingsTabZoom": "縮放級別",
      "settingsLayoutExplain": "選擇所需的版面設定。",
      "settingsLayoutProfessional": "三面板",
      "settingsLayoutModern": "整合式",
      "settingsLayoutSidePanel": "側面板",
      "settingsLayoutSelected": "選取的版面設定",
      "settingsLayoutNew": "新增!",
      "settingsLayoutSelect": "選擇",
      "settingsLayoutNote": "請注意，在使用影片的位置，即使未勾選該選項，標題也始終位於影片下方。",
      "settingsLayoutLocBtn": "顯示“定位”按鈕",
      "settingsLayoutLocBtnHelp": "大多數瀏覽器皆支援。只有在透過 HTTPS 存取故事地圖時才會出現。若內嵌地圖則不會出現。",
      "settingsColorExplain": "透過選擇預定義的主題或建立自訂主題變更外觀。",
      "settingsLabelColor": "頁眉、內容和頁腳顏色",
      "settingsLogoExplain": "自訂頁眉標誌(不超過 250 x 50px)。",
      "settingsLogoEsri": "Esri 標誌",
      "settingsLogoNone": "無標誌",
      "settingsLogoCustom": "自訂標誌",
      "settingsLogoCustomPlaceholder": "圖像 URL",
      "settingsLogoCustomTargetPlaceholder": "點選連結",
      "settingsLogoSocialExplain": "自訂標題右上方的連結。",
      "settingsLogoSocialText": "文字",
      "settingsLogoSocialLink": "連結",
      "settingsLogoSocialDisabled": "管理員已停用此功能",
      "settingsDataFieldsExplain": "選擇照片名稱、說明文字和顏色欄位。",
      "settingsDataFieldsError": "應用程式無法確定相應的名稱、說明文字或顏色資料。請選擇要在此處使用的欄位。這些設定之後可進行變更。",
      "settingsFieldsLabelName": "名稱",
      "settingsFieldsLabelDescription": "說明文字",
      "settingsFieldsLabelColor": "顏色",
      "settingsFieldsReset": "重設欄位選擇",
      "settingsExtentExplain": "在下面的互動式地圖上設定 Map Tour 首頁範圍。",
      "settingsExtentExplainBottom": "您定義的範圍將修改地圖的首頁範圍。 請注意，如果不包括第一個導覽點，則不會使用此範圍。 這時將以第一個點為中心開啟導覽。",
      "settingsExtentDateLineError": "範圍不可跨越 180° 經線",
      "settingsExtentDateLineError2": "計算範圍時出錯",
      "settingsExtentDrawBtn": "畫一個新範圍",
      "settingsExtentModifyBtn": "編輯範圍",
      "settingsExtentApplyBtn": "Map Tour 預覽",
      "settingsExtentUseMainMap": "使用 Map Tour 範圍",
      "settingsZoomExplain": "設定故事點的縮放 (選用)。",
      "settingsLabelZoom": "比例/級別",
      "settingsZoomFirstValue": "無",
      "settingsFieldError": "請在每個清單中選擇一個欄位",
      "dataTitle": "建立託管的 Map Tour 圖層",
      "dataExplain": "將為您的圖像和導覽點建立新的圖徵圖層。除非您分享您的 Map Tour，否則不會與任何人分享導覽圖層。",
      "dataExplainPortal": "若未成功建立圖徵圖層，請聯絡您的 ArcGIS 管理員。",
      "dataNameLbl": "圖層名稱",
      "dataFolderListLbl": "文件夾",
      "dataFolderListFetching": "獲取文件夾 ...",
      "dataRootFolder": "根目錄",
      "dataNameError": "輸入圖徵服務的名稱",
      "dataFolderError": "選擇有效的文件夾",
      "dataSrcContainsInvalidChar": "圖徵服務名稱包含一個或多個無效的字元 (-, <, >, #, %, :, \", ?, &, +, /, 或 )。",
      "dataSrvAlreadyExistsError": "組織中已經存在該名稱的服務。請選擇其他名稱。",
      "dataBtnSave": "建立圖層",
      "dataFooterProgress": "正在建立",
      "dataFooterSucceed": "建立成功。正在載入",
      "dataFooterError": "建立失敗。請重試",
      "tabError": "請檢查所有索引標籤中的錯誤",
      "introRecordBtn": "入口",
      "introRecordActivate": "將第一個點做為導入點 (不在轉盤中顯示)",
      "coverRecordActivate": "將第一個點作為封面頁",
      "coverBuilder": "封面頁配置",
      "cover": "封面",
      "showCover": "顯示封面",
      "editCover": "編輯封面",
      "coverNoVideo": "封面媒體不支援影片。請選擇圖片。",
      "coverPreview": "若要看到封面頁，請儲存故事，然後使用「檢視故事」按鈕預覽它。",
      "thirdPartyTerms": "使用協力廠商服務時，即表示您同意其服務條款。 "
    },
    "addPopupJS": {
      "uploadingPicture": "正在上傳圖片",
      "uploadSuccess": "上傳成功",
      "uploadError": "上傳圖片出錯",
      "uploadError2": "新增圖徵時出錯(html 標記無效)",
      "notJpg": "請選擇 jpeg 格式的照片",
      "errorNoPhoto": "選擇要上傳的圖像",
      "errorNoThumbnail": "選擇要上傳的縮圖",
      "errorInvalidPicUrl": "請輸入有效的圖片 URL。 以 https 開頭。 以 jpg、png、gif 或 bmp 結尾，或將 '#isImage' 作為 URL 的結尾以覆蓋該規則。",
      "errorInvalidThumbUrl": "輸入有效縮圖 (以 https:// 開頭，以 jpg、png、gif 或 bmp 結尾)。",
      "errorInvalidVideoUrl": "輸入有效影片 URL(以 https:// 開頭)",
      "errorNoName": "輸入該導覽點的名稱",
      "errorNoDescription": "輸入該導覽點的說明文字",
      "errorNoLocation": "設定該導覽點的位置"
    },
    "builderJS": {
      "noPendingChange": "無未儲存的變更",
      "unSavedChangeSingular": "1 個未儲存的變更",
      "unSavedChangePlural": "未儲存的變更",
      "shareStatus1": "未儲存導覽",
      "shareStatus2": "導覽已公開分享",
      "shareStatus3": "導覽已在組織內部分享",
      "shareStatus4": "導覽未分享",
      "popoverDiscard": "確定要放棄未儲存的變更嗎?",
      "yes": "是",
      "no": "否",
      "popoverLoseSave": "打開檢視器時，您將流失所有未儲存的變更",
      "ok": "確定",
      "popoverSaveWhenDone": "完成後請不要忘記儲存",
      "closeWithPendingChange": "是否確定要確認動作? 您的變更將遺失。",
      "gotIt": "確定",
      "savingApplication": "正在儲存故事",
      "saveSuccess": "故事已儲存",
      "saveError": "儲存失敗，請重試",
      "saveError2": "由於名稱或描述中存在無效的 html 標記，因此儲存失敗",
      "saveError3": "標題不能為空",
      "dragColorPicker": "隨意移動<br />或變更顏色",
      "dataWarningExtent": "部分資料位於 web 地圖的範圍之外。這些資料不用作導覽點，如果要使用，請變更地圖範圍。",
      "dataWarningVisibi": "您的 Map Tour 圖層在目前 web 地圖範圍內不可見。將地圖放大到 %MAPSIZE% ，確認您的 Map Tour 圖層是可見的。",
      "dataWarningEdit": "編輯 web 地圖",
      "dataWarningClose": "關閉",
      "signIn": "請使用帳戶登錄",
      "signInTwo": "以儲存故事。",
      "switchBM": "變更底圖"
    },
    "organizePopupJS": {
      "messageStart": "您已選擇刪除",
      "messageSinglePoint": "一個導覽點",
      "messageMultiPoint": "多個導覽點",
      "messagePermantRemove": "此操作將從資料庫永久移除",
      "messageRecord": "個記錄",
      "messageRecordPlural": "個記錄",
      "messageConfirm": "。是否要繼續?",
      "labelButtonShow": "顯示",
      "labelButtonHide": "隱藏"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "這將永久刪除圖片和縮圖",
      "popoverDeleteWarningThumb": "這將永久刪除縮圖",
      "popoverUploadingPhoto": "正在上傳圖片和縮圖",
      "popoverUploadingThumbnail": "正在上傳縮圖",
      "popoverUploadSuccessful": "上傳成功",
      "popoverUploadError": "上傳失敗，請重試",
      "changePicAndThumb": "變更圖片",
      "changeThumb": "變更縮圖",
      "selectPic": "變更媒體",
      "selectThumb": "變更縮圖",
      "uploadPicAndThumb": "套用"
    },
    "headerJS": {
      "editMe": "編輯!",
      "templateTitle": "設定標題",
      "templateSubtitle": "設定子標題",
      "edit": "編輯"
    },
    "crossFaderJS": {
      "setPicture": "設置圖片標題",
      "setCaption": "設置圖片說明文字"
    },
    "importPopup": {
      "title": "匯入",
      "prevBtn": "上一步",
      "nextBtn": "下一步"
    },
    "importPopupHome": {
      "header": "圖片儲存在哪裡?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "圖片",
      "videos": "影片",
      "disabled": "管理員已停用此功能",
      "disabledPortal": "此功能需要入口網站具有託管伺服器。請聯絡您的 Portal for ArcGIS 管理員。",
      "header1": "您的圖片必須公開分享。",
      "header2": "匯入將限制為前 %NB1% 個 %MEDIA%。",
      "emptyDataset": "發生錯誤，未找到圖片",
      "footerImport": "匯入",
      "selectAlbum": "選擇公開圖片集",
      "selectAlbum2": "選擇圖片集",
      "pleaseChoose": "請選擇",
      "userLookup": "查詢",
      "userLookingup": "正在查詢",
      "csv": "在 CSV 中引用",
      "advanced": "進階選項",
      "advancedScratchLbl": "啟動新的導覽",
      "advancedScratchTip": "建立可在其中新增導覽點的空白導覽。您的媒體必須已連線。此選項不支援圖片上傳。",
      "advancedCSVLbl": "從 CSV 檔案匯入導覽資料",
      "advancedCSVTip": "從在線上參考媒體的 CSV 檔案中匯入導覽內容。此選項不支援圖片上傳。",
      "advancedCommonTip": "這需要圖像和影片均已上線。",
      "select": "做出選擇",
      "locUse": "使用圖片地理位置",
      "locExplain": "由於圖片位置可能源自圖片集，造成所有照片都在相同的位置，因此您可能不想使用圖片位置。",
      "locExplain2": "由於影片位置可能源自使用者的設定，造成所有影片均位於同一位置，因此您可能不想使用影片位置。"
    },
    "viewFlickr": {
      "title": "Flickr 匯入",
      "header": "輸入 Flickr 使用者名稱並選擇要匯入的圖片集或標記。",
      "userInputLbl": "輸入使用者名稱",
      "signInMsg2": "未找到使用者",
      "selectSet": "選擇圖片集",
      "selectTag": "或選擇標記",
      "footerImportTag": "匯入選取的標記",
      "footerImportSet": "匯入選擇的圖片集"
    },
    "viewFacebook": {
      "title": "Facebook 匯入",
      "header": "使用 Facebook 使用者帳戶進行驗證或使用公開頁面。私人圖片集可用於建立不需要 Facebook 使用者驗證的公開 Map Tour ，這樣可以保持評論和喜好的私密性。",
      "leftHeader": "Facebook 使用者",
      "rightHeader": "Facebook 頁面",
      "pageExplain": "Facebook 頁面屬￿公開品牌/產品或像 <b>esrigis</b> 一樣的名品。您可以在 URL 頁面的第一個 '/' 後面取得頁面名稱。",
      "pageInputLbl": "輸入頁面名稱",
      "lookupMsgError": "未找到頁面"
    },
    "viewPicasa": {
      "title": "Google+ 匯入",
      "header": "輸入您的電子郵件位址或您的 ID。",
      "userInputLbl": "電子郵件或 Picasa/Google+ ID",
      "signInMsg2": "未找到帳戶",
      "signInMsg3": "無公開圖片集",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>瞭解詳細資訊</a>",
      "howToFind2": "複製任何 Picasa 頁面第一個和第二個 '/' 之間的數字"
    },
    "viewCSV": {
      "title": "CSV 匯入",
      "uploadBtn": "選擇或刪除 CSV 檔案",
      "resultHeaderEmpty": "CSV 為空",
      "resultHeaderSuccess": "已載入 %NB_POINTS% 個點",
      "resultHasBeenLimited": "匯入已限制為 %VAL2% 個點的前 %VAL1% 個點，以符合每次瀏覽 %VAL3% 個點的限制",
      "browserSupport": "您的瀏覽器不受支援，若要使用 CSV，必須<a href='http://browsehappy.com/' target='_blank'>升級瀏覽器</a>或使用 ArcGIS.com web 地圖檢視器 (請參閱“說明”)。",
      "errorLatLng": "未找到緯度和經度欄位。可能的緯度值為: <i>%LAT%</i>，經度值為: <i>%LONG%</i>。",
      "errorFieldsExplain": "未找到以下必填欄位，所以載入失敗",
      "errorFieldsName": "<b>名稱</b>可能值為: %VAL%",
      "errorFieldsDesc": "<b>描述</b>可能值為: %VAL%",
      "errorFieldsUrl": "<b>圖片 URL</b> 可能值為: %VAL%",
      "errorFieldsThumb": "<b>縮圖 URL</b> 可能值為: %VAL%",
      "errorFields2Explain": "載入失敗，因為 CSV 沒有使用與以下圖層屬性相同的屬性",
      "errorFields2Name": "<b>名稱</b>使用 %VAL1% 替代 %VAL2%",
      "errorFields2Desc": "<b>描述</b>使用 %VAL1% 替代 %VAL2%",
      "errorFields2Url": "<b>圖片 URL</b> 使用 %VAL1% 替代 %VAL2%",
      "errorFields2Thumb": "<b>縮圖 URL</b> 使用 %VAL1% 替代 %VAL2%",
      "resultFieldsAll": "已匯入所有屬性",
      "resultFieldsNotAll": "未匯入以下屬性，因為它們不存在於地圖圖層中",
      "resultFieldsNotAll2": "未匯入以下屬性",
      "footerNextBtnResult": "匯入到 Web 地圖",
      "footerProgress": "匯入進行中",
      "footerSucceed": "匯入成功。正在載入"
    },
    "viewYoutube": {
      "title": "YouTube 匯入",
      "header": "輸入 YouTube 使用者名以查詢公開分享的影片。",
      "pageInputLbl": "輸入 YouTube 使用者名",
      "lookupMsgError": "未找到使用者",
      "howToFind": "如何查詢 YouTube 使用者名稱",
      "howToFind2": "使用者名稱顯示在影片下方",
      "found": "已找到",
      "noData": "未找到公開影片"
    },
    "viewGeoTag": {
      "title": "選擇並定位您的圖像/影片",
      "header": "將匯入定位的項目。 按一下要匯入的任何未定位項目，以將其定位。",
      "headerMore": "說明",
      "headerExplain": "按一下<b>匯入</b>按鈕時，只會匯入<b>已定位</b>頁籤中的圖片或影片。<br><br>如果可存取與圖片或影片一起儲存的地理位置資訊，則會自動匯入該資訊。 會在<b>定位</b>頁籤中列出不含地理位置的任何項目。 若要定位該頁籤列出的項目，請按一下它，然後按一下地圖上的所要位置。<br><br>若要從<b>已定位</b>頁籤中移除項目以避免匯入該項目，請按一下將游標移至該項目上方時所出現的「不要匯入」按鈕。<br><br>提示: 若目前未匯入您擁有之媒體的地理位置資訊，請檢查您的帳號的隱私權設定。 例如，確定您的 Flickr 帳號設定中未隱藏 EXIF 資料。 此外，若關閉用來匯入新上傳之 EXIF 資料的 Flickr 隱私權選項 (預設) 值，則不會在 Flickr 中儲存圖片的地理位置，除非您重新上傳它們，或在 Flickr 中手動指定其位置。",
      "leftPanelTab1": "定位",
      "leftPanelTab2": "已定位",
      "clickOrTap": "按一下「地圖」加以定位",
      "clearLoc": "清除位置",
      "clickDrop": "不要匯入",
      "footerImport": "匯入",
      "footerProgress": "匯入進行中",
      "footerSucceed": "匯入成功。正在載入...",
      "loading": "正在載入",
      "error": "圖片地理位置匯入失敗，地理位置已被忽略。"
    },
    "initPopup": {
      "title": "歡迎使用 Map Tour Builder",
      "prevBtn": "上一步",
      "nextBtn": "下一步"
    },
    "initPopupHome": {
      "header1": "圖像或影片的位置在哪?",
      "header2": "該助手將協助您透過從已經儲存在線上的媒體建構 Map Tour，或者將媒體匯入到您的 ArcGIS Online for Organizations 帳戶。",
      "title1": "媒體已上線",
      "title2": "我需要上傳我的圖像",
      "hostedFSTooltip": "上傳您的圖片並將其儲存於導覽中 (不支援影片)。",
      "hostedFsNA": "您必須是發佈者，或是具有發佈託管的圖徵圖層權限的其他角色。請聯絡您的 ArcGIS 管理員。",
      "hostedFsNA2": "僅適用於 ArcGIS Online 訂閱。<a href='%LINK%'>註冊免費試用</a>",
      "footer1": "完成後，不要忘記透過應用程式項目頁面分享您的 Map Tour 。",
      "footer3": "下載 CSV 範本",
      "footer4": "如果不下載，則 \"另存新檔\"",
      "footer4bis": "如果下載未開始，請右鍵按一下並選擇“另存新檔”",
      "footer5": "瞭解詳細資訊",
      "footerProgress": "正在建立",
      "footerSucceed": "建立成功。正在載入..."
    },
    "helpPopup": {
      "title": "說明",
      "close": "關閉",
      "tab1": {
        "title": "簡介",
        "moreInfo": "如需詳細資訊",
        "infoSites": "造訪 <a href='https://storymaps.arcgis.com' target='_blank'>Esri Story Maps 網站的 <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>Map Tour 部分。</a></a>",
        "mtFAQ": "請參閱 <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Map Tour 常見問題集。</a>",
        "myStories": "您可以管理 Map Tour，並在網站的<a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>我的故事</a>中檢查其中是否有錯誤。",
        "div1": "Map Tour 範本旨在呈現地理資訊，為您要講述的故事提供吸引人的攝影或媒體元素。",
        "div2": "範本可生成具有吸引力且易於使用的 web 應用程式，讓您按編號順序在地圖上顯示使用者可瀏覽的一小組地點。該範本可在任何裝置上的任何 web 瀏覽器中使用，其中包括智慧型手機和平板電腦。<br /><br />",
        "div42": "若要查看其他使用者正在建立的 Map Tour 範例，請造訪 <a href='https://storymaps.arcgis.com/' target='_blank'>Story Maps 網站</a>上的<a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>圖庫</a>。您也可以在 Twitter (<a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>) 上追蹤我們的動態。",
        "div5": "我們很希望聽到您的意見! 請造訪 <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet</a> 上的 Story Maps 論壇，告訴我們問題和您需要的新功能。"
      },
      "tab2": {
        "title": "資料",
        "div1": "建構Map Tour 時要考慮的主要因素是選擇在何處儲存圖片。Map Tour 可使用圖片分享服務上儲存的圖片、任何 Web 伺服器上的圖片，或從磁碟上傳的圖片。",
        "div1a": "有關受支援的圖片格式和影片的詳細資訊，請參閱此索引標籤的最後一部分。",
        "div2": "互動式建構器提供兩個選項，用於處理您的 Map Tour 中的影像:",
        "div3": "<ul><li>您可以使用<b>已經在線上的照片</b>，例如 Flickr 或 Google+ 中的圖片，或您自己的 Web 伺服器所儲存的圖片。 透過這些圖片的 URL，在您的 Map Tour 中參考它們。</li><li>還可以<b>透過電腦將照片</b>直接上傳到您的 Map Tour。 該上傳選項需要您具有 ArcGIS 訂閱並擁有發佈者或管理員權限，因為系統將自動為您建立託管圖徵服務，您可將照片做為附件儲存在其中。</li></ul>",
        "div4": "主要用例包括:",
        "div4b": "<b>您的照片尚未託管</b>，且您擁有 ArcGIS 訂閱: 使用託管的圖徵服務是您的最佳選擇。與公開照片分享服務一樣，我們將最佳化您的圖片以建立快速載入影像，您將可以存取 ArcGIS 平臺的所有管理和資料管理功能。",
        "div5": "<b>您不是組織的成員</b>: 首先，您需要將圖片上傳到照片分享網站或您自己的 web 伺服器上。建構器將協助您使用這些繼續託管在其原始位置的圖片。",
        "div6": "<b>您希望重複使用現有圖徵服務</b>將圖片儲存為附件或引用外部圖片: 請參閱下面的詳細描述部分。",
        "div7": "<b>您是上一版 Map Tour </b>範本的使用者，且已經擁有引用圖片和縮圖的 CSV: 您可以匯入該 CSV 並最佳化資料。建構器僅支援使用緯度/經度欄位的 CSV; 以地址為基礎的 CSV 可以繼續在您的 web 地圖中使用 (請參閱以下部分)。",
        "div8": "從線上照片分享服務中匯入",
        "div9a": "Facebook 支援已中斷，${learn}。",
        "learn": "瞭解詳細資訊",
        "div9": "匯入操作透過在 web 地圖圖徵集中儲存其 URL 來引用已託管的圖片。圖片並未儲存在 ArcGIS Online 中。如果無法存取託管的圖片，則無法在 Map Tour 中使用，您將看到“圖片不可用”的圖像。依您的照片服務提供者而定，Map Tour 可能不會匯入圖片的名稱、描述和位置。這些屬性儲存在 web 地圖中，對在線上服務進行的任何編輯都不會反映在 Map Tour 中。",
        "div10": "在 web 伺服器上儲存圖片",
        "div11": "如果選擇在自己的 Web 伺服器上託管圖片 (而非在 Flickr 或 Google+ 中存取圖片，或將它們直接上傳到您的導覽)，則必須手動建立圖片的縮圖。 使用完整解析度的圖片建立縮圖將導致效能不佳。 若要透過 URL 直接在 Web 上存取圖片，請參閱此<a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>常見問題集</a>以取得調整圖片大小的提示。",
        "div12": "使用現有的 GIS 資料",
        "div13": "若任何圖徵服務、CSV 檔案或包含點的 shapefile 包含應用程式所預期的欄位集，則可將其作為 Map Tour 資料資源。您必須將其作為圖層新增至 ArcGIS Web 地圖，然後藉由建立 Map Tour 來分享地圖。",
        "div14": "欄位名稱的支援值包括 (不區分大小寫):",
        "div151": "名稱",
        "div152": "描述",
        "div153": "圖片",
        "div154": "縮圖",
        "div155": "顏色 ",
        "div16": "如果在使用圖徵服務時，應用程式未找到匹配欄位，在您透過建構器設定要使用的欄位之前，檢視器無法使用。新增到 web 地圖的 CSV 和 shapefile 圖層需要包含所有必填欄位，否則建構器將無法運作。",
        "div162": "使用將圖片儲存為附件的圖徵服務時，<b>只能使用帶有兩個附件的圖徵</b>。第一個附件定義主要圖片，第二個附件定義縮圖。",
        "div17": "對於不帶附件的圖徵服務，圖片和縮圖欄位為必填欄位；對於帶附件的圖徵服務，圖片和縮圖欄位為可選欄位 (但強烈建議填寫)。如果您的服務已啟用附件，建構器將讓您以附件形式上傳圖片。如果沒有啟用，您只能編輯圖片和縮圖 URL。",
        "div172": "如果存在，則將始終使用圖片和縮圖欄位，且不會查詢圖徵服務附件。",
        "div173": "範例 CSV 和 shapefile 可以下載位置",
        "div174": "有關使用現有 GIS 資料的詳細資訊，請參閱此<a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>常見問題集</a>。",
        "div18": "透過 CSV 或 shapefile 建立託管的圖徵服務",
        "div19": "透過 CSV 或 shapefile 建立託管的圖徵服務時，預設不啟用附件。要啟用附件，請打開圖徵服務的詳細資訊頁面，按一下圖層部分上的小箭頭，您將看到該選項。Map Tour 將繼續使用透過屬性引用的圖片和縮圖。另外，如果想將圖片做為圖徵服務附件上傳，可以使用圖片面板上的兩個按鈕(“變更圖片”和“變更縮圖”)。",
        "div20": "支援的圖片格式和影片",
        "div21": "若在 Flickr 或 Google+ 中存取圖片，Map Tour 將自動存取那些 .jpg 圖片檔。 若將圖片上傳到 Map Tour 建立器，圖片必須具有 .jpg 或 .jpeg 格式。 若透過圖片的 URL，直接在 Web 上參考該圖片，則支援的圖片格式將是 .jpg、.jpeg、.png、.gif 和 .bmp。 直接支援 YouTube 影片。",
        "div22": "Map Tour 範本不包括影片播放器，因此您必須使用喜歡的影片託管服務所提供的外部影片播放器 (找到嵌入影片並複製給已知代碼中的 URL 的選項)。如果您想要自己託管影片，則可以建立包含影片播放器 (例如 <a href='http://www.videojs.com/'>Video.js</a>) 的 HTML 頁面。",
        "div23": "使用帶有附件的圖徵服務時，互動式建構器不提供可包含影片的對話方塊，但可以透過在互動式建構器外部編輯資料進行。在 arcgis.com 地圖檢視器中，如果將圖片欄位修改為指向外部影片，並在 URL 尾部新增特殊參數 (#isVideo)，則您的媒體將被視為影片。",
        "div24": "請注意，您仍需要兩個有效的圖片附件，否則將不會使用此點。使用不含圖片和縮圖欄位的圖徵服務附件時，無法使用影片。"
      },
      "tab3": {
        "title": "自訂",
        "div1": "建構器提供幾個自訂選項，可以透過頂部面板中的“設定”按鈕進行存取。如果沒有找到所需的選項，我們還提供一個可下載版本，您可以在 web 伺服器上進行部署，並可強化以符合您的需求。",
        "div2": "建議您使用託管的版本，除非:",
        "div3": "<li>它不提供您想要的 UI 自訂，例如使用標題背景圖像。</li><li>您是開發者，並且希望增強應用程式。</li>",
        "div4": "可透過 web 地圖或 web 製圖應用程式識別碼設定可下載版本。主要用例有:",
        "div41": "使用託管環境中的互動式建構器來建立Map Tour，並透過 web 製圖應用程式識別碼來設定範本。將套用透過互動式建構器定義的設定。",
        "div42": "在互動式建構器外部建構您的 web 地圖，並透過 web 地圖識別碼設定範本。您需要閱讀說明文件以瞭解如何設定範本。",
        "div43": "請注意，可下載的版本中提供互動式建構器，但對於 Internet Explorer 10 之前的舊版瀏覽器仍有技術限制。",
        "div5": "要下載最新版本的範本並瞭解其使用方法，請存取 <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub 項目頁面</a>。"
      },
      "tab4": {
        "title": "提示",
        "div0": "支援的瀏覽器",
        "div0a": "IE8+ 支援 Map Tour 檢視器。IE9+ 支援互動式建構器。我們已經在所有主要瀏覽器中進行測試，但如果您遇到了困難，則建議您使用 Chrome。",
        "div0b": "如果您遇到任何困難，請與我們聯繫。此外，使用 CSV 範本建構 Map Tour，可將您與建構器介面的互動降至最低。",
        "div1": "圖片",
        "div2": "雖然可在一個 Map Tour 中使用不同大小、形狀和方向的圖片，但建議使用橫向方向而不是縱向方向的圖片。 4:3 長寬比的圖片最適合。 在三面板和整合式版面配置中 (標題與圖片會重疊)，使用縱向方向圖片會使得大量圖片被標題遮擋。 在三面板和整合式版面配置中，如果可能的話，建議您對所有圖片使用相同的大小和形狀。 利用這種方式，使用者在導覽時就不會因不同大小的圖片而分散注意力。",
        "div2a": "建議主要圖片的最大圖像大小為 1000 像素 (寬) x 750 像素 (高)，縮圖的最大圖像大小為 140 像素 (寬) x 93 像素 (高)。",
        "div3": "使用 HTML 標記將說明文字格式化",
        "div4": "您可以在標題中輸入 HTML 標記以定義格式和連結。例如，這些標記會新增綠色超連結:",
        "div4aa": "<b>建立側面板導覽的封面頁</b><br>「側面板」版面配置支援選用的封面頁，讓您能使用美觀的全螢幕圖片來吸引觀眾的目光。 若要配置側面板導覽的封面頁，請先將部分或所有點新增至導覽。 接著按一下「組織」按鈕，然後在出現的對話方塊中，確定要用來定義封面頁的導覽點是導覽中的第一個點。 接著按一下該對話方塊中的「將第一個點作為封面頁」方塊。 第一個導覽點的名稱將成為封面頁上顯示的標題、該點的標題將成為子標題，並將該點的圖片作為封面頁圖片。 封面頁不支援影片。 有關詳細資訊，請參閱此<a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>常見問題集</a>。</a>",
        "div4a": "為導覽寫出適當的子標題",
        "div4b": "請利用時間為導覽編寫吸引人的子標題。 子標題是吸引人們關注您的導覽並簡要介紹內容的良好途徑。 它也是告知觀眾該導覽所在的州或國家的好地方。 例如，不要假設大家都知道導覽中城市或城鎮的位置。 但不要製作太長的子標題。 如果想不到適當的子標題，請將其留空。 與三面板和整合式版面配置不同的是，側面板版面配置不支援其標頭中的子標題。 若在「側面板」版面配置中使用封面頁選項，封面頁將顯示導覽中第一點的標題，並作為導覽的子標題。",
        "div5": "支援圖層",
        "div6": "您可以新增其他支援的圖層為 Map Tour 提供上下文。 除 Map Tour 點之外，這些圖層還可能包含您希望地圖顯示的其他地理圖徵，例如研究區域、連結到導覽點的步行或開車路線等等。 Map Tour 樣板透過您在 Web 地圖中指定的符號系統顯示這些附加的支援圖層，但不支援為圖層定義的任何快顯視窗。 若要為您的導覽新增支援圖層，請儲存工作並關閉 Map Tour 建立器。 然後開啟導覽中使用的 Web 地圖。 您可以在 ArcGIS 的「我的內容」中，或透過 Story Maps 網站的「我的故事」部分來尋找此功能。",
        "div7": "維持導覽簡潔明瞭",
        "div8": "每次導覽限制為 99 個點。大部分 Map Tour 肯定明顯少於該限制。不要期望觀眾願意逐一瀏覽過多的導覽點。您可能覺得自己的主題很吸引人，但不要以為其他人也這麼想!",
        "div10": "嵌入模式",
        "div11": "如果您想要透過 iframe 將範本嵌入另一個網站，在 URL 末端添加選用參數 \"embed\" 將移除標頭。",
        "div12": "避免使用狹窄的 iFrame 寬度，因其可能導致 Map Tour 切換至其小型的顯示視圖，也就是導覽在行動裝置上使用的視圖。 為了擴大使用簡易性，在嵌入 Map Tour 時，通常建議在所嵌入的導覽旁邊提供一個連結，以便使用者啟動全螢幕導覽。"
      },
      "tab5": {
        "title": "發佈",
        "div1": "完成操作後，不要忘記透過 ArcGIS Online 中的“分享”按鈕或應用程式項目頁面分享您的 Map Tour 。",
        "div2a": "透過建構器分享導覽",
        "div2b": "透過“分享”按鈕可更新應用程式和 web 地圖項目。如果您的導覽資料儲存在圖徵服務項目中，也會更新。如果透過 ArcGIS.com 地圖檢視器新增其他圖層，則這些圖層將不會進行更新。這可能導致導覽不會按預期進行分享。具有必要 (或更多) 權限的項目將不會更新。",
        "div2c": "透過 ArcGIS Online 分享導覽",
        "div2d": "透過 ArcGIS Online 分享應用程式時，系統將在必要時要求您更新非以相同方式分享的所有相關資源(web 地圖、圖徵服務和裝飾圖層)。如果 Map Tour 處於公開狀態，且其中一個資源並沒有分享給觀眾，則使用者將被重新導向至 ArcGIS Online 登錄頁面。",
        "div3t": "圖徵服務安全性",
        "div3a": "如果使用透過 Map Tour 建構器建立的託管圖徵服務，應用程式將為您管理服務安全性，即使公開分享服務，您也是唯一具有編輯權限的人員。",
        "div3t2": "在分享導覽之前",
        "div3": "請確保在未使用 ArcGIS.com 帳戶登錄時，導覽也可正常運作。要使用的 URL 不應重新導向至登錄頁面或建構器模式。",
        "div4": "最好查看 iPad 上以橫向儲存的 Map Tour 的外觀，以確保在這種普遍的裝置上看起來美觀。這有助於瞭解文字說明是否覆蓋了圖片太多。還可以使您瞭解子標題是否合適，以及是否因過長而被裁剪。",
        "div5a": "搜尋建議",
        "div5b": "要協助大家在搜尋 ArcGIS Online 時找到您的 Map Tour，我們建議在您的 Map Tour 應用程式項目頁面 (而並非 web 地圖的項目頁面) 中新增“故事地圖”標記以及其他標記，例如該導覽所在的州或省名稱、美國以外的國家名稱，以及諸如“公開藝術”、“遊客指南”或“歷史名勝”的主題標記。這些標記還可以協助我們在 Esri 中找到有趣的新導覽範例，我們可以在圖庫中展示這些範例，並在社交媒體上進行宣傳。同時建議您在應用程式項目頁面中上傳美觀的縮圖，例如導覽的小型螢幕截圖或其中一張圖片。將 Map Tour 新增到 ArcGIS Online 圖庫後，將自動使用該圖片。"
      }
    },
    "share": {
      "firstSaveTitle": "已儲存導覽",
      "manageStory": "管理您的故事",
      "manageStoryA1": "提示: 您可以使用 %LINK1% 來檢查故事的錯誤及變更其分享方式，讓它在社交媒體等項目上呈現美觀的外觀。 深入瞭解我的故事 %LINK2%。",
      "manageStoryA1V1": "我的經驗",
      "manageStoryA1V2": "此處",
      "shareTitle": "分享您的導覽",
      "sharePrivateHeader": "您的導覽尚未分享，是否要分享?",
      "sharePrivateBtn1": "公開分享",
      "sharePrivateBtn2": "與我的組織分享",
      "sharePrivateProgress": "正在進行分享...",
      "sharePrivateErr": "分享失敗，請重試或",
      "sharePrivateOk": "分享已更新，正在載入...",
      "sharePreviewAsUser": "預覽",
      "shareHeader1": "您的導覽<strong>可公開存取</strong>。",
      "shareHeader2": "組織成員可以存取您的導覽(需要登錄)。",
      "shareLinkHeader": "分享您的導覽",
      "shareLinkOpen": "打開",
      "shareA1": "使用<a href='%LINK1%' target='_blank'>應用程式項目頁面</a>中的 %SHAREIMG%。如果還希望取消分享 Web 地圖，請使用 <a href='%LINK2%' target='_blank'>Web 地圖項目頁面</a>。",
      "shareWarning": "已禁止分享 %WITH%，因為您不是 <a href='%LINK%' target='_blank'>webmap</a> 的擁有者。",
      "shareWarningWith1": "公開",
      "shareWarningWith2": "公開並在組織內分享",
      "viewStory": "檢視故事"
    },
    "locator": {
      "error": "位置無法使用"
    },
    "saveErrorSocial": {
      "title": "社交媒體分享更新",
      "panel1": "您在社交媒體上的故事外觀已優化，但您的 ArcGIS Web 應用程式項目標題不同於您的故事標題。",
      "panel1tooltip": "藉由定義標題、摘要和縮圖圖片，您的故事外觀類似於：",
      "panel2": "您要在社交媒體上使用哪個標題:",
      "panel2q1": "故事標題（建議）",
      "panel2q1tooltip": "藉由選擇此選項，將修改您的項目標題來符合您的故事標題，並在將同步的建立器中進一步變更。",
      "panel2q2": "項目標題",
      "panel3": "要進一步優化您在社交媒體上的故事外觀，請使用 ${MYSTORIES} 以新增摘要和縮圖圖片。",
      "panel4": "請勿再針對此故事發出警告",
      "mystories": "我的經驗",
      "btnSave": "儲存"
    },
    "bannerNotification": {
      "learnMore": "瞭解詳細資訊",
      "close": "關閉",
      "dontShowAgain": "請勿再次顯示此訊息"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Web 安全性和 Story Maps 的相關重要資訊",
      "s1h1": "Esri 正在加強 Story Maps 的安全性",
      "s1p1": "您的 Story Maps 在 Web 上運作，且 Web 社群一直致力於建立和實施更好的安全機制。 為透過網際網路傳輸的內容提供安全連線的 HTTPS，正在成為存取 Web 內容的通行方式。 若是使用 HTTP 而非 HTTPS，現今大多數的瀏覽器都會顯示警告訊息。 基於此新興的標準，我們強烈建議您使用 HTTPS 連結來創作和分享 Story Maps，並在故事地圖的圖片中嵌入 Web 內容或連結時，僅使用 HTTPS URL。",
      "s1p2": "從實務而言，這表示故事地圖及其所有內容 (包含圖片、圖層、內嵌的應用程式和網站) 都必須使用以 HTTPS (而非 HTTP) 開頭的連結存取。 如此可確保為您的讀者提供最佳的體驗，因為大多數的 Web 瀏覽器都會指出您的故事是安全的。",
      "s2h1": "我需要執行哪些工作?",
      "s2p1": "Esri 正在努力使故事地圖的作者和讀者都能輕鬆進行此轉移。 故事地圖建立器和我的故事現在提供了工具，可協助您在故事中尋找不安全的內容 (HTTP)，並提供如何解決問題的建議。 請檢查您的故事是否有不安全的內容，並盡快更新為 HTTPS。",
      "action1": "關閉",
      "action2": "立即檢查我的故事",
      "action3": "瞭解詳細資訊"
    },
    "embedBar": {
      "share": "分享",
      "fullScreen": "全螢幕",
      "enlarge": "放大",
      "newTab": "在新頁籤中開啟",
      "tagline": "故事地圖",
      "exitFullScreen": "退出全螢幕"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "我們是否能詢問您一些事情? 它將有助於形塑 Story Maps 的願景。",
      "s1h1": "分享您的構想以形塑願景。",
      "s1p1": "您的意見是我們最重要且唯一的回饋來源，且盡可能獲得您的寶貴意見將有助於改善 Story Maps。 如果您能參加這個三分鐘的調查，我們將不勝感激。",
      "s2p1": "無論如何，非常感謝您使用 Esri Story Maps!",
      "action1": "關閉",
      "action2": "參與調查"
    },
    "licenseChange2018": {
      "noAccess": "您的帳號 (%USER_NAME%) 未經授權，無法開啟非公開的故事地圖。 請聯繫您的組織管理員，請其將包含 Story Maps 或附加元件基礎應用程式授權的使用者類型指派給您。"
    }
  }
});