define({
  "viewer": {
    "loading": {
      "step1": "MEMUAT CERITA",
      "step2": "MEMUAT DATA",
      "step3": "MENGINISIALISASI TUR",
      "loadBuilder": "BERALIH KE MODE PENYUSUN",
      "redirectSignIn": "MENGALIHKAN KE HALAMAN MASUK",
      "redirectSignIn2": "(Anda akan dialihkan ke sini setelah masuk)",
      "fail": "Maaf, gagal memuat Tur Peta",
      "failButton": "Coba lagi"
    },
    "errors": {
      "boxTitle": "Terjadi kesalahan",
      "portalSelf": "Kesalahan fatal: Gagal mendapatkan konfigurasi portal",
      "invalidConfig": "Kesalahan fatal: Konfigurasi tidak valid",
      "invalidConfigOwner": "Kesalahan fatal: Konfigurasi tidak valid (diperlukan pemilik resmi)",
      "invalidConfigNoWebmap": "Kesalahan fatal: Konfigurasi tidak valid (peta web atau pengenal aplikasi tidak ditentukan di index.html)",
      "invalidConfigNoAppDev": "Tidak ada pengenal Aplikasi Pemetaan Web atau peta web yang ditentukan di parameter URL (?appid= atau ?webmap=). Pada mode pengembangan, konfigurasi appid dan peta web di index.html diabaikan.",
      "createMap": "Tidak dapat membuat peta",
      "invalidApp": "Kesalahan fatal: Cerita tidak dapat dimuat",
      "noLayer": "Peta web tidak berisi lapisan data yang valid untuk Tur Peta.",
      "noLayerMobile": "Penyusun Tur Peta tidak didukung pada ukuran tampilan ini. Jika memungkinkan, ubah ukuran browser Anda untuk mengakses penyusun atau buat cerita Anda pada perangkat dengan layar yang lebih besar.",
      "noLayerMobile2": "Putar posisi perangkat Anda ke orientasi lanskap untuk menggunakan penyusun Tur Peta.",
      "noLayerView": "Selamat datang di aplikasi web Tur Peta.<br />Cerita belum dikonfigurasikan.",
      "appSave": "Kesalahan saat menyimpan cerita",
      "mapSave": "Kesalahan saat menyimpan peta web",
      "featureServiceLoad": "Kesalahan saat memuat layanan fitur",
      "notAuthorized": "Anda tidak diizinkan untuk mengakses cerita ini.",
      "notAuthorizedBuilder": "Anda tidak diizinkan untuk menggunakan penyusun Tur Peta.",
      "oldBrowserTitle": "Browser tidak didukung sepenuhnya",
      "noBuilderIE8": "Penyusun Tur Peta tidak didukung pada Internet Explorer sebelum versi 9.",
      "ie10Win7Explain": "Penyusun interaktif Tur Peta tidak didukung di Internet Explorer 10 pada Windows 7 saat sumber data merupakan Layanan Fitur dengan lampiran. Untuk menggunakan Layanan Fitur dengan lampiran, Anda harus menerapkan mode dokumen <a target='_blank' href='http://msdn.microsoft.com/en-us/perpustakaan/ie/hh920756(v=vs.85).aspx'>secara manual pada standar Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/Petunjuk-hapus-IE10-and-Get-Kembali-to-IE9-on-jendela-7-308998.shtml'>menurunkan menjadi Internet Explorer 9</a>, atau meningkatkan menjadi Windows 8.",
      "oldBrowserExplain": "Browser ini tidak mendukung pembuatan gambar mini otomatis dari gambar yang Anda unggah pada tur peta. Anda dapat membuat tur peta menggunakan browser ini, tetapi diharuskan untuk menyiapkan gambar tampilan mini terpisah untuk setiap gambar yang Anda unggah.",
      "oldBrowserExplain2": "Untuk meningkatkan pengalaman Anda, <a href='http://browsehappy.com/' target='_blank'> tingkatkan browser Anda</a> atau <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktifkan Bingkai Google Chrome untuk Internet Explorer</a>.",
      "oldBrowserExplain3": "Penyusun Tur Peta tidak berfungsi pada Internet Explorer 10 di Windows XP.",
      "oldBrowserClose": "Tutup",
      "noViewerIE2": "Anda mencoba melihat cerita ini menggunakan browser yang lama dan tidak didukung. Mungkin ada fitur yang tidak berfungsi atau masalah yang tidak terduga lainnya. Sebaiknya Anda memperbaruinya ke Internet Explorer 11 atau gunakan browser lain, seperti Chrome.",
      "noViewerIE3": "Di akhir 2017, cerita ini tidak akan dimuat lagi di browser ini. Pada saat itu, Anda harus menggunakan browser yang didukung untuk melihat cerita ini.",
      "attention": "Perhatian!"
    },
    "mobileHTML": {
      "showIntro": "TAMPILKAN JUDUL",
      "hideIntro": "SEMBUNYIKAN JUDUL",
      "navList": "Daftar",
      "navMap": "Peta",
      "navInfo": "Media",
      "introStartBtn": "Mulai"
    },
    "desktopHTML": {
      "storymapsText": "Peta cerita",
      "builderButton": "Pindah ke mode penyusun",
      "facebookTooltip": "Bagikan ke Facebook",
      "twitterTooltip": "Bagikan ke Twitter",
      "bitlyTooltip": "Dapatkan tautan pendek",
      "bitlyStartIndex": "Tautkan pada tempat saat ini",
      "tooltipAutoplayDisabled": "Tidak tersedia pada mode pemutaran otomatis",
      "autoplayLabel": "Mode pemutaran otomatis",
      "autoplayExplain1": "Mode pemutaran otomatis akan berputar seiring cerita Anda pada interval reguler. Interval ini ideal pada monitor layar kios atau publik, namun perlu diperhatikan bahwa dalam situasi lainnya, cerita mungkin akan lebih sulit dibaca. Fitur ini tidak didukung pada layar kecil.",
      "autoplayExplain2": "Saat mode ini aktif, ada beberapa kontrol untuk memutar/menjeda cerita dan mengatur kecepatan navigasi."
    },
    "builderHTML": {
      "panelHeader": "KONFIGURASI CERITA",
      "buttonSave": "SIMPAN",
      "buttonSettings": "Pengaturan",
      "buttonShare": "Bagikan",
      "buttonView": "Mode Tampilan",
      "buttonItem": "Buka item Aplikasi Web",
      "buttonHelp": "Bantuan",
      "buttonOrganize": "Atur",
      "buttonAdd": "Tambah",
      "buttonImport": "Impor",
      "buttonImportDisabled": "Impor tidak tersedia ketika menggunakan Layanan Fitur dengan lampiran",
      "dataEditionDisabled": "Mengedit data dinonaktifkan pada sumber data CSV ini",
      "dataSourceWarning": "Lapisan data Tur Peta telah berubah. Jika ID fitur tidak sama, Anda harus mengatur ulang pesanan dan poin tersembunyi melalui <b>Kelola</b>. Jika nama bidang berbeda, Anda harus mengatur ulang pengaturan bidang di bawah <b>tab data pada Pengaturan</b>.",
      "organizeWarning": "Satu atau beberapa poin yang ditambahkan di luar penyusun interaktif disembunyikan.",
      "dataPicError0a": "Tur ini mencakup URL gambar yang tidak sesuai dengan <b>%NB%</b>.",
      "dataPicError0b": "Tur ini dapat mencakup URL gambar yang tidak sesuai dengan <b>%NB%</b>.",
      "dataPicError1": "Tur Peta saat ini mengharuskan URL gambar diakhiri dengan salah satu ekstensi berikut: .jp(e)g, .png, .gif, atau .bmp.",
      "dataPicError2": "Persyaratan ini tidak akan memengaruhi Tur Peta yang sudah Anda terbitkan. Akan tetapi, untuk menggunakan penyusun interaktif, Anda harus menyelesaikan masalah URL terlebih dahulu dengan melakukan salah satu dari dua tindakan:",
      "dataPicError3": "Edit URL",
      "dataPicError4": "Ini akan menambahkan <i>#isImage</i> pada akhir URL gambar yang tidak didukung. Kebanyakan server mendukung pelengkap URL. Tetapi, sekali melakukan tindakan itu, Anda harus memastikan bahwa URL gambar yang diperbarui berfungsi dengan menavigasikan poin Anda. Jika setiap gambar dimuat, Anda dapat menyimpan Tur Peta sekarang. Jika <b>gambar rusak, jangan menyimpan Tur Peta</b>. Sebagai gantinya, muat ulang penyusun dan lakukan tindakan kedua.",
      "dataPicError5": "Batasi tur pada gambar",
      "dataPicError6": "Opsi ini menyebabkan semua URL dianggap sebagai gambar, tetapi Anda tidak akan dapat menambahkan video menggunakan penyusun interaktif. Tindakan ini dapat dibatalkan, jika Anda memutuskan untuk menambahkan video ini di kemudian hari.",
      "dataPicError7": "Tur Peta Anda telah dibatasi pada gambar, video tidak dapat digunakan. Jika memilih untuk menghapus batasan tersebut, pastikan gambar Anda masih dimuat dengan benar sebelum menyimpan Tur Peta. Anda akan dapat memulihkan batasan tersebut nantinya, jika diperlukan.",
      "dataPicError8": "Hapus batasan gambar",
      "dataPicError9": "Jika URL ini mengarah ke video, Anda dapat mengabaikan peringatan ini, jika mengarah pada gambar, Anda perlu melakukan salah satu dari dua tindakan berikut:",
      "modalCancel": "Batal",
      "modalApply": "Terapkan",
      "organizeHeader": "Kelola Tur",
      "organizeGeneralCaption": "Gunakan seret and lepaskan untuk mengurutkan poin tur",
      "organizeDelete": "Hapus",
      "organizeHide": "Sembunyikan",
      "organizeReset": "Atur ulang urutan dan poin tersembunyi.",
      "addMaxPointReached": "Jika Anda telah mencapai jumlah poin maksimum yang diperbolehkan menurut rangkaian ikon dan tidak dapat menambahkan poin tur lain.<br /><br />Perhatikan bahwa jika menghapus poin yang ada, Anda harus memuat ulang cerita.",
      "addMaxPointReachedMobile": "Maaf, Anda telah mencapai jumlah maksimal poin yang diperbolehkan dan tidak dapat menambahkan gambar tersebut.",
      "addClose": "Tutup",
      "addHeader": "Tambah poin tur baru",
      "addTabPicture": "Media",
      "addTabInformation": "Informasi",
      "addTabLocation": "Lokasi",
      "addSelectCaption": "Pilih atau lepaskan gambar",
      "addNoteVideo": "Hubungi Bantuan untuk mendapatkan petunjuk terkait penggunaan video",
      "addSelectCaptionNoFileReader": "Pilih gambar",
      "addChangePhoto": "Ubah gambar dan gambar mini",
      "addPictureResolutionIntro": "Resolusi gambar lebih tinggi dari yang diperlukan:",
      "addPictureResolutionOldBrowser": "Resolusi gambar lebih tinggi dari yang diperlukan. Opimalkan pengalaman Tur Peta dengan menentukan resolusi yang lebih rendah dari %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Ubah resolusi gambar menjadi %RESOLUTION%",
      "addPictureResolutionKeep": "Pertahankan resolusi asli %RESOLUTION%",
      "addSelectThumbnail": "Pilih gambar mini",
      "addNoThumbSelected": "Tidak ada gambar mini yang dipilih",
      "addThumbSelected": "Terpilih",
      "addCameraSettingsHeader": "PENGATURAN KAMERA",
      "addThumbnailHeader": "GAMBAR MINI",
      "addLabelPicUrl": "Gambar",
      "addLabelThumbUrl": "Gambar mini",
      "addTextPlaceholderUrl": "Masukkan URL gambar",
      "addTextPlaceholderUrl2": "Masukkan URL halaman YouTube",
      "addTextPlaceholderUrl3": "Masukkan URL halaman Vimeo",
      "addTextPlaceholderUrl4": "Masukkan URL yang disematkan untuk video",
      "addLabelVideo": "Video",
      "addMediaVideoOther": "Lainnya",
      "addMediaVideoHelp": "Periksa URL dan dapatkan gambar mini default",
      "addMediaVideoHelpTooltip1": "Pemeriksaan berhasil",
      "addMediaVideoHelpTooltip2": "Pemeriksaan gagal",
      "addMediaVideoHelpTooltip4": "Temukan opsi untuk menyematkan video dan salin URL video yang disajikan dalam kode",
      "addLabelName": "Nama",
      "addLabelDescription": "Keterangan",
      "addTextPlaceholder": "Ketik sesuatu",
      "addLocatePlaceholder": "Temukan alamat atau tempat",
      "addPinColor": "Warna",
      "addLatitude": "Garis Lintang",
      "addLongitude": "Garis Bujur",
      "addLatitudePlaceholder": "mis. 34,056",
      "addLongitudePlaceholder": "mis. -117,195",
      "addUploading": "Mengunggah poin tur",
      "addSave": "Tambah poin tur",
      "addMobileUploading": "Mengunggah gambar",
      "addMobileName": "Masukkan nama",
      "addMobileNameMandatory": "Kesalahan, masukkan nama.",
      "addMobileError": "Maaf, ada yang tidak beres",
      "settingsHeader": "Pengaturan cerita",
      "settingsTabLayout": "Tata letak",
      "settingsTabColor": "Warna",
      "settingsTabLogo": "Header",
      "settingsTabFields": "Data",
      "settingsTabExtent": "Jangkauan",
      "settingsTabZoom": "Tingkat Zoom",
      "settingsLayoutExplain": "Pilih tata letak yang Anda inginkan.",
      "settingsLayoutProfessional": "Tata Letak Tiga Panel",
      "settingsLayoutModern": "Tata Letak Terintegrasi",
      "settingsLayoutSelected": "Tata letak terpilih",
      "settingsLayoutSelect": "Pilih tata letak ini",
      "settingsLayoutNote": "Perhatikan bahwa pada poin yang menggunakan video, plakat akan selalu ditempatkan di bawah video, meskipun opsi tersebut tidak dicentang.",
      "settingsLayoutLocBtn": "Tampilkan tombol 'Temukan'",
      "settingsLayoutLocBtnHelp": "Didukung di sebagian besar browser. Hanya muncul ketika peta cerita diakses melalui HTTPS. Tidak akan muncul jika cerita disematkan.",
      "settingsColorExplain": "Ubah tampilan dengan memilih tema yang telah ditetapkan, atau buat tema Anda sendiri.",
      "settingsLabelColor": "Warna header, konten, and catatan kaki",
      "settingsLogoExplain": "Sesuaikan logo header (maksimum 250 x 50 px).",
      "settingsLogoEsri": "Logo Esri",
      "settingsLogoNone": "Tanpa logo",
      "settingsLogoCustom": "Logo kustom",
      "settingsLogoCustomPlaceholder": "URL gambar",
      "settingsLogoCustomTargetPlaceholder": "Tautan klik tayang",
      "settingsLogoSocialExplain": "Sesuaikan tautan kanan atas header.",
      "settingsLogoSocialText": "Teks",
      "settingsLogoSocialLink": "Tautan",
      "settingsLogoSocialDisabled": "Fitur ini telah dinonaktifkan oleh Administrator",
      "settingsDataFieldsExplain": "Pilih nama foto, keterangan, dan bidang warna.",
      "settingsDataFieldsError": "Aplikasi tidak dapat menentukan nama, keterangan, atau data warna yang sesuai. Pilih bidang yang akan digunakan di sini. Pengaturan ini dapat diubah di kemudian hari.",
      "settingsFieldsLabelName": "Nama",
      "settingsFieldsLabelDescription": "Keterangan",
      "settingsFieldsLabelColor": "Warna",
      "settingsFieldsReset": "Atur ulang pemilihan bidang",
      "settingsExtentExplain": "Atur jangkauan awal Tur Peta melalui peta interaktif di bawah.",
      "settingsExtentExplainBottom": "Jangkauan yang Anda tetapkan akan mengubah jangkauan awal peta web. Perhatikan bahwa jangkauan ini tidak digunakan jika tidak mencakup poin tur pertama. Dalam kasus tersebut, tur akan dibuka di bagian tengah pada poin pertama.",
      "settingsExtentDateLineError": "Jangkauan tidak dapat melintasi meridian garis bujur 180Â°",
      "settingsExtentDateLineError2": "Kesalahan saat menghitung jangkauan",
      "settingsExtentDrawBtn": "Gambar jangkauan baru",
      "settingsExtentModifyBtn": "Edit jangkauan",
      "settingsExtentApplyBtn": "Pratinjau pada Tur Peta",
      "settingsExtentUseMainMap": "Gunakan jangkauan Tur Peta",
      "settingsZoomExplain": "Atur zoom untuk poin cerita yang mengikuti pengantar (opsional).",
      "settingsLabelZoom": "Skala/tingkat",
      "settingsZoomFirstValue": "Tidak ada",
      "settingsFieldError": "Pilih bidang pada setiap daftar",
      "dataTitle": "Buat lapisan Tur Peta di-host",
      "dataExplain": "Lapisan Fitur baru akan dibuat untuk poin gambar dan tur Anda. Lapisan tur tidak akan dibagikan dengan siapa pun kecuali jika Anda berbagi Tur Peta.",
      "dataExplainPortal": "Fitur ini membutuhkan Portal untuk ArcGIS 10.4. Jika Anda tidak berhasil membuat Lapisan Fitur, hubungi administrator ArcGIS Anda.",
      "dataNameLbl": "Nama lapisan",
      "dataFolderListLbl": "Folder",
      "dataFolderListFetching": "Mengambil folder ...",
      "dataRootFolder": "Akar",
      "dataNameError": "Masukkan nama untuk layanan fitur",
      "dataFolderError": "Pilih folder yang valid",
      "dataSrcContainsInvalidChar": "Nama layanan fitur berisi satu atau beberapa karakter yang tidak valid (-, <, >, #, %, :, \", ?, &, +, /, atau ).",
      "dataSrvAlreadyExistsError": "Layanan dengan nama tersebut sudah ada di dalam organisasi. Pilih nama yang berbeda.",
      "dataBtnSave": "Buat lapisan",
      "dataFooterProgress": "Pembuatan dalam proses",
      "dataFooterSucceed": "Pembuatan berhasil. Memuat",
      "dataFooterError": "Pembuatan gagal. Silahkan coba lagi",
      "tabError": "Periksa kesalahan pada semua tab",
      "introRecordBtn": "Pendahuluan",
      "introRecordActivate": "Gunakan poin pertama sebagai pendahuluan (tidak muncul pada korsel)"
    },
    "addPopupJS": {
      "uploadingPicture": "Mengunggah gambar",
      "uploadSuccess": "Pengunggahan berhasil",
      "uploadError": "Kesalahan saat mengunggah gambar",
      "uploadError2": "Kesalahan saat menambahkan fitur (tag html tidak valid)",
      "notJpg": "Pilih foto jpeg untuk diunggah",
      "errorNoPhoto": "Pilih gambar untuk diunggah",
      "errorNoThumbnail": "Pilih gambar mini untuk diunggah",
      "errorInvalidPicUrl": "Masukkan gambar yang valid (dimulai dengan http(s)://, diakhiri dengan jpg, png, gif, atau bmp). Anda dapat mengakhiri URL dengan: '#isImage' untuk menimpa aturan tersebut.",
      "errorInvalidThumbUrl": "Masukkan gambar mini yang valid (dimulai dengan http(s)://, diakhiri dengan jpg, png, gif, atau bmp).",
      "errorInvalidVideoUrl": "Masukkan URL video yang valid (dimulai dengan http(s)://)",
      "errorNoName": "Masukkan nama untuk poin tur ini",
      "errorNoDescription": "Masukkan keterangan untuk poin tur ini",
      "errorNoLocation": "Masukkan lokasi untuk poin tur ini"
    },
    "builderJS": {
      "noPendingChange": "Semua perubahan telah disimpan",
      "unSavedChangeSingular": "1 perubahan belum disimpan",
      "unSavedChangePlural": "perubahan belum disimpan",
      "shareStatus1": "Tur tidak disimpan",
      "shareStatus2": "Tour dibagikan secara publik",
      "shareStatus3": "Tur dibagikan di dalam organisasi",
      "shareStatus4": "Tur tidak dibagikan",
      "popoverDiscard": "Anda yakin ingin membuang perubahan yang belum disimpan?",
      "yes": "Ya",
      "no": "Tidak",
      "popoverLoseSave": "Dengan membuka penampil, Anda akan membuang semua perubahan yang belum disimpan",
      "ok": "Oke",
      "popoverSaveWhenDone": "Jangan lupa menyimpan saat Anda telah selesai",
      "closeWithPendingChange": "Anda yakin ingin mengonfirmasi tindakan ini? Perubahan Anda akan hilang.",
      "gotIt": "Oke",
      "savingApplication": "Menyimpan cerita",
      "saveSuccess": "Cerita disimpan",
      "saveError": "Gagal menyimpan. Harap coba lagi.",
      "saveError2": "Penyimpanan gagal karena tag html pada nama atau deskripsi tidak valid",
      "saveError3": "Judul tidak boleh kosong",
      "dragColorPicker": "Ubah lokasi saya<br />atau ubah warna saya",
      "dataWarningExtent": "Anda memiliki data di luar jangkauan peta web. Data tersebut tidak akan digunakan sebagai poin tur, ubah jangkauan peta jika Anda ingin menggunakannya.",
      "dataWarningVisibi": "Lapisan Tur Peta Anda tidak terlihat pada jangkauan peta web saat ini. Pastikan lapisan Tur Peta Anda terlihat dengan peta besar %MAPSIZE%.",
      "dataWarningEdit": "Edit peta web",
      "dataWarningClose": "Tutup",
      "signIn": "Harap masuk dengan akun di",
      "signInTwo": "untuk menyimpan cerita.",
      "switchBM": "Ubah Peta Dasar"
    },
    "organizePopupJS": {
      "messageStart": "Anda telah memilih untuk hapus",
      "messageSinglePoint": "satu poin tur",
      "messageMultiPoint": "lokasi tur",
      "messagePermantRemove": "Ini secara permanen akan menghapus",
      "messageRecord": "rekaman",
      "messageRecordPlural": "rekaman",
      "messageConfirm": "dari database Anda. Ingin melanjutkan?",
      "labelButtonShow": "Tampilkan",
      "labelButtonHide": "Sembunyikan"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Ini akan menghapus gambar dan gambar mini secara permanen",
      "popoverDeleteWarningThumb": "Ini akan menghapus gambar mini secara permanen",
      "popoverUploadingPhoto": "Mengunggah gambar and gambar mini",
      "popoverUploadingThumbnail": "Mengunggah gambar mini",
      "popoverUploadSuccessful": "Pengunggahan berhasil",
      "popoverUploadError": "Pengunggahan gagal, coba lagi",
      "changePicAndThumb": "Ubah gambar",
      "changeThumb": "Ubah gambar mini",
      "selectPic": "Ubah media",
      "selectThumb": "Ubah gambar mini",
      "uploadPicAndThumb": "Terapkan"
    },
    "headerJS": {
      "editMe": "Edit saya!",
      "templateTitle": "Tentukan judul templat",
      "templateSubtitle": "Tentukan subjudul pola dasar"
    },
    "crossFaderJS": {
      "setPicture": "Atur judul gambar",
      "setCaption": "Atur keterangan gambar"
    },
    "importPopup": {
      "title": "Impor",
      "prevBtn": "Kembali",
      "nextBtn": "Berikutnya"
    },
    "importPopupHome": {
      "header": "Di mana gambar Anda disimpan?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "gambar",
      "videos": "video",
      "disabled": "Fitur ini telah dinonaktifkan oleh Administrator",
      "disabledPortal": "Fitur ini mensyaratkan portal memiliki server hosting. Hubungi Administrator Portal untuk ArcGIS Anda.",
      "header1": "Gambar Anda akan dibagikan secara publik.",
      "header2": "Impor akan dibatasi pada %NB1% %MEDIA% pertama.",
      "emptyDataset": "Kesalahan, tidak ditemukan gambar",
      "footerImport": "Impor",
      "selectAlbum": "Pilih album publik",
      "selectAlbum2": "Pilih album",
      "pleaseChoose": "Silahkan Pilih",
      "userLookup": "Cari",
      "userLookingup": "Mencari",
      "csv": "Dirujuk pada CSV",
      "advanced": "Opsi lanjutan",
      "advancedScratchLbl": "Mulai Tur baru",
      "advancedScratchTip": "Buat Tur kosong yang akan dapat Anda tempati secara manual menggunakan wizard.",
      "advancedCSVLbl": "Impor data Tur dari file CSV",
      "advancedCSVTip": "Impor konten Tur dari file CSV.",
      "advancedCommonTip": "Hal itu mengharuskan gambar dan video Anda untuk online.",
      "select": "Buat pilihan",
      "locUse": "Gunakan geolokasi gambar",
      "locExplain": "Anda mungkin tidak ingin menggunakan lokasi gambar karena dapat diwariskan dari album, sehingga semua foto berada di lokasi yang sama.",
      "locExplain2": "Anda mungkin tidak ingin menggunakan lokasi video karena dapat diwariskan dari pengaturan pengguna, sehingga semua video berada di lokasi yang sama."
    },
    "viewFlickr": {
      "title": "Impor Flickr",
      "header": "Masukkan nama pengguna Flickr dan pilih Rangkaian Foto atau Tag yang akan diimpor.",
      "userInputLbl": "Masukkan Nama Pengguna",
      "signInMsg2": "Pengguna tidak ditemukan",
      "selectSet": "Pilih Rangkaian Foto",
      "selectTag": "atau Pilih Tag",
      "footerImportTag": "Impor Tag terpilih",
      "footerImportSet": "Impor Rangkaian terpilih"
    },
    "viewFacebook": {
      "title": "Impor Facebook",
      "header": "Pengesahan dengan Akun Pengguna Facebook atau gunakan Halaman Publik. Album pribadi dapat digunakan untuk membuat Tur Peta publik yang tidak membutuhkan pengesahan pengguna Facebook, yang memungkinkan komentar dan suka untuk tetap bersifat pribadi.",
      "leftHeader": "Pengguna Facebook",
      "rightHeader": "Halaman Facebook",
      "pageExplain": "Halaman Facebook seperti produk/merek publik atau selebriti seperti <b>esrigis</b>. Anda bisa mendapatkan nama halaman setelah '/' pertama di URL halaman.",
      "pageInputLbl": "Masukkan nama halaman",
      "lookupMsgError": "Halaman tidak ditemukan"
    },
    "viewPicasa": {
      "title": "Impor Picasa",
      "header": "Masukkan alamat email atau id Picasa Anda.",
      "userInputLbl": "Email atau id Picasa",
      "signInMsg2": "Akun tidak ditemukan",
      "signInMsg3": "Bukan album publik",
      "howToFind": "Cara menemukan id Picasa",
      "howToFind2": "Salin angka di antara '/' pertama dan kedua dari halaman Picasa mana saja"
    },
    "viewCSV": {
      "title": "Impor CSV",
      "uploadBtn": "Pilih atau lepaskan file CSV",
      "resultHeaderEmpty": "CSV kosong",
      "resultHeaderSuccess": "Muat poin %NB_POINTS%",
      "resultHasBeenLimited": "Impor telah dibatasi pada %VAL1% pertama yang menunjukkan %VAL2% untuk mematuhi batasan poin %VAL3% per tur",
      "browserSupport": "Browser Anda tidak didukung, untuk menggunakan CSV, Anda harus <a href='http://browsehappy.com/' target='_blank'>meningkatkan browser</a> atau menggunakan penampil peta web ArcGIS.com (lihat Bantuan).",
      "errorLatLng": "Bidang Garis Lintang dan Garis Bujur tidak ditemukan. Kemungkinan nilai untuk Garis Lintang adalah: <i>%LAT%</i> dan untuk Garis Bujur adalah: <i>%LONG%</i>.",
      "errorFieldsExplain": "Pemuatan gagal karena bidang yang dibutuhkan berikut tidak ditemukan",
      "errorFieldsName": "<b>Nama</b> nilai yang memungkinkan adalah: %VAL%",
      "errorFieldsDesc": "<b>Deskripsi</b> nilai yang memungkinkan adalah: %VAL%",
      "errorFieldsUrl": "<b>URL Gambar</b> nilai yang memungkinkan adalah: %VAL%",
      "errorFieldsThumb": "<b>URL Gambar Kecil</b> nilai yang memungkinkan adalah: %VAL%",
      "errorFields2Explain": "Gagal memuat karena CSV tidak menggunakan atribut yang sama dengan lapisan untuk atribut berikut.",
      "errorFields2Name": "<b>Nama</b> gunakan %VAL1%, bukan %VAL2%",
      "errorFields2Desc": "<b>Deskripsi</b> gunakan %VAL1%, bukan %VAL2%",
      "errorFields2Url": "<b>URL Gambar</b> gunakan %VAL1%, bukan %VAL2%",
      "errorFields2Thumb": "<b>URL Gambar Mini</b> gunakan %VAL1%, bukan %VAL2%",
      "resultFieldsAll": "Semua atribut telah diimpor",
      "resultFieldsNotAll": "Atribut berikut tidak diimpor karena tidak ada pada lapisan peta",
      "resultFieldsNotAll2": "Atribut berikut telah diimpor",
      "footerNextBtnResult": "Impor ke dalam peta web",
      "footerProgress": "Impor dalam proses",
      "footerSucceed": "Impor sukses. Memuat"
    },
    "viewYoutube": {
      "title": "Impor YouTube",
      "header": "Masukkan nama pengguna YouTube untuk memukan video yang dibagikan secara publik.",
      "pageInputLbl": "Masukkan nama pengguna YouTube",
      "lookupMsgError": "Pengguna tidak ditemukan",
      "howToFind": "Cara menemukan nama pengguna YouTube",
      "howToFind2": "Nama pengguna ditampilkan di bawah video",
      "found": "Ditemukan",
      "noData": "Video publik tidak ditemukan"
    },
    "viewGeoTag": {
      "title": "Pilih dan temukan gambar/video",
      "header": "Klik atau ketuk gambar yang ingin Anda impor untuk menemukannya.",
      "headerMore": "Mengapa gambar/video saya tidak tergeolokasi?",
      "headerExplain": "Jika gambar Anda memiliki geolokasi yang valid, gambar tersebut secara otomatis akan ditemukan pada peta dan didaftarkan pada tab kedua.<br /><br />Secara default, Picasa dan Flickr tidak menyimpan metadata EXIF geolokasi ketika Anda mengimpor gambar. Periksa pengaturan pribadi Picasa/Flickr untuk mengaktifkan impor dan penggunaan geolokasi gambar oleh aplikasi eksternal. Anda mungkin harus mengimpor ulang gambar yang ada ke dalam Flickr/Picasa untuk geolokasi EXIF yang akan digunakan.<br /><br />Pada Facebook, Anda harus masuk ke setiap gambar, mengeklik Edit, dan memilih lokasi.",
      "leftPanelTab1": "Untuk menemukan",
      "leftPanelTab2": "Ditemukan",
      "clickOrTap": "Klik atau ketuk Peta untuk menemukan",
      "clearLoc": "Bersihkan lokasi",
      "clickDrop": "Jangan mengimpor",
      "footerImport": "Impor",
      "footerProgress": "Impor dalam proses",
      "footerSucceed": "Impor sukses. Memuat...",
      "loading": "Memuat",
      "error": "Gagal mengimpor geolokasi gambar, geolokasi diabaikan."
    },
    "initPopup": {
      "title": "Selamat datang di Penyusun Tur Peta",
      "prevBtn": "Kembali",
      "nextBtn": "Berikutnya"
    },
    "initPopupHome": {
      "header1": "Di mana gambar atau video Anda?",
      "header2": "Bantuan ini akan membantu Anda membuat Tur Peta dari media yang disimpan secara online atau akan mengimpornya ke dalam ArcGIS Online Anda untuk akun Organisasi.",
      "title1": "Gambar atau video sudah online",
      "title2": "Saya perlu mengunggah gambar.",
      "hostedFSTooltip": "Unggah gambar Anda dan simpan dengan lapisan Tur Peta (tidak mendukung video).",
      "hostedFsNA": "Anda harus menjadi Penerbit atau memiliki peran lain dengan hak istimewa untuk menerbitkan Lapisan Fitur di-host. Hubungi administrator ArcGIS.",
      "hostedFsNA2": "Hanya tersedia dengan langganan ArcGIS Daring. <a href='%LINK%'>Daftar untuk coba gratis</a>",
      "footer1": "Jika telah selesai, jangan lupa untuk membagikan Tur Peta Anda kepada audiens melalui halaman item aplikasi.",
      "footer3": "Unduh pola dasar CSV",
      "footer4": "\"Simpan sebagai\" jika tidak terunduh",
      "footer4bis": "Gunakan klik kanan dan \"Simpan sebagai\" jika unduhan tidak dimulai",
      "footer5": "Pelajari selengkapnya",
      "footerProgress": "Pembuatan dalam proses",
      "footerSucceed": "Pembuatan berhasil. Memuat..."
    },
    "helpPopup": {
      "title": "Bantuan",
      "close": "Tutup",
      "tab1": {
        "title": "Perkenalan",
        "div1": "Pola dasar Tur Peta dirancang untuk menyajikan informasi geografis ketika ada elemen fotografi atau media yang menarik pada cerita yang akan Anda ceritakan.",
        "div2": "Pola dasar menghasilkan aplikasi web interaktif dan mudah digunakan yang memungkinkan Anda menyajikan rangkaian tempat kecil pada peta di urutan bernomor yang dapat ditelusuri pengguna. Pola dasar ini dirancang untuk digunakan di semua browser web pada semua perangkat, termasuk smartphone dan tablet. <br /><br />",
        "div42": "Untuk melihat contoh tur peta yang dibuat pengguna lain, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>kunjungi galeri</a> pada <a href='http://storymaps.arcgis.com/' target='_blank'>situs web Peta Cerita</a>. Anda juga dapat mengikuti kami di Twitter <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Kami ingin mendengar dari Anda! Apakah Anda memiliki pertanyaan, ingin meminta fitur baru, atau merasa menemukan bug, silakan kunjungi <a href='http://links.esri.com/storymaps/forum' target='_blank'>Forum Pengguna Peta Cerita</a>."
      },
      "tab2": {
        "title": "Data",
        "div1": "Elemen utama yang harus dipertimbangkan ketika membuat Tur Peta adalah memilih tempat untuk menyimpan gambar. Tur Peta dapat menggunakan gambar yang disimpan di layanan berbagi foto utama, di semua server web, atau sebagai lampiran pada layanan fitur.",
        "div1a": "Lihat bagian terakhir pada tab ini untuk mengetahui detail tentang format gambar dan video yang didukung.",
        "div2": "Penyusun interaktif memberikan Anda dua opsi untuk menangani gambar di Tur Peta:",
        "div3": "<ul><li>Anda dapat menggunakan <b>foto yang sudah online</b>, seperti gambar yang disimpan di situs berbagi foto seperti Flickr, atau gambar yang disimpan di situs web Anda sendiri. Gambar ini akan dirujuk pada Tur Peta Anda melalui URL-nya.</li><li>Anda juga dapat <b>mengunggah foto dari komputer</b> secara langsung ke Tur Peta Anda. Opsi unggah ini mengharuskan Anda memiliki ArcGIS untuk akun Organisasi dan memiliki hak istimewa Administrator atau Penerbit, karena layanan fitur di-host secara otomatis dibuat untuk Anda yang mana foto Anda disimpan sebagai lampiran.</li></ul>",
        "div4": "Kasus penggunaan utama adalah:",
        "div4b": "<b>Foto Anda belum di-host</b> dan Anda memiliki ArcGIS untuk akun Organisasi: Menggunakan layanan fitur di-host adalah pilihan terbaik. Seperti layanan berbagi foto publik, kami akan mengoptimasi gambar untuk menciptakan gambar yang dimuat cepat dan Anda akan memiliki akses ke semua kemampuan administrasi dan menajemen data dari platform ArcGIS.",
        "div5": "<b>Anda bukan anggota Organisasi</b>: Pertama-tama Anda harus mengunggah gambar pada situs web berbagi foto atau ke server web Anda sendiri. Penyusun akan membantu Anda menggunakan gambar ini yang akan terus di-host pada lokasi aslinya.",
        "div6": "<b>Anda sepertinya akan menggunakan ulang Layanan Fitur saat ini</b> yang menyimpan gambar sebagai lampiran atau gambar referensi eksternal: Lihat bagian rincian di bawah.",
        "div7": "<b>Anda merupakan pengguna versi sebelumnya</b> dari pola dasar Tur Peta dan telah memiliki CSV yang merujuk gambar pada dan gambar mini: Anda akan dapat mengimpornya dan memperbaiki data. Penyusun hanya mendukung CSV yang menggunakan bidang lat/long; CVS berbasis alamat dapat terus digunakan melalui peta web (lihat bagian di bawah).",
        "div8": "Mengimpor dari layanan berbagi foto online",
        "div9a": "Dukungan untuk Facebook telah dihentikan, ${learn}.",
        "learn": "pelajari selengkapnya",
        "div9": "Operasi impor merujuk pada gambar yang telah di-host dengan menyimpan URLnya di koleksi fitur peta web. Gambar tidak disimpan pada ArcGIS Daring. Jika gambar yang di-host tidak dapat diakses, gambar tidak akan tersedia di Tur Peta dan Anda akan melihat citra \"Gambar tidak tersedia\". Bergantung pada penyedia layanan foto Anda, Tur Peta mungkin tidak mengimpor nama, deskripsi, dan lokasi gambar. Atribut tersebut disimpan pada peta web dan semua editan pada layanan online tidak akan tercermin di Tur Peta.",
        "div10": "Menyimpan foto di server web",
        "div11": "Jika memilih untuk meng-host gambar sendiri, Anda diharuskan untuk membuat gambar mini dari foto Anda secara manual. Menggunakan gambar beresolusi penuh untuk gambar mini akan menghasilkan kinerja yang buruk. Oleh karena itu, kami sangat menyarankan Anda untuk menggunakan layanan berbagi foto online atau feature service yang akan melakukan hal itu untuk Anda.",
        "div12": "Menggunakan Layanan Fitur atau Shapefile yang ada",
        "div13": "Setiap layanan fitur poin atau shapefile dapat digunakan sebagai sumber data Tur Peta. Anda hanya perlu menambahkannya sebagai lapisan ke dalam peta web melalui Penampil Web arcgis.com. Jika aplikasi menemui atribut yang diharapkan pada lapisan Anda, semua fungsi penyusun akan tersedia.",
        "div14": "Nilai yang memungkinkan untuk bidang nama adalah (tidak sensitif huruf besar dan kecil):",
        "div151": "Nama",
        "div152": "Deskripsi",
        "div153": "Gambar",
        "div154": "Gambar mini",
        "div155": "Warna ",
        "div16": "Jika aplikasi tidak menemukan bidang yang cocok ketika menggunakan layanan fitur, penampil tidak akan berfungsi sebelum Anda mengonfigurasi bidang yang digunakan melalui penyusun. Lapisan CSV dan shapefile yang ditambahkan pada peta web mengharuskan adanya semua bidang yang dibutuhkan atau penyusun tidak akan berfungsi.",
        "div162": "Ketika menggunakan layanan fitur yang menyimpan gambar sebagai lampiran, <b>hanya fitur dengan dua lampiran yang akan digunakan.</b>. Lampiran pertama menentukan gambar utama, dan lampiran kedua menentukan gambar mini.",
        "div17": "Bidang gambar dan gambar mini adalah hal wajib untuk layanan fitur tanpa lampiran dan opsional (tapi sangat disarankan) untuk layanan fitur dengan lampiran. Jika layanan Anda memiliki lampiran aktif, penyusun akan mengizinkan Anda untuk mengunggah gambar sebagai lampiran. Jika tidak, Anda hanya akan dapat mengedit URL gambar dan gambar mini.",
        "div172": "Jika ada, bidang foto dan gambar mini akan selalu digunakan dan lampiran layanan fitur tidak akan ditanyakan.",
        "div173": "Contoh CSV dan shapefile dapat diunduh dari",
        "div18": "Membuat Layanan Fitur di-host dari CSV atau shapefile",
        "div19": "Jika Anda membuat layanan fitur di-host dari CSV atau shapefile, lampiran tidak akan diaktifkan secara default. Untuk mengaktifkannya, buka halaman rincian layanan fitur, klik panah kecil pada bagian lapisan, dan Anda akan melihat opsi tersebut. Tur Peta akan terus menggunakan gambar dan gambar mini yang sudah Anda rujuk melalui atribut. Atau, jika ingin mengunggah gambar sebagai lampiran layanan fitur, Anda dapat melakukannya melalui dua tombol pada panel gambar (\"Ubah Gambar\" dan \"Ubah Gambar Mini\").",
        "div20": "Format gambar dan video yang didukung.",
        "div21": "Format gambar yang didukung adalah: <b>.jpg, .jpeg, .png, .gif, dan .bmp</b>. Jika media Anda tidak diakhiri dengan ekstensi tersebut, Tur Peta akan menganggapnya sebagai video, kecuali jika menggunakan layanan fitur (lihat di bawah).",
        "div22": "Pola dasar Tur Peta tidak mencakup pemutar video, jadi Anda harus menggunakan pemutar video eksternal yang disediakan oleh layanan hosting video favorit Anda (temukan opsi untuk menyematkan video dan salin URL yang disajikan pada kode yang diberikan). Jika ingin meng-host video sendiri, Anda dapat membuat halaman HTML yang berisi pemutar video seperti <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Penyusun interaktif tidak menyediakan dialog untuk menyertakan video jika menggunakan layanan fitur dengan lampiran, tetapi hal itu dapat dilakukan dengan mengedit data di luar penyusun interaktif. Pada penampil peta arcgis.com, jika Anda memodifikasi bidang gambar untuk mengarahkan pada video eksternal dan menambahkan parameter spesial di akhir URL (#isVideo), media Anda akan dianggap sebagai video.",
        "div24": "Perhatikan bahwa Anda masih harus memiliki dua lampiran foto yang valid atau poin tidak akan digunakan. Anda tidak dapat menggunakan video ketika menggunakan lampiran layanan fitur tanpa bidang gambar dan gambar mini."
      },
      "tab3": {
        "title": "Penyesuaian",
        "div1": "Penyusun memberikan beberapa opsi penyesuaian yang dapat diakses melalui tombol PENGATURAN di panel atas. Jika Anda tidak menemukan opsi yang diharapkan, kami juga menyediakan versi terunduh yang dapat Anda sebarkan pada server web dan tingkatkan sesuai dengan kebutuhan.",
        "div2": "Kami menyarankan Anda untuk menggunakan versi di-host, kecuali:",
        "div3": "<li>Penyusun tidak menawarkan penyesuaian UI yang ingin Anda miliki, seperti menggunakan gambar latar belakang header.</li><li>Anda adalah pengembang dan ingin meningkatkan aplikasi.</li>",
        "div4": "Versi yang dapat diunduh dapat dikonfigurasi melalui peta web atau pengenal aplikasi pemetaan web. Kasus penggunaan utamanya adalah:",
        "div41": "Anda membuat tur peta menggunakan penyusun interaktif pada lingkungan di-host dan mengonfigurasi pola dasar dengan pengenal aplikasi pemetaan web. Pengaturan yang telah Anda tentukan dengan penyusun interaktif akan diterapkan.",
        "div42": "Anda membuat peta web di luar penyusun interaktif dan mengonfigurasi pola dasar dengan pengenal peta web. Anda harus membaca dokumentasi untuk mempelajari cara mengonfigurasi pola dasar.",
        "div43": "Perhatikan bahwa penyusun interaktif tersedia di versi yang dapat diunduh, tetapi dengan beberapa batasan teknis pada browser seperti Internet Explorer versi di bawah 10.",
        "div5": "Untuk mengunduh versi pola dasar terbaru dan mempelajari lebih lanjut tentang cara menggunakannya, kunjungi <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>Halaman proyeksi GitHub</a>."
      },
      "tab4": {
        "title": "Tip",
        "div0": "Browser yang didukung",
        "div0a": "Penampil Tur Peta didukung pada IE8+. Penyusun interaktif didukung pada IE9+. Kami secara aktif mengujinya di semua browser utama, tetapi jika Anda mengalami beberapa kesulitan, sebaiknya gunakan Chrome.",
        "div0b": "Jika Anda mengalami beberapa kesulitan, mohon beri tahu kami. Sementara itu, dengan membuat Tur Peta menggunakan pola dasar CSV, Anda akan meminimalkan interaksi dengan antarmuka penyusun.",
        "div1": "Gambar",
        "div2": "Kami menyarankan foto orientasi lanskap, bukan orientasi potret. Foto dengan rasio aspek 4:3 yang paling sesuai. Gambar orientasi potret dapat digunakan, tetapi pada layar yang lebih kecil seperti iPad, banyak foto yang terlihat kabur karena keterangan (teks mengambil banyak ruang ketika ditampilkan di area tinggi dibandingkan pada area luas). Walaupun gambar dengan ukuran, bentuk, dan orientasi yang berbeda dapat digunakan pada Tur Peta, sebaiknya gunakan ukuran dan bentuk yang sama untuk semua gambar. Dengan cara ini, pengguna tidak akan bingung karena perbedaan ukuran gambar saat mereka mengikuti tur.",
        "div2a": "Kami sarankan ukuran gambar maksimal dengan lebar 1000 piksel x tinggi 750 piksel untuk gambar utama dan 140x93 untuk gambar mini.",
        "div3": "Pemformatan teks keterangan menggunakan tag HTML",
        "div4": "Judul/keterangan header dan gambar dapat mencakup tag HTML untuk menetapkan pemformatan dan tautan. Misalnya, kode ini menambahkan tautan berwarna kuning:",
        "div4a": "Tulis subjudul yang baik untuk tur Anda",
        "div4b": "Luangkan waktu untuk menulis subjudul yang menarik untuk tur Anda. Subjudul adalah cara yang baik untuk menarik orang ke tur Anda dan memberi tahu mereka tentang apa yang ada di dalamnya. Itu juga tempat yang baik untuk memberi tahu audiens tentang negara bagian atau negara tempat tur itu berada. Misalnya, jangan beranggapan bahwa orang sudah mengetahui kota atau lokasi tur Anda. Keterangan Anda juga dapat diformat menggunakan tag HTML, seperti menyertakan tautan. Jangan membuat keterangan terlalu panjang. Pada jendela browser yang lebih kecil atau pada iPad, itu tidak akan pas sepenuhnya dan terpotong. Jika Anda tidak memiliki subjudul yang baik, biarkan kosong.",
        "div5": "Lapisan Pendukung",
        "div6": "Anda dapat menambahkan lapisan pendukung tambahan untuk menyediakan konteks pada Tur Peta. Lapisan ini mungkin berisi fitur geografis lainnya yang ingin Anda tampilkan di Peta selain poin Tur Peta, seperti area studi, rute berjalan atau mengemudi yang menghubungkan titik-titik wisata, dll. Pola dasar Tur Peta menampilkan lapisan pendukung tambahan ini menggunakan simbologi yang Anda tentukan di peta web, tetapi pop-up tidak tersedia.",
        "div7": "Pertahankan agar tur Anda pendek dan menarik",
        "div8": "Terdapat batasan 99 titik per tur. Sebagian besar Tur Peta tentunya akan lebih pendek dari ini. Jangan berharap audiens Anda ingin mengunjungi terlalu banyak titik tur. Anda mungkin melihat bahwa subjeknya menarik, tetapi jangan mengangap mereka akan mengunjunginya juga!",
        "div10": "Sematkan mode",
        "div11": "Jika Anda ingin menyematkan pola dasar di situs web lainnya melalui iframe, menambahkan parameter opsional \"&sematkan\" di akhir URL akan menghapus header. Mode tersebut juga dapat diatur di versi yang dapat diunduh melalui file konfigurasi.",
        "div12": "Hindari menggunakan iFrame sempit yang menyebabkan tur peta beralih ke tata letak berbasis layar sentuh yang kurang responsif. Untuk memaksimalkan kemudahan penggunaan. Saat Anda menyematkan tur peta, sebaiknya tetap sediakan tautan di sebelah tur yang disematkan, sehingga pengguna dapat meluncurkan tur dalam layar penuh."
      },
      "tab5": {
        "title": "Penerbitan",
        "div1": "Jika telah selesai, jangan lupa untuk membagikan Tur Peta Anda dengan audiens melalui tombol BAGIKAN atau halaman item aplikasi di ArcGIS Daring.",
        "div2a": "Berbagi Tur melalui penyusun",
        "div2b": "Tombol BAGIKAN akan memperbarui item aplikasi dan peta web. Jika data Tur disimpan di item Layanan Fitur, data juga akan diperbarui. Jika Anda menambahkan lapisan lainnya melalui penampil peta ArcGIS.com, lapisan tersebut tidak akan diperbarui. Ini dapat menyebabkan Tur tidak dibagikan sesuai harapan Anda. Item yang telah memiliki hak istimewa yang diperlukan (atau lebih banyak) tidak akan diperbarui.",
        "div2c": "Berbagi Tur melalui ArcGIS Daring",
        "div2d": "Ketika berbagi aplikasi melalui ArcGIS Daring, Anda mungkin akan diminta untuk memperbarui sumber daya bergantung apa pun (peta web, layanan fitur, lapisan dekorasi) yang tidak dibagikan dengan cara yang sama. Jika Tur Peta bersifat publik dan salah satu sumber daya Anda tidak dibagikan dengan audiens, pengguna akan diarahkan ke halaman masuk ArcGIS Daring.",
        "div3t": "Keamanan Layanan Fitur",
        "div3a": "Jika Anda menggunakan layanan fitur di-host yang dibuat melalui penyusun Tur Peta, aplikasi tersebut mengelola keamanan layanan untuk Anda dan Anda tetap menjadi satu-satunya orang yang memiliki hak istimewa pengeditan, meskipun Anda membagikan layanan secara publik.",
        "div3t2": "Sebelum berbagi Tur dengan audiens",
        "div3": "Pastikan Tur berfungsi dengan baik ketika Anda tidak masuk dengan akun ArcGIS.com. URL yang akan Anda gunakan tidak boleh mengarah pada halaman masuk atau pada mode penyusun.",
        "div4": "Sebaiknya lihat tampilan tur peta Anda di iPad yang menampilkan orientasi lanskap untuk memastikan tur peta terlihat baik di perangkat ternama ini. Ini akan membantu Anda memastikan apakah keterangan tersebut terlalu banyak menutupi gambar. Hal ini juga memungkinkan Anda melihat apakah subjudul cocok dan tidak terlalu panjang sehingga terpotong.",
        "div5a": "Saran untuk pencarian",
        "div5b": "Untuk membantu orang menemukan Tur Peta ketika mencarinya di ArcGIS Online, sebaiknya tambahkan tag 'peta cerita' ke halaman item aplikasi tur peta (bukan halaman item web Anda), bersama dengan tag seperti nama negara bagian atau provinsi tempat tur berada, nama negara jika berada di luar AS, dan tag tematik seperti 'seni publik', 'panduan wisata', atau 'tempat bersejarah'. Tag ini juga membantu kami di Esri untuk menemukan contoh tur baru keren yang dapat kami pamerkan di galeri dan promosikan di media sosial. Sebaiknya Anda juga mengunggah grafik gambar mini yang menarik ke halaman item aplikasi, seperti tangkapan layar kecil dari tur dan salah satu foto dari tur. Gambar ini digunakan secara otomatis jika tur peta Anda ditambahkan ke galeri ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Tur disimpan",
      "manageStory": "Kelola cerita Anda",
      "manageStoryA1": "Tip: Anda dapat menggunakan %LINK1% untuk memeriksa kesalahan pada cerita dan mengubah cara komponen dibagikan. Cerita Saya juga akan membantu membuat cerita Anda terlihat bagus saat dibagikan di jejaring sosial. Anda dapat mempelajari fitur berguna lainnya dari Cerita Saya di %LINK2%.",
      "manageStoryA1V1": "Cerita Saya",
      "manageStoryA1V2": "pos blog",
      "shareTitle": "Bagikan Tur Anda",
      "sharePrivateHeader": "Tur Anda tidak dibagikan, ingin membagikannya?",
      "sharePrivateBtn1": "Bagikan untuk publik",
      "sharePrivateBtn2": "Bagikan dengan Organisasi saya",
      "sharePrivateProgress": "Berbagi dalam proses...",
      "sharePrivateErr": "Berbagi gagal, coba lagi atau",
      "sharePrivateOk": "Berbagi diperbarui, memuat...",
      "sharePreviewAsUser": "Pratinjau",
      "shareHeader1": "Tur Anda <strong>dapat diakses oleh publik</strong>.",
      "shareHeader2": "Tur Anda dapat diakses oleh anggota organisasi (perlu masuk).",
      "shareLinkHeader": "Bagikan Tur Anda",
      "shareLinkOpen": "BUKA",
      "shareA1": "Gunakan %SHAREIMG% pada <a href='%LINK1%' target='_blank'>halaman item aplikasi</a>. Jika Anda juga ingin membatalkan berbagi peta web, gunakan <a href='%LINK2%' target='_blank'>halaman item peta web</a>.",
      "shareWarning": "Berbagi %WITH% telah dinonaktifkan karena Anda bukan pemilik <a href='%LINK%' target='_blank'>peta web</a>.",
      "shareWarningWith1": "secara publik",
      "shareWarningWith2": "secara publik dan dengan Organisasi"
    },
    "locator": {
      "error": "Lokasi tidak tersedia"
    },
    "saveErrorSocial": {
      "title": "Pembaruan berbagi di media sosial",
      "panel1": "Penampilan cerita di media sosial meningkat, namun judul item aplikasi web ArcGIS Anda tidak sama dengan judul cerita Anda.",
      "panel1tooltip": "Dengan menentukan judul, ringkasan, dan gambar tampilan mini, cerita Anda akan terlihat seperti ini:",
      "panel2": "Judul mana yang ingin Anda gunakan di media sosial:",
      "panel2q1": "Judul cerita (disarankan)",
      "panel2q1tooltip": "Dengan memilih opsi ini, judul item akan diubah agar sama dengan judul cerita Anda dan perubahan lebih lanjut pada penyusun akan diselaraskan.",
      "panel2q2": "Judul item",
      "panel3": "Untuk meningkatkan penampilan cerita Anda di media sosial, gunakan ${MYSTORIES} untuk menambahkan ringkasan dan gambar tampilan mini.",
      "panel4": "Jangan mengingatkan saya lagi untuk cerita ini",
      "mystories": "Cerita Saya",
      "btnSave": "Simpan"
    }
  }
});