define(
({
		viewer: {
			loading: {
				step1: "SE ÎNCARCĂ APLICAŢIA",
				step2: "SE ÎNCARCĂ DATELE",
				step3: "SE INIŢIALIZEAZĂ TURUL",
				fail: "Ne pare rău, nu s-a reuşit încărcarea turului hărţii",
				failButton: "Reîncercare"
			},
			errors: {
				boxTitle: "A apărut o eroare",
				invalidConfig: "Eroare gravă: Configurare incorectă",
				invalidConfigOwner: "Eroare gravă: Configurare incorectă (necesită proprietar autorizat)",
				invalidConfigNoWebmap: "Eroare gravă: Configurare incorectă (necesită hartă web şi proprietar autorizat)",
				createMap: "Imposibil de creat harta",
				invalidApp: "Eroare gravă: Imposibil de încărcat aplicaţia",
				noLayer: "Harta web nu conţine un strat tematic cu date valabile pentru turul hărţii.",
				noLayerNoHostedFS: "Harta Web nu conţine un strat tematic de date valide pentru Turul hărţii şi nu aveţi privilegiile necesare pentru a crea un serviciu de obiecte spaţiale găzduit.",
				noLayerMobile: "Bine aţi venit la turul hărţii. Aplicaţia nu este configurată. Aplicaţia Map Tour builder nu este acceptată pe dispozitivele mobile.",
				noLayerView: "Bine aţi venit la aplicaţia web Map Tour.<br />Aplicaţia nu s-a configurat încă.",
				noBuilderWebmapData: "Instrumentul de creare a Turului hărţii nu este suportat de datele încorporate în harta Web. Pentru a utiliza instrumentul de creare, trebuie să utilizaţi un serviciu de obiecte spaţiale. Pentru a utiliza stratul tematic de date actual, trebuie să utilizaţi versiunea descărcabilă a Turului hărţii.",
				appSave: "Eroare la salvarea aplicaţiei web",
				mapSave: "Eroare la salvarea hărţii web",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "Nu sunteţi autorizat pentru a configura această aplicaţie",
				oldBrowserTitle: "Browserul nu este acceptat în totalitate",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "Instrumentul de creare a Turului hărţii nu este suportat în Internet Explorer 10 din Windows 7. Trebuie să <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>forţaţi manual accesul în modul document în standardele Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>să faceţi downgrade la Internet Explore 9</a> sau upgrade la Windows 8.",
				oldBrowserExplain: "Acest browser nu suportă generarea automată de miniaturi pentru imaginile pe care le-aţi încărcat în turul hărţii. Puteţi crea un tur al hărţii utilizând acest browser, însă va trebui să furnizaţi câte o imagine miniaturală separată pentru fiecare din imaginile încărcate.",
				oldBrowserExplain2: "Pentru a vă îmbunătăţi experienţa, <a href='http://browsehappy.com/' target='_blank'>efectuaţi upgrade de browser</a> sau <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activaţi Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserClose: "Închidere"
			},
			mobileHTML: {
				showIntro: "AFIŞARE PREZENTARE",
				hideIntro: "ASCUNDERE PREZENTARE",
				navList: "Listă",
				navMap: "Hartă",
				navInfo: "Informaţii"
			},
			desktopHTML: {
				storymapsText: "O hartă informativă",
				builderButton: "Comutare la modul builder"
			},
			builderHTML: {
				panelHeader: "CONFIGURARE APLICAŢIE",
				buttonSave: "SALVARE",
				buttonDiscard: "ANULARE",
				buttonSettings: "Setări",
				buttonView: "Mod de vizualizare",
				buttonOrganize: "Organizare",
				buttonAdd: "Adăugare",
				modalCancel: "Anulare",
				modalApply: "Aplicare",
				organizeHeader: "Organizaţi turul",
				organizeGeneralCaption: "Utilizaţi funcţia de glisare şi fixare pentru a sorta punctele turului",
				organizeDelete: "Ştergere",
				organizeHide: "Ascundere",
				addMaxPointReached: "Aţi atins numărul maxim de puncte permise de către pictogramele setate şi nu se mai poate adăuga alt punct de tur.<br /><br />Reţineţi că ştergând punctele existente va trebui să reîncărcaţi aplicaţia.",
				addMaxPointReachedMobile: "Ne pare rău, aţi atins numărul maxim de puncte autorizate şi nu puteţi adăuga acea imagine.",
				addClose: "Închidere",
				addHeader: "Adăugaţi un punct de tur nou",
				addTabPicture: "Imagine",
				addTabInformation: "Informaţii",
				addTabLocation: "Locaţie",
				addSelectCaption: "Selectaţi sau fixaţi imaginea",
				addSelectCaptionNoFileReader: "Selectare imagine",
				addChangePhoto: "Modificare imagine şi miniatură",
				addPictureResolutionIntro: "Rezoluţia imaginii este mai mare decât este necesar:",
				addPictureResolutionOldBrowser: "Rezoluţia imaginii este mai mare decât este necesar. Optimizaţi experienţa privind harta turului specificând o rezoluţie mai mică decât %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Modificaţi rezoluţia imaginii la %RESOLUTION%",
				addPictureResolutionKeep: "Păstraţi rezoluţia originală pentru %RESOLUTION%",
				addSelectThumbnail: "Selectare miniatură",
				addNoThumbSelected: "Nu s-a selectat o miniatură",
				addThumbSelected: "S-a selectat",
				addCameraSettingsHeader: "SETĂRI APARAT FOTO",
				addThumbnailHeader: "MINIATURĂ",
				addLabelName: "Nume",
				addLabelDescription: "Subtitlu",
				addTextPlaceholder: "Scrieţi ceva",
				addLocatePlaceholder: "Găsiţi o adresă sau un loc",
				addPinColor: "Culoare",
				addLatitude: "Latitudine",
				addLongitude: "Longitudine",
				addLatitudePlaceholder: "de ex. 34.056",
				addLongitudePlaceholder: "de ex. -117.195",
				addUploading: "Încărcarea punctului de tur",
				addSave: "Adăugare punct de tur",
				addMobileUploading: "Se încarcă imaginea",
				addMobileName: "Introducere nume",
				addMobileNameMandatory: "Eroare, introduceţi un nume.",
				addMobileError: "Ne pare rău, ceva nu a mers bine",
				settingsHeader: "Setări aplicaţie",
				settingsTabLayout: "Configuraţie",
				settingsTabColor: "Culori",
				settingsTabLogo: "Antet",
				settingsTabFields: "Date",
				settingsTabExtent: "Extindere",
				settingsTabZoom: "Nivel de transfocare",
				settingsLayoutExplain: "Selectaţi configuraţia aplicaţiei dintre cele două furnizate.",
				settingsLayoutProfessional: "Configuraţie cu trei panouri",
				settingsLayoutModern: "Configuraţie integrată",
				settingsLayoutSelected: "Configuraţie selectată",
				settingsLayoutSelect: "Selectaţi această configuraţie",
				settingsColorExplain: "Schimbaţi aspectul prin alegerea unei teme predefinite sau creaţi una proprie.",
				settingsLabelColor: "Culori pentru antet, cuprins şi notă de subsol",
				settingsLogoExplain: "Particularizaţi sigla antetului (maximum 250 x 50px).",
				settingsLogoEsri: "Sigla Esri",
				settingsLogoNone: "Fără siglă",
				settingsLogoCustom: "Siglă particularizată",
				settingsLogoCustomPlaceholder: "Adresă URL imagine",
				settingsLogoCustomTargetPlaceholder: "Link de accesare cu clic",
				settingsLogoSocialExplain: "Personalizaţi linkul din colţul din dreapta sus al antetului.",
				settingsLogoSocialText: "Text",
				settingsLogoSocialLink: "Link",
				settingsDataFieldsExplain: "Selectaţi Câmpurile cu numele fotografiei, subtitlul şi culoare.",
				settingsDataFieldsError: "Aplicaţia nu poate stabili datele corespunzătoare pentru nume, subtitlu şi culoare. Selectaţi câmpurile de utilizat aici. Acste setări se pot modifica ulterior.",
				settingsFieldsLabelName: "Nume",
				settingsFieldsLabelDescription: "Subtitlu",
				settingsFieldsLabelColor: "Culoare",
				settingsExtentExplain: "Setaţi extinderea iniţială a Turului hărţii cu ajutorul hărţii interactive de mai jos.",
				settingsExtentExplainBottom: "Acea extindere este utilizată numai dacă include primul punct din tur. Valoarea este propagată prin extinderea iniţială a hărţii Web.",
				settingsExtentDrawBtn: "Trasare extindere nouă",
				settingsExtentModifyBtn: "Editare extindere curentă",
				settingsExtentApplyBtn: "Aplicare pe harta principală",
				settingsZoomExplain: "Setaţi transfocarea pentru punctele informative care urmează după prezentare (opţional).",
				settingsLabelZoom: "Scară/nivel",
				settingsZoomFirstValue: "Niciuna",
				settingsFieldError : "Selectaţi un câmp în fiecare listă",
				dataHeader: "Date aplicaţie",
				dataExplain: "Harta web nu conţine un serviciu de obiecte spaţiale. Completaţi acest dialog pentru a crea un serviciu de obiecte spaţiale găzduit în cadrul contului organizaţiei ArcGIS.com. Serviciul de obiecte spaţiale va fi adăugat în harta Web şi partajat public însă numai dvs. veţi avea privilegii de adăugare/editare şi ştergere.<br /><br />Aplicaţia va putea fi vizualizată numai de dvs. până când o partajaţi cu alţii. <strong>După ce Turul hărţii este gata, partajaţi aplicaţia prin pagina elementului.</strong>",
				dataNameLbl: "Nume serviciu",
				dataFolderListLbl: "Director",
				dataFolderListFetching: "Se extrag directoare...",
				dataRootFolder: "Rădăcină",
				dataNameError: "Introduceţi un nume pentru serviciul de obiecte spaţiale",
				dataFolderError: "Selectaţi un director valabil",
				dataSrcContainsInvalidChar: "Numele serviciului de obiecte spaţiale conţine unul sau mai multe caractere incorecte (<, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "Există deja un serviciu cu numele respectiv în cadrul organizaţiei. Alegeţi alt nume.",
				dataBtnClose: "Revocaţi turul",
				dataBtnSave: "Creaţi serviciul",
				dataFooterProgress: "Creare în curs",
				dataFooterSucceed: "Creare reuşită. Se încarcă",
				dataFooterError: "Creare nereuşită. Încercaţi din nou",
				tabError: "Verificaţi erorile în toate filele",
				introRecordBtn: "Introducere",
				introRecordActivate: "Utilizare primul punct drept introducere"
			},
			addPopupJS: {
				uploadingPicture: "Se încarcă imaginea",
				uploadSuccess: "Încărcare reuşită",
				uploadError: "Eroare la încărcarea imaginii",
				notJpg: "Alegeţi o fotografie jpeg de încărcat",
				errorNoPhoto: "Alegeţi o imagine de încărcat",
				errorNoThumbnail: "Alegeţi o miniatură de încărcat",
				errorNoName: "Introduceţi un nume pentru acest punct de tur",
				errorNoDescription: "Introduceţi un subtitlu pentru acest punct de tur",
				errorNoLocation: "Setaţi o locaţie pentru acest punct de tur"
			},
			builderJS: {
				noPendingChange: "Nicio modificare în aşteptare",
				unSavedChangeSingular: "O modificare nesalvată",
				unSavedChangePlural: "modificări nesalvate",
				popoverDiscard: "Sigur renunţaţi la toate modificările nesalvate?",
				yes: "Da",
				no: "Nu",
				popoverLoseSave: "Prin deschiderea vizualizatorului veţi pierde toate modificările nesalvate",
				ok: "Ok",
				popoverSaveWhenDone: "Nu uitaţi să salvaţi când aţi terminat",
				closeWithPendingChange: "Sigur confirmaţi acţiunea? Se vor pierde modificările.",
				gotIt: "Ok",
				savingApplication: "Se salvează aplicaţia",
				saveSuccess: "S-a reuşit salvarea aplicaţiei",
				saveError: "Salvare nereuşită, încercaţi din nou",
				dragColorPicker: "Deplasează-mă<br />sau schimbă-mi culoarea",
				dataWarningExtent: "Aveţi date care nu se încadrează în limitele hărţii web. Aceste date nu vor fi utilizate ca puncte de tur, modificaţi limitele hărţii dacă doriţi să le utilizaţi.",
				dataWarningVisibi: "Stratul tematic al turului de hartă nu este vizibil în limitele actuale ale hărţii. Confirmaţi că stratul tematic al turul de hartă este vizibil cu o hartă mai mare %MAPSIZE%.",
				dataWarningEdit: "Editare hartă web",
				dataWarningClose: "Închidere",
				signIn: "Conectaţi-vă la un cont în",
				signInTwo: "pentru a salva aplicaţia."
			},
			organizePopupJS: {
				messageStart: "Aţi ales să ştergeţi",
				messageSinglePoint: "un punct de tur",
				messageMultiPoint: "puncte de tur",
				messagePermantRemove: "Astfel se va efectua eliminarea definitivă pentru",
				messageRecord: "înregistrare",
				messageRecordPlural: "înregistrări",
				messageConfirm: "din baza de date. Continuaţi?",
				labelButtonShow: "Afişare",
				labelButtonHide: "Ascundere"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "Se încarcă imaginea şi miniatura",
				popoverUploadingThumbnail: "Se încarcă miniatura",
				popoverUploadSuccessful: "Încărcare reuşită",
				popoverUploadError: "Încărcare nereuşită, încercaţi din nou",
				changePicAndThumb: "Schimbare imagine",
				changeThumb: "Schimbare miniatură",
				selectPic: "Schimbare imagine",
				selectThumb: "Schimbare miniatură",
				uploadPicAndThumb: "Aplicare"
			},
			headerJS:{
				editMe: "Editează-mă!",
				templateTitle: "Setare titlu şablon",
				templateSubtitle: "Setare subtitlu şablon"
			},
			crossFaderJS:{
				setPicture: "Setare titlu imagine",
				setCaption: "Setare subtitlu imagine"
			}
        }
    })
);
