define(
	 ({
		viewer: {
			loading: {
				step1: "SE ÎNCARCĂ APLICAŢIA",
				step2: "SE ÎNCARCĂ DATELE",
				step3: "SE INIŢIALIZEAZĂ TURUL",
				loadBuilder: "SE COMUTĂ LA MODUL INSTRUMENT DE CĂUTARE",
				redirectSignIn: "REDIRECŢIONARE LA PAGINA DE AUTENTIFICARE",
				redirectSignIn2: "(veţi fi redirecţionat aici după autentificare)",
				fail: "Ne pare rău, nu s-a reuşit încărcarea turului hărţii",
				failButton: "Reîncercare"
			},
			errors: {
				boxTitle: "A apărut o eroare",
				portalSelf: "Eroare fatală: Eşec la obţinerea configuraţiei portalului",
				invalidConfig: "Eroare gravă: Configurare incorectă",
				invalidConfigOwner: "Eroare gravă: Configurare incorectă (necesită proprietar autorizat)",
				invalidConfigNoWebmap: "Eroare gravă: Configurare incorectă (identificatorul pentru harta sau aplicaţia web nu este specificat în index.html)",
				createMap: "Nu se poate crea harta",
				invalidApp: "Eroare gravă: Imposibil de încărcat aplicaţia",
				noLayer: "Harta web nu conţine un strat tematic cu date valabile pentru turul hărţii.",
				noLayerMobile: "Bine aţi venit la turul hărţii. Aplicaţia nu este configurată. Aplicaţia Map Tour builder nu este acceptată pe dispozitivele mobile.",
				noLayerView: "Bine aţi venit la aplicaţia web Map Tour.<br />Aplicaţia nu s-a configurat încă.",
				appSave: "Eroare la salvarea aplicaţiei web",
				mapSave: "Eroare la salvarea hărţii web",
				featureServiceLoad: "Eroare la încărcarea serviciului de obiecte spaţiale",
				notAuthorized: "Nu sunteţi autorizat pentru a accesa această aplicaţie",
				oldBrowserTitle: "Browserul nu este acceptat în totalitate",
				noBuilderIE8: "Instrumentul de crearea a Turului hărţii nu este suportat în versiunile Internet Explorer anterioare versiunii 9.",
				ie10Win7Explain: "Instrumentul interactiv de creare a Turului hărţii nu este suportat în Internet Explorer 10 din Windows 7 când sursa de date este un serviciu de obiecte spaţiale cu ataşări. Pentru a utiliza un serviciu de obiecte spaţiale cu ataşări, trebuie să <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>forţaţi manual accesul în modul document în standardele Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>să faceţi downgrade la Internet Explorer 9</a> sau upgrade la Windows 8.",
				oldBrowserExplain: "Acest browser nu suportă generarea automată de miniaturi pentru imaginile pe care le-aţi încărcat în turul hărţii. Puteţi crea un tur al hărţii utilizând acest browser, însă va trebui să furnizaţi câte o imagine miniaturală separată pentru fiecare din imaginile încărcate.",
				oldBrowserExplain2: "Pentru a vă îmbunătăţi experienţa, <a href='http://browsehappy.com/' target='_blank'>efectuaţi upgrade de browser</a> sau <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activaţi Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserExplain3: "Instrumentul de creare a Turului hărţii nu funcţionează cu Internet Explorer 10 în Windows XP.",
				oldBrowserClose: "Închidere"
			},
			mobileHTML: {
				showIntro: "AFIŞARE TITLU",
				hideIntro: "ASCUNDERE TITLU",
				navList: "Listă",
				navMap: "Hartă",
				navInfo: "Media",
				introStartBtn: "Pornire"
			},
			desktopHTML: {
				storymapsText: "O hartă informativă",
				builderButton: "Comutare la modul builder",
				facebookTooltip: "Partajare pe Facebook",
				twitterTooltip: "Partajare pe Twitter",
				bitlyTooltip: "Obţinere link scurt",
				bitlyStartIndex: "Link către locul curent"
			},
			builderHTML: {
				panelHeader: "CONFIGURARE APLICAŢIE",
				buttonSave: "SALVARE",
				buttonSettings: "Setări",
				buttonShare: "Partajare",
				buttonView: "Mod de vizualizare",
				buttonItem: "Deschidere element aplicaţie web",
				buttonHelp: "Ajutor",
				buttonOrganize: "Organizare",
				buttonAdd: "Adăugare",
				buttonImport: "Import",
				buttonImportDisabled: "Importul nu este disponibil la utilizarea unui serviciu de obiecte spaţiale cu ataşări",
				dataEditionDisabled: "Ediţia de date este dezactivată pe sursa de date CSV",
				dataSourceWarning: "Stratul tematic de date pentru Tur hartă a fost modificat. Dacă ID-urile obiectelor spaţiale nu sunt identice, trebuie să resetaţi ordinea şi punctele ascunse prin opţiunea <b>Organizare</b>. Dacă numele câmpurilor diferă, trebuie să resetaţi setările câmpurilor din <b>fila pentru date din Setări</b>.",
				organizeWarning: "Unul sau mai multe puncte adăugate în afara instrumentului de creare interactiv sunt ascunse.",
				dataPicError0a: "Acest tur include <b>%NB%</b> URL-uri de fotografii neconforme.",
				dataPicError0b: "Acest tur poate include <b>%NB%</b> URL-uri de fotografii neconforme.",
				dataPicError1: "Turul hărţii necesită acum ca un URL de fotografie să se termine cu una din următoarele extensii: .jp(e)g, .png, .gif sau .bmp.",
				dataPicError2: "Această cerinţă nu va afecta Turul hărţii publicat în prezent. Cu toate acestea, pentru a utiliza instrumentul de creare interactiv, trebuie mai întâi să rezolvaţi problema URL-ului efectuând una din următoarele activităţi:",
				dataPicError3: "Editare URL-uri",
				dataPicError4: "Acesta va adăuga <i>#isImage</i> la sfârşitul URL-urilor de fotografii nesuportate. Majoritatea serverelor suportă anexe la URL-uri. Cu toate acestea, după ce aţi efectuat acea acţiune, trebuie să verificaţi dacă URL-urile de fotografii actualizate sunt funcţionale, navigând prin puncte.Dacă se încarcă toate fotografiile, puteţi salva Turul hărţii. Dacă există <b>fotografii defecte, nu salvaţi Turul hărţii</b>. În schimb, încărcaţi din nou instrumentul de creare şi efectuaţi a doua acţiune.",
				dataPicError5: "Limitarea turului la fotografii",
				dataPicError6: "Această opţiune determină considerarea tuturor URL-urilor drept fotografii, însă nu veţi pute adăuga clipuri video utilizând instrumentul de creare interactivă. Această acţiune este reversibilă în cazul în care vă hotărâţi în viitor să adăugaţi clipuri video.",
				dataPicError7: "Turul hărţii a fost restricţionat la fotografii; nu se pot utiliza clipuri video. Dacă alegeţi să eliminaţi limitarea, verificaţi dacă fotografiile se încarcă în continuare corect înainte de a salva Turul hărţii. Dacă va fi necesar, veţi putea restaura ulterior limitarea.",
				dataPicError8: "Eliminare limitare la fotografii",
				dataPicError9: "În cazul în care aceste URL-uri conduc la clipuri video puteţi ignora acest avertisment; în cazul în care conduc la fotografii, trebuie să efectuaţi una din următoarele acţiuni:",
				modalCancel: "Anulare",
				modalApply: "Aplicare",
				organizeHeader: "Organizaţi turul",
				organizeGeneralCaption: "Utilizaţi funcţia de glisare şi fixare pentru a sorta punctele turului",
				organizeDelete: "Ştergere",
				organizeHide: "Ascundere",
				organizeReset: "Resetare ordine şi puncte ascunse",
				addMaxPointReached: "Aţi atins numărul maxim de puncte permise de către pictogramele setate şi nu se mai poate adăuga alt punct de tur.<br /><br />Reţineţi că ştergând punctele existente va trebui să reîncărcaţi aplicaţia.",
				addMaxPointReachedMobile: "Ne pare rău, aţi atins numărul maxim de puncte autorizate şi nu puteţi adăuga acea imagine.",
				addClose: "Închidere",
				addHeader: "Adăugaţi un punct de tur nou",
				addTabPicture: "Media",
				addTabInformation: "Informaţii",
				addTabLocation: "Locaţie",
				addSelectCaption: "Selectaţi sau fixaţi imaginea",
				addNoteVideo: "Consultaţi Ajutorul pentru instrucţiuni referitoare la utilizarea clipurilor video",		
				addSelectCaptionNoFileReader: "Selectare imagine",	
				addChangePhoto: "Modificare imagine şi miniatură",
				addPictureResolutionIntro: "Rezoluţia imaginii este mai mare decât este necesar:",
				addPictureResolutionOldBrowser: "Rezoluţia imaginii este mai mare decât este necesar. Optimizaţi experienţa privind harta turului specificând o rezoluţie mai mică decât %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Modificaţi rezoluţia imaginii la %RESOLUTION%",
				addPictureResolutionKeep: "Păstraţi rezoluţia originală pentru %RESOLUTION%",
				addSelectThumbnail: "Selectare miniatură",
				addNoThumbSelected: "Nu s-a selectat o miniatură",
				addThumbSelected: "S-a selectat",
				addCameraSettingsHeader: "SETĂRI APARAT FOTO",
				addThumbnailHeader: "MINIATURĂ",
				addLabelPicUrl: "Fotografie",
				addLabelThumbUrl: "Miniatură",
				addTextPlaceholderUrl: "Introducere URL imagine",
				addTextPlaceholderUrl2: "Introducere URL de pagină YouTube",
				addTextPlaceholderUrl3: "Introducere URL de pagină Vimeo",
				addTextPlaceholderUrl4: "Introducere URL de încorporare video",
				addLabelVideo: "Video",
				addMediaVideoOther: "Altul",
				addMediaVideoHelp: "Verificaţi URL-ul şi preluaţi miniatura implicită",
				addMediaVideoHelpTooltip1: "Verificare reuşită",
				addMediaVideoHelpTooltip2: "Verificare eşuată",
				addMediaVideoHelpTooltip4: "Găsiţi opţiunea pentru încorporarea clipului video şi copiaţi URL-ul clipului video prezent în cod",
				addLabelName: "Nume",
				addLabelDescription: "Subtitlu",
				addTextPlaceholder: "Scrieţi ceva",
				addLocatePlaceholder: "Găsiţi o adresă sau un loc",
				addPinColor: "Culoare",
				addLatitude: "Latitudine",
				addLongitude: "Longitudine",
				addLatitudePlaceholder: "de ex. 34.056",
				addLongitudePlaceholder: "de ex. -117.195",
				addUploading: "Încărcarea punctului de tur",
				addSave: "Adăugare punct de tur",
				addMobileUploading: "Se încarcă imaginea",
				addMobileName: "Introducere nume",
				addMobileNameMandatory: "Eroare, introduceţi un nume.",
				addMobileError: "Ne pare rău, ceva nu a mers bine",
				settingsHeader: "Setări aplicaţie",
				settingsTabLayout: "Configuraţie",
				settingsTabColor: "Culori",
				settingsTabLogo: "Antet",
				settingsTabFields: "Date",
				settingsTabExtent: "Extindere",
				settingsTabZoom: "Nivel de transfocare",
				settingsLayoutExplain: "Selectaţi configuraţia dorită a aplicaţiei.",
				settingsLayoutProfessional: "Configuraţie cu trei panouri",
				settingsLayoutModern: "Configuraţie integrată",
				settingsLayoutSelected: "Configuraţie selectată",
				settingsLayoutSelect: "Selectaţi această configuraţie",
				settingsLayoutNote: "Reţineţi că în punctele care utilizează clipuri video, afişul va fi plasat întotdeauna sub clipul video chiar dacă opţiunea este debifată.",
				settingsLayoutLocBtn: "Afişare buton pentru localizare",
				settingsLayoutLocBtnHelp: "Acea funcţionalitate este suportată pe majoritatea browserelor pentru dispozitive mobile şi sisteme desktop (Internet Explorer 9).",
				settingsColorExplain: "Schimbaţi aspectul prin alegerea unei teme predefinite sau creaţi una proprie.",
				settingsLabelColor: "Culori pentru antet, cuprins şi notă de subsol",
				settingsLogoExplain: "Particularizaţi sigla antetului (maximum 250 x 50px).",
				settingsLogoEsri: "Sigla Esri",
				settingsLogoNone: "Fără siglă",
				settingsLogoCustom: "Siglă particularizată",
				settingsLogoCustomPlaceholder: "Adresă URL imagine",
				settingsLogoCustomTargetPlaceholder: "Link de accesare cu clic",
				settingsLogoSocialExplain: "Personalizaţi linkul din colţul din dreapta sus al antetului.",
				settingsLogoSocialText: "Text",
				settingsLogoSocialLink: "Link",
				settingsLogoSocialDisabled: "Acest obiect spaţial a fost dezactivat de administrator",
				settingsDataFieldsExplain: "Selectaţi Câmpurile cu numele fotografiei, subtitlul şi culoare.",
				settingsDataFieldsError: "Aplicaţia nu poate stabili datele corespunzătoare pentru nume, subtitlu şi culoare. Selectaţi câmpurile de utilizat aici. Acste setări se pot modifica ulterior.",
				settingsFieldsLabelName: "Nume",
				settingsFieldsLabelDescription: "Subtitlu",
				settingsFieldsLabelColor: "Culoare",
				settingsFieldsReset: "Resetare selecţie câmpuri",
				settingsExtentExplain: "Setaţi extinderea iniţială a Turului hărţii cu ajutorul hărţii interactive de mai jos.",
				settingsExtentExplainBottom: "Extinderea pe care o definiţi va modifica extinderea iniţială a hărţii dvs. web. Reţineţi că această extensie nu este utilizată dacă nu include primul punct al turului. În acest caz, turul se va deschide centrat pe primul punct.",
				settingsExtentDateLineError: "Extinderea nu poate traversa meridianul cu longitudinea 180Â°",
				settingsExtentDateLineError2: "Eroare la calculul extinderii",
				settingsExtentDrawBtn: "Trasare extindere nouă",
				settingsExtentModifyBtn: "Editare extindere",
				settingsExtentApplyBtn: "Previzualizare în Turul hărţii",
				settingsExtentUseMainMap: "Utilizare extindere Tur hartă",
				settingsZoomExplain: "Setaţi transfocarea pentru punctele informative care urmează după prezentare (opţional).",
				settingsLabelZoom: "Scară/nivel",
				settingsZoomFirstValue: "Niciuna",
				settingsFieldError: "Selectaţi un câmp în fiecare listă",
				dataTitle: "Găzduire ArcGIS Online",
				dataExplain: "Harta web nu conţine un serviciu de obiecte spaţiale. Acesta nu va fi partajat cu nimeni şi numai dvs. veţi avea privilegii de adăugare, editare şi ştergere.<br /><br />Reţineţi că, dacă partajaţi aplicaţia prin pagina elementului, sistemul vă va întreba dacă doriţi să partajaţi şi serviciul de obiecte spaţiale. Acesta este un pas obligatoriu. Veţi rămâne singurul utilizator cu privilegii de editare.",
				dataNameLbl: "Nume serviciu",
				dataFolderListLbl: "Director",
				dataFolderListFetching: "Se extrag directoare...",
				dataRootFolder: "Rădăcină",
				dataNameError: "Introduceţi un nume pentru serviciul de obiecte spaţiale",
				dataFolderError: "Selectaţi un director valabil",
				dataSrcContainsInvalidChar: "Numele serviciului de obiecte spaţiale conţine unul sau mai multe caractere incorecte (-, <, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "Există deja un serviciu cu numele respectiv în cadrul organizaţiei. Alegeţi alt nume.",
				dataBtnSave: "Creaţi serviciul",
				dataFooterProgress: "Creare în curs",
				dataFooterSucceed: "Creare reuşită. Se încarcă",
				dataFooterError: "Creare nereuşită. Încercaţi din nou",
				tabError: "Verificaţi erorile în toate filele",
				introRecordBtn: "Introducere",
				introRecordActivate: "Utilizare primul punct drept introducere (nu apare în carusel)"
			},
			addPopupJS: {
				uploadingPicture: "Se încarcă imaginea",
				uploadSuccess: "Încărcare reuşită",
				uploadError: "Eroare la încărcarea imaginii",
				uploadError2: "Eroare la adăugarea obiectului spaţial (etichetă html nevalidă)",
				notJpg: "Alegeţi o fotografie jpeg de încărcat",
				errorNoPhoto: "Alegeţi o imagine de încărcat",
				errorNoThumbnail: "Alegeţi o miniatură de încărcat",
				errorInvalidPicUrl: "Introduceţi o fotografie validă (începe cu http(s)://, se termină cu jpg, png, gif sau bmp). Pentru a ocoli această regulă, puteţi termina URL-ul cu '#isImage'.",
				errorInvalidThumbUrl: "Introduceţi o miniatură validă (începe cu http(s)://, se termină cu jpg, png, gif sau bmp).",
				errorInvalidVideoUrl: "Introduceţi un URL valid de clip video (începe cu http(s)://)",
				errorNoName: "Introduceţi un nume pentru acest punct de tur",
				errorNoDescription: "Introduceţi un subtitlu pentru acest punct de tur",
				errorNoLocation: "Setaţi o locaţie pentru acest punct de tur"
			},
			builderJS: {
				noPendingChange: "Nicio modificare nesalvată",
				unSavedChangeSingular: "O modificare nesalvată",
				unSavedChangePlural: "modificări nesalvate",
				shareStatus1: "Turul nu este salvat",
				shareStatus2: "Turul este partajat public",
				shareStatus3: "Turul este partajat în cadrul organizaţiei",
				shareStatus4: "Turul nu este partajat",
				popoverDiscard: "Sigur renunţaţi la toate modificările nesalvate?",
				yes: "Da",
				no: "Nu",
				popoverLoseSave: "Prin deschiderea vizualizatorului veţi pierde toate modificările nesalvate",
				ok: "OK",
				popoverSaveWhenDone: "Nu uitaţi să salvaţi când aţi terminat",
				closeWithPendingChange: "Sigur confirmaţi acţiunea? Se vor pierde modificările.",
				gotIt: "OK",
				savingApplication: "Se salvează aplicaţia",
				saveSuccess: "S-a reuşit salvarea aplicaţiei",
				saveError: "Salvare nereuşită, încercaţi din nou",
				saveError2: "Salvare eşuată din cauza unei etichete html nevalide într-un nume sau o descriere",
				saveError3: "Titlul nu poate fi necompletat",
				dragColorPicker: "Deplasează-mă<br />sau schimbă-mi culoarea",
				dataWarningExtent: "Aveţi date care nu se încadrează în limitele hărţii web. Aceste date nu vor fi utilizate ca puncte de tur, modificaţi limitele hărţii dacă doriţi să le utilizaţi.",
				dataWarningVisibi: "Stratul tematic al turului de hartă nu este vizibil în limitele actuale ale hărţii. Confirmaţi că stratul tematic al turul de hartă este vizibil cu o hartă mai mare %MAPSIZE%.",
				dataWarningEdit: "Editare hartă web",
				dataWarningClose: "Închidere",
				signIn: "Conectaţi-vă la un cont în",
				signInTwo: "pentru a salva aplicaţia.",
				switchBM: "Modificare hartă fundal"
			},
			organizePopupJS: {
				messageStart: "Aţi ales să ştergeţi",
				messageSinglePoint: "un punct de tur",
				messageMultiPoint: "puncte de tur",
				messagePermantRemove: "Astfel se va efectua eliminarea definitivă pentru",
				messageRecord: "înregistrare",
				messageRecordPlural: "înregistrări",
				messageConfirm: "din baza de date. Continuaţi?",
				labelButtonShow: "Afişare",
				labelButtonHide: "Ascundere"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Acest lucru va şterge definitiv imaginea şi miniatura",
				popoverDeleteWarningThumb: "Acest lucru va şterge definitiv miniatura",
				popoverUploadingPhoto: "Se încarcă imaginea şi miniatura",
				popoverUploadingThumbnail: "Se încarcă miniatura",
				popoverUploadSuccessful: "Încărcare reuşită",
				popoverUploadError: "Încărcare nereuşită, încercaţi din nou",
				changePicAndThumb: "Schimbare imagine",
				changeThumb: "Schimbare miniatură",
				selectPic: "Schimbare media",
				selectThumb: "Schimbare miniatură",
				uploadPicAndThumb: "Aplicare"
			},
			headerJS:{
				editMe: "Editează-mă!",
				templateTitle: "Setare titlu şablon",
				templateSubtitle: "Setare subtitlu şablon"
			},
			crossFaderJS:{
				setPicture: "Setare titlu imagine",
				setCaption: "Setare subtitlu imagine"
			},
			importPopup: {
				title: "Import",
				prevBtn: "Înapoi",
				nextBtn: "Înainte"
			},
			importPopupHome: {
				header: "Unde sunt stocate imaginile dvs.?"
			},
			onlinePhotoSharingCommon: {
				pictures: "fotografii",
				videos: "videoclipuri",
				disabled: "Acest obiect spaţial a fost dezactivat de administrator",
				disabledPortal: "Această caracteristică este dezactivată în Portal for ArcGIS",
				header1: "Imaginile dvs. trebuie partajate public.",
				header2: "Importul va fi limitat la primele %NB1% %MEDIA%.",
				emptyDataset: "Eroare, nu a fost găsită nicio imagine",
				footerImport: "Import",
				selectAlbum: "Selectare album public",
				selectAlbum2: "Selectare album",
				pleaseChoose: "Alegeţi",
				userLookup: "Căutare",
				userLookingup: "Se caută",
				csv: "Cu referinţă într-un CSV",
				advanced: "Opţiuni avansate",
				advancedScratchLbl: "Începeţi un tur nou",
				advancedScratchTip: "Creaţi un tur gol, pe care îl veţi putea popula manual utilizând un expert.",
				advancedCSVLbl: "Import date tur dintr-un fişier CSV",
				advancedCSVTip: "Import conţinut tur dintr-un fişier CSV.",
				advancedCommonTip: "Necesită ca imaginile şi videoclipurile să fie deja online.",
				select: "Efectuare selecţie",
				locUse: "Utilizare locaţie geografică imagini",
				locExplain: "Este posibil să nu doriţi să utilizaţi locaţia imaginilor aşa cum sunt acestea preluate din album, rezultând că toate fotografiile se află în aceeaşi locaţie.",
				locExplain2: "Este posibil să doriţi să utilizaţi locaţia videoclipurilor, fiind posibil ca acestea să fie moştenite din setările utilizatorului, ceea ce ar face ca toate videoclipurile să se afle în aceeaşi locaţie."
			},
			viewFlickr: {
				title: "Import Flickr",
				header: "Introduceţi numele de utilizator Flickr şi selectaţi un Set de fotografii sau o Etichetă de importat.",
				userInputLbl: "Introducere nume de utilizator",
				signInMsg2: "Utilizator negăsit",
				selectSet: "Selectare set de fotografii",
				selectTag: "sau Selectare etichetă",
				footerImportTag: "Import etichetă selectată",
				footerImportSet: "Import set selectat"
			},
			viewFacebook: {
				title: "Import Facebook",
				header: "Autentificaţi-vă folosind contul dvs. de utilizator Facebook sau utilizaţi o pagină publică. Se pot utiliza albume private pentru crearea unui tur al hărţii public, care nu necesită autentificarea utilizator pe Facebook, ceea ce permite rămânerea privată a comentariilor şi calificativelor Îmi place.",
				leftHeader: "Utilizator Facebook",
				rightHeader: "Pagină Facebook",
				pageExplain: "O pagină de Facebook este o marcă sau un produs public sau o celebritate precum <b>esrigis</b>. Puteţi prelua numele paginii după primul caracter „/” din URL-ul paginii.",
				pageInputLbl: "Introducere nume pagină",
				lookupMsgError: "Pagină negăsită"
			},
			viewPicasa: {
				title: "Import Picasa/Google+",
				header: "Introduceţi adresa e-mail sau ID-ul contului dvs. Picasa sau Google+.",
				userInputLbl: "Introducere e-mail sau ID",
				signInMsg2: "Cont negăsit",
				signInMsg3: "Niciun album public",
				howToFind: "Găsirea unui ID de cont Picasa sau Google+",
				howToFind2: "Copiaţi cifrele dintre primul şi al doilea caracter „/” a unei pagini Picasa sau G+"
			},
			viewCSV: {
				title: "Import CSV",
				uploadBtn: "Selectare sau plasare fişier CSV",
				resultHeaderEmpty: "Fişierul CSV este gol",
				resultHeaderSuccess: "Au fost încărcate cu succes %NB_POINTS% puncte",
				resultHasBeenLimited: "Importul a fost limitat la primele %VAL1% puncte din %VAL2% pentru respectarea limitei de %VAL3% puncte per tur",
				browserSupport: "Browserul dvs. nu este suportat; pentru a utiliza un fişier CSV trebuie să faceţi <a href='http://browsehappy.com/' target='_blank'>upgrade pentru browser</a> sau să utilizaţi aplicaţia de vizualizare a hărţilor web din ArcGIS.com (consultaţi Ajutorul).",
				errorLatLng: "Câmpurile Latitudine şi Longitudine nu au fost găsite. Valorile posibile pentru latitudine sunt: <i>%LAT%</i> şi pentru longitudine: <i>%LONG%</i>.",
				errorFieldsExplain: "Încărcarea a eşuat deoarece următoarele câmpuri obligatorii nu au fost găsite",
				errorFieldsName: "Valorile posibile pentru <b>Nume</b> sunt: %VAL%",
				errorFieldsDesc: "Valorile posibile pentru <b>Descriere</b> sunt: %VAL%",
				errorFieldsUrl: "Valorile posibile pentru <b>URL imagine</b> sunt: %VAL%",
				errorFieldsThumb: "Valorile posibile pentru <b>URL miniatură</b> sunt: %VAL%",
				errorFields2Explain: "Încărcarea a eşuat deoarece fişierul CSV nu utilizează aceleaşi atribute ca şi stratul tematic pentru următoarele atribute",
				errorFields2Name: "<b>Nume</b> utilizează %VAL1% în loc de %VAL2%",
				errorFields2Desc: "<b>Descriere</b> utilizează %VAL1% în loc de %VAL2%",
				errorFields2Url: "<b>URL imagine</b> utilizează %VAL1% în loc de %VAL2%",
				errorFields2Thumb: "<b>URL miniatură</b> utilizează %VAL1% în loc de %VAL2%",
				resultFieldsAll: "Toate atributele au fost importate",
				resultFieldsNotAll: "Următoarele atribute nu au fost importate deoarece nu există în stratul tematic al hărţii",
				resultFieldsNotAll2: "Următoarele atribute au fost importate",
				footerNextBtnResult: "Import în harta web",
				footerProgress: "Import în curs",
				footerSucceed: "Importul a reuşit. Se încarcă"
			},
			viewYoutube: {
				title: "Import YouTube",
				header: "Introduceţi un nume de utilizator YouTube pentru a găsi clipuri video partajate în mod public.",
				pageInputLbl: "Introduceţi un nume de utilizator YouTube",
				lookupMsgError: "Utilizator negăsit",
				howToFind: "Cum găsiţi un nume de utilizator YouTube",
				howToFind2: "Numele de utilizator este afişat sub videoclipuri",
				found: "Găsit",
				noData: "Nu a fost găsit niciun videoclip public"
			},
			viewGeoTag: {
				title: "Selectarea şi localizarea imaginilor/videoclipurilor",
				header: "Faceţi clic pe sau atingeţi imaginile pe care doriţi să le importaţi pentru a le localiza.",
				headerMore: "De ce nu sunt localizate geografic imaginile/clipurile mele video?",
				headerExplain: "Dacă imaginile dvs. au o locaţie validă, acestea vor fi localizate automat pe hartă şi listate în a doua filă.<br /><br />În mod implicit, Picasa şi Flickr nu stochează metadatele EXIF ale locaţiei când importaţi fotografii. Verificaţi setările Flickr/Picasa din fila Confidenţialitate pentru a activa utilizarea locaţiei imaginilor. Este posibil să fie necesar să reimportaţi complet imaginile în Flickr/Picasa.<br /><br />Pentru Facebook, trebuie să accesaţi fiecare imagine, să faceţi clic pe Editare şi să selectaţi locaţia dintre variantele sugerate, care se bazează pe metadatele EXIF ale imaginilor.",
				leftPanelTab1: "De localizat",
				leftPanelTab2: "Localizat",
				clickOrTap: "Faceţi clic pe sau atingeţi harta pentru a localiza",
				clearLoc: "Golire locaţii",
				clickDrop: "Nu se importă",
				footerImport: "Import",
				footerProgress: "Import în curs",
				footerSucceed: "Import reuşit. Se încarcă...",
				loading: "Se încarcă",
				error: "Importul locaţiilor geografice ale imaginilor nu a reuşit, locaţiile geografice au fost ignorate."
			},
			initPopup: {
				title: "Bun venit la instrumentul de creare a Turului hărţii",
				prevBtn: "Înapoi",
				nextBtn: "Înainte"
			},
			initPopupHome: {
				header1: "Unde se găsesc imaginile sau clipurile video?",
				header2: "Acest asistent vă va ajuta să creaţi un Tur al hărţii din imaginile stocate deja online sau le va importa în contul ArcGIS Online for Organizations.",
				title1: "Acestea sunt online deja",
				title2: "Trebuie să încarc imaginile",
				hostedFSTooltip: "Utilizaţi ArcGIS Online pentru a găzdui imaginile (nu acceptă clipuri video).",
				hostedFsNA: "Disponibil numai pentru utilizatori cu permisiuni Editor sau Administrator ArcGIS for Organizations",
				footer1: "După ce terminaţi, nu uitaţi să partajaţi Turul hărţii cu publicul prin pagina elementului de tip aplicaţie.",
				footer3: "Descărcare şablon CSV",
				footer4: "\"Salvare ca\" dacă nu se descarcă",
				footer4bis: "Utilizaţi clic dreapta şi \„Salvare ca\” dacă descărcarea nu începe",
				footer5: "Învăţaţi mai mult",
				footerProgress: "Creare în curs",
				footerSucceed: "Creare reuşită. Se încarcă..."
			},
			helpPopup: {
				title: "Ajutor",
				close: "Închidere",
				tab1: {
					title: "Introducere",
					div1: "Şablonul Turul hărţii este conceput pentru prezentarea de informaţii geografice atunci când există un element fotografic sau media interesant pentru informaţiile pe care doriţi să le ilustraţi.",
					div2: "Şablonul reprezintă o aplicaţie web atractivă şi uşor de utilizat, care vă permite să prezentaţi un set redus de locuri de pe o hartă într-o ordine numerotată, pe care utilizatorii o pot parcurge. Şablonul este conceput pentru a fi utilizat în orice browser web de pe orice dispozitiv, inclusiv pe telefoane smartphone şi tablete. <br /><br />Iată un exemplu de aplicaţie pe care o puteţi crea:",
					div4: "<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Turul hărţii Palm Springs</a>.",
					div42: "Pentru a vedea exemple de tururi de hărţi create de alţi utilizatori, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>vizitaţi galeria</a> de pe <a href='http://storymaps.arcgis.com/' target='_blank'>site-ul web de hărţi informative</a>. De asemenea, ne puteţi urmări pe Twitter, la adresa <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
					div5: "Ne-ar face plăcere să împărtăşiţi lucruri cu noi! Dacă aveţi o întrebare, doriţi să solicitaţi o caracteristică nouă sau credeţi că aţi găsit o defecţiune, vizitaţi <a href='http://links.esri.com/storymaps/forum' target='_blank'>Forumul utilizatorilor de hărţi informative</a>."
				},
				tab2: {
					title: "Date",
					div1: "Cel mai important element de luat în considerare la crearea unui Tur al hărţii este alegere locaţiei în care vor fi stocate fotografiile. Un tur de hartă poate utiliza fotografii stocate în servicii mari de partajare a fotografiilor, de pe orice server web sau ca ataşări la un serviciu de obiecte spaţiale.",
					div1a: "Consultaţi ultima parte a acestei file pentru detalii despre formatele de fotografii şi clipuri video suportate.",
					div2: "Instrumentul de creare interactiv vă oferă două posibilităţi  pentru gestionarea imaginilor din Turul hărţii:",
					div3: "<ul><li>Puteţi utiliza <b>fotografii aflate deja online</b>, precum imaginile stocate pe un site de partajare a fotografiilor, cum ar fi Flickr, sau imagini stocate pe propriul dvs. site web. Aceste imagini vor avea referinţe în Turul hărţii prin intermediul URL-urilor lor</li><li>De asemenea, puteţi <b>încărca fotografii de pe computer</b> direct în Turul hărţii. Pentru această opţiune de încărcare, trebuie să aveţi un cont ArcGIS pentru organizaţii şi privilegii de Editor sau Administrator, deoarece se creează automat un serviciu de obiecte spaţiale găzduit, care sunt stocate fotografiile dvs. sub formă de ataşări.</li></ul>",
					div4: "Principalele cazuri de utilizare sunt:",
					div4b: "<b>Fotografiile dvs. nu sunt găzduite</b> încă şi aveţi un cont ArcGIS pentru organizaţii: utilizarea unui serviciu de obiecte spaţiale găzduit este cea mai bună alegere. Ca şi serviciile publice de partajare a fotografiilor, vă vom optimiza fotografiile pentru a crea fotografiile cu încărcare rapidă, iar dvs. veţi avea acces la toate capabilităţile de administrare şi gestionare a datelor de pe platforma ArcGIS.",
					div5: "<b>Nu sunteţi membru al unei organizaţii</b>: mai întâi trebuie să încărcaţi fotografiile pe un site web de partajare a fotografiilor sau pe propriul dvs. server web. Apoi, instrumentul de creare vă va ajuta să utilizaţi aceste fotografii, care vor continua să fie găzduite în locaţia lor originală",
					div6: "<b>Doriţi să reutilizaţi un serviciu de obiecte spaţiale existent</b>, în care fotografiile dvs. sunt stocate ca ataşări sau în care există referinţe către fotografii externe: consultaţi capitolul detaliat de mai jos.",
					div7: "<b>Utilizaţi o versiune anterioară</b> a şablonului Turul hărţii şi aveţi propriul dvs. CSV în care aveţi referinţe la fotografii şi miniaturi: îl veţi putea importa şi vă veţi putea rafina datele. Instrumentul de creare suportă numai formatul CSV care utilizează câmpuri lat/long; utilizarea fişierului CSV bazat pe adrese poate continua în harta web (consultaţi capitolul de mai jos).",
					div8: "Importul din servicii online de partajare a fotografiilor",
					div9: "Operaţia de import conţine referinţe la fotografii deja găzduite, prin stocarea URL-urilor acestora într-o colecţie de obiecte spaţiale de hartă web. Fotografiile nu sunt stocate în ArcGIS Online.Dacă imaginile găzduite nu pot fi accesate, ele nu vor fi disponibile în Turul hărţii, iar dvs. veţi vedea o imagine cu textul „Imagine indisponibilă”. În funcţie de furnizorul de servicii fotografice, este posibil ca Turul hărţii să nu importe numele, descrierile şi locaţiile imaginilor. Aceste informaţii sunt stocate în harta web şi nicio editare a serviciilor online nu se va reflecta în Turul hărţii.",
					div10: "Stocarea imaginilor pe un server web",
					div11: "Dacă alegeţi să vă găzduiţi singuri fotografiile, va trebui să creaţi manual miniaturi ale fotografiilor. Utilizarea fotografiilor la rezoluţia maximă pentru miniaturi va conduce la performanţe slabe. Din acest motiv, vă recomandăm să utilizaţi un serviciu online de partajare a fotografiilor sau un serviciu de obiecte spaţiale care va face acest lucru pentru dvs.",
					div12: "Utilizarea unui serviciu de obiecte spaţiale sau a unui shapefile existent",
					div13: "Orice serviciul de obiecte spaţiale sau shapefile de puncte poate fi utilizat ca sursă de date pentru Turul hărţii. Trebuie doar să îl adăugaţi ca strat tematic în harta web prin aplicaţia de vizualizare a hărţilor din arcgis.com. Dacă aplicaţia găseşte atributele aşteptate în stratul dvs. tematic, toate funcţionalităţile instrumentului de creare vor fi disponibile.",
					div14: "Valorile posibile pentru numele câmpurilor sunt (ţin cont de majuscule/minuscule):",
					div151: "Nume",
					div152: "Descriere",
					div153: "Fotografie",
					div154: "Miniatură",
					div155: "Culoare ",
					div16: "Dacă aplicaţia nu găseşte câmpuri corespunzătoare la utilizarea unui serviciu de obiecte spaţiale, aplicaţia de vizualizare nu va funcţiona până când nu configuraţi câmpurile de utilizat în instrumentul de creare. Straturile tematice CSV sau shapefile adăugate în harta web trebuie să aibă toate câmpurile necesare sau instrumentul de creare nu va funcţiona.",
					div162: "La utilizarea unui serviciu de obiecte spaţiale care stochează fotografiile ca ataşări, <b>vor fi utilizate numai obiectele spaţiale cu două ataşări</b>.Prima ataşare defineşte fotografia principală, iar a doua ataşare defineşte miniatura.",
					div17: "Câmpurile pentru imagine şi miniatură sunt obligatorii pentru serviciul de obiecte spaţiale fără ataşări şi opţionale (dar recomandate) pentru serviciul de obiecte spaţiale cu ataşări. Dacă serviciul dvs. are ataşările activate, instrumentul de creare vă va permite să încărcaţi fotografii ca ataşări. În caz contrar, veţi putea numai să editaţi URL-urile fotografiei şi miniaturii.",
					div172: "Când sunt prezente, câmpurile pentru fotografie şi miniatură vor fi întotdeauna utilizate, iar ataşările serviciului de obiecte spaţiale nu vor fi interogate.",
					div173: "Exemple de fişiere CSV şi shapefile pot fi descărcate de la",
					div18: "Crearea unui serviciu de obiecte spaţiale din CSV sau shapefile",
					div19: "Când creaţi un serviciu de obiecte spaţiale din CSV sau shapefile, ataşările nu sunt activate implicit. Pentru a le activa, deschideţi pagina cu detaliile serviciului de obiecte spaţiale, faceţi clic pe mica săgeată de pe secţiunea stratului tematic şi veţi vedea opţiunea respectivă. Turul hărţii va continua să utilizeze fotografiile şi miniaturile pentru care aţi introdus referinţe prin atribute. Opţional, dacă doriţi să încărcaţi fotografiile ca ataşări la serviciul de obiecte spaţiale, veţi putea face acest lucru cu ajutorul a două butoane de pe panoul pentru imagini (\"Modificare fotografie\" şi \"Modificare miniatură\").",
					div20: "Formate de imagini şi clipuri video suportate",
					div21: "Formatele de fotografii suportate sunt: <b>.jpg, .jpeg, .png, .gif şi .bmp</b>. Dacă fişierul dvs. media nu se termină cu una din aceste extensii, Turul hărţii îl va considera un clip video, cu excepţia cazului în care se utilizează un serviciu de obiecte spaţiale (vedeţi mai jos).",
					div22: "Şablonul Tur hartă nu include un player video, astfel încât trebuie să utilizaţi player video extern furnizat de serviciul dvs. preferat de găzduire a materialelor video (găsiţi opţiunea pentru încorporarea clipurilor video şi copiaţi URL-ul prezent în codul dat). Dacă doriţi să găzduiţi voi înşivă clipul video, puteţi crea o pagină HTML care să conţină un player video precum <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Instrumentul de creare interactiv nu furnizează un dialog pentru includerea clipului video când utilizaţi servicii de obiecte spaţiale cu ataşări, însă este posibil să faceţi acest lucru editând datele în afara instrumentului de creare interactiv. În aplicaţia de vizualizare a hărţilor din arcgis.com, dacă modificaţi câmpurile pentru fotografii pentru a conduce la un clip video extern şi adăugaţi un parametru special la sfârşitul URL-ului (#isVideo), fişierul media va fi considerat ca fiind un clip video.",
					div24: "Reţineţi că este în continuare necesar să aveţi două ataşări de tip fotografie valide, în caz contrar punctul nu va fi utilizat. Nu se pot utiliza clipuri video când se utilizează ataşări la serviciul de obiecte spaţiale fără câmpuri pentru fotografie şi miniatură."
				},
				tab3: {
					title: "Personalizarea",
					div1: "Instrumentul de creare oferă mai multe opţiuni de personalizare accesibile prin butonul SETĂRI din panoul de sus. Dacă nu găsiţi opţiunea aşteptată, vă furnizăm şi o versiune descărcabilă pe care o puteţi pune în funcţiune pe serverul web şi îmbunătăţi pentru a corespunde necesităţilor dvs.",
					div2: "Vă recomandăm să utilizaţi versiunea găzduită, cu următoarele excepţii:",
					div3: "<li>Când nu oferă o personalizare a interfeţei cu utilizatorul pe care o doriţi, precum în cazul utilizării unei imagini de fundal pentru antet.</li><li>Când sunteţi dezvoltator şi doriţi să îmbunătăţiţi aplicaţia.</li>",
					div4: "Versiunea descărcabilă poate fi configurată printr-un identificator de hartă web sau aplicaţie de cartografiere web. Principalele situaţii de utilizare sunt:",
					div41: "Construiţi un tur de hartă folosind aplicaţia de creare interactivă din mediul găzduit şi să configuraţi şablonul cu identificatorul aplicaţiei de cartografiere web. Se vor aplica setările pe care le-aţi definit cu instrumentul de creare interactiv.",
					div42: "Construiţi harta web în afara aplicaţiei de creare interactivă şi să configuraţi şablonul cu identificatorul hărţii web. Va trebui să citiţi documentaţia pentru a afla cum să configuraţi şablonul.",
					div43: "Reţineţi că aplicaţia de creare interactivă este disponibilă în versiunea descărcabilă, însă cu unele restricţii tehnice pentru browsere precum Internet Explorer anterior versiunii 10.",
					div5: "Pentru a descărca cea mai recentă versiune a şablonului şi pentru a afla mai multe despre modul în care îl puteţi utiliza, vizitaţi <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>pagina proiectului GitHub</a>."
				},
				tab4: {
					title: "Sfaturi",
					div0: "Browsere suportate",
					div0a: "Aplicaţia de vizualizare pentru Turul hărţii este suportată începând de la IE8+.Instrumentul de creare interactiv este suportat începând de la IE9+. Noi testăm în mod activ toate browserele importante, însă, dacă întâmpinaţi dificultăţi, vă recomandăm să utilizaţi Chrome.",
					div0b: "Dacă întâmpinaţi dificultăţi, daţi-ne de ştire. Între timp, prin creare Turului hărţii utilizând şablonul CSV veţi reduce la minim interacţiunea cu interfaţa instrumentului de creare.",
					div1: "Imagini",
					div2: "Vă recomandăm să utilizaţi orientarea fotografiilor peisaj în loc de portret. Fotografiile cu raportul 4:3 se potrivesc cel mai bine. Imaginile cu orientare portret pot fi utilizate, însă pe ecrane mai mici precum iPad şi este posibil ca o mare parte din fotografie să fie obturată de subtitlu (textul ocupă mai mult spaţiu când este afişat într-o suprafaţă înaltă, decât într-o suprafaţă înaltă). Cu toate că se pot utiliza imagini de dimensiuni, forme şi orientări diferite într-un Tur al hărţii, vă recomandăm să utilizaţi aceeaşi dimensiune şi aceeaşi formă pentru toate imaginile. În acest fel, utilizatorul nu va fi distras de de imagini cu dimensiuni diferite în timp ce parcurg turul.",
					div2a: "Vă recomandăm o dimensiune maximă pentru imagini de 1000 pixeli pe lăţime x 750 pixeli pe înălţime pentru fotografiile principale şi 140x93 pentru miniaturi.",
					div3: "Formatarea textului din subtitluri cu ajutorul etichetelor HTML",
					div4: "Antetul şi titlul/subtitlul fotografiei pot include etichete HTML pentru definirea formatării şi a linkurilor. De exemplu, acest cod adaugă un link galben:",
					div4a: "Scrieţi un subtitlu bun pentru tur",
					div4b: "Alocaţi timp pentru redactarea unui subtitlu atrăgător pentru tur. Subtitlul constituie un mijloc bun de a atrage oamenii să parcurgă turul şi de a le spune ce vor descoperi în el. De asemenea, este un loc potrivit pentru a comunica publicului statul sau ţara în care este localizat turul. De exemplu, nu presupuneţi că publicul ştie unde se află localitatea prezentată în tur. Subtitlul poate fi, de asemenea, formatat folosind etichete HTML, precum în cazul includerii unor linkuri. Totuşi, nu faceţi subtitlul prea mare. În ferestrele de browser mai mici sau pe iPad este posibil să nu încapă complet şi să fie scurtat. Dacă nu găsiţi niciun subtitlu bun, lăsaţi-l necompletat.",
					div5: "Straturi tematice de asistenţă",
					div6: "Puteţi adăuga straturi tematice de asistenţă suplimentare pentru a oferi context în Turul hărţii. Aceste straturi tematice pot conţine alte obiecte spaţiale geografice care doriţi să apară pe hartă pe lângă punctele din Turul hărţii, cum ar fi o rută de deplasare pe jos sau cu maşina, care să lege punctele din tur etc. Turul hărţii afişează afişează aceste straturi tematice de asistenţă suplimentare utilizând simbolurile pe care le specificaţi în harta web, însă nu sunt disponibile ferestre pop-up.",
					div7: "Păstraţi turul scurt şi plăcut",
					div8: "Există o limită de 99 de puncte per tur. Majoritatea Tururilor de hărţi vor fi semnificativ mai scurte de atât. Nu vă aşteptaţi ca publicul să dorească să parcurgă prea multe puncte în tur. Poate că dvs. vi se pare subiectul fascinant, însă nu presupuneţi că şi ceilalţi cred acelaşi lucru!",
					div9: "Pentru a afla mai multe, consultaţi <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>ghidul detaliat</a>.",
					div10: "Mod încorporat",
					div11: "Dacă doriţi să încorporaţi şablonul în alt site web folosind un iframe, adăugarea parametrului opţional \"&embed\" la sfârşitul URL-ului va elimina antetul. Acel mod poate fi setat şi în versiunea descărcabilă prin intermediul fişierului de configurare.",
					div12: "Evitaţi să utilizaţi o lăţime iFrame îngustă, care ar determina turul hărţii să comute la aspectul bazat pe interacţiune tactilă, pentru ecrane mici. Pentru a-l face cât mai uşor de utilizat. La încorporarea unui tur de hartă, recomandăm întotdeauna să furnizaţi şi un link lângă turul încorporat, astfel încât utilizatorii să poată lansa turul pe tot ecranul." 
				},
				tab5: {
					title: "Publicarea",
					div1: "După ce terminaţi, nu uitaţi să împărtăşiţi Turul hărţii cu publicul folosind butonul Partajare sau pagina elementului aplicaţie din ArcGIS Online.",
					div2a: "Partajare tur cu ajutorul instrumentului de creare",
					div2b: "Butonul Partajare va actualiza aplicaţia şi elementele Hartă web. Dacă datele turului sunt stocate într-un element de tip Serviciu de obiecte spaţiale, acesta va fi, de asemenea, actualizat. Dacă aţi adăugat alte straturi tematice prin aplicaţia de vizualizare a hărţilor din ArcGIS.com, ele nu vor fi actualizate. Acest lucru poate conduce la nepartajarea turului aşa cum v-aţi aştepta. Elementele care dispun deja de privilegii necesare (sau superioare celor necesare) nu vor fi actualizate.",
					div2c: "Partajare tur prin ArcGIS Online",
					div2d: "Când partajaţi aplicaţia prin ArcGIS Online, dacă va fi necesar, aceasta vă va solicita să actualizaţi eventuale resurse de care depinde (hărţi web, servicii de obiecte spaţiale, straturi tematice decorative) şi care nu sunt partajate în acelaşi fel. Dacă Turul hărţii este public şi una din resurse nu este partajată cu publicul dvs., utilizatorii vor fi redirecţionaţi către pagina de autentificare ArcGIS Online.",
					div3t: "Securitate serviciu spaţial",
					div3a: "Dacă utilizaţi un serviciu de obiecte spaţiale găzduit, creat prin instrumentul de creare a Turului hărţii, aplicaţia administrează securitatea serviciului pentru dvs. şi dvs. veţi rămâne singurul cu privilegii de editare chiar dacă partajaţi serviciul public.",
					div3t2: "Înainte de partajarea turului cu publicul",
					div3: "Asiguraţi-vă că turul funcţionează bine când nu sunteţi autentificat la contul ArcGIS.com. URL-ul pe care îl veţi utiliza nu trebuie să redirecţioneze către o pagină de autentificare sau către modul instrumentului de creare.",
					div4: "O idee bună este să vedeţi cum arată turul hărţii dvs. pe un iPad ţinut în poziţia peisaj pentru a vă asigura că arată bine pe acest dispozitiv popular. Acest lucru este util pentru a vedea dacă subtitlurile acoperă prea mult din imagini. De asemenea, vă permite să vedeţi dacă subtitlul încape şi dacă nu este prea lung apărând ciuntit.",
					div5a: "Recomandare pentru căutare",
					div5b: "Pentru a ajuta utilizatorii să găsească Turul dvs. de hartă atunci când caută în ArcGIS Online, vă recomandăm să adăugaţi eticheta „hartă informativă” în pagina elementului aplicaţie corespunzător turului hărţii (nu în pagina de element corespunzătoare hărţii web), împreună cu etichete precum numele statului sau provinciei în care este localizat turul, numele ţării dacă se află în afara S.U.A. şi etichete tematice precum „artă stradală”, „ghid turistic” sau „obiective istorice”. Aceste etichete ajută şi Esri să găsească exemple noi şi interesante de tururi pe care să le prezentăm în galeriile noastre şi să le promovăm pe site-urile de socializare. De asemenea, vă recomandăm să încărcaţi o miniatură cât mai frumoasă în pagina de element corespunzătoare aplicaţiei, cum ar fi o mică captură de ecran din tur sau sau una din fotografiile din el. Această fotografie este utilizată automat în cazul în care turul dvs. de hartă este adăugat într-o galerie ArcGIS Online."
				}
			},
			share: {
				firstSaveTitle: "Tur salvat cu succes",
				firstSaveHeader: "Turul dvs. este acum salvat în ArcGIS Online. Citiţi următoarele răspunsuri la întrebări frecvente.",
				firstSaveA1: "Dacă nu sunteţi familiarizat cu ArcGIS Online sau doriţi o comandă rapidă pentru a accesa interfaţa de creare, puteţi salva următorul link: %LINK1%",
				firstSaveA1bis: "Turul poate fi găsit şi în <a href='%LINK2%' target='_blank'>folderul de conţinut ArcGIS Online</a>.",
				firstSaveQ2: "Este partajat Turul meu?",
				firstSaveA2: "În prezent, Turul dvs. nu este partajat. Pentru a-l partaja, utilizaţi butonul Partajare.",
				shareTitle: "Partajarea Turului",
				sharePrivateHeader: "Turul dvs. nu este partajat, doriţi să îl partajaţi?",
				sharePrivateBtn1: "Partajare în mod public",
				sharePrivateBtn2: "Partajare cu organizaţia mea",
				sharePrivateProgress: "Partajare în curs...",
				sharePrivateErr: "Partajare nereuşită, încercaţi din nou sau",
				sharePrivateOk: "Partajare actualizată cu succes, se încarcă...",
				sharePreviewAsUser: "Previzualizare",
				shareHeader1: "Turul dvs. este <strong>accesibil în mod public</strong>.",
				shareHeader2: "Turul dvs. este accesibil membrilor organizaţiei dvs. (este necesară conectarea).",
				shareLinkHeader: "Se partajează turul cu publicul",
				shareLinkOpen: "DESCHIDERE",
				shareQ1Opt1: "Cum păstrez Turul privat?",
				shareQ1Opt2: "Cum păstrez Turul privat şi cum în partajez public?",
				shareA1: "Utilizaţi %SHAREIMG% în <a href='%LINK1%' target='_blank'>pagina de element corespunzătoare aplicaţiei</a>. Dacă doriţi şi să anulaţi partajarea hărţii web, utilizaţi <a href='%LINK2%' target='_blank'>pagina de element corespunzătoare hărţii web</a>.",
				shareA1bis: "De asemenea, dacă doriţi să anulaţi partajarea serviciului de obiecte spaţiale, utilizaţi <a href='%LINK1%' target='_blank'>pagina de element corespunzătoare serviciului de obiecte spaţiale</a>.",
				shareQ2: "Cum editez Turul mai târziu?",
				shareQ2bis: "Cum revin la interfaţa de creare?",
				shareA2div1: "Salvaţi şi utilizaţi din nou următorul link, %LINK1%, sau utilizaţi <a href='%LINK2%' target='_blank'>pagina de element corespunzătoare aplicaţiei</a>.",
				shareA2div2: "În calitate de proprietar al aplicaţiei, când sunteţi autentificat pe ArcGIS.com, aplicaţia include un buton pentru a deschide instrumentul de creare interactiv:",				
				shareQ3: "Unde sunt stocate datele?",
				shareA3: "Configuraţia Turului este stocată în <a href='%LINK1%' target='_blank'>acest element de hartă Web</a> şi <a href='%LINK2%' target='_blank'>acest element de aplicaţie Web</a>. Imaginile Flickr, Picasa şi Facebook, împreună cu videoclipurile YouTube sunt apelate de pe site-urile respective şi nu sunt dublate în ArcGIS Online.",
				shareWarning: "Partajarea %WITH% a fost dezactivată, deoarece nu mai sunteţi proprietarul <a href='%LINK%' target='_blank'>hărţii web</a>.",
				shareWarningWith1: "public",
				shareWarningWith2: "public şi cu Organizaţia"
			}
        }
    })
);
