define(
	 ({
		viewer: {
			loading: {
				step1: "ĐANG TẢI ỨNG DỤNG",
				step2: "ĐANG TẢI DỮ LIỆU",
				step3: "ĐANG KHỞI TẠO CHUYẾN THAM QUAN",
				loadBuilder: "ĐANG CHUYỂN SANG CHẾ ĐỘ THIẾT LẬP",
				redirectSignIn: "ĐANG CHUYỂN HƯỚNG ĐẾN TRANG ĐĂNG NHẬP",
				redirectSignIn2: "(bạn sẽ được chuyển hướng ở đây sau khi đăng nhập)",
				fail: "Rất tiếc, tải Map Tour thất bại",
				failButton: "Thử lại"
			},
			errors: {
				boxTitle: "Đã xảy ra lỗi",
				portalSelf: "Lỗi nghiêm trọng: Không thể tải cấu hình cổng thông tin",
				invalidConfig: "Lỗi nghiêm trọng: Cấu hình không hợp lệ",
				invalidConfigOwner: "Lỗi nghiêm trọng: Cấu hình không hợp lệ (cần có chủ sở hữu được ủy quyền)",
				invalidConfigNoWebmap: "Lỗi nghiêm trọng: Cấu hình không hợp lệ (không xác định bản đồ web hoặc định danh ứng dụng trong index.html)",
				createMap: "Không thể tạo bản đồ",
				invalidApp: "Lỗi nghiêm trọng: Không thể tải ứng dụng",
				noLayer: "Bản đồ web không chứa lớp dữ liệu hợp lệ cho Map Tour.",
				noLayerMobile: "Chào mừng bạn đến ứng dụng web Map Tour. Ứng dụng này không được cấu hình. Bộ dựng Map Tour không được hỗ trợ trên các thiết bị di động.",
				noLayerView: "Chào mừng bạn đến với ứng dụng web Trượt nhanh.<br />Ứng dụng này vẫn chưa được cấu hình.",
				appSave: "Lỗi khi lưu ứng dụng web",
				mapSave: "Lỗi khi lưu bản đồ web",
				featureServiceLoad: "Lỗi khi tải dịch vụ đối tượng",
				notAuthorized: "Bạn không được phép truy cập vào ứng dụng này",
				oldBrowserTitle: "Trình duyệt không được hỗ trợ đầy đủ",
				noBuilderIE8: "Bộ dựng Map Tour không được hỗ trợ trên trình duyệt Internet Explorer trước phiên bản 9.",
				ie10Win7Explain: "Bộ dựng tương tác Map Tour không được hỗ trợ trên Internet Explorer 10 trên Windows 7 khi nguồn dữ liệu là một Dịch vụ Đối tượng với tệp đính kèm. Để sử dụng Dịch vụ Đối tượng với tệp đính kèm, bạn phải <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>tự chuyển chế độ văn bản sang Internet Explorer 9 tiêu chuẩn</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>hạ cấp xuống Internet Explorer 9</a> hoặc nâng cấp lên Windows 8.",
				oldBrowserExplain: "Trình duyệt này không hỗ trợ tạo hình thu nhỏ tự động từ những hình ảnh bạn tải vào map tour của bạn. Bạn có thể tạo ra một map tour bằng trình duyệt này, nhưng bạn sẽ phải cung cấp một hình ảnh thu nhỏ riêng biệt cho từng hình ảnh bạn tải lên.",
				oldBrowserExplain2: "Để nâng cao trải nghiệm của bạn, <a href='http://browsehappy.com/' target='_blank'>hãy nâng cấp trình duyệt của bạn</a> hoặc <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>kích hoạt Google Chrome Frame cho Internet Explorer</a>.",
				oldBrowserExplain3: "Bộ dựng Map Tour không làm việc với Internet Explorer 10 trên Windows XP.",
				oldBrowserClose: "Đóng"
			},
			mobileHTML: {
				showIntro: "HIỆN TIÊU ĐỀ",
				hideIntro: "ẨN TIÊU ĐỀ",
				navList: "Danh sách",
				navMap: "Bản đồ",
				navInfo: "Phương tiện",
				introStartBtn: "Bắt đầu"
			},
			desktopHTML: {
				storymapsText: "Story map",
				builderButton: "Chuyển sang chế độ thiết lập",
				bitlyTooltip: "Tải liên kết ngắn đến ứng dụng",
				bitlyStartIndex: "Liên kết đến địa điểm hiện tại"
			},
			builderHTML: {
				panelHeader: "CẤU HÌNH ỨNG DỤNG",
				buttonSave: "LƯU",
				buttonSettings: "Thiết lập",
				buttonShare: "Chia sẻ",
				buttonView: "Chế độ xem",
				buttonItem: "Mở mục Ứng dụng Web",
				buttonHelp: "Trợ giúp",
				buttonOrganize: "Tổ chức",
				buttonAdd: "Thêm",
				buttonImport: "Nhập",
				buttonImportDisabled: "Nhập không khả dụng khi sử dụng Dịch vụ Đối tượng với tệp đính kèm",
				dataEditionDisabled: "Phiên bản dữ liệu bị vô hiệu hóa trên nguồn dữ liệu CSV",
				dataSourceWarning: "Lớp dữ liệu Map Tour đã thay đổi. Nếu ID các tính năng không giống nhau, bạn phải thiết lập lại thứ tự và các điểm ẩn thông qua <b>Tổ chức</b>. Nếu tên các trường khác nhau, bạn phải đặt lại các thiết đặt trường dưới <b>tab dữ liệu trong Thiết đặt</b>.",
				organizeWarning: "Một hoặc nhiều điểm được thêm bên ngoài bộ dựng tương tác bị ẩn.",
				dataPicError0a: "Chuyến tham quan này bao gồm <b>%NB%</b> URL ảnh không tương thích.",
				dataPicError0b: "Chuyến tham quan này có thể bao gồm <b>%NB%</b> URL ảnh không tương thích.",
				dataPicError1: "Map Tour hiện yêu cầu một URL hình ảnh kết thúc bằng một trong những phần mở rộng sau: .jp(e)g, .png, .gif hoặc .bmp.",
				dataPicError2: "Yêu cầu này sẽ không ảnh hưởng đến Map Tour được xuất bản hiện tại của bạn. Tuy nhiên, để sử dụng bộ dựng tương tác, trước tiên bạn phải giải quyết vấn đề URL bằng cách thực hiện một trong hai hành động:",
				dataPicError3: "Sửa URL",
				dataPicError4: "Điều này sẽ thêm <i>#isImage</i> vào cuối URL hình ảnh không được hỗ trợ. Hầu hết máy chủ hỗ trợ các phần phụ URL. Tuy nhiên, khi bạn đã thực hiện hành động đó, bạn nên xác minh rằng các URL hình ảnh được cập nhật hoạt động bằng cách điều hướng thông qua các điểm của bạn. Nếu mỗi hình ảnh tải, thì bạn có thể lưu Map Tour ngay bây giờ. Nếu <b>hình ảnh bị vỡ, thì không được lưu Map Tour</b>. Thay vào đó, tải lại bộ dựng và thực hiện hành động thứ hai.",
				dataPicError5: "Hạn chế chuyến tham quan đến hình ảnh",
				dataPicError6: "Tùy chọn này dẫn đến tất cả các URL được coi là hình ảnh, nhưng bạn sẽ không thể thêm video bằng cách sử dụng bộ dựng tương tác. Có thể đảo lại hành động này, nếu bạn quyết định thêm video sau này.",
				dataPicError7: "Map Tour của bạn đã được giới hạn hình ảnh, không thể sử dụng video. Nếu bạn chọn xóa bỏ giới hạn đó, hãy kiểm tra xem hình ảnh của bạn vẫn tải đúng trước khi lưu Map Tour. Bạn sẽ có thể khôi phục lại giới hạn sau này nếu cần.",
				dataPicError8: "Xóa giới hạn hình ảnh",
				dataPicError9: "Nếu những URL này trỏ vào video, bạn có thể bỏ qua cảnh báo này, nếu chúng trỏ vào hình ảnh, bạn cần phải thực hiện một trong hai hành động sau đây:",
				modalCancel: "Hủy",
				modalApply: "Áp dụng",
				organizeHeader: "Tổ chức tham quan",
				organizeGeneralCaption: "Sử dụng kéo và thả để sắp xếp các điểm tham quan",
				organizeDelete: "Xóa",
				organizeHide: "Ẩn",
				organizeReset: "Đặt lại thứ tự và điểm ẩn",
				addMaxPointReached: "Bạn đã đạt đến số điểm tối đa cho phép theo nhóm biểu tượng và không thể thêm một điểm tham quan khác.<br /><br />Lưu ý rằng nếu bạn xóa các điểm hiện tại, bạn sẽ cần phải tải lại ứng dụng.",
				addMaxPointReachedMobile: "Rất tiếc, bạn đã đạt đến số điểm tối đa được cho phép và không thể thêm ảnh đó.",
				addClose: "Đóng",
				addHeader: "Thêm một điểm tham quan mới",
				addTabPicture: "Phương tiện",
				addTabInformation: "Thông tin",
				addTabLocation: "Vị trí",
				addSelectCaption: "Chọn hoặc thả ảnh",
				addNoteVideo: "Tham khảo Trợ giúp để biết hướng dẫn về cách sử dụng video",		
				addSelectCaptionNoFileReader: "Chọn ảnh",	
				addChangePhoto: "Thay đổi ảnh và hình thu nhỏ",
				addPictureResolutionIntro: "Độ phân giải hình ảnh cao hơn so với yêu cầu:",
				addPictureResolutionOldBrowser: "Độ phân giải ảnh cao hơn so với yêu cầu. Tối ưu hóa trải nghiệm Map Tour bằng cách chỉ định độ phân giải thấp hơn %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Thay đổi độ phân giải ảnh thành %RESOLUTION%",
				addPictureResolutionKeep: "Giữ độ phân giải gốc %RESOLUTION%",
				addSelectThumbnail: "Chọn hình thu nhỏ",
				addNoThumbSelected: "Không có hình thu nhỏ nào được chọn",
				addThumbSelected: "Đã chọn",
				addCameraSettingsHeader: "THIẾT ĐẶT MÁY ẢNH",
				addThumbnailHeader: "HÌNH THU NHỎ",
				addLabelPicUrl: "Ảnh",
				addLabelThumbUrl: "Hình thu nhỏ",
				addTextPlaceholderUrl: "Nhập URL Hình ảnh",
				addTextPlaceholderUrl2: "Nhập URL trang YouTube",
				addTextPlaceholderUrl3: "Nhập URL trang Vimeo",
				addTextPlaceholderUrl4: "Nhập URL nhúng video",
				addLabelVideo: "Video",
				addMediaVideoOther: "Khác",
				addMediaVideoHelp: "Kiểm tra URL và tải hình thu nhỏ mặc định",
				addMediaVideoHelpTooltip1: "Kiểm tra thành công",
				addMediaVideoHelpTooltip2: "Kiểm tra thất bại",
				addMediaVideoHelpTooltip4: "Tìm tùy chọn để nhúng video và sao chép URL video có trong mã",
				addLabelName: "Tên",
				addLabelDescription: "Chú thích",
				addTextPlaceholder: "Nhập nội dung gì đó",
				addLocatePlaceholder: "Định vị một địa chỉ hoặc địa điểm",
				addPinColor: "Màu",
				addLatitude: "Vĩ độ",
				addLongitude: "Kinh độ",
				addLatitudePlaceholder: "ví dụ: 34.056",
				addLongitudePlaceholder: "ví dụ: -117.195",
				addUploading: "Tải điểm tham quan lên",
				addSave: "Thêm điểm tham quan",
				addMobileUploading: "Đang tải ảnh lên",
				addMobileName: "Nhập tên",
				addMobileNameMandatory: "Lỗi, vui lòng nhập tên.",
				addMobileError: "Rất tiếc, đã xảy ra lỗi",
				settingsHeader: "Thiết lập ứng dụng",
				settingsTabLayout: "Bố cục",
				settingsTabColor: "Màu",
				settingsTabLogo: "Đầu mục",
				settingsTabFields: "Dữ liệu",
				settingsTabExtent: "Phạm vi",
				settingsTabZoom: "Độ thu phóng",
				settingsLayoutExplain: "Chọn bố cục ứng dụng bạn muốn.",
				settingsLayoutProfessional: "Bố cục ba bảng điều khiển",
				settingsLayoutModern: "Bố cục tích hợp",
				settingsLayoutSelected: "Bố cục được chọn",
				settingsLayoutSelect: "Chọn bố cục này",
				settingsLayoutNote: "Lưu ý rằng trên điểm sử dụng video, áp phích sẽ luôn luôn được đặt dưới video ngay cả khi tùy chọn đó được bỏ chọn.",
				settingsLayoutLocBtn: "Hiển thị nút 'Định vị'",
				settingsLayoutLocBtnHelp: "Chức năng được hỗ trợ trên hầu hết các trình duyệt máy tính để bàn và thiết bị di động (Internet Explorer 9).",
				settingsColorExplain: "Thay đổi giao diện bằng cách chọn một chủ đề được xác định trước hoặc tạo giao diện của riêng bạn.",
				settingsLabelColor: "Màu đầu mục, nội dung và chân trang",
				settingsLogoExplain: "Tùy chỉnh logo đầu mục (tối đa là 250 x 50px).",
				settingsLogoEsri: "Logo Esri",
				settingsLogoNone: "Không có logo",
				settingsLogoCustom: "Logo tùy chỉnh",
				settingsLogoCustomPlaceholder: "URL Hình ảnh",
				settingsLogoCustomTargetPlaceholder: "Bấm vào liên kết",
				settingsLogoSocialExplain: "Tùy chỉnh liên kết trên cùng bên phải đầu mục.",
				settingsLogoSocialText: "Văn bản",
				settingsLogoSocialLink: "Liên kết",
				settingsLogoSocialDisabled: "Người quản trị đã vô hiệu hóa tính năng này",
				settingsDataFieldsExplain: "Chọn các trường tên ảnh, chú thích và màu sắc.",
				settingsDataFieldsError: "Ứng dụng này không thể xác định tên, chú thích hoặc dữ liệu màu thích hợp. Vui lòng chọn các trường được sử dụng ở đây. Các thiết lập này có thể được thay đổi sau một thời gian.",
				settingsFieldsLabelName: "Tên",
				settingsFieldsLabelDescription: "Chú thích",
				settingsFieldsLabelColor: "Màu",
				settingsFieldsReset: "Đặt lại lựa chọn trường",
				settingsExtentExplain: "Thiết lập phạm vi ban đầu của Map Tour thông qua bản đồ tương tác dưới đây.",
				settingsExtentExplainBottom: "Phạm vi bạn xác định sẽ thay đổi phạm vi ban đầu của bản đồ web của bạn. Lưu ý rằng phạm vi này không được dùng nếu nó không bao gồm điểm tham quan đầu tiên. Trong trường hợp đó chuyến tham quan sẽ mở ở giữa của điểm đầu tiên.",
				settingsExtentDateLineError: "Phạm vi không thể vượt qua kinh tuyến 180°",
				settingsExtentDateLineError2: "Lỗi khi tính toán phạm vi",
				settingsExtentDrawBtn: "Vẽ một phạm vi mới",
				settingsExtentModifyBtn: "Sửa phạm vi",
				settingsExtentApplyBtn: "Xem trước trên Map Tour",
				settingsExtentUseMainMap: "Sử dụng phạm vi Map Tour",
				settingsZoomExplain: "Đặt thu phóng cho các điểm kể chuyện sau khi giới thiệu (tùy chọn).",
				settingsLabelZoom: "Tỷ lệ/mức độ",
				settingsZoomFirstValue: "Không có",
				settingsFieldError: "Vui lòng chọn một trường trong mỗi danh sách",
				dataTitle: "Lưu trữ ArcGIS Online",
				dataExplain: "Dịch vụ đối tượng sẽ được thêm vào bản đồ web của bạn. Nó sẽ không được chia sẻ với bất cứ ai và chỉ bạn có đặc quyền thêm, sửa và xóa.<br /><br />Lưu ý rằng nếu bạn chia sẻ ứng dụng qua trang mục, hệ thống sẽ hỏi xem bạn có muốn chia sẻ Dịch vụ Đối tượng không. Đây là một bước bắt buộc. Bạn sẽ vẫn là người duy nhất có đặc quyền sửa.",
				dataNameLbl: "Tên dịch vụ",
				dataFolderListLbl: "Thư mục",
				dataFolderListFetching: "Đang tìm nạp thư mục ...",
				dataRootFolder: "Gốc",
				dataNameError: "Nhập tên dịch vụ đối tượng",
				dataFolderError: "Chọn thư mục hợp lệ",
				dataSrcContainsInvalidChar: "Tên dịch vụ đối tượng có chứa một hoặc nhiều ký tự không hợp lệ (-, <, >, #, %, :, \", ?, &, +, / hoặc \).",
				dataSrvAlreadyExistsError: "Một dịch vụ có tên đó đã tồn tại trong tổ chức. Vui lòng chọn một tên khác.",
				dataBtnSave: "Tạo dịch vụ",
				dataFooterProgress: "Đang tạo",
				dataFooterSucceed: "Tạo thành công. Đang tải",
				dataFooterError: "Tạo thất bại. Vui lòng thử lại",
				tabError: "Vui lòng kiểm tra lỗi trong tất cả các tab",
				introRecordBtn: "Giới thiệu",
				introRecordActivate: "Sử dụng điểm đầu tiên là phần giới thiệu (không xuất hiện trong ảnh trượt xoay vòng)"
			},
			addPopupJS: {
				uploadingPicture: "Đang tải ảnh lên",
				uploadSuccess: "Tải lên thành công",
				uploadError: "Lỗi khi tải ảnh lên",
				uploadError2: "Lỗi khi thêm tính năng (thẻ html không hợp lệ)",
				notJpg: "Vui lòng chọn ảnh jpeg để tải lên",
				errorNoPhoto: "Chọn ảnh để tải lên",
				errorNoThumbnail: "Chọn hình thu nhỏ để tải lên",
				errorInvalidPicUrl: "Nhập ảnh hợp lệ (bắt đầu bằng http(s)://, kết thúc bằng jpg, png, gif hoặc bmp). Bạn có thể kết thúc URL bằng '#isImage' để ghi đè quy tắc đó.",
				errorInvalidThumbUrl: "Nhập hình thu nhỏ hợp lệ (bắt đầu bằng http(s)://, kết thúc bằng jpg, png, gif hoặc bmp).",
				errorInvalidVideoUrl: "Nhập URL video hợp lệ (bắt đầu bằng http(s)://)",
				errorNoName: "Nhập tên cho điểm tham quan này",
				errorNoDescription: "Nhập chú thích cho điểm tham quan này",
				errorNoLocation: "Đặt vị trí cho điểm tham quan này"
			},
			builderJS: {
				noPendingChange: "Không có thay đổi chưa được lưu",
				unSavedChangeSingular: "1 thay đổi chưa được lưu",
				unSavedChangePlural: "thay đổi chưa được lưu",
				shareStatus1: "Chuyến tham quan chưa được lưu",
				shareStatus2: "Chuyến tham quan được chia sẻ công khai",
				shareStatus3: "Chuyến tham quan được chia sẻ trong tổ chức",
				shareStatus4: "Chuyến tham quan không được chia sẻ",
				popoverDiscard: "Bạn có chắc chắn muốn hủy mọi thay đổi chưa được lưu không?",
				yes: "Có",
				no: "Không",
				popoverLoseSave: "Bằng cách mở trình xem, bạn sẽ mất mọi thay đổi chưa được lưu",
				ok: "Ok",
				popoverSaveWhenDone: "Đừng quên lưu khi bạn hoàn tất",
				closeWithPendingChange: "Bạn có chắc chắn muốn xác nhận hành động này không? Các thay đổi của bạn sẽ bị mất.",
				gotIt: "Ok",
				savingApplication: "Đang lưu ứng dụng",
				saveSuccess: "Đã lưu ứng dụng thành công",
				saveError: "Lưu thất bại, vui lòng thử lại",
				saveError2: "Lưu thất bại do thẻ html trong tên hoặc mô tả không hợp lệ",
				saveError3: "Không được để trống tiêu đề",
				dragColorPicker: "Di chuyển xung quanh tôi<br />hoặc thay đổi màu sắc của tôi",
				dataWarningExtent: "Bạn có dữ liệu bên ngoài phạm vi bản đồ web. Những dữ liệu đó sẽ không được dùng làm các điểm tham quan, thay đổi phạm vi bản đồ nếu bạn muốn sử dụng chúng.",
				dataWarningVisibi: "Không thể nhìn thấy lớp Map Tour trong phạm vi bản đồ web hiện tại. Xác nhận lớp Map Tour của bạn hiển thị với bản bản đồ lớn %MAPSIZE%.",
				dataWarningEdit: "Sửa bản đồ web",
				dataWarningClose: "Đóng",
				signIn: "Vui lòng đăng nhập bằng một tài khoản vào",
				signInTwo: "để lưu ứng dụng.",
				switchBM: "Thay đổi Bản đồ nền"
			},
			organizePopupJS: {
				messageStart: "Bạn đã chọn xóa",
				messageSinglePoint: "một điểm tham quan",
				messageMultiPoint: "các điểm tham quan",
				messagePermantRemove: "Điều này sẽ xóa vĩnh viễn",
				messageRecord: "hồ sơ",
				messageRecordPlural: "các hồ sơ",
				messageConfirm: "khỏi cơ sở dữ liệu của bạn. Bạn có muốn tiếp tục không?",
				labelButtonShow: "Hiển thị",
				labelButtonHide: "Ẩn"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Thao tác này sẽ xóa vĩnh viễn ảnh và hình thu nhỏ",
				popoverDeleteWarningThumb: "Thao tác này sẽ xóa vĩnh viễn hình thu nhỏ",
				popoverUploadingPhoto: "Đang tải ảnh và hình thu nhỏ lên",
				popoverUploadingThumbnail: "Đang tải hình thu nhỏ lên",
				popoverUploadSuccessful: "Tải lên thành công",
				popoverUploadError: "Tải lên thất bại, vui lòng thử lại",
				changePicAndThumb: "Thay đổi ảnh",
				changeThumb: "Thay đổi hình thu nhỏ",
				selectPic: "Thay đổi phương tiện",
				selectThumb: "Thay đổi hình thu nhỏ",
				uploadPicAndThumb: "Áp dụng"
			},
			headerJS:{
				editMe: "Chỉnh sửa tôi!",
				templateTitle: "Thiết lập tiêu đề mẫu",
				templateSubtitle: "Thiết lập phụ đề mẫu"
			},
			crossFaderJS:{
				setPicture: "Đặt tiêu đề ảnh",
				setCaption: "Đặt chú thích ảnh"
			},
			importPopup: {
				title: "Nhập",
				prevBtn: "Quay lại",
				nextBtn: "Tiếp"
			},
			importPopupHome: {
				header: "Ảnh của bạn được lưu ở đâu ?"
			},
			onlinePhotoSharingCommon: {
				pictures: "ảnh",
				videos: "video",
				disabled: "Người quản trị đã vô hiệu hóa tính năng này",
				disabledPortal: "Tính năng này bị vô hiệu hóa trên Portal for ArcGIS",
				header1: "Ảnh của bạn phải được chia sẻ công khai.",
				header2: "Việc nhập sẽ bị giới hạn đối với %NB1% %MEDIA% đầu tiên.",
				emptyDataset: "Lỗi, không tìm thấy ảnh",
				footerImport: "Nhập",
				selectAlbum: "Chọn một album công khai",
				selectAlbum2: "Chọn một album",
				pleaseChoose: "Vui lòng chọn",
				userLookup: "Tìm kiếm",
				userLookingup: "Đang tìm kiếm",
				csv: "Tham chiếu trong một CSV",
				advanced: "Tùy chọn nâng cao",
				advancedScratchLbl: "Bắt đầu một Chuyến tham quan mới",
				advancedScratchTip: "Tạo một Chuyến tham quan trống mà bạn có thể nhập thủ công bằng một thuật sĩ.",
				advancedCSVLbl: "Nhập dữ liệu Chuyến tham quan từ một tệp CSV",
				advancedCSVTip: "Nhập nội dung Chuyến tham quan từ một tệp CSV.",
				advancedCommonTip: "Yêu cầu ảnh và video của bạn hiện đang trực tuyến.",
				select: "Lựa chọn",
				locUse: "Sử dụng vị trí địa lý ảnh",
				locExplain: "Bạn có thể không muốn sử dụng vị trí ảnh vì chúng có thể được kế thừa từ album, dẫn đến tất cả ảnh đều ở cùng một vị trí.",
				locExplain2: "Bạn có thể không muốn sử dụng vị trí video vì chúng có thể được kế thừa từ thiết lập người dùng, dẫn đến tất cả video đều ở cùng một vị trí."
			},
			viewFlickr: {
				title: "Nhập từ Flickr",
				header: "Nhập tên đăng nhập Flickr của bạn và chọn một Tập ảnh hoặc một Thẻ cần nhập.",
				userInputLbl: "Nhập Tên đăng nhập",
				signInMsg2: "Không tìm thấy người dùng",
				selectSet: "Chọn một Tập ảnh",
				selectTag: "hoặc chọn một Thẻ",
				footerImportTag: "Nhập Thẻ được chọn",
				footerImportSet: "Nhập Tập ảnh được chọn"
			},
			viewFacebook: {
				title: "Nhập từ Facebook",
				header: "Xác thực bằng Tài khoản Người dùng Facebook của bạn hoặc sử dụng một Trang Công cộng. Album cá nhân có thể được sử dụng để tạo Map Tour công khai mà không yêu cầu xác thực người dùng Facebook, cho phép bình luận và thích để duy trì tính riêng tư.",
				leftHeader: "Người dùng Facebook",
				rightHeader: "Trang Facebook",
				pageExplain: "Trang Facebook là một thương hiệu/sản phẩm công cộng hay nổi tiếng như <b>esrigis</b>. Bạn có thể lấy tên trang sau '/' đầu tiên trong URL trang.",
				pageInputLbl: "Nhập tên trang",
				lookupMsgError: "Không tìm thấy trang"
			},
			viewPicasa: {
				title: "Nhập từ Picasa/Google+",
				header: "Nhập địa chỉ email của bạn hoặc ID tài khoản Picasa hoặc Google+ của bạn.",
				userInputLbl: "Nhập email hoặc ID",
				signInMsg2: "Không tìm thấy tài khoản",
				signInMsg3: "Không có album công khai nào",
				howToFind: "Cách tìm ID tài khoản Picasa hoặc Google+",
				howToFind2: "Sao chép chữ số giữa '/' đầu tiên và thứ hai của bất kỳ trang Picasa hoặc G+ nào"
			},
			viewCSV: {
				title: "Nhập từ CSV",
				uploadBtn: "Chọn hoặc thả một tệp CSV",
				resultHeaderEmpty: "CSV trống",
				resultHeaderSuccess: "Đã tải thành công %NB_POINTS% điểm",
				resultHasBeenLimited: "Nhập đã được giới hạn đối với điểm %VAL1% đầu tiên trên tổng số %VAL2% để theo giới hạn %VAL3% điểm trên mỗi chuyến tham quan",
				browserSupport: "Trình duyệt của bạn không được hỗ trợ, để sử dụng một CSV bạn phải <a href='http://browsehappy.com/' target='_blank'>nâng cấp trình duyệt của bạn</a> hoặc sử dụng trình xem bản đồ web ArcGIS.com (xem Trợ giúp).",
				errorLatLng: "Không tìm thấy trường Vĩ độ và Kinh độ. Giá trị có thể cho vĩ độ là: <i>%LAT%</i> và kinh độ là: <i>%LONG%</i>.",
				errorFieldsExplain: "Tải thất bại vì không tìm thấy các trường bắt buộc dưới đây",
				errorFieldsName: "<b>Tên</b> các giá trị có thể là: %VAL%",
				errorFieldsDesc: "<b>Mô tả</b> các giá trị có thể là: %VAL%",
				errorFieldsUrl: "<b>URL ảnh</b> các giá trị có thể là: %VAL%",
				errorFieldsThumb: "<b>URL hình thu nhỏ</b> các giá trị có thể là: %VAL%",
				errorFields2Explain: "Tải thất bại do CSV không sử dụng các thuộc tính giống như lớp đối với các thuộc tính sau",
				errorFields2Name: "<b>Tên</b> sử dụng %VAL1% thay vì %VAL2%",
				errorFields2Desc: "<b>Mô tả</b> sử dụng %VAL1% thay vì %VAL2%",
				errorFields2Url: "<b>URL ảnh</b> sử dụng %VAL1% thay vì %VAL2%",
				errorFields2Thumb: "<b>URL hình thu nhỏ</b> sử dụng %VAL1% thay vì %VAL2%",
				resultFieldsAll: "Đã nhập hết các thuộc tính",
				resultFieldsNotAll: "Không nhập các thuộc tính sau đây vì chúng không tồn tại trong lớp bản đồ",
				resultFieldsNotAll2: "Đã nhập các thuộc tính sau đây",
				footerNextBtnResult: "Nhập vào bản đồ web",
				footerProgress: "Đang nhập",
				footerSucceed: "Nhập thành công. Đang tải"
			},
			viewYoutube: {
				title: "Nhập từ YouTube",
				header: "Nhập tên đăng nhập YouTube để tìm video chia sẻ công khai.",
				pageInputLbl: "Nhập tên người dùng YouTube",
				lookupMsgError: "Không tìm thấy người dùng",
				howToFind: "Cách tìm tên đăng nhập Youtube",
				howToFind2: "Tên đăng nhập được hiển thị dưới video",
				found: "Tìm thấy",
				noData: "Không tìm thấy video công khai"
			},
			viewGeoTag: {
				title: "Chọn và định vị ảnh/video của bạn",
				header: "Bấm hoặc gõ nhẹ vào ảnh bạn muốn nhập để định vị chúng.",
				headerMore: "Tại sao không định vị địa lý được ảnh/video?",
				headerExplain: "Nếu ảnh của bạn có một vị trí địa lý hợp lệ, chúng sẽ được tự động đặt trên bản đồ và được liệt kê vào tab thứ hai.<br /><br />Theo mặc định, Picasa và Flickr không lưu trữ siêu dữ liệu EXIF định vị địa lý khi bạn nhập ảnh. Kiểm tra thiết lập bảo mật Picasa/Flickr để cho phép nhập vị trí địa lý ảnh và sử dụng bởi ứng dụng bên ngoài. Bạn có thể phải nhập lại ảnh hiện tại của bạn vào Flickr/Picasa để sử dụng vị trí địa lý EXIF.<br /><br />Trên Facebook, bạn phải vào từng hình ảnh, nhấp vào Sửa và chọn vị trí.",
				leftPanelTab1: "Để định vị",
				leftPanelTab2: "Được định vị",
				clickOrTap: "Bấm hoặc gõ nhẹ vào Bản đồ để định vị",
				clearLoc: "Xóa vị trí",
				clickDrop: "Không nhập",
				footerImport: "Nhập",
				footerProgress: "Đang nhập",
				footerSucceed: "Nhập thành công. Đang tải...",
				loading: "Đang tải",
				error: "Nhập vị trí địa lý ảnh thất bại, đã bỏ qua các vị trí địa lý."
			},
			initPopup: {
				title: "Chào mừng bạn đến Bộ thiết lập Map Tour",
				prevBtn: "Quay lại",
				nextBtn: "Tiếp"
			},
			initPopupHome: {
				header1: "Ảnh hoặc video của bạn ở đâu?",
				header2: "Bộ trợ giúp này sẽ giúp bạn xây dựng một Map Tour từ phương tiện đã được lưu trữ trực tuyến hoặc nó sẽ nhập chúng vào ArcGIS Online cho tài khoản Tổ chức.",
				title1: "Chúng đã trực tuyến",
				title2: "Tôi cần tải lên ảnh của mình",
				hostedFSTooltip: "Sử dụng ArcGIS Online để lưu trữ ảnh của bạn (không hỗ trợ video).",
				hostedFsNA: "Chỉ khả dụng cho người dùng ArcGIS dành cho Tổ chức, Nhà xuất bản và Người quản trị",
				footer1: "Khi bạn làm xong, đừng quên chia sẻ Map Tour của bạn với khán giả thông qua trang mục ứng dụng.",
				footer3: "Tải xuống mẫu CSV",
				footer4: "\"Lưu thành\" nếu nó không tải xuống",
				footer4bis: "Bấm chuột phải và \"Lưu thành\" nếu quá trình tải xuống không bắt đầu",
				footer5: "Tìm hiểu thêm",
				footerProgress: "Đang tạo",
				footerSucceed: "Tạo thành công. Đang tải..."
			},
			helpPopup: {
				title: "Trợ giúp",
				close: "Đóng",
				tab1: {
					title: "Giới thiệu",
					div1: "Mẫu Map Tour được thiết kế để trình bày thông tin địa lý, ở đây có một bộ phận truyền thông và nhiếp ảnh hấp dẫn cho câu chuyện bạn muốn kể.",
					div2: "Mẫu tạo ra một ứng dụng web hấp dẫn và dễ sử dụng cho phép bạn trình bày một tập hợp địa điểm nhỏ trên bản đồ theo chuỗi được đánh số mà qua đó người dùng có thể duyệt. Mẫu được thiết kế để được sử dụng trong bất kỳ trình duyệt web trên bất kỳ thiết bị nào, bao gồm cả điện thoại thông minh và máy tính bảng. <br /><br /> Dưới đây là một ví dụ về loại ứng dụng mà bạn có thể tạo ra:",
					div4: "<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Map Tour tại Palm Springs</a>.",
					div42: "Để xem ví dụ về các map tour mà người dùng khác đang tạo, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>truy cập phòng trưng bày</a> trên <a href='http://storymaps.arcgis.com/' target='_blank'>trang web Story Maps</a>. Bạn cũng có thể theo dõi chúng tôi trên Twitter tại <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
					div5: "Chúng tôi muốn nhận phản hồi từ bạn! Cho dù bạn có một câu hỏi, muốn yêu cầu một tính năng mới hoặc cho rằng bạn đã tìm thấy một lỗi, vui lòng truy cập <a href='http://links.esri.com/storymaps/forum' target='_blank'>Diễn đàn Người dùng Story Maps</a>."
				},
				tab2: {
					title: "Dữ liệu",
					div1: "Đối tượng chính cần xem xét khi xây dựng một Map Tour là chọn nơi hình ảnh của bạn sẽ được lưu trữ. Một Map Tour có thể sử dụng hình ảnh được lưu trữ trên các dịch vụ chia sẻ hình ảnh lớn, trên bất kỳ máy chủ web hoặc theo tệp đính kèm một dịch vụ đối tượng.",
					div1a: "Xem phần cuối cùng của tab này để biết chi tiết về các định dạng hình ảnh và video được hỗ trợ.",
					div2: "Bộ dựng tương tác cung cấp cho bạn hai lựa chọn để xử lý các hình ảnh của bạn trên Map Tour:",
					div3: "<ul><li>Bạn có thể sử dụng <b>hình ảnh đã trực tuyến</b>, chẳng hạn như hình ảnh được lưu trữ trong một trang web chia sẻ hình ảnh như Flickr hoặc hình ảnh được lưu trữ trên trang web của riêng bạn. Những hình ảnh này sẽ được tham chiếu trong Map Tour của bạn thông qua URL của chúng.</li><li>Bạn cũng có thể <b>tải lên hình ảnh trực tiếp từ máy tính của bạn</b> vào Map Tour của bạn. Tùy chọn tải lên này yêu cầu bạn có một tài khoản ArcGIS dành cho Tổ chức và bạn có đặc quyền của Nhà xuất bản hoặc Người quản trị, bởi vì một dịch vụ đối tượng lưu trữ sẽ được tự động tạo cho bạn, trong đó hình ảnh của bạn được lưu trữ dưới dạng tệp đính kèm.</li></ul>",
					div4: "Các trường hợp sử dụng chính là:",
					div4b: "<b>Hình ảnh của bạn vẫn chưa được lưu trữ</b> và bạn có tài khoản ArcGIS dành cho Tổ chức: Sử dụng một dịch vụ đối tượng lưu trữ là sự lựa chọn tốt nhất của bạn. Giống như các dịch vụ chia sẻ hình ảnh công khai, chúng tôi sẽ tối ưu hóa hình ảnh của bạn để tạo các ảnh tải nhanh và bạn sẽ có quyền truy cập vào tất cả các khả năng quản lý và quản trị dữ liệu của nền tảng ArcGIS.",
					div5: "<b>Bạn không phải là thành viên của một Tổ chức</b>: Trước tiên, bạn phải tải ảnh của mình lên một trang web chia sẻ hình ảnh hoặc máy chủ web của riêng bạn. Bộ dựng sẽ giúp bạn sử dụng những ảnh vẫn tiếp tục được lưu trữ tại vị trí ban đầu của họ.",
					div6: "<b>Bạn đang muốn sử dụng lại một Dịch vụ Đối tượng hiện có</b> lưu trữ hình ảnh của bạn dưới dạng tệp đính kèm hoặc tham chiếu ảnh bên ngoài: Xem phần chi tiết dưới đây.",
					div7: "<b>Bạn là một người dùng phiên bản mẫu Map Tour trước</b> và đã có CSV tham chiếu ảnh và hình thu nhỏ của bạn: Bạn có thể nhập nó và tinh chỉnh dữ liệu của bạn. Bộ dựng chỉ hỗ trợ các CSV sử dụng các trường kinh độ/vĩ độ; CSV theo địa chỉ có thể tiếp tục được sử dụng thông qua bản đồ web của bạn (xem phần dưới đây).",
					div8: "Nhập từ các dịch vụ chia sẻ hình ảnh trực tuyến",
					div9: "Thao tác nhập tham chiếu ảnh đã được lưu trữ bằng cách lưu trữ các URL của chúng vào một bộ sưu tập tính năng bản đồ web. Các ảnh không được lưu trữ trong ArcGIS Online. Nếu không thể truy cập vào ảnh được lưu trữ, chúng sẽ không có trong Map Tour và bạn sẽ thấy một hình ảnh 'Ảnh không khả dụng'. Tùy thuộc vào nhà cung cấp dịch vụ hình ảnh, Map Tour có thể không nhập tên, mô tả và vị trí ảnh. Những thuộc tính đó được lưu trữ trong bản đồ web và bất kỳ sửa đổi dịch vụ trực tuyến nào sẽ không được phản ánh trong Map Tour.",
					div10: "Lưu trữ các ảnh trên một máy chủ web",
					div11: "Nếu bạn chọn tự lưu trữ ảnh, bạn sẽ phải tạo hình thu nhỏ ảnh của bạn thủ công. Sử dụng các hình ảnh độ phân giải đầy đủ cho hình thu nhỏ sẽ dẫn đến hiệu quả kém. Vì lý do đó, chúng tôi khuyên bạn nên sử dụng một dịch vụ chia sẻ ảnh trực tuyến hoặc dịch vụ đối tượng giúp bạn làm điều đó.",
					div12: "Sử dụng một Dịch vụ Đối tượng hiện có hoặc Shapefile",
					div13: "Có thể sử dụng bất kỳ dịch vụ đối tượng điểm hoặc shapefile nào để làm nguồn dữ liệu Map Tour. Bạn chỉ cần thêm nó như là một lớp vào bản đồ web của bạn thông qua Trình xem Bản đồ arcgis.com. Nếu ứng dụng phát hiện các thuộc tính dự kiến ​​trong lớp của bạn, tất cả các chức năng bộ dựng sẽ khả dụng.",
					div14: "Các giá trị có thể cho các trường tên là (không phân biệt chữ hoa/chữ thường):",
					div151: "Tên",
					div152: "Mô tả",
					div153: "Ảnh",
					div154: "Hình thu nhỏ",
					div155: "Màu ",
					div16: "Nếu ứng dụng không tìm thấy các trường phù hợp khi sử dụng một dịch vụ đối tượng, trình xem sẽ không hoạt đọng cho đến khi bạn cấu hình các trường được sử dụng thông qua bộ dựng. CSV và lớp shapefile được thêm vào bản đồ web cần phải có tất cả các trường bắt buộc hoặc bộ dựng sẽ không hoạt động.",
					div162: "Khi sử dụng một dịch vụ đối tượng lưu trữ các hình ảnh dưới dạng đính kèm, <b>chỉ các tính năng có hai tệp đính kèm sẽ được sử dụng</b>. Tệp đính kèm đầu tiên xác định ảnh chính và tệp đính kèm thứ hai xác định hình thu nhỏ.",
					div17: "Các trường ảnh và hình thu nhỏ là trường bắt buộc đối với các dịch vụ đối tượng mà không có tệp đính kèm và tùy chọn (nhưng hoàn toàn khuyến khích) cho các dịch vụ đối tượng có tệp đính kèm. Nếu dịch vụ của bạn đã kích hoạt tệp đính kèm, bộ dựng sẽ cho phép bạn tải lên ảnh dưới dạng tệp đính kèm. Nếu không, bạn sẽ chỉ có thể chỉnh sửa URL ảnh và hình thu nhỏ.",
					div172: "Khi có, các trường ảnh và hình thu nhỏ sẽ luôn luôn được sử dụng và các tệp đính kèm dịch vụ đối tượng sẽ không được truy vấn.",
					div173: "Các CSV và shapefile mẫu có thể được tải về từ",
					div18: "Tạo Dịch vụ Đối tượng được lưu trữ từ một CSV hoặc shapefile",
					div19: "Khi bạn tạo một dịch vụ đối tượng lưu trữ từ một CSV hoặc shapefile, các tệp đính kèm không được kích hoạt theo mặc định. Để kích hoạt chúng, mở trang chi tiết dịch vụ đối tượng, bấm vào mũi tên nhỏ ở phần lớp và bạn sẽ thấy tùy chọn đó. Map Tour sẽ tiếp tục sử dụng ảnh và hình thu nhỏ mà bạn được tham chiếu thông qua các thuộc tính. Tùy chọn, nếu bạn muốn tải ảnh của bạn lên dưới dạng tệp đính kèm dịch vụ đối tượng, bạn sẽ có thể làm như vậy thông qua hai nút trên bảng điều khiển hình ảnh (\"Thay đổi Ảnh\" và \"Thay đổi Hình thu nhỏ\").",
					div20: "Định dạng hình ảnh và video được hỗ trợ",
					div21: "Định dạng ảnh được hỗ trợ: <b>.jpg, .jpeg, .png, .gif và .bmp</b>. Nếu phương tiện của bạn không kết thúc với phần mở rộng đó, Map Tour sẽ coi nó là một video, trừ khi sử dụng một dịch vụ đối tượng (xem bên dưới).",
					div22: "Mẫu Map Tour không bao gồm trình phát video, do đó bạn phải sử dụng trình phát video bên ngoài được cung cấp bởi dịch vụ lưu trữ video yêu thích của bạn (tìm tùy chọn để nhúng video và sao chép URL hiện tại vào mã nhất định). Nếu bạn muốn tự lưu trữ các video, bạn có thể tạo một trang HTML có chứa một trình phát video như <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Bộ dựng tương tác không cung cấp một hộp thoại để kèm video khi sử dụng dịch vụ đối tượng có tệp đính kèm, nhưng có thể làm như vậy bằng cách sửa dữ liệu bên ngoài bộ dựng tương tác. Trong trình xem bản đồ arcgis.com, nếu bạn sửa đổi các trường ảnh để trỏ đến một video bên ngoài và thêm một tham số đặc biệt vào cuối URL của bạn (#isVideo), phương tiện của bạn sẽ được coi là một video.",
					div24: "Lưu ý rằng bạn vẫn cần phải có hai tệp đính kèm ảnh hợp lệ hoặc điểm sẽ không được sử dụng. Không thể sử dụng video khi sử dụng tệp đính kèm dịch vụ đối tượng mà không có các trường ảnh và hình thu nhỏ."
				},
				tab3: {
					title: "Tùy chỉnh",
					div1: "Bộ dựng cung cấp một số tùy chọn tùy chỉnh có thể truy cập qua nút THIẾT ĐẶT trong bảng điều khiển trên cùng. Nếu bạn không tìm thấy các tùy chọn mà bạn mong đợi, chúng tôi cũng cung cấp một phiên bản tải về mà bạn có thể triển khai trên máy chủ web của bạn và nâng cao để phù hợp với nhu cầu của bạn.",
					div2: "Chúng tôi khuyên bạn nên sử dụng phiên bản lưu trữ, trừ khi:",
					div3: "<li>Nó không cung cấp chức năng tùy chỉnh Giao diện người dùng mà bạn muốn có, như sử dụng một hình nền đầu mục.</li><li>Bạn là một nhà phát triển và bạn muốn tăng cường ứng dụng.</li>",
					div4: "Có thể cấu hình phiên bản tải về thông qua một bản đồ web hoặc định danh ứng dụng bản đồ web. Các tình huống sử dụng chính là:",
					div41: "Bạn xây dựng map tour của mình bằng bộ dựng tương tác trong môi trường lưu trữ và cấu hình mẫu bằng định danh ứng dụng bản đồ web. Các thiết lập bạn đã xác định với bộ dựng tương tác sẽ được áp dụng.",
					div42: "Bạn xây dựng bản đồ web của mình bên ngoài bộ dựng tương tác và cấu hình mẫu bằng định danh bản đồ web. Bạn sẽ phải đọc tài liệu để tìm hiểu cách cấu hình mẫu.",
					div43: "Lưu ý rằng bộ dựng tương tác khả dụng trong phiên bản có thể tải về nhưng có một số hạn chế về kỹ thuật trên các trình duyệt như Internet Explorer cũ hơn phiên bản 10.",
					div5: "Để tải về phiên bản mẫu mới nhất và tìm hiểu thêm về cách sử dụng, hãy truy cập <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>trang dự án GitHub</a>."
				},
				tab4: {
					title: "Mẹo",
					div0: "Trình duyệt hỗ trợ",
					div0a: "Trình xem Map Tour được hỗ trợ trên IE8+. Bộ dựng tương tác được hỗ trợ trên IE9+. Chúng tôi tích cực thử nghiệm nó trên tất cả các trình duyệt, nhưng nếu bạn gặp một số khó khăn, chúng tôi khuyên bạn nên sử dụng Chrome.",
					div0b: "Nếu bạn gặp phải một số khó khăn, vui lòng cho chúng tôi biết. Trong khi đó, với việc xây dựng Map Tour của bạn bằng cách sử dụng mẫu CSV, bạn sẽ giảm thiểu sự tương tác của mình với giao diện bộ dựng.",
					div1: "Ảnh",
					div2: "Chúng tôi khuyến khích ảnh hướng ngang thay vì ảnh hướng dọc. Hình ảnh với tỷ lệ khung hình 4:3 phù hợp nhất. Có thể sử dụng ảnh hướng dọc, nhưng trên màn hình nhỏ hơn như iPad, rất nhiều bức ảnh có thể bị che khuất bởi chú thích (văn bản chiếm nhiều không gian hơn khi nó được hiển thị trong một khu vực cao so với một khu vực rộng). Mặc dù hình ảnh có các kích cỡ, hình dạng và hướng khác nhau có thể được sử dụng trong một Map Tour, chúng tôi khuyên bạn nên sử dụng cùng một kích thước và hình dạng cho tất cả các hình ảnh. Bằng cách này, người dùng sẽ không bị phân tâm bởi những hình ảnh có kích thước khác nhau khi họ theo dõi chuyến tham quan.",
					div2a: "Chúng tôi khuyến khích sử dụng kích thước hình ảnh tối đa là chiều rộng 1000 điểm ảnh x chiều cao 750 điểm cho hình ảnh chính và 140x93 cho hình thu nhỏ.",
					div3: "Định dạng văn bản chú thích của bạn bằng cách sử dụng các thẻ HTML",
					div4: "Đầu mục và tiêu đề/chú thích ảnh có thể bao gồm các thẻ HTML để xác định định dạng và liên kết. Ví dụ: mã này sẽ thêm một liên kết màu vàng:",
					div4a: "Viết phụ đề hay cho chuyến tham quan của bạn",
					div4b: "Hãy dành thời gian để viết phụ đề hấp dẫn cho chuyến tham quan của bạn. Phụ đề là một cách hay để thu hút mọi người vào chuyến tham quan và cho họ biết những điều họ sẽ khám phá ra trong đó. Nó cũng là một nơi tốt để cho khán giả của bạn biết chuyến tham quan diễn ra tại tiểu bang hoặc quốc gia nào. Ví dụ: giả sử mọi người không biết thành phố hoặc thị xã diễn ra chuyến tham quan. Chú thích của bạn cũng có thể được định dạng bằng cách sử dụng các thẻ HTML, chẳng hạn như liên kết bao gồm. Đừng tạo chú thích quá dài. Trong cửa sổ trình duyệt nhỏ hơn hoặc trên iPad, nó có thể không hoàn toàn vừa và bị cắt bớt. Nếu bạn không thể nghĩ ra một phụ đề hay, hãy để trống.",
					div5: "Lớp Hỗ trợ",
					div6: "Bạn có thể thêm các lớp hỗ trợ bổ sung để cung cấp bối cảnh cho Map Tour. Những lớp này có thể chứa các đặc điểm địa lý khác mà bạn muốn bản đồ thể hiện ngoài các điểm Map Tour, chẳng hạn như một khu vực nghiên cứu, một tuyến đường đi bộ hoặc lái xe đến các điểm tham quan của bạn, v.v. Mẫu Map Tour sẽ hiển thị các lớp hỗ trợ bổ sung bằng biểu tượng mà bạn chỉ định trong bản đồ trang web, nhưng không khả dụng cửa sổ pop-up.",
					div7: "Giữ cho chuyến tham quan của bạn ngắn gọn và ngọt ngào",
					div8: "Giới hạn 99 điểm cho mỗi chuyến tham quan. Dĩ nhiên, hầu hết Map Tour sẽ ngắn hơn nhiều. Đừng nghĩ rằng khán giả của bạn muốn đi qua quá nhiều điểm tham quan. Bạn có thể thấy chủ đề của bạn hấp dẫn, nhưng đừng cho rằng họ cũng nghĩ như vậy!",
					div9: "Để tìm hiểu thêm, xem <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>hướng dẫn chi tiết</a>.",
					div10: "Chế độ nhúng",
					div11: "Nếu bạn muốn nhúng mẫu vào một trang web khác thông qua một iframe, thêm tham số tùy chọn \"&embed\" vào cuối URL sẽ xóa đầu mục. Chế độ đó cũng có thể được thiết lập trong phiên bản tải về thông qua tệp cấu hình.",
					div12: "Tránh sử dụng chiều rộng iFrame hẹp dẫn đến map tour chuyển sang bố cục màn hình cảm ứng nhỏ. Để dễ sử dụng nhất. Khi bạn nhúng một map tour, chúng tôi luôn khuyến khích bạn vẫn cung cấp một liên kết bên cạnh chuyến tham quan đã nhúng để người dùng có thể khởi chạy chuyến tham quan ở chế độ toàn màn hình." 
				},
				tab5: {
					title: "Đang xuất bản",
					div1: "Khi bạn làm xong, đừng quên chia sẻ Map Tour của bạn với khán giả thông qua các nút CHIA SẺ hoặc trang mục ứng dụng trên ArcGIS Online.",
					div2a: "Chia sẻ Chuyến tham quan thông qua bộ dựng",
					div2b: "Nút CHIA SẺ sẽ cập nhật ứng dụng và các mục trên bản đồ web. Nếu dữ liệu Chuyến tham quan của bạn được lưu trữ trong một mục Dịch vụ Đối tượng, nó cũng sẽ được cập nhật. Nếu bạn đã thêm các lớp khác thông qua trình xem bản đồ ArcGIS.com, chúng sẽ không được cập nhật. Điều này có thể dẫn đến Chuyến tham quan không được chia sẻ như bạn mong đợi. Các mục đã có một (hoặc nhiều) đặc quyền bắt buộc sẽ không được cập nhật.",
					div2c: "Chia sẻ Chuyến tham quan qua ArcGIS Online",
					div2d: "Khi bạn chia sẻ ứng dụng thông qua ArcGIS Online, nếu cần nó sẽ yêu cầu bạn cập nhật bất kỳ tài nguyên phụ thuộc nào (bản đồ trang web, dịch vụ đối tượng, lớp trang trí) không được chia sẻ theo cùng một cách. Nếu Map Tour công khai và một trong những tài nguyên của bạn không được chia sẻ với khán giả, người dùng sẽ được chuyển hướng đến trang đăng nhập ArcGIS Online.",
					div3t: "Bảo mật Dịch vụ Đối tượng",
					div3a: "Nếu bạn đang sử dụng một dịch vụ đối tượng lưu trữ được tạo ra qua bộ dựng Map Tour, ứng dụng quản lý dịch vụ an ninh cho bạn và bạn sẽ vẫn là người duy nhất có quyền sửa, ngay cả khi bạn chia sẻ dịch vụ công khai.",
					div3t2: "Trước khi chia sẻ Chuyến tham quan của bạn với khán giả",
					div3: "Đảm bảo rằng Chuyến tham quan hoạt động tốt khi bạn không đăng nhập bằng tài khoản ArcGIS.com của bạn. URL mà bạn sẽ sử dụng không được chuyển hướng đến trang đăng nhập hoặc chế độ bộ dựng.",
					div4: "Đó là một ý tưởng hay để biết giao diện map tour của bạn trên iPad khi giữ theo hướng ngang nhằm đảm bảo nhìn đẹp trên thiết bị phổ biến này. Điều này có thể giúp bạn xem liệu có quá nhiều chú thích trên ảnh không. Nó cũng cho phép bạn xem liệu phụ đề có phù hợp và không quá dài để còn cắt bớt.",
					div5a: "Lời khuyên cho tìm kiếm",
					div5b: "Để giúp mọi người tìm thấy Map Tour của bạn nếu họ tìm kiếm trên ArcGIS Online, chúng tôi khuyên bạn nên thêm các từ khóa 'story map' vào trang mục ứng dụng bản đồ du lịch của bạn (không phải trang mục bản đồ web của bạn), cùng với các thẻ như tên tiểu bang hoặc quận nơi diễn ra chuyến tham quan, tên nước nếu không phải Hoa Kỳ và các thẻ theo chủ đề như 'nghệ thuật công cộng', 'hướng dẫn du lịch' hay 'di tích lịch sử'. Các thẻ này cũng giúp chúng tôi tại Esri tìm ví dụ mới thú vị về các chuyến tham quan mà chúng tôi có thể giới thiệu tại bộ sưu tập ảnh của chúng tôi và thúc đẩy phương tiện truyền thông xã hội. Chúng tôi cũng khuyến khích bạn nên tải lên đồ họa thu nhỏ đẹp mắt vào trang mục ứng dụng của bạn, chẳng hạn như là một ảnh chụp màn hình nhỏ của chuyến tham quan hoặc một trong các hình ảnh trong đó. Bức ảnh này được sử dụng tự động nếu map tour của bạn được thêm vào một bộ sưu tập ảnh ArcGIS Online."
				}
			},
			share: {
				firstSaveTitle: "Đã lưu chuyến tham quan thành công",
				firstSaveHeader: "Chuyến tham quan hiện được lưu trên ArcGIS Online. Vui lòng đọc các câu trả lời cho các câu hỏi thường gặp sau đây.",
				firstSaveA1: "Nếu bạn không quen với ArcGIS Online hoặc muốn có một phím tắt để truy cập vào giao diện tác nghiệp, bạn có thể lưu liên kết sau đây:%LINK1%",
				firstSaveA1bis: "Cũng có thể tìm thấy Chuyến tham quan trong <a href='%LINK2%' target='_blank'>thư mục nội dung ArcGIS Online</a> của bạn.",
				firstSaveQ2: "Chuyến tham quan của tôi có được chia sẻ không?",
				firstSaveA2: "Hiện tại Chuyến tham quan của bạn không được chia sẻ. Để chia sẻ nó, dùng nút CHIA SẺ.",
				shareTitle: "Chia sẻ Chuyến tham quan của bạn",
				sharePrivateHeader: "Chuyến tham quan của bạn không được chia sẻ, bạn có muốn chia sẻ nó không?",
				sharePrivateBtn1: "Chia sẻ công khai",
				sharePrivateBtn2: "Chia sẻ với Tổ chức của tôi",
				sharePrivateProgress: "Đang tiến hành chia sẻ...",
				sharePrivateErr: "Chia sẻ thất bại, thử lại hoặc",
				sharePrivateOk: "Chia sẽ cập nhật thành công, đang tải...",
				sharePreviewAsUser: "Xem trước",
				shareHeader1: "Có thể truy cập <strong>Chuyến tham quan của bạn công khai</strong>.",
				shareHeader2: "Các thành viên trong tổ chức của bạn có thể truy cập Chuyến tham quan (yêu cầu đăng nhập).",
				shareLinkHeader: "Chia sẻ Chuyến tham quan với người xem",
				shareLinkOpen: "MỞ",
				shareQ1Opt1: "Làm cách nào để giữ Chuyến tham quan riêng tư?",
				shareQ1Opt2: "Làm cách nào để giữ Chuyến tham quan riêng tư hoặc chia sẻ công khai?",
				shareA1: "Sử dụng %SHAREIMG% trên <a href='%LINK1%' target='_blank'>trang mục ứng dụng</a>. Nếu bạn cũng muốn hủy chia sẻ bản đồ web, sử dụng <a href='%LINK2%' target='_blank'>trang mục bản đồ web</a>.",
				shareA1bis: "Nếu bạn cũng muốn hủy chia sẻ Dịch vụ Đối tượng, sử dụng <a href='%LINK1%' target='_blank'>trang mục Dịch vụ Đối tượng</a>.",
				shareQ2: "Làm cách nào để sửa Chuyến tham quan sau này?",
				shareQ2bis: "Làm cách nào để quay lại giao diện tác nghiệp?",
				shareA2div1: "Lưu và sử dụng lại liên kết sau %LINK1% hoặc sử dụng <a href='%LINK2%' target='_blank'>trang mục ứng dụng</a>.",
				shareA2div2: "Là chủ sở hữu của ứng dụng, khi bạn đăng nhập vào ArcGIS.com, ứng dụng có một nút để mở bộ thiết lập tương tác:",				
				shareQ3: "Dữ liệu được lưu trữ ở đâu?",
				shareA3: "Cấu hình Chuyến tham quan được lưu trữ trong <a href='%LINK1%' target='_blank'>mục bản đồ web này</a> và <a href='%LINK2%' target='_blank'>mục ứng dụng web này</a>. Ảnh Flickr, Picasa và Facebook và video YouTube vẫn được tham chiếu tại các trang web tương ứng và không bị trùng lặp trong ArcGIS Online.",
				shareWarning: "Chia sẻ %WITH% đã bị vô hiệu hóa vì bạn không phải là chủ sở hữu <a href='%LINK%' target='_blank'>bản đồ web</a>.",
				shareWarningWith1: "công khai",
				shareWarningWith2: "công khai và với Tổ chức"
			}
        }
    })
);
