define(
({
		viewer: {
			loading: {
				step1: "正在加载应用程序",
				step2: "正在加载数据",
				step3: "正在初始化浏览",
				loadBuilder: "切换到构建器模式",
				fail: "抱歉，地图浏览加载失败",
				failButton: "重试"
			},
			errors: {
				boxTitle: "发生错误",
				invalidConfig: "严重错误: 配置无效",
				invalidConfigOwner: "严重错误: 配置无效(需要授权的所有者)",
				invalidConfigNoWebmap: "严重错误: 配置无效(需要 web 地图和授权的所有者)",
				createMap: "无法创建地图",
				invalidApp: "严重错误: 无法加载应用程序",
				noLayer: "Web 地图不包含适用于地图浏览的有效数据图层。",
				noLayerMobile: "欢迎使用地图浏览 web 应用程序。该应用程序未配置。移动设备不支持地图浏览构建器。",
				noLayerView: "欢迎使用地图浏览 web 应用程序。<br />该应用程序尚未配置。",
				appSave: "保存 web 应用程序时出错",
				mapSave: "保存 web 地图时出错",
				featureServiceLoad: "加载要素服务时出错",
				notAuthorized: "未经授权，无法配置该应用程序",
				oldBrowserTitle: "浏览器的部分功能不受支持",
				noBuilderIE8: "低于版本 9 的 Internet Explorer 不支持 Map Tour 构建器。",
				ie10Win7Explain: "当数据源是带有附件的要素服务时，Windows 7 上的 Internet Explorer 10 不支持地图浏览构建器。若要使用带有附件的要素服务，需要<a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>手动使文档模式符合 Internet Explorer 9 标准</a>，<a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>降级为 Internet Explorer 9</a> 或升级为 Windows 8。",
				oldBrowserExplain: "此浏览器不支持根据上传到地图浏览的图像自动生成缩略图。可使用此浏览器创建一个地图浏览，但需要为每个上传的图像分别提供缩略图。",
				oldBrowserExplain2: "要改善体验，请<a href='http://browsehappy.com/' target='_blank'>升级浏览器</a>或<a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>激活用于 Internet Explore 的 Google Chrome 浏览器内嵌框架</a>。",
				oldBrowserExplain3: "地图浏览构建器不适用于 Windows XP 上的 Internet Explorer 10。",
				oldBrowserClose: "关闭"
			},
			mobileHTML: {
				showIntro: "显示标题",
				hideIntro: "隐藏标题",
				navList: "列表",
				navMap: "地图",
				navInfo: "图片",
				introStartBtn: "开始"
			},
			desktopHTML: {
				storymapsText: "故事地图",
				builderButton: "切换到构建器模式"
			},
			builderHTML: {
				panelHeader: "应用程序配置",
				buttonSave: "保存",
				buttonDiscard: "取消",
				buttonSettings: "设置",
				buttonView: "视图模式",
				buttonHelp: "帮助",
				buttonOrganize: "组织",
				buttonAdd: "添加",
				buttonImport: "导入",
				buttonImportDisabled: "使用带有附件的要素服务时，导入不可用",
				modalCancel: "取消",
				modalApply: "应用",
				organizeHeader: "组织浏览",
				organizeGeneralCaption: "使用拖放功能对浏览点排序",
				organizeDelete: "删除",
				organizeHide: "隐藏",
				addMaxPointReached: "已达到图标集允许的最多点数，无法再添加更多的浏览点。<br /><br />请注意，如果删除现有点，则需要重新加载应用程序。",
				addMaxPointReachedMobile: "抱歉，已达到授权点的最大数目，无法添加该图片。",
				addClose: "关闭",
				addHeader: "添加新浏览点",
				addTabPicture: "图片",
				addTabInformation: "信息",
				addTabLocation: "位置",
				addSelectCaption: "选择或拖动图片",
				addSelectCaptionNoFileReader: "选择图片",
				addChangePhoto: "更改图片和缩略图",
				addPictureResolutionIntro: "图片分辨率高于所要求值:",
				addPictureResolutionOldBrowser: "图片分辨率高于所要求值。请指定一个低于 %RECOMMENDED_RES% 的分辨率，以便优化地图浏览体验。",
				addPictureResolutionResize: "将图片分辨率更改为 %RESOLUTION%",
				addPictureResolutionKeep: "保持原始分辨率 %RESOLUTION%",
				addSelectThumbnail: "选择缩略图",
				addNoThumbSelected: "未选择缩略图",
				addThumbSelected: "已选",
				addCameraSettingsHeader: "照相机设置",
				addThumbnailHeader: "缩略图",
				addLabelPicUrl: "图片 URL",
				addLabelThumbUrl: "缩略图 URL",
				addTextPlaceholderUrl: "输入 URL",
				addLabelName: "名称",
				addLabelDescription: "说明文字",
				addTextPlaceholder: "输入内容",
				addLocatePlaceholder: "查找地址或地点",
				addPinColor: "颜色",
				addLatitude: "纬度",
				addLongitude: "经度",
				addLatitudePlaceholder: "例如 34.056",
				addLongitudePlaceholder: "例如 -117.195",
				addUploading: "上传浏览点",
				addSave: "添加浏览点",
				addMobileUploading: "正在上传图片",
				addMobileName: "输入名称",
				addMobileNameMandatory: "出错，请输入名称。",
				addMobileError: "抱歉，出现一些问题",
				settingsHeader: "应用程序设置",
				settingsTabLayout: "布局",
				settingsTabColor: "颜色",
				settingsTabLogo: "标题",
				settingsTabFields: "数据",
				settingsTabExtent: "范围",
				settingsTabZoom: "缩放级别",
				settingsLayoutExplain: "在所提供的两个布局之间选择应用程序布局。",
				settingsLayoutProfessional: "由三个面板构成的布局",
				settingsLayoutModern: "集成的布局",
				settingsLayoutSelected: "选中的布局",
				settingsLayoutSelect: "选择此布局",
				settingsColorExplain: "通过选择预定义主题或创建自定义主题来更改外观。",
				settingsLabelColor: "页眉、内容和页脚颜色",
				settingsLogoExplain: "自定义页眉徽标(不超过 250 x 50px)。",
				settingsLogoEsri: "Esri 徽标",
				settingsLogoNone: "无徽标",
				settingsLogoCustom: "自定义徽标",
				settingsLogoCustomPlaceholder: "图像 URL",
				settingsLogoCustomTargetPlaceholder: "点击链接",
				settingsLogoSocialExplain: "自定义标题右上方的链接。",
				settingsLogoSocialText: "文本",
				settingsLogoSocialLink: "链接",
				settingsDataFieldsExplain: "选择照片名称、说明文字和颜色字段。",
				settingsDataFieldsError: "应用程序无法确定相应的名称、说明文字或颜色数据。请选择要在此处使用的字段。这些设置稍后可进行更改。",
				settingsFieldsLabelName: "名称",
				settingsFieldsLabelDescription: "说明文字",
				settingsFieldsLabelColor: "颜色",
				settingsExtentExplain: "通过下面的交互式地图设置 Map Tour 初始范围。",
				settingsExtentExplainBottom: "仅在范围包含第一个浏览点时才使用该范围。该值在 Web 地图初始范围中保持不变。",
				settingsExtentDrawBtn: "确定一个新范围",
				settingsExtentModifyBtn: "编辑当前范围",
				settingsExtentApplyBtn: "应用到主地图",
				settingsZoomExplain: "根据介绍设置故事点的缩放(可选项)。",
				settingsLabelZoom: "比例/级别",
				settingsZoomFirstValue: "无",
				settingsFieldError: "请在每个列表中选择一个字段",
				dataExplain: "该要素服务将添加到 Web 地图中。该服务不会共享给任何人，只有您具有添加、编辑和删除权限。<br /><br />如果更改应用程序共享权限，系统将询问是否要更新要素服务共享配置。用户访问您的数据时需要该权限。您仍具有唯一的编辑权限。",
				dataNameLbl: "服务名称",
				dataFolderListLbl: "文件夹",
				dataFolderListFetching: "获取文件夹 ...",
				dataRootFolder: "根目录",
				dataNameError: "输入要素服务的名称",
				dataFolderError: "选择有效的文件夹",
				dataSrcContainsInvalidChar: "要素服务名称包含一个或多个无效字符(-、<、>、#、%、:、\"、?、&、+、/ 或 \)。",
				dataSrvAlreadyExistsError: "组织中已经存在该名称的服务。请选择其他名称。",
				dataBtnSave: "创建服务",
				dataFooterProgress: "正在创建",
				dataFooterSucceed: "创建成功。正在加载",
				dataFooterError: "创建失败。请重试",
				tabError: "请检查所有选项卡中的错误",
				introRecordBtn: "入口",
				introRecordActivate: "将第一个点做为入手点 (不在转盘中显示)"
			},
			addPopupJS: {
				uploadingPicture: "正在上传图片",
				uploadSuccess: "上传成功",
				uploadError: "上传图片出错",
				notJpg: "请选择 jpeg 格式的照片",
				errorNoPhoto: "选择要上传的图像",
				errorNoThumbnail: "选择要上传的缩略图",
				errorInvalidPicUrl: "输入该浏览点的有效图片 URL",
				errorInvalidThumbUrl: "输入该浏览点的有效缩略图 URL",
				errorNoName: "输入该浏览点的名称",
				errorNoDescription: "输入该浏览点的说明文字",
				errorNoLocation: "设置该浏览点的位置"
			},
			builderJS: {
				noPendingChange: "无待决的更改",
				unSavedChangeSingular: "1 个未保存的更改",
				unSavedChangePlural: "未保存的更改",
				popoverDiscard: "确定要放弃未保存的更改吗?",
				yes: "是",
				no: "否",
				popoverLoseSave: "打开查看器，您将丢失所有未保存的更改",
				ok: "确定",
				popoverSaveWhenDone: "完成后请不要忘记保存",
				closeWithPendingChange: "确定要执行此操作吗? 您的更改将丢失。",
				gotIt: "确定",
				savingApplication: "保存应用程序",
				saveSuccess: "应用程序保存成功",
				saveError: "保存失败，请重试",
				dragColorPicker: "随意移动<br />或更改颜色",
				dataWarningExtent: "部分数据位于 web 地图的范围之外。这些数据不用作浏览点，如果要使用它们，请更改地图范围。",
				dataWarningVisibi: "您的地图浏览图层在当前 web 地图范围内不可见。将地图扩大到 %MAPSIZE% 可保证地图浏览图层可见。",
				dataWarningEdit: "编辑 web 地图",
				dataWarningClose: "关闭",
				signIn: "请使用帐户登录",
				signInTwo: "保存应用程序。"
			},
			organizePopupJS: {
				messageStart: "您已选择删除",
				messageSinglePoint: "一个浏览点",
				messageMultiPoint: "多个浏览点",
				messagePermantRemove: "此操作将从数据库中永久移除",
				messageRecord: "个记录",
				messageRecordPlural: "个记录",
				messageConfirm: "。是否要继续?",
				labelButtonShow: "显示",
				labelButtonHide: "隐藏"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "这将永久删除图片和缩略图",
				popoverDeleteWarningThumb: "这将永久删除缩略图",
				popoverUploadingPhoto: "正在上传图片和缩略图",
				popoverUploadingThumbnail: "正在上传缩略图",
				popoverUploadSuccessful: "上传成功",
				popoverUploadError: "上传失败，请重试",
				changePicAndThumb: "更改图片",
				changeThumb: "更改缩略图",
				selectPic: "更改图片",
				selectThumb: "更改缩略图",
				uploadPicAndThumb: "应用"
			},
			headerJS:{
				editMe: "编辑!",
				templateTitle: "设置模板标题",
				templateSubtitle: "设置模板子标题"
			},
			crossFaderJS:{
				setPicture: "设置图片标题",
				setCaption: "设置图片说明文字"
			},
			importPopup: {
				title: "导入",
				prevBtn: "上一步",
				nextBtn: "下一步"
			},
			importPopupHome: {
				header: "图片存储在哪里?",
				loadCSV: "在 CSV 中引用图片 (任何共享服务或 Web 服务器的图片，请参阅帮助了解详细信息)",
				loadFolder: "计算机中的文件夹 (需要现代浏览器和带有附件的要素服务数据源)"
			},
			onlinePhotoSharingCommon: {
				header1: "需要公开共享图片。",
				header2: "导入将限制为 %NB1% 张图片，以符合每次浏览 %NB2% 个点的限制。",
				emptyDataset: "发生错误，未找到图片",
				footerImport: "导入",
				selectAlbum: "选择公共图片集",
				selectAlbum2: "选择图片集",
				pleaseChoose: "请选择",
				userLookup: "查找",
				userLookingup: "正在查找",
				csv: "在 CSV 中引用",
				fromScratch: "从头开始",
				select: "做出选择",
				locUse: "使用图片位置",
				locWhy: "为什么选择该选项?",
				locExplain: "您可能不想使用图片位置，因为可以从图片集继承图片位置，导致全部照片都位于同一位置。"
			},
			viewFlickr: {
				header: "输入 Flickr 用户名并选择要导入的照片集或标签。",
				userInputLbl: "输入用户名",
				signInMsg2: "未找到用户",
				selectSet: "选择照片集",
				selectTag: "或选择标签",
				footerImportTag: "导入所选标签",
				footerImportSet: "导入所选集"
			},
			viewFacebook: {
				header: "使用 Facebook 用户帐户验证或使用公共页面。可以使用私人图片集创建不需要 Facebook 用户验证的公共地图浏览，这样可以保留注释，像私人帐户一样。",
				leftHeader: "Facebook 用户",
				rightHeader: "Facebook 页面",
				pageExplain: "Facebook 页面属于公共品牌/产品或像 <b>esrigis</b> 一样的名品。可以在页面 URL 的第一个 '/' 后面获得页面名称。",
				pageInputLbl: "输入页面名称",
				lookupMsgError: "未找到页面"
			},
			viewPicasa: {
				header: "输入 Picasa 或 Google+ 帐户的电子邮件或 ID。",
				userInputLbl: "输入电子邮件或 ID",
				signInMsg2: "未找到帐户",
				howToFind: "如何查找帐户 ID",
				howToFind2: "复制任何 Picasa 或 G+ 页面的第一个和第二个 '/' 之间的数字"
			},
			viewCSV: {
				uploadBtn: "选择或删除 CSV 文件",
				resultHeaderEmpty: "CSV 为空",
				resultHeaderSuccess: "已成功加载 %NB_POINTS% 个点",
				resultHasBeenLimited: "导入已限制为 %VAL2% 个点的前 %VAL1% 个点，以符合每次浏览 %VAL3% 个点的限制",
				browserSupport: "不支持您的浏览器，若要使用 CSV，必须<a href='http://browsehappy.com/' target='_blank'>升级浏览器</a>或使用 ArcGIS.com web 地图查看器 (请参阅“帮助”)。",
				errorLatLng: "未找到纬度和经度字段。可能的纬度值为: <i>%LAT%</i>，经度值为: <i>%LONG%</i>。",
				errorFieldsExplain: "未找到以下必填字段，所以加载失败",
				errorFieldsName: "<b>名称</b>可能值为: %VAL%",
				errorFieldsDesc: "<b>描述</b>可能值为: %VAL%",
				errorFieldsUrl: "<b>图片 URL</b> 可能值为: %VAL%",
				errorFieldsThumb: "<b>缩略图 URL</b> 可能值为: %VAL%",
				errorFields2Explain: "加载失败，因为 CSV 没有使用与以下图层属性相同的属性",
				errorFields2Name: "<b>名称</b>使用 %VAL1% 替代 %VAL2%",
				errorFields2Desc: "<b>描述</b>使用 %VAL1% 替代 %VAL2%",
				errorFields2Url: "<b>图片 URL</b> 使用 %VAL1% 替代 %VAL2%",
				errorFields2Thumb: "<b>缩略图 URL</b> 使用 %VAL1% 替代 %VAL2%",
				resultFieldsAll: "已导入所有属性",
				resultFieldsNotAll: "未导入以下属性，因为它们不存在于地图图层中",
				resultFieldsNotAll2: "未导入以下属性",
				footerNextBtnResult: "导入到 Web 地图",
				footerProgress: "正在导入",
				footerSucceed: "导入成功。正在加载"
			},
			viewGeoTag: {
				header: "单击或点击想导入的图片，以将其定位。",
				headerMore: "为什么我的图片没有定位?",
				headerExplain: "如果您的图片具有有效位置，它们将自动定位在地图上并列于第二个选项卡中。<br /><br />默认情况下，Picasa 和 Flickr 不会利用图片 EXIF 位置元数据，选中“隐私政策”选项卡下的 Flickr/Picasa 设置，以启用图片位置使用情况。可能需要将图片完全重新导入到 Flickr/Picasa。<br /><br />对于 Facebook，需要处理每个图片，单击“编辑”，在图片 EXIF 元数据所建议的位置中做出选择。",
				leftPanelTab1: "定位",
				leftPanelTab2: "已定位",
				clickOrTap: "单击或点击要定位的地图",
				clickDrop: "不要导入",
				footerImport: "导入",
				footerProgress: "正在导入",
				footerSucceed: "导入成功。正在加载..."
			},
			initPopup: {
				title: "欢迎使用地图浏览构建器",
				prevBtn: "上一步",
				nextBtn: "下一步"
			},
			initPopupHome: {
				header2: "该助手将帮助您通过已在线存储的图片构建地图浏览，或者将图片导入到您的 ArcGIS Online for Organization 帐户。",
				title1: "我的图片已托管",
				title2: "我需要托管我的图片",
				hostedFsNA: "仅适用于 ArcGIS for Organization 发布者和管理员用户",
				footer1: "完成后，不要忘记通过应用程序项目页面与受众共享您的地图浏览。",
				footer2: "参阅地图浏览帮助",
				footer3: "下载 CSV 模板",
				footerProgress: "正在创建",
				footerSucceed: "创建成功。正在加载..."
			},
			helpPopup: {
				title: "帮助",
				close: "关闭",
				tab1: {
					title: "简介",
					div1: "地图浏览模板旨在介绍地理信息，为您要讲述的故事提供吸引人的摄影元素。",
					div2: "模板生成一个吸引人且易于使用的 web 应用程序，允许您按已编号顺序在地图上展示一小组地点，用户可以此顺序进行浏览。该模板设计为可用于任何设备上的任何 web 浏览器，包括智能手机和平板电脑。",
					div3: "此帮助将指导您进行发布地图浏览的步骤，例如:",
					div4: "<ul><li><a href='http://storymaps.esri.com/stories/demo/map_tour/?webmap=7190edafe7464cb19c1caf1360cd6ee5' target='_blank'>棕榈泉地图浏览</a></li><li><a href='http://story.maps.arcgis.com/apps/MapTour/index.html?appid=4d6054b109ce482d88588d5c06a7a478' target='_blank'>荷兰国家最佳山地自行车</a></li><li><a href='http://ugis.esri.com/LA_River_Tour/' target='_blank'>洛杉矶河地图浏览</a></li></ul>",
					div5: "我们非常期望收到您的来信! 不要犹豫，与我们分享您的地图浏览:",
					div6: "<ul><li><a href='mailto:storymaps@esri.com' target='_blank'>storymaps@esri.com</a></li><li><a href='http://storymaps.esri.com/home/' target='_blank'>StoryMaps 网站</a></li><li><a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a></li></ul>",
					div7: "发现漏洞或者想请求新功能? 请告知我们，将问题提交到 <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub 项目页面</a>。"
				},
				tab2: {
					title: "数据",
					div1: "构建地图浏览时要考虑的主要因素是选择在哪里存储图片。地图浏览可以使用存储在主要照片共享服务、任何 web 服务器或要素服务中的图片。",
					div2: "交互式构建器提供两个选项，用于处理您的地图浏览中的影像:",
					div3: "<ul><li>您可以使用<b>在线照片</b>，例如存储在 Flickr 等照片共享站点的影像或存储在您自己网站上的影像。通过影像的 URL 将这些图像引用到您的地图浏览中</li><li>还可以<b>通过计算机将影像照片</b>直接上传到您的地图浏览。该上传选项需要您拥有 ArcGIS for Organizations 订阅帐户以及拥有发布者或管理员权限 (因为将自动为您创建托管的要素服务，可在其中将您的照片存储为附件)</li></ul>",
					div4: "主要用例包括:",
					div4b: "<b>您的照片还未</b>托管，您拥有一个 Organization 账户: 使用托管的要素服务是您的最佳选择。就像公共照片共享服务一样，我们将优化您的图片以创建快速加载影像，您将可以访问 ArcGIS 平台的所有管理和数据管理功能",
					div5: "<b>您不是组织成员</b>: 首先，您需要将图片上传到照片共享网站或您自己的 webserver。然后，向导将帮助您使用这些将继续在其原始位置托管的图片",
					div6: "<b>您希望重新使用</b>将图片存储为附件或引用外部图片的现有要素服务: 请参阅下面的详细信息部分",
					div7: "<b>您是</b>地图浏览模板先前版本的用户，并且已经拥有引用图片和缩略图的 CSV: 您能够导入 CSV 并优化数据。向导仅支持使用纬度/经度属性的 CSV，可以继续在您的 web 地图中使用基于地址的 CSV (请参阅以下部分)",
					div8: "从在线照片共享服务中导入",
					div9: "导入操作通过在 web 地图要素集合中存储图片的 URL 引用已托管的图片。图片没有存储在 ArcGIS Online 中。如果图片托管损坏，则图片在地图浏览中不可用，将使用“图片不可用”影像。地图浏览是否导入图片的名称、描述和位置，取决于服务提供商。这些属性存储在 web 地图中，任何对在线服务的编辑都不会反映在地图浏览中。",
					div10: "在 web 服务器上存储图片",
					div11: "如果选择自己托管图片，需要手动创建图片的缩略图。使用全分辨率的图片创建缩略图将导致性能下降。所以，强烈建议您使用在线照片共享服务或要素服务。",
					div12: "使用现有要素服务或 Shapefile",
					div13: "任何点要素服务或 Shapefile 都可用作地图浏览数据源。只需通过 ArcGIS.com 地图查看器将其作为图层添加到 web 地图中。如果应用程序在您的图层中找到预期属性，则所有构建器功能都可用。",
					div14: "预期字段包括 (不分大小写):",
					div151: "名称",
					div152: "描述",
					div153: "图片",
					div154: "缩略图",
					div155: "颜色(可选)",
					div16: "名称和描述字段为必填字段。如果在使用要素服务时，应用程序没有找到匹配的字段，则查看器不工作，直到您通过构建器配置要使用的字段。添加到 web 地图的 CSV 和 Shapefile 图层需要拥有全部必填字段，否则构建器不工作。",
					div17: "对于不带附件的要素服务，图片和缩略图字段为必填字段；对于带附件的要素服务，图片和缩略图字段可选，但强烈建议填写。如果您的服务已启用附件，构建器将让您上传图片作为附件。如果没有，您只能编辑图片和缩略图 URL。",
					div18: "从 CSV 或 Shapefile 创建托管的要素服务",
					div19: "从 CSV 或 Shapefile 创建托管的要素服务时，没有默认启用附件。若要启用附件，需打开“要素服务”项目页面，单击图层部分上的小箭头，您将看到该选项。然后，地图浏览将继续使用通过属性引用的图片和缩略图。另外，如果想将图片作为要素服务附件上传，可以使用图片面板上的两个按钮 (“更改图片”和“更改缩略图”)。",
				},
				tab3: {
					title: "自定义",
					div1: "构建器提供几个自定义选项，可以通过顶部面板中的“设置”按钮进行访问。如果没有找到所需的选项，我们还提供一个可下载版本，您可以在 web 服务器上进行部署，并可增强以符合您的需求。",
					div2: "建议您使用托管的版本，除非:",
					div3: "<li>它不提供您想要的 UI 自定义，例如使用标题背景影像</li><li>您是开发者，希望增强应用程序</li>",
					div4: "可下载版本不提供交互式构建器。地图浏览将从 web 地图中获得数据，并从与托管版本具有相同功能的配置文件中获得配置。建议您使用托管版本创建和优化 web 地图，并通过可下载版本重新使用 web 地图。",
					div5: "请访问 <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub 项目页面</a>了解有关可下载版本的详细信息。"
				},
				tab4: {
					title: "提示",
					div1: "图片",
					div2: "建议使用横向照片，而不要使用纵向照片。可以使用纵向影像，但在像 iPad 这样的小屏幕上，很多照片可能被说明文字遮挡，因为相对于宽幅区域，在长幅区域显示文本会占用更多的空间。虽然在一个地图浏览中可以使用不同大小、形状和方向的影像，但建议对所有影像使用完全相同的大小和形状。这样，用户就不会在浏览时被不同大小的影像分散注意力。",
					div3: "使用 HTML 标签格式化说明文字文本",
					div4: "说明文字文本可以包含 HTML 标签，以定义格式和链接，请参阅<a href='http://blogs.esri.com/esri/arcgis/2013/03/29/add-links-map-tour/' target='_blank'>本篇博文</a>。",
					div5: "支持图层",
					div6: "可以将其他支持图层添加到地图中。这些图层将出现在地图浏览中，提供除地图浏览点以外想让地图显示的方向、背景和任何其他地理要素，例如研究区域、链接到浏览点的步行或行驶路线。模板通过在 web 地图中指定的符号系统显示这些附加的支持图层，弹出窗口不可用。",
					div7: "保持浏览简洁明了",
					div8: "每次浏览限制为 99 个点。大部分地图浏览肯定明显少于该限制。不要期望受众愿意逐个完成过多浏览点。您可能觉得自己的主题很吸引人，但不要以为其他人也如此!",
					div9: "要了解详细信息，请参阅<a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>详细指南</a>。"
				},
				tab5: {
					title: "正在发布",
					div1: "完成操作后，不要忘记通过 ArcGIS Online 中的应用程序项目页面与受众共享您的地图浏览。在该过程中，如有必要，ArcGIS Online 将要求您更新没有相同共享权限的任何信赖资源 (web 地图、要素服务)。如果没有与受众共享您的某个资源，用户将重定向回 ArcGIS Online 登录页面。",
					div2: "如果使用通过地图浏览构建器创建的托管要素服务，应用程序将为您管理服务安全，即使公开共享服务，您仍具有唯一编辑权限。",
					div3: "公开共享地图浏览前，确保在您未登录 ArcGIS.com 帐户时，该地图浏览可以工作。"
				}
			}
        }
    })
);
