define(
({
		viewer: {
			loading: {
				step1: "CARGANDO APLICACIÓN",
				step2: "CARGANDO DATOS",
				step3: "INICIALIZANDO EL RECORRIDO",
				loadBuilder: "CAMBIANDO A MODO DE CREADOR",
				fail: "Lo siento. Error al cargar el Recorrido de mapa",
				failButton: "Reintentar"
			},
			errors: {
				boxTitle: "Se ha producido un error",
				invalidConfig: "Error muy grave: configuración no válida",
				invalidConfigOwner: "Error muy grave: configuración no válida (se requiere el propietario autorizado)",
				invalidConfigNoWebmap: "Error muy grave: configuración no válida (se requiere el mapa web y el propietario autorizado)",
				createMap: "No se puede crear el mapa",
				invalidApp: "Error muy grave: la aplicación no se puede cargar",
				noLayer: "El mapa web no contiene una capa de datos válida para el Recorrido de mapa.",
				noLayerMobile: "Bienvenido a la aplicación web Recorrido de mapa. La configuración no está configurada. El creador de Recorrido de mapa no está admitido en dispositivos móviles.",
				noLayerView: "Bienvenido a la aplicación web Recorrido de mapa.<br />La aplicación aún no está configurada.",
				appSave: "Error al guardar la aplicación web",
				mapSave: "Error al guardar el mapa web",
				featureServiceLoad: "Error al cargar el servicio de entidades",
				notAuthorized: "No está autorizado a configurar esta aplicación",
				oldBrowserTitle: "Explorador no compatible totalmente",
				noBuilderIE8: "El builder de Recorrido de mapa no es compatible con Internet Explorer anterior a la versión 9.",
				ie10Win7Explain: "El creador interactivo de recorrido de mapa no es compatible con Internet Explorer 10 en Windows 7 cuando el origen de los datos es un servicio de entidades con adjuntos. Para utilizar el servicio de entidades con adjuntos, tienes que <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>forzar manualmente el modo del documento hasta conseguir los estándares de Internet Explorer 9 </a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>cambiar la versión a Internet Explorer 9</a> o actualizar a Windows 8.",
				oldBrowserExplain: "Este navegador no es compatible con la generación de miniaturas automática a partir de las imágenes que subas a tu recorrido de mapa. Puedes crear un recorrido de mapa con este navegador, pero tendrás que proporcionar una imagen en miniatura diferente para cada una de las imágenes que subas.",
				oldBrowserExplain2: "Para mejorar tu experiencia, <a href='http://browsehappy.com/' target='_blank'>actualiza tu explorador</a> o <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activa Google Chrome Frame para Internet Explorer</a>.",
				oldBrowserExplain3: "El creador de recorridos de mapa no funciona con Internet Explorer 10 ni Windows XP.",
				oldBrowserClose: "Cerrar"
			},
			mobileHTML: {
				showIntro: "MOSTRAR TÍTULO",
				hideIntro: "OCULTAR TÍTULO",
				navList: "Lista",
				navMap: "Mapa",
				navInfo: "Imágenes",
				introStartBtn: "Inicio"
			},
			desktopHTML: {
				storymapsText: "Un mapa de historias",
				builderButton: "Cambiar el modo de creador"
			},
			builderHTML: {
				panelHeader: "CONFIGURACIÓN DE LA APLICACIÓN",
				buttonSave: "GUARDAR",
				buttonDiscard: "CANCELAR",
				buttonSettings: "Configuración",
				buttonView: "Modo Vista",
				buttonHelp: "Ayuda",
				buttonOrganize: "Organizar",
				buttonAdd: "Agregar",
				buttonImport: "Importar",
				buttonImportDisabled: "La importación no está disponible al usar un servicio de entidades con adjuntos",
				modalCancel: "Cancelar",
				modalApply: "Aplicar",
				organizeHeader: "Organizar el recorrido",
				organizeGeneralCaption: "Utilizar arrastrar y colocar para ordenar los puntos del recorrido",
				organizeDelete: "Eliminar",
				organizeHide: "Ocultar",
				addMaxPointReached: "Has alcanzado el número máximo de puntos autorizado por los iconos establecidos y no puedes añadir otro punto de recorrido.<br /><br />Recuerda que si eliminas puntos existentes, tendrás que volver a cargar la aplicación.",
				addMaxPointReachedMobile: "Lo sentimos, pero has alcanzado el número máximo de puntos autorizados y no puedes agregar esa imagen.",
				addClose: "Cerrar",
				addHeader: "Añadir un punto de recorrido nuevo",
				addTabPicture: "Imagen",
				addTabInformation: "Información",
				addTabLocation: "Ubicación",
				addSelectCaption: "Selecciona o coloca la imagen",
				addSelectCaptionNoFileReader: "Selecciona imagen",
				addChangePhoto: "Cambia la imagen y la miniatura",
				addPictureResolutionIntro: "La resolución de imagen es superior a la necesaria:",
				addPictureResolutionOldBrowser: "La resolución de la imagen es superior a la necesaria. Para optimizar la experiencia con Recorrido de mapa, especifica una resolución inferior a %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Cambiar la resolución de la imagen a %RESOLUTION%",
				addPictureResolutionKeep: "Mantener la solución original de %RESOLUTION%",
				addSelectThumbnail: "Seleccionar miniatura",
				addNoThumbSelected: "No hay una miniatura seleccionada",
				addThumbSelected: "Seleccionado",
				addCameraSettingsHeader: "AJUSTES DE LA CÁMARA",
				addThumbnailHeader: "MINIATURA",
				addLabelPicUrl: "URL de imagen",
				addLabelThumbUrl: "URL de vista en miniatura",
				addTextPlaceholderUrl: "Introduce una URL",
				addLabelName: "Nombre",
				addLabelDescription: "Leyenda",
				addTextPlaceholder: "Escribir algo",
				addLocatePlaceholder: "Localizar una dirección o un lugar",
				addPinColor: "Color",
				addLatitude: "Latitud",
				addLongitude: "Longitud",
				addLatitudePlaceholder: "por ejemplo, 34.056",
				addLongitudePlaceholder: "por ejemplo, -117.195",
				addUploading: "Cargando punto de recorrido",
				addSave: "Añadir punto de recorrido",
				addMobileUploading: "Cargando imagen",
				addMobileName: "Introduce un nombre",
				addMobileNameMandatory: "Error, introduce un nombre.",
				addMobileError: "Lo sentimos pero se ha producido un error",
				settingsHeader: "Ajustes de la aplicación",
				settingsTabLayout: "Diseño",
				settingsTabColor: "Colores",
				settingsTabLogo: "Encabezado",
				settingsTabFields: "Datos",
				settingsTabExtent: "Extensión",
				settingsTabZoom: "Nivel de zoom",
				settingsLayoutExplain: "Selecciona uno de los dos diseños de aplicación que se proporcionan.",
				settingsLayoutProfessional: "Diseño de tres paneles",
				settingsLayoutModern: "Diseño integrado",
				settingsLayoutSelected: "Diseño seleccionado",
				settingsLayoutSelect: "Selecciona este diseño",
				settingsColorExplain: "Cambia el aspecto eligiendo un tema predefinido, o crea uno propio.",
				settingsLabelColor: "Colores del encabezado, contenido y pie",
				settingsLogoExplain: "Personaliza el logotipo del encabezado (el valor máximo es 250 x 50px).",
				settingsLogoEsri: "Logotipo de Esri",
				settingsLogoNone: "Sin logotipo",
				settingsLogoCustom: "Logotipo personalizado",
				settingsLogoCustomPlaceholder: "URL de imagen",
				settingsLogoCustomTargetPlaceholder: "Enlace click-through",
				settingsLogoSocialExplain: "Personaliza el enlace superior derecho del encabezado.",
				settingsLogoSocialText: "Texto",
				settingsLogoSocialLink: "Vínculo",
				settingsDataFieldsExplain: "Selecciona los campos de nombre de foto, leyenda y color.",
				settingsDataFieldsError: "La aplicación no puede determinar los datos de nombre, leyenda o color adecuados. Selecciona los campos que se usarán aquí. Estos ajustes se pueden cambiar más adelante.",
				settingsFieldsLabelName: "Nombre",
				settingsFieldsLabelDescription: "Leyenda",
				settingsFieldsLabelColor: "Color",
				settingsExtentExplain: "Define la extensión inicial del Recorrido de mapa mediante el mapa interactivo siguiente.",
				settingsExtentExplainBottom: "Esa extensión solo se utiliza si incluye el punto de partida del recorrido. El valor se conserva en toda la extensión inicial del mapa Web.",
				settingsExtentDrawBtn: "Dibuja una nueva extensión",
				settingsExtentModifyBtn: "Edita la extensión actual",
				settingsExtentApplyBtn: "Aplica en el mapa principal",
				settingsZoomExplain: "Ajusta el zoom para los puntos de la historia después de la introducción (opcional).",
				settingsLabelZoom: "Escala/Nivel",
				settingsZoomFirstValue: "Ninguno",
				settingsFieldError: "Selecciona un campo de cada lista",
				dataExplain: "El servicio de entidades se agregará al mapa Web. No se compartirá con nadie y solo tú tendrás privilegios para agregar, editar y eliminar.<br /><br />Si cambias los privilegios de uso compartido de la aplicación, el sistema te preguntará si deseas actualizar la configuración de uso compartido del servicio de entidades. Es un requisito obligatorio para que los usuarios accedan a los datos. Seguirás siendo el único que tenga privilegios de edición.",
				dataNameLbl: "Nombre del servicio",
				dataFolderListLbl: "Carpeta",
				dataFolderListFetching: "Recuperando carpetas ...",
				dataRootFolder: "Raíz",
				dataNameError: "Introduce un nombre para el servicio de entidades",
				dataFolderError: "Selecciona una carpeta válida",
				dataSrcContainsInvalidChar: "El nombre del servicio de entidades contiene uno o varios caracteres no válidos (-, <, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "En la organización ya existe un servicio con este nombre. Elige un nombre diferente.",
				dataBtnSave: "Crear el servicio",
				dataFooterProgress: "Creación en curso",
				dataFooterSucceed: "Creación satisfactoria. Cargando",
				dataFooterError: "Error de creación. Inténtalo de nuevo",
				tabError: "Comprueba todas las fichas por si existen errores",
				introRecordBtn: "Introducción",
				introRecordActivate: "Utiliza el punto de partida como introducción (no aparece en la muestra)"
			},
			addPopupJS: {
				uploadingPicture: "Cargando imagen",
				uploadSuccess: "Carga satisfactoria",
				uploadError: "Error al cargar la imagen",
				notJpg: "Elige una foto jpeg para cargarla",
				errorNoPhoto: "Elige una imagen para cargarla",
				errorNoThumbnail: "Elige una miniatura para cargarla",
				errorInvalidPicUrl: "Introduce una URL de imagen válida para este punto del recorrido",
				errorInvalidThumbUrl: "Introduce una URL de vista en miniatura para este punto del recorrido",
				errorNoName: "Escribe un nombre para este punto de recorrido",
				errorNoDescription: "Escribe una leyenda para este punto de recorrido",
				errorNoLocation: "Establece una ubicación para este punto de recorrido"
			},
			builderJS: {
				noPendingChange: "Sin cambios pendientes",
				unSavedChangeSingular: "1 cambio sin guardar",
				unSavedChangePlural: "cambios no guardados",
				popoverDiscard: "¿Estás seguro de que deseas descartar los cambios no guardados?",
				yes: "Sí",
				no: "No",
				popoverLoseSave: "Al abrir el visor, perderás los cambios no guardados",
				ok: "Aceptar",
				popoverSaveWhenDone: "No olvides guardar los cambios cuando hayas terminado",
				closeWithPendingChange: "¿Estás seguro de que deseas confirmar la acción? Tus cambios se perderán.",
				gotIt: "Aceptar",
				savingApplication: "Guardando la aplicación",
				saveSuccess: "La aplicación se ha guardado con éxito",
				saveError: "Error al guardar. Inténtalo de nuevo",
				dragColorPicker: "Desplázame<br />o cambia mi color",
				dataWarningExtent: "Tienes datos fuera de la extensión del mapa web. Estos datos no se usarán como puntos de recorrido. Si quieres usarlos, cambia la extensión del mapa.",
				dataWarningVisibi: "Tu capa de Recorrido de mapa no está visible en la extensión de mapa web actual. Confirma que tu capa de Recorrido de mapa esté visible con un mapa grande %MAPSIZE%.",
				dataWarningEdit: "Editar mapa web",
				dataWarningClose: "Cerrar",
				signIn: "Inicia sesión con una cuenta en",
				signInTwo: "para guardar la aplicación."
			},
			organizePopupJS: {
				messageStart: "Has elegido eliminar",
				messageSinglePoint: "un punto de recorrido",
				messageMultiPoint: "dos puntos",
				messagePermantRemove: "Esto eliminará permanentemente",
				messageRecord: "el registro",
				messageRecordPlural: "los registros",
				messageConfirm: "de la base de datos. ¿Deseas continuar?",
				labelButtonShow: "Mostrar",
				labelButtonHide: "Ocultar"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Esto eliminará la imagen y la miniatura de forma permanente",
				popoverDeleteWarningThumb: "Esto eliminará la miniatura de forma permanente",
				popoverUploadingPhoto: "Actualizando imagen y miniatura",
				popoverUploadingThumbnail: "Actualizando miniatura",
				popoverUploadSuccessful: "Carga satisfactoria",
				popoverUploadError: "Error de carga. Inténtalo de nuevo",
				changePicAndThumb: "Cambiar imagen",
				changeThumb: "Cambiar miniatura",
				selectPic: "Cambiar imagen",
				selectThumb: "Seleccionar miniatura",
				uploadPicAndThumb: "Aplicar"
			},
			headerJS:{
				editMe: "¡Modifícame!",
				templateTitle: "Establecer título de plantilla",
				templateSubtitle: "Establecer subtítulo de plantilla"
			},
			crossFaderJS:{
				setPicture: "Establecer título de imagen",
				setCaption: "Establecer leyenda de imagen"
			},
			importPopup: {
				title: "Importar",
				prevBtn: "Atrás",
				nextBtn: "Siguiente"
			},
			importPopupHome: {
				header: "¿Dónde se almacenan las imágenes?",
				loadCSV: "Se hace referencia a ellos en un archivo CSV (cualquier servidor Web o servicio de uso compartido de imágenes; consulta la ayuda para obtener más información)",
				loadFolder: "Una carpeta en Mi PC (necesita un explorador actualizado y un servicio de entidades con fuentes de datos adjuntas)"
			},
			onlinePhotoSharingCommon: {
				header1: "Es necesario compartir las imágenes de forma pública.",
				header2: "La importación se limitará a %NB1% imágenes para respetar el límite de %NB2% puntos por recorrido.",
				emptyDataset: "Error, no se han encontrado imágenes",
				footerImport: "Importar",
				selectAlbum: "Selecciona un álbum público",
				selectAlbum2: "Selecciona un álbum",
				pleaseChoose: "Elige",
				userLookup: "Buscar",
				userLookingup: "Buscando",
				csv: "Referenciado en un CSV",
				fromScratch: "Empezar desde el principio",
				select: "Crear una selección",
				locUse: "Utilizar ubicación de imágenes",
				locWhy: "¿Por qué esa opción?",
				locExplain: "Es posible que no quieras utilizar la ubicación de imágenes, ya que se puede heredar del álbum, con lo que todas las fotografías estarán en la misma ubicación."
			},
			viewFlickr: {
				header: "Introduce un nombre de usuario de Flickr y selecciona un conjunto de imágenes o una etiqueta para importar.",
				userInputLbl: "Introduce un nombre de usuario",
				signInMsg2: "Usuario no encontrado",
				selectSet: "Selecciona un conjunto de imágenes",
				selectTag: "o selecciona una etiqueta",
				footerImportTag: "Importar la etiqueta seleccionada",
				footerImportSet: "Importar el conjunto seleccionado"
			},
			viewFacebook: {
				header: "Autentica con una cuenta de usuario de Facebook o usa una página pública. Los álbumes se pueden usar para crear recorridos de mapa que no necesitan autenticación con un usuario de Facebook, lo que permite mantener los comentarios y me gusta en privado.",
				leftHeader: "Usuario de Facebook",
				rightHeader: "Página de Facebook",
				pageExplain: "Una página de Facebook es una marca/producto público o un famoso como <b>esrigis</b>. Puedes obtener el nombre de la página después de la  primera '/' de la URL de la página.",
				pageInputLbl: "Introduce un nombre de página",
				lookupMsgError: "No se encontró la página"
			},
			viewPicasa: {
				header: "Introduce el correo electrónico o el ID de una cuenta Picasa o Google +.",
				userInputLbl: "Introduce un correo electrónico o ID",
				signInMsg2: "Cuenta no encontrada",
				howToFind: "Cómo encontrar el ID de una cuenta",
				howToFind2: "Copia los dígitos que hay entre la primera y la segunda "/" de cualquier página de Picasa o G+"
			},
			viewCSV: {
				uploadBtn: "Selecciona o coloca un archivo CSV",
				resultHeaderEmpty: "El archivo CSV está vacío",
				resultHeaderSuccess: "%NB_POINTS% puntos cargados correctamente",
				resultHasBeenLimited: "La importación se ha limitado a los primeros %VAL1% puntos de %VAL2% para respetar el límite de %VAL3% puntos por recorrido",
				browserSupport: "El navegador no es compatible. Si quieres utilizar un archivo CSV tienes que <a href='http://browsehappy.com/' target='_blank'>actualizar el navegador</a> o utilizar el visor de mapas Web de ArcGIS.com (consulta la ayuda).",
				errorLatLng: "No se han encontrado los campos de latitud y longitud. Los valores posibles de latitud son: <i>%LAT%</i>y los de longitud son: <i>%LONG%</i>.",
				errorFieldsExplain: "Se ha producido un error en la carga porque no se han encontrado los siguientes campos obligatorios",
				errorFieldsName: "Los posibles valores de <b>Nombre</b> son: %VAL%",
				errorFieldsDesc: "Los posibles valores de <b>Descripción</b> son: %VAL%",
				errorFieldsUrl: "Los posibles valores de <b>URL de imagen</b> son: %VAL%",
				errorFieldsThumb: "Los posibles valores de <b>URL de vista en miniatura</b> son: %VAL%",
				errorFields2Explain: "Se ha producido un error en la carga porque el archivo CSV no utiliza los mismos atributos que la capa de los siguientes atributos",
				errorFields2Name: "<b>Nombre</b> usa %VAL1% en lugar de %VAL2%",
				errorFields2Desc: "<b>Descripción</b> usa %VAL1% en lugar de %VAL2%",
				errorFields2Url: "<b>URL de imagen</b> usa %VAL1% en lugar de %VAL2%",
				errorFields2Thumb: "<b>URL de vista en miniatura</b> usa %VAL1% en lugar de %VAL2%",
				resultFieldsAll: "Se han importado todo los atributos",
				resultFieldsNotAll: "No se han importado los siguientes atributos porque no existen en la capa del mapa",
				resultFieldsNotAll2: "Se han importado los siguientes atributos",
				footerNextBtnResult: "Importar al mapa Web",
				footerProgress: "Importación en curso",
				footerSucceed: "Importación correcta. Cargando"
			},
			viewGeoTag: {
				header: "Haz clic o puntea las imágenes que quieres importar para localizarlas.",
				headerMore: "¿Por qué no se encuentran mis imágenes?",
				headerExplain: "Si tus imágenes tienen una ubicación válida, se ubicarán automáticamente en el mapa y se registrarán en la segunda etiqueta.<br /><br />Por defecto, Picasa y Flickr no explotan los metadatos de ubicación de la imágenes EXIF. Comprueba los ajustes de Flickr/Picasa en la etiqueta Privacidad para activar el uso de la ubicación. Es posible que tengas que volver a importar todas tus imágenes a Flickr/Picasa.<br /><br />Para Facebook, tienes que ir a cada imagen, hacer clic en Editar y seleccionar la ubicación de entre las opciones sugeridas que se basan en los metadatos de las imágenes EXIF.",
				leftPanelTab1: "Para localizar",
				leftPanelTab2: "Localizado",
				clickOrTap: "Haz clic o puntea el mapa para localizar",
				clickDrop: "No importar",
				footerImport: "Importar",
				footerProgress: "Importación en curso",
				footerSucceed: "Importación correcta. Cargando..."
			},
			initPopup: {
				title: "Bienvenido al creador de recorridos de mapa",
				prevBtn: "Atrás",
				nextBtn: "Siguiente"
			},
			initPopupHome: {
				header2: "Este asistente te ayudará a crear un recorrido de mapa a partir de imágenes que ya estén almacenadas en línea o las importará en la cuenta de ArcGis Online for Organization.",
				title1: "Mis imágenes ya están alojadas",
				title2: "Necesito alojar mis imágenes",
				hostedFsNA: "Solo disponible para los usuarios Publisher y Administrator de ArcGIS for Organization",
				footer1: "Cuando termines, no olvides compartir el recorrido de mapa con tus seguidores a través de la página de elementos de la aplicación.",
				footer2: "Consulta la ayuda del recorrido de mapa",
				footer3: "Descargar la plantilla CSV",
				footerProgress: "Creación en curso",
				footerSucceed: "Se ha creado correctamente. Cargando..."
			},
			helpPopup: {
				title: "Ayuda",
				close: "Cerrar",
				tab1: {
					title: "Introducción",
					div1: "La plantilla del recorrido de mapa está diseñada para presentar la información geográfica cuando exista un elemento fotográfico convincente en la historia que desea contar.",
					div2: "La plantilla produce una aplicación Web atractiva fácil de usar que te permitirá presentar un conjunto pequeño de lugares en un mapa con una secuencia numerada por el que podrán navegar los usuarios. La plantilla se ha diseñado para su uso en cualquier navegador Web y dispositivo, incluidos los smartphones y las tabletas.",
					div3: "Esta ayuda te guiará por los pasos necesarios para publicar un recorrido de mapa como:",
					div4: "<ul><li><a href='http://storymaps.esri.com/stories/demo/map_tour/?webmap=7190edafe7464cb19c1caf1360cd6ee5' target='_blank'>Recorrido de mapa de Palm Springs</a></li><li><a href='http://story.maps.arcgis.com/apps/MapTour/index.html?appid=4d6054b109ce482d88588d5c06a7a478' target='_blank'>Mejores lugares para hacer ciclismo de montaña en los Países Bajos</a></li><li><a href='http://ugis.esri.com/LA_River_Tour/' target='_blank'>Recorrido de mapa del río Los Ángeles</a></li></ul>",
					div5: "Nos gusta mucho tener noticias tuyas. No dudes en compartir tu recorrido de mapa con nosotros:",
					div6: "<ul><li><a href='mailto:storymaps@esri.com' target='_blank'>storymaps@esri.com</a></li><li><a href='http://storymaps.esri.com/home/' target='_blank'>Página Web de StoryMaps</a></li><li><a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a></li></ul>",
					div7: "¿Has encontrado un error o quieres solicitar una nueva entidad? Infórmanos enviando el problema en la página de proyecto GitHug<a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'></a>."
				},
				tab2: {
					title: "Datos",
					div1: "El elemento principal al tener en cuenta a la hora de crear un recorrido de mapa es elegir el lugar de almacenamiento de las imágenes. El recorrido de mapa puede utilizar las imágenes que se almacenan en los principales servicios de uso compartido de fotografías, en cualquier servidor Web o en los servicios de entidades.",
					div2: "El creador interactivo te da dos opciones para gestionar las imágenes del recorrido de mapa:",
					div3: "<ul><li>Puedes usar <b>fotos que ya están en la red</b>, como las fotos almacenadas en un sitio para compartir imágenes como Flickr o las imágenes almacenadas en tu propia página Web. Se hará referencia a estas imágenes en tu recorrido de mapa a través de sus URL</li><li>También puedes <b>cargar fotografías desde tu ordenador</b> directamente a tu recorrido de mapa. Esta opción de carga necesita que tengas una cuenta de suscripción a ArcGIS for Organizations y que tengas privilegios de Publisher o Administrator (porque crea automáticamente un servicio de entidades alojadas en el que tus fotos se almacenan como adjuntos</li></ul>",
					div4: "Los principales casos de uso son:",
					div4b: "<b>Si tus fotos no se han alojado</b> aún y tienes una cuenta con una organización, la mejor opción es que uses un servicio de entidades alojadas. Al igual que los servicios públicos de compartir imágenes, nosotros optimizaremos tus fotos para crear imágenes de subida rápida y tendrás acceso a todas las prestaciones de administración y gestión de la plataforma ArcGIS",
					div5: "<b>Si no eres miembro de una organización</b>, primero tienes que subir tu imagen a una página Web para compartir fotos o a tu propio servidor Web y, a continuación, el asistente te ayudará a usar esas imágenes que seguirán alojadas en su ubicación original",
					div6: "<b>Si quieres volver a usar un servicio de entidades existente</b> que almacene tus imágenes como datos adjuntos o que haga referencia a imágenes externas, consulta la siguiente sección detalla",
					div7: "<b>Si eres usuario de la versión anterior</b> de la plantilla Recorrido de mapa y ya tienes tu archivo CSV que hace referencia a tus imágenes y vistas en miniatura, podrás importar y modificar tus datos. El asistente solo es compatible con los archivos CSV que usan atributos de latitud/longitud. Los archivos CSV basados en direcciones se pueden seguir usando mediante tu mapa Web (consulta la sección siguiente)",
					div8: "Importando de los servicios de intercambio de fotos en línea",
					div9: "La referencia de la operación de importación ya aloja las imágenes almacenando las URL en un conjunto de entidades de mapa Web. Las imágenes no se almacenan en ArcGIS Online. Si se interrumpe el alojamiento de las imágenes, no estarán disponibles en el recorrido de mapa y se usará la imagen “Imagen no disponible”. Según el proveedor de servicios, el recorrido de mapa importará o no el nombre, la descripción y la ubicación de las imágenes. Estos atributos se almacenan en el mapa Web y no se reflejará en el recorrido de mapa ninguna edición que se realice en los servicios en línea.",
					div10: "Almacenando las imágenes en un servidor Web",
					div11: "Si eliges alojar las imágenes tú mismo, tendrás que crear manualmente vistas en miniatura de tus imágenes. Usar la resolución completa de las imágenes para las vistas en miniatura daría como resultado un rendimiento bajo. Por esa razón, te recomendamos encarecidamente que uses un servicio de intercambio de fotos en línea o un servicio de entidades que lo haga por ti.",
					div12: "Uso de Shapefile o de un servicio de entidad existente",
					div13: "Cualquier punto del servicio de entidades o shapefile se puede usar como una fuente de datos del Recorrido de mapa. Solo tienes que agregarlo como una capa a tu mapa Web mediante el visor de mapas de ArcGIS.com. Si el mapa encuentra los atributos esperados en tu capa, toda las funcionalidades de creador estarán disponibles.",
					div14: "Los campos esperados son (se distingue entre mayúsculas y minúsculas):",
					div151: "Nombre",
					div152: "Descripción",
					div153: "Imagen",
					div154: "Miniatura",
					div155: "Color (opcional)",
					div16: "Los campos de nombre y descripción son obligatorios. Si la aplicación no encuentra campos coincidentes al usar un servicio de entidades, el visor no funcionará hasta que configures los campos a usar mediante el creador. Las capas CSV y Shapefile agregadas al mapa Web deben tener todos los campos necesarios o el creador no funcionará.",
					div17: "Los campos de imagen y vista en miniatura son obligatorios para el servicio de entidades sin adjuntos y opcionales, aunque muy recomendables, para el servicio de entidades con adjuntos. Si el servicio tiene adjuntos habilitados, el creador te permitirá cargar imágenes como adjuntos. Si no, solo podrás editar la URL de la imagen y la vista en miniatura.",
					div18: "Crear un servicio de entidades alojado a partir de un archivo de CSV o Shapefile",
					div19: "Si creas un servicio de entidades alojado a partir de un archivo CSV o Shapefile, los adjuntos no están habilitados de forma predeterminada. Para habilitarlos, abre la página de elementos del servicio de entidades y haz clic en la flecha pequeña de la sección de capas para ver la opción. Una vez hecho, el recorrido de mapa seguirá utilizando las imágenes y vistas en miniatura a las que se haya hecho referencia a través de los atributos. De forma opcional, si deseas cargar las imágenes como adjuntos del servicio de entidades, podrás hacerlo a través de dos botones que se encuentran en el panel de imágenes (cambiar imagen y cambiar vista en miniatura).",
				},
				tab3: {
					title: "Personalización",
					div1: "El creador proporciona varias opciones de personalización a las que se puede acceder a través del botón CONFIGURACIÓN del panel superior. Si no encuentras la opción esperada, también podemos proporcionarte una versión para descarga que puedes desplegar en el servidor Web y mejorarla para adaptarla a tus necesidades.",
					div2: "Te recomendamos que utilices la versión alojada, excepto en:",
					div3: "<li>No ofrece una personalización de la interfaz de usuario que quieres tener, como usar una imagen de fondo del encabezado</li><li>Eres un desarrollador y quieres mejorar la aplicación</li>",
					div4: "La versión para descarga no ofrece el creador interactivo. El recorrido de mapa obtendrá los datos de un mapa Web y su configuración de un archivo de configuración que ofrece las mismas capacidades que la versión alojada. Recomendamos que crees y definas el mapa Web utilizando la versión alojada y que lo reutilices con la versión para descarga.",
					div5: "Visita la <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>página del proyecto GitHub</a> para obtener más información sobre la versión para descarga."
				},
				tab4: {
					title: "Consejos",
					div1: "Imágenes",
					div2: "Recomendamos la orientación horizontal de las fotografías en lugar de la vertical. Se pueden utilizar imágenes con la orientación vertical, pero en pantallas de menor tamaño como es el caso del iPad, gran parte de la fotografía puede aparecer oscurecida por el título, ya que el texto ocupa más espacio cuando se muestra en un área elevada que cuando se hace en un área ancha. Aunque se pueden utilizar imágenes de diferentes tamaños, formas y orientaciones en un recorrido de mapa, recomendamos que utilices siempre el mismo tamaño y forma para todas las imágenes. De esta forma, el usuario no se distraerá con las imágenes de los distintos tamaños a medida que siguen el recorrido.",
					div3: "Establece el formato de texto de tu leyenda usando etiquetas HTML",
					div4: "El texto de la leyenda puede incluir etiquetas HTML para definir el formato y los enlaces. Consulta <a href='http://blogs.esri.com/esri/arcgis/2013/03/29/add-links-map-tour/' target='_blank'>esta publicación del blog</a>.",
					div5: "Capas de apoyo",
					div6: "Puedes agregar capas de apoyo adicionales al mapa. Estas capas aparecerán en el recorrido de mapa para proporcionar orientación, fondo y otras entidades geográficas que quieras mostrar en el mapa además de los puntos del recorrido de mapa, como un área de estudio, una ruta a pie o en coche que una los puntos del recorrido, etc. La plantilla muestra estas capas de apoyo adicionales con la simbología que especifiques en el mapa Web. Las ventanas emergentes no están disponibles.",
					div7: "Mantén tu recorrido corto y agradable",
					div8: "Existe un límite de 99 puntos por recorrido. Por supuesto, la mayor parte de loa recorridos de mapa serán mucho más cortos. No esperes que el público quiera pasar por tantos puntos de recorrido. Es posible que encuentres el tema fascinante, pero no pienses que a ellos les sucederá lo mismo.",
					div9: "Para obtener más información, consulta <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>la guía detallada</a>."
				},
				tab5: {
					title: "Publicando",
					div1: "Cuando hayas terminado, no olvides compartir el recorrido de mapa con tu público a través de la página de elementos de la aplicación en ArcGIS Online. Durante ese proceso, ArcGIS Online te pedirá que actualices los recursos dependientes (mapa Web, servicio de entidades) que no tengan los mismos privilegios de uso compartido. Si no compartes uno de tus recursos con el público, se redirigirá a los usuarios a la página de inicio de sesión de ArcGIS Online.",
					div2: "Si estás usando un servicio de entidades alojado creado mediante el creador de recorrido de mapa, la aplicación gestiona la seguridad del servicio por ti y tú serás el único con privilegios de edición, incluso aunque compartas el servicio de forma pública.",
					div3: "Antes de compartir públicamente un recorrido de mapa, asegúrate de que funciona cuando no has iniciado sesión con tu cuenta de ArcGIS.com."
				}
			}
        }
    })
);
