define({
  "viewer": {
    "loading": {
      "step1": "CARGANDO HISTORIA",
      "step2": "CARGANDO DATOS",
      "step3": "INICIALIZANDO EL RECORRIDO",
      "loadBuilder": "CAMBIANDO A MODO DE BUILDER",
      "redirectSignIn": "REDIRIGIENDO A LA PÁGINA DE INICIO DE SESIÓN",
      "redirectSignIn2": "(se te redirigirá aquí después del inicio de sesión)",
      "fail": "Lo sentimos. Error al cargar Ruta de mapa",
      "failButton": "Reintentar"
    },
    "errors": {
      "boxTitle": "Se ha producido un error",
      "portalSelf": "Error muy grave: no se ha podido obtener la configuración del portal",
      "invalidConfig": "Error muy grave: configuración no válida",
      "invalidConfigOwner": "Error muy grave: configuración no válida (se requiere el propietario autorizado)",
      "invalidConfigNoWebmap": "Error muy grave: configuración no válida (el mapa web o el identificador de la aplicación no están especificados en index.html)",
      "invalidConfigNoAppDev": "No se ha especificado ningún identificador de la aplicación de representación cartográfica web o mapa web en los parámetros de la dirección URL (?appid= o ?webmap=). En modo de desarrollo, la configuración de appid y webmap en index.html se ignora.",
      "createMap": "No se puede crear el mapa",
      "invalidApp": "Error grave: la historia no se puede cargar",
      "noLayer": "El mapa web no contiene una capa de datos válida para la ruta de mapa.",
      "noLayerMobile": "El builder de Map Tour no es compatible con este tamaño de pantalla. Si es posible, cambia el tamaño de tu navegador para acceder al builder o crea tu historia en un dispositivo que tenga una pantalla más grande.",
      "noLayerMobile2": "Rota el dispositivo a horizontal para utilizar el builder de Map Tour.",
      "noLayerView": "Bienvenido a la aplicación web Map Tour.<br />La historia aún no está configurada.",
      "appSave": "Error al guardar la historia",
      "mapSave": "Error al guardar el mapa web",
      "featureServiceLoad": "Error al cargar el servicio de entidades",
      "notAuthorized": "No tienes autorización para acceder a esta historia",
      "notAuthorizedBuilder": "No estás autorizado para utilizar el builder de Map Tour.",
      "oldBrowserTitle": "Explorador no compatible totalmente",
      "noBuilderIE8": "El builder de Ruta de mapa no es compatible con Internet Explorer anterior a la versión 9.",
      "ie10Win7Explain": "El builder interactivo de ruta de mapa no es compatible con Internet Explorer 10 en Windows 7 cuando el origen de los datos es un servicio de entidades con adjuntos. Para utilizar el servicio de entidades con adjuntos, tienes que <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>forzar manualmente el modo del documento hasta conseguir los estándares de Internet Explorer 9 </a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>cambiar la versión a Internet Explorer 9</a> o actualizar a Windows 8.",
      "oldBrowserExplain": "Este navegador no es compatible con la generación de vistas en miniatura automática a partir de las imágenes que subas a tu ruta de mapa. Puedes crear una ruta de mapa con este navegador, pero tendrás que proporcionar una imagen en miniatura diferente para cada una de las imágenes que subas.",
      "oldBrowserExplain2": "Para mejorar tu experiencia, <a href='http://browsehappy.com/' target='_blank'>actualiza tu explorador</a> o <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activa Google Chrome Frame para Internet Explorer</a>.",
      "oldBrowserExplain3": "El builder de ruta de mapa no funciona con Internet Explorer 10 ni Windows XP.",
      "oldBrowserClose": "Cerrar",
      "noViewerIE2": "Está intentando ver esta historia con un navegador antiguo no compatible. Es posible que algunas características no funcionen o que se produzcan otros problemas inesperados. Es recomendable actualizar a Internet Explorer 11 o usar otro navegador como Chrome.",
      "noViewerIE3": "A finales de 2017, esta historia no se podrá cargar en este navegador. Cuando eso ocurra, deberá usar un navegador compatible para ver la historia.",
      "attention": "Atención"
    },
    "mobileHTML": {
      "showIntro": "MOSTRAR TÍTULO",
      "hideIntro": "OCULTAR TÍTULO",
      "navList": "Lista",
      "navMap": "Mapa",
      "navInfo": "Multimedia",
      "introStartBtn": "Inicio"
    },
    "desktopHTML": {
      "storymapsText": "Un mapa de historias",
      "builderButton": "Cambiar a modo de builder",
      "facebookTooltip": "Compartir en Facebook",
      "twitterTooltip": "Compartir en Twitter",
      "bitlyTooltip": "Obtén un vínculo corto",
      "bitlyStartIndex": "Enlazar al lugar actual",
      "tooltipAutoplayDisabled": "Esto no está disponible en el modo de reproducción automática",
      "autoplayLabel": "Modo de reproducción automática",
      "autoplayExplain1": "El modo de reproducción automática avanzará por la historia a intervalos regulares. Esto es idóneo para monitores de quioscos o de visualización pública, pero debes tener en cuenta que, en otras situaciones, puede que dificulte la lectura de la historia. Esta función no es compatible con pantallas pequeñas.",
      "autoplayExplain2": "Cuando este modo está activado, hay disponibles controles para reproducir o detener la historia y para ajustar la velocidad de navegación.",
      "takeTourText": "Realizar el recorrido",
      "backToStart": "Volver al inicio"
    },
    "builderHTML": {
      "panelHeader": "CONFIGURACIÓN DE LA HISTORIA",
      "buttonSave": "GUARDAR",
      "buttonSettings": "Configuración",
      "buttonShare": "Compartir",
      "buttonView": "Modo Vista",
      "buttonItem": "Abre el elemento de la aplicación web",
      "buttonHelp": "Ayuda",
      "buttonOrganize": "Organizar",
      "buttonOrganizeAndCover": "Organizar puntos de recorrido y agregar una página de portada",
      "buttonAdd": "Agregar",
      "buttonImport": "Importar",
      "buttonImportDisabled": "La importación no está disponible cuando se usa la carga de imágenes. Haga clic en Agregar para cargar una imagen.",
      "dataEditionDisabled": "La edición de datos está desactivada en esta fuente de datos CSV",
      "dataSourceWarning": "La capa de datos de Map Tour ha cambiado. Si los Id. de las entidades no son las mismas, debe restablecer el orden y los puntos ocultos mediante <b>Organizar</b>. Si los nombres de campos difieren, debe restablecer los ajustes de los campos en la <b>pestaña de datos de Ajustes</b>.",
      "organizeWarning": "Uno o varios puntos agregados fuera del builder interactivo están ocultos.",
      "dataPicError0a": "El recorrido incluye <b>%NB%</b> direcciones URL de imágenes no conformes.",
      "dataPicError0b": "Este recorrido puede incluir <b>%NB%</b> direcciones URL de imágenes no conformes.",
      "dataPicError1": "La ruta de mapa ahora requiere que las direcciones URL de las imágenes acaben con una de las siguientes extensiones: .jp(e)g, .png, .gif o .bmp.",
      "dataPicError2": "Este requisito no afectará a las rutas de mapa existentes que ya estén publicadas. Sin embargo, para utilizar el builder interactivo, debes solucionar en primer lugar el problema con la dirección URL realizando una de las dos siguientes acciones:",
      "dataPicError3": "Editar las direcciones URL",
      "dataPicError4": "Con esto se agrega <i>#isImage</i> al final de las URL de las imágenes no admitidas. La mayoría de los servidores admiten los apéndices de URL. Sin embargo, una vez realizada la acción, debe verificar que las URL actualizadas de las imágenes funcionen correctamente, navegando para ello por sus puntos. Si todas las imágenes se cargan correctamente, puede guardar el Map Tour. Si hay <b>imágenes con vínculos no válidos, no guarde el Map Tour</b>. En su lugar, recargue el builder y realice la segunda acción.",
      "dataPicError5": "Limitar el recorrido a las imágenes",
      "dataPicError6": "Esta opción hace que todas las URL se consideren imágenes, pero no podrá agregar vídeos mediante el builder interactivo. Esta acción es reversible si decidiera agregar vídeo en el futuro.",
      "dataPicError7": "Su Map Tour se ha restringido a fotografías; no puede usar vídeos. Si decide eliminar esta limitación, verifique que sus imágenes se sigan cargando correctamente antes de guardar el Map Tour. Podrá restaurar esta limitación más adelante en caso necesario.",
      "dataPicError8": "Eliminar la limitación de imágenes",
      "dataPicError9": "Si estas URL apuntan a vídeos, puede hacer caso omiso de esta advertencia; si apuntan a imágenes, necesita realizar una de las dos acciones siguientes:",
      "modalCancel": "Cancelar",
      "modalApply": "Aplicar",
      "organizeHeader": "Organizar el recorrido",
      "organizeGeneralCaption": "Utilizar arrastrar y colocar para ordenar los puntos del recorrido",
      "organizeDelete": "Eliminar",
      "organizeHide": "Ocultar",
      "organizeReset": "Restablecer el orden y los puntos ocultos",
      "addMaxPointReached": "Has alcanzado el número máximo de puntos permitidos por los iconos establecidos y no puedes añadir otro punto al recorrido.<br /><br />Recuerda que si eliminas puntos existentes, tendrás que volver a cargar la historia.",
      "addMaxPointReachedMobile": "Lo sentimos, pero has alcanzado el número máximo de puntos autorizados y no puedes agregar esa imagen.",
      "addClose": "Cerrar",
      "addHeader": "Añadir un punto de recorrido nuevo",
      "addTabPicture": "Multimedia",
      "addTabInformation": "Información",
      "addTabLocation": "Ubicación",
      "addSelectCaption": "Seleccionar o soltar la imagen",
      "addNoteVideo": "Consulta la Ayuda para obtener instrucciones sobre el uso de vídeos",
      "addSelectCaptionNoFileReader": "Seleccionar imagen",
      "addChangePhoto": "Cambiar la imagen y la vista en miniatura",
      "addPictureResolutionIntro": "La resolución de imagen es superior a la necesaria:",
      "addPictureResolutionOldBrowser": "La resolución de la imagen es superior a la necesaria. Para optimizar la experiencia con Ruta de mapa, especifica una resolución inferior a %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Cambiar la resolución de la imagen a %RESOLUTION%",
      "addPictureResolutionKeep": "Mantener la solución original de %RESOLUTION%",
      "addSelectThumbnail": "Seleccionar miniatura",
      "addNoThumbSelected": "No hay una miniatura seleccionada",
      "addThumbSelected": "Seleccionado",
      "addCameraSettingsHeader": "AJUSTES DE LA CÁMARA",
      "addThumbnailHeader": "MINIATURA",
      "addLabelPicUrl": "Imagen",
      "addLabelThumbUrl": "Miniatura",
      "addTextPlaceholderUrl": "Introduce la URL de una imagen",
      "addTextPlaceholderUrl2": "Introduce la URL de una página de YouTube",
      "addTextPlaceholderUrl3": "Introduce la URL de una página de Vimeo",
      "addTextPlaceholderUrl4": "Introduce la URL de un vídeo integrado",
      "addLabelVideo": "Vídeo",
      "addMediaVideoOther": "Otro",
      "addMediaVideoHelp": "Comprueba la URL y consigue la vista previa predeterminada",
      "addMediaVideoHelpTooltip1": "Comprobación correcta",
      "addMediaVideoHelpTooltip2": "Error en la comprobación",
      "addMediaVideoHelpTooltip4": "Encuentra la opción que permite integrar el vídeo y copia la URL del vídeo que se muestra en el código",
      "addLabelName": "Nombre",
      "addLabelDescription": "Leyenda",
      "addTextPlaceholder": "Escribir algo",
      "addLocatePlaceholder": "Localizar una dirección o un lugar",
      "addPinColor": "Color",
      "addLatitude": "Latitud",
      "addLongitude": "Longitud",
      "addLatitudePlaceholder": "por ejemplo, 34.056",
      "addLongitudePlaceholder": "por ejemplo, -117.195",
      "addUploading": "Cargando punto de recorrido",
      "addSave": "Añadir punto de recorrido",
      "addMobileUploading": "Cargando imagen",
      "addMobileName": "Introduce un nombre",
      "addMobileNameMandatory": "Error, introduce un nombre.",
      "addMobileError": "Lo sentimos pero se ha producido un error",
      "settingsHeader": "Ajustes",
      "settingsTabLayout": "Diseño",
      "settingsTabColor": "Colores",
      "settingsTabLogo": "Encabezado",
      "settingsTabFields": "Datos",
      "settingsTabExtent": "Extensión",
      "settingsTabZoom": "Nivel de zoom",
      "settingsLayoutExplain": "Selecciona el diseño que desees.",
      "settingsLayoutProfessional": "Panel triple",
      "settingsLayoutModern": "Integrado",
      "settingsLayoutSidePanel": "Panel lateral",
      "settingsLayoutSelected": "Diseño seleccionado",
      "settingsLayoutNew": "¡Novedad!",
      "settingsLayoutSelect": "Seleccionar",
      "settingsLayoutNote": "Recuerde que, en el caso de los puntos que utilicen vídeos, siempre se colocará el título debajo del vídeo, aunque esta opción esté desactivada.",
      "settingsLayoutLocBtn": "Mostrar un botón de localización",
      "settingsLayoutLocBtnHelp": "Es compatible con la mayoría de navegadores. Solo aparece cuando el acceso al story map se realiza mediante HTTPS. No aparece si la historia está integrada.",
      "settingsColorExplain": "Cambia el aspecto eligiendo un tema predefinido, o crea uno propio.",
      "settingsLabelColor": "Colores del encabezado, contenido y pie",
      "settingsLogoExplain": "Personaliza el logotipo del encabezado (el valor máximo es 250 x 50px).",
      "settingsLogoEsri": "Logotipo de Esri",
      "settingsLogoNone": "Sin logotipo",
      "settingsLogoCustom": "Logotipo personalizado",
      "settingsLogoCustomPlaceholder": "URL de imagen",
      "settingsLogoCustomTargetPlaceholder": "Enlace click-through",
      "settingsLogoSocialExplain": "Personaliza el enlace superior derecho del encabezado.",
      "settingsLogoSocialText": "Texto",
      "settingsLogoSocialLink": "Vínculo",
      "settingsLogoSocialDisabled": "El administrador ha deshabilitado esta característica",
      "settingsDataFieldsExplain": "Selecciona los campos de nombre de foto, leyenda y color.",
      "settingsDataFieldsError": "La aplicación no puede determinar los datos de nombre, leyenda o color adecuados. Selecciona los campos que se usarán aquí. Estos ajustes se pueden cambiar más adelante.",
      "settingsFieldsLabelName": "Nombre",
      "settingsFieldsLabelDescription": "Leyenda",
      "settingsFieldsLabelColor": "Color",
      "settingsFieldsReset": "Restablece la selección de campos",
      "settingsExtentExplain": "Establezca la extensión de inicio del Map Tour en el mapa interactivo de la parte inferior.",
      "settingsExtentExplainBottom": "La extensión que defina modificará la extensión de inicio de su mapa. Recuerde que esta extensión no se utiliza si no contiene el primer punto del recorrido. En este caso, el recorrido se abrirá centrado en el primer punto.",
      "settingsExtentDateLineError": "La extensión no puede atravesar el meridiano de longitud 180°",
      "settingsExtentDateLineError2": "Error al calcular la extensión",
      "settingsExtentDrawBtn": "Dibuja una nueva extensión",
      "settingsExtentModifyBtn": "Edita la extensión",
      "settingsExtentApplyBtn": "Vista previa de la ruta de mapa",
      "settingsExtentUseMainMap": "Uso de la extensión de la ruta de mapa",
      "settingsZoomExplain": "Establezca el zoom para los puntos de la historia (opcional).",
      "settingsLabelZoom": "Escala/Nivel",
      "settingsZoomFirstValue": "Ninguno",
      "settingsFieldError": "Selecciona un campo de cada lista",
      "dataTitle": "Crear una capa de Map Tour alojada",
      "dataExplain": "Se creará una nueva capa de entidades para tus imágenes y puntos de recorrido. La capa de recorrido no se compartirá con nadie a menos que compartas tu Map Tour.",
      "dataExplainPortal": "Si la capa de entidades no se crea correctamente, contacte con su administrador de ArcGIS.",
      "dataNameLbl": "Nombre de capa",
      "dataFolderListLbl": "Carpeta",
      "dataFolderListFetching": "Recuperando carpetas ...",
      "dataRootFolder": "Raíz",
      "dataNameError": "Introduce un nombre para el servicio de entidades",
      "dataFolderError": "Selecciona una carpeta válida",
      "dataSrcContainsInvalidChar": "El nombre del servicio de entidades contiene uno o varios caracteres no válidos (-, <, >, #, %, :, \", ?, &, +, /, or ).",
      "dataSrvAlreadyExistsError": "En la organización ya existe un servicio con este nombre. Elige un nombre diferente.",
      "dataBtnSave": "Crear la capa",
      "dataFooterProgress": "Creación en curso",
      "dataFooterSucceed": "Creación satisfactoria. Cargando",
      "dataFooterError": "Error de creación. Inténtalo de nuevo",
      "tabError": "Comprueba todas las fichas por si existen errores",
      "introRecordBtn": "Introducción",
      "introRecordActivate": "Utiliza el punto de partida como introducción (no aparece en la muestra)",
      "coverRecordActivate": "Utilizar el primer punto como portada",
      "coverBuilder": "Configuración de portada",
      "cover": "Portada",
      "showCover": "Mostrar portada",
      "editCover": "Editar portada",
      "coverNoVideo": "El contenido multimedia de la portada no admite vídeo. Seleccione una imagen.",
      "coverPreview": "Para ver la portada, guarde su historia y, luego, previsualícela con el botón Ver historia.",
      "thirdPartyTerms": "Al utilizar un servicio de terceros, usted acepta sus condiciones de servicio: "
    },
    "addPopupJS": {
      "uploadingPicture": "Cargando imagen",
      "uploadSuccess": "Carga satisfactoria",
      "uploadError": "Error al cargar la imagen",
      "uploadError2": "Error al agregar la entidad (etiqueta HTML no válida)",
      "notJpg": "Elige una foto jpeg para cargarla",
      "errorNoPhoto": "Elige una imagen para cargarla",
      "errorNoThumbnail": "Elige una miniatura para cargarla",
      "errorInvalidPicUrl": "Introduzca una URL válida para la imagen. Comienza por HTTPS. Termina en jpg, png, gif o bmp; también puede terminar la URL con '#isImage' para invalidar esta regla.",
      "errorInvalidThumbUrl": "Introduzca una vista en miniatura válida (comienza por https://, termina en jpg, png, gif o bmp).",
      "errorInvalidVideoUrl": "Introduzca una URL válida para el vídeo (comienza por https://)",
      "errorNoName": "Escribe un nombre para este punto de recorrido",
      "errorNoDescription": "Escribe una leyenda para este punto de recorrido",
      "errorNoLocation": "Establece una ubicación para este punto de recorrido"
    },
    "builderJS": {
      "noPendingChange": "Sin cambios no guardados",
      "unSavedChangeSingular": "1 cambio sin guardar",
      "unSavedChangePlural": "cambios no guardados",
      "shareStatus1": "No se ha guardado el recorrido",
      "shareStatus2": "El recorrido se ha compartido públicamente",
      "shareStatus3": "El recorrido se ha compartido con la organización",
      "shareStatus4": "No se ha compartido el recorrido",
      "popoverDiscard": "¿Estás seguro de que deseas descartar los cambios no guardados?",
      "yes": "Sí",
      "no": "No",
      "popoverLoseSave": "Al abrir el visor, perderás los cambios no guardados",
      "ok": "Aceptar",
      "popoverSaveWhenDone": "No olvides guardar los cambios cuando hayas terminado",
      "closeWithPendingChange": "¿Desea realmente confirmar la acción? Sus cambios se perderán.",
      "gotIt": "Aceptar",
      "savingApplication": "Guardando la historia",
      "saveSuccess": "Historia guardada",
      "saveError": "Error al guardar. Inténtalo de nuevo",
      "saveError2": "Error al guardar a causa de una etiqueta HTML no válida en un nombre o una descripción",
      "saveError3": "El título no puede estar vacío",
      "dragColorPicker": "Desplázame<br />o cambia mi color",
      "dataWarningExtent": "Tienes datos fuera de la extensión del mapa web. Estos datos no se usarán como puntos de recorrido. Si quieres usarlos, cambia la extensión del mapa.",
      "dataWarningVisibi": "Tu capa de Ruta de mapa no está visible en la extensión de mapa web actual. Confirma que tu capa de Ruta de mapa esté visible con un mapa grande %MAPSIZE%.",
      "dataWarningEdit": "Editar mapa web",
      "dataWarningClose": "Cerrar",
      "signIn": "Inicia sesión con una cuenta en",
      "signInTwo": "para guardar la historia.",
      "switchBM": "Cambiar mapa base"
    },
    "organizePopupJS": {
      "messageStart": "Has elegido eliminar",
      "messageSinglePoint": "un punto de recorrido",
      "messageMultiPoint": "dos puntos",
      "messagePermantRemove": "Esto eliminará permanentemente",
      "messageRecord": "el registro",
      "messageRecordPlural": "los registros",
      "messageConfirm": "de la base de datos. ¿Deseas continuar?",
      "labelButtonShow": "Mostrar",
      "labelButtonHide": "Ocultar"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Esto eliminará la imagen y la miniatura de forma permanente",
      "popoverDeleteWarningThumb": "Esto eliminará la miniatura de forma permanente",
      "popoverUploadingPhoto": "Actualizando imagen y miniatura",
      "popoverUploadingThumbnail": "Actualizando miniatura",
      "popoverUploadSuccessful": "Carga satisfactoria",
      "popoverUploadError": "Error de carga. Inténtalo de nuevo",
      "changePicAndThumb": "Cambiar imagen",
      "changeThumb": "Cambiar miniatura",
      "selectPic": "Cambiar medio",
      "selectThumb": "Cambiar miniatura",
      "uploadPicAndThumb": "Aplicar"
    },
    "headerJS": {
      "editMe": "¡Modifícame!",
      "templateTitle": "Establecer título",
      "templateSubtitle": "Establecer subtítulo",
      "edit": "Editar"
    },
    "crossFaderJS": {
      "setPicture": "Establecer título de imagen",
      "setCaption": "Establecer leyenda de imagen"
    },
    "importPopup": {
      "title": "Importar",
      "prevBtn": "Atrás",
      "nextBtn": "Siguiente"
    },
    "importPopupHome": {
      "header": "¿Dónde se almacenan las imágenes?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "imágenes",
      "videos": "vídeos",
      "disabled": "El administrador ha deshabilitado esta entidad",
      "disabledPortal": "Esta entidad requiere que el portal tenga un servidor host. Póngase en contacto con el administrador de Portal for ArcGIS.",
      "header1": "Tus imágenes deben compartirse públicamente.",
      "header2": "La importación se limitará a los primeros %NB1% %MEDIA%.",
      "emptyDataset": "Error, no se han encontrado imágenes",
      "footerImport": "Importar",
      "selectAlbum": "Selecciona un álbum público",
      "selectAlbum2": "Selecciona un álbum",
      "pleaseChoose": "Elige",
      "userLookup": "Buscar",
      "userLookingup": "Buscando",
      "csv": "Referenciado en un CSV",
      "advanced": "Opciones avanzadas",
      "advancedScratchLbl": "Iniciar recorrido nuevo",
      "advancedScratchTip": "Cree un recorrido vacío al que agregar puntos de recorrido. Su contenido multimedia ya debe estar en línea. Esta opción no admite la carga de sus imágenes.",
      "advancedCSVLbl": "Importar datos de recorrido de un archivo CSV",
      "advancedCSVTip": "Importe el contenido de su recorrido desde un archivo CSV que haga referencia a su contenido multimedia en línea. Esta opción no admite la carga de sus imágenes.",
      "advancedCommonTip": "Es necesario que las imágenes y vídeos ya estén en línea.",
      "select": "Crear una selección",
      "locUse": "Utilizar geolocalización de imágenes",
      "locExplain": "Quizá prefiera no usar las ubicaciones de fotografías, dado que se heredarán del álbum y resultará en que todas las fotos se encuentren en la misma ubicación.",
      "locExplain2": "Quizá prefiera no usar las ubicaciones de vídeos, dado que se heredarán de los ajustes del usuario y resultará en que todos los vídeos se encuentren en la misma ubicación."
    },
    "viewFlickr": {
      "title": "Importación de Flickr",
      "header": "Introduzca su nombre de usuario de Flickr y seleccione un álbum o una etiqueta para su importación.",
      "userInputLbl": "Introduce un nombre de usuario",
      "signInMsg2": "Usuario no encontrado",
      "selectSet": "Seleccionar un álbum",
      "selectTag": "o selecciona una etiqueta",
      "footerImportTag": "Importar la etiqueta seleccionada",
      "footerImportSet": "Importar el álbum seleccionado"
    },
    "viewFacebook": {
      "title": "Importación de Facebook",
      "header": "Autentica con tu cuenta de usuario de Facebook o usa una página pública. Los álbumes se pueden usar para crear recorridos de mapa públicos que no necesiten autenticación con un usuario de Facebook, lo que permite que los comentarios y las etiquetas de \"me gusta\" se mantengan en privado.",
      "leftHeader": "Usuario de Facebook",
      "rightHeader": "Página de Facebook",
      "pageExplain": "Una página de Facebook es una marca/producto público o famoso como <b>esrigis</b>. Puedes obtener el nombre de la página después de la  primera '/' de la URL de la página.",
      "pageInputLbl": "Introduce un nombre de página",
      "lookupMsgError": "No se encontró la página"
    },
    "viewPicasa": {
      "title": "Importación de Google+",
      "header": "Introduzca su dirección de correo electrónico o su Id.",
      "userInputLbl": "Dirección de correo electrónico o Id. de Picasa/Google+",
      "signInMsg2": "Cuenta no encontrada",
      "signInMsg3": "No hay ningún álbum público",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Más información</a>",
      "howToFind2": "Copie los dígitos que hay entre la primera y la segunda '/' de cualquier página de Picasa"
    },
    "viewCSV": {
      "title": "Importación de CSV",
      "uploadBtn": "Selecciona o coloca un archivo CSV",
      "resultHeaderEmpty": "El archivo CSV está vacío",
      "resultHeaderSuccess": "%NB_POINTS% puntos cargados",
      "resultHasBeenLimited": "La importación se ha limitado a los primeros %VAL1% puntos de %VAL2% para respetar el límite de %VAL3% puntos por recorrido",
      "browserSupport": "El navegador no es compatible. Si quieres utilizar un archivo CSV tienes que <a href='http://browsehappy.com/' target='_blank'>actualizar el navegador</a> o utilizar el visor de mapas web de ArcGIS.com (consulta la ayuda).",
      "errorLatLng": "No se han encontrado los campos de latitud y longitud. Los valores posibles de latitud son: <i>%LAT%</i>y los de longitud son: <i>%LONG%</i>.",
      "errorFieldsExplain": "La carga falló debido a que no se encontraron los siguientes campos obligatorios",
      "errorFieldsName": "Los posibles valores de <b>Nombre</b> son: %VAL%",
      "errorFieldsDesc": "Los posibles valores de <b>Descripción</b> son: %VAL%",
      "errorFieldsUrl": "Los posibles valores de <b>URL de imagen</b> son: %VAL%",
      "errorFieldsThumb": "Los posibles valores de <b>URL de vista en miniatura</b> son: %VAL%",
      "errorFields2Explain": "Se ha producido un error en la carga porque el archivo CSV no utiliza los mismos atributos que la capa en los siguientes atributos",
      "errorFields2Name": "<b>Nombre</b> usa %VAL1% en lugar de %VAL2%",
      "errorFields2Desc": "<b>Descripción</b> usa %VAL1% en lugar de %VAL2%",
      "errorFields2Url": "<b>URL de imagen</b> usa %VAL1% en lugar de %VAL2%",
      "errorFields2Thumb": "<b>URL de vista en miniatura</b> usa %VAL1% en lugar de %VAL2%",
      "resultFieldsAll": "Se han importado todos los atributos",
      "resultFieldsNotAll": "Los siguientes atributos no se importaron porque no existen en la capa de mapa",
      "resultFieldsNotAll2": "Se han importado los siguientes atributos",
      "footerNextBtnResult": "Importar al mapa web",
      "footerProgress": "Importación en curso",
      "footerSucceed": "Importación correcta. Cargando"
    },
    "viewYoutube": {
      "title": "Importación de YouTube",
      "header": "Introduce un nombre de usuario de YouTube para buscar vídeos que se hayan compartido públicamente.",
      "pageInputLbl": "Introduce un nombre de usuario de YouTube",
      "lookupMsgError": "Usuario no encontrado",
      "howToFind": "Cómo encontrar un nombre de usuario de YouTube",
      "howToFind2": "El nombre de usuario se muestra bajo los vídeos",
      "found": "Encontrados",
      "noData": "No se han encontrado vídeos públicos"
    },
    "viewGeoTag": {
      "title": "Selecciona y localiza tus imágenes/vídeos",
      "header": "Los elementos ubicados se importarán. Haga clic en los elementos no ubicados que desee importar, para ubicarlos.",
      "headerMore": "Ayuda",
      "headerExplain": "Al hacer clic en el botón <b>Importar</b>, solo se importan las imágenes o los vídeos enumerados en la pestaña <b>Ubicados</b>.<br><br>La información de geolocalización almacenada junto con las imágenes o los vídeos se importa automáticamente, si es posible acceder a ella. Todos los elementos sin geolocalización se enumeran en la pestaña <b>Para ubicar</b>. Para ubicar un elemento enumerado en esta pestaña, haga clic en él y, a continuación, haga clic en la ubicación deseada del mapa.<br><br>Para eliminar un elemento de la pestaña <b>Ubicados</b> de modo que no se importe, haga clic en el botón No importar que verá al situar el cursor sobre el elemento.<br><br>Sugerencia: Si la información de geolocalización de su propio contenido multimedia no se importa, compruebe los ajustes de privacidad de su cuenta. Por ejemplo, en los ajustes de su cuenta de Flickr, asegúrese de que los datos de EXIF no estén ocultos. Además, si la opción de privacidad de Flickr para la importación de datos EXIF de las nuevas cargas está desactivada (la opción predeterminada), las geolocalizaciones no se almacenarán en Flickr para sus imágenes a no ser que las cargue de nuevo o especifique manualmente sus ubicaciones en Flickr.",
      "leftPanelTab1": "Para localizar",
      "leftPanelTab2": "Localizado",
      "clickOrTap": "Haga clic en el mapa para ubicar",
      "clearLoc": "Borrar ubicaciones",
      "clickDrop": "No importar",
      "footerImport": "Importar",
      "footerProgress": "Importación en curso",
      "footerSucceed": "Importación correcta. Cargando...",
      "loading": "Cargando",
      "error": "Error al importar la geolocalización de las imágenes. Se han ignorado las geolocalizaciones."
    },
    "initPopup": {
      "title": "Bienvenido al builder de recorridos de mapa",
      "prevBtn": "Atrás",
      "nextBtn": "Siguiente"
    },
    "initPopupHome": {
      "header1": "¿Dónde están tus imágenes y vídeos?",
      "header2": "Este asistente te ayudará a crear una ruta de mapa a partir de imágenes que ya estén almacenadas en línea o las importará en la cuenta de ArcGIS Online for Organizations.",
      "title1": "Ya están en línea",
      "title2": "Necesito cargar mis imágenes",
      "hostedFSTooltip": "Cargue sus imágenes y almacénelas en su recorrido (no admite vídeo).",
      "hostedFsNA": "Debes ser publicador o tener otro rol con el privilegio de publicar capas de entidades alojadas. Contacta con tu administrador de ArcGIS.",
      "hostedFsNA2": "Solo está disponible con una suscripción a ArcGIS Online. <a href='%LINK%'>Regístrate para obtener una versión de prueba</a>",
      "footer1": "Cuando termines, no olvides compartir la ruta de mapa con tu audiencia a través de la página de elementos de la aplicación.",
      "footer3": "Descargar la plantilla CSV",
      "footer4": "Utilizar\"Guardar como\" si no se descarga",
      "footer4bis": "Si la descarga no se inicia, haz clic con el botón secundario y selecciona \"Guardar como\"",
      "footer5": "Más información",
      "footerProgress": "Creación en curso",
      "footerSucceed": "Se ha creado correctamente. Cargando..."
    },
    "helpPopup": {
      "title": "Ayuda",
      "close": "Cerrar",
      "tab1": {
        "title": "Introducción",
        "moreInfo": "Para obtener más información",
        "infoSites": "Visite la <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>sección Map Tour</a> del <a href='https://storymaps.arcgis.com' target='_blank'>sitio web de Esri Story Maps.</a>",
        "mtFAQ": "Consulte las <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Preguntas frecuentes de Map Tour.</a>",
        "myStories": "Puede administrar sus Map Tours y buscar errores en ellos en <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Mis historias</a>, en el sitio web.",
        "div1": "La plantilla de Ruta de mapa está diseñada para presentar la información geográfica donde exista un elemento fotográfico o multimedia atractivo en la historia que deseas contar.",
        "div2": "La plantilla crea una atractiva aplicación web fácil de usar que te permitirá presentar un conjunto pequeño de lugares en un mapa con una secuencia numerada por el que podrán navegar los usuarios. La plantilla se ha diseñado para su uso en cualquier navegador web y dispositivo, incluidos los smartphones y las tablets. <br /><br />",
        "div42": "Para ver ejemplos de recorridos de mapa creados por otros usuarios, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visite la galería</a> en el <a href='https://storymaps.arcgis.com/' target='_blank'>sitio web de Story Maps</a>. También puede seguirnos en Twitter en <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "¡Nos encantaría conocer su opinión! Infórmenos de los problemas detectados y de las características que necesita visitando el foro de Story Maps en <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet.</a>"
      },
      "tab2": {
        "title": "Datos",
        "div1": "El elemento principal a tener en cuenta cuando se crea un Map Tour es elegir dónde se van a almacenar sus imágenes. Un Map Tour puede usar imágenes almacenadas en servicios de uso compartido de imágenes o en cualquier servidor web, o bien imágenes que usted carga desde el disco.",
        "div1a": "Consulta la última sección de esta pestaña para obtener información detallada acerca de los formatos de imágenes y vídeos compatibles.",
        "div2": "El builder interactivo te da dos opciones para gestionar las imágenes de la ruta de mapa:",
        "div3": "<ul><li>Puede utilizar <b>fotos que ya estén en línea</b>, por ejemplo, imágenes de Flickr o Google+, o almacenadas en su propio servidor web. Se hará referencia a estas imágenes en su Map Tour mediante sus URL.</li><li>También puede <b>cargar fotos desde su equipo</b> directamente en su Map Tour. Esta opción de carga requiere una suscripción de ArcGIS y tener privilegios de publicador o administrador, porque el servicio de entidades alojado se crea automáticamente para usted, y en él sus fotos están almacenadas como adjuntos.</li></ul>",
        "div4": "Los principales casos de uso son:",
        "div4b": "<b>Sus fotos aún no están alojadas</b> y usted tiene una suscripción a ArcGIS: Su mejor opción es utilizar un servicio de entidades alojado. Al igual que los servicios públicos de uso compartido de imágenes, optimizaremos sus fotos para crear imágenes de carga rápida y tendrá acceso a todas las capacidades de administración general y de datos de la plataforma ArcGIS.",
        "div5": "<b>No eres miembro de ninguna organización</b>: en primer lugar, debes cargar las imágenes en un sitio web de uso compartido de fotos o en tu propio sitio web. El builder te ayudará a utilizar estas imágenes, que seguirán alojadas en su ubicación original.",
        "div6": "<b>Deseas volver a utilizar un servicio de entidades existente</b> que almacena las imágenes como adjuntos o que hace referencia a imágenes externas: consulta la siguiente sección detallada.",
        "div7": "<b>Eres usuario de una versión anterior</b> de la plantilla de ruta de mapa y ya posees un archivo CSV que hace referencia a las imágenes y miniaturas: puedes importarlo y refinar los datos. El builder solo es compatible con los archivos CSV que utilicen campos lat./long.; puedes seguir utilizando los archivos CSV basados en direcciones mediante el mapa web (consulta la siguiente sección).",
        "div8": "Importando de los servicios de intercambio de fotos en línea",
        "div9a": "Facebook ya no se admite, ${learn}.",
        "learn": "más información",
        "div9": "La operación de importación hace referencia a imágenes que ya se encuentran alojadas mediante el almacenamiento de las direcciones URL en una recopilación de entidades de mapas web. Las imágenes no se almacenan en ArcGIS Online. Si no se puede acceder a las imágenes alojadas, no estarán disponibles en la ruta de mapa y aparecerá la imagen 'Imagen no disponible'. En función del proveedor de servicios fotográficos, la ruta de mapa podría no importar el nombre, la descripción ni la ubicación de las imágenes. Estos atributos se almacenan en el mapa web y las modificaciones de los servicios en línea no aparecerán reflejadas en la ruta de mapa.",
        "div10": "Almacenando las imágenes en un servidor web",
        "div11": "Si decide alojar sus imágenes en su propio servidor web (en lugar de acceder a las imágenes en Flickr o Google+, o cargarlas directamente en su recorrido), deberá crear manualmente vistas en miniatura para sus imágenes. El uso de imágenes de máxima resolución para la vista en miniatura supondrá una pérdida de rendimiento. Consulte estas <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>Preguntas frecuentes</a> para obtener sugerencias sobre el tamaño de sus imágenes si va a acceder a ellas en la web directamente a través de URL.",
        "div12": "Usar datos de SIG existentes",
        "div13": "Cualquier servicio de entidades, archivo CSV o shapefile que contenga puntos se puede utilizar como fuente de datos de un Map Tour si contiene el conjunto de campos que la aplicación espera. Tiene que agregarlo como capa a un mapa web de ArcGIS y, luego, compartir el mapa creando un Map Tour.",
        "div14": "Los valores compatibles para los nombres de campo son (no distingue entre mayúsculas y minúsculas):",
        "div151": "Nombre",
        "div152": "Descripción",
        "div153": "Imagen",
        "div154": "Miniatura",
        "div155": "Color ",
        "div16": "Si la aplicación no encuentra campos coincidentes al utilizar un servicio de entidades, el visor no funcionará hasta que configure los campos que se utilizarán mediante el builder. Las capas Shapefile y CSV agregadas al mapa web deben incluir todos los campos obligatorios o el builder no funcionará.",
        "div162": "Al utilizar un servicio de entidades que almacene las imágenes como adjuntos, <b>solamente se utilizarán las entidades con dos adjuntos</b>. El primer adjunto define la imagen principal y el segundo, la vista en miniatura.",
        "div17": "Los campos de imágenes y miniaturas son obligatorios para los servicios de entidades sin adjuntos y opcionales (pero muy recomendables) para los servicios de entidades con adjuntos. Si el servicio tiene los adjuntos habilitados, el builder te permitirá cargar imágenes como adjuntos. En caso contrario, solamente podrás editar las direcciones URL de la imagen y la vista en miniatura.",
        "div172": "Si están presentes, siempre se utilizarán los campos de imagen y miniatura, y no se consultarán los adjuntos del servicio de entidades.",
        "div173": "Puedes descargar archivos Shapefile y CSV de ejemplo en:",
        "div174": "Consulte estas <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>Preguntas frecuentes</a> para más información sobre el uso de datos de SIG existentes.",
        "div18": "Creación de servicios de entidades alojados desde archivos CSV o Shapefile",
        "div19": "Al crear un servicio de entidades alojado a partir de un archivo CSV o Shapefile, los adjuntos no se habilitan de forma predeterminada. Para habilitarlos, abre la página de detalles del servicio de entidades, haz clic en la flecha pequeña de la sección de capas y podrás ver dicha opción. La ruta de mapa seguirá utilizando las imágenes y las miniaturas a las que se hace referencia mediante atributos. De forma opcional, si deseas cargar las imágenes como adjuntos del servicio de entidades, podrás hacerlo mediante dos botones en el panel de imágenes (\"Cambiar imagen\" y \"Cambiar vista en miniatura\").",
        "div20": "Vídeos y formatos de imagen compatibles",
        "div21": "Si accede a imágenes en Flickr o Google+, Map Tour accede automáticamente a estas imágenes como archivos .jpg. Si carga las imágenes en el builder de Map Tour, las imágenes deben tener el formato .jpg o .jpeg. Si hace referencia a las imágenes directamente en la web a través de sus URL, los formatos de imagen admitidos son .jpg, .jpeg, .png, .gif y .bmp. Los vídeos de YouTube se admiten directamente.",
        "div22": "La plantilla de ruta de mapa no incluye un reproductor de vídeos, por lo que deberás utilizar el reproductor de vídeos externo ofrecido por tu servicio de alojamiento de vídeos favorito (busca la opción para integrar el vídeo y copia de la dirección URL presente en un código determinado). Si deseas alojar un vídeo tú mismo, puedes crear una página HTML que contenga un reproductor de vídeos como <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "El builder interactivo no ofrece ningún cuadro de diálogo para incluir vídeos al utilizar servicios de entidades con adjuntos, pero es posible hacerlo mediante la edición de datos fuera del builder interactivo. En el visor de mapas de arcgis.com, si modificas los campos de imágenes para que señalen a un vídeo externo y agregas un parámetro especial al final de la dirección URL (#isVideo), se considerará que el medio es un vídeo.",
        "div24": "Ten en cuenta que seguirás necesitando dos adjuntos de imágenes válidos o no se utilizará el punto. No se puede utilizar vídeos al emplear adjuntos del servicio de entidades sin los campos de imágenes y vistas en miniatura."
      },
      "tab3": {
        "title": "Personalización",
        "div1": "El builder proporciona varias opciones de personalización a las que se puede acceder a través del botón CONFIGURACIÓN del panel superior. Si no encuentras la opción esperada, también proporcionamos una versión para descarga que puedes desplegar en el servidor web y mejorarla para adaptarla a tus necesidades.",
        "div2": "Se recomienda utilizar la versión alojada, salvo en los siguientes casos:",
        "div3": "<li>No ofrece la personalización de la IU deseada, como el uso de una imagen de fondo de encabezado.</li><li>Eres desarrollador y deseas mejorar la aplicación.</li>",
        "div4": "Se puede configurar la versión para descarga a través de un mapa web o un identificador de aplicaciones de representación cartográfica. Los principales casos de uso son:",
        "div41": "Genera tu ruta de mapa con el builder interactivo en el entorno alojado y configura la plantilla con el identificador de la aplicación de mapas web. Se aplicará la configuración que hayas definido con el builder interactivo.",
        "div42": "El mapa web se genera fuera del builder interactivo y se configura la plantilla con el identificador de mapas web. Necesitarás leer la documentación para obtener más información sobre la configuración de la plantilla.",
        "div43": "Ten en cuenta que hay una versión descargable disponible del builder interactivo, pero con algunas restricciones técnicas en exploradores como las versiones anteriores a Internet Explorer 10.",
        "div5": "Para descargar la versión más reciente de la plantilla y obtener más información sobre cómo se utiliza, visita la <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>página del proyecto GitHub</a>."
      },
      "tab4": {
        "title": "Consejos",
        "div0": "Exploradores compatibles",
        "div0a": "El visor de rutas de mapa es compatible con IE8 (y posteriores). El builder interactivo es compatible con IE9 (y posteriores). Lo hemos probado de forma activa en todos los exploradores principales, pero, si experimentas dificultades, te recomendamos que utilices Chrome.",
        "div0b": "Si experimentas dificultades, ponte en contacto con nosotros. Mientras tanto, si generas la ruta de mapa con la plantilla CSV, se minimizará la interacción con la interfaz del builder.",
        "div1": "Imágenes",
        "div2": "Aunque puede utilizar imágenes de distintos tamaños, formas y orientación en un Map Tour, recomendamos las imágenes en orientación horizontal en lugar de vertical. Las imágenes con una relación de aspecto de 4:3 son las que mejor encajan. En los diseños Panel triple e Integrado, en los que el título se superpone a la imagen, el uso de imágenes en orientación vertical puede hacer que el título oscurezca gran parte de la imagen. En los diseños Panel triple e Integrado, recomendamos el uso del mismo tamaño y forma en todas las imágenes en la medida de lo posible. De esta forma, el usuario no se distraerá por tener imágenes de distinto tamaño a medida que avanzan por el recorrido.",
        "div2a": "Te recomendamos que utilices un tamaño máximo de la imagen de 1.000 píxeles de ancho x 750 píxeles para las imágenes principales y de 140 x 93 para las vistas en miniatura.",
        "div3": "Establece el formato de texto de tu leyenda usando etiquetas HTML",
        "div4": "Puede introducir etiquetas HTML en sus títulos para definir el formato y los vínculos. Por ejemplo, estas etiquetas agregan un hipervínculo verde:",
        "div4aa": "<b>Cree una portada para su recorrido de Panel lateral</b><br>El diseño Panel lateral admite una portada opcional, de forma que pueda llamar la atención de su público con una imagen atractiva y a pantalla completa. Para configurar la página de portada de un recorrido de Panel lateral, primero agregue algunos o todos los puntos a su recorrido. Luego, haga clic en el botón Organizar y, en el cuadro de diálogo que aparece, asegúrese de que el punto de recorrido que desee utilizar para definir la página de portada sea el primer punto de su recorrido. Después, active la casilla 'Utilizar el primer punto como portada' en ese cuadro de diálogo. El nombre de su primer punto de recorrido se convertirá en el primer título que aparecerá en la portada, el título de ese punto se convertirá en el subtítulo y la imagen del punto se utilizará como la imagen de página de portada. La portada no admite el uso de vídeos. Consulte estas <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>Preguntas frecuentes</a> para más información.</a>",
        "div4a": "Escribe un buen subtítulo para el recorrido",
        "div4b": "Tómese su tiempo para escribir un subtítulo atractivo para su recorrido. El subtítulo es una buena forma de atraer a los usuarios hacia su recorrido y contarles qué descubrirán en él. También es un buen lugar para informar al público sobre el estado o el país en el que tiene lugar el recorrido. Por ejemplo, no suponga que todo el mundo sabe dónde se encuentra la ciudad o el pueblo al que corresponde su recorrido. No obstante, evite los subtítulos demasiado largos. Si no se le ocurre un buen subtítulo, déjelo vacío. A diferencia de los diseños Panel triple e Integrado, el diseño Panel lateral no admite los subtítulos en su encabezado. Si usa la opción de portada con el diseño Panel lateral, el título del primer punto de su recorrido se muestra en la portada y hace las veces de subtítulo de su recorrido.",
        "div5": "Capas de apoyo",
        "div6": "Puede agregar capas complementarias adicionales para proporcionar contexto al Map Tour. Estas capas pueden contener otras características geográficas que desea que aparezcan en el mapa además de los puntos del Map Tour, por ejemplo, un área de estudio, una ruta a pie o de conducción que una los puntos del recorrido, etc. La plantilla Map Tour muestra estas capas complementarias adicionales con la simbología que usted especifique en el mapa web, pero los elementos emergentes definidos para las capas no están disponibles.  Para agregar capas complementarias a su recorrido, guarde su trabajo y cierre el Builder de Map Tour. A continuación, abra el mapa web utilizado en su recorrido. Lo encontrará en ArcGIS Mi contenido o en la sección Mis historias del sitio web de Story Maps.",
        "div7": "Mantén tu recorrido corto y agradable",
        "div8": "Hay un límite de 99 puntos por recorrido. Por supuesto, la mayoría de las rutas de mapa tendrán menos. No esperes a que los demás usuarios deseen pasar por demasiados puntos de recorrido. Aunque el tema te resulte fascinante, puede que a otros usuarios no se lo parezca.",
        "div10": "Modo integrado",
        "div11": "Si desea integrar la plantilla en otro sitio web a través de iframe, al agregar el parámetro adicional \"&embed\" al final de la URL se eliminará el encabezado.",
        "div12": "Evite utilizar un ancho de iFrame estrecho que haga que el recorrido de mapa cambie a su vista de pantalla pequeña de alta respuesta, que es la misma vista que el recorrido usa en los dispositivos móviles. Para maximizar la facilidad de uso, recomendamos que cuando integre un recorrido de mapa proporcione un vínculo junto al recorrido integrado para que los usuarios puedan iniciar el recorrido a pantalla completa."
      },
      "tab5": {
        "title": "Publicación",
        "div1": "Cuando termines, no olvides compartir el recorrido del mapa con el público mediante el botón de COMPARTIR o la página de elementos de la aplicación de ArcGIS Online.",
        "div2a": "Compartir el recorrido mediante el builder",
        "div2b": "Con el botón COMPARTIR se actualizará la aplicación y los elementos del mapa web. Si los datos de tu recorrido están almacenados en un elemento de servicio de entidades, también se actualizarán. Si has agregado otras capas mediante el visor de mapas de ArcGIS.com, estas no se actualizarán. Esto puede dar lugar a que el recorrido no se comparta como esperabas. Los elementos que ya tienen los privilegios necesarios (o más) no se actualizarán.",
        "div2c": "Compartir el recorrido mediante ArcGIS Online",
        "div2d": "Cuando compartes la aplicación mediante ArcGIS Online, si es necesario se te pedirá que actualices los recursos dependientes (mapa web, servicio de entidades, capa de decoración) que no se han compartido del mismo modo. Si el recorrido del mapa es público y uno de tus recursos no se ha compartido con el público, se redirigirá a los usuarios a la página de inicio de sesión de ArcGIS Online.",
        "div3t": "Seguridad del servicio de entidades",
        "div3a": "Si estás utilizando un servicio de entidades alojado creado mediante el builder de rutas de mapa, la aplicación administra la seguridad del servicio por ti y serás la única persona con privilegios de edición, incluso aunque compartas el servicio públicamente.",
        "div3t2": "Antes de compartir el recorrido con el público",
        "div3": "Asegúrate de que el recorrido funciona cuando no has iniciado sesión con tu cuenta de ArcGIS.com. La URL que vas a utilizar no debe redirigir a una página de inicio de sesión ni al modo del builder.",
        "div4": "Es recomendable comprobar el aspecto del recorrido del mapa en un iPad con orientación horizontal para comprobar si se ve bien en este dispositivo tan utilizado. Esto te permitirá saber si los títulos cubren gran parte de las imágenes o si el subtítulo cabe y no es demasiado largo para que aparezca cortado.",
        "div5a": "Recomendación para la búsqueda",
        "div5b": "Para ayudar a que los usuarios que realizan búsquedas en ArcGIS Online encuentren tu recorrido del mapa, te recomendamos que agregues la etiqueta 'mapa de historia' ('story map') en la página de elementos de la aplicación del recorrido del mapa (no en la página de elementos del mapa web), junto con otras etiquetas, como el nombre del estado o la provincia donde se encuentra el recorrido, el nombre del país (si está fuera de Estados Unidos) y etiquetas temáticas como 'arte público', 'guía turística' o 'lugares históricos'. Estas etiquetas también nos permiten en Esri encontrar ejemplos de buenos recorridos para mostrarlos en nuestras galerías y promocionarlos en las redes sociales. También te recomendamos que cargues una imagen en miniatura bonita en la página de elementos de la aplicación, como una pequeña captura de pantalla o una imagen del recorrido. Esta es la imagen que se utilizará automáticamente si el recorrido del mapa se agrega a una galería de ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Se ha guardado el recorrido",
      "manageStory": "Administrar tu historia",
      "manageStoryA1": "Sugerencia: Puede usar %LINK1% para buscar errores en su historia, cambiar el modo en que se comparte, hacer que se vea bien en las redes sociales, etc. Más información sobre Mis historias %LINK2%.",
      "manageStoryA1V1": "Mis historias",
      "manageStoryA1V2": "aquí",
      "shareTitle": "Compartir ruta",
      "sharePrivateHeader": "Tu ruta no está compartida. ¿Quieres compartirla?",
      "sharePrivateBtn1": "Compartir públicamente",
      "sharePrivateBtn2": "Compartir con mi organización",
      "sharePrivateProgress": "Uso compartido en curso...",
      "sharePrivateErr": "Error del uso compartido. Inténtalo de nuevo o",
      "sharePrivateOk": "Uso compartido actualizado, cargando...",
      "sharePreviewAsUser": "Presentación preliminar",
      "shareHeader1": "Tu ruta está <strong>accesible públicamente</strong>.",
      "shareHeader2": "Tu ruta está accesible para los miembros de tu organización (se necesita iniciar sesión).",
      "shareLinkHeader": "Compartir ruta",
      "shareLinkOpen": "ABRIR",
      "shareA1": "Usa %SHAREIMG% en <a href='%LINK1%' target='_blank'>la página de elemento de la aplicación</a>. Si también quieres dejar de compartir el mapa web, usa <a href='%LINK2%' target='_blank'>la página de elemento del mapa web</a>.",
      "shareWarning": "Se ha deshabilitado la opción de compartir %WITH% porque no eres el propietario del <a href='%LINK%' target='_blank'>mapa web</a>.",
      "shareWarningWith1": "públicamente",
      "shareWarningWith2": "públicamente y con la organización",
      "viewStory": "Ver historia"
    },
    "locator": {
      "error": "Ubicación no disponible"
    },
    "saveErrorSocial": {
      "title": "Actualización de uso compartido de redes sociales",
      "panel1": "La apariencia de tu historia en las redes sociales ha mejorado, pero el título del elemento de tu aplicación web en ArcGIS no coincide con el título de tu historia.",
      "panel1tooltip": "Al definir un título, un resumen y una imagen de la vista en miniatura, tu historia tendrá este aspecto:",
      "panel2": "Indica el título que deseas utilizar en las redes sociales:",
      "panel2q1": "Título de la historia (recomendado)",
      "panel2q1tooltip": "Si eliges esta opción, el título de tu elemento se modificará para que coincida con el título de la historia. Todos los cambios que se realicen en el builder se sincronizarán.",
      "panel2q2": "Título del elemento",
      "panel3": "Para mejorar aún más la apariencia de tu historia en las redes sociales, utiliza ${MYSTORIES} para agregar un resumen y una imagen de la vista en miniatura.",
      "panel4": "No volver a advertirme sobre esta historia",
      "mystories": "Mis historias",
      "btnSave": "Guardar"
    },
    "bannerNotification": {
      "learnMore": "Más información",
      "close": "Cerrar",
      "dontShowAgain": "No volver a mostrar este mensaje"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Mensaje importante sobre seguridad web y Story Maps",
      "s1h1": "Esri está mejorando la seguridad de Story Maps",
      "s1p1": "Sus Story Maps viven en la web y la comunidad web siempre está trabajando para establecer e implementar una mejor seguridad. HTTPS, que ofrece una conexión segura al contenido transmitido por Internet, está emergiendo como la forma esperada de acceder a contenido web. La mayoría de navegadores modernos ahora muestran mensajes de advertencia cuando se utiliza HTTP en lugar de HTTPS. Debido a este estándar emergente, recomendamos encarecidamente que utilice vínculos HTTPS para crear y compartir Story Maps y usar únicamente URL de HTTPS al integrar contenido de web o vincular a imágenes de un Story Map.",
      "s1p2": "Desde el punto de vista práctico, significa que se debería acceder a un Story Map y todo su contenido (incluidas imágenes, capas, aplicaciones y sitios web integrados) por medio de vínculos que comiencen por HTTPS en lugar de HTTP. Con ello garantiza una experiencia óptima a sus lectores, ya que la mayoría de navegadores web indicarán que sus historias son seguras.",
      "s2h1": "¿Qué tengo que hacer?",
      "s2p1": "Esri está trabajando para que esta sea una transición fácil para los autores y lectores de Story Maps. Ahora, los builders de Story Maps y Mis historias cuentan con herramientas que le ayudarán a encontrar contenido no seguro (HTTP) en sus historias y le harán recomendaciones para actuar al respecto. Compruebe si sus historias tienen contenido no seguro y actualícese a HTTPS lo antes posible.",
      "action1": "Cerrar",
      "action2": "Comprobar mis historias ahora",
      "action3": "Más información"
    },
    "embedBar": {
      "share": "Compartir",
      "fullScreen": "Pantalla completa",
      "enlarge": "Ampliar",
      "newTab": "Abrir en una nueva pestaña",
      "tagline": "Un story map",
      "exitFullScreen": "Salir de pantalla completa"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "¿Podemos preguntarle algo? Nos ayudará a dar forma al futuro de los Story Maps.",
      "s1h1": "Comparta su opinión y dé forma al futuro",
      "s1p1": "Sus comentarios son nuestra principal fuente de opiniones y, saber más acerca de usted nos ayuda a mejorar los Story Maps. Le agradeceríamos que participara en esta breve encuesta de tan solo tres minutos.",
      "s2p1": "Como siempre ¡gracias por usar Esri Story Maps!",
      "action1": "Cerrar",
      "action2": "Responder a la encuesta"
    }
  }
});