define(
({
		viewer: {
			loading: {
				step1: "CARGANDO APLICACIÓN",
				step2: "CARGANDO DATOS",
				step3: "INICIALIZANDO EL RECORRIDO",
				fail: "Lo siento. Error al cargar el Recorrido de mapa",
				failButton: "Reintentar"
			},
			errors: {
				boxTitle: "Se ha producido un error",
				invalidConfig: "Error muy grave: configuración no válida",
				invalidConfigOwner: "Error muy grave: configuración no válida (se requiere el propietario autorizado)",
				invalidConfigNoWebmap: "Error muy grave: configuración no válida (se requiere el mapa web y el propietario autorizado)",
				createMap: "No se puede crear el mapa",
				invalidApp: "Error muy grave: la aplicación no se puede cargar",
				noLayer: "El mapa web no contiene una capa de datos válida para el Recorrido de mapa.",
				noLayerNoHostedFS: "El mapa web no contiene una capa de datos válida para Recorrido de mapa y no tienes los permisos necesarios para crear un Servicio de entidad alojado.",
				noLayerMobile: "Bienvenido a la aplicación web Recorrido de mapa. La configuración no está configurada. El creador de Recorrido de mapa no está admitido en dispositivos móviles.",
				noLayerView: "Bienvenido a la aplicación web Recorrido de mapa.<br />La aplicación aún no está configurada.",
				noBuilderWebmapData: "Los datos integrados en el mapa Web no son compatibles con el builder de Recorrido de mapa. Para usar esta herramienta, debes usar un Servicio de entidades. Para usar tu capa de datos real, tienes que utilizar la versión para descargar del Recorrido de mapa.",
				appSave: "Error al guardar la aplicación web",
				mapSave: "Error al guardar el mapa web",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "No está autorizado a configurar esta aplicación",
				oldBrowserTitle: "Explorador no compatible totalmente",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "El builder de Recorrido de mapa no es compatible con Internet Explorer 10 en Windows 7. Debes <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>forzar manualmente el modo del documento para Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>bajar a la versión Internet Explore 9</a> o actualizar a Windows 8.",
				oldBrowserExplain: "Este navegador no es compatible con la generación de miniaturas automática a partir de las imágenes que subas a tu recorrido de mapa. Puedes crear un recorrido de mapa con este navegador, pero tendrás que proporcionar una imagen en miniatura diferente para cada una de las imágenes que subas.",
				oldBrowserExplain2: "Para mejorar tu experiencia, <a href='http://browsehappy.com/' target='_blank'>actualiza tu explorador</a> o <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activa Google Chrome Frame para Internet Explorer</a>.",
				oldBrowserClose: "Cerrar"
			},
			mobileHTML: {
				showIntro: "MOSTRAR INTRO",
				hideIntro: "OCULTAR INTRO",
				navList: "Lista",
				navMap: "Mapa",
				navInfo: "Información"
			},
			desktopHTML: {
				storymapsText: "Un mapa de historias",
				builderButton: "Cambiar el modo de creador"
			},
			builderHTML: {
				panelHeader: "CONFIGURACIÓN DE LA APLICACIÓN",
				buttonSave: "GUARDAR",
				buttonDiscard: "CANCELAR",
				buttonSettings: "Configuración",
				buttonView: "Modo Vista",
				buttonOrganize: "Organizar",
				buttonAdd: "Agregar",
				modalCancel: "Cancelar",
				modalApply: "Aplicar",
				organizeHeader: "Organizar el recorrido",
				organizeGeneralCaption: "Utilizar arrastrar y colocar para ordenar los puntos del recorrido",
				organizeDelete: "Eliminar",
				organizeHide: "Ocultar",
				addMaxPointReached: "Has alcanzado el número máximo de puntos autorizado por los iconos establecidos y no puedes añadir otro punto de recorrido.<br /><br />Recuerda que si eliminas puntos existentes, tendrás que volver a cargar la aplicación.",
				addMaxPointReachedMobile: "Lo sentimos, pero has alcanzado el número máximo de puntos autorizados y no puedes agregar esa imagen.",
				addClose: "Cerrar",
				addHeader: "Añadir un punto de recorrido nuevo",
				addTabPicture: "Imagen",
				addTabInformation: "Información",
				addTabLocation: "Ubicación",
				addSelectCaption: "Selecciona o coloca la imagen",
				addSelectCaptionNoFileReader: "Selecciona imagen",
				addChangePhoto: "Cambia la imagen y la miniatura",
				addPictureResolutionIntro: "La resolución de imagen es superior a la necesaria:",
				addPictureResolutionOldBrowser: "La resolución de la imagen es superior a la necesaria. Para optimizar la experiencia con Recorrido de mapa, especifica una resolución inferior a %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Cambiar la resolución de la imagen a %RESOLUTION%",
				addPictureResolutionKeep: "Mantener la solución original de %RESOLUTION%",
				addSelectThumbnail: "Seleccionar miniatura",
				addNoThumbSelected: "No hay una miniatura seleccionada",
				addThumbSelected: "Seleccionado",
				addCameraSettingsHeader: "AJUSTES DE LA CÁMARA",
				addThumbnailHeader: "MINIATURA",
				addLabelName: "Nombre",
				addLabelDescription: "Leyenda",
				addTextPlaceholder: "Escribir algo",
				addLocatePlaceholder: "Localizar una dirección o un lugar",
				addPinColor: "Color",
				addLatitude: "Latitud",
				addLongitude: "Longitud",
				addLatitudePlaceholder: "por ejemplo, 34.056",
				addLongitudePlaceholder: "por ejemplo, -117.195",
				addUploading: "Cargando punto de recorrido",
				addSave: "Añadir punto de recorrido",
				addMobileUploading: "Cargando imagen",
				addMobileName: "Introduce un nombre",
				addMobileNameMandatory: "Error, introduce un nombre.",
				addMobileError: "Lo sentimos pero se ha producido un error",
				settingsHeader: "Ajustes de la aplicación",
				settingsTabLayout: "Diseño",
				settingsTabColor: "Colores",
				settingsTabLogo: "Encabezado",
				settingsTabFields: "Datos",
				settingsTabExtent: "Extensión",
				settingsTabZoom: "Nivel de zoom",
				settingsLayoutExplain: "Selecciona uno de los dos diseños de aplicación que se proporcionan.",
				settingsLayoutProfessional: "Diseño de tres paneles",
				settingsLayoutModern: "Diseño integrado",
				settingsLayoutSelected: "Diseño seleccionado",
				settingsLayoutSelect: "Selecciona este diseño",
				settingsColorExplain: "Cambia el aspecto eligiendo un tema predefinido, o crea uno propio.",
				settingsLabelColor: "Colores del encabezado, contenido y pie",
				settingsLogoExplain: "Personaliza el logotipo del encabezado (el valor máximo es 250 x 50px).",
				settingsLogoEsri: "Logotipo de Esri",
				settingsLogoNone: "Sin logotipo",
				settingsLogoCustom: "Logotipo personalizado",
				settingsLogoCustomPlaceholder: "URL de imagen",
				settingsLogoCustomTargetPlaceholder: "Enlace click-through",
				settingsLogoSocialExplain: "Personaliza el enlace superior derecho del encabezado.",
				settingsLogoSocialText: "Texto",
				settingsLogoSocialLink: "Vínculo",
				settingsDataFieldsExplain: "Selecciona los campos de nombre de foto, leyenda y color.",
				settingsDataFieldsError: "La aplicación no puede determinar los datos de nombre, leyenda o color adecuados. Selecciona los campos que se usarán aquí. Estos ajustes se pueden cambiar más adelante.",
				settingsFieldsLabelName: "Nombre",
				settingsFieldsLabelDescription: "Leyenda",
				settingsFieldsLabelColor: "Color",
				settingsExtentExplain: "Define la extensión inicial del Recorrido de mapa mediante el mapa interactivo siguiente.",
				settingsExtentExplainBottom: "Esa extensión solo se utiliza si incluye el punto de partida del recorrido. El valor se conserva en toda la extensión inicial del mapa Web.",
				settingsExtentDrawBtn: "Dibuja una nueva extensión",
				settingsExtentModifyBtn: "Edita la extensión actual",
				settingsExtentApplyBtn: "Aplica en el mapa principal",
				settingsZoomExplain: "Ajusta el zoom para los puntos de la historia después de la introducción (opcional).",
				settingsLabelZoom: "Escala/Nivel",
				settingsZoomFirstValue: "Ninguno",
				settingsFieldError : "Selecciona un campo en cada lista",
				dataHeader: "Datos de aplicación",
				dataExplain: "Tu mapa web no contiene un servicio de entidades. Completa este cuadro de diálogo para crear un servicio de entidades alojado en tu cuenta de organización de ArcGIS.com. El servicio de entidades se agregará a tu mapa Web y se compartirá públicamente pero solo si tienes permisos para agregar/editar y eliminar.<br /><br />Solo tú podrás ver la aplicación hasta que la compartas con los demás. <strong>Una vez listo tu Recorrido de mapa, comparte la aplicación a través de la página del elemento.</strong>",
				dataNameLbl: "Nombre del servicio",
				dataFolderListLbl: "Carpeta",
				dataFolderListFetching: "Recuperando carpetas ...",
				dataRootFolder: "Raíz",
				dataNameError: "Introduce un nombre para el servicio de entidades",
				dataFolderError: "Selecciona una carpeta válida",
				dataSrcContainsInvalidChar: "El nombre de servicio de la entidad contiene uno o varios caracteres no válidos (<, >, #, %, :, \", ?, &, +, /, o \).",
				dataSrvAlreadyExistsError: "En la organización ya existe un servicio con este nombre. Elija un nombre diferente.",
				dataBtnClose: "Cancelar el recorrido",
				dataBtnSave: "Crear el servicio",
				dataFooterProgress: "Creación en curso",
				dataFooterSucceed: "Creación satisfactoria. Cargando",
				dataFooterError: "Error de creación. Inténtalo de nuevo",
				tabError: "Comprueba todas las fichas por si existen errores",
				introRecordBtn: "Introducción",
				introRecordActivate: "Utiliza el punto de partida como introducción"
			},
			addPopupJS: {
				uploadingPicture: "Cargando imagen",
				uploadSuccess: "Carga satisfactoria",
				uploadError: "Error al cargar la imagen",
				notJpg: "Elige una foto jpeg para cargarla",
				errorNoPhoto: "Elige una imagen para cargarla",
				errorNoThumbnail: "Elige una miniatura para cargarla",
				errorNoName: "Escribe un nombre para este punto de recorrido",
				errorNoDescription: "Escribe una leyenda para este punto de recorrido",
				errorNoLocation: "Establece una ubicación para este punto de recorrido"
			},
			builderJS: {
				noPendingChange: "Sin cambios pendientes",
				unSavedChangeSingular: "1 cambio sin guardar",
				unSavedChangePlural: "cambios no guardados",
				popoverDiscard: "¿Estás seguro de que deseas descartar los cambios no guardados?",
				yes: "Sí",
				no: "No",
				popoverLoseSave: "Al abrir el visor, perderás los cambios no guardados",
				ok: "Aceptar",
				popoverSaveWhenDone: "No olvides guardar los cambios cuando hayas terminado",
				closeWithPendingChange: "¿Estás seguro de que deseas confirmar la acción? Tus cambios se perderán.",
				gotIt: "Aceptar",
				savingApplication: "Guardando la aplicación",
				saveSuccess: "La aplicación se ha guardado con éxito",
				saveError: "Error al guardar. Inténtalo de nuevo",
				dragColorPicker: "Desplázame<br />o cambia mi color",
				dataWarningExtent: "Tienes datos fuera de la extensión del mapa web. Estos datos no se usarán como puntos de recorrido. Si quieres usarlos, cambia la extensión del mapa.",
				dataWarningVisibi: "Tu capa de Recorrido de mapa no está visible en la extensión de mapa web actual. Confirma que tu capa de Recorrido de mapa esté visible con un mapa grande %MAPSIZE%.",
				dataWarningEdit: "Editar mapa web",
				dataWarningClose: "Cerrar",
				signIn: "Inicia sesión con una cuenta en",
				signInTwo: "para guardar la aplicación."
			},
			organizePopupJS: {
				messageStart: "Has elegido eliminar",
				messageSinglePoint: "un punto de recorrido",
				messageMultiPoint: "dos puntos",
				messagePermantRemove: "Esto eliminará permanentemente",
				messageRecord: "el registro",
				messageRecordPlural: "los registros",
				messageConfirm: "de la base de datos. ¿Deseas continuar?",
				labelButtonShow: "Mostrar",
				labelButtonHide: "Ocultar"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "Actualizando imagen y miniatura",
				popoverUploadingThumbnail: "Actualizando miniatura",
				popoverUploadSuccessful: "Carga satisfactoria",
				popoverUploadError: "Error de carga. Inténtalo de nuevo",
				changePicAndThumb: "Cambiar imagen",
				changeThumb: "Cambiar miniatura",
				selectPic: "Cambiar imagen",
				selectThumb: "Seleccionar miniatura",
				uploadPicAndThumb: "Aplicar"
			},
			headerJS:{
				editMe: "¡Modifícame!",
				templateTitle: "Establecer título de plantilla",
				templateSubtitle: "Establecer subtítulo de plantilla"
			},
			crossFaderJS:{
				setPicture: "Establecer título de imagen",
				setCaption: "Establecer leyenda de imagen"
			}
        }
    })
);
