define({
	root: ({
		viewer: {
			loading: {
				step1: "LOADING APPLICATION",
				step2: "LOADING DATA",
				step3: "INITIALIZING THE TOUR",
				loadBuilder: "SWITCHING TO BUILDER MODE",
				fail: "Sorry, Map Tour loading failed",
				failButton: "Retry"
			},
			errors: {
				boxTitle: "An error has occurred",
				invalidConfig: "Fatal error: Invalid configuration",
				invalidConfigOwner: "Fatal error: Invalid configuration (authorized owner required)",
				invalidConfigNoWebmap: "Fatal error: Invalid configuration (web map and authorized owner required)",
				createMap: "Unable to create map",
				invalidApp: "Fatal error: The application cannot be loaded",
				noLayer: "The web map does not contain a valid data layer for Map Tour.",
				noLayerMobile: "Welcome to the Map Tour web application. The application is not configured. The Map Tour builder is not supported on mobile devices.",
				noLayerView: "Welcome to the Map Tour web application.<br />The application is not configured yet.",
				appSave: "Error saving the web application",
				mapSave: "Error saving the web map",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "You are not authorized to access this application",
				oldBrowserTitle: "Browser not fully supported",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "The Map Tour interactive builder is not supported on Internet Explorer 10 on Windows 7 when the data source is a Feature Service with attachments. To use a Feature Service with attachments, you have to <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manually force document mode to Internet Explorer 9 standards</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>downgrade to Internet Explorer 9</a> or upgrade to Windows 8.",
				oldBrowserExplain: "This browser doesn't support automatic thumbnail generation from the images you upload into your map tour. You can create a map tour using this browser, but you will have to provide a separate thumbnail image for each of the images you upload.",
				oldBrowserExplain2: "To improve your experience, <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activate Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserExplain3: "The Map Tour builder doesn't work with Internet Explorer 10 on Windows XP.",
				oldBrowserClose: "Close"
			},
			mobileHTML: {
				showIntro: "SHOW TITLE",
				hideIntro: "HIDE TITLE",
				navList: "List",
				navMap: "Map",
				navInfo: "Pictures",
				introStartBtn: "Start"
			},
			desktopHTML: {
				storymapsText: "A story map",
				builderButton: "Switch to builder mode"
			},
			builderHTML: {
				panelHeader: "APPLICATION CONFIGURATION",
				buttonSave: "SAVE",
				buttonDiscard: "CANCEL",
				buttonSettings: "Settings",
				buttonView: "View mode",
				buttonHelp: "Help",
				buttonOrganize: "Organize",
				buttonAdd: "Add",
				buttonImport: "Import",
				buttonImportDisabled: "Import is not available when using a Feature Service with attachments",
				modalCancel: "Cancel",
				modalApply: "Apply",
				organizeHeader: "Organize the tour",
				organizeGeneralCaption: "Use drag and drop to sort tour points",
				organizeDelete: "Delete",
				organizeHide: "Hide",
				addMaxPointReached: "You have reached the maximum number of points authorized by the icons set and cannot add another tour point.<br /><br />Note that if you delete existing points, you will need to reload the application.",
				addMaxPointReachedMobile: "Sorry, you have reached the maximum number of authorized points and cannot add that picture.",
				addClose: "Close",
				addHeader: "Add a new tour point",
				addTabPicture: "Picture",
				addTabInformation: "Information",
				addTabLocation: "Location",
				addSelectCaption: "Select or drop picture",		
				addSelectCaptionNoFileReader: "Select picture",	
				addChangePhoto: "Change picture and thumbnail",
				addPictureResolutionIntro: "The picture resolution is higher than required:",
				addPictureResolutionOldBrowser: "The picture resolution is higher than required. Optimize the Map Tour experience by specifying a resolution lower than %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Change picture resolution to %RESOLUTION%",
				addPictureResolutionKeep: "Keep the original resolution of %RESOLUTION%",
				addSelectThumbnail: "Select thumbnail",
				addNoThumbSelected: "No thumbnail selected",
				addThumbSelected: "Selected",
				addCameraSettingsHeader: "CAMERA SETTINGS",
				addThumbnailHeader: "THUMBNAIL",
				addLabelPicUrl: "Picture URL",
				addLabelThumbUrl: "Thumbnail URL",
				addTextPlaceholderUrl: "Enter an URL",
				addLabelName: "Name",
				addLabelDescription: "Caption",
				addTextPlaceholder: "Type something",
				addLocatePlaceholder: "Locate an address or a place",
				addPinColor: "Color",
				addLatitude: "Latitude",
				addLongitude: "Longitude",
				addLatitudePlaceholder: "e.g. 34.056",
				addLongitudePlaceholder: "e.g. -117.195",
				addUploading: "Uploading tour point",
				addSave: "Add tour point",
				addMobileUploading: "Uploading picture",
				addMobileName: "Enter a name",
				addMobileNameMandatory: "Error, please enter a name.",
				addMobileError: "Sorry, something has gone wrong",
				settingsHeader: "Application settings",
				settingsTabLayout: "Layout",
				settingsTabColor: "Colors",
				settingsTabLogo: "Header",
				settingsTabFields: "Data",
				settingsTabExtent: "Extent",
				settingsTabZoom: "Zoom Level",
				settingsLayoutExplain: "Select the application layout you want.",
				settingsLayoutProfessional: "Three-panel Layout",
				settingsLayoutModern: "Integrated Layout",
				settingsLayoutSelected: "Selected layout",
				settingsLayoutSelect: "Select this layout",
				settingsColorExplain: "Change appearance by choosing a pre-defined theme, or create your own.",
				settingsLabelColor: "Header, content and footer colors",
				settingsLogoExplain: "Customize the header logo (maximum is 250 x 50px).",
				settingsLogoEsri: "Esri logo",
				settingsLogoNone: "No logo",
				settingsLogoCustom: "Custom logo",
				settingsLogoCustomPlaceholder: "Image URL",
				settingsLogoCustomTargetPlaceholder: "Click-through link",
				settingsLogoSocialExplain: "Customize the header top right link.",
				settingsLogoSocialText: "Text",
				settingsLogoSocialLink: "Link",
				settingsDataFieldsExplain: "Select photo name, caption and color fields.",
				settingsDataFieldsError: "The application cannot determine the appropriate name, caption or color data. Please select the fields to be used here. These settings can be changed at a later time.",
				settingsFieldsLabelName: "Name",
				settingsFieldsLabelDescription: "Caption",
				settingsFieldsLabelColor: "Color",
				settingsExtentExplain: "Set the Map Tour initial extent through the interactive map below.",
				settingsExtentExplainBottom: "That extent is used only if it includes the first tour point. The value is persisted through the web map initial extent.",
				settingsExtentDrawBtn: "Draw a new extent",
				settingsExtentModifyBtn: "Edit the current extent",
				settingsExtentApplyBtn: "Apply on main map",
				settingsZoomExplain: "Set zoom for story points following introduction (optional).",
				settingsLabelZoom: "Scale/level",
				settingsZoomFirstValue: "None",
				settingsFieldError: "Please select a field in each list",
				dataExplain: "The feature service will be added to your web map. It won't be shared with anyone, and only you will have add, edit, and delete privileges.<br /><br />If you change the application sharing privileges, the system will ask you if you want to update your Feature Service sharing configuration. This is required for your users to access your data. You will remain the only one with editing privileges.",
				dataNameLbl: "Service name",
				dataFolderListLbl: "Folder",
				dataFolderListFetching: "Fetching folders ...",
				dataRootFolder: "Root",
				dataNameError: "Enter a name for the feature service",
				dataFolderError: "Select a valid folder",
				dataSrcContainsInvalidChar: "The feature service name contains one or more invalid characters (-, <, >, #, %, :, \", ?, &, +, /, or \).",
				dataSrvAlreadyExistsError: "A service with that name already exists within the organization. Please choose a different name.",
				dataBtnSave: "Create the service",
				dataFooterProgress: "Creation in progress",
				dataFooterSucceed: "Creation succeeded. Loading",
				dataFooterError: "Creation failed. Please try again",
				tabError: "Please check for errors in all tabs",
				introRecordBtn: "Intro",
				introRecordActivate: "Use the first point as introduction (does not appear in carousel)"
			},
			addPopupJS: {
				uploadingPicture: "Uploading picture",
				uploadSuccess: "Upload successful",
				uploadError: "Error uploading the picture",
				notJpg: "Please choose a jpeg photo to upload",
				errorNoPhoto: "Choose an image to upload",
				errorNoThumbnail: "Choose a thumbnail to upload",
				errorInvalidPicUrl: "Enter a valid picture URL for this tour point",
				errorInvalidThumbUrl: "Enter a valid thumbnail URL for this tour point",
				errorNoName: "Enter a name for this tour point",
				errorNoDescription: "Enter a caption for this tour point",
				errorNoLocation: "Set a location for this tour point"
			},
			builderJS: {
				noPendingChange: "No pending change",
				unSavedChangeSingular: "1 unsaved change",
				unSavedChangePlural: "unsaved changes",
				popoverDiscard: "Are you sure to want to discard any unsaved changes?",
				yes: "Yes",
				no: "No",
				popoverLoseSave: "By opening the viewer, you will lose any unsaved changes",
				ok: "Ok",
				popoverSaveWhenDone: "Don't forget to save when you are done",
				closeWithPendingChange: "Are you sure to want to confirm the action ? Your changes will be lost.",
				gotIt: "Ok",
				savingApplication: "Saving application",
				saveSuccess: "Application saved successfully",
				saveError: "Save failed, please try again",
				dragColorPicker: "Move me around<br />or change my color",
				dataWarningExtent: "You have data outside of the web map extent. Those data won't be used as tour points, change map extent if you want to use them.",
				dataWarningVisibi: "Your Map Tour layer is not visible at the current web map extent. Confirm your Map Tour layer is visible with a %MAPSIZE% large map.",
				dataWarningEdit: "Edit web map",
				dataWarningClose: "Close",
				signIn: "Please sign in with an account on",
				signInTwo: "to save the application."
			},
			organizePopupJS: {
				messageStart: "You have chosen to delete",
				messageSinglePoint: "one tour point",
				messageMultiPoint: "tour points",
				messagePermantRemove: "This will permanently remove the",
				messageRecord: "record",
				messageRecordPlural: "records",
				messageConfirm: "from your database. Do you want to continue?",
				labelButtonShow: "Show",
				labelButtonHide: "Hide"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "Uploading picture and thumbnail",
				popoverUploadingThumbnail: "Uploading thumbnail",
				popoverUploadSuccessful: "Upload successful",
				popoverUploadError: "Upload failed, please try again",
				changePicAndThumb: "Change picture",
				changeThumb: "Change thumbnail",
				selectPic: "Change picture",
				selectThumb: "Change thumbnail",
				uploadPicAndThumb: "Apply"
			},
			headerJS:{
				editMe: "Edit me !",
				templateTitle: "Set template title",
				templateSubtitle: "Set template subtitle"
			},
			crossFaderJS:{
				setPicture: "Set picture title",
				setCaption: "Set picture caption"
			},
			importPopup: {
				title: "Import",
				prevBtn: "Back",
				nextBtn: "Next"
			},
			importPopupHome: {
				header: "Where are your pictures stored ?",
				loadCSV: "They are referenced in a CSV (any pictures sharing service or web server, see help for details)",
				loadFolder: "A folder on my computer (require a modern browser and a Feature Service with attachments data source)"
			},
			onlinePhotoSharingCommon: {
				header1: "The pictures need to be publicly shared.",
				header2: "The import will be limited to %NB1% pictures to respect the limit of %NB2% points per tour.",
				emptyDataset: "Error, no pictures found",
				footerImport: "Import",
				selectAlbum: "Select a public album",
				selectAlbum2: "Select an album",
				pleaseChoose: "Please Choose",
				userLookup: "Look up",
				userLookingup: "Looking up",
				csv: "Referenced in a CSV",
				fromScratch: "Start from scratch",
				select: "Make a selection",
				locUse: "Use pictures location",
				locWhy: "why that option?",
				locExplain: "You may not want to use pictures location as they can be inherited from the album, resulting in all photos being at the same location."
			},
			viewFlickr: {
				header: "Enter a Flickr user name and select a Photo Set or a Tag to be imported.",
				userInputLbl: "Enter a User Name",
				signInMsg2: "User not found",
				selectSet: "Select a Photo Set",
				selectTag: "or Select a Tag",
				footerImportTag: "Import the selected Tag",
				footerImportSet: "Import the selected Set"
			},
			viewFacebook: {
				header: "Authenticate with a Facebook User Account or use a Public Page. Private albums can be used to create a public Map Tour that does not require Facebook user authentication, which allows comments and likes to remain private.",
				leftHeader: "Facebook User",
				rightHeader: "Facebook Page",
				pageExplain: "A Facebook page is a public brand/product or celebrity like <b>esrigis</b>. You can get the page name after the first '/' in the page URL.",
				pageInputLbl: "Enter a page name",
				lookupMsgError: "Page not found"
			},
			viewPicasa: {
				header: "Enter the email or the ID of a Picasa or Google+ account.",
				userInputLbl: "Enter an email or ID",
				signInMsg2: "Account not found",
				howToFind: "How to find an account ID",
				howToFind2: "Copy digits between the first and second '/' of any Picasa or G+ page"
			},
			viewCSV: {
				uploadBtn: "Select or drop a CSV file",
				resultHeaderEmpty: "The CSV is empty",
				resultHeaderSuccess: "Successfully loaded %NB_POINTS% points",
				resultHasBeenLimited: "The import has been limited to the first %VAL1% points out of %VAL2% to respect the limit of %VAL3% points per tour",
				browserSupport: "Your browser isn't supported, to use a CSV you have to <a href='http://browsehappy.com/' target='_blank'>upgrade your browser</a> or use ArcGIS.com web map viewer (see Help).",
				errorLatLng: "Latitude and Longitude fields haven't been found. Possible values for latitude are: <i>%LAT%</i> and for longitude: <i>%LONG%</i>.",
				errorFieldsExplain: "The loading failed as the following required fields hasn't been found",
				errorFieldsName: "<b>Name</b> possible values are: %VAL%",
				errorFieldsDesc: "<b>Description</b> possible values are: %VAL%",
				errorFieldsUrl: "<b>Picture URL</b> possible values are: %VAL%",
				errorFieldsThumb: "<b>Thumbnail URL</b> possible values are: %VAL%",
				errorFields2Explain: "The loading failed as the CSV does not use the same attributes than the layer for the following attributes",
				errorFields2Name: "<b>Name</b> use %VAL1% instead of %VAL2%",
				errorFields2Desc: "<b>Description</b> use %VAL1% instead of %VAL2%",
				errorFields2Url: "<b>Picture URL</b> use %VAL1% instead of %VAL2%",
				errorFields2Thumb: "<b>Thumbnail URL</b> use %VAL1% instead of %VAL2%",
				resultFieldsAll: "All attributes have been imported",
				resultFieldsNotAll: "The following attributes haven't been imported because they don't exists in the map layer",
				resultFieldsNotAll2: "The following attributes have been imported",
				footerNextBtnResult: "Import into the web map",
				footerProgress: "Import in progress",
				footerSucceed: "Import succeeded. Loading"
			},
			viewGeoTag: {
				header: "Click or tap the pictures you want to import to locate them.",
				headerMore: "Why my pictures are not located?",
				headerExplain: "If your pictures have a valid location, they will be automatically located on the map and listed on the second tab.<br /><br />By default Picasa and Flickr don't exploit the pictures EXIF location metadata, check Flickr/Picasa settings under Privacy tab to enable pictures location usage. You may have to completly reimport your pictures into Flickr/Picasa.<br /><br />For Facebook, you have to go on each picture, click Edit and select the location between the suggested choices that are based on the pictures EXIF metadata.",
				leftPanelTab1: "To locate",
				leftPanelTab2: "Located",
				clickOrTap: "Click or tap the Map to locate",
				clickDrop: "Do not import",
				footerImport: "Import",
				footerProgress: "Import in progress",
				footerSucceed: "Import succeeded. Loading..."
			},
			initPopup: {
				title: "Welcome to the Map Tour Builder",
				prevBtn: "Back",
				nextBtn: "Next"
			},
			initPopupHome: {
				header2: "This assistant will help you build a Map Tour from pictures already stored online or it will import them into your ArcGIS Online for Organization account.",
				title1: "My pictures are already hosted",
				title2: "I need to host my pictures",
				hostedFsNA: "Only available for ArcGIS for Organization Publisher and Administrator users",
				footer1: "When you are done, don't forget to share your Map Tour with your audience through the application item page.",
				footer2: "Map Tour Help",
				footer3: "Download the CSV template",
				footerProgress: "Creation in progress",
				footerSucceed: "Creation succeeded. Loading..."
			},
			helpPopup: {
				title: "Help",
				close: "Close",
				tab1: {
					title: "Introduction",
					div1: "The Map Tour template is designed for presenting geographic information where there is a compelling photographic element to the story you want to tell.",
					div2: "The template produces an attractive, easy-to-use web application that lets you present a small set of places on a map in a numbered sequence through which users can browse. The template is designed to be used in any web browser on any device, including smartphones and tablets.",
					div3: "This help will guide you through the steps for publishing Map Tours like:",
					div4: "<ul><li><a href='http://storymaps.esri.com/stories/demo/map_tour/?webmap=7190edafe7464cb19c1caf1360cd6ee5' target='_blank'>Palm Springs Map Tour</a></li><li><a href='http://story.maps.arcgis.com/apps/MapTour/index.html?appid=4d6054b109ce482d88588d5c06a7a478' target='_blank'>Nederland country's best mountain biking</a></li><li><a href='http://ugis.esri.com/LA_River_Tour/' target='_blank'>Los Angeles River Map Tour</a></li></ul>",
					div5: "We would love to hear from you! Do not hesitate to share your Map Tour with us:",
					div6: "<ul><li><a href='mailto:storymaps@esri.com' target='_blank'>storymaps@esri.com</a></li><li><a href='http://storymaps.esri.com/home/' target='_blank'>StoryMaps Website</a></li><li><a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a></li></ul>",
					div7: "Find a bug or want to request a new feature? Please let us know by submitting an issue on the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a>."
				},
				tab2: {
					title: "Data",
					div1: "The main element to consider when building a Map Tour is to choose where your pictures will be stored. A Map Tour can use pictures stored on major photo sharing services, on any web server or in Feature Services.",
					div2: "The interactive builder gives you two options for handling the images in your Map Tour:",
					div3: "<ul><li>You can use <b>photos that are already online</b>, such as images stored in a photo sharing site like Flickr or images stored on your own website. These images will be referenced in your Map Tour via their URLs</li><li>You can also <b>upload image photos from your computer</b> directly into your Map Tour. This upload option requires that you have an ArcGIS for Organizations subscription account and you have Publisher or Administrator privileges (because it automatically creates a hosted feature service for you in which your photos are stored as attachments)</li></ul>",
					div4: "The main use cases are:",
					div4b: "<b>Your photos are not hosted</b> yet and you have an Organization account: using a hosted Feature Service is your best choice. Like public photo sharing services, we will optimize your pictures to create fast loading images and you will have access to all administration and data management capabilities of the ArcGIS platform",
					div5: "<b>You aren't a member of an Organization</b>: you first have to upload your pictures to a photo sharing website or to your own webserver. Then the wizard will help you use these pictures that will continue to be hosted at their original location",
					div6: "<b>You are looking to reuse an existing Feature Service</b> that store your pictures as attachments or that reference external pictures: see the detailed section below",
					div7: "<b>You are a user of a previous version</b> of the Map Tour template and already have your CSV that reference your pictures and thumbnail: you will be able to import it and refine your data. The wizard only supports CSV that use lat/long fields, address based CSV can continue to be used through your web map (see section below)",
					div8: "Importing from online photo sharing services",
					div9: "The import operation references pictures that are already hosted by storing their URLs in a web map feature collection. The pictures are not stored in ArcGIS Online. If hosted pictures can't be accessed, they won't be available in the Map Tour and you''ll see a 'Picture not available' image. Depending on your photo service provider, the Map Tour may not import the name, description and location of the pictures. Those attributes are stored in the web map and any edits to the online services won't be reflected in the Map Tour.",
					div10: "Storing the pictures on a web server",
					div11: "If you choose to host the pictures yourself, you will have to manually create thumbnails of your pictures. Using the full resolution pictures for the thumbnail will result in poor performance. For that reason we strongly recommend that you use an online photo sharing services or a Feature Service that will do that for you.",
					div12: "Using an existing Feature Service or Shapefile",
					div13: "Any point Feature Service or Shapefile can be used as a Map Tour data source. You just have to add it as a layer into your web map through ArcGIS.com Map Viewer. If the application finds the expected attributes in your layer, all builder functionalities will be available.",
					div14: "The expected fields are (case insensitive):",
					div151: "Name",
					div152: "Description",
					div153: "Picture",
					div154: "Thumbnail",
					div155: "Color (optional)",
					div16: "Name and description fields are mandatory. If the application doesn't find matching fields when using a Feature Service, the viewer will not work until you configure the fields to be used through the builder. CSV and Shapefile layers added to the web map need to have all the required fields or the builder won't work.",
					div17: "The picture and Thumbnail fields are mandatory for Feature Service without attachments and optional but strongly recommended for Feature service with attachments. If your service have attachments enabled, the builder will let you upload pictures as attachments. If not you will only be able to edit the picture and thumbnail URL.",
					div18: "Creating a hosted Feature Services from CSV or Shapefile",
					div19: "When you create a hosted Feature Service from a CSV or Shapefile, the attachments are not enabled by default. To enable them, open the Feature Service item page, click the small arrow on the layer section and you will see that option. After that the Map Tour will continue to use the pictures and thumbnail you have referenced through attributes. Optionally if you want to upload your pictures as Feature Service attachments you will be able to do so through two buttons on the picture panel (change picture and change thumbnail).",
				},
				tab3: {
					title: "Customization",
					div1: "The builder provides several customization options that are accessible through the SETTINGS button in the top panel. If you don't find the option you expect, we also provide a downloadable version that you can deploy on your web server and enhance to fit your needs.",
					div2: "We recommend that you use the hosted version except if:",
					div3: "<li>It doesn't offer an UI customization you want to have, like using a header background image</li><li>You are a developer and you want to enhance the application</li>",
					div4: "The downloadable version doesn't offer the interactive builder. The Map Tour gets its data from a web map and its configuration from parameters in a file that offer the same capabilities as the hosted version. We recommend that you create and refine your web map using the hosted version and that you reuse it with the downloadable.",
					div5: "Visit the <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub project page</a> to learn more about the downloadable version."
				},
				tab4: {
					title: "Tips",
					div1: "Pictures",
					div2: "We recommend landscape orientation photos instead of portrait. Portrait orientation images can be used but on smaller screens like the iPad, a lot of the photo may be obscured by the caption, because text takes up more space when it is displayed in a tall area compared to a wide area. Although images of different sizes, shapes and orientation can be used in one Map Tour, we recommend using the exact same size and shape for all the images. In this way, the user won't be distracted by different sized images as they follow the tour.",
					div3: "Formatting your caption text using HTML tags",
					div4: "The caption text can include HTML tags to define formatting and links, see <a href='http://blogs.esri.com/esri/arcgis/2013/03/29/add-links-map-tour/' target='_blank'>this blog post</a>.",
					div5: "Supporting Layers",
					div6: "You can add additional supporting layers into the map. These layers will appear in your Map Tour to provide orientation, background, and any other geographic features you want the map to show in addition to the Map Tour points, such as a study area, a walking or driving route linking your tour points, etc. The template displays these additional supporting layers using the symbology you specify in the web map, the popup aren't available.",
					div7: "Keep your tour short and sweet",
					div8: "There's a limit of 99 points per tour. Most Map Tours will of course be significantly shorter than that. Don't expect your audience to want to step through too many tour points. You might find your subject fascinating, but don't assume they will too!",
					div9: "To learn more, see <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>the detailed guide</a>."
				},
				tab5: {
					title: "Publishing",
					div1: "When you are done, don't forget to share your Map Tour with your audience through the application item page in ArcGIS Online. During that process, ArcGIS Online will if necessary ask you to update any depending resources (web map, Feature Service) that doesn't have the same sharing privileges. If one of your resources isn't shared with your audience, users will be redirected to the ArcGIS Online login page.",
					div2: "If you are using an hosted Feature Service created through the Map Tour builder, the application manages the service security for you and you will remain the only one with editing privileges even if you share the service publicly.",
					div3: "Before sharing a Map Tour publicly, make sure it work when you are not logged in your ArcGIS.com account.",
					div4: "It is a good idea to see what your map tour looks like on an iPad held in landscape (lengthways) orientation. This can help you see if your captions cover up too much of the pictures."
				}
			}
        }
    }),
	"ar":1,
	"da":1,
	"de":1,
	"es":1,
	"fr":1,
	"he":1,
	"it":1,
	"ja":1,
	"ko":1,
	"lt":1,
	"nl":1,
	"nb":1,
	"pl":1,
	"pt-br":1,
	"pt-pt":1,
	"ro":1,
	"ru":1,
	"sv":1,
	"zh-cn":1
});
