define({
  "viewer": {
    "loading": {
      "step1": "INDLÆSER HISTORIE",
      "step2": "INDLÆSER DATA",
      "step3": "STARTER TUREN",
      "loadBuilder": "SKIFTER TIL BUILDER-TILSTAND",
      "redirectSignIn": "OMDIRIGERER TIL LOG IND-SIDE",
      "redirectSignIn2": "(du omdirigeres hertil efter login)",
      "fail": "Beklager, indlæsning af Map Tour mislykkedes",
      "failButton": "Prøv igen"
    },
    "errors": {
      "boxTitle": "Der opstod en fejl",
      "portalSelf": "Uoprettelig fejl: Kunne ikke hente portalkonfiguration",
      "invalidConfig": "Uoprettelig fejl: Ugyldig konfiguration",
      "invalidConfigOwner": "Uoprettelig fejl: Ugyldig konfiguration (autoriseret ejer kræves)",
      "invalidConfigNoWebmap": "Uoprettelig fejl: Ugyldig konfiguration (webkort- eller applikationsidentifikator er ikke angivet i index.html)",
      "invalidConfigNoAppDev": "Ingen webkortapplikation-identifikator eller webkort er angivet i URL-parametrene (?appid= eller ?webmap=). I udviklertilstand tilsidesættes appid- og webkort-konfigurationen i index.html.",
      "createMap": "Kan ikke oprette kort",
      "invalidApp": "Uoprettelig fejl: Historien kan ikke indlæses",
      "noLayer": "Webkort indeholder ikke et gyldigt datalag for kortturen.",
      "noLayerMobile": "Map Tour-builder-programmet understøttes ikke ved denne skærmstørrelse. Hvis det er muligt, skal du ændre størrelse på din browser for at få adgang til builder-programmet, eller du kan udvikle din historie på en enhed med en større skærm.",
      "noLayerMobile2": "Rotér din enhed til liggende retning for at bruge Map Tour-builder-programmet.",
      "noLayerView": "Velkommen til Map Tour-webapplikationen.<br />Historien er endnu ikke blevet konfigureret.",
      "appSave": "Fejl under lagring af historie",
      "mapSave": "Fejl ved lagring af webkortet",
      "featureServiceLoad": "Fejl under indlæsning af featuretjeneste",
      "notAuthorized": "Du er ikke autoriseret til at få adgang til denne historie",
      "notAuthorizedBuilder": "Du har ikke autorisation til at bruge Map Tour-builder-programmet.",
      "oldBrowserTitle": "Browser understøttes ikke fuldt ud",
      "noBuilderIE8": "Map Tour-builderprogrammet understøttes ikke for Internet Explorer før version 9.",
      "ie10Win7Explain": "Map Tour-builderprogammet understøttes ikke i Internet Explorer 10 på Windows 7, når datakilden er en featuretjeneste med vedhæftninger. Hvs du vil bruge en featuretjenste med vedhæftninger, skal du <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuelt tvinge dokumenenttilstanden til at følge Internet Explorer 9-standarden</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>nedgradere til Internet Explorer 9</a> eller opgradere til Windows 8.",
      "oldBrowserExplain": "Denne browser understøtter ikke automatisk miniaturegenerering af de billeder, du overfører til din korttur. Du kan oprette en korttur med denne browser, men du skal oprette et separat miniaturebillede for hvert af de billeder, du overfører.",
      "oldBrowserExplain2": "For at forbedre din oplevelse skal du <a href='http://browsehappy.com/' target='_blank'>opgradere din browser</a> eller <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivere Google Chrome Frame for Internet Explorer</a>.",
      "oldBrowserExplain3": "Map Tour-builder fungerer ikke med Internet Explorer 10 på Windows XP.",
      "oldBrowserClose": "Luk",
      "noViewerIE2": "Du forsøger at få vist denne historie ved hjælp af en ældre, ikke-understøttet browser. Der kan være funktioner, der ikke fungerer, eller andre uventede problemer. Vi foreslår, at du opgraderer til Internet Explorer 11 eller benytter en anden browser, f.eks. Chrome.",
      "noViewerIE3": "I slutningen af 2017 vil denne historie ikke længere kunne vises i denne browser. På det tidspunkt skal du benytte en understøttet browser til at vise denne historie.",
      "attention": "Bemærk!"
    },
    "mobileHTML": {
      "showIntro": "VIS TITEL",
      "hideIntro": "SKJUL TITEL",
      "navList": "Liste",
      "navMap": "Kort",
      "navInfo": "Medier",
      "introStartBtn": "Start"
    },
    "desktopHTML": {
      "storymapsText": "Et historiekort",
      "builderButton": "Skift til builder-tilstand",
      "facebookTooltip": "Del på Facebook",
      "twitterTooltip": "Del på Twitter",
      "bitlyTooltip": "Hent et kort link",
      "bitlyStartIndex": "Link til aktuelt sted",
      "tooltipAutoplayDisabled": "Dette er ikke tilgængeligt i autoplay-tilstand.",
      "autoplayLabel": "Autoplay-tilstand",
      "autoplayExplain1": "Autoplay-tilstand vil gå frem igennem din historie med et regelmæssigt interval. Dette er ideelt på en kiosk-skærm eller offentlig tilgængelig skærm, men du skal være opmærksom på, at dette kan gøre din historie vanskeligere at læse i andre situationer. Denne funktion understøttes ikke på små skærme.",
      "autoplayExplain2": "Når denne tilstand er aktiv, er der knapper til at afspille din historie eller sætte den på pause og til at justere navigationshastigheden.",
      "takeTourText": "Tag en rundtur",
      "backToStart": "Tilbage til Start"
    },
    "builderHTML": {
      "panelHeader": "HISTORIEKONFIGURATION",
      "buttonSave": "GEM",
      "buttonSettings": "Indstillinger",
      "buttonShare": "Del",
      "buttonView": "Visningstilstand",
      "buttonItem": "Åbn webapplikationselement",
      "buttonHelp": "Hjælp",
      "buttonOrganize": "Organisér",
      "buttonOrganizeAndCover": "Arrangér tour-punkter og tilføj en forside",
      "buttonAdd": "Tilføj",
      "buttonImport": "Importér",
      "buttonImportDisabled": "Import er ikke tilgængelig, når du bruger overførsel af billeder. Klik på Tilføj for at overføre et billede.",
      "dataEditionDisabled": "Dataredigering er deaktiveret på denne CSV-datakilde",
      "dataSourceWarning": "Map Tour-datalaget er ændret. Hvis objekt-ID'er ikke er ens, skal du nulstille rækkefølgen og skjulte punkter ved hjælp af <b>Organisér</b>. Hvis feltnavnene er forskellige, skal du nulstille feltindstillingerne på <b>datafanen i Indstillinger</b>.",
      "organizeWarning": "Et eller flere punkter, der er tilføjet uden for det interaktive builder-program, er skjulte.",
      "dataPicError0a": "Denne tour omfatter <b>%NB%</b> ikke-kompatible billed-URL'er.",
      "dataPicError0b": "Denne tour omfatter <b>%NB%</b> ikke-kompatible billed-URL'er.",
      "dataPicError1": "Map Tour kræver nu, at billed-URL'er slutter med ét af følgende filtypenavne: .jp(e)g, .png, .gif eller .bmp.",
      "dataPicError2": "Dette krav vil ikke få nogen indflydelse på din eksisterende publicerede Map Tour. Men for at kunne bruge det interaktive builder-program skal du først løse URL-problemet ved at udføre én af følgende to handlinger:",
      "dataPicError3": "Redigér URL'er",
      "dataPicError4": "Det tilføjer <i>#isImage</i> til slutningen af ​​ikke-understøttede billed-URL’er. De fleste servere understøtter URL-tilknytninger. Når du har udført denne handling, skal du kontrollere, at de opdaterede billed-URL'er fungerer ved at navigere gennem dine punkter. Hvis alle billeder indlæses, kan du gemme din Map Tour.  Hvis <b>billederne er ødelagte, skal du ikke gemme din Map Tour</b>. Genindlæs i stedet builder-programmet, og udfør den anden handling.",
      "dataPicError5": "Begræns turen til billeder",
      "dataPicError6": "Denne indstilling medfører, at alle URL’er bliver betragtet som billeder, men du vil ikke kunne tilføje videoer med det interaktive builder-program. Denne handling kan fortrydes, hvis du på et tidspunkt i fremtiden beslutter at tilføje videoer.",
      "dataPicError7": "Din Map Tour er begrænset til billeder, der kan ikke benyttes videoer. Hvis du vælger at fjerne denne begrænsning, skal du kontrollere, at dine billeder fortsat indlæses korrekt, før du gemmer din Map Tour. Du kan gendanne denne begrænsning på et senere tidspunkt, hvis det bliver nødvendigt.",
      "dataPicError8": "Fjern billedbegrænsningen",
      "dataPicError9": "Hvis disse URL’er peger på videoer, kan du se bort fra denne advarsel. Hvis de peger på billeder, skal du udføre én af følgende to handlinger:",
      "modalCancel": "Annullér",
      "modalApply": "Anvend",
      "organizeHeader": "Organisér turen",
      "organizeGeneralCaption": "Brug træk og slip til at sortere turpunkter",
      "organizeDelete": "Slet",
      "organizeHide": "Skjul",
      "organizeReset": "Nulstil rækkefølge og skjulte punkter",
      "addMaxPointReached": "Du har nået det maksimale antal punkter, der er autoriseret af de indstillede ikoner, og du kan ikke tilføje endnu et tour-punkt.<br /><br />Bemærk, at hvis du sletter eksisterende punkter, skal du genindlæse historien.",
      "addMaxPointReachedMobile": "Beklager, du har nået det maksimale antal autoriserede points og kan ikke tilføje dette billede.",
      "addClose": "Luk",
      "addHeader": "Tilføj et nyt turpunkt",
      "addTabPicture": "Medier",
      "addTabInformation": "Oplysninger",
      "addTabLocation": "Sted",
      "addSelectCaption": "Vælg eller slip billede",
      "addNoteVideo": "Se Hjælp for at få vejledning i brugen af videoer",
      "addSelectCaptionNoFileReader": "Vælg billede",
      "addChangePhoto": "Redigér billede og miniature",
      "addPictureResolutionIntro": "Billedopløsningen er højere end krævet:",
      "addPictureResolutionOldBrowser": "Billedopløsningen er højere end krævet. Optimér Map Tour-oplevelsen ved at indstille en opløsning, der er lavere end %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Skift billedopløsning til %RESOLUTION%",
      "addPictureResolutionKeep": "Behold den oprindelige opløsning på %RESOLUTION%",
      "addSelectThumbnail": "Vælg miniaturebillede",
      "addNoThumbSelected": "Intet miniaturebillede valgt",
      "addThumbSelected": "Valgt",
      "addCameraSettingsHeader": "KAMERAINDSTILLLINGER",
      "addThumbnailHeader": "MINIATUREBILLEDE",
      "addLabelPicUrl": "Billede",
      "addLabelThumbUrl": "Miniature",
      "addTextPlaceholderUrl": "Indtast en billed-URL",
      "addTextPlaceholderUrl2": "Indtast en Youtube-side-URL",
      "addTextPlaceholderUrl3": "Indtast en Vimeo-side-URL",
      "addTextPlaceholderUrl4": "Indtast en URL, der er indlejret i en video",
      "addLabelVideo": "Video",
      "addMediaVideoOther": "Andet",
      "addMediaVideoHelp": "Kontrollér URL'en, og hent standardminiaturen",
      "addMediaVideoHelpTooltip1": "Kontrol lykkedes",
      "addMediaVideoHelpTooltip2": "Kontrol mislykkedes",
      "addMediaVideoHelpTooltip4": "Find indstillingen til indlejring af videoen, og kopiér video-URL'en, der findes i koden",
      "addLabelName": "Navn",
      "addLabelDescription": "Billedtekst",
      "addTextPlaceholder": "Skriv noget",
      "addLocatePlaceholder": "Find en adresse eller et sted",
      "addPinColor": "Farve",
      "addLatitude": "Breddegrad",
      "addLongitude": "Længdegrad",
      "addLatitudePlaceholder": "f.eks. 34,056",
      "addLongitudePlaceholder": "f.eks. -117,195",
      "addUploading": "Overfører turpunkt",
      "addSave": "Tilføj turpunkt",
      "addMobileUploading": "Overfører billede",
      "addMobileName": "Angiv et navn",
      "addMobileNameMandatory": "Fejl, angiv et navn.",
      "addMobileError": "Beklager, noget er gået galt",
      "settingsHeader": "Indstillinger",
      "settingsTabLayout": "Layout",
      "settingsTabColor": "Farver",
      "settingsTabLogo": "Logo",
      "settingsTabFields": "Data",
      "settingsTabExtent": "Område",
      "settingsTabZoom": "Zoomniveau",
      "settingsLayoutExplain": "Vælg det ønskede layout.",
      "settingsLayoutProfessional": "Tre-panel",
      "settingsLayoutModern": "Integreret",
      "settingsLayoutSidePanel": "Sidepanel",
      "settingsLayoutSelected": "Vælg layout",
      "settingsLayoutNew": "Nyt!",
      "settingsLayoutSelect": "Vælg",
      "settingsLayoutNote": "Bemærk, at ved punkter, der benytter videoer, vil teksten altid være placeret under videoen, selvom denne indstilling ikke er markeret.",
      "settingsLayoutLocBtn": "Få vist en søgeknap",
      "settingsLayoutLocBtnHelp": "Understøttes af de fleste browsere. Vises kun, når historiekortet åbnes via HTTPS. Vises ikke, hvis historien er indlejret.",
      "settingsColorExplain": "Skift udseende ved at vælge et foruddefineret tema eller ved at oprette dit eget.",
      "settingsLabelColor": "Farver på toptekster, indhold og bundtekster",
      "settingsLogoExplain": "Tilpas toptekstlogoet  (maks. 250 x 50 pixel).",
      "settingsLogoEsri": "Esri-logo",
      "settingsLogoNone": "Intet logo",
      "settingsLogoCustom": "Brugerdefineret logo",
      "settingsLogoCustomPlaceholder": "Billede-URL",
      "settingsLogoCustomTargetPlaceholder": "Klik gennem-link",
      "settingsLogoSocialExplain": "Tilpas header-linket øverst til højre.",
      "settingsLogoSocialText": "Tekst",
      "settingsLogoSocialLink": "Link",
      "settingsLogoSocialDisabled": "Dette objekt er blevet deaktiveret af administratoren",
      "settingsDataFieldsExplain": "Vælg fotonavn, billedtekst og farvefelter.",
      "settingsDataFieldsError": "Applikationen kan ikke fastsætte et passende navn, billedtekst eller farvedata. Vælg de felter, der skal bruges her. Disse indstillinger kan ændres på et senere tidspunkt.",
      "settingsFieldsLabelName": "Navn",
      "settingsFieldsLabelDescription": "Billedtekst",
      "settingsFieldsLabelColor": "Farve",
      "settingsFieldsReset": "Nulstil feltvalget",
      "settingsExtentExplain": "Indstil Map Tour-hjemudstrækningen på det interaktive kort nedenfor.",
      "settingsExtentExplainBottom": "Den udstrækning, du definerer, ændrer dit korts hjemudstrækning. Bemærk, at denne udstrækning ikke bruges, hvis den ikke inkluderer det første tour-punkt. I så fald åbner touren centreret på det første punkt.",
      "settingsExtentDateLineError": "Udstrækningen må ikke krydse meridianen på længdegraden 180°",
      "settingsExtentDateLineError2": "Fejl ved behandlingen af udstrækningen",
      "settingsExtentDrawBtn": "Tegn ny udstrækning",
      "settingsExtentModifyBtn": "Redigér udstrækningen",
      "settingsExtentApplyBtn": "Vis på Map Tour",
      "settingsExtentUseMainMap": "Brug Map Tour-udstrækning",
      "settingsZoomExplain": "Indstil zoom for historiepunkter (valgfrit).",
      "settingsLabelZoom": "Skala/niveau",
      "settingsZoomFirstValue": "Ingen",
      "settingsFieldError": "Marker et felt i hver liste",
      "dataTitle": "Opret \"hosted\" Map Tour-lag",
      "dataExplain": "Der vil blive oprettet et nyt vektorlag til dine billeder og tour-punkter. Tour-laget vil ikke blive delt med nogen, medmindre du deler din Map Tour.",
      "dataExplainPortal": "Hvis vektorlaget ikke bliver oprettet, skal du kontakte din ArcGIS-administrator.",
      "dataNameLbl": "Navn på lag",
      "dataFolderListLbl": "Mappe",
      "dataFolderListFetching": "Henter mapper...",
      "dataRootFolder": "Rod",
      "dataNameError": "Indtast et navn for featuretjenesten",
      "dataFolderError": "Vælg en gyldig mappe",
      "dataSrcContainsInvalidChar": "Navnet på featuretjenesten indeholder et eller flere ugyldige tegn (-, <, >, #, %, :, \", ?, &, +, / eller ).",
      "dataSrvAlreadyExistsError": "Der findes allerede en tjeneste med dette navn i organisationen. Vælg et andet navn.",
      "dataBtnSave": "Opret lag",
      "dataFooterProgress": "Oprettelse i gang",
      "dataFooterSucceed": "Oprettelse lykkedes. Indlæser",
      "dataFooterError": "Oprettelse mislykkedes. Prøv igen",
      "tabError": "Kontrollér for fejl på alle faner",
      "introRecordBtn": "Introduktion",
      "introRecordActivate": "Brug det første punkt som introduktion (vises ikke i karrusellen)",
      "coverRecordActivate": "Brug det første punkt som forside",
      "coverBuilder": "Konfiguration af forside",
      "cover": "Forside",
      "showCover": "Vis forside",
      "editCover": "Redigér forside",
      "coverNoVideo": "Video understøttes ikke som forsidemedie. Vælg et billede.",
      "coverPreview": "Hvis du vil se forsiden, skal du gemme din historie og derefter forhåndsvise den ved hjælp af knappen Vis historie.",
      "thirdPartyTerms": "Ved at benytte en tredjeparts-tjeneste accepterer du vilkårene for brug af den pågældende tjeneste: "
    },
    "addPopupJS": {
      "uploadingPicture": "Overfører billede",
      "uploadSuccess": "Overførsel lykkedes",
      "uploadError": "Fejl ved overførsel af billede",
      "uploadError2": "Fejl ved tilføjelse af objektet (ugyldig html-kode)",
      "notJpg": "Vælg et jpeg-foto at overføre",
      "errorNoPhoto": "Vælg et billede at overføre",
      "errorNoThumbnail": "Vælg et miniaturebillede at overføre",
      "errorInvalidPicUrl": "Indtast en gyldig billed-URL. Starter med https. Slutter med jpg, png, gif eller bmp, eller afslut URL’en med '#isImage' for at tilsidesætte denne regel.",
      "errorInvalidThumbUrl": "Indtast et gyldigt miniaturebillede (starter med https://, slutter med jpg, png, gif eller bmp).",
      "errorInvalidVideoUrl": "Indtast en gyldig video-URL (starter med https://)",
      "errorNoName": "Angiv et navn for dette turpunkt",
      "errorNoDescription": "Angiv en billedtekst for dette turpunkt",
      "errorNoLocation": "Indstil en position for dette turpunkt"
    },
    "builderJS": {
      "noPendingChange": "Ingen ikke-gemte ændringer",
      "unSavedChangeSingular": "1 ikke-gemt ændring",
      "unSavedChangePlural": "ikke-gemte ændringer",
      "shareStatus1": "Turen gemmes ikke",
      "shareStatus2": "Turen deles offentligt",
      "shareStatus3": "Turen deles inden for organisationen",
      "shareStatus4": "Turen deles ikke",
      "popoverDiscard": "Er du sikker på, at du vil slette nogle ikke-gemte ændringer?",
      "yes": "Ja",
      "no": "Nej",
      "popoverLoseSave": "Ved at åbne viseren mister du eventuelle ikke-gemte ændringer",
      "ok": "OK",
      "popoverSaveWhenDone": "Glem ikke at gemme, når du er færdig",
      "closeWithPendingChange": "Er du sikker på, at du vil bekræfte handlingen? Dine ændringer vil gå tabt.",
      "gotIt": "OK",
      "savingApplication": "Gemmer historie",
      "saveSuccess": "Historien gemt",
      "saveError": "Lagring mislykkedes, prøv igen",
      "saveError2": "Lagring mislykkedes pga. en ugyldig html-kode i et navn eller beskrivelse",
      "saveError3": "Titlen kan ikke være tom",
      "dragColorPicker": "Flyt mig rundt,<br />eller skift min farve",
      "dataWarningExtent": "Du har data uden for webkortudstrækningen. Disse data vil ikke blive brugt som turpunkter. Du skal ændre kortudstrækningen, hvis du vil bruge dem.",
      "dataWarningVisibi": "Dit Map Tour-lag er ikke synligt med den aktuelle webkortudstrækning. Bekræft, at dit Map Tour-lag vil være synligt med et %MAPSIZE% større kort.",
      "dataWarningEdit": "Redigér webkort",
      "dataWarningClose": "Luk",
      "signIn": "Log ind med en konto på",
      "signInTwo": "for at gemme historien",
      "switchBM": "Skift baggrundskort"
    },
    "organizePopupJS": {
      "messageStart": "Du har valgt at slette",
      "messageSinglePoint": "ét turpunkt",
      "messageMultiPoint": "turpunkter",
      "messagePermantRemove": "Dette vil permanent fjerne",
      "messageRecord": "post",
      "messageRecordPlural": "poster",
      "messageConfirm": "fra din database. Vil du fortsætte?",
      "labelButtonShow": "Vis",
      "labelButtonHide": "Skjul"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Dette vil slette billedet og miniaturen permanent",
      "popoverDeleteWarningThumb": "Dette vil slette miniaturen permanent",
      "popoverUploadingPhoto": "Overfører billede og miniaturebillede",
      "popoverUploadingThumbnail": "Overfører miniaturebillede",
      "popoverUploadSuccessful": "Overførsel lykkedes",
      "popoverUploadError": "Overførsel mislykkedes, prøv igen",
      "changePicAndThumb": "Redigér billede",
      "changeThumb": "Redigér miniaturebillede",
      "selectPic": "Redigér medier",
      "selectThumb": "Redigér miniaturebillede",
      "uploadPicAndThumb": "Anvend"
    },
    "headerJS": {
      "editMe": "Redigér mig!",
      "templateTitle": "Angiv titel",
      "templateSubtitle": "Angiv undertitel",
      "edit": "Redigér"
    },
    "crossFaderJS": {
      "setPicture": "Indstil billedtitel",
      "setCaption": "Indstil billedtekst"
    },
    "importPopup": {
      "title": "Importér",
      "prevBtn": "Tilbage",
      "nextBtn": "Næste"
    },
    "importPopupHome": {
      "header": "Hvor er dine billeder lagret?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "billeder",
      "videos": "videoer",
      "disabled": "Dette objekt er blevet deaktiveret af administratoren",
      "disabledPortal": "Dette objekt kræver, at portalen har en værtsserver. Kontakt din Portal for ArcGIS-administrator.",
      "header1": "Dine billeder skal være delt offentligt.",
      "header2": "Importen begrænses til det første %NB1%%MEDIA%.",
      "emptyDataset": "Fejl, der blev ikke fundet nogen billeder",
      "footerImport": "Importér",
      "selectAlbum": "Vælg et offentligt album",
      "selectAlbum2": "Vælg et album",
      "pleaseChoose": "Vælg",
      "userLookup": "Slå op",
      "userLookingup": "Slår op",
      "csv": "Refereres til i en CSV-fil",
      "advanced": "Avancerede indstillinger",
      "advancedScratchLbl": "Start en ny tur",
      "advancedScratchTip": "Opret en tom rundtur, som du kan tilføje punkter i. Dine medier skal være online. Denne valgmulighed understøtter ikke indlæsning af dine billeder.",
      "advancedCSVLbl": "Importér turdata fra en CSV-fil",
      "advancedCSVTip": "Importér dit rundtursindhold fra en CSV-fil, der henviser til dine medier online. Denne valgmulighed understøtter ikke indlæsning af dine billeder.",
      "advancedCommonTip": "Det kræver, at dine billeder og videoer allerede er online.",
      "select": "Foretag en markering",
      "locUse": "Brug billed-geoplacering",
      "locExplain": "Det er ikke sikkert, du vil benytte billedplaceringer, da de kan være genbrugt fra albummet, hvilket betyder, at alle fotos placeres samme sted.",
      "locExplain2": "Det er ikke sikkert, du vil benytte videoplaceringer, da de kan være genbrugt fra brugerindstillingerne, hvilket betyder, at alle videoer er placeret det samme sted."
    },
    "viewFlickr": {
      "title": "Flickr-import",
      "header": "Indtast dit Flickr-brugernavn og vælg et album eller et nøgleord, der skal importeres.",
      "userInputLbl": "Indtast et brugernavn",
      "signInMsg2": "Bruger ikke fundet",
      "selectSet": "Vælg et album",
      "selectTag": "eller vælg et nøgleord",
      "footerImportTag": "Importér det valgte nøgleord",
      "footerImportSet": "Importer det valgte album"
    },
    "viewFacebook": {
      "title": "Facebook-import",
      "header": "Godkend med din Facebook-brugerkonto, eller brug en offentlig side. Private albummer kan bruges til at oprette en offentlig Map Tour, der ikke kræver Facebook-brugergodkendelse, hvilket gør det muligt at bevare kommentarer og \"likes\" private.",
      "leftHeader": "Facebook-bruger",
      "rightHeader": "Facebook-side",
      "pageExplain": "En Facebook-side er et offentligt varemærke//produkt eller en celebritet ligesom <b>esrigis</b>. Du kan få sidenavnet efter den første '/' i sidens URL.",
      "pageInputLbl": "Indtast et sidenavn",
      "lookupMsgError": "Side ikke fundet"
    },
    "viewPicasa": {
      "title": "Google+ import",
      "header": "Indtast din e-mail-adresse eller dit ID.",
      "userInputLbl": "E-mail eller Picasa/Google+ ID",
      "signInMsg2": "Kontoen kunne ikke findes",
      "signInMsg3": "Intet offentligt album",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Få flere oplysninger</a>",
      "howToFind2": "Kopiér tal mellem første og anden '/' på en vilkårlig Picasa-side"
    },
    "viewCSV": {
      "title": "CSV-import",
      "uploadBtn": "Markér eller slip en CSV-fil",
      "resultHeaderEmpty": "CSV-filen er tom",
      "resultHeaderSuccess": "Har indlæst %NB_POINTS%-punkter",
      "resultHasBeenLimited": "Importen blev begrænset til de første %VAL1% punkter ud af %VAL2% for at overholde grænsen på %VAL3% punkter pr. tur",
      "browserSupport": "Din browser understøttes ikke. Hvis du vil bruge en CSV-fil, skal du <a href='http://browsehappy.com/' target='_blank'>opgradere din browser</a> eller bruge ArcGIS.com-webkortviser (se Hjælp).",
      "errorLatLng": "Der blev ikke fundet bredde- og længdegradsfelter. Mulige værdier for breddegrad er: <i>%LAT%</i> pg for længdegrad: <i>%LONG%</i>.",
      "errorFieldsExplain": "Indlæsningen mislykkedes, de følgende obligatoriske felter ikke blev fundet",
      "errorFieldsName": "<b>Navn</b> mulige værdier er: %VAL%",
      "errorFieldsDesc": "<b>Beskrivelse</b> mulige værdier er: %VAL%",
      "errorFieldsUrl": "<b>Billed-URL</b> mulige værdier er: %VAL%",
      "errorFieldsThumb": "<b>Miniature-URL</b> mulige værdier er: %VAL%",
      "errorFields2Explain": "Indlæsningen mislykkedes, da CSV-filen ikke ikke bruger samme attributter som laget for følgende attributter",
      "errorFields2Name": "<b>Navn</b> brug %VAL1% i stedet for %VAL2%",
      "errorFields2Desc": "<b>Beskrivelse</b> brug %VAL1% i stedet for %VAL2%",
      "errorFields2Url": "<b>Billed-URL</b> brug %VAL1% i stedet for %VAL2%",
      "errorFields2Thumb": "<b>Miniature-URL</b> brug %VAL1% i stedet for %VAL2%",
      "resultFieldsAll": "Alle attributter er importeret",
      "resultFieldsNotAll": "Følgende attributter er ikke importeret, da de ikke eksisterer i kortlaget",
      "resultFieldsNotAll2": "Følgende attributter er  importeret",
      "footerNextBtnResult": "Importér til webkortet",
      "footerProgress": "Import i gang",
      "footerSucceed": "Import lykkedes. Indlæser"
    },
    "viewYoutube": {
      "title": "YouTube-import",
      "header": "Angiv et YouTube-brugernavn for at finde offentligt delte videoer.",
      "pageInputLbl": "Indtast et Youtube-brugernavn",
      "lookupMsgError": "Bruger ikke fundet",
      "howToFind": "Sådan finder du et YouTube-brugernavn",
      "howToFind2": "Brugernavnet vises under videoer",
      "found": "Fundet",
      "noData": "Ingen offentlige videoer fundet"
    },
    "viewGeoTag": {
      "title": "Vælg og find dine billeder/videoer",
      "header": "Elementer med en placering bliver importeret. Klik på eventuelle ikke-placerede elementer, som du vil importere, for at finde deres placering.",
      "headerMore": "Hjælp",
      "headerExplain": "Når du klikker på knappen <b>Importér</b>, importeres kun billeder eller videoer, der er angivet på fanen <b>Placeret</b>.<br><br>Geoplaceringsinformation, der er gemt sammen med billederne eller videoerne, importeres automatisk, hvis den er tilgængelig. Alle elementer uden geoplacering er angivet på fanen <b>Skal placeres</b>. For at finde et emne, der er angivet på den fane, skal du klikke på det og derefter klikke på den ønskede placering på kortet.<br><br>Hvis du vil fjerne et element fra fanen <b>Placeret </b>, så det ikke bliver importeret, skal du klikke på knappen Importer ikke, som vises, når du flytter markøren hen over det pågældende element.<br><br>Tip: Hvis oplysninger om geoplacering af dine egne medier ikke importeres, skal du kontrollere indstillingerne for databeskyttelse for din konto. Kontrollér f.eks. i dine Flickr-kontoindstillinger, at EXIF-data ikke er skjult. Hvis databeskyttelsesindstillingen på Flickr til import af EXIF-data er slået fra (standard), bliver geoplaceringer ikke blive gemt i Flickr for dine billeder, medmindre du overfører dem igen, eller manuelt angiver deres placeringer på Flickr.",
      "leftPanelTab1": "Skal findes",
      "leftPanelTab2": "Fundet",
      "clickOrTap": "Klik på kortet for at finde",
      "clearLoc": "Ryd placeringer",
      "clickDrop": "Importér ikke",
      "footerImport": "Importér",
      "footerProgress": "Import i gang",
      "footerSucceed": "Import lykkedes. Indlæser...",
      "loading": "Indlæser",
      "error": "Import af billedernes geoplaceringer mislykkedes, geoplaceringer er blevet tilsidesat."
    },
    "initPopup": {
      "title": "Velkommen til Map Tour Builder",
      "prevBtn": "Tilbage",
      "nextBtn": "Næste"
    },
    "initPopupHome": {
      "header1": "Hvor er dine billeder eller videoer?",
      "header2": "Denne assistent hjælper dig med at oprette en Map Tour på grundlag af medier, der allerede er lagret online, eller den importerer dem til din ArcGIS Online for Organizations-konto.",
      "title1": "De findes allerede online",
      "title2": "Jeg skal overføre mine billeder",
      "hostedFSTooltip": "Overfør dine billeder, og gem dem i din rundtur (understøtter ikke video).",
      "hostedFsNA": "Du skal være udgiver eller have en anden rolle med rettigheder til at publicere \"hostede\" vektorlag. Kontakt din ArcGIS-administrator.",
      "hostedFsNA2": "Kun tilgængelig med ArcGIS Online-abonnement. <a href='%LINK%'>Tilmeld dig et gratis prøveabonnement</a>",
      "footer1": "Når du er færdig, skal du huske at dele din Map Tour med dit publikum gennem siden for applikationselementer.",
      "footer3": "Download CSV-skabelonen",
      "footer4": "\"Gem som\" hvis den ikke overføres",
      "footer4bis": "Brug højreklik og \"Gem som\", hvis overførslen ikke starter",
      "footer5": "Find ud af mere",
      "footerProgress": "Oprettelse i gang",
      "footerSucceed": "Oprettelse lykkedes. Indlæser..."
    },
    "helpPopup": {
      "title": "Hjælp",
      "close": "Luk",
      "tab1": {
        "title": "Introduktion",
        "moreInfo": "Yderligere oplysninger.",
        "infoSites": "Besøg <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>Map Tour-afsnittet</a> af <a href='https://storymaps.arcgis.com' target='_blank'>Esri Story Maps-webstedet.</a>",
        "mtFAQ": "Se <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Map Tour FAQ.</a>",
        "myStories": "Du kan administrere dine Map Tours og kontrollere dem for fejl i <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Mine historier</a> på webstedet.",
        "div1": "Map Tour-skabelonen er udviklet til at præsentere geografisk information dér, hvor der er et spændende fotografi- eller medieelement, der passer til din historie.",
        "div2": "Skabelonen producerer en attraktiv, brugervenlig webapplikation, der gør det muligt at præsentere en række steder på et kort i nummereret rækkefølge, som brugere kan gennemse. Skabelonen er beregnet til at anvendelse i alle webbrowsere og på alle enheder, herunder smartphones og tablets.<br /><br />",
        "div42": "For at se eksempler på rundture, som andre forfattere er i gang med at skabe, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>kan du besøge galleriet</a> på <a href='https://storymaps.arcgis.com/' target='_blank'>Story Maps-webstedet</a>. Du kan også følge os på Twitter på <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Vi vil meget gerne have din tilbagemelding! Fortæl os om eventuelle problemer og nye funktioner, som du har brug for, ved at besøge Story Maps-forum på <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet.</a>"
      },
      "tab2": {
        "title": "Data",
        "div1": "Det vigtigste, du skal overveje, når du skal oprette en Map Tour, er hvor dine billeder skal lagres. En Map Tour kan bruge billeder, der er lagret på fotodelingstjenester, webservere eller som overføres fra en disk.",
        "div1a": "Se det sidste afsnit på denne fane for at få oplysninger om understøttede formater og videoer.",
        "div2": "Det interaktive builder-program indeholder to muligheder til håndtering af billeder i din Map Tour:",
        "div3": "<ul><li>Du kan bruge <b>billeder, der allerede er online</b>, såsom billeder på Flickr eller Google+, eller billeder, der er gemt på din egen webserver. Der vil være referencer til disse billeder i din Map Tour via deres URL'er.</li><li>Du kan også <b>overføre billeder fra din computer</b> direkte til din Map Tour. Denne mulighed kræver, at du har et ArcGIS-abonnement, og at du har udgiver- eller administratorrettigheder, fordi der automatisk oprettes en \"hosted\" featuretjeneste til dig, hvor dine fotos gemmes som vedhæftninger.</li></ul>",
        "div4": "Typiske brugerscenarier:",
        "div4b": "<b>Dine billeder er ikke  \"hosted \"</b> endnu, og du har et ArcGIS-abonnement: Det er dit bedste valg at benytte en  \"hosted \" featuretjeneste. Ligesom på offentlige fotodelingstjenester vil vi optimere dine billeder med henblik på at oprette billeder, der indlæses hurtigt, og du får adgang til alle administrations- og datahåndteringsfunktionerne på ArcGIS-platformen.",
        "div5": "<b>Du er ikke medlem af en organisation</b>: Du skal først overføre dine billeder til et fotodelings-websted eller til din egen webserver. Builder-programmet hjælper dig med at anvende disse billeder, der fortsat vil være \"hosted\" på deres oprindelige placering.",
        "div6": "<b>Du vil gerne genbruge en eksisterende featuretjeneste,</b> som gemmer dine billeder som vedhæftede filer, eller som henviser til eksterne billeder: Se afsnittet med detaljerede oplysninger nedenfor.",
        "div7": "<b>Du bruger en tidligere version</b> af Map Tour-skabelonen og har allerede en CSV-fil, der henviser til dine billeder og miniaturer: Du kan importere den og forfine dine data. Builder-programmet understøtter kun CSV-filer, der benytter længde- og breddegradsfelter. Adressebaserede CSV-filer kan fortsat benyttes via dit webkort (se nedenfor).",
        "div8": "Import fra online fotodelingstjenester",
        "div9a": "Facebook-understøttelse er blevet standset, ${learn}.",
        "learn": "lær mere",
        "div9": "Denne import-handling henviser til billeder, der allerede er \"hosted\" ved at gemme deres URL'er i en samling af webkorttjenester. Billederne gemmes ikke på ArcGIS Online. Hvis du ikke kan få adgang til de \"hostede\" billeder, vil de ikke være tilgængelige i din Map Tour, og du får vist et billede med teksten 'Billedet er ikke tilgængeligt'. Det afhænger af tjenesteudbyderen, om din Map Tour importerer navn, beskrivelse og placering for billederne. Disse attributter gemmes i webkortet, og eventuelle redigeringer af online-tjenesten vises ikke i Map Tour.",
        "div10": "Lagring af billeder på en web-server",
        "div11": "Hvis du vælger at hoste dine billeder på din egen webserver (i stedet for at have billederne på Flickr eller Google+, eller overføre dem direkte til din tour), skal du manuelt oprette miniaturebilleder til dine billeder. Hvis du bruger billeder i fuld opløsning til miniaturebillederne, bliver de ikke gode. Se disse <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>FAQ</a> for at få tips til at tilpasse størrelsen på dine billeder, hvis du benytter dem på nettet direkte via URL’er.",
        "div12": "Bruge eksisterende GIS-data",
        "div13": "Enhver featuretjeneste, CSV-fil eller shapefil, der indeholder punkter, kan bruges som datakilde for Map Tour, hvis den indeholder det sæt felter, applikationen forventer. Du skal tilføje den som et lag i et ArcGIS-webkort og derefter dele kortet ved at oprette en Map Tour.",
        "div14": "De understøttede værdier for feltnavnene er (forskel på store og små bogstaver):",
        "div151": "Navn",
        "div152": "Beskrivelse",
        "div153": "Billede",
        "div154": "Miniature",
        "div155": "Farve ",
        "div16": "Hvis applikationen ikke finder matchende felter, når der benyttes en featuretjeneste, fungerer viewer-programmet ikke, før du konfigurerer de felter, der skal benyttes via builder-programmet. CSV- og shapefil-lag, der er føjet til webkortet, skal have alle de obligatoriske felter, ellers fungerer builder-programmet ikke.",
        "div162": "Når du anvender en featuretjeneste, der gemmer billeder som vedhæftede filer, <b>er det kun objekter med to vedhæftninger, der benyttes</b>. Den første vedhæftning definerer hovedbilledet, og den anden definerer miniaturen.",
        "div17": "Billed- og miniaturefelterne er obligatoriske for featuretjenester uden vedhæftninger og valgfrie (men anbefalede) for featuretjenester med vedhæftninger. Hvis din tjeneste har vedhæftninger aktiveret, kan du overføre billeder som vedhæftede filer med builder-programmet. Hvis ikke, kan du kun redigere billed- og miniature-URL'erne.",
        "div172": "Billed- og miniaturefelterne vil, når de findes, altid blive brugt, og der vil ikke blive anmodet om featuretjenestens vedhæftninger.",
        "div173": "Eksempel-CSV-filer og shapefiler kan overføres fra",
        "div174": "Se disse <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>FAQ</a> for at få flere oplysninger om at bruge eksisterende GIS-data.",
        "div18": "Opretter en \"hosted\" featuretjeneste ud fra en CSV- eller shapefil",
        "div19": "Når du opretter en \"hosted\" featuretjeneste på basis af en CSV- eller shapefil, er vedhæftninger ikke aktiveret som standard. Hvis du vil aktivere dem, skal du åbne featuretjenestens oplysningsside og klikke på den lille pil på lagsektionen for at få indstillingen vist. Map Tour'en vil fortsat bruge de billeder og miniaturer, du har refereret til via attributter. Hvis du vil overføre dine billeder som featuretjeneste-vedhæftninger, kan du gøre det vha. to knapper på billedpanelet (\"Redigér billede\" og \"Redigér miniature\").",
        "div20": "Understøttede billedformater og videoer",
        "div21": "Hvis du benytter billeder på Flickr eller Google+, får din Map Tour automatisk adgang til disse billeder som .jpg-filer. Hvis du overfører billeder til Map Tour builder-programmet, skal billederne være i formaterne .jpg eller .jpeg. Hvis du henviser til billeder direkte på internettet via deres URL’er, understøttes billedformaterne .jpg, .jpeg, .png, .gif og .bmp. YouTube-videoer understøttes direkte.",
        "div22": "Map Tour-skabelonen indeholder ikke en videoafspiller, så du skal bruge den eksterne videoafspiller, som leveres af din foretrukne værtstjeneste for videoindhold (find indstillingen til indlejring af videoen, og kopiér den URL, der findes i den givne kode). Hvis du selv ønsker at \"hoste\" videoen, kan du oprette en HTML-side, der indeholder en videoafspiller som f.eks. <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Det interaktive builder-program indeholder ikke nogen dialogboks, som kan benyttes til at inkludere videoer, når du bruger featuretjenester med vedhæftninger, men det er muligt at gøre dette ved at redigere dine data uden for det interaktive builder-program. I ArcGIS-kortviseren vil dit medie blive betragtet som en video, hvis du redigerer billedfelterne, så de peger på en ekstern video og tilføjer en særlig parameter i slutningen af din URL (#isVideo).",
        "div24": "Bemærk, at du fortsat skal have to gyldige vedhæftede billeder, ellers vil punktet ikke blive anvendt. Du kan ikke bruge videoer, når du benytter featuretjeneste-vedhæftninger uden billed- og miniaturefelter."
      },
      "tab3": {
        "title": "Tilpasning",
        "div1": "Map Tour builder indeholder flere muligheder for tilpasning, der er tilgængelige via knappen INDSTILLINGER i toppanelet. Hvis du ikke kan finde den indstilling, du skal bruge, findes der også en version, der kan downloades til din webserver, hvor du kan bruge den til de indstillinger, du ønsker.",
        "div2": "Vi anbefaler, at du bruger den \"hostede\" version, medmindre:",
        "div3": "<li>Den ikke indeholder den UI-tilpasning, du ønsker, f.eks. brug af et baggrundsbillede til overskiften</li><li>Du er udvikler, og du ønsker at forbedre applikationen.</li>",
        "div4": "Den overførbare version kan konfigureres via en webkort- eller en webkortapplikationsidentifikator. De primære brugssituationer er:",
        "div41": "Du opretter din map tour med det interaktive builder-program i værtsmiljøet og konfigurerer skabelonen med et webkortapplikations-ID. De indstillinger, du har defineret med det interaktive builder-program, vil blive anvendt.",
        "div42": "Du opretter din map tour uden for det interaktive builder-program og konfigurerer skabelonen med et webkort-ID. Du skal læse dokumentationen for at lære, hvordan du konfigurerer skabelonen.",
        "div43": "Bemærk, at det interaktive builder-program er tilgængeligt i en version, der kan overføres, men at der er nogle tekniske begrænsninger for browsere, f.eks. Internet Explorer, der er ældre end version 10.",
        "div5": "Hvis du vil downloade den nyeste version af skabelonen og lære mere om, hvordan du bruger den, kan du besøge <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub-projektsiden</a>."
      },
      "tab4": {
        "title": "Tips",
        "div0": "Understøttede browsere",
        "div0a": "Map Tour-viewer-programmet understøttes af IE8+. Det interaktive builder-program understøttes af IE9+. Vi tester programmet i alle de store browsere, men hvis du kommer ud for vanskeligheder, anbefaler vi, at du bruger Chrome.",
        "div0b": "Giv os gerne besked, hvis du kommer ud for vanskeligheder. I mellemtiden vil du, når du opretter din Map Tour ved hjælp af CSV-skabelonen, minimere din interaktion med builder-programmets grænseflade.",
        "div1": "Billeder",
        "div2": "Selvom billeder med forskellige størrelser, former og orientering kan bruges i en Map Tour, anbefaler vi liggende billeder i stedet for stående. Billeder med et 4:3-format passer bedst. I Tre-panelet og integrerede layouts, hvor billedteksten overlapper billedet, kan stående billedretning betyde, at billedet bliver skjult af billedteksten. I Tre-panelet og integrerede layouts anbefaler vi at bruge samme størrelse og form til alle billeder, hvis det er muligt. På den måde bliver brugeren ikke distraheret af forskellige billedstørrelser, når de ser din tour.",
        "div2a": "Vi anbefaler en maksimal billedstørrelse på 1000 pixels i bredden x 750 pixels i højden for almindelige billeder og 140x93 for miniaturer.",
        "div3": "Formatering af din billedtekst vha. HTML-tags",
        "div4": "Du kan indsætte HTML-koder i dine billedtekster for at definere formatering og links. For eksempel vil denne kode tilføje et grønt hyperlink:",
        "div4aa": "<b>Opret en forside til din sidepaneltour</b><br>Sidepanellayoutet understøtter en valgfri forside, så du kan få dit publikums opmærksomhed med et fantastisk  fuldskærmsbillede. Hvis du vil konfigurere forsiden til en sidepaneltour, skal du først tilføje nogle eller alle dine punkter i din tur. Klik derefter på knappen Organisér, og i den dialogboks, der vises, skal du sørge for at det tourpunkt, du vil bruge til at definere forsiden, er det første punkt i din tour. Klik derefter på boksen 'Brug det første punkt som forside' i dialogboksen. Navnet på dit første tourpunkt bliver titlen, som vises på forsiden, billedteksten til dette punkt bliver undertitlen, og dette punkts billede bliver billedet på forsiden. Video understøttes ikke på forsiden. Se disse <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>FAQ</a> for at få flere oplysninger.</a>",
        "div4a": "Skriv en god undertitel til din tur",
        "div4b": "Brug tid på at skrive en markant undertitel til din tour. Undertitlen er en god måde at drage brugerne ind i din tour på og fortælle dem, hvad de vil blive præsenteret for på touren. Det er også et godt sted at fortælle dit publikum, hvilken stat eller hvilket land touren foregår i. Du skal f.eks. ikke regne med, at brugerne ved, hvor byen i din tur ligger. Du må ikke gøre undertitlen for lang. Hvis du ikke kan komme i tanker om en god undertitel, så lad være med at skrive en. I modsætning til Tre-panelet og integrerede layouts understøtter sidepanellayoutet ikke en undertitel i overskriften. Hvis du bruger forsideindstillingen i sidepanellayoutet, vises billedteksten for det første punkt i din tour på forsiden og fungerer så som undertitel til din tour.",
        "div5": "Understøttende lag",
        "div6": "Du kan tilføje flere understøttende lag, der giver yderligere kontekst til din Map Tour. Disse lag kan indeholde andre geografiske objekter, som du ønsker, at kortet skal vise som supplement til Map Tour-punkterne, såsom et undersøgelsesområde, en gå- eller kørerute, der forbinder dine tour-punkter osv. Map Tour-skabelonen viser disse supplerende supportlag vha. den symbologi, du angiver i webkortet, men pop-up-vinduerne er ikke tilgængelige. Hvis du vil tilføje understøttende lag til din rundtur, skal du gemme dit arbejde og lukke Map Tour Builder. Åbn derefter det webkort, der blev brugt i din rundtur. Du kan finde dette i ArcGIS Mit indhold eller via afsnittet Mine historier på Story Maps-webstedet.",
        "div7": "Pas på, din tour ikke bliver for lang",
        "div8": "Der er en begrænsning på 99 punkter pr. tour. De fleste Map Tours vil naturligvis være væsentligt kortere end dette. Publikum har som regel ikke lyst til at gå igennem alt for mange tour-punkter. Det er ikke sikkert, de finder dit emne lige så spændende, som du gør!",
        "div10": "Indlejringstilstand",
        "div11": "Hvis du ønsker at indlejre skabelonen på et andet websted via en iframe, fjernes overskriften, hvis du tilføjer den valgfrie parameter \"&embed\" i slutningen af URL'en.",
        "div12": "Undgå at bruge en iFrame-bredde, der er for smal, fordi det medfører, at Map Tour'en skifter til det lille touch-screen-baserede layout, der benyttes på mobile enheder. Hvis du vil maksimere brugervenligheden, når du indlejrer en Map Tour, anbefaler vi altid, at du placerer et link ved siden af den indlejrede tur, så brugerne kan starte turen i fuldskærmsvisning."
      },
      "tab5": {
        "title": "Udgivelse",
        "div1": "Når du er færdig, så husk at dele din map tour med dit publikum via knappen DEL eller via applikationens elementoplysningsside i ArcGIS Online.",
        "div2a": "Deler turen via builder-programmet",
        "div2b": "Knappen DEL vil opdatere applikations- og webkortelementerne. Hvis dine tour-data er lagret i et featuretjenesteelement, bliver dette element også opdateret. Hvis du har tilføjet andre lag via ArcGIS.com-kortviseren, opdateres disse ikke. Dette kan medføre, at turen ikke deles som forventet. Elementer, der allerede har de påkrævede rettigheder (eller flere), opdateres ikke.",
        "div2c": "Deler turen via ArcGIS Online",
        "div2d": "Når du deler applikationen via ArcGIS Online, vil du muligvis blive bedt om at opdatere eventuelle afhængige ressourcer (webkort, featuretjeneste, udsmykningslag), der ikke deles på samme måde. Hvis map tour'en er offentlig, og en af dine ressourcer ikke deles med publikum, vil brugere blive omdirigeret til ArcGIS Online-loginsiden.",
        "div3t": "Sikkerhed for featuretjenester",
        "div3a": "Hvis du bruger en \"hosted\" featuretjeneste, der er oprettet med Map Tour-builder-programmet, håndterer applikationen tjenestens sikkerhed for dig , og du er den eneste, der har redigeringsrettigheder, også når tjenesten er delt med offentligheden.",
        "div3t2": "Før du deler turen med dit publikum",
        "div3": "Kontrollér, at turen fungerer godt, når du ikke er logget ind med din ArcGIS.com-konto. Den URL, du skal bruge, må ikke omdirigere til en loginside eller til builder-tilstand.",
        "div4": "Det er en god idé at se, hvordan din map tour ser ud på en iPad, der holdes vandret, for at kontrollere, at den ser godt ud på denne populære enhed. Dette kan hjælpe dig med at se, om dine billedtekster dækker for meget af billederne. Du kan også se, om din undertitel passer og ikke er for lang, så den bliver afskåret.",
        "div5a": "Anbefaling vedr. søgning",
        "div5b": "For at hjælpe brugere med at finde din map tour, hvis de søger på ArcGIS Online, anbefaler vi, at du tilføjer nøgleordet 'story map' på kortturens applikationselementside (ikke webkortets elementside) sammen med nøgleord, såsom navnet på staten eller regionen, hvor turen er placeret, landenavnet - hvis det er uden for USA - og temanøgleord som 'public art', 'tourist guide' eller 'historic places'. Disse nøgleord hjælper også os hos Esri med at finde smarte nye eksempler på ture, vi kan vise i vores gallerier og promovere på de sociale medier. Vi anbefaler også, at du overfører et pænt miniaturebillede til din applikations elementoplysningsside, f.eks. et lille screenshot af turen eller et af billederne fra den. Dette billede bruges automatisk, hvis din map tour føjes til et ArcGIS Online-galleri."
      }
    },
    "share": {
      "firstSaveTitle": "Tour gemt",
      "manageStory": "Administrér din historie",
      "manageStoryA1": "Tip: Du kan bruge %LINK1% til at tjekke din historie for fejl samt ændre, hvordan dens komponenter deles,  få den til at se godt ud på de sociale medier etc. Der er yderligere oplysninger om Mine historier her %LINK2%.",
      "manageStoryA1V1": "Mine historier",
      "manageStoryA1V2": "her",
      "shareTitle": "Del din Map Tour",
      "sharePrivateHeader": "Din Map Tour er ikke delt. Vil du gerne dele den?",
      "sharePrivateBtn1": "Del offentligt",
      "sharePrivateBtn2": "Del med min organiaation",
      "sharePrivateProgress": "Deling i gang...",
      "sharePrivateErr": "Deling mislykkedes, prøv igen eller",
      "sharePrivateOk": "Deling opdateret, indlæser...",
      "sharePreviewAsUser": "Forhåndsvisning",
      "shareHeader1": "Din Map Tour er <strong>offentligt tilgængelig</strong>.",
      "shareHeader2": "Din Map Tour er tilgængelig for dine organisationsmedlemmer (login kræves).",
      "shareLinkHeader": "Del din Map Tour",
      "shareLinkOpen": "ÅBN",
      "shareA1": "Brug %SHAREIMG% på <a href='%LINK1%' target='_blank'>siden med applikationselementet</a>. Hvis du også vil ophæve deling af webkortet, skal du bruge <a href='%LINK2%' target='_blank'>siden med webkortelementer</a>.",
      "shareWarning": "Deling %WITH% er blevet deaktiveret, fordi du ikke er ejer af <a href='%LINK%' target='_blank'>webkortet</a>.",
      "shareWarningWith1": "offentligt",
      "shareWarningWith2": "offentligt og med organiaationen",
      "viewStory": "Vis historie"
    },
    "locator": {
      "error": "Placering er ikke tilgængelig"
    },
    "saveErrorSocial": {
      "title": "Opdatering af deling på sociale medier",
      "panel1": "Visningen af din historie på de sociale medier er blevet forbedret, men din ArcGIS-webapplikations elementtitel er ikke identisk med din historietitel.",
      "panel1tooltip": "Ved at definere en titel, et resumé og et miniaturebillede kan din historie komme til at se sådan ud:",
      "panel2": "Hvilken titel vil du gerne bruge på de sociale medier:",
      "panel2q1": "Historietitel (anbefales)",
      "panel2q1tooltip": "Når du vælger denne indstilling, vil din elementtitel blive ændret, så den matcher din historietitel, og yderligere ændringer i builder-programmet vil blive synkroniserede.",
      "panel2q2": "Elementtitel",
      "panel3": "Hvis du vil forbedre visningen af din historie på de sociale medier yderligere, kan du bruge ${MYSTORIES} til at tilføje et resumé og et miniaturebillede.",
      "panel4": "Giv mig ikke igen besked om denne historie",
      "mystories": "Mine historier",
      "btnSave": "Gem"
    },
    "bannerNotification": {
      "learnMore": "Yderligere oplysninger",
      "close": "Luk",
      "dontShowAgain": "Vis ikke denne meddelelse igen"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Vigtig meddelelse om internetsikkerhed og Story Maps",
      "s1h1": "Esri forbedrer sikkerheden for Story Maps",
      "s1p1": "Dine Story Maps lever på nettet, og internetfællesskabet arbejder altid for at skabe og implementere bedre sikkerhed. HTTPS som giver en sikker forbindelse til indhold, der sendes over internettet, bliver den mest almindelige måde at få adgang til webindhold på. De fleste moderne browsere viser nu advarselsmeddelelser, når der bruges HTTP i stedet for HTTPS. På grund af denne nye standard anbefaler vi kraftigt, at du bruger HTTPS-links til at redigere og dele Story Maps, og at du udelukkende bruger HTTPS-URL'er, når du integrerer webindhold eller linker til billeder i i et Story Map.",
      "s1p2": "I praksis betyder det, at et Story Map og alt dets indhold (herunder billeder, lag, indlejrede apps og websteder) bør åbnes ved hjælp af links, der starter med HTTPS i stedet for HTTP. Det sikrer den bedste oplevelse for dine læsere, fordi de fleste webbrowsere vil vise, at dine historier er sikre.",
      "s2h1": "Hvad skal jeg gøre?",
      "s2p1": "Esri arbejder på at gøre overgangen nem for Story Map- forfattere og -læsere. Der er værktøjer tilgængelige nu i Story Map builders og Mine historier, der hjælper dig med at finde usikkert indhold (HTTP) i dine historier og giver anbefalinger til, hvordan du ordner det. Kontrollér dine historier for usikkert indhold og opdatér til HTTPS snarest muligt.",
      "action1": "Luk",
      "action2": "Kontrollér mine historier nu",
      "action3": "Lær mere"
    },
    "embedBar": {
      "share": "Opdatér",
      "fullScreen": "Fuld skærm",
      "enlarge": "Forstør",
      "newTab": "Åbn på en ny fane",
      "tagline": "Et Story Map",
      "exitFullScreen": "Afslut Fuld skærm-tilstand"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Kan vi spørge dig om noget? Det vil bidrage til at definere fremtiden for Story Maps.",
      "s1h1": "Del dine tanker, og påvirk fremtiden",
      "s1p1": "Dit input er vores vigtigste kilde til feedback, og når vi ved mere om dig, hjælper det os med at forbedre Story Maps. Det ville glæde os, hvis du vil deltage i denne undersøgelse, der varer tre minutter.",
      "s2p1": "Tak, fordi du bruger Esri Story Maps!",
      "action1": "Luk",
      "action2": "Deltag i undersøgelsen"
    },
    "licenseChange2018": {
      "noAccess": "Din konto (%USER_NAME%) har ikke licens til at åbne et Story Map, der ikke er offentlige. Bed din organisationsadministrator om at knytte dig til en brugertype, der omfatter Story Maps eller en add-on Essential Apps-licens."
    }
  }
});