define({
  "viewer": {
    "loading": {
      "step1": "LASTER INN HISTORIEN",
      "step2": "LASTER INN DATA",
      "step3": "INITIALISERER OMVISNINGEN",
      "loadBuilder": "BYTTER TIL MODUS FOR BYGGEVERKTØY",
      "redirectSignIn": "OMDIRIGERING TIL PÅLOGGINGSSIDEN",
      "redirectSignIn2": "(du blir omdirigert hit etter pålogging)",
      "fail": "Beklager, innlastingen av Map Tour mislyktes",
      "failButton": "Prøv på nytt"
    },
    "errors": {
      "boxTitle": "Det har oppstått en feil",
      "portalSelf": "Alvorlig feil: Kan ikke hente portalkonfigurasjon",
      "invalidConfig": "Alvorlig feil: Ugyldig konfigurasjon",
      "invalidConfigOwner": "Alvorlig feil: Ugyldig konfigurasjon (autorisert eier kreves)",
      "invalidConfigNoWebmap": "Alvorlig feil: Ugyldig konfigurasjon (webkart- eller applikasjons-ID ikke angitt i index.html)",
      "invalidConfigNoAppDev": "Det er ikke angitt en webkartapplikasjons-ID eller et webkart i URL-parameterne (?appid= eller ?webmap=). App-ID-en og webkartkonfigurasjonen i Index.html ignoreres i utviklingsmodus.",
      "createMap": "Kan ikke opprette kart",
      "invalidApp": "Alvorlig feil: Kan ikke laste inn historien",
      "noLayer": "Webkartet inneholder ikke noe gyldig datalag for Map Tour.",
      "noLayerMobile": "Byggeverktøyet for Map Tour støttes ikke med denne skjermstørrelsen. Hvis det er mulig, endrer du størrelsen på nettleseren for å få tilgang til byggeverktøyet. Du kan også lage historien på en enhet med større skjerm.",
      "noLayerMobile2": "Snu enheten i liggende retning for å bruke byggeverktøyet for Map Tour.",
      "noLayerView": "Velkommen til webprogrammet Map Tour.<br />Historien er ikke konfigurert ennå.",
      "appSave": "Feil under lagring av historien",
      "mapSave": "Feil under lagring av webkartet",
      "featureServiceLoad": "Feil ved innlasting av featuretjeneste",
      "notAuthorized": "Du har ikke tillatelse til å lese denne historien",
      "notAuthorizedBuilder": "Du har ikke tillatelse til å bruke byggeverktøyet for Map Tour.",
      "oldBrowserTitle": "Webleseren støttes ikke fullt ut",
      "noBuilderIE8": "Map Tour-byggeren støttes ikke på Internet Explorer før versjon 9.",
      "ie10Win7Explain": "Det interaktive byggeverktøyet for Map Tour støttes ikke i Internet Explorer 10 på Windows 7 når datakilden er en featuretjeneste med vedlegg. For å bruke en featuretjeneste med vedlegg må du <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuelt tvinge dokumentmodusen til å bruke Internet Explorer 9-standarder</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>nedgradere til Internet Explorer 9</a> eller oppgradere til Windows 8.",
      "oldBrowserExplain": "Denne nettleseren støtter ikke automatisk generering av miniatyrbilder fra bildene du laster inn i map tour. Du kan opprette map tour med denne nettleseren, men du må oppgi et eget miniatyrbilde for hvert av bildene du laster opp.",
      "oldBrowserExplain2": "Hvis du vil få en bedre opplevelse, kan du <a href='http://browsehappy.com/' target='_blank'>oppgradere webleseren</a> eller <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivere Google Chrome Frame for Internet Explorer</a>.",
      "oldBrowserExplain3": "Byggeverktøyet for Map Tour fungerer ikke med Internet Explorer 10 på Windows XP.",
      "oldBrowserClose": "Lukk",
      "noViewerIE2": "Du prøver å vise denne historien ved hjelp av en eldre nettleser som ikke støttes. Det kan være funksjoner som ikke fungerer eller andre uventede problemer. Vi foreslår at du oppgraderer til Internet Explorer 11 eller bruker en annen nettleser, for eksempel Chrome.",
      "noViewerIE3": "Mot slutten av 2017 vil denne historien ikke lenger lastes på denne nettleseren. I mellomtiden må du bruke en nettleser som støttes for å se denne historien.",
      "attention": "Obs!"
    },
    "mobileHTML": {
      "showIntro": "VIS TITTEL",
      "hideIntro": "SKJUL TITTEL",
      "navList": "Liste",
      "navMap": "Kart",
      "navInfo": "Medier",
      "introStartBtn": "Start"
    },
    "desktopHTML": {
      "storymapsText": "En story map",
      "builderButton": "Gå over til bygge-modus",
      "facebookTooltip": "Del på Facebook",
      "twitterTooltip": "Del på Twitter",
      "bitlyTooltip": "Få en kort kobling",
      "bitlyStartIndex": "Kobling til gjeldende sted",
      "tooltipAutoplayDisabled": "Dette er ikke tilgjengelig i automatisk avspillingsmodus",
      "autoplayLabel": "Automatisk avspillingsmodus",
      "autoplayExplain1": "Automatisk avspillingsmodus går videre i historien med gitte intervaller. Dette fungerer utmerket til kiosker eller informasjonsskjermer, men kan i andre situasjoner gjøre det vanskeligere å lese historien. Denne funksjonen støttes ikke på små skjermer.",
      "autoplayExplain2": "Når denne modusen er aktivert, vises det kontroller for å spille av/pause historien og justere navigeringshastigheten.",
      "takeTourText": "Bli med på omvisningen",
      "backToStart": "Tilbake til start"
    },
    "builderHTML": {
      "panelHeader": "KONFIGURASJON AV HISTORIE",
      "buttonSave": "LAGRE",
      "buttonSettings": "Innstillinger",
      "buttonShare": "Del",
      "buttonView": "Visningsmodus",
      "buttonItem": "Åpne webapplikasjonselementet",
      "buttonHelp": "Hjelp",
      "buttonOrganize": "Organiser",
      "buttonOrganizeAndCover": "Organiser omvisningspunkter og legg til en forside",
      "buttonAdd": "Legg til",
      "buttonImport": "Importer",
      "buttonImportDisabled": "Import er ikke tilgjengelig når du bruker bildeopplasting. Klikk på Legg til for å laste opp et bilde.",
      "dataEditionDisabled": "Redigering av data er deaktivert i denne CSV-datakilden",
      "dataSourceWarning": "Datalaget for kartomvisning er endret. Hvis ID-ene for geoobjektene er endret, må du tilbakestille rekkefølgen og skjulte punkter ved hjelp av <b>Organiser</b>. Hvis feltnavnene er endret, må du tilbakestille feltinnstillingene i <b>kategorien Data i Innstillinger</b>.",
      "organizeWarning": "Ett eller flere punkter som er lagt til utenfor det interaktive byggeverktøyet, er skjult.",
      "dataPicError0a": "Denne omvisningen har <b>%NB%</b> bilde-URLer som ikke samsvarer.",
      "dataPicError0b": "Denne omvisningen kan ha <b>%NB%</b> bilde-URLer som ikke samsvarer.",
      "dataPicError1": "Map Tour krever nå at en bilde-URL slutter med en av de følgende etternavnene: .jp(e)g, .png, .gif eller .bmp.",
      "dataPicError2": "Dette kravet påvirker ikke Map Tours som allerede er publisert. For å bruke den interaktive byggeren må du imidlertid først løse URL-problemet ved å gjøre ett av følgende:",
      "dataPicError3": "Rediger URLer",
      "dataPicError4": "Dette legger til <i>#isImage</i> helt til slutt i bilde-URL-er som ikke støttes. De fleste servere støtter tillegg til URL-er. Når du har utført denne handlingen, bør du imidlertid navigere gjennom punktene dine for å kontrollere at de oppdaterte bilde-URL-ene fungerer. Hvis alle bildene lastes inn, kan du nå lagre kartomvisningen. Hvis <b>bilder er ødelagt, lagrer du ikke kartomvisningen</b>. Da laster du i stedet inn byggeverktøyet på nytt og utfører den andre handlingen.",
      "dataPicError5": "Begrens omvisningen til bilder",
      "dataPicError6": "Dette alternativet gjør at alle URL-ene regnes som bilder, men du kan ikke legge til videoer med det interaktive byggeverktøyet. Denne handlingen kan reverseres hvis du bestemmer deg for å legge til video i fremtiden.",
      "dataPicError7": "Kartomvisningen din er begrenset til bilder, videoer kan ikke brukes. Hvis du bestemmer deg for å fjerne den begrensningen, må du kontrollere at bildene fortsatt lastes inn korrekt før du lagrer kartomvisningen. Du kan om nødvendig gjenopprette den begrensningen senere.",
      "dataPicError8": "Fjern bildebegrensning",
      "dataPicError9": "Hvis disse URL-ene peker mot videoer, kan du ignorere denne advarselen. Hvis de peker mot bilder, må du utføre en av disse to handlingene:",
      "modalCancel": "Avbryt",
      "modalApply": "Bruk",
      "organizeHeader": "Organiser omvisningen",
      "organizeGeneralCaption": "Bruk dra og slipp for å sortere omvisningspunkter",
      "organizeDelete": "Slett",
      "organizeHide": "Skjul",
      "organizeReset": "Tilbakestill rekkefølge og skjulte punkt",
      "addMaxPointReached": "Du har nådd maksimalt antall punkter som er tillatt av ikonene som er valgt, og kan ikke legge til flere omvisningspunkter.<br /><br />Vær oppmerksom på at du må laste inn historien på nytt hvis du sletter eksisterende punkter.",
      "addMaxPointReachedMobile": "Beklager, du har nådd det maksimale antallet autoriserte punkter og kan ikke legge til dette bildet.",
      "addClose": "Lukk",
      "addHeader": "Legg til et nytt omvisningspunkt",
      "addTabPicture": "Medier",
      "addTabInformation": "Informasjon",
      "addTabLocation": "Plassering",
      "addSelectCaption": "Velg eller slipp bilde",
      "addNoteVideo": "Se i Hjelp for instruksjoner om å bruke videoer",
      "addSelectCaptionNoFileReader": "Velg bilde",
      "addChangePhoto": "Endre bilde og miniatyrbilde",
      "addPictureResolutionIntro": "Bildeoppløsningen er høyere enn nødvendig:",
      "addPictureResolutionOldBrowser": "Bildeoppløsningen er høyere enn nødvendig. Få mest mulig ut av Map Tour ved å angi en oppløsning som er lavere enn %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Endre bildeoppløsningen til %RESOLUTION%",
      "addPictureResolutionKeep": "Behold den opprinnelige bildeoppløsningen på %RESOLUTION%",
      "addSelectThumbnail": "Velg miniatyrbilde",
      "addNoThumbSelected": "Du har ikke valgt noe miniatyrbilde",
      "addThumbSelected": "Valgt",
      "addCameraSettingsHeader": "KAMERAINNSTILLINGER",
      "addThumbnailHeader": "MINIATYRBILDE",
      "addLabelPicUrl": "Bilde",
      "addLabelThumbUrl": "Miniatyrbilde",
      "addTextPlaceholderUrl": "Angi en bilde-URL",
      "addTextPlaceholderUrl2": "Angi URL-adresse for en YouTube-side",
      "addTextPlaceholderUrl3": "Angi URL for Vimeo-side",
      "addTextPlaceholderUrl4": "Angi URL for innebygging av video",
      "addLabelVideo": "Video",
      "addMediaVideoOther": "Annet",
      "addMediaVideoHelp": "Kontroller URL-en, og hent standard miniatyrbilde",
      "addMediaVideoHelpTooltip1": "Kontrollen var vellykket",
      "addMediaVideoHelpTooltip2": "Kontrollen mislyktes",
      "addMediaVideoHelpTooltip4": "Finn alternativet for å bygge inn videoen, og kopier video-URL-en som finnes i koden",
      "addLabelName": "Navn",
      "addLabelDescription": "Undertekst",
      "addTextPlaceholder": "Skriv noe",
      "addLocatePlaceholder": "Finn en adresse eller et sted",
      "addPinColor": "Farge",
      "addLatitude": "Breddegrad",
      "addLongitude": "Lengdegrad",
      "addLatitudePlaceholder": "f.eks. 34.056",
      "addLongitudePlaceholder": "f.eks. -117.195",
      "addUploading": "Laster opp omvisningspunkt",
      "addSave": "Legg til omvisningspunkt",
      "addMobileUploading": "Laster opp bilde",
      "addMobileName": "Angi et navn",
      "addMobileNameMandatory": "Feil, angi et navn.",
      "addMobileError": "Beklager, noe gikk galt.",
      "settingsHeader": "Innstillinger",
      "settingsTabLayout": "Utforming",
      "settingsTabColor": "Farger",
      "settingsTabLogo": "Overskrift",
      "settingsTabFields": "Data",
      "settingsTabExtent": "Utstrekning",
      "settingsTabZoom": "Zoomnivå",
      "settingsLayoutExplain": "Velg det oppsettet du ønsker.",
      "settingsLayoutProfessional": "Tre paneler",
      "settingsLayoutModern": "Integrert",
      "settingsLayoutSidePanel": "Sidepanel",
      "settingsLayoutSelected": "Valgt utforming",
      "settingsLayoutNew": "Ny!",
      "settingsLayoutSelect": "Velg",
      "settingsLayoutNote": "Legg merke til at for punkter som bruker video, plasseres bildeteksten alltid under videoen, selv om det ikke er merket av for dette alternativet.",
      "settingsLayoutLocBtn": "Vis en 'lokaliser'-knapp",
      "settingsLayoutLocBtnHelp": "Støttes på de fleste weblesere. Vises bare når fortellingskart brukes over HTTPS. Vises ikke hvis historien er innebygd.",
      "settingsColorExplain": "Endre utseende ved å velge et forhåndsdefinert tema eller opprette ditt eget.",
      "settingsLabelColor": "Farge på topptekst, innhold og bunntekst",
      "settingsLogoExplain": "Tilpass logoen øverst (maks. 250 x 50 piksler).",
      "settingsLogoEsri": "Esri-logo",
      "settingsLogoNone": "Ingen logo",
      "settingsLogoCustom": "Tilpasset logo",
      "settingsLogoCustomPlaceholder": "Bilde-URL",
      "settingsLogoCustomTargetPlaceholder": "Gjennomklikkingskobling",
      "settingsLogoSocialExplain": "Tilpass overskriftkoblingen øverst til høyre.",
      "settingsLogoSocialText": "Tekst",
      "settingsLogoSocialLink": "Kobling",
      "settingsLogoSocialDisabled": "Administratoren har deaktivert denne funksjonen",
      "settingsDataFieldsExplain": "Velg bildenavn, tekst og fargefelter.",
      "settingsDataFieldsError": "Kan ikke finne riktig navn, tekst eller fargedata. Velg feltene som skal brukes her. Disse innstillingene kan endres senere.",
      "settingsFieldsLabelName": "Navn",
      "settingsFieldsLabelDescription": "Undertekst",
      "settingsFieldsLabelColor": "Farge",
      "settingsFieldsReset": "Tilbakestill feltvalg",
      "settingsExtentExplain": "Angi startutstrekningen for kartomvisningen på det interaktive kartet nedenfor.",
      "settingsExtentExplainBottom": "Utstrekningen du definerer, endrer kartets startutstrekning. Vær oppmerksom på at denne utstrekningen ikke brukes hvis den ikke inkluderer omvisningens første punkt. I så fall åpnes kartomvisningen sentrert på det første punktet.",
      "settingsExtentDateLineError": "Utstrekningen kan ikke være over den 180. lengdegraden",
      "settingsExtentDateLineError2": "Feil ved beregning av utstrekningen",
      "settingsExtentDrawBtn": "Tegn en ny utstrekning",
      "settingsExtentModifyBtn": "Rediger utstrekningen",
      "settingsExtentApplyBtn": "Forhåndsvis på Map Tour",
      "settingsExtentUseMainMap": "Bruk Map Tour-utstrekning",
      "settingsZoomExplain": "Angi zoom for fortellingspunkter (valgfritt).",
      "settingsLabelZoom": "Målestokk/nivå",
      "settingsZoomFirstValue": "Ingen",
      "settingsFieldError": "Velg et felt i hver liste",
      "dataTitle": "Opprett et hostet kartomvisningslag",
      "dataExplain": "Et nytt geoobjektslag opprettes for bildene og omvisningspunktene. Omvisningslaget blir ikke delt med noen med mindre du deler kartomvisningen.",
      "dataExplainPortal": "Kontakt ArcGIS-administratoren hvis geoobjektlaget ikke blir opprettet slik det skal.",
      "dataNameLbl": "Lagnavn",
      "dataFolderListLbl": "Mappe",
      "dataFolderListFetching": "Henter mapper...",
      "dataRootFolder": "Rot",
      "dataNameError": "Angi et navn for featuretjenesten",
      "dataFolderError": "Velg en gyldig mappe",
      "dataSrcContainsInvalidChar": "Navnet på featuretjenesten inneholder ett eller flere ugyldige tegn (-, <, >, #, %, :, \", ?, &, +, / eller ).",
      "dataSrvAlreadyExistsError": "Det finnes allerede en tjeneste med det navnet i organisasjonen. Velg et annet navn.",
      "dataBtnSave": "Opprett laget",
      "dataFooterProgress": "Opprettelse pågår",
      "dataFooterSucceed": "Opprettelsen er fullført. Laster inn.",
      "dataFooterError": "Opprettelsen mislyktes. Prøv på nytt.",
      "tabError": "Se etter feil i alle faner",
      "introRecordBtn": "Intro",
      "introRecordActivate": "Bruk første punkt som innledning (vises ikke i karusell)",
      "coverRecordActivate": "Bruk første punkt som forside",
      "coverBuilder": "Forsidekonfigurasjon",
      "cover": "Forside",
      "showCover": "Vis forside",
      "editCover": "Rediger forside",
      "coverNoVideo": "Video støttes ikke som forsidemedia. Velg et bilde.",
      "coverPreview": "Hvis du vil se forsiden, lagrer du fortellingen og forhåndsviser den ved hjelp av knappen Vis fortelling.",
      "thirdPartyTerms": "Når du bruker en tredjepartstjeneste, godtar du dennes tjenestevilkår: "
    },
    "addPopupJS": {
      "uploadingPicture": "Laster opp bilde",
      "uploadSuccess": "Opplastingen er fullført",
      "uploadError": "Feil under opplasting av bildet",
      "uploadError2": "Feil da geobjektet ble lagt til (ugyldig HTML-kode)",
      "notJpg": "Velg et JPEG-bilde du vil laste opp",
      "errorNoPhoto": "Velg et bilde du vil laste opp",
      "errorNoThumbnail": "Velg et miniatyrbilde du vil laste opp",
      "errorInvalidPicUrl": "Angi en gyldig bilde-URL. Begynner med https. Slutter med jpg, png, gif eller bmp. Du kan avslutte URL-en med «#isImage» for å overstyre regelen.",
      "errorInvalidThumbUrl": "Angi et gyldig miniatyrbilde (begynner med https://, slutter med jpg, png, gif eller bmp).",
      "errorInvalidVideoUrl": "Angi en gyldig video-URL (starter med https://)",
      "errorNoName": "Angi et navn for dette omvisningspunktet",
      "errorNoDescription": "Angi en tekst for dette omvisningspunktet",
      "errorNoLocation": "Angi et sted for dette omvisningspunktet"
    },
    "builderJS": {
      "noPendingChange": "Ingen ulagret endring",
      "unSavedChangeSingular": "1 ulagret endring",
      "unSavedChangePlural": "ulagrede endringer",
      "shareStatus1": "Omvisningen er ikke lagret",
      "shareStatus2": "Omvisningen deles offentlig",
      "shareStatus3": "Omvisningen deles innenfor organisasjonen",
      "shareStatus4": "Omvisningen deles ikke",
      "popoverDiscard": "Er du sikker på at du vil forkaste endringer som ikke er lagret?",
      "yes": "Ja",
      "no": "Nei",
      "popoverLoseSave": "Dersom du åpner viseren, mister du endringer som ikke er lagret",
      "ok": "Ok",
      "popoverSaveWhenDone": "Ikke glem å lagre når du er ferdig",
      "closeWithPendingChange": "Er du sikker på at du vil bekrefte handlingen? Endringene dine går tapt.",
      "gotIt": "Ok",
      "savingApplication": "Lagrer historien",
      "saveSuccess": "Historien er lagret",
      "saveError": "Lagringen mislyktes. Prøv på nytt.",
      "saveError2": "Lagring mislyktes på grunn av ugyldig HTML-kode i et navn eller en beskrivelse",
      "saveError3": "Tittelen må fylles ut",
      "dragColorPicker": "Flytt på meg<br />eller endre fargen min",
      "dataWarningExtent": "Du har data utenfor webkartets utstrekning. Disse dataene blir ikke brukt som omvisningspunkter. Endre kartets utstrekning hvis du vil bruke dem.",
      "dataWarningVisibi": "Map Tour-laget er ikke synlig med den gjeldende utstrekningen for webkartet. Bekreft at Map Tour-laget er synlig med et %MAPSIZE% stort kart.",
      "dataWarningEdit": "Rediger webkart",
      "dataWarningClose": "Lukk",
      "signIn": "Logg på med en konto på",
      "signInTwo": "for å lagre historien.",
      "switchBM": "Endre bakgrunnskart"
    },
    "organizePopupJS": {
      "messageStart": "Du har valgt å slette",
      "messageSinglePoint": "ett omvisningspunkt",
      "messageMultiPoint": "omvisningspunkter",
      "messagePermantRemove": "Dette fører til permanent fjerning av",
      "messageRecord": "posten",
      "messageRecordPlural": "poster",
      "messageConfirm": "fra databasen. Vil du fortsette?",
      "labelButtonShow": "Vis",
      "labelButtonHide": "Skjul"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Dette vil slette bildet og miniatyrbildet permanent",
      "popoverDeleteWarningThumb": "Dette vil slette miniatyrbildet permanent",
      "popoverUploadingPhoto": "Laster opp bilde og miniatyrbilde",
      "popoverUploadingThumbnail": "Laster opp miniatyrbilde",
      "popoverUploadSuccessful": "Opplastingen er fullført",
      "popoverUploadError": "Opplastingen mislyktes, prøv på nytt",
      "changePicAndThumb": "Endre bilde",
      "changeThumb": "Endre miniatyrbilde",
      "selectPic": "Endre medier",
      "selectThumb": "Endre miniatyrbilde",
      "uploadPicAndThumb": "Bruk"
    },
    "headerJS": {
      "editMe": "Rediger meg!",
      "templateTitle": "Angi tittel",
      "templateSubtitle": "Angi undertittel",
      "edit": "Rediger"
    },
    "crossFaderJS": {
      "setPicture": "Angi bildetittel",
      "setCaption": "Angi bildetekst"
    },
    "importPopup": {
      "title": "Importer",
      "prevBtn": "Bak",
      "nextBtn": "Neste"
    },
    "importPopupHome": {
      "header": "Hvor har du lagret bildene dine?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "bilder",
      "videos": "videoer",
      "disabled": "Administratoren har deaktivert denne funksjonen",
      "disabledPortal": "Dette geoobjektet krever at portalen har en hostserver. Kontakt administratoren for Portal for ArcGIS.",
      "header1": "Bildene må deles offentlig.",
      "header2": "Importen blir begrenset til første %NB1% %MEDIA%.",
      "emptyDataset": "Feil; ingen bilder funnet",
      "footerImport": "Importer",
      "selectAlbum": "Velg et offentlig album",
      "selectAlbum2": "Velg et album",
      "pleaseChoose": "Velg",
      "userLookup": "Slå opp",
      "userLookingup": "Slår opp",
      "csv": "Vist til i en CSV",
      "advanced": "Avanserte alternativer",
      "advancedScratchLbl": "Start en ny omvisning",
      "advancedScratchTip": "Opprett en tom omvisning som du legger til omvisningspunktene i. Mediene må allerede være tilgjengelige på nettet. Dette alternativet støtter ikke at du laster opp bilder",
      "advancedCSVLbl": "Importer omvisningsdata fra en CSV-fil",
      "advancedCSVTip": "Importer omvisningsinnholdet fra en CSV-fil som refererer til mediene på nettet. Dette alternativet støtter ikke at du laster opp bilder",
      "advancedCommonTip": "Det krever at bildene og videoene dine allerede er lagret online.",
      "select": "Foreta et valg",
      "locUse": "Bruk bildenes geolokasjon",
      "locExplain": "Du vil kanskje ikke bruke bildeplasseringer, ettersom de kan være overtatt fra albumet. Det fører i tilfelle til at alle får den samme plasseringen.",
      "locExplain2": "Du vil kanskje ikke bruke videoplasseringer, ettersom de kan hentes fra brukerinnstillingene. Det fører i tilfelle til at alle videoer får samme plassering."
    },
    "viewFlickr": {
      "title": "Flickr-import",
      "header": "Angi brukernavnet ditt for Flickr og velg et album eller en tagg som skal importeres.",
      "userInputLbl": "Angi et brukernavn",
      "signInMsg2": "Finner ikke bruker",
      "selectSet": "Velg et album",
      "selectTag": "eller velg en knagg",
      "footerImportTag": "Importer den valgte knaggen",
      "footerImportSet": "Importer det valgte albumet"
    },
    "viewFacebook": {
      "title": "Facebook-import",
      "header": "Godkjenn med brukerkontoen din på Facebook, eller bruk en fellesside. Private albumer kan brukes til å opprette en offentlig Map Tour som ikke krever brukergodkjenning via Facebook. Det gjør det mulig å holde kommentarer og likes privat.",
      "leftHeader": "Facebook-bruker",
      "rightHeader": "Facebook-side",
      "pageExplain": "En Facebook-side er for et offisielt merke, et produkt eller en kjendis, for eksempel <b>esrigis</b>. Du finner navnet på siden etter første / i sidens URL-adresse.",
      "pageInputLbl": "Angi et sidenavn",
      "lookupMsgError": "Finner ikke siden"
    },
    "viewPicasa": {
      "title": "Import fra Google+",
      "header": "Skriv inn e-postadressen eller ID-en din.",
      "userInputLbl": "E-postadresse eller Picasa-/Google+-ID",
      "signInMsg2": "Finner ikke kontoen",
      "signInMsg3": "Ingen offentlige album",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Les mer</a>",
      "howToFind2": "Kopier tallene mellom første og andre / på en tilfeldig side på Picasa"
    },
    "viewCSV": {
      "title": "CSV-import",
      "uploadBtn": "Velg eller dropp en CSV-fil",
      "resultHeaderEmpty": "CSV-filen er tom",
      "resultHeaderSuccess": "%NB_POINTS% punkter ble lastet inn",
      "resultHasBeenLimited": "Importen er blitt begrenset til de første %VAL1% punktene av %VAL2% for å overholde grensen på %VAL3% punkter per omvisning",
      "browserSupport": "Du bruker en nettleser som ikke støttes. For å bruke en CSV må du <a href='http://browsehappy.com/' target='_blank'>oppgradere nettleseren</a> eller bruke visningsprogrammet for webkart på ArcGIS.com (se Hjelp).",
      "errorLatLng": "Finner ikke bredde- og lengdegradfeltene. Mulige verdier for breddegrad er: <i>%LAT%</i> og for lengdegrad: <i>%LONG%</i>.",
      "errorFieldsExplain": "Innlastingen mislyktes ettersom følgende obligatoriske felter ikke ble funnet",
      "errorFieldsName": "<b>Navn</b> mulige verdier er: %VAL%",
      "errorFieldsDesc": "<b>Beskrivelse</b> mulige verdier er: %VAL%",
      "errorFieldsUrl": "<b>Bilde-URL</b> mulige verdier er: %VAL%",
      "errorFieldsThumb": "<b>URL-adresse til miniatyrbilde</b> mulige verdier er: %VAL%",
      "errorFields2Explain": "Innlastingen mislyktes ettersom CSV-filen ikke bruker samme attributter som laget, for følgende attributter",
      "errorFields2Name": "<b>Navn</b> bruk %VAL1% i stedet for %VAL2%",
      "errorFields2Desc": "<b>Beskrivelse</b> bruk %VAL1% i stedet for %VAL2%",
      "errorFields2Url": "<b>Bilde-URL</b> bruk %VAL1% i stedet for %VAL2%",
      "errorFields2Thumb": "<b>URL-adresse til miniatyrbilde</b> bruk %VAL1% i stedet for %VAL2%",
      "resultFieldsAll": "Alle attributter er blitt importert",
      "resultFieldsNotAll": "Følgende attributter er ikke blitt importert fordi de ikke finnes i kartlaget",
      "resultFieldsNotAll2": "Følgende attributter er blitt importert",
      "footerNextBtnResult": "Importer til webkart",
      "footerProgress": "Import pågår",
      "footerSucceed": "Import fullført. Laster inn"
    },
    "viewYoutube": {
      "title": "YouTube-import",
      "header": "Oppgi et brukernavn på YouTube for å finne videoer som er delt offentlig.",
      "pageInputLbl": "Angi et YouTube-brukernavn",
      "lookupMsgError": "Finner ikke bruker",
      "howToFind": "Slik finner du et YouTube-brukernavn",
      "howToFind2": "Brukernavnet vises under videoer",
      "found": "Funnet",
      "noData": "Finner ingen offentlige videoer"
    },
    "viewGeoTag": {
      "title": "Velg og finn bildene/videoene dine",
      "header": "Lokaliserte elementer blir importert. Klikk på ikke-lokaliserte elementer du vil importere, for å finne dem.",
      "headerMore": "Hjelp",
      "headerExplain": "Når du klikker på <b>Importer</b>-knappen, importeres bare bilder eller videoer som er oppført i kategorien <b>Lokalisert</b>.<br><br>Informasjon om geolokasjon som er lagret sammen med bildene eller videoene, importeres automatisk hvis den er tilgjengelig. Alle elementer uten geolokasjon føres opp i kategorien <b>Skal lokaliseres</b>. For å finne et element som er oppført i den kategorien, kan du klikke på det og deretter klikke på ønsket lokasjon på kartet.<br><br>Hvis du vil fjerne et element fra kategorien <b>Lokalisert</b> slik at det ikke blir importert, klikker du på knappen Ikke importer, som du får se når du fører markøren over det elementet.<br><br>Tips: Sjekk personverninnstillingene for kontoen din hvis informasjonen om geolokasjon på dine egne medier ikke blir importert. Kontroller for eksempel at EXIF-data ikke er skjult i innstillingene for Flickr-kontoen din. Og hvis Flickr-personverninnstillingen for å importere EXIF-data for nye opplastinger er slått av (standardinnstillingen), blir ikke geolokasjoner for bildene dine lagret i Flickr med mindre du laster opp bildene på nytt eller angir manuelt hvor de skal plasseres i Flickr.",
      "leftPanelTab1": "For å finne",
      "leftPanelTab2": "Funnet",
      "clickOrTap": "Klikk på kartet for å finne",
      "clearLoc": "Fjern plasseringer",
      "clickDrop": "Ikke importer",
      "footerImport": "Importer",
      "footerProgress": "Import pågår",
      "footerSucceed": "Import fullført. Laster inn ...",
      "loading": "Laster inn",
      "error": "Importen av bildenes geolokasjon mislyktes, geolokasjonene er blitt ignorert."
    },
    "initPopup": {
      "title": "Velkommen til byggeverktøyet for Map Tour",
      "prevBtn": "Tilbake",
      "nextBtn": "Neste"
    },
    "initPopupHome": {
      "header1": "Hvor er bildene eller videoene dine?",
      "header2": "Denne assistenten hjelper deg med å bygge en Map Tour fra bilder som allerede er lagret online, eller den importerer dem til kontoen din på ArcGIS Online for Organizations.",
      "title1": "De er allerede online",
      "title2": "Jeg må laste opp bildene mine",
      "hostedFSTooltip": "Last opp bildene dine, og lagre dem i omvisningen (støtter ikke video).",
      "hostedFsNA": "Du må være en utgiver eller ha en annen rolle med rettigheter til å publisere hostede geoobjektslag. Kontakt ArcGIS-administratoren din.",
      "hostedFsNA2": "Kun tilgjengelig med et ArcGIS Online-abonnement. <a href='%LINK%'>Registrer deg og få en gratis prøveversjon</a>",
      "footer1": "Når du er ferdig, må du ikke glemme å dele Map Tour med publikum via  siden for programelementer.",
      "footer3": "Last ned CSV-malen",
      "footer4": "\"Lagre som\" hvis det ikke lastes ned",
      "footer4bis": "Bruk høyreklikk og \"Lagre som\" hvis nedlastingen ikke startes",
      "footer5": "Få mer informasjon",
      "footerProgress": "Opprettelse pågår",
      "footerSucceed": "Opprettelsen er fullført. Laster inn ..."
    },
    "helpPopup": {
      "title": "Hjelp",
      "close": "Lukk",
      "tab1": {
        "title": "Innledning",
        "moreInfo": "For mer informasjon",
        "infoSites": "Gå til <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>kartomvisningsområdet</a> på  <a href='https://storymaps.arcgis.com' target='_blank'>nettstedet for Esri Story Maps.</a>",
        "mtFAQ": "Se <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Vanlige spørsmål om kartomvisning.</a>",
        "myStories": "Du kan administrere kartomvisningene og sjekke om de inneholder feil, under <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Mine fortellinger</a> på nettstedet.",
        "div1": "Map Tour-malen er utarbeidet for å presentere geografisk informasjon i de tilfellene der fortellingen du vil formidle, har et sterkt fotografisk- eller mediaelement.",
        "div2": "Malen produserer et tiltalende og brukervennlig webprogram som gjør at du kan presentere et lite sett av steder på et kart i nummerert rekkefølge, som brukerne kan bla gjennom. Malen er beregnet for bruk i alle weblesere og på alle typer enheter, også smarttelefoner og nettbrett.<br /><br />",
        "div42": "Hvis du vil se eksempler på omvisninger som andre brukere lager, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>går du til galleriet</a> på <a href='https://storymaps.arcgis.com/' target='_blank'>nettstedet for Story Maps </a>. Du kan også følge oss på Twitter på <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Vi vil gjerne høre fra deg! Du kan fortelle om problemer du har støtt på, og nye funksjoner du trenger, i Story Maps-forumet på <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet.</a>"
      },
      "tab2": {
        "title": "Data",
        "div1": "Det viktigste å tenke på når du skal bygge en kartomvisning, er hvor du skal lagre bildene dine. Kartomvisningen kan bruke bilder som er lagret i bildedelingstjenester, på en webserver eller som du laster opp fra en disk.",
        "div1a": "Se den siste delen av denne fanen for detaljer om støttede bilde- og videoformater.",
        "div2": "Det interaktive verktøyet gir deg to alternativer for bildebehandling i Map Tour:",
        "div3": "<ul><li>Du kan bruke <b>bilder som allerede er lagret på nettet</b>, for eksempel bilder i Flickr eller Google+, eller bilder du har lagret på din egen webserver. Disse bildene refereres til med URL-adresser i kartomvisningen.</li><li>Du kan også <b>laste opp bilder fra datamaskinen</b> direkte til kartomvisningen. Dette opplastingsalternativet krever at du har et ArcGIS-abonnement, og at du har utgiver- eller administratorrettigheter fordi det automatisk opprettes en hostet geoobjektstjeneste der bildene lagres som vedlegg.</li></ul>",
        "div4": "De viktigste brukertilfellene er:",
        "div4b": "<b>Bildene dine er ikke hostet</b> ennå, og du har et ArcGIS-abonnement: Det beste er å bruke en hostet geoobjektstjeneste. I likhet med offentlige bildedelingstjenester optimaliserer vi bildene slik at de lastes raskt, og du får tilgang til alle funksjonene for administrasjon og databehandling på ArcGIS-plattformen.",
        "div5": "<b>Du er ikke medlem av en organisasjon</b>: Du må først laste opp bildene dine på et bildedelingsområde eller på din egen webserver. Veiviseren gir deg deretter hjelp til å bruke disse bildene, som fortsatt blir liggende på den opprinnelige plasseringen.",
        "div6": "<b>Du prøver å gjenbruke en eksisterende featuretjeneste</b> der bildene dine er lagret som vedlegg, eller som refererer til eksterne bilder: Les det mer utfyllende avsnittet nedenfor.",
        "div7": "<b>Du bruker en tidligere versjon av</b> Map Tour-malen og har allerede en CSV som refererer til bildene og miniatyrbildene dine: Du kan importere den og forbedre dataene. Byggeren støtter bare CSV som bruker attributter for bredde- og lengdegrader; adressebasert CSV kan fortsatt brukes gjennom webkartet (se avsnitt nedenfor).",
        "div8": "Importere fra bildedelingstjenester online",
        "div9a": "Facebook-støtte har blitt avviklet, ${learn}.",
        "learn": "få mer informasjon",
        "div9": "Importoperasjonen refererer til bilder som allerede er vertsbaserte, ved å lagre URL-adressene i en samling av webkartfunksjoner. Bildene lagres ikke i ArcGIS Online. Hvis driftingen av bildene avbrytes, blir de ikke lenger tilgjengelige i kartomvisningen og et \"Bilde ikke tilgjengelig\"-bilde blir brukt. Det avhenger av tjenesteleverandøren om kartomvisningen importerer bildenes navn, beskrivelse og plassering, eller ikke. De attributttene er lagret i webkartet, og eventuelle redigeringer av online-tjenestene gjenspeiles ikke i kartomvisningen.",
        "div10": "Lagre bildene på en webserver",
        "div11": "Hvis du velger å hoste bildene på din egen webserver (i stedet for å ha tilgang til bilder i Flickr eller Google+, eller laste dem opp direkte i omvisningen din), må du opprette miniatyrer av bildene manuelt. Hvis du bruker bilder med maksimal oppløsning til miniatyrbildene, reduseres ytelsen. Se <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>Vanlige spørsmål</a> for tips om tilpasning av størrelse hvis du vil ha tilgang til bildene direkte på nettet via URL-er.",
        "div12": "Bruke eksisterende GIS-data",
        "div13": "Alle geoobjektstjenester, CSV-filer eller shapefiler som inneholder punkter, kan brukes som datakilde for kartomvisningen forutsatt at de inneholder de feltene som applikasjonen forventer. Du må legge dem til som et lag i et ArcGIS-webkart og deretter dele kartet ved å opprette en kartomvisning.",
        "div14": "Støttede verdier for feltnavn er (skiller ikke mellom små og store bokstaver):",
        "div151": "Navn",
        "div152": "Beskrivelse",
        "div153": "Bilde",
        "div154": "Miniatyrbilde",
        "div155": "Farger ",
        "div16": "Hvis programmet ikke finner felter som samsvarer ved å bruke en featuretjeneste, vil visningsprogrammet ikke fungere før du har konfigurert feltene som skal brukes, ved hjelp av byggeverktøyet. CSV- og shapefillag som er lagt til webkartet, må inneholde alle obligatoriske felter for at byggeverktøyet skal fungere.",
        "div162": "Når du bruker en featuretjeneste som lagrer bildene som vedlegg, <b>brukes bare geoobjektene med to vedlegg</b>. Det første vedlegge definerer hovedbilde, mens det andre vedlegget definerer miniatyrbildet.",
        "div17": "Feltene Bilde og Miniatyrbilde er obligatoriske for featuretjenester uten vedlegg, og valgfrie (men anbefales sterkt) for featuretjenester med vedlegg. Hvis vedlegg er aktivert for tjenesten din, lar byggeverktøyet deg laste opp bilder som vedlegg. Hvis ikke kan du bare redigere bildet og miniatyrbildet via URL-adressen.",
        "div172": "Når de er til stede, brukes bilde- og minatyrbildefeltene alltid, og vedleggene til featuretjenesten blir ikke søkt opp.",
        "div173": "Eksempel-CSV- og shapefiler kan lastes ned fra",
        "div174": "Se <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>Vanlige spørsmål</a> hvis du vil vite mer om bruken av eksisterende GIS-data.",
        "div18": "Opprette en administrert (hosted) featuretjeneste fra CSV eller shapefil",
        "div19": "Når du oppretter en administrert (hosted) featuretjeneste fra en CSV- eller shapefil, er vedlegg som standard ikke aktivert. Du kan aktivere dem ved å åpne detaljsiden for featuretjenester og klikke på den lille pilen i lagdelen for å vise alternativet. Kartomvisningen fortsetter å bruke de bildene og miniatyrbildene som du har referert til gjennom attributter. Hvis du heller vil laste opp bildene som vedlegg til en featuretjeneste, kan du gjøre det ved hjelp av to knapper på bildepanelet (Endre bilde og Endre miniatyrbilde).",
        "div20": "Bildeformater og videoer som støttes",
        "div21": "Hvis du bruker Flickr eller Google+ for å få tilgang til bilder, åpner kartomvisningen automatisk de aktuelle bildene som .jpg-filer. Hvis du laster opp bilder i verktøyet for kartomvisning, må bildene være i formatet .jpg eller .jpeg. Hvis du viser til bilder direkte på nettet via URL-ene deres, er de støttede bildeformatene .jpg, .jpeg, .png, .gif og .bmp. YouTube-videoer støttes alltid direkte.",
        "div22": "Map Tour-malen inkluderer ingen videospiller, så du må bruke den eksterne videospilleren fra videotjenesten du foretrekker (finn alternativet for å bygge inn videoen, og kopier URLen som gis i den koden som oppgis). Hvis du vil drifte videoen selv, kan du opprette en HTML-side som inneholder en videospiller som <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Den interaktive byggeren har ingen dialog for å ta med video ved bruk av featuretjenester med vedlegg, men det er mulig å gjøre det ved å redigere dataene utenfor den interaktive byggeren. I arcgis.com-kartvisningen kan du endre bildefeltene slik at de peker mot en ekstern video og legge til en egen parameter til slutt i URLen (#isVideo), slik at mediene dine regnes som en video.",
        "div24": "Merk at du fortsatt må ha to gyldige bildevedlegg, ellers blir ikke punktet brukt. Det er ikke mulig å bruke videoer når du bruker featuretjenestevedlegg, uten bilde- og miniatyrbildefeltene."
      },
      "tab3": {
        "title": "Tilpasning",
        "div1": "Byggeverktøyet inneholder flere alternativer for tilpasning, som er tilgjengelige via knappen INNSTILLINGER i toppanelet. Hvis du ikke finner alternativet du forventer, leverer vi også en nedlastbar versjon som du kan distribuere på din egen webserver og forbedre slik du ønsker.",
        "div2": "Vi anbefaler å bruke den driftede (hostede) versjonen, med mindre:",
        "div3": "<li>Den ikke tilbyr en grensesnittilpasning som du gjerne vil ha, for eksempel å kunne bruke et bakgrunnsbilde i overskriften.</li><li>Du er en utvikler og ønsker å forbedre programmet.</li>",
        "div4": "Du kan konfigurere den nedlastbare versjonen gjennom en webkart- eller webkartapplikasjons-ID. De viktigste bruksområdene er:",
        "div41": "Du bygger Map Tour ved å bruke den interaktive byggeren i det driftede (hostede) miljøet, og konfigurerer malen med webkartapplikasjons-identifikatoren. Innstillingene du har definert med den interaktive byggeren, blir brukt.",
        "div42": "Du bygger webkartet utenfor den interaktive byggeren og konfigurerer malen med webkartidentifikatoren. Du må lese dokumentasjonen for å se hvordan du skal konfigurere malen.",
        "div43": "Merk at den interaktive byggeren er tilgjengelig i den nedlastbare versjonen, men med noen tekniske begrensninger i nettlesere som Internet Explorer som er eldre enn versjon 10.",
        "div5": "Gå til<a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub-prosjektsiden</a> for å laste ned den nyeste versjonen av malen og lære mer om hvordan den brukes."
      },
      "tab4": {
        "title": "Tips",
        "div0": "Støttede nettlesere",
        "div0a": "Map Tour-viseren støttes på IE8+. Den interaktive byggeren støttes på IE9+. Vi tester aktivt i alle større nettlesere, men hvis du opplever problemer, anbefaler vi at du bruker Chrome.",
        "div0b": "Hvis du opplever problemer, må du varsle oss. I mellomtiden kan du begrense samhandlingen med byggergrensesnittet ved å bygge Map Tour med CSV-malen.",
        "div1": "Bilder",
        "div2": "Selv om bilder med ulike størrelser, former og formater kan brukes i samme kartomvisning, anbefaler vi at du bruker liggende format fremfor stående format. Bilder med størrelsesforholdet 4:3 passer best. I oppsettet med tre paneler og integrert oppsett der bildeteksten overlapper bildet, kan bildet bli skjult av bildeteksten om bildet har stående format. I oppsettet med tre paneler eller integrert oppsett anbefaler vi at det brukes samme størrelse og form for alle bildene hvis det er mulig. Det gjør at brukeren ikke distraheres av bilder i ulike størrelser under omvisningen.",
        "div2a": "Vi anbefaler en maksimal bildestørrelse på 1000 pikslers bredde x 750 pikslers høyde for hovedbildene og 140 x 93 for miniatyrbildene.",
        "div3": "Formatere underteksten med HTML-koder",
        "div4": "Du kan angi HTML-koder i bildetekstene for å definere formatering og koblinger. Disse kodene legger for eksempel inn en grønn hyperkobling:",
        "div4aa": "<b>Lag en forside for omvisningen i sidepanelene</b><br>Oppsettet med sidepaneler støtter en valgfri forside som gjør at du kan tiltrekke publikums oppmerksomhet med et flott bilde i fullskjermvisning. Legg til alle eller noen av punktene i omvisningen før du konfigurerer forsiden for en omvisning med sidepaneler. Klikk deretter på Organiser-knappen, og kontroller i den viste dialogboksen at omvisningspunktet du vil bruke til å definere forsiden, er det første punktet i omvisningen. Klikk deretter på avmerkingsboksen for «Bruk det første punktet som forside» i dialogboksen. Navnet på det første punktet i omvisningen blir tittelen som vises på forsiden, bildeteksten for det samme punktet blir undertittel, og bildet av punktet blir brukt som forsidebilde. Video er ikke støttet på forsiden. Se <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>Vanlige spørsmål</a> hvis du vil vite mer.</a>",
        "div4a": "Gi omvisningen en god undertittel",
        "div4b": "Ta deg tid til å gi omvisningen en fengende undertittel. Undertittelen er viktig for å gjøre folk interessert i omvisningen og fortelle dem hva de vil oppdage underveis. Det er også en god anledning til å fortelle publikum om fylket eller landet som omvisningen handler om. Du bør for eksempel ikke ta for gitt at folk vet hvor byen eller stedet for omvisningen ligger. Pass på at undertittelen ikke blir for lang. Hvis du ikke kommer på en god undertittel, lar du den stå tom. Til forskjell fra oppsettet med tre paneler og integrert oppsett støtter ikke oppsettet med sidepaneler en undertittel i toppteksten. Hvis du bruker forsidealternativet i oppsettet med sidepaneler, vises bildeteksten til det første punktet i omvisningen på forsiden og fungerer dermed som undertittel på omvisningen.",
        "div5": "Støttelag",
        "div6": "Du kan legge til ekstra støttelag i kartet for å gi kontekst i kartomvisningen. Disse lagene kan inneholde andre geografiske objekter du vil at kartet skal vise i tillegg til kartomvisningspunktene, for eksempel et studieområde eller en gå- eller kjørerute som kobler omvisningspunktene sammen. Kartomvisningsmalen viser disse ekstra støttelagene ved å bruke symbolene du angir i webkartet, men eventuelle popuper som er angitt for lagene, er ikke støttet. Hvis du vil legge til et støttelag i omvisningen, lagrer du arbeidet og lukker byggeverktøyet for kartomvisning. Åpne deretter webkartet som skal brukes i omvisningen. Du finner dette i ArcGIS Mitt innhold eller via Mine fortellinger-delen på Story Map-nettsiden.",
        "div7": "Gjør omvisningen kort og hyggelig",
        "div8": "Det er en grense på 99 punkter per omvisning. De fleste omvisninger vil selvsagt være atskillig kortere enn det. Ikke forvent at publikum har lyst til å gå gjennom altfor mange omvisningspunkter. Du synes kanskje emnet er uendelig fascinerende, men det er ikke sikkert at alle andre synes det samme!",
        "div10": "Innbyggingsmetode",
        "div11": "Hvis du vil bygge inn malen på et annet webområde ved hjelp av en iframe, fjerner du toppteksten ved å legge til den valgfrie parameteren \"embed\" på slutten av URL-en.",
        "div12": "Unngå å bruke en smal iFrame-bredde som får kartomvisningen til å bytte til det berøringsbaserte oppsettet for små skjermer, som er den samme visningen omvisningen bruker på mobile enheter. Når du bygger inn en kartomvisning, anbefaler vi alltid å opprette en kobling ved siden av den innebygde omvisningen slik at brukerne kan starte omvisningen i fullskjermmodus. Det er mer brukervennlig."
      },
      "tab5": {
        "title": "Publisere",
        "div1": "Ikke glem å dele Map Tour via DEL-knappen eller siden for programelementer i ArcGIS Online når du er ferdig.",
        "div2a": "Dele Map Tour via byggeverktøyet",
        "div2b": "DEL-knappen vil oppdatere programmet og webkartelementene. Hvis du har lagret Map Tour-dataene i et element i featuretjenesten, blir de også oppdatert. Hvis du har lagt til andre lag via kartvisningsprogrammet på ArcGIS.com, oppdateres de ikke. Dette kan føre til at omvisningen ikke deles som forventet. Elementer som allerede har de obligatoriske rettighetene (eller flere), oppdateres ikke.",
        "div2c": "Dele Map Tour via ArcGIS Online",
        "div2d": "Når du deler programmet via ArcGIS Online, vil det om nødvendig be deg om å oppdatere eventuelle tilknyttede ressurser (webkart, featuretjeneste, dekorasjonslag) som ikke blir delt på samme måte. Hvis kartomvisningen er offentlig og én av ressursene dine ikke deles med publikum, blir brukerne videresendt til påloggingssiden for ArcGIS Online.",
        "div3t": "Sikkerhet for featuretjenester",
        "div3a": "Hvis du bruker en administrert (hosted) featuretjeneste som er opprettet med byggeverktøyet for Map Tour, tar programmet hånd om sikkerheten til tjenesten, og du vil fortsatt være den eneste med redigeringsrettigheter, selv om du har delt tjenesten offentlig.",
        "div3t2": "Før du deler Map Tour med publikum",
        "div3": "Kontroller at omvisningen fungerer godt også når du ikke er logget på kontoen din på ArcGIS.com. URL-en du bruker, bør ikke videresende til en påloggingsside eller til byggermodus.",
        "div4": "Det er lurt å se hvordan kartomvisningen tar seg ut på en iPad i liggende retning for å være sikker på at den ser bra ut på denne populære enheten. Da kan du se om underteksten dekker for mye av bildene. Du kan også se om undertittelen passer og ikke er så lang at den blir kuttet.",
        "div5a": "Anbefaling for søk",
        "div5b": "For å gjøre det enklere å finne din Map Tour ved søk i ArcGIS Online, anbefaler vi å legge til knaggen 'story map' på omvisningens side for programelementer  (ikke siden for webkartelementer), sammen med knagger som navnet på fylket eller kommunen der omvisningen foregår, navnet på landet hvis det er utenfor USA, og tematiske knagger som 'offentlig kunst', 'turistguide' eller 'historiske steder'. Slike knagger hjelper oss hos Esri å finne gode nye eksempler på omvisninger vi kan vise frem i galleriene og promotere på sosiale medier. Vi anbefaler deg også å laste opp et fint miniatyrbilde på siden for programelementer, for eksempel et lite skjermbilde av omvisningen eller et av bildene den inneholder. Dette bildet brukes automatisk hvis omvisningen legges inn i et galleri på  ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Omvisningen er lagret",
      "manageStory": "Administrer historien",
      "manageStoryA1": "Tips: Du kan bruke %LINK1% blant annet til å sjekke om det er feil i fortellingen, endre måtene den deles på, og sørge for at den vises på en god måte i sosiale medier. Les mer om My Stories %LINK2%.",
      "manageStoryA1V1": "Mine historier",
      "manageStoryA1V2": "her",
      "shareTitle": "Dele Map Tour",
      "sharePrivateHeader": "Map Tour er ikke delt. Har du lyst til å dele den?",
      "sharePrivateBtn1": "Del offentlig",
      "sharePrivateBtn2": "Del med min organisasjon",
      "sharePrivateProgress": "Deling pågår ...",
      "sharePrivateErr": "Deling mislyktes. Prøv på nytt, eller",
      "sharePrivateOk": "Delingen er oppdatert, laster inn ...",
      "sharePreviewAsUser": "Forhåndsvisning",
      "shareHeader1": "Din Map Tour er<strong>offentlig tilgjengelig</strong>.",
      "shareHeader2": "Din Map Tour er tilgjengelig for medlemmer av din organisasjon (krever pålogging).",
      "shareLinkHeader": "Dele Map Tour",
      "shareLinkOpen": "ÅPNE",
      "shareA1": "Bruk %SHAREIMG% på <a href='%LINK1%' target='_blank'>siden for applikasjonselementet</a>. Hvis du vil også ønsker å oppheve delingen av webkartet, bruker du <a href='%LINK2%' target='_blank'>siden for webkartet</a>.",
      "shareWarning": "Deling av %WITH% er deaktivert fordi du ikke eier <a href='%LINK%' target='_blank'>webkartet</a>.",
      "shareWarningWith1": "offentlig",
      "shareWarningWith2": "offentlig og med organisasjonen",
      "viewStory": "Vis historie"
    },
    "locator": {
      "error": "Lokasjon ikke tilgjengelig"
    },
    "saveErrorSocial": {
      "title": "Oppdater deling på sosiale medier",
      "panel1": "Historien vises på en bedre måte på sosiale medier, men tittelen på ArcGIS-webapplikasjonselementet er ikke den samme som historietittelen.",
      "panel1tooltip": "Når du angir en tittel, et sammendrag og et miniatyrbilde, vil historien se slik ut:",
      "panel2": "Hvilken tittel vil du bruke på sosiale medier:",
      "panel2q1": "Historietittel (anbefales)",
      "panel2q1tooltip": "Når du velger dette alternativet, endres elementtittelen slik at den er identisk med historietittelen og andre endringer i byggeverktøyet synkroniseres.",
      "panel2q2": "Elementtittel",
      "panel3": "Hvis du vil forbedre hvordan historien vises på sosiale medier, bruker du ${MYSTORIES} til å legge til et sammendrag og et miniatyrbilde.",
      "panel4": "Ikke vis denne advarselen igjen for denne historien",
      "mystories": "Mine historier",
      "btnSave": "Lagre"
    },
    "bannerNotification": {
      "learnMore": "Få mer informasjon",
      "close": "Lukk",
      "dontShowAgain": "Ikke vis denne meldingen igjen"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Viktig informasjon om websikkerhet og fortellingskart",
      "s1h1": "Esri forbedrer sikkerheten for fortellingskart",
      "s1p1": "Fortellingskartene lever på nettet, og Internett-fellesskapet jobber hele tiden med å forbedre sikkerheten. HTTPS, som gir en sikker forbindelse til innhold som sendes over Internett, begynner å bli den vanligste måten å få tilgang til Internett-innhold på. De fleste moderne nettlesere viser en advarsel når det brukes HTTP i stedet for HTTPS. Som følge av denne nye standarden anbefaler vi på det sterkeste å bruke HTTPS-koblinger når du utarbeider og deler fortellingskart, og bare bruke HTTPS-URL-er når du bygger inn webinnhold eller oppretter koblinger til bilder i et fortellingskart.",
      "s1p2": "Det betyr at du får tilgang til et fortellingskart og alt innholdet i det (inkludert bilder, lag, innebygde apper og nettsteder) ved hjelp av koblinger som begynner med HTTPS i stedet for HTTP. Dette gir leserne dine den beste opplevelsen siden de fleste nettleserne viser at fortellingene dine er sikre.",
      "s2h1": "Hva må jeg gjøre?",
      "s2p1": "Esri arbeider for at det skal bli en enkel overgang for alle som lager og bruker fortellingskart. Byggeverktøyene for Story Map og My Stories inneholder nå verktøy som hjelper deg med å finne usikkert innhold (HTTP) i fortellingene dine og gir råd om hvordan du ordner dette. Kontroller om fortellingene dine har usikkert innhold, og oppdater til HTTPS så snart som mulig.",
      "action1": "Lukk",
      "action2": "Kontroller mine fortellinger nå",
      "action3": "Mer informasjon"
    },
    "embedBar": {
      "share": "Del",
      "fullScreen": "Fullskjerm",
      "enlarge": "Forstørr",
      "newTab": "Åpne i ny fane",
      "tagline": "Et fortellingskart",
      "exitFullScreen": "Avslutt fullskjerm"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Kan vi spørre deg om noe? Det vil bidra til å forme fortellingskartenes fremtid.",
      "s1h1": "Si hva du tenker, bidra til å forme fremtiden",
      "s1p1": "Du er vår viktigste kilde til tilbakemeldinger, og når vi vet mer om deg, kan vil lettere forbedre fortellingskartene. Vi setter stor pris på om du kan avse tre minutter til å delta i denne undersøkelsen.",
      "s2p1": "Nok en gang takk for at du bruker Esri Story Maps!",
      "action1": "Lukk",
      "action2": "Ta undersøkelsen"
    }
  }
});