define(
({
		viewer: {
			loading: {
				step1: "CARREGANDO APLICATIVO",
				step2: "CARREGANDO DADOS",
				step3: "INICIALIZANDO O PERCURSO",
				loadBuilder: "TROCANDO PARA MODO DO CONSTRUTOR",
				fail: "Desculpe, falha ao carregar Apresentação do Mapa",
				failButton: "Tentar Novamente"
			},
			errors: {
				boxTitle: "Ocorreu um erro",
				invalidConfig: "Erro fatal: configuração inválida",
				invalidConfigOwner: "Erro fatal: Configuração inválida (proprietário autorizado exigido)",
				invalidConfigNoWebmap: "Erro fatal: Configuração inválida (mapa da web e proprietário autorizado exigidos)",
				createMap: "Não foi possível criar o mapa",
				invalidApp: "Erro fatal: O aplicativo não pode ser carregado",
				noLayer: "O mapa da web não contém uma camada de dados válida de Apresentação do Mapa.",
				noLayerMobile: "Bem-Vindo ao aplicativo da web de Apresentação do Mapa. O aplicativo não está configurado. O construtor de Apresentação do Mapa não tem suporte em dispositivos móveis.",
				noLayerView: "Bem-Vindo ao aplicativo da web de Apresentação do Mapa.<br />O aplicativo não está configurado ainda.",
				appSave: "Erro ao salvar o aplicativo da web",
				mapSave: "Erro ao salvar o mapa da web",
				featureServiceLoad: "Erro ao carregar serviço da feição",
				notAuthorized: "Você não está autorizado para configurar este aplicativo",
				oldBrowserTitle: "Navegador sem suporte completo",
				noBuilderIE8: "O construtor de Apresentação do Mapa não tem suporte no Internet Explorer anterior à versão 9.",
				ie10Win7Explain: "O construtor de Apresentação do Mapa interativo não tem suporte no Internet Explorer 10 do Windows 7 quando a fonte de dados é um Serviço da Feição com anexos. Para utilizar um Serviço da Feição com anexos, você tem que <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>forçar manualmente o modo de documento para os padrões do Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>migrar para o Internet Explore 9</a> ou atualizar para Windows 8.",
				oldBrowserExplain: "Este navegador não suporta geração automática de miniaturas a partir de imagens que você carregou em sua apresentação do mapa. Você pode criar uma  apresentação do mapa utilizando este navegador, mas você terá que fornecer uma imagem de miniatura separada para cada uma das imagens que você carregar.",
				oldBrowserExplain2: "Para melhorar sua experiência, <a href='http://browsehappy.com/' target='_blank'>atualize seu navegador</a> ou <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>ative o Google Chrome Frame para Internet Explorer</a>.",
				oldBrowserExplain3: "O construtor de Apresentação do Mapa não funciona com Internet Explorer 10 no Windows XP.",
				oldBrowserClose: "Fechar"
			},
			mobileHTML: {
				showIntro: "MOSTRAR TÍTULO",
				hideIntro: "OCULTAR TÍTULO",
				navList: "Lista",
				navMap: "Mapa",
				navInfo: "Info",
				introStartBtn: "Iniciar"
			},
			desktopHTML: {
				storymapsText: "Um mapa histórico",
				builderButton: "Trocar para modo do construtor"
			},
			builderHTML: {
				panelHeader: "CONFIGURAÇÃO DO APLICATIVO",
				buttonSave: "SALVAR",
				buttonDiscard: "CANCELAR",
				buttonSettings: "Configurações",
				buttonView: "Modo de visualização",
				buttonHelp: "Ajuda",
				buttonOrganize: "Organizar",
				buttonAdd: "Adicionar",
				buttonImport: "Importar",
				buttonImportDisabled: "A operação Importar não fica disponível ao utilizar um Serviço da Feição com anexos",
				modalCancel: "Cancelar",
				modalApply: "Aplicar",
				organizeHeader: "Organizar o percurso",
				organizeGeneralCaption: "Utilize arrastar e soltar para classificar os pontos de percurso",
				organizeDelete: "Excluir",
				organizeHide: "Ocultar",
				addMaxPointReached: "Você alcançou o número máximo de pontos autorizados pelo conjunto de ícones e não pode adicionar outro ponto do percurso.<Br /><br />Observe que se você excluir pontos existentes, você precisará recarregar o aplicativo.",
				addMaxPointReachedMobile: "Desculpe, você alcançou o número máximo de pontos autorizados e não pode adicionar esta figura.",
				addClose: "Fechar",
				addHeader: "Adicione um novo ponto do percurso",
				addTabPicture: "Figura",
				addTabInformation: "Informações",
				addTabLocation: "Local",
				addSelectCaption: "Selecionar ou baixar figura",
				addSelectCaptionNoFileReader: "Selecionar figura",
				addChangePhoto: "Alterar figura e miniatura",
				addPictureResolutionIntro: "A resolução da figura é maior que o exigido:",
				addPictureResolutionOldBrowser: "A resolução da figura é maior que o exigido. Melhore a experiência de Apresentação do Mapa especificando uma resolução menor que %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Alterar a resolução da figura para %RESOLUTION%",
				addPictureResolutionKeep: "Manter a resolução original de %RESOLUTION%",
				addSelectThumbnail: "Selecionar miniatura",
				addNoThumbSelected: "Nenhuma miniatura selecionada",
				addThumbSelected: "Selecionado",
				addCameraSettingsHeader: "CONFIGURAÇÕES DA CÂMERA",
				addThumbnailHeader: "MINIATURA",
				addLabelPicUrl: "URL da Figura",
				addLabelThumbUrl: "URL da Miniatura",
				addTextPlaceholderUrl: "Insira uma URL",
				addLabelName: "Nome",
				addLabelDescription: "Legenda",
				addTextPlaceholder: "Digite algo",
				addLocatePlaceholder: "Localize um endereço ou lugar",
				addPinColor: "Cor",
				addLatitude: "Latitude",
				addLongitude: "Longitude",
				addLatitudePlaceholder: "ex: 34.056",
				addLongitudePlaceholder: "ex: -117.195",
				addUploading: "Carregando ponto do percurso",
				addSave: "Adicionar ponto do percurso",
				addMobileUploading: "Carregando figura",
				addMobileName: "Insira um nome",
				addMobileNameMandatory: "Erro, insira um nome.",
				addMobileError: "Desculpe, algo deu errado",
				settingsHeader: "Configurações do aplicativo",
				settingsTabLayout: "Layout",
				settingsTabColor: "Cores",
				settingsTabLogo: "Logo",
				settingsTabFields: "Dados",
				settingsTabExtent: "Extensão",
				settingsTabZoom: "Nível de Zoom",
				settingsLayoutExplain: "Selecione o layout do aplicativo entre os dois fornecidos.",
				settingsLayoutProfessional: "Layout de Três Painéis",
				settingsLayoutModern: "Layout Integrado",
				settingsLayoutSelected: "Layout selecionado",
				settingsLayoutSelect: "Selecionar este layout",
				settingsColorExplain: "Altere a aparência escolhendo um tema pré-definido ou crie seu próprio.",
				settingsLabelColor: "Cabeçalho, conteúdo e cores do rodapé",
				settingsLogoExplain: "Personalize o logo do cabeçalho (máximo de 250 x 50px).",
				settingsLogoEsri: "Logo da Esri",
				settingsLogoNone: "Nenhum logo",
				settingsLogoCustom: "Logo personalizado",
				settingsLogoCustomPlaceholder: "URL da Imagem",
				settingsLogoCustomTargetPlaceholder: "Clicar pelo link",
				settingsLogoSocialExplain: "Personalizar o link no cabeçalho superior direito.",
				settingsLogoSocialText: "Texto",
				settingsLogoSocialLink: "Link",
				settingsDataFieldsExplain: "Selecione nome da foto, legenda ou campos de cores.",
				settingsDataFieldsError: "O aplicativo não pode determinar o nome apropriado, legenda ou dados de cor. Selecione os campos a serem utilizados aqui. Estas configurações podem ser alteradas posteriormente.",
				settingsFieldsLabelName: "Nome",
				settingsFieldsLabelDescription: "Legenda",
				settingsFieldsLabelColor: "Cor",
				settingsExtentExplain: "Configure a extensão inicial de Apresentação do Mapa pelo mapa interativo abaixo.",
				settingsExtentExplainBottom: "Esta extensão é utilizada somente se incluir o primeiro ponto do percurso. O valor é persistido pela extensão inicial do mapa da web.",
				settingsExtentDrawBtn: "Desenhar uma nova extensão",
				settingsExtentModifyBtn: "Editar a extensão atual",
				settingsExtentApplyBtn: "Aplicar no mapa principal",
				settingsZoomExplain: "Configura zoom para pontos históricos seguindo a introdução (opcional).",
				settingsLabelZoom: "Escala/nível",
				settingsZoomFirstValue: "Nenhum",
				settingsFieldError: "Selecione um campo em cada lista",
				dataExplain: "O serviço da feição será adicionado no seu mapa da web. Não será compartilhado com ninguém, e somente você terá privilégios para adicionar, editar e excluir.<br /><br />Se você alterar os privilégios de compartilhamento do aplicativo, o sistema perguntará a você se deseja a atualização da configuração de compartilhamento do Serviço da Feição. Isto é exigido para seus usuários acessarem seus dados. Você permanecerá como o único com privilégios de edição.",
				dataNameLbl: "Nome do serviço",
				dataFolderListLbl: "Pasta",
				dataFolderListFetching: "Buscando pastas ...",
				dataRootFolder: "Raiz",
				dataNameError: "Insira um nome do serviço da feição",
				dataFolderError: "Selecione uma pasta válida",
				dataSrcContainsInvalidChar: "O nome do serviço da feição contém um ou mais caracteres inválidos (-, <, >, #, %, :, \", ?, &, +, / ou \).",
				dataSrvAlreadyExistsError: "Um serviço com este nome já existe dentro da organização. Escolha um nome diferente.",
				dataBtnSave: "Crie o serviço",
				dataFooterProgress: "Criação em progresso",
				dataFooterSucceed: "Criação bem sucedida. Carregando",
				dataFooterError: "Falha ao criar. Tente novamente",
				tabError: "Verifique por erros em todas as guias",
				introRecordBtn: "Intro",
				introRecordActivate: "Utilize o primeiro ponto como introdução (não aparece no carrossel)"
			},
			addPopupJS: {
				uploadingPicture: "Carregando figura",
				uploadSuccess: "Carregado com sucesso",
				uploadError: "Erro ao carregar a figura",
				notJpg: "Escolha uma imagem jpeg para carregar",
				errorNoPhoto: "Escolha uma imagem para carregar",
				errorNoThumbnail: "Escolha uma miniatura para carregar",
				errorInvalidPicUrl: "Insira uma URL de figura válida para este ponto do percurso",
				errorInvalidThumbUrl: "Insira uma URL de miniatura válida para este ponto do percurso",
				errorNoName: "Insira um nome para este ponto do percurso",
				errorNoDescription: "Insira uma legenda para este ponto do percurso",
				errorNoLocation: "Configure um local para este ponto do percurso"
			},
			builderJS: {
				noPendingChange: "Nenhuma alteração pendente",
				unSavedChangeSingular: "1 alteração não salva",
				unSavedChangePlural: "alterações não salvas",
				popoverDiscard: "Tem certeza que deseja descartar quaisquer alterações não salvas?",
				yes: "Sim",
				no: "Não",
				popoverLoseSave: "Ao abrir o visualizador, você perderá quaisquer alterações não slavas",
				ok: "Ok",
				popoverSaveWhenDone: "Não esqueça de salvar ao finalizar",
				closeWithPendingChange: "Tem certeza que deseja confirmar a ação ? Suas alterações serão perdidas.",
				gotIt: "Ok",
				savingApplication: "Salvando aplicativo",
				saveSuccess: "Aplicativo salvo com sucesso",
				saveError: "Falha ao salvar, tente novamente",
				dragColorPicker: "Mover ao redor<br />ou alterar minha cor",
				dataWarningExtent: "Você tem dados fora da extensão de mapa da web. Estes dados não serão utilizados como pontos de percurso, altere a extensão do mapa se você desejar utilizá-los.",
				dataWarningVisibi: "Sua camada Apresentação do Mapa não está visível na extensão de mapa da web atual. Confirme que sua camada Apresentação do Mapa é visível com um grande mapa %MAPSIZE%.",
				dataWarningEdit: "Editar mapa da web",
				dataWarningClose: "Fechar",
				signIn: "Registre-se com uma conta em",
				signInTwo: "para salvar o aplicativo."
			},
			organizePopupJS: {
				messageStart: "Você optou por excluir",
				messageSinglePoint: "um ponto do percurso",
				messageMultiPoint: "pontos de percurso",
				messagePermantRemove: "Isto removerá permanentemente o",
				messageRecord: "registro",
				messageRecordPlural: "registros",
				messageConfirm: "do seu Banco de Dados. Deseja continuar?",
				labelButtonShow: "Mostrar",
				labelButtonHide: "Ocultar"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Isto excluirá permanentemente a figura ou miniatura",
				popoverDeleteWarningThumb: "Isto excluirá permanentemente a miniatura",
				popoverUploadingPhoto: "Carregando figura e miniatura",
				popoverUploadingThumbnail: "Carregando miniatura",
				popoverUploadSuccessful: "Carregado com sucesso",
				popoverUploadError: "Falha ao carregar, tente novamente",
				changePicAndThumb: "Alterar figura",
				changeThumb: "Alterar miniatura",
				selectPic: "Alterar figura",
				selectThumb: "Alterar miniatura",
				uploadPicAndThumb: "Aplicar"
			},
			headerJS:{
				editMe: "Editar-me !",
				templateTitle: "Configurar título do modelo",
				templateSubtitle: "Configurar subtítulo do modelo"
			},
			crossFaderJS:{
				setPicture: "Configurar título da figura",
				setCaption: "Cofigurar legenda da figura"
			},
			importPopup: {
				title: "Importar",
				prevBtn: "Voltar",
				nextBtn: "Avançar"
			},
			importPopupHome: {
				header: "Onde a suas figuras estão armazenadas ?",
				loadCSV: "Elas estão referenciadas no CSV (qualquer serviço de compartilhamento de figura ou servidor da web, consulte a ajuda para detalhes)",
				loadFolder: "Uma pasta no meu computador (exige um navegador moderno e um Serviço da Feição com fonte de dados anexadas)"
			},
			onlinePhotoSharingCommon: {
				header1: "As figuras precisam ser compartilhadas publicamente.",
				header2: "A importação será limitada para %NB1% figuras para respeitar o limite de %NB2% pontos por percurso.",
				emptyDataset: "Erro, nenhuma figura encontrada",
				footerImport: "Importar",
				selectAlbum: "Selecione um álbum público",
				selectAlbum2: "Selecione um álbum",
				pleaseChoose: "Escolher",
				userLookup: "Procurar",
				userLookingup: "Procurando",
				csv: "Referenciado no CSV",
				fromScratch: "Começar do zero",
				select: "Criar uma seleção",
				locUse: "Utilizar local das figuras",
				locWhy: "Por que esta opção?",
				locExplain: "Você não pode desejar a utilização de local das figuras, pois podem ser herdados do álbum, resultando em todas as fotografias estando no mesmo local."
			},
			viewFlickr: {
				header: "Insira um nome de usuário do Flickr e selecione um Conjunto de Fotos ou Tag para ser importado.",
				userInputLbl: "Insira um Nome de Usuário",
				signInMsg2: "Usuário não encontrado",
				selectSet: "Selecione um Conjunto de Fotos",
				selectTag: "ou Selecione um Tag",
				footerImportTag: "Importe a Tag selecionada",
				footerImportSet: "Importe o Conjunto Selecionado"
			},
			viewFacebook: {
				header: "Autentique com uma Conta de Usuário do Facebook ou utilize uma Página Pública. Os álbuns privados podem ser utilizados para criar uma Apresentação do Mapa pública que não exigirá autenticação de usuário do Facebook, isto permite manter aprovações e comentários privados.",
				leftHeader: "Usuário do Facebook",
				rightHeader: "Página do Facebook",
				pageExplain: "A página do Facebook é um produto/marca pública ou figura pública como<b>esrigis</b>. Você pode obter um nome de página após o primeiro '/' na URL da página.",
				pageInputLbl: "Insira um nome de página",
				lookupMsgError: "Página não encontrada"
			},
			viewPicasa: {
				header: "Insira o e-mail ou ID de uma conta do Picasa ou Google+.",
				userInputLbl: "Insira um e-mail ou ID",
				signInMsg2: "Conta não encontrada",
				howToFind: "Como encontrar um ID da conta",
				howToFind2: "Copie dígitos entre o primeiro e segundo '/' de qualquer página do Picasa ou G+"
			},
			viewCSV: {
				uploadBtn: "Selecione ou solte um arquivo CSV",
				resultHeaderEmpty: "O arquivo CSV está vazio",
				resultHeaderSuccess: "pontos %NB_POINTS% carregados com sucesso",
				resultHasBeenLimited: "A importação foi limitada aos primeiros pontos do %VAL1% fora de %VAL2% para respeitar o limite de pontos do %VAL3% po rpercurso",
				browserSupport: "Seu navegador não tem suporte, para utilizar um CSV você tem que <a href='http://browsehappy.com/' target='_blank'>atualizar seu navegador</a> ou utilizar um visualizador de mapa do ArcGIS.com (consultar Ajuda).",
				errorLatLng: "Os campos de Latitude e Longitude não foram encontrados. Os possíveis valores para latitude são: <i>%LAT%</i> e para longitude: <i>%LONG%</i>.",
				errorFieldsExplain: "Falha ao carregar, pois os seguintes campos exigidos não foram encontrados",
				errorFieldsName: "<b>Nome</b> os possíveis valores são: %VAL%",
				errorFieldsDesc: "<b>Descrição</b> os possíveis valores são: %VAL%",
				errorFieldsUrl: "<b>URL da Figura</b> os possíveis valores são: %VAL%",
				errorFieldsThumb: "<b>URL da Miniatura</b> os possíveis valores são: %VAL%",
				errorFields2Explain: "Falha ao carregar, pois o arquivo CSV não utiliza os mesmos atributos que a camada para os seguintes atributos",
				errorFields2Name: "<b>Nome</b> utilize %VAL1% ao invés de %VAL2%",
				errorFields2Desc: "<b>Descrição</b> utilize %VAL1% ao invés de %VAL2%",
				errorFields2Url: "<b>URL da Figura</b> utilize %VAL1% ao invés de %VAL2%",
				errorFields2Thumb: "<b>URL da Miniatura</b> utilize %VAL1% ao invés de %VAL2%",
				resultFieldsAll: "Todos os atributos foram importados",
				resultFieldsNotAll: "Os seguintes atributos não foram importados, pois não existem na camada do mapa",
				resultFieldsNotAll2: "Os seguintes atributos foram importados",
				footerNextBtnResult: "Importar no mapa da web",
				footerProgress: "Importação em progesso",
				footerSucceed: "Importação bem sucedida. Carregando"
			},
			viewGeoTag: {
				header: "Clique ou toque nas figuras que você deseja importar para posicioná-las.",
				headerMore: "Por que minhas figuras não estão posicionadas?",
				headerExplain: "Se as suas figuras tiverem uma localização válida, elas serão automaticamente posicionadas no mapa e listadas na segunda guia.<br /><br />Por padrão, Picasa e Flickr não exploram metadados de localização das figuras EXIF, verifique as configurações do Flickr/Picasa na guia Privacidade para habilitar o uso de localização das figuras. Talvez seja necessário para reimportar completamente suas figuras no Flickr/Picasa.<br /><br />Para Facebook, você tem que seguir com cada figura, clique em Editar e seleciona o local entre as opções sugeridas que são baseadas em metadados das figuras EXIF.",
				leftPanelTab1: "Para localizar",
				leftPanelTab2: "Localizado",
				clickOrTap: "Clique ou toque no Mapa para localizar",
				clickDrop: "Não importar",
				footerImport: "Importar",
				footerProgress: "Importação em progesso",
				footerSucceed: "Importação bem sucedida. Carregando..."
			},
			initPopup: {
				title: "Bem-Vindo ao Construtor de Apresentação do Mapa",
				prevBtn: "Voltar",
				nextBtn: "Avançar"
			},
			initPopupHome: {
				header2: "Este assistente o ajudará a construir uma Apresentção do Mapa a partir de figuras já armazenadas online ou irá importá-las na sua conta do ArcGIS Online para Organizações.",
				title1: "Minhas figuras já estão hospedadas",
				title2: "Eu preciso hospedar minhas figuras",
				hostedFsNA: "Disponível somente para usuários com papel de Adminstrador e Publicador do ArcGIS for Organization",
				footer1: "Ao finalizar, não esqueça de compartilhar sua Apresentação do Mapa com seu público pela página de item do aplicativo.",
				footer2: "Consultar Ajuda de Apresentação do Mapa",
				footer3: "Download do modelo CSV",
				footerProgress: "Criação em progresso",
				footerSucceed: "Criação bem sucedida. Carregando..."
			},
			helpPopup: {
				title: "Ajuda",
				close: "Fechar",
				tab1: {
					title: "Introdução",
					div1: "O modelo de Apresentação do Mapa é projetado para apresentar informações geográficas onde há um elemento fotográfico narrativo para a história que você deseja contar.",
					div2: "O modelo produz um aplicativo da web, atraente e de fácil uso que permite a você apresentar um pequeno conjunto de lugares em um mapa em uma sequência numerada pela qual os usuários podem procurar. O modelo é projetado para ser utilizado em qualquer navegador da web em qualquer dispositivo, inclusive smartphones e tablets.",
					div3: "Esta ajuda o guiará pela etapa de publicação de Apresentação do Mapa como:",
					div4: "<ul><li><a href='http://storymaps.esri.com/stories/demo/map_tour/?webmap=7190edafe7464cb19c1caf1360cd6ee5' target='_blank'>Apresentação do Mapa de Palm Springs</a></li><li><a href='http://story.maps.arcgis.com/apps/MapTour/index.html?appid=4d6054b109ce482d88588d5c06a7a478' target='_blank'>Melhor passeio de bicicleta da cidade de Neverland</a></li><li><a href='http://ugis.esri.com/LA_River_Tour/' target='_blank'>Apresentação do Mapa de Los Angeles River</a></li></ul>",
					div5: "Gostariamos de saber a sua opinião! Não hesite em compartilhar sua Apresentação do Mapa conosco:",
					div6: "<ul><li><a href='mailto:storymaps@esri.com' target='_blank'>storymaps@esri.com</a></li><li><a href='http://storymaps.esri.com/home/' target='_blank'>Site da Web do StoryMaps</a></li><li><a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a></li></ul>",
					div7: "Localizar o erro ou deseja solicitar uma nova feição? Deixe-nos saber enviando um problema na <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>página do projeto GitHub</a>."
				},
				tab2: {
					title: "Dados",
					div1: "O principal elemento para considerar ao construir uma Apresentação do Mapa é escolher onde suas figuras serão armazenadas. A Apresentação do Mapa pode utilizar figuras armazenadas na maioria dos serviços de compartilhamento de fotos, em qualquer servidor da web ou no Serviços da Feição.",
					div2: "O construtor interativo lhe oferece duas opções para manipular as imagens em sua Apresentação do Mapa:",
					div3: "<ul><li>Você pode utilizar <b>fotos que já estão online</b>, tais como imagens armazenadas em site de compartilhamento de fotos como Flickr ou imagens armazenadas em seu próprio site da web. Estas imagens serão referenciadas na sua Apresentação do Mapa via suas URLs</li><li>Você também pode <b>carregar imagens do seu computador</b> diretamente na sua Apresentação do Mapa.Esta opção de transferência exige que você tenha uma conta de assinatura do ArcGIS for Organizations e privilégios de Administrador ou Publicador (pois cria automaticamente um serviço da feição hospedado para você no qual suas fotos são armazenadas como anexos)</li></ul>",
					div4: "Os principais casos de uso são:",
					div4b: "<b>Suas fotos não estão hospedadas</b> ainda e você tem uma conta de Organização: Utilizar uma Serviço da Feição hospedado é sua melhor opção. Assim como os serviços de compartilhamento de foto públicos, aperfeiçoaremos suas figuras para criar rapidamente imagens e você terá acesso a todos os recursos de administração e gerenciamento de dados da plataforma ArcGIS.",
					div5: "<b>Você não é membro de uma Organização</b>: você tem primeiro que carregar suas figuras em um site da web de compartilhamento de fotos ou no seu próprio servidor da web. Então o assistente o ajudará a utilizar estas figuras que continuarão a ser hospedadas em seu local original",
					div6: "<b>Você está pensando em reutilizar um Serviço da Feição existente</b> que armazena suas figuras como anexos ou que referencia as figuras externas: Consulte a seção detalhada abaixo",
					div7: "<b>Você é usuário de uma versão anterior</b> do modelo de Apresentação do Mapa e já tem seu CSV que referencia suas figuras e miniaturas: Você poderá importá-lo e refinar seus dados. O assistente oferece suporte somente para CSV que utiliza atributos de lat/long; o endereço baseado em CSV pode continuar a ser utilizado por seu mapa da web (consultar seção abaixo)",
					div8: "Importando de serviços de compartilhamento de fotos online",
					div9: "A operação de importação referencia figuras já hospedadas, armazenando suas URLs em uma coleção da feição de mapa da web. As figuras não são armazenadas no ArcGIS Online. Se as figuras hospedadas estiverem quebradas, elas não ficarão disponíveis na Apresentação do Mapa e uma imagem "Figura não disponível" será utilizada. Dependendo do provedor de serviços, a Apresentação do Mapa importará ou não o nome, descrição e local das figuras. Estes atributos são armazenados no mapa da web e quaisquer edições nos serviços online não serão refletidas na Apresentação do Mapa.",
					div10: "Armazenando as figuras em um servidor da web",
					div11: "Se você escolher para hospedar as figuras você mesmo, você terá que criar manualmente as miniaturas das suas figuras. Utilizar as figuras de máxima resolução para a miniatura resultará em um desempenho ruim. Por isso recomendamos fortemente que você utilize serviços de compartilhamento de fotos online ou um Serviço da Feição que fará isto para você.",
					div12: "Utilizando um Serviço da Feição ou Shapefile existente",
					div13: "Qualquer Serviço da Feição ou Shapefile de ponto pode ser utilizado como uma fonte de dados de Apresentação do Mapa. Você tem apenas que adicioná-lo como uma camada no seu mapa da web pelo Visualizador de Mapa do ArcGIS.com. Se o aplicativo encontrar os atributos esperados na sua camada, todas as funcionalidades do construtor estarão disponíveis.",
					div14: "Os campos esperados são (diferença de letra maiúscula e minúscula):",
					div151: "Nome",
					div152: "Descrição",
					div153: "Figura",
					div154: "Miniatura",
					div155: "Cor (opcional)",
					div16: "Os campos de Nome e Descrição são obrigatórios. Se o aplicativo não encontrar os campos correspondentes ao utilizar um Serviço da Feição, o visualizador não funcionará até que você configure os campos para serem utilizados pelo construtor. A camada de Shapefile ou CSV adicionada no mapa da web precisa ter todos os campos exigido ou o construtor não funcionará.",
					div17: "Os campos de Figura e Miniatura são obrigatórios para Serviço da Feição sem anexos e opcionais, mas é fortemente recomendado para Serviço da Feição com anexos. Se o seu serviço tiver anexos habilitados, o construtor permitirá a você carregar as figuras como anexos. Se não, você poderá somente editar a figura e URL da miniatura.",
					div18: "Criando um Serviço da Feição hospedado de Shapefile ou CSV",
					div19: "Quando você cria um Serviço da Feição hospedado de Shapefile ou CSV, os anexos não são habilitados  por padrão. Para habilitá-los, abra a página de item do Serviço da Feição, clique na seta pequena na seção da camada e você visualizará esta opção. Após isto, a Apresentação do Mapa continuará a utilizar as figuras e miniaturas que você referenciou pelos atributos. Opcionalmente, se você desejar carregar suas figuras como anexos de Serviço da Feição você poderá fazer isto por dois botões no painel da figura (alterar figura e alterar miniatura).",
				},
				tab3: {
					title: "Personalização",
					div1: "O construtor fornece diversas opções de personalização que são acessíveis pelo botão CONFIGURAÇÕES no painel superior. Se você não localizar a opção que você espera, fornecemos também uma versão de download que você podeimplantar no seu servidor da web e ajustar às suas necessidades.",
					div2: "Recomendamos que você utilize a versão hospedada, exceto se:",
					div3: "<li>Não oferecer um personalização de UI que você deseja ter, como utilizar uma imagem do plano de fundo do cabeçalho</li><li>Você é um desenvolvedor e deseja melhorar o aplicativo</li>",
					div4: "A versão de download não oferece um construtor interativo. A Apresentação do Mapa obterá seus dados de um mapa da web e sua configuração de um arquivo de configuração que oferece os mesmos recursos que a versão hospedada. Recomendamos que você crie e refine seu mapa da web utilizando a versão hospedada e que você o reutilize com a versão de download.",
					div5: "Visite a <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>página do projeto GitHub</a> para mais informações sobre a versão de download."
				},
				tab4: {
					title: "Dicas",
					div1: "Figuras",
					div2: "Recomendamos fotografias com orientação de paisagem ao invés de retrato. As imagens com orientação de retrato podem ser utilizadas, mas em telas pequenas como do iPad, muito da fotografia pode ser ofuscado pela legenda, pois o texto ocupa mais espaço quando é exibido em uma área alta comparada a uma área ampla. Embora imagens de diferentes tamanhos, formas e orientação possam ser utilizadas em uma Aprersentação do Mapa, recomendamos utilizar o exato mesmo tamanho e forma para todas as imagens. Deste modo, o usuário não será distraído por imagens de tamanhos diferentes conforme seguir  apresentação.",
					div3: "Formatando seu texto da legenda utilizando tags HTML",
					div4: "O texto da legenda pode incluir tags HTML para definir a formatação e links, consulte <a href='http://blogs.esri.com/esri/arcgis/2013/03/29/add-links-map-tour/' target='_blank'>esta postagem do blog</a>.",
					div5: "Suporte para Camadas",
					div6: "Você pode fornecer suporte adicional para camadas no mapa. Estas camadas aparecerão na sua Apresentação do Mapa para fornecer orientação, plano de fundo, e quaisquer outros recursos geográficos que você desejar mostrar no mapa além dos pontos de Apresentação do Mapa, tais como uma área de estudo, um caminho ou rota de direção vinculando seus pontos do percurso, etc. O modelo exibe estes suportes adicionais das camadas utilizando a simbologia que você especificar no mapa da web, o pop-up não estará disponível.",
					div7: "Matenha sua apresentação curta e agradável",
					div8: "Há um limite de 99 pontos por percurso. A maioria de Apresentações do Mapa será com certeza significativamente menor que isto. Não espere seu público para percorrer por muitos pontos do percurso. Você pode localizar seu assuntos preferidos, mas não assuma que eles também localizarão!",
					div9: "Para mais informações, consulte <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>o guia detalhado</a>."
				},
				tab5: {
					title: "Publicar",
					div1: "Ao finalizar, não esqueça de compartilhar sua Apresentação do Mapa com seu público pela página de item do aplicativo no ArcGIS Online. Durante este processo, o ArcGIS Online, irá se necessário, perguntar a você para atualizar quaisquer recursos dependentes (mapa da web, Serviço da Feição) que não tenham os mesmos privilégios de compartilhamento. Se um dos seus recursos não estiver compartilhado com seu público, os usuários serão redirecionados para a página de login do ArcGIS Online.",
					div2: "Se você estiver utilizando um Serviço da Feição hospedado criado pelo construtor de Apresentação do Mapa, o aplicativo gerenciará a segurança do serviço para você e você permanecerá como o único com privilégios de edição, mesmo se compartilhar o serviço publicamente.",
					div3: "Antes de compartilhar uma Apresentação do Mapa publicamente, certifique-se que funcione quando você não estiver registrado em sua conta do ArcGIS.com."
				}
			}
        }
    })
);
