define({
  "viewer": {
    "loading": {
      "step1": "TRWA WCZYTYWANIE NARRACJI",
      "step2": "WCZYTYWANIE DANYCH",
      "step3": "INICJOWANIE WYCIECZKI",
      "loadBuilder": "PRZEŁĄCZANIE DO TRYBU KREATORA",
      "redirectSignIn": "PRZEKIEROWANIE DO STRONY LOGOWANIA",
      "redirectSignIn2": "(tutaj nastąpi przekierowanie po zalogowaniu)",
      "fail": "Przepraszamy, wczytanie Mapy wycieczki nie powiodło się",
      "failButton": "Ponów próbę"
    },
    "errors": {
      "boxTitle": "Wystąpił błąd",
      "portalSelf": "Błąd krytyczny: Nie można pobrać konfiguracji portalu",
      "invalidConfig": "Błąd krytyczny: Nieprawidłowa konfiguracja",
      "invalidConfigOwner": "Błąd krytyczny: Nieprawidłowa konfiguracja (wymagany autoryzowany właściciel)",
      "invalidConfigNoWebmap": "Błąd krytyczny: Nieprawidłowa konfiguracja (nie określono mapy internetowej lub identyfikatora aplikacji w pliku index.html)",
      "invalidConfigNoAppDev": "W parametrach adresu URL nie określono identyfikatora aplikacji map internetowych lub mapy internetowej (?appid=  ?webmap=). W trybie deweloperskim konfiguracja parametrów appid i webmap w pliku index.html jest ignorowana.",
      "createMap": "Nie można utworzyć mapy",
      "invalidApp": "Błąd krytyczny: nie można wczytać narracji",
      "noLayer": "Mapa internetowa nie zawiera prawidłowej warstwy danych wymaganej w aplikacji Mapa wycieczki.",
      "noLayerMobile": "Kreator Mapa wycieczki nie jest obsługiwany dla wyświetlacza w tym rozmiarze. Jeśli to możliwe, zmień rozmiar okna przeglądarki, aby uzyskać dostęp do kreatora, lub buduj narrację na urządzeniu z większym ekranem.",
      "noLayerMobile2": "Aby korzystać z kreatora Mapa wycieczki, obróć urządzenie do orientacji poziomej.",
      "noLayerView": "Witaj w aplikacji internetowej Mapa wycieczki.<br />Narracja nie została jeszcze skonfigurowana.",
      "appSave": "Błąd podczas zapisywania narracji",
      "mapSave": "Błąd podczas zapisywania mapy internetowej",
      "featureServiceLoad": "Błąd podczas wczytywania usługi obiektowej",
      "notAuthorized": "Nie masz uprawnień dostępu do tej narracji",
      "notAuthorizedBuilder": "Nie masz uprawnień do korzystania z kreatora Mapa wycieczki.",
      "oldBrowserTitle": "Przeglądarka nie jest w pełni obsługiwana",
      "noBuilderIE8": "Kreator aplikacji Mapa wycieczki nie jest obsługiwany przez przeglądarkę Internet Explorer w wersji starszej niż 9.",
      "ie10Win7Explain": "Interaktywny kreator aplikacji Mapa wycieczki nie jest obsługiwany w przeglądarce Internet Explorer 10 w systemie Windows 7 w przypadku, gdy źródło danych to usługa obiektowa z załącznikami. Aby użyć usługi obiektowej z załącznikami, konieczne jest <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>ręczne wymuszenie aktywacji trybu dokumentu w standardzie programu Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>skorzystanie ze starszej wersji oprogramowania, czyli programu Internet Explorer 9</a> lub uaktualnienie do systemu Windows 8.",
      "oldBrowserExplain": "Przeglądarka nie obsługuje automatycznego generowania miniatur obrazów przesyłanych do mapy wycieczki. Możesz utworzyć mapę wycieczki w tej przeglądarce, ale konieczne będzie pojedyncze wprowadzanie miniatur dla każdego wczytanego obrazu.",
      "oldBrowserExplain2": "Aby poprawić jakość użytkowania, <a href='http://browsehappy.com/' target='_blank'>zaktualizuj przeglądarkę</a> lub <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>włącz dodatek Google Chrome Frame dla przeglądarki Internet Explorer</a>.",
      "oldBrowserExplain3": "Kreator aplikacji Mapa wycieczki nie współpracuje z przeglądarką Internet Explorer 10 w systemie Windows XP.",
      "oldBrowserClose": "Zamknij",
      "noViewerIE2": "Próbujesz wyświetlić tę narrację za pomocą starszej, nieobsługiwanej przeglądarki. Niektóre funkcje mogą nie działać lub mogą wystąpić inne nieoczekiwane problemy. Zalecamy zaktualizowanie przeglądarki do programu Internet Explorer 11 lub użycie innej przeglądarki, na przykład Chrome.",
      "noViewerIE3": "Pod koniec 2017 roku ta narracja nie będzie się już wczytywała w tej przeglądarce. Do jej wyświetlenia konieczne będzie użycie obsługiwanej przeglądarki.",
      "attention": "Uwaga!"
    },
    "mobileHTML": {
      "showIntro": "POKAŻ TYTUŁ",
      "hideIntro": "UKRYJ TYTUŁ",
      "navList": "Lista",
      "navMap": "Mapa",
      "navInfo": "Multimedia",
      "introStartBtn": "Początek"
    },
    "desktopHTML": {
      "storymapsText": "Story map",
      "builderButton": "Przełącz do trybu kreatora",
      "facebookTooltip": "Udostępnij na Facebooku",
      "twitterTooltip": "Udostępnij na Twitterze",
      "bitlyTooltip": "Utwórz skrócone łącze",
      "bitlyStartIndex": "Połącz z bieżącym miejscem",
      "tooltipAutoplayDisabled": "To nie jest dostępne w trybie automatycznego odtwarzania",
      "autoplayLabel": "Tryb automatycznego odtwarzania",
      "autoplayExplain1": "W trybie automatycznego odtwarzania narracja jest prezentowana w stałym tempie. Ten tryb doskonale nadaje się do monitora kiosku internetowego lub wyświetlacza publicznego, ale należy pamiętać, że w innych sytuacjach może pogorszyć czytelność narracji. Ta funkcja nie jest obsługiwana na małych wyświetlaczach.",
      "autoplayExplain2": "Po włączeniu tego trybu udostępniane są elementy sterujące do włączania odtwarzania/wstrzymywania narracji oraz do regulacji szybkości nawigacji.",
      "takeTourText": "Rozpocznij wycieczkę",
      "backToStart": "Powrót do początku"
    },
    "builderHTML": {
      "panelHeader": "KONFIGURACJA NARRACJI",
      "buttonSave": "ZAPISZ",
      "buttonSettings": "Ustawienia",
      "buttonShare": "Udostępnij",
      "buttonView": "Tryb wyświetlania",
      "buttonItem": "Otwórz element aplikacji internetowej",
      "buttonHelp": "Pomoc",
      "buttonOrganize": "Organizuj",
      "buttonOrganizeAndCover": "Organizuj punkty wycieczki i dodaj okładkę",
      "buttonAdd": "Dodaj",
      "buttonImport": "Importuj",
      "buttonImportDisabled": "Podczas przesyłania obrazu importowanie jest niedostępne. Kliknij przycisk Dodaj, aby przesłać obraz.",
      "dataEditionDisabled": "Edycja danych źródła danych formatu CSV jest wyłączona",
      "dataSourceWarning": "Warstwa danych mapy wycieczki została zmieniona. Jeśli identyfikatory obiektów nie są takie same, należy zresetować kolejność i ukryte punkty za pomocą opcji <b>Organizuj</b>. Jeśli nazwy pól są różne, należy zresetować ustawienia pól w <b>Ustawieniach na karcie Dane</b>.",
      "organizeWarning": "Ukryty jest jeden lub więcej punktów, dodanych poza interaktywnym kreatorem.",
      "dataPicError0a": "Ta wycieczka obejmuje następującą liczbę niezgodnych adresów URL obrazu: <b>%NB%</b>.",
      "dataPicError0b": "Ta wycieczka może obejmować następującą liczbę niezgodnych adresów URL obrazu: <b>%NB%</b>.",
      "dataPicError1": "Mapa wycieczki wymaga obecnie, aby adres URL obrazu kończył się jednym z następujących rozszerzeń: .jp(e)g, .png, .gif lub .bmp.",
      "dataPicError2": "Wymaganie to nie dotyczy opublikowanej już mapy wycieczki. W celu korzystania z interaktywnego kreatora należy jednak rozwiązać najpierw problem z adresami URL, wykonując jedno z dwóch działań:",
      "dataPicError3": "Edytuj adresy URL",
      "dataPicError4": "Spowoduje to dodanie parametru <i>#isImage</i> do końca nieobsługiwanych adresów URL obrazu. Większość serwerów obsługuje parametry adresów URL. Po wykonaniu tej czynności należy jednak sprawdzić, czy zaktualizowane adresy URL obrazów funkcjonują prawidłowo podczas nawigacji po punktach. Jeżeli każdy obraz zostanie wczytany, można zapisać mapę wycieczki. Jeżeli <b>obrazy nie wczytują się, nie zapisuj mapy wycieczki</b>. W takim przypadku uruchom ponownie kreator i wykonaj drugą operację.",
      "dataPicError5": "Ogranicz wycieczkę do obrazów",
      "dataPicError6": "Ta opcja spowoduje traktowanie wszystkich adresów URL jako adresów obrazów. Nie będzie można wtedy jednak dodawać plików wideo przy użyciu interaktywnego kreatora. Aby dodać w przyszłości pliki wideo, tę opcję można zmienić.",
      "dataPicError7": "Mapa wycieczki została ograniczona do obrazów. Nie można stosować plików wideo. Jeżeli zdecydujesz się usunąć to ograniczenie, sprawdź przed zapisaniem mapy wycieczki czy obrazy nadal wczytują się prawidłowo. W razie potrzeby będzie można później zmienić to ograniczenie.",
      "dataPicError8": "Usuń ograniczenie do obrazów",
      "dataPicError9": "Jeżeli te adresy URL prowadzą do plików wideo, można zignorować to ostrzeżenie. Jeżeli prowadzą do obrazów, należy wykonać jedno z dwóch następujących działań:",
      "modalCancel": "Anuluj",
      "modalApply": "Zastosuj",
      "organizeHeader": "Organizuj wycieczkę",
      "organizeGeneralCaption": "Użyj metody „przeciągnij i upuść”, aby uporządkować punkty wycieczki",
      "organizeDelete": "Usuń",
      "organizeHide": "Ukryj",
      "organizeReset": "Resetuj kolejność i ukryte punkty",
      "addMaxPointReached": "Osiągnięto maksymalną liczbę punktów dozwolonych dla wybranych ikon. Nie można dodać kolejnego punktu wycieczki.<br /><br />Jeśli usuniesz istniejące punkty, konieczne będzie ponowne wczytanie narracji.",
      "addMaxPointReachedMobile": "Przepraszamy, osiągnięto maksymalną liczbę dozwolonych punktów i nie można dodać tego obrazu.",
      "addClose": "Zamknij",
      "addHeader": "Dodaj nowy punkt wycieczki",
      "addTabPicture": "Multimedia",
      "addTabInformation": "Informacja",
      "addTabLocation": "Lokalizacja",
      "addSelectCaption": "Wybierz lub upuść obraz",
      "addNoteVideo": "Aby uzyskać instrukcję używania plików wideo, skorzystaj z Pomocy.",
      "addSelectCaptionNoFileReader": "Wybierz obraz",
      "addChangePhoto": "Zmień obraz i miniaturę",
      "addPictureResolutionIntro": "Rozdzielczość obrazu jest wyższa niż wymagana:",
      "addPictureResolutionOldBrowser": "Rozdzielczość obrazu jest wyższa niż wymagana. Możesz zoptymalizować korzystanie z aplikacji Mapa wycieczki, ustawiając rozdzielczość o wartości niższej niż %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Zmień rozdzielczość obrazu na %RESOLUTION%",
      "addPictureResolutionKeep": "Zachowaj oryginalną rozdzielczość %RESOLUTION%",
      "addSelectThumbnail": "Wybierz miniaturę",
      "addNoThumbSelected": "Nie wybrano miniatury",
      "addThumbSelected": "Wybrane",
      "addCameraSettingsHeader": "USTAWIENIA KAMERY",
      "addThumbnailHeader": "MINIATURA",
      "addLabelPicUrl": "Obraz",
      "addLabelThumbUrl": "Miniatura",
      "addTextPlaceholderUrl": "Wprowadź adres URL obrazu",
      "addTextPlaceholderUrl2": "Wprowadź adres URL strony w serwisie YouTube",
      "addTextPlaceholderUrl3": "Wprowadź adres URL strony w serwisie Vimeo",
      "addTextPlaceholderUrl4": "Wprowadź adres URL umożliwiający osadzenie materiału wideo",
      "addLabelVideo": "Wideo",
      "addMediaVideoOther": "Inne",
      "addMediaVideoHelp": "Sprawdź adres URL i pobierz domyślną miniaturę",
      "addMediaVideoHelpTooltip1": "Sprawdzanie zakończone pomyślnie",
      "addMediaVideoHelpTooltip2": "Sprawdzanie nie powiodło się",
      "addMediaVideoHelpTooltip4": "Znajdź opcję osadzania materiału wideo i skopiuj adres URL do wideo, który jest podany w kodzie",
      "addLabelName": "Nazwa",
      "addLabelDescription": "Podpis",
      "addTextPlaceholder": "Wpisz tekst",
      "addLocatePlaceholder": "Zlokalizuj adres lub miejsce",
      "addPinColor": "Kolor",
      "addLatitude": "Szerokość geograficzna",
      "addLongitude": "Długość geograficzna",
      "addLatitudePlaceholder": "np. 34,056",
      "addLongitudePlaceholder": "np. -117,195",
      "addUploading": "Przesyłanie punktu wycieczki",
      "addSave": "Dodaj punkt wycieczki",
      "addMobileUploading": "Przesyłanie obrazu",
      "addMobileName": "Wprowadź nazwę",
      "addMobileNameMandatory": "Błąd, należy podać nazwę.",
      "addMobileError": "Przepraszamy, wystąpiły błędy",
      "settingsHeader": "Ustawienia",
      "settingsTabLayout": "Układ",
      "settingsTabColor": "Kolory",
      "settingsTabLogo": "Nagłówek",
      "settingsTabFields": "Dane",
      "settingsTabExtent": "Zasięg",
      "settingsTabZoom": "Poziom powiększenia",
      "settingsLayoutExplain": "Wybierz kompozycję, której chcesz używać.",
      "settingsLayoutProfessional": "Panel trzyczęściowy",
      "settingsLayoutModern": "Zintegrowana",
      "settingsLayoutSidePanel": "Panel boczny",
      "settingsLayoutSelected": "Wybrany układ",
      "settingsLayoutNew": "Nowe!",
      "settingsLayoutSelect": "Zaznacz",
      "settingsLayoutNote": "Należy pamiętać, że w przypadku punktów, w ramach których wykorzystywane są materiały wideo, podpis będzie zawsze znajdował się pod materiałem wideo, nawet jeśli opcja ta nie jest zaznaczona.",
      "settingsLayoutLocBtn": "Wyświetl przycisk Lokalizuj",
      "settingsLayoutLocBtnHelp": "Funkcja obsługiwana w większości przeglądarek. Wyświetlana tylko wtedy, gdy dostęp do mapy narracyjnej jest uzyskiwany za pomocą protokołu HTTPS. Nie pojawia się, gdy narracja jest osadzona.",
      "settingsColorExplain": "Zmień wygląd aplikacji, wybierając gotowy motyw lub tworząc własny.",
      "settingsLabelColor": "Kolory nagłówka, zawartości i stopki",
      "settingsLogoExplain": "Dostosuj logo w nagłówku (maksymalny rozmiar to 250 x 50 pikseli).",
      "settingsLogoEsri": "Logo firmy Esri",
      "settingsLogoNone": "Brak logo",
      "settingsLogoCustom": "Logo niestandardowe",
      "settingsLogoCustomPlaceholder": "Adres URL obrazu",
      "settingsLogoCustomTargetPlaceholder": "łącze przekierowujące do innej strony",
      "settingsLogoSocialExplain": "Dostosuj łącze nagłówka wyświetlane u góry po prawej.",
      "settingsLogoSocialText": "Tekst",
      "settingsLogoSocialLink": "Łącze",
      "settingsLogoSocialDisabled": "Opcja ta została wyłączona przez Administratora",
      "settingsDataFieldsExplain": "Wybierz nazwę zdjęcia, podpis i pola koloru.",
      "settingsDataFieldsError": "Aplikacja nie jest w stanie określić odpowiednich danych dotyczących nazwy, podpisu lub kolorów. Wybierz pola, które mają zostać użyte. Ustawienia te można później zmienić.",
      "settingsFieldsLabelName": "Nazwa",
      "settingsFieldsLabelDescription": "Podpis",
      "settingsFieldsLabelColor": "Kolor",
      "settingsFieldsReset": "Resetuj wybrane pola",
      "settingsExtentExplain": "Skonfiguruj początkowy zasięg Mapy wycieczki na poniższej interaktywnej mapie.",
      "settingsExtentExplainBottom": "Zdefiniowany zasięg zostanie użyty do modyfikacji początkowego zasięgu mapy. Prosimy pamiętać, że zasięg ten nie jest używany, jeśli nie obejmuje pierwszego punktu wycieczki. W takim przypadku wycieczka zostanie rozpoczęta od punktu pierwszego.",
      "settingsExtentDateLineError": "Zasięg nie może przebiegać przez południk 180Â°",
      "settingsExtentDateLineError2": "Błąd w obliczaniu zasięgu",
      "settingsExtentDrawBtn": "Narysuj nowy zasięg",
      "settingsExtentModifyBtn": "Zmień zasięg",
      "settingsExtentApplyBtn": "Zobacz podgląd mapy wycieczki",
      "settingsExtentUseMainMap": "Użyj zasięgu mapy wycieczki",
      "settingsZoomExplain": "Konfiguracja powiększenia punktów narracji (opcja).",
      "settingsLabelZoom": "Skala/poziom",
      "settingsZoomFirstValue": "Brak",
      "settingsFieldError": "Wybierz pole z każdej listy",
      "dataTitle": "Utwórz hostowaną warstwę Mapy wycieczki",
      "dataExplain": "Zostanie utworzona nowa warstwa obiektowa dla obrazów i punktów wycieczki. Warstwa wycieczki nie będzie udostępniana, jeśli mapa wycieczki nie zostanie udostępniona.",
      "dataExplainPortal": "Jeśli warstwa obiektowa nie została pomyślnie utworzona, skontaktuj się z administratorem systemu ArcGIS.",
      "dataNameLbl": "Nazwa warstwy",
      "dataFolderListLbl": "Folder",
      "dataFolderListFetching": "Trwa pobieranie folderów...",
      "dataRootFolder": "Główny",
      "dataNameError": "Wprowadź nazwę usługi obiektowej",
      "dataFolderError": "Wybierz prawidłowy folder",
      "dataSrcContainsInvalidChar": "Nazwa usługi obiektowej zawiera co najmniej jeden nieprawidłowy znak (-, <, >, #, %, :, \", ?, &, +, / lub ).",
      "dataSrvAlreadyExistsError": "Usługa o tej nazwie już istnieje w zasobach instytucji. Wybierz inną nazwę.",
      "dataBtnSave": "Utwórz warstwę",
      "dataFooterProgress": "Trwa tworzenie",
      "dataFooterSucceed": "Tworzenie zakończyło się pomyślnie. Trwa wczytywanie",
      "dataFooterError": "Tworzenie nie powiodło się. Spróbuj ponownie",
      "tabError": "Sprawdź, czy dane w poszczególnych kartach nie zawierają błędów",
      "introRecordBtn": "Wprowadzenie",
      "introRecordActivate": "Użyj pierwszego punktu jako wprowadzenia (nie jest wyświetlany na przewijanej taśmie)",
      "coverRecordActivate": "Użyj pierwszego punktu jako okładki",
      "coverBuilder": "Konfiguracja okładki",
      "cover": "Okładka",
      "showCover": "Pokaż okładkę",
      "editCover": "Edytuj okładkę",
      "coverNoVideo": "Wideo nie jest obsługiwane na okładkach. Wybierz obraz.",
      "coverPreview": "Aby zobaczyć okładkę, zapisz swoją narrację, a następnie wyświetl podgląd, używając przycisku Wyświetl narrację.",
      "thirdPartyTerms": "Używając usługi innych producentów, zgadzasz się na warunki jej użytkowania: "
    },
    "addPopupJS": {
      "uploadingPicture": "Wczytywanie obrazu",
      "uploadSuccess": "Przesyłanie zakończone pomyślnie",
      "uploadError": "Błąd podczas przesyłania obrazu",
      "uploadError2": "Wystąpił błąd podczas dodawania obiektu (błędny znacznik HTML)",
      "notJpg": "Wybierz obraz w formacie JPEG do przesłania",
      "errorNoPhoto": "Wybierz obraz do przesłania",
      "errorNoThumbnail": "Wybierz miniaturę do przesłania",
      "errorInvalidPicUrl": "Wprowadź prawidłowy adres URL obrazu. Zaczyna się on od https. Kończy się na jpg, png, gif lub bmp. W celu ominięcia tej reguły możesz zakończyć adres URL parametrem '#isImage'.",
      "errorInvalidThumbUrl": "Wprowadź prawidłowy adres miniatury (zaczyna się od https://, a kończy na jpg, png, gif lub bmp).",
      "errorInvalidVideoUrl": "Wprowadź prawidłowy adres URL materiału wideo (rozpoczyna się od https://)",
      "errorNoName": "Wprowadź nazwę tego punktu wycieczki",
      "errorNoDescription": "Wprowadź podpis dla tego punktu wycieczki",
      "errorNoLocation": "Określ lokalizację dla tego punktu wycieczki"
    },
    "builderJS": {
      "noPendingChange": "Brak niezapisanych zmian",
      "unSavedChangeSingular": "1 niezapisana zmiana",
      "unSavedChangePlural": "niezapisane zmiany",
      "shareStatus1": "Wycieczka nie została zapisana",
      "shareStatus2": "Wycieczka została udostępniona publicznie",
      "shareStatus3": "Wycieczka została udostępniona w obrębie instytucji",
      "shareStatus4": "Wycieczka nie została nikomu udostępniona",
      "popoverDiscard": "Na pewno chcesz odrzucić wszystkie niezapisane zmiany?",
      "yes": "Tak",
      "no": "Nie",
      "popoverLoseSave": "Otwarcie przeglądarki spowoduje utratę niezapisanych zmian",
      "ok": "OK",
      "popoverSaveWhenDone": "Nie zapomnij zapisać po zakończeniu pracy",
      "closeWithPendingChange": "Czy na pewno chcesz zatwierdzić tę operację? Zmiany zostaną utracone.",
      "gotIt": "OK",
      "savingApplication": "Trwa zapisywanie narracji",
      "saveSuccess": "Narracja została zapisana",
      "saveError": "Zapisywanie nie powiodło się, spróbuj ponownie",
      "saveError2": "Próba zapisania nie powiodła się - błędny znacznik HTML w nazwie lub opisie",
      "saveError3": "Tytuł nie może być pusty",
      "dragColorPicker": "Przesuwaj mapą<br />lub zmień jej kolory",
      "dataWarningExtent": "Twoje dane znajdują się poza zasięgiem mapy internetowej. Dane te nie zostaną przekształcone w punkty wycieczki, zmień zasięg mapy, aby ich użyć.",
      "dataWarningVisibi": "Twoja warstwa Mapy wycieczki nie jest widoczna w bieżącym zasięgu mapy. Aby warstwa mapy wycieczki była widoczna, ustaw wartość rozmiaru mapy na %MAPSIZE%.",
      "dataWarningEdit": "Edytuj mapę internetową",
      "dataWarningClose": "Zamknij",
      "signIn": "Zaloguj się na konto,",
      "signInTwo": "aby zapisać narrację.",
      "switchBM": "Zmień mapę bazową"
    },
    "organizePopupJS": {
      "messageStart": "Podjęto decyzję o usunięciu",
      "messageSinglePoint": "punktu wycieczki",
      "messageMultiPoint": "punktów wycieczki",
      "messagePermantRemove": "Spowoduje to trwałe usunięcie",
      "messageRecord": "rekordu",
      "messageRecordPlural": "rekordy",
      "messageConfirm": "z Twojej bazy danych. Chcesz kontynuować?",
      "labelButtonShow": "Pokaż",
      "labelButtonHide": "Ukryj"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Spowoduje to trwałe usunięcie obrazu i miniatury",
      "popoverDeleteWarningThumb": "Spowoduje to trwałe usunięciu miniatury",
      "popoverUploadingPhoto": "Przesyłanie obrazu i miniatury",
      "popoverUploadingThumbnail": "Przesyłanie miniatury",
      "popoverUploadSuccessful": "Przesyłanie zakończone pomyślnie",
      "popoverUploadError": "Przesyłanie nie powiodło się, spróbuj ponownie",
      "changePicAndThumb": "Zmień obraz",
      "changeThumb": "Zmień miniaturę",
      "selectPic": "Zmień media",
      "selectThumb": "Zmień miniaturę",
      "uploadPicAndThumb": "Zastosuj"
    },
    "headerJS": {
      "editMe": "Edytuj!",
      "templateTitle": "Skonfiguruj tytuł",
      "templateSubtitle": "Skonfiguruj podtytuł",
      "edit": "Edytuj"
    },
    "crossFaderJS": {
      "setPicture": "Określ tytuł obrazu",
      "setCaption": "Określ podpis obrazu"
    },
    "importPopup": {
      "title": "Importuj",
      "prevBtn": "Powrót",
      "nextBtn": "Dalej"
    },
    "importPopupHome": {
      "header": "Gdzie są przechowywane Twoje obrazy?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "obrazy",
      "videos": "wideo",
      "disabled": "Opcja ta została wyłączona przez Administratora",
      "disabledPortal": "Ta funkcja wymaga, aby portal miał serwer hostujący. Skontaktuj się z administratorem witryny Portal for ArcGIS.",
      "header1": "Obrazy muszą być udostępnione publicznie.",
      "header2": "Import zostanie ograniczony do pierwszych %NB1% %MEDIA%.",
      "emptyDataset": "Błąd, nie znaleziono obrazów",
      "footerImport": "Importuj",
      "selectAlbum": "Wybierz album publiczny",
      "selectAlbum2": "Wybierz album",
      "pleaseChoose": "Wybierz",
      "userLookup": "Odszukaj",
      "userLookingup": "Wyszukiwanie",
      "csv": "Odnośnik w pliku CSV",
      "advanced": "Opcje zaawansowane",
      "advancedScratchLbl": "Rozpocznij nową wycieczkę",
      "advancedScratchTip": "Utwórz pustą wycieczkę, do której możesz dodać punkty wycieczki. Multimedia muszą być dostępne w trybie online. Ta opcja nie obsługuje przesyłania własnych obrazów.",
      "advancedCSVLbl": "Importuj dane wycieczki z pliku CSV",
      "advancedCSVTip": "Importuj zawartość swojej wycieczki z pliku CSV, który odnosi się do Twoich multimediów w internecie. Ta opcja nie obsługuje przesyłania własnych obrazów.",
      "advancedCommonTip": "Wymagane jest, aby Twoje obrazy oraz filmy znajdowały się już w Internecie.",
      "select": "Wybierz",
      "locUse": "Użyj geolokalizacji obrazów",
      "locExplain": "Nie musisz korzystać z lokalizacji obrazów, gdyż mogą one być dziedziczone z albumu, w wyniku czego wszystkie zdjęcia znajdą się w tej samej lokalizacji.",
      "locExplain2": "Nie ma konieczności używania lokalizacji filmów, ponieważ informacje te mogą być dziedziczone z ustawień użytkownika, w wyniku czego wszystkie filmy będą miały tę samą lokalizację."
    },
    "viewFlickr": {
      "title": "Import z serwisu Flickr",
      "header": "Wprowadź swoją nazwę użytkownika używaną w serwisie Flickr i wybierz album lub znacznik do zaimportowania.",
      "userInputLbl": "Wprowadź nazwę użytkownika",
      "signInMsg2": "Nie odnaleziono użytkownika",
      "selectSet": "Wybierz album",
      "selectTag": "lub wybierz znacznik",
      "footerImportTag": "Importuj wybrany znacznik",
      "footerImportSet": "Importuj wybrany album"
    },
    "viewFacebook": {
      "title": "Import z serwisu Facebook",
      "header": "Uwierzytelnij, używając własnego konta użytkownika w serwisie Facebook lub użyj strony publicznej. Prywatnych albumów można użyć do tworzenia publicznych map wycieczek, które nie wymagają uwierzytelniania przez użytkownika serwisu Facebook, co umożliwia zachowanie prywatnego statusu elementów, takich jak komentarze i polubienia.",
      "leftHeader": "Użytkownik Facebook",
      "rightHeader": "Strona Facebook",
      "pageExplain": "Strona Facebook to publiczna strona marki/produktu lub znanej osoby, np.<b>esrigis</b>. Nazwa strony została umieszczona po pierwszym znaku „/” w adresie URL strony.",
      "pageInputLbl": "Wprowadź nazwę strony",
      "lookupMsgError": "Nie znaleziono strony"
    },
    "viewPicasa": {
      "title": "Import z serwisu Google+",
      "header": "Podaj swój adres e-mail lub identyfikator.",
      "userInputLbl": "Adres e-mail lub identyfikator z serwisu Picasa/Google+",
      "signInMsg2": "Nie odnaleziono konta",
      "signInMsg3": "Brak albumów publicznych",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Dowiedz się więcej</a>",
      "howToFind2": "Skopiuj cyfry znajdujące się między pierwszym a drugim znakiem „/” dowolnej strony Picasa"
    },
    "viewCSV": {
      "title": "Import z pliku CSV",
      "uploadBtn": "Wybierz lub upuść plik CSV",
      "resultHeaderEmpty": "Plik CSV jest pusty",
      "resultHeaderSuccess": "Liczba wczytanych punktów: %NB_POINTS%",
      "resultHasBeenLimited": "Ograniczono import do pierwszych %VAL1% punktów z %VAL2% punktów w celu zapewnienia zgodności z ograniczeniem liczby punktów dla jednej wycieczki wynoszącym %VAL3%",
      "browserSupport": "Twoja przeglądarka nie jest obsługiwana, aby użyć pliku CSV musisz <a href='http://browsehappy.com/' target='_blank'>zaktualizować przeglądarkę</a> lub skorzystać z przeglądarki map internetowych ArcGIS.com (patrz Pomoc).",
      "errorLatLng": "Nie odnaleziono pól szerokości i długości geograficznej. Możliwe wartości szerokości geograficznej to: <i>%LAT%</i>, a długości geograficznej to: <i>%LONG%</i>.",
      "errorFieldsExplain": "Wczytywanie zakończyło się niepowodzeniem, ponieważ nie odnaleziono następujących wymaganych pól",
      "errorFieldsName": "Możliwe wartości dla parametru <b>Nazwa</b> to: %VAL%",
      "errorFieldsDesc": "Możliwe wartości parametru<b>Opis</b> to: %VAL%",
      "errorFieldsUrl": "Możliwe wartości parametru<b>Adres URL obrazu</b> to: %VAL%",
      "errorFieldsThumb": "Możliwe wartości parametru <b>Adresu URL miniatury</b> to: %VAL%",
      "errorFields2Explain": "Wczytywanie nie powiodło się, ponieważ plik CSV nie korzysta z tych samych atrybutów co warstwa, odnosi się to do następujących atrybutów",
      "errorFields2Name": "Dla parametru<b>Nazwa</b>  użyj wartości %VAL1% zamiast %VAL2%",
      "errorFields2Desc": "Dla parametru <b>Opis</b> użyj wartości %VAL1% zamiast wartości  %VAL2%",
      "errorFields2Url": "Dla parametru <b>Adres URL obrazu</b> użyj wartości %VAL1% zamiast wartości %VAL2%",
      "errorFields2Thumb": "Dla parametru <b>Adres URL miniatury</b> użyj wartości %VAL1% zamiast wartości %VAL2%",
      "resultFieldsAll": "Zaimportowano wszystkie atrybuty",
      "resultFieldsNotAll": "Następujące atrybuty nie zostały zaimportowane, ponieważ nie ma ich w warstwie mapy",
      "resultFieldsNotAll2": "Zaimportowano następujące atrybuty",
      "footerNextBtnResult": "Importuj do mapy internetowej",
      "footerProgress": "Importowanie w toku",
      "footerSucceed": "Importowanie zakończyło się pomyślnie. Trwa wczytywanie"
    },
    "viewYoutube": {
      "title": "Import z serwisu YouTube",
      "header": "Wprowadź nazwę użytkownika serwisu YouTube, aby znaleźć filmy wideo udostępnione publicznie.",
      "pageInputLbl": "Wpisz nazwę użytkownika serwisu YouTube",
      "lookupMsgError": "Nie odnaleziono użytkownika",
      "howToFind": "W jaki sposób wyszukać nazwę użytkownika serwisu YouTube",
      "howToFind2": "Nazwa użytkownika jest wyświetlana pod każdym filmem",
      "found": "Znaleziono",
      "noData": "Nie znaleziono żadnych filmów publicznych"
    },
    "viewGeoTag": {
      "title": "Wybierz i zlokalizuj swoje obrazy/filmy",
      "header": "Zlokalizowane elementy zostaną zaimportowane. Kliknij niezlokalizowane elementy, które chcesz zaimportować, aby je zlokalizować.",
      "headerMore": "Pomoc",
      "headerExplain": "Po kliknięciu przycisku <b>Importuj</b> zostaną zaimportowane tylko obrazy lub materiały wideo wyszczególnione na karcie <b>Zlokalizowane</b>.<br><br>Informacje dotyczące geolokalizacji zapisane razem z obrazami lub materiałami wideo są importowane automatycznie, o ile są dostępne. Wszystkie elementy bez danych dotyczących geolokalizacji są wyszczególnione na karcie <b>Do zlokalizowania</b>. Aby zlokalizować element wyszczególniony na tej karcie, kliknij go, a następnie kliknij wybraną lokalizację na mapie.<br><br>Aby usunąć element z karty <b>Zlokalizowane</b>, dzięki czemu nie zostanie on zaimportowany, kliknij przycisk Nie importuj widoczny po umieszczeniu kursora myszy na elemencie.<br><br>Wskazówka: Jeśli informacje dotyczące geolokalizacji medium nie są importowane, sprawdź ustawienia prywatności swojego konta. Na przykład upewnij się, że w ustawieniach konta w serwisie Flickr dane EXIF nie są ukryte. Dodatkowo, jeśli w ustawieniach prywatności serwisu Flickr opcja importowania danych EXIF dla nowych przesyłań jest wyłączona (jest to ustawienie domyślne), informacje dotyczące geolokalizacji dla Twoich obrazów nie zostaną zapisane w serwisie Flickr, o ile nie zostaną one przesłane ponownie lub ich lokalizacja nie zostanie ręcznie określona w serwisie Flickr.",
      "leftPanelTab1": "Do zlokalizowania",
      "leftPanelTab2": "Zlokalizowane",
      "clickOrTap": "Kliknij mapę, aby zlokalizować",
      "clearLoc": "Wyczyść lokalizacje",
      "clickDrop": "Nie importuj",
      "footerImport": "Importuj",
      "footerProgress": "Importowanie w toku",
      "footerSucceed": "Importowanie zakończyło się pomyślnie. Trwa wczytywanie...",
      "loading": "Wczytywanie",
      "error": "Import danych geolokalizacji obrazów nie powiódł się. Dane geolokalizacji zostały zignorowane."
    },
    "initPopup": {
      "title": "Witaj w kreatorze mapy wycieczki",
      "prevBtn": "Powrót",
      "nextBtn": "Dalej"
    },
    "initPopupHome": {
      "header1": "Gdzie znajdują się Twoje zdjęcia lub filmy wideo?",
      "header2": "Ten kreator pomoże Ci zbudować mapę wycieczki z multimediów przechowywanych online lub zaimportuje te elementy na Twoje konto w ArcGIS Online dla instytucji.",
      "title1": "Są już online",
      "title2": "Potrzebuję przesłać obrazy",
      "hostedFSTooltip": "Prześlij własne obrazy i zapisz je w wycieczce (pliki wideo nie są obsługiwane).",
      "hostedFsNA": "Do publikowania hostowanych warstw obiektów konieczna jest rola Publikującego lub inna rola z odpowiednimi uprawnieniami. Skontaktuj się z administratorem oprogramowania ArcGIS.",
      "hostedFsNA2": "Dostępne tylko w ramach subskrypcji ArcGIS Online. <a href='%LINK%'>Zarejestruj się w celu uzyskania bezpłatnej wersji próbnej</a>",
      "footer1": "Po zakończeniu wprowadzania zmian nie zapomnij udostępnić mapy wycieczki odbiorcom za pomocą strony szczegółów aplikacji.",
      "footer3": "Pobierz szablon CSV",
      "footer4": "Zapisz, jakby element nie był pobrany z sieci",
      "footer4bis": "Jeżeli pobieranie się nie rozpocznie, kliknij prawym przyciskiem myszy i wybierz polecenie Zapisz jako.",
      "footer5": "Dowiedz się więcej",
      "footerProgress": "Trwa tworzenie",
      "footerSucceed": "Tworzenie zakończyło się pomyślnie. Trwa wczytywanie..."
    },
    "helpPopup": {
      "title": "Pomoc",
      "close": "Zamknij",
      "tab1": {
        "title": "Wprowadzenie",
        "moreInfo": "Więcej informacji",
        "infoSites": "Odwiedź <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>sekcję Mapa wycieczki</a> <a href='https://storymaps.arcgis.com' target='_blank'>witryny internetowej Esri Story Maps (Mapy narracyjne).</a>",
        "mtFAQ": "Zapoznaj się z sekcją <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Mapa wycieczki — często zadawane pytania.</a>",
        "myStories": "W witrynie internetowej w elemencie <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Moje narracje</a> można zarządzać mapami wycieczek i sprawdzać w nich błędy.",
        "div1": "Szablon mapy wycieczki został zaprojektowany do prezentacji informacji geograficznych oraz fascynujących fotografii lub elementów multimedialnych dopełniających prezentowany scenariusz.",
        "div2": "Przy użyciu szablonu można utworzyć atrakcyjnie wyglądającą i łatwą w obsłudze aplikację internetową umożliwiającą prezentację niewielkiego zbioru miejsc na mapie w ponumerowanej kolejności. Użytkownicy mogą przeglądać ten zbiór. Szablon zaprojektowano do użytku w dowolnej przeglądarce i na każdym urządzeniu, w tym również na smartfonie i tablecie.<br /><br />",
        "div42": "Aby zobaczyć przykłady map wycieczek utworzonych przez innych użytkowników, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>przejdź do galerii</a> w <a href='https://storymaps.arcgis.com/' target='_blank'>witrynie internetowej Story Maps (Mapy narracyjne)</a>. Można także śledzić nas w serwisie Twitter: <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Będziemy wdzięczni za wszelkie opinie! Opowiedz nam o problemach i nowych funkcjach, których potrzebujesz, odwiedzając forum Story Maps w serwisie <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet.</a>"
      },
      "tab2": {
        "title": "Dane",
        "div1": "Głównym zagadnieniem, które należy rozważyć podczas tworzenia mapy wycieczki, jest miejsce przechowywania obrazów. Na mapie wycieczki można użyć obrazów przechowywanych w serwisach udostępniających zdjęcia, na dowolnym serwerze WWW lub przesłanych z dysku.",
        "div1a": "Informacje o obsługiwanych formatach obrazów i wideo można znaleźć w ostatniej sekcji tej karty.",
        "div2": "Interaktywny kreator udostępnia dwie opcje obsługi obrazów w mapie wycieczki:",
        "div3": "<ul><li>Można używać <b>zdjęć, które już zostały udostępnione online</b>, na przykład obrazów zapisanych w serwisie Flickr albo obrazów zapisanych na własnym serwerze internetowym. Obrazy te będą przywoływane na mapie wycieczki za pomocą ich adresów URL.</li><li>Można też <b>przesłać zdjęcia z komputera</b> bezpośrednio do mapy wycieczki. Opcja przesyłania wymaga subskrypcji ArcGIS i uprawnień Publikującego lub Administratora, ponieważ automatycznie tworzona jest hostowana usługa obiektowa, w której zdjęcia są zapisywane jako załączniki.</li></ul>",
        "div4": "Najczęstsze przypadki zastosowania to:",
        "div4b": "<b>Twoje zdjęcia nie są jeszcze hostowane</b>, ale masz subskrypcję ArcGIS. Najlepszym wyborem będzie skorzystanie z hostowanej usługi obiektowej. Podobnie jak serwisy udostępniające zdjęcia, zapewnimy optymalizację Twoich obrazów w celu uzyskania zdjęć niewymagających długiego wczytywania, a Ty będziesz mieć dostęp do wszystkich funkcji administracyjnych i zarządzania danymi oferowanych przez platformę ArcGIS.",
        "div5": "<b>Nie jesteś członkiem instytucji</b> — najpierw musisz przesłać swoje obrazy do witryny udostępniającej zdjęcia lub na własny serwer internetowy. Następnie kreator pomoże Ci w użyciu tych obrazów, które nadal będą hostowane w oryginalnej lokalizacji.",
        "div6": "<b>Chcesz ponownie użyć istniejącej już usługi obiektowej</b> przechowującej obrazy w postaci załączników lub zawierającej odnośniki do obrazów zewnętrznych. Szczegółowe informacje znajdują się w poniższej sekcji.",
        "div7": "<b>Jesteś użytkownikiem poprzedniej wersji</b> szablonu mapy wycieczki i masz już plik CSV zawierający odnośniki do obrazów i miniatury. Będziesz mieć możliwość zaimportowania go i dopracowania danych. Kreator obsługuje jedynie pliki CSV korzystające z szerokości/długości geograficznej. Plików CSV bazujących na danych adresowych można nadal używać za pomocą mapy internetowej (patrz poniższa sekcja).",
        "div8": "Importowanie z internetowych serwisów udostępniających zdjęcia",
        "div9a": "Facebook nie jest już obsługiwany, ${learn}.",
        "learn": "więcej informacji",
        "div9": "Operacja importowania tworzy odnośniki do już hostowanych obrazów poprzez zapisanie ich adresów URL w zbiorze obiektów mapy internetowej. Obrazy te nie są przechowywane w ArcGIS Online. Jeśli nie można uzyskać dostępu do hostowanych obrazów, nie będą one dostępne na mapie wycieczki i wyświetlany będzie obrazek zastępczy „Obraz niedostępny”. W zależności od dostawcy używanego serwisu udostępniania zdjęć dostępna lub niedostępna może być funkcja importowania do mapy wycieczki nazwy, opisu i lokalizacji obrazów. Te atrybuty są przechowywane na mapie internetowej, dlatego zmiany dokonywane w usługach internetowych nie będą widoczne na mapie wycieczki.",
        "div10": "Przechowywanie obrazów na serwerze WWW",
        "div11": "Jeśli zdecydujesz się hostować swoje obrazy na własnym serwerze internetowym (nie będą one pobierane z serwisu Flickr ani przesyłane bezpośrednio do wycieczki), konieczne będzie ręczne utworzenie ich miniatur. Używanie obrazów w pełnej rozdzielczości jako miniatur powoduje zmniejszenie wydajności. Następujące <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>często zadawane pytania</a> zawierają wskazówki dotyczące zmiany rozmiaru obrazów, jeśli dostęp do nich będzie uzyskiwany bezpośrednio w Internecie za pomocą adresów URL.",
        "div12": "Korzystanie z istniejących danych o miejscu",
        "div13": "Jeśli istnieją dane o miejscu, jak np. lista miejsc w arkuszu kalkulacyjnym lub warstwa punktowa GIS, można użyć tych danych w formacie CSV do utworzenia Mapy wycieczki. W takim wypadku Twoje obrazy muszą być dostępne bezpośrednio za pośrednictwem adresów URL przechowywanych jako wartości w pliku CSV. Szablon CSV można pobrać w oknie dialogowym Opcje zaawansowane przy pierwszym uruchomieniu kreatora mapy wycieczki. Swój plik CSV możesz przesłać do tego okna dialogowego.",
        "div14": "Obsługiwane wartości nazw pól to (wielkie i małe litery nie są rozróżniane):",
        "div151": "Nazwa",
        "div152": "Opis",
        "div153": "Obraz",
        "div154": "Miniatura",
        "div155": "Kolor ",
        "div16": "Jeśli aplikacja nie znajdzie pasujących pól podczas korzystania z usługi obiektowej, przeglądarka zacznie działać dopiero po skonfigurowaniu pól używanych przez kreator. Warstwy z plików CSV i shape dodawane do mapy internetowej muszą mieć wszystkie wymagane pola, w przeciwnym wypadku kreator nie będzie działać.",
        "div162": "Podczas korzystania z usługi obiektowej, która przechowuje obrazy jako załączniki<b>, używane są tylko obiekty z dwoma załącznikami</b>. Pierwszy załącznik definiuje główny obraz, a drugi — miniaturę.",
        "div17": "Pola obrazu i miniatury są wymagane w przypadku usług obiektowych bez załączników i opcjonalne (ale zdecydowanie zalecane) w przypadku usług obiektowych z załącznikami. Jeśli dla Twojej usługi zostały włączone załączniki, kreator umożliwi Ci przesłanie obrazów w postaci załączników. W przeciwnym wypadku możliwa będzie edycja jedynie adresu URL obrazu i miniatury.",
        "div172": "Jeżeli pola obrazu i załącznika są dostępne, będą zawsze używane, a zapytania dotyczące załączników w usłudze obiektowej nie będą wysyłane.",
        "div173": "Przykładowe pliki CSV i shape można pobrać z",
        "div174": "Dalsze informacje są dostępne w sekcji <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>Często zadawane pytania</a>.",
        "div18": "Tworzenie hostowanej usługi obiektowej z pliku CSV lub shape",
        "div19": "Gdy tworzysz hostowaną usługę obiektową z pliku CSV lub shape, obsługa załączników nie jest domyślnie włączona. Aby ją włączyć, otwórz stronę szczegółów usługi obiektowej, kliknij małą strzałkę w sekcji warstw, co spowoduje wyświetlenie odpowiedniej opcji. Wówczas mapa wycieczki nadal będzie używać obrazów i miniatur, do których utworzono odnośniki za pomocą atrybutów. Ewentualnie, jeśli chcesz przesłać obrazy jako załączniki do usługi obiektowej, możesz użyć w tym celu dwóch przycisków w panelu obrazów (\"Zmień obraz\" i \"Zmień miniaturę\").",
        "div20": "Obsługiwane materiały wideo i formaty obrazów",
        "div21": "W przypadku pobierania obrazów z serwisu Flickr mapa wycieczki automatycznie pobiera te obrazy jako pliki .jpg. W przypadku przesyłania obrazów do kreatora mapy wycieczki muszą one być w formacie .jpg lub .jpeg. W przypadku odwoływania się do obrazów umieszczonych w Internecie bezpośrednio za pośrednictwem adresów URL obsługiwanymi formatami są .jpg, .jpeg, .png, .gif i .bmp. Materiały wideo w serwisie YouTube są obsługiwane bezpośrednio.",
        "div22": "Szablon mapy wycieczki nie zawiera odtwarzacza wideo, dlatego należy użyć zewnętrznego odtwarzacza wideo z ulubionej usługi hostowania plików wideo (znajdź opcję osadzania wideo i skopiuj adres URL z podanego kodu). Jeżeli chcesz hostować wideo samodzielnie, możesz utworzyć stronę HTML zawierającą odtwarzacz wideo taki jak <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Interaktywny kreator nie udostępnia okna dialogowego do dodawania wideo podczas korzystania z usług obiektowych z załącznikami. Można jednak w tym celu edytować dane poza interaktywnym kreatorem. Pliki multimedialne będą traktowane jak wideo, jeżeli w przeglądarce map ArcGIS.com zmodyfikujesz pola obrazów tak, by wskazywały zewnętrzne wideo i dodasz specjalny parametr na końcu adresu URL (#isVideo).",
        "div24": "Nadal wymagane będą dwa prawidłowe załączniki obrazów — w przeciwnym razie punkt nie będzie używany. Bez pól obrazu i miniatury nie można korzystać z wideo, gdy w usłudze obiektowej używane są załączniki."
      },
      "tab3": {
        "title": "Dostosowanie",
        "div1": "Kreator wyposażony jest w kilka opcji dostosowywania, do których dostęp można uzyskać, klikając przycisk USTAWIENIA znajdujący się w górnym panelu. Jeśli nie znajdziesz tam odpowiedniej opcji, dostępna jest również wersja do pobrania, którą można utworzyć na serwerze internetowym i dostosować do własnych potrzeb.",
        "div2": "Zalecane jest korzystanie z wersji hostowanej z wyjątkiem, gdy:",
        "div3": "<li>nie oferuje ona odpowiedniej opcji dostosowania interfejsu użytkownika, np. zmiany obrazu tła nagłówka;</li><li>jesteś programistą i chcesz udoskonalić aplikację.</li>",
        "div4": "Wersję do pobrania można konfigurować z poziomu mapy internetowej lub identyfikatora aplikacji tworzenia map internetowych. Główne przypadki zastosowania tej opcji:",
        "div41": "Mapa wycieczki budowana jest przy użyciu interaktywnego kreatora w hostowanym środowisku, a szablon konfigurowany jest przy użyciu identyfikatora aplikacji tworzenia map internetowych. Zostaną zastosowane ustawienia zdefiniowane przy użyciu interaktywnego kreatora.",
        "div42": "Mapa wycieczki budowana jest poza interaktywnym kreatorem, a szablon konfigurowany jest przy użyciu identyfikatora mapy internetowej. Aby uzyskać informacje na temat konfigurowania szablonu, należy przeczytać dokumentację.",
        "div43": "Interaktywny kreator jest dostępny w wersji do pobrania, jednak w przypadku takich przeglądarek jak Internet Explorer w wersjach starszych niż 10 występują pewne techniczne ograniczenia.",
        "div5": "Aby pobrać najnowszą wersję szablonu i dowiedzieć się więcej na temat sposobu jego użytkowania, odwiedź <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>stronę projektu GitHub</a>."
      },
      "tab4": {
        "title": "Wskazówki",
        "div0": "Obsługiwane przeglądarki",
        "div0a": "Przeglądarka map wycieczek jest obsługiwana w przeglądarce IE8+. Interaktywny kreator jest obsługiwany w przeglądarce IE9+. Prowadzimy aktywnie testy z użyciem wszystkich najważniejszych przeglądarek, ale w razie trudności zalecamy używanie przeglądarki Chrome.",
        "div0b": "W razie trudności prosimy o kontakt z nami. Aby zminimalizować interakcję z interfejsem kreatora, można tymczasem skorzystać z szablonu CSV.",
        "div1": "Obrazy",
        "div2": "Wprawdzie na jednej mapie wycieczki można użyć obrazów o różnych rozmiarach, kształtach i orientacji, jednak zalecane jest używanie obrazów w orientacji poziomej, a nie pionowej. Najlepiej pasują obrazy o proporcjach 4:3. W kompozycjach Panel trzyczęściowy i Zintegrowana, w których podpis nachodzi na obraz, użycie obrazów w orientacji pionowej może spowodować zasłonięcie większej części obrazu przez podpis. W kompozycjach Panel trzyczęściowy i Zintegrowana zalecane jest w miarę możliwości używanie tego samego rozmiaru i kształtu dla wszystkich obrazów. W ten sposób podczas wycieczki użytkowników nie będą rozpraszały różne rozmiary obrazów.",
        "div2a": "Zalecamy, aby maksymalny rozmiar głównych obrazów wynosił 1000 x 750 pikseli oraz 140 x 93 pikseli w przypadku miniatur.",
        "div3": "Formatowanie tekstu podpisów za pomocą znaczników HTML",
        "div4": "W podpisach można wprowadzać znaczniki HTML, aby zdefiniować formatowanie i łącza. Na przykład następujące znaczniki dodają zielone hiperłącze:",
        "div4aa": "<b>Utwórz okładkę dla wycieczki w kompozycji Panel boczny</b><br>Kompozycja Panel boczny obsługuje opcjonalną okładkę pozwalającą przyciągać uwagę odbiorcy za pomocą atrakcyjnego wizualnie, pełnoekranowego obrazu. Aby skonfigurować okładkę dla wycieczki w kompozycji Panel boczny, najpierw dodaj do wycieczki niektóre ze swoich punktów. Następnie kliknij przycisk Organizuj i upewnij się, że w wyświetlonym oknie dialogowym punkt wycieczki, który będzie wykorzystany do zdefiniowania okładki, jest pierwszym punktem wycieczki. Z kolei w oknie dialogowym kliknij pole 'Użyj pierwszego punktu jako okładki'. Nazwa pierwszego punktu wycieczki będzie tytułem widocznym na okładce, podpis dla tego punktu stanie się podtytułem, a obraz odpowiadający temu punktowi zostanie użyty jako obraz okładki. Na okładce nie są obsługiwane materiały wideo. Dalsze informacje są dostępne w sekcji <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>Często zadawane pytania</a>.</a>",
        "div4a": "Napisz dobrze brzmiące napisy dla swojej wycieczki",
        "div4b": "Poświęć trochę czasu, aby w ciekawy sposób opisać swoją wycieczkę. Jest to dobry sposób, aby zainteresować nią innych użytkowników, informując ich co mogą podczas niej odkryć. W tym miejscu można także umieścić informację na temat stanu, województwa lub państwa, w którym ma miejsce wycieczka. Nie można zakładać, że wszyscy będą wiedzieć, gdzie dokładnie znajduje się dane miasto lub miejscowość. Jednak podtytuł nie powinien być zbyt długi. Jeśli nie możesz wymyślić dobrego podtytułu, pozostaw to pole puste. W przeciwieństwie do kompozycji Panel trzyczęściowy i Zintegrowana kompozycja Panel boczny nie obsługuje podtytułu w swoim nagłówku. W przypadku użycia opcji okładki w kompozycji Panel boczny podpis dla pierwszego punktu wycieczki jest widoczny na okładce i służy jako podtytuł dla wycieczki.",
        "div5": "Warstwy pomocnicze",
        "div6": "Można dodać dodatkowe warstwy pomocnicze oferujące kontekst dla mapy wycieczki. Warstwy te mogą zawierać inne obiekty geograficzne, które mapa wycieczki ma przedstawiać oprócz punktów, takie jak analizowany obszar, trasa piesza lub trasa przejazdu łącząca punkty wycieczki itd. W szablonie mapy wycieczki te dodatkowe warstwy pomocnicze są wyświetlane za pomocą symboli skonfigurowanych dla mapy internetowej, ale zdefiniowane dla warstw okna podręczne nie są dostępne. Aby dodać warstwy pomocnicze do wycieczki, zapisz swoją pracę i zamknij kreator mapy wycieczki. Następnie otwórz mapę internetową użytą w Twojej wycieczce. Możesz ją znaleźć na stronie Moje zasoby ArcGIS lub w sekcji Moje narracje witryny internetowej Story Maps (Mapy narracyjne).",
        "div7": "Twoja wycieczka powinna być krótka i atrakcyjna",
        "div8": "Liczba lokalizacji wycieczek jest ograniczona do 99 punktów. Większość map wycieczek będzie prezentowała znacznie krótsze trasy. Nie oczekuj, że odbiorcy będą chcieli śledzić dużą liczbę punktów wycieczki. Dla ciebie dany temat może być fascynujący, nie wszyscy jednak muszą podzielać tę opinię!",
        "div10": "Tryb osadzania",
        "div11": "Jeśli chcesz osadzić szablon w innej witrynie przy użyciu ramki iframe, dodanie opcjonalnego parametru \"&embed\" na końcu adresu URL spowoduje usunięcie nagłówka.",
        "div12": "Należy unikać korzystania z elementu iFrame o niewielkiej szerokości, ponieważ spowoduje on przełączenie się mapy wycieczki do widoku responsywnego dla małych ekranów, takiego jaki jest używany dla urządzeń przenośnych. Aby ułatwić użytkowanie mapy, po osadzeniu mapy wycieczki najlepiej nadal dodawać obok osadzonej wycieczki łącze, dzięki czemu użytkownicy będą mogli uruchomić wycieczkę na pełnym ekranie."
      },
      "tab5": {
        "title": "Publikacja",
        "div1": "Po zakończeniu wszystkich czynności nie zapomnij udostępnić mapy wycieczki odbiorcom za pomocą przycisku UDOSTĘPNIJ lub strony elementu aplikacji w ArcGIS Online.",
        "div2a": "Udostępnianie wycieczki przy pomocy kreatora",
        "div2b": "Przycisk UDOSTĘPNIJ zaktualizuje aplikację i elementy mapy internetowej. Jeśli dane wycieczki przechowywane są w elemencie Usługi obiektowej, zostaną one również zaktualizowane. Jeśli dodane zostały inne warstwy przy pomocy przeglądarki map ArcGIS.com, nie zostaną one zaktualizowane. Może to sprawić, że wycieczka nie będzie udostępniana w oczekiwany sposób. Nie będą aktualizowane elementy, które posiadają już wymagane (lub wyższe) uprawnienia.",
        "div2c": "Udostępnianie wycieczki w ArcGIS Online",
        "div2d": "Podczas udostępniania aplikacji za pośrednictwem ArcGIS Online, w razie potrzeby, system poprosi o uaktualnienie zasobów zależnych (mapy internetowej, usługi obiektowej, warstwy dekoracyjnej), które nie są udostępnione w ten sam sposób. Jeśli mapa wycieczki jest publicznie dostępna, ale jeden z zasobów nie został udostępniony wszystkim odbiorcom, użytkownicy zostaną przekierowani do strony logowania usługi ArcGIS Online.",
        "div3t": "Zabezpieczenia Usług obiektowych",
        "div3a": "Jeśli korzystasz z hostowanej usługi obiektowej utworzonej za pomocą kreatora mapy wycieczki, aplikacja zarządza bezpieczeństwem usługi, dlatego pozostajesz jedyną osobą, która ma uprawnienia do edycji, nawet jeśli udostępnisz usługę publicznie.",
        "div3t2": "Zanim podzielisz się swoją wycieczką z odbiorcami",
        "div3": "Upewnij się, że wycieczka działa poprawnie bez konieczności logowania się na konto ArcGIS.com. Adres URL, który będzie używany, nie powinien przekierowywać do strony logowania ani do trybu kreatora.",
        "div4": "Warto sprawdzić wygląd mapy wycieczki wyświetlanej za pomocą urządzenia iPad trzymanego w orientacji poziomej, aby upewnić się, że będzie ona poprawnie wyświetlać się na tym popularnym urządzeniu. Umożliwia to sprawdzenie, czy podpisy nie zajmują zbyt dużej części obrazów. Można także w ten sposób sprawdzić czy napisy są odpowiednio dopasowane (w przypadku, jeśli są one zbyt długie, zostaną one obcięte).",
        "div5a": "Rekomendacje dotyczące wyszukiwania",
        "div5b": "Aby pomóc osobom wyszukującym w ArcGIS Online znaleźć mapę wycieczki, zalecamy dodanie znacznika „story map” na stronie elementu aplikacji mapy wycieczki (nie zaś na stronie elementu mapy internetowej), a także znaczników zawierających nazwę stanu, regionu lub województwa, dla którego utworzono wycieczkę, nazwę kraju (jeśli jest ona położona poza USA) oraz znaczników tematycznych, takich jak „sztuka publiczna”, „przewodnik turystyczny”, czy „miejsca historyczne”. Znaczniki te również pomagają pracownikom firmy Esri w znajdowaniu nowych, ciekawych przykładów wycieczek do prezentowania w galeriach oraz promowania w mediach społecznościowych. Najlepiej przesyłać także estetyczne miniatury na swoją stronę elementu aplikacji, takie jak miniatury zrzutów ekranu wycieczki lub jedno ze zdjęć w niej umieszczonych. Obraz ten zostanie automatycznie użyty, jeśli mapa wycieczki zostanie dodana do galerii ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Wycieczka została zapisana",
      "manageStory": "Zarządzanie narracją",
      "manageStoryA1": "Wskazówka: Przy użyciu łącza %LINK1% można sprawdzić narracje pod kątem błędów, zmienić sposób jej udostępniania, nadać dobry wygląd w mediach społecznościowych itp. Więcej informacji na temat elementu Moje narracje %LINK2%.",
      "manageStoryA1V1": "Moje narracje",
      "manageStoryA1V2": "tutaj",
      "shareTitle": "Udostępnianie wycieczki",
      "sharePrivateHeader": "Wycieczka nie jest udostępniona. Czy chcesz ją udostępnić?",
      "sharePrivateBtn1": "Udostępnij publicznie",
      "sharePrivateBtn2": "Udostępnij mojej instytucji",
      "sharePrivateProgress": "Trwa udostępnianie...",
      "sharePrivateErr": "Udostępnianie nie powiodło się. Spróbuj ponownie lub",
      "sharePrivateOk": "Udostępnianie po aktualizacji, trwa wczytywanie...",
      "sharePreviewAsUser": "Zobacz podgląd",
      "shareHeader1": "Wycieczka jest <strong>dostępna publicznie</strong>.",
      "shareHeader2": "Wycieczka jest dostępna dla członków instytucji (wymagane jest logowanie).",
      "shareLinkHeader": "Udostępnianie wycieczki",
      "shareLinkOpen": "OTWÓRZ",
      "shareA1": "Użyj przycisku %SHAREIMG% na <a href='%LINK1%' target='_blank'>stronie elementu aplikacji</a>. Jeśli nie chcesz dłużej udostępniać mapy internetowej, użyj <a href='%LINK2%' target='_blank'>strony elementu mapy internetowej</a>.",
      "shareWarning": "Udostępnianie %WITH% zostało wyłączone, ponieważ nie jesteś właścicielem <a href='%LINK%' target='_blank'>mapy internetowej</a>.",
      "shareWarningWith1": "publicznie",
      "shareWarningWith2": "publicznie i instytucji",
      "viewStory": "Wyświetl narrację"
    },
    "locator": {
      "error": "Lokalizacja niedostępna"
    },
    "saveErrorSocial": {
      "title": "Udostępnianie aktualizacji w serwisach społecznościowych",
      "panel1": "Wygląd narracji w serwisach społecznościowych został poprawiony, ale tytuł elementu aplikacji internetowej ArcGIS jest inny niż tytuł narracji.",
      "panel1tooltip": "Po zdefiniowaniu tytułu, podsumowania i obrazu miniatury, narracja będzie wyglądała następująco:",
      "panel2": "Którego tytułu chcesz używać w serwisach społecznościowych:",
      "panel2q1": "Tytuł narracji (zalecane)",
      "panel2q1tooltip": "Po wybraniu tej opcji tytuł elementu zostanie zmodyfikowany zgodnie z tytułem narracji, a dodatkowe zmiany w kreatorze zostaną zsynchronizowane.",
      "panel2q2": "Tytuł elementu",
      "panel3": "Aby dodatkowo poprawić wygląd narracji w serwisach społecznościowych, użyj karty ${MYSTORIES} w celu dodania podsumowania i obrazu miniatury.",
      "panel4": "Nie ostrzegaj ponownie dla tej narracji",
      "mystories": "Moje narracje",
      "btnSave": "Zapisz"
    },
    "bannerNotification": {
      "learnMore": "Dowiedz się więcej",
      "close": "Zamknij",
      "dontShowAgain": "Nie pokazuj tej wiadomości ponownie"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Istotny komunikat dotyczący bezpieczeństwa internetowego i aplikacji Story Maps (Mapy narracyjne)",
      "s1h1": "Firma Esri rozbudowuje zabezpieczenia map narracyjnych (Story Maps)",
      "s1p1": "Mapy narracyjne funkcjonują w Internecie i społeczność internetowa stale pracuje nad opracowaniem i zaimplementowaniem lepszych zabezpieczeń. Protokół HTTPS, który udostępnia bezpieczne połączenie dla zasobów przesyłanych przez Internet, pojawia się jako oczekiwany sposób dostępu do zasobów internetowych Większość nowoczesnych przeglądarek obecnie wyświetla komunikaty ostrzegawcze, gdy jest używany protokół HTTP, a nie HTTPS. Z uwagi na ten nowy standard zdecydowanie zaleca się stosowanie łączy HTTPS podczas tworzenia i udostępniania map narracyjnych, a także używanie tylko adresów URL odwołujących się do protokołu HTTPS podczas osadzania zasobów internetowych lub łączenia się z obrazami zawartymi na mapie narracyjnej.",
      "s1p2": "W praktyce oznacza to, że dostęp do mapy narracyjnej i jej zasobów (w tym obrazów, warstw, osadzonych aplikacji i witryn internetowych) powinien być uzyskiwany za pomocą łączy rozpoczynających się od HTTPS, a nie od HTTP. Jest to najlepsze rozwiązanie dla czytelników, ponieważ większość przeglądarek internetowych wskaże, że narracje są bezpieczne.",
      "s2h1": "Co mam zrobić?",
      "s2p1": "Firma Esri pracuje nad tym, aby niniejsza zmiana w jak najmniejszym stopniu wpływała na pracę autorów i użytkowników map narracyjnych. Obecnie w kreatorach map narracyjnych i w elemencie Moje narracje są dostępne narzędzia pomagające znaleźć niezabezpieczone zasoby (HTTP) w narracjach i przedstawiające zalecenia dotyczące sposobu odwoływania się do nich. Należy sprawdzić narracje pod kątem niezabezpieczonych zasobów i możliwie najszybciej zaktualizować je do protokołu HTTPS.",
      "action1": "Zamknij",
      "action2": "Sprawdź teraz moje narracje",
      "action3": "Dowiedz się więcej"
    },
    "embedBar": {
      "share": "Udostępnij",
      "fullScreen": "Pełny ekran",
      "enlarge": "Powiększ",
      "newTab": "Otwórz w nowej karcie",
      "tagline": "Mapa narracyjna",
      "exitFullScreen": "Opuść tryb pełnoekranowy"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Czy możemy o coś prosić? Pomoże to nadawać przyszły kształt mapom narracyjnym.",
      "s1h1": "Podziel się z nami swoją opinią, weź udział w kształtowaniu przyszłości",
      "s1p1": "Przekazane opinie są dla nas najważniejszym źródłem informacji, a dzięki lepszej znajomości Twoich oczekiwań możemy ulepszać mapy narracyjne. Będziemy wdzięczni za wzięcie udziału w tej trzyminutowej ankiecie.",
      "s2p1": "Jak zawsze, dziękujemy też za korzystanie z map narracyjnych firmy Esri!",
      "action1": "Zamknij",
      "action2": "Wypełnij ankietę"
    },
    "licenseChange2018": {
      "noAccess": "Twoje konto (%USER_NAME%) nie jest licencjonowane do otwierania mapy narracyjnej, która nie jest publiczna. Poproś administratora instytucji o przypisanie typu użytkownika, który obejmuje licencję na mapy narracyjne lub licencję na kluczowe aplikacje dodatkowe."
    },
    "storyTellerUserType": {
      "notCreatorError": "Twoje konto (%USER_NAME%) nie ma licencji na użytkowanie kreatorów klasycznych map narracyjnych. Poproś administratora instytucji o przypisanie Tobie typu użytkownika Creator (Twórca)."
    }
  }
});