define({
  "viewer": {
    "loading": {
      "step1": "TÖRTÉNET BETÖLTÉSE",
      "step2": "ADATOK BETÖLTÉSE",
      "step3": "TÚRA INICIALIZÁLÁSA",
      "loadBuilder": "VÁLTÁS SZERKESZTŐ MÓDRA",
      "redirectSignIn": "ÁTIRÁNYÍTÁS A BEJELENTKEZÉSI OLDALRA",
      "redirectSignIn2": "(ide lesz átirányítva bejelentkezés után)",
      "fail": "Nem sikerült a Map Tour betöltése",
      "failButton": "Próbálja újra"
    },
    "errors": {
      "boxTitle": "Hiba történt",
      "portalSelf": "Helyreállíthatatlan hiba: Nem sikerült lekérni a portál konfigurációját",
      "invalidConfig": "Helyreállíthatatlan hiba: Érvénytelen konfiguráció",
      "invalidConfigOwner": "Helyreállíthatatlan hiba: Érvénytelen konfiguráció (jogosult tulajdonos szükséges)",
      "invalidConfigNoWebmap": "Helyreállíthatatlan hiba: Érvénytelen konfiguráció (a webtérkép vagy az alkalmazás azonosítója nincs megadva az index.html fájlban)",
      "invalidConfigNoAppDev": "A Webes térképkészítő alkalmazás azonosítója vagy a webtérkép nincs megadva az URL paramétereiben (?appid= vagy ?webmap=). Fejlesztői módban az index.html fájlban található appid és webmap konfiguráció figyelmen kívül van hagyva.",
      "createMap": "Nem sikerült létrehozni a térképet",
      "invalidApp": "Helyreállíthatatlan hiba: A történetet nem lehet betölteni",
      "noLayer": "A webtérkép nem tartalmaz érvényes adatréteget a Map Tour-hoz.",
      "noLayerMobile": "A Map Tour szerkesztő nem támogatott ennél a kijelzőméretnél. Ha lehetséges, módosítsa a böngésző méretét úgy, hogy elérhető legyen a szerkesztő, vagy használjon nagyobb képernyővel rendelkező eszközt a történet összeállításához.",
      "noLayerMobile2": "A Map Tour szerkesztő használatához fordítsa el fekvő tájolásra az eszközt.",
      "noLayerView": "Üdvözli a Map Tour webes alkalmazás.<br />A történet még nincs konfigurálva.",
      "appSave": "Nem sikerült a történet mentése",
      "mapSave": "Nem sikerült a webtérkép mentése",
      "featureServiceLoad": "Nem sikerült a vektoros adatszolgáltatás betöltése",
      "notAuthorized": "Ön nem jogosult a történet elérésére",
      "notAuthorizedBuilder": "Ön nem jogosult a Map Tour szerkesztő használatára.",
      "oldBrowserTitle": "A böngesző támogatása nem teljes körű",
      "noBuilderIE8": "A Map Tour szerkesztő nem támogatott a 9-es verzió előtti Internet Explorerben.",
      "ie10Win7Explain": "A Map Tour interaktív szerkesztő nem támogatott a Windows 7 rendszerben használt Internet Explorer 10-es verzióban, amikor az adatforrás egy csatolmányokkal rendelkező vektoros adatszolgáltatás. Ha csatolmányokkal rendelkező vektoros adatszolgáltatást szeretne használni, akkor <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>meg kell adnia a dokumentum kiterjesztését az Internet Explorer 9 beállításainak megfelelően</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>vissza kell lépnie az Internet Explorer 9-es verziójára</a>, vagy frissítenie kell a Windows 8 rendszerre.",
      "oldBrowserExplain": "Ez a böngésző nem támogatja a bélyegképek automatikus létrehozását a Map Tour-ba feltöltött képekből. Létrehozhat Map Tour-t ebben a böngészőben, de külön kell megadnia bélyegképet mindegyik feltöltött képhez.",
      "oldBrowserExplain2": "A felhasználói élmény javításához <a href='http://browsehappy.com/' target='_blank'>frissítse a böngészőt</a>, vagy <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>kapcsolja be a Google Chrome Frame for Internet Explorer beépülő modult</a>.",
      "oldBrowserExplain3": "A Map Tour szerkesztő nem működik a Windows XP rendszerben használt Internet Explorer 10-es verzióban.",
      "oldBrowserClose": "Bezárás",
      "noViewerIE2": "Ezt a történetet egy régebbi, nem támogatott böngészőben próbálja megtekinteni. Előfordulhat, hogy néhány vektoros elem nem fog megfelelően működni, vagy váratlan hibák történhetnek. Azt javasoljuk, hogy frissítsen az Internet Explorer 11-es verziójára, vagy használjon más böngészőt, például a Chrome-ot.",
      "noViewerIE3": "2017 végén ez a történet már nem töltődik be ebben a böngészőben. A történet megtekintéséhez támogatott böngészőt kell használnia.",
      "attention": "Figyelem!"
    },
    "mobileHTML": {
      "showIntro": "CÍM MEGJELENÍTÉSE",
      "hideIntro": "CÍM ELREJTÉSE",
      "navList": "Lista",
      "navMap": "Térkép",
      "navInfo": "Média",
      "introStartBtn": "Kezdés"
    },
    "desktopHTML": {
      "storymapsText": "Egy story map",
      "builderButton": "Váltás a szerkesztő módra",
      "facebookTooltip": "Megosztás Facebookon",
      "twitterTooltip": "Megosztás Twitteren",
      "bitlyTooltip": "Rövid hivatkozás lekérése",
      "bitlyStartIndex": "Hivatkozás a jelenlegi helyre",
      "tooltipAutoplayDisabled": "Ez nem érhető el automatikus lejátszási módban",
      "autoplayLabel": "Automatikus lejátszási mód",
      "autoplayExplain1": "Az automatikus lejátszási mód meghatározott időközönként léptetve halad végig a történeten. Ez ideális megoldás a nyilvános monitorokon történő megjelenítéshez, de vegye figyelembe, hogy más helyzetekben megnehezítheti a történet olvasását. Ez a funkció kisméretű kijelzőkön nem támogatott.",
      "autoplayExplain2": "Amikor aktív ez a mód, vezérlők érhetők el a történet lejátszásához/szüneteltetéséhez, valamint a navigáció sebességének beállításához.",
      "takeTourText": "Vegyen részt egy túrán",
      "backToStart": "Vissza az elejére"
    },
    "builderHTML": {
      "panelHeader": "TÖRTÉNET KONFIGURÁCIÓJA",
      "buttonSave": "MENTÉS",
      "buttonSettings": "Beállítások",
      "buttonShare": "Megosztás",
      "buttonView": "Megjelenítési mód",
      "buttonItem": "A webes alkalmazás elemének megnyitása",
      "buttonHelp": "Súgó",
      "buttonOrganize": "Rendezés",
      "buttonOrganizeAndCover": "Bemutatópontok rendezése és címlap hozzáadása",
      "buttonAdd": "Hozzáadás",
      "buttonImport": "Importálás",
      "buttonImportDisabled": "Az importálás nem érhető el képfeltöltéskor. Kép feltöltéséhez kattintson a Hozzáadás gombra.",
      "dataEditionDisabled": "Az adatok szerkesztése le van tiltva ennél a CSV-adatforrásnál",
      "dataSourceWarning": "Megváltozott a Map Tour adatrétege. Ha a vektoros elemek azonosítói nem egyeznek, akkor vissza kell állítania a sorrendet és a rejtett pontokat a <b>Rendezés</b> funkcióval. Ha a mezőnevek különböznek, akkor vissza kell állítania a mezőbeállításokat a <b>Beállítások adatokat tartalmazó lapján</b>.",
      "organizeWarning": "Az interaktív szerkesztőn kívül hozzáadott egy vagy több pont rejtett.",
      "dataPicError0a": "Ez a túra <b>%NB%</b> nem megfelelő URL-címet tartalmaz a képeknél.",
      "dataPicError0b": "Lehet, hogy ez a túra <b>%NB%</b> nem megfelelő URL-címet tartalmaz a képeknél.",
      "dataPicError1": "A Map Tour-hoz mostantól úgy kell megadni a képek URL-címét, hogy az a következő kiterjesztések egyikével végződjön: .jp(e)g, .png, .gif vagy .bmp.",
      "dataPicError2": "Ez a követelmény nem vonatkozik a meglévő, közzétett Map Tour-ra. Az interaktív szerkesztő használatához azonban előbb meg kell szüntetnie az URL-címek problémáját a következő módszerek valamelyikével:",
      "dataPicError3": "URL-címek szerkesztése",
      "dataPicError4": "Ez az <i>#isImage</i> toldalékot helyezi el a képekre mutató, nem támogatott URL-címek végén. A legtöbb szerver támogatja az URL-címek toldalékait. A művelet végrehajtása után azonban a pontokon végighaladva ellenőriznie kell, hogy a képek módosított URL-címei működnek-e. Ha mindegyik kép betöltődik, mentheti a Map Tour-t. Ha <b>vannak hibás képek, ne mentse a Map Tour-t</b>. Ehelyett töltse be újból a szerkesztőt, és hajtsa végre a második műveletet.",
      "dataPicError5": "Csak képek engedélyezése a túrában",
      "dataPicError6": "A beállítás hatására az összes URL-cím képnek lesz tekintve, de nem fog tudni videókat hozzáadni az interaktív szerkesztő használatával. Ez a művelet visszafordítható, ha a későbbiekben videót is szeretne hozzáadni.",
      "dataPicError7": "A Map Tour-ban a beállítás szerint csak képek jeleníthetők meg, videók nem használhatók. Ha meg szeretné szüntetni ezt a korlátozást, a Map Tour mentése előtt ellenőrizze, hogy a képek továbbra is megfelelően töltődnek-e be. A későbbiekben visszaállíthatja a korlátozást, ha szükséges.",
      "dataPicError8": "A „csak képek” korlátozás megszüntetése",
      "dataPicError9": "Ha ezek az URL-címek videókra mutatnak, figyelmen kívül hagyhatja ezt a figyelmeztetést. Ha képekre mutatnak, végre kell hajtania a következő két művelet egyikét:",
      "modalCancel": "Mégse",
      "modalApply": "Alkalmaz",
      "organizeHeader": "A túra rendezése",
      "organizeGeneralCaption": "A túraútvonalpontokat húzással rendezheti át",
      "organizeDelete": "Törlés",
      "organizeHide": "Elrejtés",
      "organizeReset": "Rendezés és rejtett pontok visszaállítása",
      "addMaxPointReached": "Elérte a beállított ikonok által engedélyezett pontok maximális számát, és nem vehet fel további túraútvonalpontot.<br /><br />Vegye figyelembe, hogy ha törli a meglévő pontokat, újból be kell töltenie a történetet.",
      "addMaxPointReachedMobile": "Elérte az engedélyezett pontok maximális számát, és nem veheti fel ezt a képet.",
      "addClose": "Bezárás",
      "addHeader": "Új túraútvonalpont hozzáadása",
      "addTabPicture": "Média",
      "addTabInformation": "Információ",
      "addTabLocation": "Hely",
      "addSelectCaption": "Válasszon ki vagy húzzon ide egy képet",
      "addNoteVideo": "A videók használatának ismertetését lásd a súgóban",
      "addSelectCaptionNoFileReader": "Kép kiválasztása",
      "addChangePhoto": "Kép és bélyegkép megváltoztatása",
      "addPictureResolutionIntro": "A kép felbontása nagyobb a szükségesnél:",
      "addPictureResolutionOldBrowser": "A kép felbontása nagyobb a szükségesnél. Optimalizálja a Map Tour megjelenítését a(z) %RECOMMENDED_RES% értéknél kisebb felbontás megadásával.",
      "addPictureResolutionResize": "Kép felbontásának módosítása a következőre: %RESOLUTION%",
      "addPictureResolutionKeep": "Eredeti felbontás megőrzése: %RESOLUTION%",
      "addSelectThumbnail": "Bélyegkép kiválasztása",
      "addNoThumbSelected": "Nincs kiválasztott bélyegkép",
      "addThumbSelected": "Kiválasztva",
      "addCameraSettingsHeader": "KAMERA BEÁLLÍTÁSAI",
      "addThumbnailHeader": "BÉLYEGKÉP",
      "addLabelPicUrl": "Kép",
      "addLabelThumbUrl": "Bélyegkép",
      "addTextPlaceholderUrl": "Adja meg egy kép URL-címét",
      "addTextPlaceholderUrl2": "Adja meg egy YouTube-oldal URL-címét",
      "addTextPlaceholderUrl3": "Adja meg egy Vimeo-oldal URL-címét",
      "addTextPlaceholderUrl4": "Adja meg egy beágyazott videó URL-címét",
      "addLabelVideo": "Videó",
      "addMediaVideoOther": "Egyéb",
      "addMediaVideoHelp": "Ellenőrizze az URL-címet, és határozza meg az alapértelmezett bélyegképet",
      "addMediaVideoHelpTooltip1": "Az ellenőrzés sikerült",
      "addMediaVideoHelpTooltip2": "Nem sikerült az ellenőrzés",
      "addMediaVideoHelpTooltip4": "Keresse meg a videó beágyazási lehetőségét, és másolja ki a videó URL-címét a kódból",
      "addLabelName": "Név",
      "addLabelDescription": "Képaláírás",
      "addTextPlaceholder": "Írjon be valamit",
      "addLocatePlaceholder": "Cím vagy hely megkeresése",
      "addPinColor": "Szín",
      "addLatitude": "Szélesség",
      "addLongitude": "Hosszúság",
      "addLatitudePlaceholder": "például: 34,056",
      "addLongitudePlaceholder": "például: -117,195",
      "addUploading": "Túraútvonalpont feltöltése folyamatban",
      "addSave": "Túraútvonalpont hozzáadása",
      "addMobileUploading": "Kép feltöltése folyamatban",
      "addMobileName": "Név megadása",
      "addMobileNameMandatory": "Hiba, adjon meg egy nevet.",
      "addMobileError": "Elnézést, hiba történt.",
      "settingsHeader": "Beállítások",
      "settingsTabLayout": "Elrendezés",
      "settingsTabColor": "Színek",
      "settingsTabLogo": "Fejléc",
      "settingsTabFields": "Adatok",
      "settingsTabExtent": "Kiterjedés",
      "settingsTabZoom": "Nagyítási szint",
      "settingsLayoutExplain": "Válassza ki a kívánt elrendezést.",
      "settingsLayoutProfessional": "Három panel",
      "settingsLayoutModern": "Integrált",
      "settingsLayoutSidePanel": "Oldalsó panel",
      "settingsLayoutSelected": "Kiválasztott elrendezés",
      "settingsLayoutNew": "Új!",
      "settingsLayoutSelect": "Kiválasztás",
      "settingsLayoutNote": "Megjegyzendő, hogy a videókat használó pontokon a képaláírás mindig a videó alatt lesz elhelyezve, még akkor is, ha a vonatkozó beállítás nincs megadva.",
      "settingsLayoutLocBtn": "„Megkeresés” gomb megjelenítése",
      "settingsLayoutLocBtnHelp": "A legtöbb böngészőben támogatott. Csak akkor jelenik meg, ha a story map elérése HTTPS-kapcsolaton keresztül történik. Nem jelenik meg, ha a történet be van ágyazva.",
      "settingsColorExplain": "A megjelenés megváltoztatásához választhat egy előre beállított témát, vagy létrehozhat egy saját témát.",
      "settingsLabelColor": "Fejléc, tartalom és lábléc színe",
      "settingsLogoExplain": "Állítsa be igényei szerint  a fejlécet (a maximális méret 250 x 50 képpont).",
      "settingsLogoEsri": "Esri logója",
      "settingsLogoNone": "Nincs logó",
      "settingsLogoCustom": "Egyéni logó",
      "settingsLogoCustomPlaceholder": "Kép URL-címe",
      "settingsLogoCustomTargetPlaceholder": "Átirányító hivatkozás",
      "settingsLogoSocialExplain": "Állítsa be igényei szerint a fejléc jobb felső hivatkozását.",
      "settingsLogoSocialText": "Szöveg",
      "settingsLogoSocialLink": "Hivatkozás",
      "settingsLogoSocialDisabled": "Ezt a vektoros elemet letiltotta az adminisztrátor",
      "settingsDataFieldsExplain": "Válassza ki a fényképnév, a képaláírás és a szín mezőjét.",
      "settingsDataFieldsError": "Az alkalmazás nem tudja meghatározni a megfelelő nevet, képaláírást vagy színt. Válassza ki használandó mezőket. Ezek a beállítások később megváltoztathatók.",
      "settingsFieldsLabelName": "Név",
      "settingsFieldsLabelDescription": "Képaláírás",
      "settingsFieldsLabelColor": "Szín",
      "settingsFieldsReset": "Mezőválasztás visszaállítása",
      "settingsExtentExplain": "Állítsa be a Map Tour kezdőlapi kiterjedését az alábbi interaktív térképen.",
      "settingsExtentExplainBottom": "Az ön által definiált kiterjedés módosítani fogja a térkép kezdőlapjának kiterjedését. Megjegyzendő, hogy ez a kiterjedés nem kerül használatra, ha nem tartalmazza az első túraútvonalpontot. Ebben az esetben a túra úgy fog megjelenni, hogy az első pont középen lesz.",
      "settingsExtentDateLineError": "A kiterjedés nem keresztezheti a 180° hosszúsági kört",
      "settingsExtentDateLineError2": "Nem sikerült a kiterjedés kiszámítása",
      "settingsExtentDrawBtn": "Új kiterjedés rajzolása",
      "settingsExtentModifyBtn": "A kiterjedés szerkesztése",
      "settingsExtentApplyBtn": "Előnézet a Map Tour-on",
      "settingsExtentUseMainMap": "Map Tour kiterjedésének használata",
      "settingsZoomExplain": "Állítsa be a történetben a pontok nagyítását (választható).",
      "settingsLabelZoom": "Méretarány/szint",
      "settingsZoomFirstValue": "Nincs",
      "settingsFieldError": "Válasszon mezőt mindegyik listából",
      "dataTitle": "Tárolt Map Tour réteg létrehozása",
      "dataExplain": "Új vektoroselem-réteg készül a képek és túraútvonalpontok számára. A túraréteg nem lesz megosztva senkivel, kivéve ha megosztja a Map Tour-t.",
      "dataExplainPortal": "Ha nem sikerül létrehozni a vektoros réteget, forduljon az Ön ArcGIS adminisztrátorához.",
      "dataNameLbl": "Réteg neve",
      "dataFolderListLbl": "Mappa",
      "dataFolderListFetching": "Mappák lekérése...",
      "dataRootFolder": "Gyökér",
      "dataNameError": "Adja meg a vektoros szolgáltatás nevét",
      "dataFolderError": "Válasszon egy érvényes mappát",
      "dataSrcContainsInvalidChar": "A vektoros szolgáltatás neve egy vagy több érvénytelen karaktert tartalmaz (-, <, >, #, %, :, \", ?, &, +, / vagy ).",
      "dataSrvAlreadyExistsError": "Ilyen nevű szolgáltatás már létezik a szervezetben. Válasszon másik nevet.",
      "dataBtnSave": "Hozza létre a réteget",
      "dataFooterProgress": "A létrehozás folyamatban van",
      "dataFooterSucceed": "A létrehozás sikerült. Betöltés",
      "dataFooterError": "Nem sikerült a létrehozás. Próbálja meg újra",
      "tabError": "Ellenőrizze az összes lapot, hogy nincs-e hiba rajtuk",
      "introRecordBtn": "Bevezetés",
      "introRecordActivate": "Az első pont használata bevezetésként (nem jelenik meg a forgótárban)",
      "coverRecordActivate": "Az első pont használata címlapként",
      "coverBuilder": "Címlap-konfiguráció",
      "cover": "Címlap",
      "showCover": "Címlap megjelenítése",
      "editCover": "Címlap szerkesztése",
      "coverNoVideo": "A videó nem támogatott a címlap-médiához. Válasszon egy képet.",
      "coverPreview": "A címlap megjelenítéséhez mentse el a történetet, majd jelenítse meg előnézetben a Történet megtekintése gomb használatával.",
      "thirdPartyTerms": "Harmadik fél szolgáltatását használva Ön elfogadja a szolgáltatás feltételeit: "
    },
    "addPopupJS": {
      "uploadingPicture": "Kép feltöltése folyamatban",
      "uploadSuccess": "Sikeres feltöltés",
      "uploadError": "Hiba a kép feltöltésekor",
      "uploadError2": "Hiba a vektoros elem hozzáadásakor (érvénytelen html-címke)",
      "notJpg": "Válassza ki a feltöltendő jpeg formátumú fényképet",
      "errorNoPhoto": "Válassza ki a feltöltendő képet",
      "errorNoThumbnail": "Válassza ki a feltöltendő bélyegképet",
      "errorInvalidPicUrl": "Adjon meg egy képre mutató, érvényes URL-címet. Https-sel kezdődik. A vége: jpg, png, gif vagy bmp, vagy zárja '#isImage' toldalékkal az URL-címet a szabály felülbírálásához.",
      "errorInvalidThumbUrl": "Adjon meg egy érvényes bélyegképet (kezdete: https://, vége: jpg, png, gif vagy bmp).",
      "errorInvalidVideoUrl": "Adja meg egy videó érvényes URL-címét (kezdete: https://)",
      "errorNoName": "Adja meg a túraútvonalpont nevét",
      "errorNoDescription": "Adja meg a túraútvonalpont képaláírását",
      "errorNoLocation": "Állítsa be a túraútvonalpont helyét"
    },
    "builderJS": {
      "noPendingChange": "Nincs nem mentett módosítás",
      "unSavedChangeSingular": "1 nem mentett módosítás",
      "unSavedChangePlural": "nem mentett módosítás",
      "shareStatus1": "A túra nincs mentve",
      "shareStatus2": "A túra nyilvánosan van megosztva",
      "shareStatus3": "A túra a szervezeten belül van megosztva",
      "shareStatus4": "A túra nincs megosztva",
      "popoverDiscard": "Biztos, hogy elveti a nem mentett módosításokat?",
      "yes": "Igen",
      "no": "Nem",
      "popoverLoseSave": "A megtekintő megnyitásával elveszíti a nem mentett módosításokat",
      "ok": "OK",
      "popoverSaveWhenDone": "Ne feledkezzen el a mentésről, amikor elkészült",
      "closeWithPendingChange": "Biztosan jóváhagyja a műveletet? A módosítások el fognak veszni.",
      "gotIt": "OK",
      "savingApplication": "Történet mentése",
      "saveSuccess": "A történet mentve",
      "saveError": "Nem sikerült a mentés, próbálja meg újra",
      "saveError2": "Nem sikerült a mentés, mert érvénytelen html-címke van egy névben vagy leírásban",
      "saveError3": "A cím nem lehet üres",
      "dragColorPicker": "Mozgasson körbe<br />vagy változtassa meg a színt",
      "dataWarningExtent": "Adatai vannak a webtérkép kiterjedésén kívül. Ezek az adatok nem lesznek túraútvonalpontként használva, változtassa meg a térkép kiterjedését, ha használni szeretné őket.",
      "dataWarningVisibi": "A Map Tour réteg nem látható az aktuális webtérkép-kiterjedésnél. A Map Tour réteg láthatóságát %MAPSIZE% méretű térképen ellenőrizze.",
      "dataWarningEdit": "Webtérkép szerkesztése",
      "dataWarningClose": "Bezárás",
      "signIn": "Jelentkezzen be egy fiókkal:",
      "signInTwo": "a történet mentéséhez.",
      "switchBM": "Alaptérkép módosítása"
    },
    "organizePopupJS": {
      "messageStart": "Azt választotta, hogy töröl",
      "messageSinglePoint": "egy túraútvonalpontot",
      "messageMultiPoint": "túraútvonalpontot",
      "messagePermantRemove": "Ez végleg eltávolítja a",
      "messageRecord": "rekordot",
      "messageRecordPlural": "rekordot",
      "messageConfirm": "az adatbázisból. Folytatja?",
      "labelButtonShow": "Megjelenítés",
      "labelButtonHide": "Elrejtés"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Ez végleg törli a képet és a bélyegképet",
      "popoverDeleteWarningThumb": "Ez végleg törli a bélyegképet",
      "popoverUploadingPhoto": "Kép és bélyegkép feltöltése folyamatban",
      "popoverUploadingThumbnail": "Bélyegkép feltöltése folyamatban",
      "popoverUploadSuccessful": "Sikeres feltöltés",
      "popoverUploadError": "Nem sikerült a feltöltés, próbálja meg újra",
      "changePicAndThumb": "Kép módosítása",
      "changeThumb": "Bélyegkép módosítása",
      "selectPic": "Média módosítása",
      "selectThumb": "Bélyegkép módosítása",
      "uploadPicAndThumb": "Alkalmaz"
    },
    "headerJS": {
      "editMe": "Szerkesztés!",
      "templateTitle": "Cím beállítása",
      "templateSubtitle": "Alcím beállítása",
      "edit": "Szerkesztés"
    },
    "crossFaderJS": {
      "setPicture": "Kép címének beállítása",
      "setCaption": "Kép feliratának beállítása"
    },
    "importPopup": {
      "title": "Importálás",
      "prevBtn": "Vissza",
      "nextBtn": "Következő"
    },
    "importPopupHome": {
      "header": "Hol vannak tárolva a képek?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "képek",
      "videos": "videók",
      "disabled": "Ezt a vektoros elemet letiltotta az adminisztrátor",
      "disabledPortal": "Ez a vektoros elem azt igényli, hogy a portálnak legyen üzemeltető szervere. Forduljon a Portal for ArcGIS adminisztrátorához.",
      "header1": "A képeket nyilvánosan kell megosztani.",
      "header2": "Az importálás korlátozott lesz, az első %NB1% %MEDIA% fog szerepelni benne.",
      "emptyDataset": "Hiba, nem találhatók képek",
      "footerImport": "Importálás",
      "selectAlbum": "Válasszon egy nyilvános albumot",
      "selectAlbum2": "Válasszon egy albumot",
      "pleaseChoose": "Válasszon",
      "userLookup": "Keresés",
      "userLookingup": "Keresés folyamatban",
      "csv": "Hivatkozva egy CSV-fájlban",
      "advanced": "Speciális beállítások",
      "advancedScratchLbl": "Új túra kezdése",
      "advancedScratchTip": "Hozzon létre üres túrát, melyhez hozzáadhatja a túraútvonal pontjait. A médiája nagy valószínűséggel már online. Ez az opció nem támogatja a képek feltöltését.",
      "advancedCSVLbl": "Túraadatok importálása CSV-fájlból",
      "advancedCSVTip": "Importálja a túrával kapcsolatos tartalmat abból a CSV-fájlból, amely online médiájára hivatkozik. Ez az opció nem támogatja a képek feltöltését.",
      "advancedCommonTip": "Ehhez a képeknek és a videóknak már online elérhetőknek kell lenniük.",
      "select": "Válassza ki",
      "locUse": "Képek földrajzi helyének használata",
      "locExplain": "Lehet, hogy nem szeretné használni a képek helyadatait, mivel a helyek származtathatók az albumból, így az összes kép készítésének helye ugyanaz.",
      "locExplain2": "Lehet, hogy nem szeretné használni a videók helyadatait, mivel a helyek származtathatók az albumból, így az összes videó készítésének helye ugyanaz."
    },
    "viewFlickr": {
      "title": "Importálás a Flickr-ből",
      "header": "Adja meg a Flickr-hez tartozó felhasználónevét, és válassza ki az importálni kívánt albumot vagy címkét.",
      "userInputLbl": "Felhasználónév megadása",
      "signInMsg2": "A felhasználó nem található",
      "selectSet": "Válasszon egy albumot",
      "selectTag": "vagy válasszon egy címkét",
      "footerImportTag": "A kiválasztott címke importálása",
      "footerImportSet": "A kiválasztott album importálása"
    },
    "viewFacebook": {
      "title": "Importálás a Facebookról",
      "header": "Adja meg a Facebook-fiókjának hitelesítő adatait, vagy használjon egy nyilvános oldalt. Privát albumok felhasználásával létrehozható olyan nyilvános Map Tour szolgáltatás, amely nem igényli a Facebook felhasználói hitelesítését, így minden hozzászólás és „tetszik” jelölés továbbra is privát marad.",
      "leftHeader": "Facebook-felhasználó",
      "rightHeader": "Facebook-oldal",
      "pageExplain": "A Facebook-oldal egy nyilvános márka/termék vagy híresség, mint például az <b>esrigis</b> oldala. Az oldal neve az URL-cím első „/” karaktere után következik.",
      "pageInputLbl": "Adja meg az oldal nevét",
      "lookupMsgError": "Az oldal nem található"
    },
    "viewPicasa": {
      "title": "Google+ importálás",
      "header": "Adja meg az e-mail-címét vagy az azonosítóját.",
      "userInputLbl": "E-mail vagy Picasa/Google+ azonosító",
      "signInMsg2": "A fiók nem található",
      "signInMsg3": "Nincs nyilvános album",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Learn More</a>",
      "howToFind2": "Másolja ki a Picasa-oldal első és második „/” karaktere közötti számjegyeket"
    },
    "viewCSV": {
      "title": "Importálás CSV-fájlból",
      "uploadBtn": "Válasszon ki vagy húzzon ide egy CSV-fájlt",
      "resultHeaderEmpty": "A CSV-fájl üres",
      "resultHeaderSuccess": "Betöltve %NB_POINTS% pont",
      "resultHasBeenLimited": "Az importálás korlátozva van az első %VAL1% pontra (összesen: %VAL2%) a túránkénti %VAL3% pontos korlátozás miatt.",
      "browserSupport": "A böngészője nem támogatott, a CSV-fájlok használatához <a href='http://browsehappy.com/' target='_blank'>frissítenie kell a böngészőjét</a>, vagy az ArcGIS.com webtérkép-nézegetőt kell használnia (lásd a súgót).",
      "errorLatLng": "Nem található a Szélesség és a Hosszúság mező. Lehetséges értékek: szélesség: <i>%LAT%</i>, hosszúság: <i>%LONG%</i>.",
      "errorFieldsExplain": "Nem sikerült a betöltés, mert nem találhatók a következő kötelező mezők:",
      "errorFieldsName": "<b>Név</b> – lehetséges értékek: %VAL%",
      "errorFieldsDesc": "<b>Leírás</b> – lehetséges értékek: %VAL%",
      "errorFieldsUrl": "<b>Kép URL-címe</b> – lehetséges értékek: %VAL%",
      "errorFieldsThumb": "<b>Bélyegkép URL-címe</b> – lehetséges értékek: %VAL%",
      "errorFields2Explain": "Nem sikerült a betöltés, mert a CSV-fájl attribútumai nem egyeznek meg a réteg következő attribútumaival:",
      "errorFields2Name": "<b>Név</b> – %VAL1% szükséges a(z) %VAL2% helyett",
      "errorFields2Desc": "<b>Leírás</b> – %VAL1% szükséges a(z) %VAL2% helyett",
      "errorFields2Url": "<b>Kép URL-címe</b> – %VAL1% szükséges a(z) %VAL2% helyett",
      "errorFields2Thumb": "<b>Bélyegkép URL-címe</b> – %VAL1% szükséges a(z) %VAL2% helyett",
      "resultFieldsAll": "Az összes attribútum importálva lett",
      "resultFieldsNotAll": "A következő attribútumok nem lettek importálva, mert nem léteznek a térképrétegben",
      "resultFieldsNotAll2": "A következő attribútumok lettek importálva",
      "footerNextBtnResult": "Importálás a webtérképbe",
      "footerProgress": "Az importálás folyamatban van",
      "footerSucceed": "Az importálás sikerült. Betöltés"
    },
    "viewYoutube": {
      "title": "Importálás a YouTube-ról",
      "header": "Adjon meg egy YouTube-felhasználónevet a nyilvánosan megosztott videók kereséséhez.",
      "pageInputLbl": "Adjon meg egy YouTube-felhasználónevet",
      "lookupMsgError": "A felhasználó nem található",
      "howToFind": "A YouTube-felhasználónév megkeresése",
      "howToFind2": "A felhasználónév a videók alatt jelenik meg",
      "found": "Sikerült megtalálni",
      "noData": "Nincsenek nyilvános videók"
    },
    "viewGeoTag": {
      "title": "Válassza ki a képeit/videóit, és határozza meg a helyüket",
      "header": "A lokalizált elemek importálva lesznek. Kattintson az importálni kívánt nem lokalizált elemekre azok helyének megállapításához.",
      "headerMore": "Súgó",
      "headerExplain": "Amikor az <b>Importálás</b> gombra kattint, csak a <b>Lokalizált</b> lapon szereplő képek és videók lesznek importálva.<br><br>Ha elérhetők, a képekkel vagy videókkal tárolt földrajzi információ importálása automatikusan történik. A földrajzi adatok nélküli elemek felsorolása a <b>Keresés</b> lapon található. Az adott fülön felsorolt elemek kereséséhez kattintson a lapra, majd a kívánt helyre a térképen.<br><br>Ha törölni szeretne egy elemet a <b>Lokalizált</b> lapról, hogy az ne legyen importálva, kattintson a Ne importálja gombra, melyet az egérmutatót az adott elemre húzva jeleníthet meg.<br><br>Tipp: Ha a saját médiájának földrajzi adatait nem sikerül importálni, ellenőrizze a fiókja adatvédelmi beállításait. Például a Flickr-fiók beállításaiban győződjön meg arról, hogy az EXIF-adatok nem rejtettek. Továbbá, ha a Flickr adatvédelmi beállításainak megfelelően az új feltöltések EXIF-adat import funkció ki van kapcsolva (alapértelmezett pozíció), akkor a rendszer nem tárolja el a földrajzi adatokat a Flickr-ben található képekhez, kivéve, ha ismét feltölti azokat, vagy egyedileg megadja a helyüket a Flickr-ben.",
      "leftPanelTab1": "Hely meghatározása",
      "leftPanelTab2": "Lokalizálva",
      "clickOrTap": "Kattintson a térképre a hely meghatározásához",
      "clearLoc": "Helyek törlése",
      "clickDrop": "Ne importálja",
      "footerImport": "Importálás",
      "footerProgress": "Az importálás folyamatban van",
      "footerSucceed": "Az importálás sikerült. Betöltés...",
      "loading": "Betöltés",
      "error": "Nem sikerült a képek földrajzi helyének importálása, a földrajzi helyek figyelmen kívül lettek hagyva."
    },
    "initPopup": {
      "title": "Üdvözöli a Map Tour szerkesztő!",
      "prevBtn": "Vissza",
      "nextBtn": "Következő"
    },
    "initPopupHome": {
      "header1": "Hol találhatók a képei és a videói?",
      "header2": "Ez az útmutató segítséget nyújt a Map Tour létrehozásához az online tárolt médiatartalmakból, vagy a tartalmak importálásához az ArcGIS Online for Organizations alkalmazáshoz tartozó fiókjába.",
      "title1": "Már online vannak tárolva",
      "title2": "Fel kell töltenem a képeimet",
      "hostedFSTooltip": "Töltse fel a képeit, és tárolja őket a Map Tour-ban (a videók nem támogatottak).",
      "hostedFsNA": "A tárolt vektoros rétegek közzétételéhez közzétevőnek kell lennie, vagy más szerepkör esetén megfelelő jogosultsággal kell rendelkeznie. Forduljon az ArcGIS adminisztrátorához.",
      "hostedFsNA2": "Csak az ArcGIS Online előfizetésével érhető el. <a href='%LINK%'>Iratkozzon fel az ingyenes próbaverzióra</a>",
      "footer1": "Amikor elkészült, ne felejtse el megosztani a Map Tour-t a közönséggel az alkalmazás elemoldalán.",
      "footer3": "A CSV-sablon letöltése",
      "footer4": "Ha nem sikerül letölteni, válassza a „Mentés másként” lehetőséget",
      "footer4bis": "Ha nem indul el a letöltés, kattintson rá a jobb egérgombbal, és válassza a „Mentés másként” parancsot",
      "footer5": "További információk",
      "footerProgress": "A létrehozás folyamatban van",
      "footerSucceed": "A létrehozás sikerült. Betöltés..."
    },
    "helpPopup": {
      "title": "Súgó",
      "close": "Bezárás",
      "tab1": {
        "title": "Bevezetés",
        "moreInfo": "További információ:",
        "infoSites": "Keresse fel a <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'> Map Tour szekciót az <a href='https://storymaps.arcgis.com' target='_blank'> Esri Story Maps webhelyen.</a>",
        "mtFAQ": "Lásd a <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Map Tour GYIK-et.</a>",
        "myStories": "Map Tour-jait itt kezelheti és ellenőrizheti, hogy vannak-e bennük hibák: <a href='https://storymaps.arcgis.com/en/my-stories/' target=’_blank’>Saját történetek</a> a webhelyen.",
        "div1": "A Map Tour sablon földrajzi adatok megjelenítésére használható, ha az elmondani kívánt történetet látványos fényképekkel vagy médiaelemekkel is ki tudja egészíteni.",
        "div2": "A sablonnal tetszetős, könnyen használható webes alkalmazás hozható létre, amellyel helyek rövid sorozatát mutathatja be térképen, számozással ellátva, hogy a felhasználók tallózhassanak a sorozatban. A sablon kialakítása olyan, hogy bármilyen böngészőben, bármilyen eszközön használható, beleértve az okostelefonokat és a táblagépeket is. <br /><br />",
        "div42": "A más felhasználók által létrehozott túratérképek megtekintéséhez <a href='https://links.esri.com/storymaps/map_tour_gallery' target=’_blank’>látogassa meg a galériát</a> a <a href='https://storymaps.arcgis.com/' target='_blank'>Story Maps webhelyen</a>. Twitteren is követhet minket: <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Örömmel hallanánk Önről! Ha el szeretné mondani, milyen problémákat talált, és milyen új funkciókra van szüksége, látogasson el a Story Maps fórumra a <a href='https://links.esri.com/storymaps/forum' target=’_blank’>Geoneten.</a>"
      },
      "tab2": {
        "title": "Adatok",
        "div1": "A Map Tour létrehozásakor fontos szempont a képek tárolási helyének meghatározása. A Map Tour-hoz felhasználhatók a fényképmegosztási szolgáltatásokban vagy bármely webszerveren tárolt, illetve a lemezről feltöltött képek.",
        "div1a": "A támogatott képformátumok és videók részletes adatait a fül alján, az utolsó szekcióban tekintheti át.",
        "div2": "Az interaktív szerkesztő két módszert kínál a Map Tour képeinek kezeléséhez:",
        "div3": "<ul><li>Használhat olyan fényképeket, amelyek<b>már online tárhelyen találhatók</b>, mint például a Flickr vagy a saját webhelyén tárolt fényképeket. Ezekre a képekre az URL-címük fog hivatkozni a térképbemutatóban.</li><li>Ezenkívül <b>a számítógépéről is feltölthet fényképeket</b> közvetlenül a túratérképbe. A feltöltéshez rendelkeznie kell az ArcGIS-előfizetéssel, valamint közzétevői vagy adminisztrátori jogosultságokkal, mivel automatikusan létre lesz hozva Önnek egy tárolt vektoros szolgáltatás, amely csatolmányként fogja tárolni a fényképeit.</li></ul>",
        "div4": "A használat főbb lehetőségei a következők:",
        "div4b": "<b>Fényképei még nincsenek tárolva</b>, és rendelkezik ArcGIS-előfizetéssel: a legjobb választás egy tárolt vektoros szolgáltatás használata. A nyilvános fényképmegosztási szolgáltatásokhoz hasonlóan optimalizálni fogjuk a képeit, gyorsan betöltődő képeket fogunk létrehozni belőlük, Ön pedig az ArcGIS platformon férhet hozzá az összes adminisztrációs és adatkezelési lehetőséghez.",
        "div5": "<b>Ön nem tagja egyetlen szervezetnek sem</b>: Először fel kell töltenie a képeit egy fényképmegosztási webhelyre vagy a saját webszerverére. A szerkesztő segítséget nyújt a képek használatához, amelyek továbbra is az eredeti helyükön lesznek tárolva.",
        "div6": "<b>Meglévő vektoros szolgáltatás újbóli használatának lehetőségét keresi</b>, amely a képeit csatolmányként tárolja, vagy amely külső képekre hivatkozik: Lásd az alábbi részletes szekciót.",
        "div7": "<b>Ön a Map Tour készítő sablon korábbi verziójának felhasználója,</b> és már van olyan CSV-fájlja, amely a képeinek és a bélyegképeinek hivatkozásait tartalmazza. Az adatokat importálhatja és pontosíthatja. A szerkesztő csak az olyan CSV-fájlokat támogatja, amelyekben szélességi/hosszúsági mezők szerepelnek. A címadatokat tartalmazó CSV-fájlok a webtérkép segítségével használhatók (lásd az alábbi szekciót).",
        "div8": "Importálás online fényképmegosztási szolgáltatásokból",
        "div9a": "A Facebook-támogatás megszűnt, ${learn}.",
        "learn": "további információk",
        "div9": "Az importálási művelet úgy hivatkozik a már tárolt képekre, hogy a webtérkép vektoros gyűjteményében tárolja az URL-címüket. A képeket nem az ArcGIS Online tárolja. Ha a tárolt képekhez nem lehet hozzáférni, akkor nem lesznek elérhetők a Map Tour-ban, és „A kép nem érhető el.” feliratú kép fog megjelenni helyette. A fényképtároló szolgáltatástól függően előfordulhat, hogy a Map Tour nem importálja a kép nevét, leírását vagy helyét. Ezeket az attribútumokat a webtérkép tárolja, és az online szolgáltatásokban végrehajtott módosítások nem jelennek meg a Map Tour-ban.",
        "div10": "A képek tárolás webszerveren",
        "div11": "Ha úgy dönt, hogy a saját webkiszolgálóján tárolja a képeit (ahelyett, hogy a Flickr szolgáltatásban tárolná vagy közvetlenül feltöltené azokat a bemutatóba), akkor egyedileg kell létrehoznia a bélyegképeket a képeihez. Ha teljes felbontású képet használ bélyegképként, romlani fog a teljesítmény. Ha közvetlenül, URL-címekkel szeretne fényképeihez hozzáférni az interneten, nézze meg az alábbi linket, ahol tanácsokat talál a megfelelő méretezésről: <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target=’_blank’>GYIK</a>.",
        "div12": "Meglévő településadatok használata",
        "div13": "Ha meglévő településadatokkal rendelkezik (például táblázatban vagy GIS-pontrétegben van településlistája), akkor azokat az adatokat CSV-formátumban tudja térképtúra létrehozásához felhasználni. Ehhez az szükséges, hogy a képekhez a CSV-fájlban értékként tárult URL-eken keresztül lehessen közvetlenül hozzáférni. A CSV-sablon a Speciális beállítások párbeszédablakból tölthető és a Térképtúra-készítő első elindításakor. A CSV-fájlt a párbeszédablakban töltheti fel.",
        "div14": "A mezőnevek támogatott értékei a következők (a kis- és a nagybetűk nem számítanak különbözőnek):",
        "div151": "Név",
        "div152": "Leírás",
        "div153": "Kép",
        "div154": "Bélyegkép",
        "div155": "Szín ",
        "div16": "Ha az alkalmazás nem talál egyező mezőket egy vektoros szolgáltatás használatakor, a megjelenítő nem fog működni, amíg a szerkesztőben nem konfigurálja a használandó mezőket. A webtérképbe felvett CSV- és shapefile-rétegben szerepelnie kell az összes szükséges mezőnek, máskülönben nem fog működni a szerkesztő.",
        "div162": "Ha olyan vektoros szolgáltatást használ, amely csatolmányként tárolja a képeket, <b>csak a két csatolmányt tartalmazó vektoros elemek lesznek használva</b>. Az első csatolmány határozza meg a fő képet, a második pedig a bélyegképet.",
        "div17": "A kép és a bélyegkép mezője kötelező a csatolmány nélküli vektoros szolgáltatások esetében, és választható (de kifejezetten ajánlott) a csatolmányokat használó vektoros szolgáltatások esetében. Ha a szolgáltatásnál engedélyezve vannak a csatolmányok, a szerkesztő lehetővé teszi a képek feltöltését csatolmányként. Ha nem, akkor csak a kép és a bélyegkép URL-címét szerkesztheti.",
        "div172": "Ha szerepel a kép és a bélyegkép mezője, mindig ezek a mezők lesznek használva, és a vektoros szolgáltatás csatolmányai nem lesznek lekérve.",
        "div173": "Letölthető példák a CSV- és shapefile-fájlokra innen",
        "div174": "További információt ebben a <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target=’_blank’>GYIK-ben</a> találhat.",
        "div18": "Tárolt vektoros szolgáltatás létrehozása CSV- vagy shapefile-fájlból",
        "div19": "Amikor létrehoz egy tárolt vektoros szolgáltatást egy CSV- vagy egy shapefile-fájlból, a csatolmányok alapértelmezés szerint nincsenek engedélyezve. Az engedélyezésükhöz nyissa meg a vektoros szolgáltatás részletes oldalát, kattintson a kis nyílra a rétegek szekciójában, és itt találja ezt a beállítást. A Map Tour továbbra is az attribútumokban megadott képeket és bélyegképeket fogja használni. Másik lehetőségként feltöltheti a képeit vektoros szolgáltatás csatolmányaként, ehhez a képek paneljén talál két gombot („Kép módosítása” és „Bélyegkép módosítása”).",
        "div20": "Támogatott képformátumok és videók",
        "div21": "Ha a Flickr szolgáltatásban lévő képeket használja, a Térképtúra funkció automatikusan .jpg fájlként fér hozzá azokhoz. A Térképtúra-készítőbe csak .jpg vagy .jpeg formátumú képeket lehet feltölteni. Ha közvetlenül az interneten, URL-címek használatával hivatkozik képekre, azok formátuma .jpg, .jpeg, .png, .gif vagy .bmp kell legyen. A YouTube-videók közvetlenül támogatottak.",
        "div22": "A Map Tour sablon nem tartalmaz videolejátszót, ezért a kedvenc videotárhely-szolgáltatója által biztosított külső videolejátszót kell használnia (keresse meg a videó beágyazásának lehetőségét, és másolja ki az URL-címet a kódból). Ha saját maga szeretné tárolni a videót, hozzon létre egy HTML-oldalt, amely tartalmaz egy videolejátszót, például a <a href='http://www.videojs.com/'>Video.js</a> lejátszót.",
        "div23": "Az interaktív szerkesztő nem biztosít párbeszédpanelt videó hozzáadásához a csatolmányokkal rendelkező vektoros szolgáltatások használata esetén, ezt azonban megoldhatja úgy, hogy az interaktív szerkesztőn kívül szerkeszti az adatokat. Ha az arcgis.com térképnézegető ablakban úgy módosítja a képmezőket, hogy egy külső videóra mutassanak, és az URL-cím végén elhelyez egy speciális paramétert (#isVideo), akkor a média videóként lesz kezelve.",
        "div24": "Megjegyzendő, hogy ekkor is két érvényes csatolmányra van szükség, máskülönben a pont nem lesz használva. Nincs lehetőség videók használatára, ha a vektoros szolgáltatás csatolmányaiban nincs kép- és bélyegképmező."
      },
      "tab3": {
        "title": "Személyreszabás",
        "div1": "A szerkesztő számos személyreszabási lehetőséget biztosít, amelyek a felső panelen lévő BEÁLLÍTÁSOK gombbal érhetők el. Ha nem talál az igényeinek megfelelő beállítást, közreadunk egy letölthető verziót is, amelyet telepíthet a webszerverén, és az egyéni igényeihez igazíthatja.",
        "div2": "Azt javasoljuk, hogy a tárolt verziót használja a következő esetek kivételével:",
        "div3": "<li>Ha nem talál olyan személyreszabási lehetőséget a felhasználói felülethez, amilyenre szüksége van, például háttérkép elhelyezését a fejlécben.</li><li>Ha Ön fejlesztő, és tovább szeretné fejleszteni az alkalmazást.</li>",
        "div4": "A letölthető verzió webtérképen keresztül vagy egy webtérkép-kezelő alkalmazás azonosítójának használatával konfigurálható. A használat főbb lehetőségei a következők:",
        "div41": "A térképtúrát az interaktív szerkesztőben hozza létre a tárolt környezetben, és a sablont a webtérkép-kezelő alkalmazás azonosítójának használatával konfigurálja. Az interaktív szerkesztőben megadott beállítások lesznek alkalmazva.",
        "div42": "A webtérképet az interaktív szerkesztőn kívül hozza létre, és a webtérkép azonosítójának használatával konfigurálja a sablont. A sablon konfigurálásának ismertetését a dokumentációban olvashatja el.",
        "div43": "Vegye figyelembe, hogy a letölthető verzióban elérhető interaktív szerkesztőre néhány technikai korlátozás vonatkozik az Internet Explorer 10-es verziójánál korábbi böngészőkben.",
        "div5": "A sablon legújabb verziójának letöltéséhez és a használatával kapcsolatos tájékoztatásért keresse fel a <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub projektoldalát</a>."
      },
      "tab4": {
        "title": "Tippek",
        "div0": "Támogatott böngészők",
        "div0a": "A Map Tour megtekintő az IE8+ verziókban támogatott. Az interaktív szerkesztő az IE9+ verziókban támogatott. Folyamatban van a tesztelése az összes jelentősebb böngészőben, de ha problémákat tapasztal, a Chrome használatát javasoljuk.",
        "div0b": "Ha problémákat tapasztal, tudassa velünk. Időközben a CSV-sablont használhatja a Map Tour létrehozásához, ami minimálisra csökkenti a szerkesztő felületének használatát.",
        "div1": "Képek",
        "div2": "Bár egy Map Tour-ban megadhatók különböző méretű, alakú és tájolású képek, azt javasoljuk, hogy álló tájolású képek helyett fekvő tájolásúakat használjon. A legmegfelelőbbek a 4:3 méretarányú fényképek. Hárompaneles és Integrált elrendezésben az álló tájolás használata azt eredményezheti, hogy a képaláírások kitakarják a képek nagy részét. Hárompaneles és Integrált elrendezésben azt javasoljuk, hogy lehetőség szerint pontosan ugyanolyan méretű és alakú képeket használjon. Így a különböző méretű képek nem zavarják meg a felhasználókat, amikor követik a bemutatót.",
        "div2a": "Azt javasoljuk, hogy a maximális képméret 1000 képpont x 750 képpont (szélesség x magasság) legyen a fő képeknél, és 140 x 93 képpont legyen a bélyegképeknél.",
        "div3": "A képaláírás szövegének formázása HTML-címkék használatával",
        "div4": "A képaláírásokba HTML-címkéket is tehet a formátum és a hivatkozások meghatározására. Ezek a címkék például egy zöld hiperhivatkozást adnak hozzá a képaláíráshoz:",
        "div4aa": "<b>Címlap létrehozása Oldalsó panel bemutatóhoz</b><br>Az Oldalsó panel elrendezés támogatja az opcionális fedőlapot, így tetszetős, teljes képernyős képpel ragadhatja meg a közönség figyelmét. Az Oldalsó panel bemutatóhoz tartozó címlap beállításához először adjon hozzá néhány (vagy az összes) pontot a bemutatóhoz. Ezután kattintson a Rendezés gombra, majd a megjelenő párbeszédpanelen győződjön meg arról, hogy a címlap meghatározásához használni kívánt bemutatópont egybeesik a bemutató első pontjával. Ezt követően jelölje be „Az első pont használata címlapként” négyzetet a párbeszédpanelen. Az első bemutatópont neve címként jelenik meg a címlapon, a ponthoz tartozó képaláírás lesz az alcím, a pont képe pedig címlapképként lesz látható. A videó nem támogatott a címlapon. Bővebb információkat ebben a <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target=’_blank’>GYIK-ben</a> találhat.</a>",
        "div4a": "Adjon jó alcímet a túrának",
        "div4b": "Szánjon időt arra, hogy figyelemfelkeltő alcímet adjon a túrának. Az alcímmel felhívhatja a felhasználók figyelmét a bemutatóra, és elmondhatja, mit fedezhetnek fel a bemutató segítségével. Arra is alkalmas, hogy közölje a felhasználókkal, melyik államban vagy országban található a túra. Nem biztos, hogy a közönség tudja, hogy a megnevezett város hol található.  Az alcímek ne legyenek túl hosszúak. Ha nem tud kitalálni jó alcímet, üresen hagyhatja. A Hárompaneles és Integrált elrendezéstől eltérően az Oldalsó paneles elrendezés nem támogatja az alcímeket a fejlécben. Ha Oldalsó panel elrendezésben a címlap opciót használja, a bemutató első pontjának képaláírása megjelenik a címlapon, és a bemutató alcímeként szolgál.",
        "div5": "Segédrétegek",
        "div6": "A Map Tour tartalmának bővítéséhez további segédrétegeket vehet fel. Ezek a rétegek a Map Tour pontjai mellett tartalmazhatnak egyéb megjeleníteni kívánt földrajzi vektoros elemeket, például vizsgált területet, gyalogos vagy autós útvonalat a bemutatópontokhoz kapcsolva stb. A Map Tour sablon a webtérképhez megadott szimbólumok használatával jeleníti meg ezeket a segédrétegeket, de a rétegekhez definiált felugró ablakok nem támogatottak.  Ha segédrétegeket akar hozzáadni a bemutatóhoz, mentse el a munkát, és zárja be a Map Tour készítőt. Ezután nyissa meg a bemutatóban használt webtérképet. Ezt az ArcGIS Saját Tartalom vagy a Story Map weboldal Saját Történetek szekciójában találja meg.",
        "div7": "A túra legyen rövid és kellemes",
        "div8": "A túrák legfeljebb 99 pontot tartalmazhatnak. A Map Tour-ok többsége természetesen ennél sokkal rövidebb. Ne várja el a közönségtől, hogy végig fogják járni a túl sok túraútvonalpontot. Lehet, hogy Önnek izgalmas a téma, de ne feltételezze, hogy mindenki másnak is.",
        "div10": "Beágyazás",
        "div11": "Ha be szeretné ágyazni a sablont egy másik webhelyre egy iframe használatával, a választható „&embed” paraméter hozzáadása az URL-cím végéhez el fogja távolítani a fejlécet.",
        "div12": "A használt iFrame ne legyen keskeny, mert ennek hatására a Map Tour átvált az interaktív kisméretű kijelzőnézetre, ami megegyezik a túra által a mobilkészülékeken használt nézettel. Javasoljuk, hogy a legkönnyebb használat biztosítása érdekében a Map Tour beágyazásakor mindig helyezzen el egy hivatkozást a beágyazott bemutató mellett, hogy a felhasználók átválthassanak a teljes képernyős bemutatóra."
      },
      "tab5": {
        "title": "Közzététel folyamatban",
        "div1": "Amikor elkészült, ne felejtse el megosztani a Map Tour-t a közönségével a MEGOSZTÁS gombra kattintva vagy az alkalmazás elemoldalán az ArcGIS Online webhelyen.",
        "div2a": "A túra megosztása a szerkesztőben",
        "div2b": "A MEGOSZTÁS gomb frissíti az alkalmazást és a webtérkép elemeit. Ha a túra adatait egy vektoros szolgáltatás elemében tárolja, ez is frissülni fog. Ha egyéb rétegeket is hozzáadott az ArcGIS.com térképnézegető ablakában, ezek nem fognak frissülni. Ez azt eredményezheti, hogy a túrát nem lehet megosztani a várt módon. A szükséges (vagy több) jogosultsággal rendelkező elemek nem fognak frissülni.",
        "div2c": "A túra megosztása az ArcGIS Online webhelyen",
        "div2d": "Amikor az ArcGIS Online webhelyen osztja meg az alkalmazást, szükség esetén az alkalmazás kérni fogja az olyan függő erőforrások (webtérkép, vektoros szolgáltatás, díszítő réteg) frissítését, amelyek nem ugyanilyen módon vannak megosztva. Ha a Map Tour nyilvános, és az egyik erőforrás nincs megosztva a közönséggel, akkor a felhasználók át lesznek irányítva az ArcGIS Online bejelentkezési oldalára.",
        "div3t": "A vektoros adatszolgáltatás biztonsága",
        "div3a": "Ha a Map Tour szerkesztővel létrehozott tárolt vektoros szolgáltatást használ, az alkalmazás gondoskodik a szolgáltatás biztonságáról, és Ön lesz az egyetlen felhasználó, akinek szerkesztési jogosultsága van, még akkor is, ha nyilvánosan osztja meg a szolgáltatást.",
        "div3t2": "Mielőtt megosztja a túrát a közönséggel",
        "div3": "Ellenőrizze, hogy a túra jól működik-e akkor is, ha nincs bejelentkezve az ArcGIS.com-fiókjával. A használandó URL-címről nem történhet átirányítás egy bejelentkezési oldalra vagy a szerkesztő módra.",
        "div4": "Érdemes megnéznie, hogyan jelenik meg a térképtúra fekvő tájolással tartott iPad eszközön, és ellenőriznie, hogy megfelelően jelenik-e meg ezen a népszerű eszközön. Így megállapíthatja, hogy a képaláírások nem takarják-e el túlságosan a képeket. Azt is nézze meg, hogy az alcím elfér-e, nem túl hosszú-e, és nincs-e levágva.",
        "div5a": "Javaslatok a kereséshez",
        "div5b": "Segíthet a felhasználóknak megtalálni a Map Tour az ArcGIS Online webhelyen azzal, hogy elhelyezi a „story map” címkét a térképtúra alkalmazásának elemoldalán (vagyis nem a webtérkép elemoldalán), olyan további címkékkel együtt, mint a túra helyének állama vagy tartománya, az ország neve, ha nem az Egyesült Államokban található, valamint tematikus címkékkel együtt, mint például a „köztéri művészet”, „útikönyv” vagy „történelmi helyek”. Ezek a címkék abban is segítenek, hogy az Esri példáként bemutatható új túrákat találjon, amelyeket felvehetünk a galériáinkba, és hirdethetünk a közösségi médiában. Azt is javasoljuk, hogy töltsön fel egy tetszetős bélyegképet az alkalmazás elemoldalára, például a túra kisméretű képernyőképét vagy egyik fényképét. Ez a kép fog megjelenni automatikusan, ha a térképtúráját felvesszük az ArcGIS Online valamelyik galériájába."
      }
    },
    "share": {
      "firstSaveTitle": "A túra mentve",
      "manageStory": "A történet kezelése",
      "manageStoryA1": "Tipp: A(z) %LINK1% használatával megkeresheti a hibákat a történetben, módosíthatja annak megosztását, szerkesztheti a közösségi médiában stb. További információk a Saját történetekről %LINK2%.",
      "manageStoryA1V1": "Saját történetek",
      "manageStoryA1V2": "itt",
      "shareTitle": "A túra megosztása",
      "sharePrivateHeader": "A túra nincs megosztva, szeretné megosztani?",
      "sharePrivateBtn1": "Megosztás nyilvánosan",
      "sharePrivateBtn2": "Megosztás a saját szervezettel",
      "sharePrivateProgress": "A megosztás folyamatban...",
      "sharePrivateErr": "Nem sikerült a megosztás, próbálja újra vagy",
      "sharePrivateOk": "A megosztás frissült, betöltés...",
      "sharePreviewAsUser": "Előnézet",
      "shareHeader1": "A túra <strong>nyilvánosan elérhető</strong>.",
      "shareHeader2": "A túrát a szervezetének tagjai érhetik el (bejelentkezés szükséges).",
      "shareLinkHeader": "A túra megosztása",
      "shareLinkOpen": "MEGNYITÁS",
      "shareA1": "Használja a(z) %SHAREIMG% lehetőséget az <a href='%LINK1%' target='_blank'>alkalmazás elemoldalán</a>. Ha meg szeretné szüntetni a webtérkép megosztását, használja a <a href='%LINK2%' target='_blank'>webtérkép elemoldalát</a>.",
      "shareWarning": "A %WITH% történő megosztás le lett tiltva, mert nem Ön a <a href='%LINK%' target='_blank'>webtérkép</a> tulajdonosa.",
      "shareWarningWith1": "nyilvánosan",
      "shareWarningWith2": "nyilvánosan és a szervezettel",
      "viewStory": "Történet megtekintése"
    },
    "locator": {
      "error": "A hely nem érhető el"
    },
    "saveErrorSocial": {
      "title": "Közösségi médiamegosztás módosítása",
      "panel1": "Történetének közösségi médiabeli megjelenését javítottuk, de az ArcGIS webes alkalmazás elemcíme nem azonos a történetének a címével.",
      "panel1tooltip": "Cím, összefoglalás és bélyegkép megadásával a történet így fog megjelenni:",
      "panel2": "Melyik címet kívánja használni a közösségi médiában:",
      "panel2q1": "Történet címe (ajánlott)",
      "panel2q1tooltip": "Ha ezt a beállítást választja, az elemcím módosítva lesz úgy, hogy megegyezzen a történet címével, és a szerkesztőben megadott további változtatások szinkronizálva lesznek.",
      "panel2q2": "Elem címe",
      "panel3": "Ha még tovább szeretné javítani a történet közösségi médiabeli megjelenését, a(z) ${MYSTORIES} használatával adjon meg összefoglalást és bélyegképet.",
      "panel4": "Ne figyelmeztessen újra ennél a történetnél",
      "mystories": "Saját történetek",
      "btnSave": "Mentés"
    },
    "bannerNotification": {
      "learnMore": "További információk",
      "close": "Bezárás",
      "dontShowAgain": "Ne jelenjen meg újra ez az üzenet"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Fontos üzenet a webbiztonságról és story mapekről",
      "s1h1": "Az Esri számára fontos a story mapek biztonsága",
      "s1p1": "Az ön story map-jei jelen vannak az interneten, és az internetes közösség folyamatosan a biztonság javítására törekszik. A HTTPS biztonságos kapcsolatot biztosít az internetes tartalmakhoz, ezért egyre inkább ez az internetes tartalmakhoz való kapcsolódás elvárt módja. A legmodernebb böngészők most már hibaüzeneteket küldenek, ha HTTPS helyett HTTP kerül használatra. Mivel a HTTPS használata egyre inkább normává válik, erősen ajánlott HTTPS hivatkozásokat használni a story mapek létrehozásához és megosztásához, továbbá kizárólag HTTPS URL-címek használatát javasoljuk internetes tartalmaknak beágyazására és képek hivatkozására a story mapeken belül.",
      "s1p2": "Ez a gyakorlatban azt jelenti, hogy egy story maphez és annak összes tartalmához (pl. képek, rétegek, beágyazott applikációk és weboldalak) HTTP-vel kezdődő hivatkozások helyett HTTPS-sel kezdődő hivatkozással kell hozzáférni. Ez a legjobb felhasználói tapasztalatokat biztosítja olvasói számára, mivel a legtöbb böngésző ki fogja írni, hogy az ön története biztonságos.",
      "s2h1": "Mit a teendőm?",
      "s2p1": "Az Esri azon dolgozik, hogy az átállás könnyű legyen a story mapek szerzőinek és olvasóinak. A Story Map szerkesztőkben és a Saját történetek alatt elérhetők azok az eszközök, amelyek segítenek önnek megtalálni a nem biztonságos tartalmakat (HTTP) a történeteiben, valamint javaslatokat is tesznek a problémák javítására. Kérjük, ellenőrizze történeteit nem biztonságos tartalmak szempontjából, és frissítsen HTTPS-re a lehető leghamarabb.",
      "action1": "Bezárás",
      "action2": "Saját történetek megtekintése most",
      "action3": "További információk"
    },
    "embedBar": {
      "share": "Megosztás",
      "fullScreen": "Teljes képernyő",
      "enlarge": "Nagyítás",
      "newTab": "Megnyitás új fülön",
      "tagline": "Egy story map",
      "exitFullScreen": "Kilépés a teljes képernyőből"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Lehet egy kérdésünk? A segítségünkre lesz a Story Map-ek továbbfejlesztésében.",
      "s1h1": "Ossza meg a gondolatait, és járuljon hozzá a fejlődéshez",
      "s1p1": "Az Öntől érkező megjegyzések a legfontosabb visszajelzési forrásunkat adják, és minél többet tudunk Önről, annál hatékonyabban fejleszthetjük a story map-eket. Fogadja hálás köszönetünket, ha részt vesz ebben a háromperces felmérésben!",
      "s2p1": "Köszönjük, hogy az Esri story mapeket választotta!",
      "action1": "Bezárás",
      "action2": "A felmérés indítása"
    },
    "licenseChange2018": {
      "noAccess": "Az Ön fiókjának (%USER_NAME%) licence nem teszi lehetővé a nem nyilvános story map megnyitását.  Igényelje a szervezete adminisztrátorától, hogy rendeljen Önhöz olyan felhasználótípust, amely tartalmazza a story map-eket, vagy egy kiegészítő story map-ekre vonatkozó licencet."
    },
    "storyTellerUserType": {
      "notCreatorError": "Az Ön fiókjának (%USER_NAME%) licence nem teszi lehetővé a klasszikus story map szerkesztők használatát. Kérje meg a szervezete adminisztrátorát, hogy rendeljen Önhöz Készítő felhasználótípust."
    }
  }
});