define({
  "viewer": {
    "loading": {
      "step1": "UČITAVANJE PRIČE",
      "step2": "UČITAVANJE PODATAKA",
      "step3": "POKRETANJE OBILASKA",
      "loadBuilder": "PREBACIVANJE NA NAČIN RADA SASTAVLJAČA",
      "redirectSignIn": "PREUSMJERAVANJE NA STRANICU ZA PRIJAVU",
      "redirectSignIn2": "(bit ćete preusmjereni ovamo nakon prijave)",
      "fail": "Nažalost, učitavanje obilaska po karti nije uspjelo",
      "failButton": "Pokušaj ponovno"
    },
    "errors": {
      "boxTitle": "Došlo je do pogreške",
      "portalSelf": "Kobna pogreška: nije uspjelo učitavanje konfiguracije portala",
      "invalidConfig": "Kobna pogreška: neispravna konfiguracija",
      "invalidConfigOwner": "Kobna pogreška: neispravna konfiguracija (potreban ovlašteni vlasnik)",
      "invalidConfigNoWebmap": "Kobna pogreška: neispravna konfiguracija (identifikator web-karte ili aplikacije nije određen u index.html)",
      "invalidConfigNoAppDev": "Identifikator aplikacije za web-kartiranje ili web-karta nije određena u parametrima URL-a (?appid= ili ?webmap=). U načinu rada razvoja ignoriraju se konfiguracije za appid i web-kartu u index.html.",
      "createMap": "Nije moguće stvoriti kartu",
      "invalidApp": "Kobna pogreška: priča se ne može učitati",
      "noLayer": "Ova web-karta nema valjani sloj podataka za Map Tour.",
      "noLayerMobile": "Sastavljač Map Tour nije podržan u ovoj veličini prikaza. Ako je moguće, promijenite veličinu preglednika da biste pristupili sastavljaču ili izradite priču na uređaju s većim zaslonom.",
      "noLayerMobile2": "Zakrenite uređaj u vodoravnu orijentaciju kako biste upotrijebili sastavljač Map Tour.",
      "noLayerView": "Dobro došli u web-aplikaciju Map Tour.<br />Priča još nije konfigurirana.",
      "appSave": "Pogreška pri spremanju priče",
      "mapSave": "Pogreška pri spremanju web-karte",
      "featureServiceLoad": "Pogreška učitavanja usluge geoobjekata",
      "notAuthorized": "Niste ovlašteni za pristup ovoj priči",
      "notAuthorizedBuilder": "Niste ovlašteni za upotrebu sastavljača Map Tour.",
      "oldBrowserTitle": "Preglednik nije u potpunosti podržan",
      "noBuilderIE8": "Sastavljač Map Tour nije podržan na verzijama pregledniku Internet Explorer ranijim od verzije 9.",
      "ie10Win7Explain": "Interaktivni sastavljač Map Tour nije podržan na pregledniku Internet Explorer 10 na Windows 7 kada je izvor podataka usluga geoobjekata s privicima. Da biste upotrijebili uslugu geoobjekata s privicima, morate <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>ručno postaviti način rada za dokumente na standarde preglednika Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>vratiti se na verziju preglednika Internet Explorer 9</a> ili nadograditi na Windows 8.",
      "oldBrowserExplain": "Ovaj preglednik ne podržava automatsko stvaranje sličice od slika koje prenesete u svoj obilazak po karti. Možete stvoriti obilazak po karti s pomoću ovog preglednika, no morat ćete napraviti zasebnu sličicu za svaku sliku koju prenesete.",
      "oldBrowserExplain2": "Da biste olakšali svoj rad, <a href='http://browsehappy.com/' target='_blank'>nadogradite preglednik</a> ili <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivirajte Google Chrome Frame za Internet Explorer</a>.",
      "oldBrowserExplain3": "Sastavljač Map Tour ne radi s preglednikom Internet Explorer 10 na Windows XP.",
      "oldBrowserClose": "Zatvori",
      "noViewerIE2": "Pokušavate prikazati ovu priču preko starijeg, nepodržanog preglednika. Možda neki geoobjekti ne rade ili je došlo do drugih neočekivanih problema. Predlažemo nadogradnju u Internet Explorer 11 ili korištenje drugog preglednika, primjerice Chromea.",
      "noViewerIE3": "Krajem 2017. ova se priča više neće moći učitati u ovom pregledniku. Tada ćete morati koristiti podržani preglednik za prikaz ove priče.",
      "attention": "Pozor!"
    },
    "mobileHTML": {
      "showIntro": "PRIKAŽI NASLOV",
      "hideIntro": "SAKRIJ NASLOV",
      "navList": "Popis",
      "navMap": "Karta",
      "navInfo": "Mediji",
      "introStartBtn": "Početak"
    },
    "desktopHTML": {
      "storymapsText": "Karta s pričom",
      "builderButton": "Prebaci na način rada sastavljača",
      "facebookTooltip": "Podijeli na Facebooku",
      "twitterTooltip": "Podijeli na Twitteru",
      "bitlyTooltip": "Preuzmite kratku poveznicu",
      "bitlyStartIndex": "Stavi poveznicu na trenutačno mjesto",
      "tooltipAutoplayDisabled": "Ovo nije dostupno u načinu automatske reprodukcije",
      "autoplayLabel": "Način automatske reprodukcije",
      "autoplayExplain1": "Način automatske reprodukcije napredovat će kroz vašu priču u redovitim intervalima. To je idealno za kiosk ili javno prikazani zaslon, no budite svjesni da će se u drugim situacijama priča možda teže čitati. Ova značajka nije podržana na malim zaslonima.",
      "autoplayExplain2": "Kada je ovaj način rada aktivan, postoje kontrole za reprodukciju/pauziranje priče i podešavanje brzine navigacije.",
      "takeTourText": "Idi na obilazak",
      "backToStart": "Natrag na početak"
    },
    "builderHTML": {
      "panelHeader": "KONFIGURACIJA PRIČE",
      "buttonSave": "SPREMI",
      "buttonSettings": "Postavke",
      "buttonShare": "Podijeli",
      "buttonView": "Način prikaza",
      "buttonItem": "Otvori stavku web-aplikacije",
      "buttonHelp": "Pomoć",
      "buttonOrganize": "Organiziraj",
      "buttonOrganizeAndCover": "Organizirajte točke obilaska i dodajte naslovnicu",
      "buttonAdd": "Dodaj",
      "buttonImport": "Uvezi",
      "buttonImportDisabled": "Unos nije dostupan kada se koristite učitavanjem slika. Kliknite na Dodaj za učitavanje slike.",
      "dataEditionDisabled": "Onemogućeno je uređivanje podataka na ovom izvoru CSV podataka",
      "dataSourceWarning": "Promijenili su se podaci slojeva Map Tour. Ako ID-jevi geoobjekata nisu jednaki, morate poništiti redoslijed i skrivene točke putem <b>Organiziraj</b>. Ako se nazivi polja razlikuju, morate poništiti postavke polja u <b>kartici podataka u Postavkama</b>.",
      "organizeWarning": "Skrivena je jedna ili više točki dodane izvan interaktivnog sastavljača.",
      "dataPicError0a": "Ovaj obilazak ima <b>%NB%</b> URL-ova slika koji nisu usklađeni.",
      "dataPicError0b": "Ovaj obilazak može imati <b>%NB%</b> URL-ova slika koji nisu usklađeni.",
      "dataPicError1": "Za Map Tour sada je potrebno da URL slike završava s jednim od sljedećih nastavaka: .jp(e)g, .png, .gif ili .bmp.",
      "dataPicError2": "Ovaj zahtjev neće utjecati na postojeći objavljeni Map Tour. Međutim, kako biste upotrijebili interaktivni sastavljač, morate prvo riješiti problem s URL-om izvođenjem jedne od dvije radnje:",
      "dataPicError3": "Uredite URL-ove",
      "dataPicError4": "To će dodati <i>#isImage</i> na kraju URL-ova nepodržanih slika. Većina poslužitelja podržava privitke URL-ova. Međutim, nakon što izvršite tu radnju, trebali biste provjeriti jesu li ažurirani URL-ovi slika funkcionalni tako da navigirate kroz točke. Ako se sve slike učitaju, možete spremiti Map Tour. Ako <b>slike ne rade, nemojte spremiti Map Tour</b>. Umjesto toga ponovo učitajte sastavljač i izvršite drugu radnju.",
      "dataPicError5": "Ograničite obilazak na slike",
      "dataPicError6": "Kada je ova opcija aktivirana, svi se URL-ovi smatraju slikama, no nećete moći dodavati videozapise putem interaktivnog sastavljača. Ova se radnja može poništiti ako odlučite dodati videozapis u budućnosti.",
      "dataPicError7": "Vaš je Map Tour ograničen na slike, ne mogu se upotrebljavati videozapisi. Ako odlučite ukloniti to ograničenje, provjerite učitavaju li se slike i dalje ispravno prije spremanja Map Toura. Moći ćete vratiti to ograničenje kasnije ako je potrebno.",
      "dataPicError8": "Ukloni ograničenje slika",
      "dataPicError9": "Ako ovi URL-ovi ukazuju na videozapise, možete zanemariti to upozorenje, a ako ukazuju na slike, morate izvršiti jednu od sljedećih dviju radnji:",
      "modalCancel": "Odustani",
      "modalApply": "Primijeni",
      "organizeHeader": "Organizirajte obilazak",
      "organizeGeneralCaption": "Upotrijebite povlačenje i ispuštanje da biste sortirali točke obilaska",
      "organizeDelete": "Izbriši",
      "organizeHide": "Sakrij",
      "organizeReset": "Ponovno postavi redoslijed i skrivene točke",
      "addMaxPointReached": "Dostigli se maksimalan broj točaka za koje ste ovlašteni prema postavljenim ikonama i ne možete dodati drugu točku obilaska.<br /><br />Imajte na umu da ako izbrišete postojeće točke, morat ćete ponovno učitati priču.",
      "addMaxPointReachedMobile": "Nažalost, dostigli ste maksimalan broj točaka za koje ste ovlašteni i ne možete dodati ovu sliku.",
      "addClose": "Zatvori",
      "addHeader": "Dodaj novu točku obilaska",
      "addTabPicture": "Mediji",
      "addTabInformation": "Informacija",
      "addTabLocation": "Lokacija",
      "addSelectCaption": "Odaberi ili ispusti sliku",
      "addNoteVideo": "Upute o upotrebi videozapisa potražite u opciji Pomoć",
      "addSelectCaptionNoFileReader": "Odaberi sliku",
      "addChangePhoto": "Promijeni sliku i sličicu",
      "addPictureResolutionIntro": "Razlučivost slike veća je nego što je potrebno:",
      "addPictureResolutionOldBrowser": "Razlučivost slike veća je nego što je potrebno. Optimizirajte Map Tour određivanjem razlučivosti niže od %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Promijeni razlučivost slike na %RESOLUTION%",
      "addPictureResolutionKeep": "Zadrži razlučivost izvorne slike od %RESOLUTION%",
      "addSelectThumbnail": "Odaberi sličicu",
      "addNoThumbSelected": "Sličica nije odabrana",
      "addThumbSelected": "Odabrano",
      "addCameraSettingsHeader": "POSTAVKE KAMERE",
      "addThumbnailHeader": "SLIČICA",
      "addLabelPicUrl": "Slika",
      "addLabelThumbUrl": "Sličica",
      "addTextPlaceholderUrl": "Unesite URL slike",
      "addTextPlaceholderUrl2": "Unesite URL stranice YouTube",
      "addTextPlaceholderUrl3": "Unesite URL stranice Vimeo",
      "addTextPlaceholderUrl4": "Unesite URL za ugrađivanje videozapisa",
      "addLabelVideo": "Videozapis",
      "addMediaVideoOther": "Ostalo",
      "addMediaVideoHelp": "Provjerite URL i primite zadanu sličicu",
      "addMediaVideoHelpTooltip1": "Uspješna provjera",
      "addMediaVideoHelpTooltip2": "Neuspješna provjera",
      "addMediaVideoHelpTooltip4": "Pronađite opciju da biste ugradili videozapis i kopirali URL videozapisa koji se nalazi u kodu",
      "addLabelName": "Naziv",
      "addLabelDescription": "Natpis",
      "addTextPlaceholder": "Utipkajte nešto",
      "addLocatePlaceholder": "Pronađite adresu ili mjesto",
      "addPinColor": "Boja",
      "addLatitude": "Geografska širina",
      "addLongitude": "Geografska dužina",
      "addLatitudePlaceholder": "npr. 34,056",
      "addLongitudePlaceholder": "npr. -117,195",
      "addUploading": "Učitavanje točke obilaska",
      "addSave": "Dodaj točku obilaska",
      "addMobileUploading": "Učitavanje slike",
      "addMobileName": "Unesite naziv",
      "addMobileNameMandatory": "Pogreška, unesite naziv.",
      "addMobileError": "Nažalost, nešto nije u redu.",
      "settingsHeader": "Postavke",
      "settingsTabLayout": "Izgled",
      "settingsTabColor": "Boje",
      "settingsTabLogo": "Zaglavlje",
      "settingsTabFields": "Podaci",
      "settingsTabExtent": "Obuhvat",
      "settingsTabZoom": "Razina uvećanja",
      "settingsLayoutExplain": "Odaberite prikaz koji želite.",
      "settingsLayoutProfessional": "Trostruka ploča",
      "settingsLayoutModern": "Integrirano",
      "settingsLayoutSidePanel": "Bočna ploča",
      "settingsLayoutSelected": "Odabrani izgled",
      "settingsLayoutNew": "Novo!",
      "settingsLayoutSelect": "Odaberi",
      "settingsLayoutNote": "Imajte na umu da na točkama koje imaju videozapis, natpis će se uvijek prikazivati ispod videozapisa čak i ako ta opcija nije označena.",
      "settingsLayoutLocBtn": "Prikaži gumb „Lociraj”",
      "settingsLayoutLocBtnHelp": "Podržano na većini preglednika. Pojavljuje se samo kada se karti s pričom pristupa preko HTTPS-a. Ne pojavljuje se ako je priča umetnuta.",
      "settingsColorExplain": "Promijenite izgled tako da izaberete prethodno utvrđenu temu ili stvorite svoju.",
      "settingsLabelColor": "Boje zaglavlja, sadržaja ili podnožja",
      "settingsLogoExplain": "Prilagodite logotip u zaglavlju (maksimalno 250 x 50 px).",
      "settingsLogoEsri": "Logotip Esri",
      "settingsLogoNone": "Bez logotipa",
      "settingsLogoCustom": "Prilagođeni logotip",
      "settingsLogoCustomPlaceholder": "URL slike",
      "settingsLogoCustomTargetPlaceholder": "Vanjska poveznica",
      "settingsLogoSocialExplain": "Prilagodite poveznicu u zaglavlju gore desno.",
      "settingsLogoSocialText": "Tekst",
      "settingsLogoSocialLink": "Poveznica",
      "settingsLogoSocialDisabled": "Administrator je onemogućio ovu značajku.",
      "settingsDataFieldsExplain": "Odaberite naziv fotografije, natpisa i polja boja.",
      "settingsDataFieldsError": "Aplikacija ne može utvrditi prikladni naziv, natpis ili podatke o boji. Odaberite polja koja će se ovdje upotrijebiti. Ove se postavke mogu kasnije mijenjati.",
      "settingsFieldsLabelName": "Naziv",
      "settingsFieldsLabelDescription": "Natpis",
      "settingsFieldsLabelColor": "Boja",
      "settingsFieldsReset": "Ponovno postavi odabir polja",
      "settingsExtentExplain": "Postavite početni obuhvat Map Toura na interaktivnoj karti u nastavku.",
      "settingsExtentExplainBottom": "Obuhvat koji definirate izmijenit će poečtni obuhvat vaše karte. Imajte na umu da se taj obuhvat ne upotrebljava ako ne uključuje prvu točku obilaska. U tom će se slučaju obilazak otvoriti sa središtem na prvoj točki.",
      "settingsExtentDateLineError": "Obuhvat se ne može protezati preko meridijana 180Â° geografske dužine",
      "settingsExtentDateLineError2": "Pogreška pri izračunavanju obuhvata",
      "settingsExtentDrawBtn": "Nacrtajte novi obuhvat",
      "settingsExtentModifyBtn": "Uredite obuhvat",
      "settingsExtentApplyBtn": "Pretpregled Map Toura",
      "settingsExtentUseMainMap": "Upotrijebi obuhvat Map Toura",
      "settingsZoomExplain": "Postavite uvećanje za točke priče (neobavezno).",
      "settingsLabelZoom": "Mjerilo/razina",
      "settingsZoomFirstValue": "Nema",
      "settingsFieldError": "Odaberi polje na svakom popisu",
      "dataTitle": "Stvori hostirani sloj Map Tour",
      "dataExplain": "Stvorit će se novi sloj geoobjekata za vaše slike i točke obilaska. Sloj obilaska neće biti podijeljen, osim ako ne podijelite Map Tour.",
      "dataExplainPortal": "Ako se sloj geoobjekata ne izradi uspješno, obratite se svom administratoru za ArcGIS.",
      "dataNameLbl": "Naziv sloja",
      "dataFolderListLbl": "Mapa",
      "dataFolderListFetching": "Dohvaćanja mapa...",
      "dataRootFolder": "Korijen",
      "dataNameError": "Unesite naziv za uslugu geoobjekata",
      "dataFolderError": "Odaberi valjanu mapu",
      "dataSrcContainsInvalidChar": "Naziv usluge geoobjekata ima jedan ili više nevažećih znakova (-, <, >, #, %, :, \", ?, &, +, / ili ).",
      "dataSrvAlreadyExistsError": "Usluga s tim nazivom već postoji unutar organizacije. Izaberite drugi naziv.",
      "dataBtnSave": "Stvori sloj",
      "dataFooterProgress": "Stvaranje u tijeku",
      "dataFooterSucceed": "Uspješno stvaranje. Učitavanje",
      "dataFooterError": "Neuspješno stvaranje. Pokušajte ponovno",
      "tabError": "Provjerite ima li pogrešaka u svim karticama",
      "introRecordBtn": "Uvod",
      "introRecordActivate": "Upotrijebite početnu točku kao uvod (ne pojavljuje se u rotirajućem prikazu)",
      "coverRecordActivate": "Upotrijebi prvu točku kao naslovnu stranicu",
      "coverBuilder": "Konfiguracija naslovne stranice",
      "cover": "Naslovnica",
      "showCover": "Prikaži naslovnicu",
      "editCover": "Uredi naslovnicu",
      "coverNoVideo": "Videozapis nije podržan za medij na naslovnici. Odaberite sliku.",
      "coverPreview": "Da biste vidjeli naslovnicu, spremite priču, a zatim je prikažite pomoću gumba Prikaz priče.",
      "thirdPartyTerms": "Upotrebom usluge treće strane pristajete na njihove uvjete korištenja: "
    },
    "addPopupJS": {
      "uploadingPicture": "Učitavanje slike",
      "uploadSuccess": "Uspješno učitavanje",
      "uploadError": "Pogreška pri učitavanju slike",
      "uploadError2": "Pogreška pri dodavanju geoobjekta (nevaljana HTML oznaka)",
      "notJpg": "Izaberite jpeg fotografiju za učitavanje",
      "errorNoPhoto": "Odaberite sliku za učitavanje",
      "errorNoThumbnail": "Odaberite sličicu za učitavanje",
      "errorInvalidPicUrl": "Unesite važeći URL slike. Započinje s https. Završava s jpg, png, gif ili bmp ili završite URL s '#isImage' da biste pregazili to pravilo.",
      "errorInvalidThumbUrl": "Unesite valjanu sličicu (počinje s https://, završava s jpg, png, gif ili bmp).",
      "errorInvalidVideoUrl": "Unesite valjani URL videozapisa (počinje s https://)",
      "errorNoName": "Unesite naziv za ovu točku obilaska",
      "errorNoDescription": "Unesite natpis za ovu točku obilaska",
      "errorNoLocation": "Postavite lokaciju za ovu točku obilaska"
    },
    "builderJS": {
      "noPendingChange": "Nema nespremljenih promjena",
      "unSavedChangeSingular": "1 nespremljena promjena",
      "unSavedChangePlural": "nespremljenih promjena",
      "shareStatus1": "Tour nije spremljen",
      "shareStatus2": "Tour je javno podijeljen",
      "shareStatus3": "Tour je podijeljen s organizacijom",
      "shareStatus4": "Tour nije podijeljen",
      "popoverDiscard": "Jeste li sigurni da želite odbaciti sve nespremljene promjene?",
      "yes": "Da",
      "no": "Ne",
      "popoverLoseSave": "Otvaranjem preglednika, izgubit ćete sve nespremljene promjene",
      "ok": "U redu",
      "popoverSaveWhenDone": "Nemojte zaboraviti spremiti kad završite",
      "closeWithPendingChange": "Jeste li sigurni da želite potvrditi radnju? Izgubit će se vaše promjene.",
      "gotIt": "U redu",
      "savingApplication": "Spremanje priče",
      "saveSuccess": "Priča spremljena",
      "saveError": "Spremanje nije uspjelo, pokušajte ponovno",
      "saveError2": "Spremanje nije uspjelo zbog neispravne html oznake u nazivu ili opisu",
      "saveError3": "Naslov ne smije biti prazan",
      "dragColorPicker": "Pomiči me okolo<br />ili promijeni moju boju",
      "dataWarningExtent": "Imate podatke izvan obuhvata web-karte. Ti podaci neće se upotrijebiti kao točke obilaska, promijenite obuhvata karte ako ih želite upotrijebiti.",
      "dataWarningVisibi": "Vaš sloj Map Toura nije vidljiv na trenutačnom obuhvatu web-karte. Potvrdite je li sloj Map Toura vidljiv s velikom kartom od %MAPSIZE%.",
      "dataWarningEdit": "Uredi web-kartu",
      "dataWarningClose": "Zatvori",
      "signIn": "Prijavite se s računom za",
      "signInTwo": "za spremanje priče.",
      "switchBM": "Promijeni kartografsku podlogu"
    },
    "organizePopupJS": {
      "messageStart": "Izabrali ste brisanje",
      "messageSinglePoint": "jedna točka obilaska",
      "messageMultiPoint": "točke obilaska",
      "messagePermantRemove": "To će trajno ukloniti",
      "messageRecord": "zapis",
      "messageRecordPlural": "zapise",
      "messageConfirm": "iz vaše baze podataka. Želite li nastaviti?",
      "labelButtonShow": "Prikaži",
      "labelButtonHide": "Sakrij"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "To će trajno izbrisati sliku i sličicu",
      "popoverDeleteWarningThumb": "To će trajno izbrisati sličicu",
      "popoverUploadingPhoto": "Učitavanje slike i sličice",
      "popoverUploadingThumbnail": "Učitavanje sličice",
      "popoverUploadSuccessful": "Uspješno učitavanje",
      "popoverUploadError": "Neuspješno učitavanje, pokušajte ponovno",
      "changePicAndThumb": "Promijeni sliku",
      "changeThumb": "Promijeni sličicu",
      "selectPic": "Promijeni medij",
      "selectThumb": "Promijeni sličicu",
      "uploadPicAndThumb": "Primijeni"
    },
    "headerJS": {
      "editMe": "Uredi me!",
      "templateTitle": "Postavi naslov",
      "templateSubtitle": "Postavi podnaslov",
      "edit": "Uredi"
    },
    "crossFaderJS": {
      "setPicture": "Postavi naslov slike",
      "setCaption": "Postavi natpis slike"
    },
    "importPopup": {
      "title": "Uvezi",
      "prevBtn": "Natrag",
      "nextBtn": "Sljedeće"
    },
    "importPopupHome": {
      "header": "Gdje su vam spremljene slike?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "slike",
      "videos": "videozapisi",
      "disabled": "Administrator je onemogućio ovu značajku.",
      "disabledPortal": "Za ovu je značajku potrebno da portal ima poslužitelj domaćin. Obratite se administratoru za Portal for ArcGIS.",
      "header1": "Slike se moraju javno podijeliti.",
      "header2": "Uvoz će biti ograničen na prvi %NB1% %MEDIA%.",
      "emptyDataset": "Pogreška, nema slika",
      "footerImport": "Uvezi",
      "selectAlbum": "Odaberi javni album",
      "selectAlbum2": "Odaberi album",
      "pleaseChoose": "Izaberite",
      "userLookup": "Potraži",
      "userLookingup": "Traženje",
      "csv": "Referencirano u CSV-u",
      "advanced": "Napredne opcije",
      "advancedScratchLbl": "Pokreni novi Tour",
      "advancedScratchTip": "Stvorite prazan obilazak kojem možete dodati točke obilaska. Vaši mediji već moraju biti na internetu. Ta opcija ne podržava učitavanje vlastitih slika.",
      "advancedCSVLbl": "Uvezi podatke o Touru iz CSV datoteke",
      "advancedCSVTip": "Uvezite sadržaj obilaska s CSV datoteke koja referencira vaše medije na internetu. Ta opcije ne podržava učitavanje vlastitih slika.",
      "advancedCommonTip": "Slike i videozapisi već moraju biti na mreži.",
      "select": "Odaberite",
      "locUse": "Upotrijebi geolokaciju slike",
      "locExplain": "Najbolje je ne upotrijebiti lokacije slika jer se mogu naslijediti iz albuma, što može dovesti do toga da su sve fotografije na istoj lokaciji.",
      "locExplain2": "Najbolje je ne upotrijebiti lokacije videozapisa jer se mogu naslijediti iz albuma, što može dovesti do toga da su svi videozapisi na istoj lokaciji."
    },
    "viewFlickr": {
      "title": "Uvoz s Flickra",
      "header": "Unesite korisničko ime za Flickr i odaberite album ili oznaku koji će se uvesti.",
      "userInputLbl": "Unesite korisničko ime",
      "signInMsg2": "Korisnik nije pronađen",
      "selectSet": "Odaberite album",
      "selectTag": "ili odaberi oznaku",
      "footerImportTag": "Uvezi odabranu oznaku",
      "footerImportSet": "Uvezi odabrani album"
    },
    "viewFacebook": {
      "title": "Uvezi s Facebooka",
      "header": "Provjerite autentičnost s korisničkim računom za Facebook ili upotrijebite javnu stranicu. Privatni albumi mogu se upotrijebiti za stvaranje javnog Map Toura za koji ne treba provjera autentičnosti korisnika Facebooka, što omogućuje da komentari i oznake sviđanja ostanu privatni.",
      "leftHeader": "Korisnik Facebooka",
      "rightHeader": "Stranica Facebooka",
      "pageExplain": "Stranica na Facebooku javni je brand/proizvod ili poznati subjekt kao <b>esrigis</b>. Možete vidjeti naziv stranice nakon '/' na URL-u stranice.",
      "pageInputLbl": "Unesite naziv stranice",
      "lookupMsgError": "Stranica nije pronađena"
    },
    "viewPicasa": {
      "title": "Uvoz za Google+",
      "header": "Unesite svoju adresu e-pošte ili ID.",
      "userInputLbl": "ID za e-poštu ili Picasu/Google+",
      "signInMsg2": "Račun nije pronađen",
      "signInMsg3": "Nema javnog albuma",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Saznajte više</a>",
      "howToFind2": "Kopirajte znamenke između prvog i posljednjeg znaka „/” bilo koje stranice Picasa"
    },
    "viewCSV": {
      "title": "Uvoz CSV-a",
      "uploadBtn": "Odaberi ili ispusti CSV datoteku",
      "resultHeaderEmpty": "Ovaj je CSV prazan",
      "resultHeaderSuccess": "Učitano %NB_POINTS% točaka",
      "resultHasBeenLimited": "Uvoz je ograničen na prvih %VAL1% točaka od %VAL2% kako bi se poštivala granica od %VAL3% točaka po obilasku",
      "browserSupport": "Vaš preglednik nije podržan, da biste upotrebljavali CSV, morate <a href='http://browsehappy.com/' target='_blank'>nadograditi preglednik</a> ili upotrebljavati preglednik web-karte ArcGIS.com (vidi Pomoć).",
      "errorLatLng": "Polja geografske širine i dužine nisu pronađena. Moguće vrijednosti za geografsku širinu jesu: <i>%LAT%</i> i za geografsku dužinu: <i>%LONG%</i>.",
      "errorFieldsExplain": "Učitavanje nije uspjelo jer sljedeća potrebna polja nisu pronađena",
      "errorFieldsName": "Moguće vrijednosti za <b>naziv</b>: %VAL%",
      "errorFieldsDesc": "Moguće vrijednosti za <b>opis</b>: %VAL%",
      "errorFieldsUrl": "Moguće vrijednosti za <b>URL slike</b>: %VAL%",
      "errorFieldsThumb": "Moguće vrijednosti za <b>URL sličice</b>: %VAL%",
      "errorFields2Explain": "Učitavanje nije uspjelo jer CSV ne upotrebljava iste atribute kao i sloj za sljedeće atribute",
      "errorFields2Name": "Za <b>naziv</b> upotrijebite %VAL1% umjesto %VAL2%",
      "errorFields2Desc": "Za <b>opis </b> upotrijebite %VAL1% umjesto %VAL2%",
      "errorFields2Url": "Za <b>URL slike</b> upotrijebite %VAL1% umjesto %VAL2%",
      "errorFields2Thumb": "Za <b>URL sličice</b> upotrijebite %VAL1% umjesto %VAL2%",
      "resultFieldsAll": "Uvezeni su svi atributi",
      "resultFieldsNotAll": "Sljedeći atributi nisu uvezeni jer ne postoje u sloju karte",
      "resultFieldsNotAll2": "Uvezeni su sljedeći atributi",
      "footerNextBtnResult": "Uvezi u web-kartu",
      "footerProgress": "Uvoz u tijeku",
      "footerSucceed": "Uspješan uvoz. Učitavanje"
    },
    "viewYoutube": {
      "title": "Uvoz s YouTubea",
      "header": "Unesite korisničko ime za YouTube da biste pronašli javno podijeljene videozapise.",
      "pageInputLbl": "Unesite korisničko ime za YouTube",
      "lookupMsgError": "Korisnik nije pronađen",
      "howToFind": "Kako pronaći YouTube korisničko ime",
      "howToFind2": "Korisničko ime prikazano je ispod videozapisa",
      "found": "Pronađeno",
      "noData": "Nije pronađen nijedan javni videozapis"
    },
    "viewGeoTag": {
      "title": "Odaberite i pronađite svoje slike/videozapise",
      "header": "Uvest će se pronađene stavke. Kliknite na stavke koje želite uvesti a koje nisu pronađene da biste ih pronašli.",
      "headerMore": "Izaberite stil za alat klizača.",
      "headerExplain": "Kada kliknete na gumb <b>Uvoz</b>, uvest će se samo slike i videozapisi koji su navedeni u kartici <b>Pronađeno</b>.<br><br>Informacije o geolokaciji pohranjene sa slikama ili videozapisima uvoze se automatski, ako im se može pristupiti. Sve stavke bez geolokacije navedene su u kartici <b>Za traženje</b>. Da biste pronašli stavku navedenu u toj kartici, kliknite na nju i zatim klinite na željenu lokaciju na karti.<br><br>Da biste uklonili stavku iz kartice <b>Pronađeno</b> ako je ne želite uvesti, kliknite na gum Ne uvozi koji će se prikazati kada stanete pokazivačem iznad te stavke.<br><br>Savjet: ako informacije o geolokaciji vaših medija nisu uvezene, provjerite postavke privatnosti svog računa. Na primjer, u postavkama vašeg Flickr računa provjerite jesu li skriveni EXIF podaci. Također, ako je isključena postavka privatnosti u Flickru za uvoz EXIF podataka za nove stavke (zadana postavka), neće se spremiti geolokacije vaših slika u vaš Flickr osim ako ih ponovo ne učitate ili ručno u Flickru odredite njihove lokacije.",
      "leftPanelTab1": "Za lociranje",
      "leftPanelTab2": "Locirano",
      "clickOrTap": "Kliknite na kartu da biste locirali",
      "clearLoc": "Očisti lokacije",
      "clickDrop": "Nemoj uvesti",
      "footerImport": "Uvezi",
      "footerProgress": "Uvoz u tijeku",
      "footerSucceed": "Uspješan uvoz. Učitavanje...",
      "loading": "Učitavanje",
      "error": "Uvoz geolokacija slika nije uspio, ignoriraju se geolokacije."
    },
    "initPopup": {
      "title": "Dobro došli u sastavljač Map Tour",
      "prevBtn": "Natrag",
      "nextBtn": "Sljedeće"
    },
    "initPopupHome": {
      "header1": "Gdje su vaše slike ili videozapisi?",
      "header2": "Pomoćnik će vam pomoći izraditi Map Tour od medija koji su već pohranjeni na mreži ili će ih uvesti u vaš račun ArcGIS Online za organizacije.",
      "title1": "Već su na mreži",
      "title2": "Trebam učitati slike",
      "hostedFSTooltip": "Učitajte slike i pohranite ih u obilazak (ne podržava videozapise).",
      "hostedFsNA": "Morate biti objavljivač ili u drugoj ulozi s privilegijama za objavljivanje hostiranih slojeva geoobjekata. Obratite se administratoru za ArcGIS.",
      "hostedFsNA2": "Dostupno samo s pretplatom na ArcGIS Online. <a href='%LINK%'>Prijavite se za besplatno probno razdoblje</a>",
      "footer1": "Kad ste gotovi, nemojte zaboraviti podijeliti svoj Map Tour sa svojom publikom putem stranice stavke aplikacije.",
      "footer3": "Preuzmi CSV predložak",
      "footer4": "Ako se ne preuzme, kliknite na „Spremi kao”",
      "footer4bis": "Desnim klikom miša kliknite na „Spremi kao” ako se ne pokrene preuzimanje",
      "footer5": "Saznaj više",
      "footerProgress": "Stvaranje u tijeku",
      "footerSucceed": "Uspješno stvaranje. Učitavanje..."
    },
    "helpPopup": {
      "title": "Pomoć",
      "close": "Zatvori",
      "tab1": {
        "title": "Uvod",
        "moreInfo": "Za više informacija",
        "infoSites": "Posjetite odjeljak <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>Map Tour</a> na web-mjestu <a href='https://storymaps.arcgis.com' target='_blank'>Esri Story Maps.</a>",
        "mtFAQ": "Pogledajte <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>često postavljena pitanja za Map Tour.</a>",
        "myStories": "Možete upravljati svojim Map Tours i provjeriti imaju li pogreške u <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Mojim pričama</a> na web-mjestu.",
        "div1": "Predložak Map Tour osmišljen je za predstavljanje geografskih informacija kada postoji fotografski ili medijski element priče koju želite ispričati.",
        "div2": "Predloškom se daje privlačna web-aplikacija jednostavna za upotrebu koja vam omogućuje da predstavite mali niz mjesta na karti u brojčanom nizu koje korisnici mogu pregledavati. Predložak je osmišljen za upotrebu u svim web-preglednicima na bilo kojem uređaju, uključujući pametne telefone i tablete. <br /><br />",
        "div42": "Da biste vidjeli primjere obilazaka po karti koje drugi korisnici stvaraju, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>posjetite galeriju</a> na web-mjestu <a href='https://storymaps.arcgis.com/' target='_blank'>Story Maps</a>. Možete nas pratiti i na Twitteru na <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Rado bismo vas čuli! Recite nam o problemima i novim značajkama koje vam trebaju tako da posjetite forum Story Maps na <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonetu.</a>"
      },
      "tab2": {
        "title": "Podaci",
        "div1": "Glavni element koji treba razmotriti pri izradi Map Toura jest odabir gdje ćete pohraniti slike. Map Tour može upotrijebiti slike pohranjene na servisima za dijeljenje fotografija, s bilo kojeg poslužitelja ili slike koje učitate s diska.",
        "div1a": "Pojedinosti o podržanim formatima slika i videozapisima potražite u posljednjem odjeljku ove kartice.",
        "div2": "Interaktivni sastavljač daje vam dvije opcije za rukovanje slikama u Map Touru:",
        "div3": "<ul><li>Možete upotrijebiti <b>fotografije koje su već na mreži</b>, kao što su slike u Flickru ili Google+ ili slike pohranjene na vašem mrežnom poslužitelju. Te će se slike referencirati u vašem Map Touru putem njihovih URL-ova.</li><li>Također možete <b>učitati fotografije sa svojeg računala</b> izravno u Map Tour. Za ovu opciju učitavanja morate imate pretplatu za ArcGIS i privilegije izdavača ili administratora jer se automatski stvara hostirana usluga za vas u kojoj se vaše fotografije pohranjuju kao privitci.</li></ul>",
        "div4": "Glavni slučajevi kad se upotrebljava:",
        "div4b": "<b>Vaše fotografije još nisu hostirane</b> i imate pretplatu na ArcGIS: upotreba hostirane usluge geoobjekata najbolji vam je izbor. Kao javni servis za dijeljenje fotografija optimizirat ćemo vam slike kako bismo stvorili slike koje se brzo učitavaju i imat ćete pristup svim mogućnostima za administraciju i upravljanje podacima platforme ArcGIS.",
        "div5": "<b>Niste član organizacije</b>: prvo morate učitati slike na web-mjesto za dijeljenje fotografija ili na vlastiti web-poslužitelj. Sastavljač će vam pomoći upotrijebiti ove slike koje će se nastaviti hostirati na izvornoj lokaciji.",
        "div6": "<b>Želite ponovno upotrijebiti postojeću uslugu geoobjekata</b> koja pohranjuje vaše slike i privitke ili koja referencira vanjske slike: potražite odjeljak s pojedinostima u nastavku.",
        "div7": "<b>Korisnik ste prethodne verzije</b> predloška Map Toura i već imate CSV koji referencira vaše slike i sličice: moći ćete ga uvesti i pročistiti svoje podatke. Sastavljač podupire samo CSV-ove koji upotrebljavaju polja geografske širine/dužine. CSV-ovi koji se temelje na adresama mogu se nastaviti upotrebljavati putem web-karte (vidi odjeljak u nastavku).",
        "div8": "Uvoz sa servisa za dijeljenje fotografija",
        "div9a": "Prekinuta je podrška za Facebook, ${learn}.",
        "learn": "saznaj više",
        "div9": "Operacija uvoza referencira slike koje su već hostirane tako da pohranjuje njihove URL-ove u kolekciji geoobjekata web-karte. Slike nisu pohranjene na programu ArcGIS Online. Ako se hostiranim slikama ne može pristupiti, neće biti dostupne u Map Touru i vidjet ćete obavijest 'Slika nije dostupna'. Ovisno o pružatelju usluga za fotografije, Map Tour možda neće uvesti naziv, opis i lokaciju slika. Ovi su atributi pohranjeni u web-karti i sva uređivanja usluga na mreži neće se odraziti u Map Touru.",
        "div10": "Pohranjivanje slika na web-poslužitelju",
        "div11": "Ako odlučite hostirati svoje fotografije na vlastitom mrežnom poslužitelju (umjesto pristupanja slikama u Flickru ili Google+ ili izravnog učitavanja u obilazak), morat ćete ručno izraditi sličice za svoje slike. Upotreba slika s punom razlučivošću za sličice rezultirat će lošijim performansama. U <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>često postavljenim pitanjima</a> potražite savjete za promjenu veličine vaših slika ako ćete im pristupati mrežno izravno putem URL-ova.",
        "div12": "Upotreba postojećih GIS podataka",
        "div13": "Bilo koja usluga geoobjekata, CSV datoteka ili shapefile koji sadrži točke može se upotrijebiti kao izvor podataka za Map Tour ako sadrži skup polja koje aplikacija očekuje. Morate je/ga dodati kao sloj na ArcGIS web-kartu i zatim podijeliti kartu stvaranjem Map Toura.",
        "div14": "Podržane vrijednosti za naziv polja jesu (velika i mala slova):",
        "div151": "Naziv",
        "div152": "Opis",
        "div153": "Slika",
        "div154": "Sličica",
        "div155": "Boja ",
        "div16": "Ako aplikacija ne pronađe podudarajuća polja prilikom upotrebe usluge geoobjekata, preglednik neće raditi dok ne konfigurirate polja koja će se upotrijebiti putem sastavljača. Slojevi CSV-a i shapefilea dodani na web-kartu moraju imati sva potrebna polja ili sastavljač neće raditi.",
        "div162": "Prilikom upotrebe usluge geoobjekata koja pohranjuje slike kao privitke, <b>upotrijebit će se samo geoobjekti s dva privitka</b>. Prvim se privitkom definira glavna slika, a drugim se privitkom definira sličica.",
        "div17": "Polja slike i sličice su obvezna za usluge geoobjekata bez privitaka, a nisu obvezna (no preporučuju se) za usluge geoobjekata s privicima. Ako vaša usluga ima omogućene privitke, sastavljač će vam dopustiti da učitate slike kao privitke. Ako nema, moći ćete samo urediti URL-ove slike i sličice.",
        "div172": "Kada postoje, polja slike i sličice uvijek će se upotrijebiti i neće biti upita za privicima usluge geoobjekata.",
        "div173": "Primjeri CSV-a i shapefileova mogu se preuzeti s",
        "div174": "Pogledajte <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>često postavljena pitanja</a> i pronađite više informacija o upotrebi postojećih GIS podataka.",
        "div18": "Stvaranje hostirane usluge geoobjekata od CSV-a ili shapefile",
        "div19": "Kada stvorite hostiranu uslugu geoobjekata od CSV-a ili shapefilea, privici nisu omogućeni po zadanim postavkama. Da bi ste ih omogućili, otvorite stranicu o pojedinostima značajke usluge geoobjekata, kliknite na malu strelicu na odjeljku sloja i vidjet ćete tu opciju. Map Tour nastavit će upotrebljavati slike i sličice koje ste referencirali atributima. Po želji, ako želite učitati svoje slike kao privitke usluge geoobjekata, moći ćete to napraviti putem dva gumba na ploči slike („Promijeni sliku” i „Promijeni sličicu”).",
        "div20": "Podržani formati slika i videozapisi",
        "div21": "Ako pristupate slikama u Flickru ili Google+, Map automatski pristupa tim slikama kao .jpg datotekama. Ako učitate slike u sastavljač za Map Tour, slike trebaju biti u formatu .jpg ili .jpeg. Ako navodite slike izravno s mreže putem URL-ova, podržani formati slika su .jpg, .jpeg, .png, .gif i .bmp. Videozapisi s YouTubea izravno su podržani.",
        "div22": "Predložak Map Tour ne uključuje reproduktor videozapisa pa morate upotrijebiti vanjski reproduktor videozapisa koji pruža vaš omiljeni servis za hostiranje videozapisa (pronađite opciju za ugrađivanje videozapisa i kopirajte URL u danom kodu). Ako sami želite hostirati videozapis, možete stvoriti HTML stranicu koja sadrži reproduktor videozapisa poput <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Interaktivni sastavljač ne pruža dijalog za uključivanje videozapisa prilikom upotrebe usluge geoobjekata s privicima, no moguće je to napraviti uređivanjem podataka izvan interaktivnog sastavljača. U pregledniku karte na arcgis.com ako izmijenite polja slike da ukazuju na vanjski videozapis i dodate posebne parametre na kraju svojeg URL-a (#isVideo), vaš će se medij smatrati videozapisom.",
        "div24": "Imajte na umu da još uvijek morate imati dva valjana privitka sa slikama ili se točka neće upotrijebiti. Nije moguće upotrijebiti videozapise prilikom upotrebe privitaka usluge geoobjekata bez polja slike i sličice."
      },
      "tab3": {
        "title": "Prilagođavanje",
        "div1": "Sastavljač pruža nekoliko opcija za prilagođavanje koje su dostupne kroz gumb POSTAVKE na gornjoj ploči. Ako ne pronađete opciju koju očekujete pružamo i verziju koja se može preuzeti i koju možete implementirati na svojem web-poslužitelju i poboljšati da odgovara vašim potrebama.",
        "div2": "Preporučujemo da upotrebljavate hostiranu verziju osim sljedećeg:",
        "div3": "<li>Ne pruža prilagođavanje korisničkog sučelja koji želite imati, kao upotreba pozadinske slike zaglavlja.</li><li>Vi ste programer i želite poboljšati aplikaciju.</li>",
        "div4": "Verziju koju je moguće preuzeti može se konfigurirati putem identifikatora aplikacije web-kartiranja ili web-karte. Glavni slučajevi uporabe:",
        "div41": "Izradite obilazak po karti s pomoću interaktivnog sastavljača u hostiranoj okolini i konfigurirajte predložak s identifikatorom aplikacije web-kartiranja. Primijenit će se postavke koje ste definirali s interaktivnim sastavljačem.",
        "div42": "Izradite web-kartu izvan interaktivnog sastavljača i konfigurirajte predložak identifikatorom web-karte. Morat ćete pročitati dokumentaciju da biste naučili kako konfigurirati predložak.",
        "div43": "Imajte na umu da je interaktivni sastavljač dostupan u verziji za preuzimanje, no s nekim tehničkim ograničenjima na preglednicima kao što su verzije preglednika Internet Explorer ranije od verzije 10.",
        "div5": "Da biste preuzeli najnoviju verziju predloška i saznali više o tome kako ga upotrebljavati, posjetite <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>stranicu projekta GitHub</a>."
      },
      "tab4": {
        "title": "Savjeti",
        "div0": "Podržani preglednici",
        "div0a": "Preglednik Map Toura podržava IE8+. Interaktivni sastavljač podržava IE9+. Aktivno smo ga ispitali u svim glavnim preglednicima, ali ako doživite poteškoće, preporučujemo koristiti Chrome.",
        "div0b": "Ako imate poteškoća, obavijestite nas. U međuvremenu, ako izradite Map Tour s pomoću predloška CSV, umanjit ćete interakciju sa sučeljem sastavljača.",
        "div1": "Slike",
        "div2": "Iako se u jednom Map Touru mogu upotrebljavati slike različitih veličina, oblika i usmjerenja, preporučujemo vodoravno usmjerenje fotografija, a ne okomito. Najbolje će odgovarati slike omjera 4:3. U izgledima s trostrukom pločom i integriranim izgledima u kojima se natpis preklapa preko slike upotreba slika okomitog usmjerenja može dovesti do toga da je većina slike skrivena natpisom. U izgledima s trostrukom pločom i integriranim izgledima preporučujemo upotrebu jedinstvene veličine i oblika za sve slike. Na taj način korisnika neće omesti slike različitih veličina tijekom obilaska.",
        "div2a": "Preporučujemo maksimalnu veličinu slike od 1000 px širine x 750 px visine za glavnu sliku i 140 x 93 px za sličice.",
        "div3": "Formatiranje teksta natpisa s pomoću HTML oznaka",
        "div4": "Možete unijeti HTML oznake na natpise da biste definirali formatiranje i poveznice. Primjerice, ove oznake dodaju zelenu hipervezu:",
        "div4aa": "<b>Stvorite naslovnu stranicu za svoj obilazak bočne ploče</b><br>Izgled bočne ploče podržava dodatnu naslovnicu, tako možete privući pozornost svoje publike putem sjajne slike preko punog zaslona. Da biste konfigurirali naslovnu stranicu za obilazak bočne ploče, prvo dodajte neke ili sve točke u svoj obilazak. Zatim kliknite na gumb Organiziraj i u dijaloškom okviru koji se pojavi provjerite je li točka obilaska koju želite upotrijebiti za naslovnu stranicu prva točka u vašem obilasku. Zatim u dijaloškom okviru kliknite na „Upotrijebi prvu točku kao naslovnu stranicu”. Naziv prve točke vašeg obilaska postat će naslov koji će se prikazivati na naslovnoj stranici, natpis te točke postat će podnapis, a slika te točke upotrijebit će se kao slika naslovne stranice. Videozapis nije podržan na naslovnoj stranici. Više informacija potražite u <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>često postavljenim pitanjima</a>.</a>",
        "div4a": "Napišite dobar podnapis za svoj obilazak",
        "div4b": "Uložite vrijeme kako biste napisali zanimljive podnapise za obilazak. Podnapisi su dobar način za privlačenje ljudi i za obavještavanje o tome što mogu saznati u obilasku. Osim toga, podnapisima možete informirati svoju publiku o državi ili županiji u kojoj se nalazi obilazak. Nemojte pretpostaviti da ljudi znaju primjerice gdje se nalazi grad u kojem se odvija vaš obilazak. Pripazite ipak da podnapis ne bude predug. Ako ne možete smisliti dobar podnapis, ostavite ga praznim. Za razliku od trostruke ploče i integriranog izgleda, izgled bočne ploče nhe podržava podnapis u zaglavlju. Ako upotrebljavate opciju naslovne stranicu u izgledu bočne ploče, natpis prve točke u vašem obilasku prikazat će se na naslovnoj stranici i poslužit će kao podnapis za vaš obilazak.",
        "div5": "Dodatni slojevi",
        "div6": "Možete umetnuti dodatne slojeve da prikažu kontekst Map Toura. Ti slojevi mogu sadržavati ostale geoobjekte koje želite prikazati na karti uz točke obilaska, kao što su studijska područja, ruta za šetanje ili vožnju koja povezuje vaše točke obilaska itd. Predložak za Map Tour prikazat će dodatne slojeve s pomoću simbologije koju odredite na web-karti, ali skočni prozori za slojeve nisu podržani. Da biste dodali dodatne slojeve na obilazak, spremite ono što ste napravili i zatvorite sastavljač Map Tour. Zatim otvorite web-kartu koja se upotrebljava u vašem obilasku. To možete pronaći u Mojem sadržaju ArcGIS ili u odjeljku Moje priče na web-mjestu Story Maps.",
        "div7": "Neka obilazak bude kratak i sladak",
        "div8": "Postoji ograničenje od 99 točaka po obilasku. Naravno, većina Map Tourova bit će mnogo kraća. Ne očekujte od publike da želi proći kroz previše točaka obilaska. Vama je možda vaša tema iznimno zanimljiva, ali nemojte pretpostaviti da će i njima biti!",
        "div10": "Ugradbeni način",
        "div11": "Ako želite ugraditi svoj predložak u neko drugo web-mjesto s pomoću iFramea, umetanjem dodatnog parametra \"&embed\" na kraju URL-a izgubit će se zaglavlje.",
        "div12": "Izbjegavajte upotrebu uskog iFramea zbog kojeg će se obilazak po karti prebaciti na izgled za mali prikaz, što je isti prikaz koji se upotrebljava za mobilne uređaje. Da biste olakšali upotrebu, kad je obilazak po karti ugrađen, uvijek preporučujemo da svejedno umetnete još i poveznicu pored ugrađenog obilaska jer ga tako korisnici mogu pokrenuti na punom zaslonu."
      },
      "tab5": {
        "title": "Objavljivanje",
        "div1": "Kad ste gotovi, ne zaboravite podijeliti svoj Map Tour sa svojom publikom preko gumba PODIJELI ili putem stranice stavke aplikacije na ArcGIS Online.",
        "div2a": "Dijeljenje Toura putem sastavljača",
        "div2b": "Gumb PODIJELI ažurirat će stavke aplikacije i web-karte. Ako su podaci Toura pohranjeni u stavci usluge geoobjekata, također će se ažurirati. Ako ste dodali druge slojeve putem preglednika karata ArcGIS.com, neće se ažurirati. Zbog toga se možda vaš Tour neće podijeliti kako ste očekivali. Stavke koje već imaju potrebne privilegije (ili ih premašuju) neće se ažurirati.",
        "div2c": "Dijeljenje Toura kroz ArcGIS Online",
        "div2d": "Kada dijelite svoju aplikaciju preko programa ArcGIS Online, on će zatražiti od vas, ako je neophodno, da ažurirate sve povezane resurse (web-kartu, uslugu geoobjekata, ukrasni sloj) koji nisu podijeljeni na isti način. Ako je Map Tour javan i neki od vaših resursa nije podijeljen s publikom, korisnici će biti preusmjereni na stranicu za prijavu u ArcGIS Online.",
        "div3t": "Sigurnost za uslugu geoobjekata",
        "div3a": "Ako upotrebljavate hostiranu uslugu geoobjekata izrađenu s pomoću sastavljača za Map Tour, aplikacija će upravljati sigurnošću usluge umjesto vas, a vi ćete biti jedina osoba s uređivačkim privilegijama, čak i ako javno objavite uslugu.",
        "div3t2": "Prije nego što podijelite svoj Tour s publikom",
        "div3": "Provjerite radi li Tour ispravno kada niste prijavljeni svojim računom za ArcGIS.com. URL koji ćete upotrijebiti ne bi trebao preusmjeriti prema stranici za prijavu ili prema načinu sastavljača.",
        "div4": "Dobra je ideja vidjeti kako izgleda vaš obilazak po karti na iPadu u vodoravnom usmjerenju kako biste bili sigurni da izgleda dobro na ovom popularnom uređaju. Ovime možete vidjeti pokrivaju li vaši natpisi preveliki dio slika. Možete i vidjeti odgovaraju li podnaslovi i jesu li toliko veliki da se dio ne vidi.",
        "div5a": "Preporuka za pretraživanje",
        "div5b": "Da biste pomogli ljudima pronaći vaš Map Tour, ako pretražuju u ArcGIS Online, preporučujemo da dodate oznaku 'karta s pričom' u stranicu stavke aplikacije obilaska po karti (ne u stranicu stavke web-karte) uz oznake kao što je naziv županije u kojoj se nalazi obilazak, naziv države i tematske oznake kao što su 'javna umjetnost', 'turistički vodič' ili 'povijesna mjesta'. Te oznake pomažu i nama u tvrtki Esri da pronađemo zgodne nove primjere obilazaka koje možemo pokazati u našim galerijama i promovirati u društvenim medijima. Preporučujemo da učitate lijepu sličicu na stranicu stavke aplikacije, poput male snimke zaslona ili jedne od slika iz nje. Ova slika će se koristiti automatski ako je vaš obilazak po karti dodan u galeriju programa ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Tour spremljen",
      "manageStory": "Upravljajte svojom pričom",
      "manageStoryA1": "Savjet: možete upotrijebiti %LINK1% za provjeru ima li pogrešaka u vašoj priči, za mijenjanje načina dijeljenja ili izgleda u društvenim medijima itd. Saznajte više o Ma Stories %LINK2%.",
      "manageStoryA1V1": "Moje priče",
      "manageStoryA1V2": "ovdje",
      "shareTitle": "Podijelite svoj Tour",
      "sharePrivateHeader": "Vaš Tour nije podijeljen, želite li ga podijeliti?",
      "sharePrivateBtn1": "Podijeli javno",
      "sharePrivateBtn2": "Podijeli s mojom organizacijom",
      "sharePrivateProgress": "Dijeljenje u tijeku...",
      "sharePrivateErr": "Dijeljenje nije uspjelo, pokušajte ponovno ili",
      "sharePrivateOk": "Dijeljenje je ažurirano, učitavanje...",
      "sharePreviewAsUser": "Pretpregled",
      "shareHeader1": "Vaš je Tour <strong>javno dostupan</strong>.",
      "shareHeader2": "Vaš Tour dostupan je članovima vaše organizacije (potrebna je prijava)",
      "shareLinkHeader": "Podijelite svoj Tour",
      "shareLinkOpen": "OTVORI",
      "shareA1": "Upotrijebite %SHAREIMG% na <a href='%LINK1%' target='_blank'>stranici stavke aplikacije</a>. Ako želite prekinuti dijeljenje web-karte, upotrijebite <a href='%LINK2%' target='_blank'>stranicu stavke web-karte</a>.",
      "shareWarning": "Onemogućeno je dijeljenje %WITH% jer niste vlasnik <a href='%LINK%' target='_blank'>web-karte</a>.",
      "shareWarningWith1": "javno",
      "shareWarningWith2": "javno i s organizacijom",
      "viewStory": "Prikaz priče"
    },
    "locator": {
      "error": "Lokacija nije dostupna"
    },
    "saveErrorSocial": {
      "title": "Ažuriranje dijeljenja na društvenim mrežama",
      "panel1": "Poboljšana je prisutnost vaše priče na društvenim medijima, ali naziv stavke u ArcGIS web-aplikaciji nije jednak nazivu vaše priče.",
      "panel1tooltip": "Kada odredite naziv, sažetak i sličicu, vaša će priča izgledati ovako:",
      "panel2": "Koji biste naziv upotrijebili na društvenim medijima:",
      "panel2q1": "Naziv priče (preporučeno)",
      "panel2q1tooltip": "Ako odaberete ovu mogućnost, naziv vaše stavke izmijenit će se kako bi se podudarao s naslovom vaše priče, a dodatne promjene u sastavljaču će se sinkronizirati.",
      "panel2q2": "Naslov stavke",
      "panel3": "Da biste dodatno poboljšali izgled svoje priče na društvenim medijima, upotrijebite ${MYSTORIES} za dodavanje sažetka i sličice.",
      "panel4": "Ne upozoravaj me ponovno za ovu priču",
      "mystories": "Moje priče",
      "btnSave": "Spremi"
    },
    "bannerNotification": {
      "learnMore": "Saznaj više",
      "close": "Zatvori",
      "dontShowAgain": "Nemoj ponovno prikazati ovu poruku"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Važna poruka o internetskoj sigurnosti i Story Mapsu",
      "s1h1": "Esri unaprjeđuje sigurnost Story Mapsa",
      "s1p1": "Vaše Story Maps uživo na mreži i mrežna zajednica uvijek radi na uspostavljanju u ostvarivanju veće sigurnosti. HTTPS, koji omogućuje sigurnu vezu za sadržaj koji se prenosi putem interneta, sve se češće pojavljuje se kao način pristupa mrežnom sadržaju Najmoderniji pretraživači sada prikazuju poruke upozorenja kada se upotrebljava HTTP umjesto HTTPS-a. Zbog ovog rastućeg standarda, preporučujemo da upotrebljavate HTTPS poveznice za stvaranje i dijeljenje za Story Maps i da upotrebljavate samo HTTPS URL-ove kada ugrađujete mrežni sadržaj ili stvarate poveznice na slike unutar Story Maps.",
      "s1p2": "Općenito govoreći, to znači da u Story Maps i sav pripadajući sadržaj (uključujući slike, slojeve, ugrađene appove i web-mjesta) treba pristupiti putem povezinica koje počinju s HTTPS, a ne HTTP. To osigurava najbolje iskustvo vašim čitateljima jer će većina mrežnih preglednika prepoznati da su vaše priče sigurne.",
      "s2h1": "Što trebam napraviti?",
      "s2p1": "Esri radi na toma da olakša ovaj prijelaz za autore i čitače usluge Story Maps. Alati su dostupni sada u sastavljačima za Story Map i My Stories koji vam olakšavaju pronalaženje nesigurnog sadržaja (HTTP) u vašim pričama i nude vam preporuke kako ih riješiti. Pregledajte ima li u vašim pričama nesigurnog sadržaja i nadogradite ih na HTTPS što je prije moguće.",
      "action1": "Zatvori",
      "action2": "Sada pregledaj moje priče",
      "action3": "Saznajte više"
    },
    "embedBar": {
      "share": "Podijeli",
      "fullScreen": "Puni zaslon",
      "enlarge": "Uvećaj",
      "newTab": "Otvori u novoj kartici",
      "tagline": "Story Map",
      "exitFullScreen": "Izađi iz punog zaslona"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Možemo li vas nešto pitati? Pomoći će nam u oblikovanju budućnosti usluge Story Maps.",
      "s1h1": "Podijelite svoje misli, oblikujte budućnost",
      "s1p1": "Vaša su iskustva naš najvažniji izvor povratnih informacija i ako saznamo više o vama, to će nam pomoći poboljšati Story Maps. Bili bismo zahvalni ako biste sudjelovali u ovoj anketi koja traje tri minute.",
      "s2p1": "Kao i uvijek, hvala na korištenju Esri Story Maps!",
      "action1": "Zatvori",
      "action2": "Ispuni anketu"
    },
    "licenseChange2018": {
      "noAccess": "Vaš račun (%USER_NAME%) nije licenciran za upotrebu Story Mapa koji nije javan. Obratite se administratoru svoje organizacije da vam dodijeli vrstu korisnika koja sadrži licencu za Story Map ili za dodatke za osnovne appove."
    }
  }
});