define({
  "viewer": {
    "loading": {
      "step1": "UČITAVANJE PRIČE",
      "step2": "UČITAVANJE PODATAKA",
      "step3": "POKRETANJE OBILASKA",
      "loadBuilder": "PREBACIVANJE NA NAČIN RADA SASTAVLJAČA",
      "redirectSignIn": "PREUSMJERAVANJE NA STRANICU ZA PRIJAVU",
      "redirectSignIn2": "(bit ćete preusmjereni ovamo nakon prijave)",
      "fail": "Nažalost, učitavanje obilaska po karti nije uspjelo",
      "failButton": "Pokušaj ponovno"
    },
    "errors": {
      "boxTitle": "Došlo je do pogreške",
      "portalSelf": "Kobna pogreška: nije uspjelo učitavanje konfiguracije portala",
      "invalidConfig": "Kobna pogreška: neispravna konfiguracija",
      "invalidConfigOwner": "Kobna pogreška: neispravna konfiguracija (potreban ovlašteni vlasnik)",
      "invalidConfigNoWebmap": "Kobna pogreška: neispravna konfiguracija (identifikator web-karte ili aplikacije nije određen u index.html)",
      "invalidConfigNoAppDev": "Identifikator aplikacije za web-kartiranje ili web-karta nije određena u parametrima URL-a (?appid= ili ?webmap=). U načinu rada razvoja ignoriraju se konfiguracije za appid i web-kartu u index.html.",
      "createMap": "Nije moguće stvoriti kartu",
      "invalidApp": "Kobna pogreška: priča se ne može učitati",
      "noLayer": "Ova web-karta nema valjani sloj podataka za Map Tour.",
      "noLayerMobile": "Sastavljač Map Tour nije podržan u ovoj veličini prikaza. Ako je moguće, promijenite veličinu preglednika da biste pristupili sastavljaču ili izradite priču na uređaju s većim zaslonom.",
      "noLayerMobile2": "Zakrenite uređaj u vodoravnu orijentaciju kako biste upotrijebili sastavljač Map Tour.",
      "noLayerView": "Dobro došli u web-aplikaciju Map Tour.<br />Priča još nije konfigurirana.",
      "appSave": "Pogreška pri spremanju priče",
      "mapSave": "Pogreška pri spremanju web-karte",
      "featureServiceLoad": "Pogreška učitavanja usluge geoobjekata",
      "notAuthorized": "Niste ovlašteni za pristup ovoj priči",
      "notAuthorizedBuilder": "Niste ovlašteni za upotrebu sastavljača Map Tour.",
      "oldBrowserTitle": "Preglednik nije u potpunosti podržan",
      "noBuilderIE8": "Sastavljač Map Tour nije podržan na verzijama pregledniku Internet Explorer ranijim od verzije 9.",
      "ie10Win7Explain": "Interaktivni sastavljač Map Tour nije podržan na pregledniku Internet Explorer 10 na Windows 7 kada je izvor podataka usluga geoobjekata s privicima. Da biste upotrijebili uslugu geoobjekata s privicima, morate <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>ručno postaviti način rada za dokumente na standarde preglednika Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>vratiti se na verziju preglednika Internet Explorer 9</a> ili nadograditi na Windows 8.",
      "oldBrowserExplain": "Ovaj preglednik ne podržava automatsko stvaranje sličice od slika koje prenesete u svoj obilazak po karti. Možete stvoriti obilazak po karti s pomoću ovog preglednika, no morat ćete napraviti zasebnu sličicu za svaku sliku koju prenesete.",
      "oldBrowserExplain2": "Da biste olakšali svoj rad, <a href='http://browsehappy.com/' target='_blank'>nadogradite preglednik</a> ili <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivirajte Google Chrome Frame za Internet Explorer</a>.",
      "oldBrowserExplain3": "Sastavljač Map Tour ne radi s preglednikom Internet Explorer 10 na Windows XP.",
      "oldBrowserClose": "Zatvori",
      "noViewerIE2": "Pokušavate prikazati ovu priču preko starijeg, nepodržanog preglednika. Možda neki geoobjekti ne rade ili je došlo do drugih neočekivanih problema. Predlažemo nadogradnju u Internet Explorer 11 ili korištenje drugog preglednika, primjerice Chromea.",
      "noViewerIE3": "Krajem 2017. ova se priča više neće moći učitati u ovom pregledniku. Tada ćete morati koristiti podržani preglednik za prikaz ove priče.",
      "attention": "Pozor!"
    },
    "mobileHTML": {
      "showIntro": "PRIKAŽI NASLOV",
      "hideIntro": "SAKRIJ NASLOV",
      "navList": "Popis",
      "navMap": "Karta",
      "navInfo": "Mediji",
      "introStartBtn": "Početak"
    },
    "desktopHTML": {
      "storymapsText": "Karta s pričom",
      "builderButton": "Prebaci na način rada sastavljača",
      "facebookTooltip": "Podijeli na Facebooku",
      "twitterTooltip": "Podijeli na Twitteru",
      "bitlyTooltip": "Preuzmite kratku poveznicu",
      "bitlyStartIndex": "Stavi poveznicu na trenutačno mjesto",
      "tooltipAutoplayDisabled": "Ovo nije dostupno u načinu automatske reprodukcije",
      "autoplayLabel": "Način automatske reprodukcije",
      "autoplayExplain1": "Način automatske reprodukcije napredovat će kroz vašu priču u redovitim intervalima. To je idealno za kiosk ili javno prikazani zaslon, no budite svjesni da će se u drugim situacijama priča možda teže čitati. Ova značajka nije podržana na malim zaslonima.",
      "autoplayExplain2": "Kada je ovaj način rada aktivan, postoje kontrole za reprodukciju/pauziranje priče i podešavanje brzine navigacije."
    },
    "builderHTML": {
      "panelHeader": "KONFIGURACIJA PRIČE",
      "buttonSave": "SPREMI",
      "buttonSettings": "Postavke",
      "buttonShare": "Podijeli",
      "buttonView": "Način prikaza",
      "buttonItem": "Otvori stavku web-aplikacije",
      "buttonHelp": "Pomoć",
      "buttonOrganize": "Organiziraj",
      "buttonAdd": "Dodaj",
      "buttonImport": "Uvezi",
      "buttonImportDisabled": "Uvoz nije dostupan kad se upotrebljava usluga geoobjekata s privicima",
      "dataEditionDisabled": "Onemogućeno je uređivanje podataka na ovom izvoru CSV podataka",
      "dataSourceWarning": "Promijenio se sloj podataka Map Tour. Ako ID-ovi geoobjekata nisu isti, morate ponovno postaviti redoslijed i skrivene točke značajkom <b>Organiziraj</b>. Ako se razlikuje naziv polja, morate ponovno postaviti postavke polja u <b>kartici podataka u postavkama</b>.",
      "organizeWarning": "Skrivena je jedna ili više točki dodane izvan interaktivnog sastavljača.",
      "dataPicError0a": "Ovaj obilazak ima <b>%NB%</b> URL-ova slika koji nisu usklađeni.",
      "dataPicError0b": "Ovaj obilazak može imati <b>%NB%</b> URL-ova slika koji nisu usklađeni.",
      "dataPicError1": "Za Map Tour sada je potrebno da URL slike završava s jednim od sljedećih nastavaka: .jp(e)g, .png, .gif ili .bmp.",
      "dataPicError2": "Ovaj zahtjev neće utjecati na postojeći objavljeni Map Tour. Međutim, kako biste upotrijebili interaktivni sastavljač, morate prvo riješiti problem s URL-om izvođenjem jedne od dvije radnje:",
      "dataPicError3": "Uredite URL-ove",
      "dataPicError4": "To će dodati <i>#isImage</i> na kraj nepodržanog URL-a slike. Većina poslužitelja podržava nastavke URL-a. Međutim, kad izvedete tu radnju, trebali biste provjeriti jesu li ažurirani URL-ovi slika funkcionalni navigiranjem kroz točke. Ako se učita svaka slika, tada možete spremiti Map Tour. Ako se  <b>slike ne prikazuju, nemojte spremiti Map Tour</b>. Umjesto toga, ponovno učitajte sastavljač i izvedite drugu radnju.",
      "dataPicError5": "Ograničite obilazak na slike",
      "dataPicError6": "Ovom se opcijom uzrokuje da se svi URL-ovi smatraju slikama, no nećete moći dodavati videozapise s pomoću interaktivnog sastavljača. Ova se radnja može poništiti ako odlučite dodati videozapis u budućnosti.",
      "dataPicError7": "Map Tour ograničen je na slike, ne mogu se upotrijebiti videozapisi. Ako odlučite ukloniti to ograničenje, provjerite učitavaju li vam se još uvijek slike ispravno prije nego što spremite Map Tour. Moći ćete vratit to ograničenje kasnije ako bude potrebno.",
      "dataPicError8": "Ukloni ograničenje slika",
      "dataPicError9": "Ako ovi URL-ovi ukazuju na videozapise, možete ignorirati to upozorenje, a ako ukazuju na sliku, morate izvršiti jednu od sljedeće dvije radnje:",
      "modalCancel": "Odustani",
      "modalApply": "Primijeni",
      "organizeHeader": "Organizirajte obilazak",
      "organizeGeneralCaption": "Upotrijebite povlačenje i ispuštanje da biste sortirali točke obilaska",
      "organizeDelete": "Izbriši",
      "organizeHide": "Sakrij",
      "organizeReset": "Ponovno postavi redoslijed i skrivene točke",
      "addMaxPointReached": "Dostigli se maksimalan broj točaka za koje ste ovlašteni prema postavljenim ikonama i ne možete dodati drugu točku obilaska.<br /><br />Imajte na umu da ako izbrišete postojeće točke, morat ćete ponovno učitati priču.",
      "addMaxPointReachedMobile": "Nažalost, dostigli ste maksimalan broj točaka za koje ste ovlašteni i ne možete dodati ovu sliku.",
      "addClose": "Zatvori",
      "addHeader": "Dodaj novu točku obilaska",
      "addTabPicture": "Mediji",
      "addTabInformation": "Informacija",
      "addTabLocation": "Lokacija",
      "addSelectCaption": "Odaberi ili ispusti sliku",
      "addNoteVideo": "Upute o upotrebi videozapisa potražite u opciji Pomoć",
      "addSelectCaptionNoFileReader": "Odaberi sliku",
      "addChangePhoto": "Promijeni sliku i sličicu",
      "addPictureResolutionIntro": "Razlučivost slike veća je nego što je potrebno:",
      "addPictureResolutionOldBrowser": "Razlučivost slike veća je nego što je potrebno. Optimizirajte Map Tour određivanjem razlučivosti niže od %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Promijeni razlučivost slike na %RESOLUTION%",
      "addPictureResolutionKeep": "Zadrži razlučivost izvorne slike od %RESOLUTION%",
      "addSelectThumbnail": "Odaberi sličicu",
      "addNoThumbSelected": "Sličica nije odabrana",
      "addThumbSelected": "Odabrano",
      "addCameraSettingsHeader": "POSTAVKE KAMERE",
      "addThumbnailHeader": "SLIČICA",
      "addLabelPicUrl": "Slika",
      "addLabelThumbUrl": "Sličica",
      "addTextPlaceholderUrl": "Unesite URL slike",
      "addTextPlaceholderUrl2": "Unesite URL stranice YouTube",
      "addTextPlaceholderUrl3": "Unesite URL stranice Vimeo",
      "addTextPlaceholderUrl4": "Unesite URL za ugrađivanje videozapisa",
      "addLabelVideo": "Videozapis",
      "addMediaVideoOther": "Ostalo",
      "addMediaVideoHelp": "Provjerite URL i primite zadanu sličicu",
      "addMediaVideoHelpTooltip1": "Uspješna provjera",
      "addMediaVideoHelpTooltip2": "Neuspješna provjera",
      "addMediaVideoHelpTooltip4": "Pronađite opciju da biste ugradili videozapis i kopirali URL videozapisa koji se nalazi u kodu",
      "addLabelName": "Naziv",
      "addLabelDescription": "Natpis",
      "addTextPlaceholder": "Utipkajte nešto",
      "addLocatePlaceholder": "Pronađite adresu ili mjesto",
      "addPinColor": "Boja",
      "addLatitude": "Geografska širina",
      "addLongitude": "Geografska dužina",
      "addLatitudePlaceholder": "npr. 34,056",
      "addLongitudePlaceholder": "npr. -117,195",
      "addUploading": "Učitavanje točke obilaska",
      "addSave": "Dodaj točku obilaska",
      "addMobileUploading": "Učitavanje slike",
      "addMobileName": "Unesite naziv",
      "addMobileNameMandatory": "Pogreška, unesite naziv.",
      "addMobileError": "Nažalost, nešto nije u redu.",
      "settingsHeader": "Postavke priče",
      "settingsTabLayout": "Izgled",
      "settingsTabColor": "Boje",
      "settingsTabLogo": "Zaglavlje",
      "settingsTabFields": "Podaci",
      "settingsTabExtent": "Obuhvat",
      "settingsTabZoom": "Razina uvećanja",
      "settingsLayoutExplain": "Odaberite prikaz koji želite.",
      "settingsLayoutProfessional": "Izgled s trostrukom pločom",
      "settingsLayoutModern": "Integrirani izgled",
      "settingsLayoutSelected": "Odabrani izgled",
      "settingsLayoutSelect": "Odaberi ovaj izgled",
      "settingsLayoutNote": "Imajte na umu da na točkama koje imaju videozapis, plakat će se uvijek prikazivati ispod videozapisa čak i ako ta opcija nije označena.",
      "settingsLayoutLocBtn": "Prikaži gumb „Lociraj”",
      "settingsLayoutLocBtnHelp": "Podržano na većini preglednika. Pojavljuje se samo kada se karti s pričom pristupa preko HTTPS-a. Ne pojavljuje se ako je priča umetnuta.",
      "settingsColorExplain": "Promijenite izgled tako da izaberete prethodno utvrđenu temu ili stvorite svoju.",
      "settingsLabelColor": "Boje zaglavlja, sadržaja ili podnožja",
      "settingsLogoExplain": "Prilagodite logotip u zaglavlju (maksimalno 250 x 50 px).",
      "settingsLogoEsri": "Logotip Esri",
      "settingsLogoNone": "Bez logotipa",
      "settingsLogoCustom": "Prilagođeni logotip",
      "settingsLogoCustomPlaceholder": "URL slike",
      "settingsLogoCustomTargetPlaceholder": "Vanjska poveznica",
      "settingsLogoSocialExplain": "Prilagodite poveznicu u zaglavlju gore desno.",
      "settingsLogoSocialText": "Tekst",
      "settingsLogoSocialLink": "Poveznica",
      "settingsLogoSocialDisabled": "Administrator je onemogućio ovu značajku.",
      "settingsDataFieldsExplain": "Odaberite naziv fotografije, natpisa i polja boja.",
      "settingsDataFieldsError": "Aplikacija ne može utvrditi prikladni naziv, natpis ili podatke o boji. Odaberite polja koja će se ovdje upotrijebiti. Ove se postavke mogu kasnije mijenjati.",
      "settingsFieldsLabelName": "Naziv",
      "settingsFieldsLabelDescription": "Natpis",
      "settingsFieldsLabelColor": "Boja",
      "settingsFieldsReset": "Ponovno postavi odabir polja",
      "settingsExtentExplain": "Postavite početni obuhvat Map Toura putem interaktivne karte u nastavku.",
      "settingsExtentExplainBottom": "Obuhvat koji utvrdite izmijenit će početni obuhvat web-karte. Imajte na umu da se ovaj obuhvat neće upotrijebiti ako ne sadrži početnu točku obilaska. U tom slučaju obilazak će se otvoriti s početnom točkom u središtu.",
      "settingsExtentDateLineError": "Obuhvat se ne može protezati preko meridijana 180Â° geografske dužine",
      "settingsExtentDateLineError2": "Pogreška pri izračunavanju obuhvata",
      "settingsExtentDrawBtn": "Nacrtajte novi obuhvat",
      "settingsExtentModifyBtn": "Uredite obuhvat",
      "settingsExtentApplyBtn": "Pretpregled Map Toura",
      "settingsExtentUseMainMap": "Upotrijebi obuhvat Map Toura",
      "settingsZoomExplain": "Postavite uvećanje za točke priče koje slijede nakon uvoda (nije obavezno).",
      "settingsLabelZoom": "Mjerilo/razina",
      "settingsZoomFirstValue": "Nema",
      "settingsFieldError": "Odaberi polje na svakom popisu",
      "dataTitle": "Stvori hostirani sloj Map Tour",
      "dataExplain": "Stvorit će se novi sloj geoobjekata za vaše slike i točke obilaska. Sloj obilaska neće biti podijeljen, osim ako ne podijelite Map Tour.",
      "dataExplainPortal": "Za ovaj je geoobjekt potreban Portal for ArcGIS 10.4. Ako ne možete stvoriti sloj geoobjekta, obratite se administratoru za ArcGIS.",
      "dataNameLbl": "Naziv sloja",
      "dataFolderListLbl": "Mapa",
      "dataFolderListFetching": "Dohvaćanja mapa...",
      "dataRootFolder": "Korijen",
      "dataNameError": "Unesite naziv za uslugu geoobjekata",
      "dataFolderError": "Odaberi valjanu mapu",
      "dataSrcContainsInvalidChar": "Naziv usluge geoobjekata ima jedan ili više nevažećih znakova (-, <, >, #, %, :, \", ?, &, +, / ili ).",
      "dataSrvAlreadyExistsError": "Usluga s tim nazivom već postoji unutar organizacije. Izaberite drugi naziv.",
      "dataBtnSave": "Stvori sloj",
      "dataFooterProgress": "Stvaranje u tijeku",
      "dataFooterSucceed": "Uspješno stvaranje. Učitavanje",
      "dataFooterError": "Neuspješno stvaranje. Pokušajte ponovno",
      "tabError": "Provjerite ima li pogrešaka u svim karticama",
      "introRecordBtn": "Uvod",
      "introRecordActivate": "Upotrijebite početnu točku kao uvod (ne pojavljuje se u rotirajućem prikazu)"
    },
    "addPopupJS": {
      "uploadingPicture": "Učitavanje slike",
      "uploadSuccess": "Uspješno učitavanje",
      "uploadError": "Pogreška pri učitavanju slike",
      "uploadError2": "Pogreška pri dodavanju geoobjekta (nevaljana HTML oznaka)",
      "notJpg": "Izaberite jpeg fotografiju za učitavanje",
      "errorNoPhoto": "Odaberite sliku za učitavanje",
      "errorNoThumbnail": "Odaberite sličicu za učitavanje",
      "errorInvalidPicUrl": "Unesite valjanu sliku (počinje s http(s)://, završava s jpg, png, gif ili bmp). Možete završiti URL s '#isImage' da biste zaobišli ovo pravilo.",
      "errorInvalidThumbUrl": "Unesite valjanu sličicu (počinje s http(s)://, završava s jpg, png, gif ili bmp).",
      "errorInvalidVideoUrl": "Unesite valjani URL videozapisa (počinje s http(s)://)",
      "errorNoName": "Unesite naziv za ovu točku obilaska",
      "errorNoDescription": "Unesite natpis za ovu točku obilaska",
      "errorNoLocation": "Postavite lokaciju za ovu točku obilaska"
    },
    "builderJS": {
      "noPendingChange": "Nema nespremljenih promjena",
      "unSavedChangeSingular": "1 nespremljena promjena",
      "unSavedChangePlural": "nespremljenih promjena",
      "shareStatus1": "Tour nije spremljen",
      "shareStatus2": "Tour je javno podijeljen",
      "shareStatus3": "Tour je podijeljen s organizacijom",
      "shareStatus4": "Tour nije podijeljen",
      "popoverDiscard": "Jeste li sigurni da želite odbaciti sve nespremljene promjene?",
      "yes": "Da",
      "no": "Ne",
      "popoverLoseSave": "Otvaranjem preglednika, izgubit ćete sve nespremljene promjene",
      "ok": "U redu",
      "popoverSaveWhenDone": "Nemojte zaboraviti spremiti kad završite",
      "closeWithPendingChange": "Jeste li sigurni da želite potvrditi radnju? Vaše će se promjene izgubiti.",
      "gotIt": "U redu",
      "savingApplication": "Spremanje priče",
      "saveSuccess": "Priča spremljena",
      "saveError": "Spremanje nije uspjelo, pokušajte ponovno",
      "saveError2": "Spremanje nije uspjelo zbog neispravne html oznake u nazivu ili opisu",
      "saveError3": "Naslov ne smije biti prazan",
      "dragColorPicker": "Pomiči me okolo<br />ili promijeni moju boju",
      "dataWarningExtent": "Imate podatke izvan obuhvata web-karte. Ti podaci neće se upotrijebiti kao točke obilaska, promijenite obuhvata karte ako ih želite upotrijebiti.",
      "dataWarningVisibi": "Vaš sloj Map Toura nije vidljiv na trenutačnom obuhvatu web-karte. Potvrdite je li sloj Map Toura vidljiv s velikom kartom od %MAPSIZE%.",
      "dataWarningEdit": "Uredi web-kartu",
      "dataWarningClose": "Zatvori",
      "signIn": "Prijavite se s računom za",
      "signInTwo": "za spremanje priče.",
      "switchBM": "Promijeni kartografsku podlogu"
    },
    "organizePopupJS": {
      "messageStart": "Izabrali ste brisanje",
      "messageSinglePoint": "jedna točka obilaska",
      "messageMultiPoint": "točke obilaska",
      "messagePermantRemove": "To će trajno ukloniti",
      "messageRecord": "zapis",
      "messageRecordPlural": "zapise",
      "messageConfirm": "iz vaše baze podataka. Želite li nastaviti?",
      "labelButtonShow": "Prikaži",
      "labelButtonHide": "Sakrij"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "To će trajno izbrisati sliku i sličicu",
      "popoverDeleteWarningThumb": "To će trajno izbrisati sličicu",
      "popoverUploadingPhoto": "Učitavanje slike i sličice",
      "popoverUploadingThumbnail": "Učitavanje sličice",
      "popoverUploadSuccessful": "Uspješno učitavanje",
      "popoverUploadError": "Neuspješno učitavanje, pokušajte ponovno",
      "changePicAndThumb": "Promijeni sliku",
      "changeThumb": "Promijeni sličicu",
      "selectPic": "Promijeni medij",
      "selectThumb": "Promijeni sličicu",
      "uploadPicAndThumb": "Primijeni"
    },
    "headerJS": {
      "editMe": "Uredi me!",
      "templateTitle": "Postavi naslov predloška",
      "templateSubtitle": "Postavi podnaslov predloška"
    },
    "crossFaderJS": {
      "setPicture": "Postavi naslov slike",
      "setCaption": "Postavi natpis slike"
    },
    "importPopup": {
      "title": "Uvezi",
      "prevBtn": "Natrag",
      "nextBtn": "Sljedeće"
    },
    "importPopupHome": {
      "header": "Gdje su vam spremljene slike?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "slike",
      "videos": "videozapisi",
      "disabled": "Administrator je onemogućio ovu značajku.",
      "disabledPortal": "Za ovu je značajku potrebno da portal ima poslužitelj domaćin. Obratite se administratoru za Portal for ArcGIS.",
      "header1": "Slike se moraju javno podijeliti.",
      "header2": "Uvoz će biti ograničen na prvi %NB1% %MEDIA%.",
      "emptyDataset": "Pogreška, nema slika",
      "footerImport": "Uvezi",
      "selectAlbum": "Odaberi javni album",
      "selectAlbum2": "Odaberi album",
      "pleaseChoose": "Izaberite",
      "userLookup": "Potraži",
      "userLookingup": "Traženje",
      "csv": "Referencirano u CSV-u",
      "advanced": "Napredne opcije",
      "advancedScratchLbl": "Pokreni novi Tour",
      "advancedScratchTip": "Stvorite prazni Tour koji ćete moći popuniti ručno s pomoću čarobnjaka.",
      "advancedCSVLbl": "Uvezi podatke o Touru iz CSV datoteke",
      "advancedCSVTip": "Uvezite sadržaj Toura iz CSV datoteke.",
      "advancedCommonTip": "Slike i videozapisi već moraju biti na mreži.",
      "select": "Odaberite",
      "locUse": "Upotrijebi geolokaciju slike",
      "locExplain": "Najbolje je ne upotrijebiti lokacije slika jer se mogu naslijediti iz albuma, što može dovesti do toga da su sve fotografije na istoj lokaciji.",
      "locExplain2": "Najbolje je ne upotrijebiti lokacije videozapisa jer se mogu naslijediti iz albuma, što može dovesti do toga da su svi videozapisi na istoj lokaciji."
    },
    "viewFlickr": {
      "title": "Uvoz s Flickra",
      "header": "Unesite korisničko ime za Flickr i odaberite skup fotografija ili oznake koje će se uvesti.",
      "userInputLbl": "Unesite korisničko ime",
      "signInMsg2": "Korisnik nije pronađen",
      "selectSet": "Odaberi skup fotografija",
      "selectTag": "ili odaberi oznaku",
      "footerImportTag": "Uvezi odabranu oznaku",
      "footerImportSet": "Uvezi odabrani skup"
    },
    "viewFacebook": {
      "title": "Uvezi s Facebooka",
      "header": "Provjerite autentičnost s korisničkim računom za Facebook ili upotrijebite javnu stranicu. Privatni albumi mogu se upotrijebiti za stvaranje javnog Map Toura za koji ne treba provjera autentičnosti korisnika Facebooka, što omogućuje da komentari i oznake sviđanja ostanu privatni.",
      "leftHeader": "Korisnik Facebooka",
      "rightHeader": "Stranica Facebooka",
      "pageExplain": "Stranica na Facebooku javni je brand/proizvod ili poznati subjekt kao <b>esrigis</b>. Možete vidjeti naziv stranice nakon '/' na URL-u stranice.",
      "pageInputLbl": "Unesite naziv stranice",
      "lookupMsgError": "Stranica nije pronađena"
    },
    "viewPicasa": {
      "title": "Uvoz na Picasu",
      "header": "Unesite svoju adresu e-pošte ili ID za Picasu.",
      "userInputLbl": "ID za e-poštu ili Picasu",
      "signInMsg2": "Račun nije pronađen",
      "signInMsg3": "Nema javnog albuma",
      "howToFind": "Kako pronaći ID za Picasu",
      "howToFind2": "Kopirajte znamenke između prvog i posljednjeg znaka „/” bilo koje stranice Picasa"
    },
    "viewCSV": {
      "title": "Uvoz CSV-a",
      "uploadBtn": "Odaberi ili ispusti CSV datoteku",
      "resultHeaderEmpty": "Ovaj je CSV prazan",
      "resultHeaderSuccess": "Učitano %NB_POINTS% točaka",
      "resultHasBeenLimited": "Uvoz je ograničen na prvih %VAL1% točaka od %VAL2% kako bi se poštivala granica od %VAL3% točaka po obilasku",
      "browserSupport": "Vaš preglednik nije podržan, da biste upotrebljavali CSV, morate <a href='http://browsehappy.com/' target='_blank'>nadograditi preglednik</a> ili upotrebljavati preglednik web-karte ArcGIS.com (vidi Pomoć).",
      "errorLatLng": "Polja geografske širine i dužine nisu pronađena. Moguće vrijednosti za geografsku širinu jesu: <i>%LAT%</i> i za geografsku dužinu: <i>%LONG%</i>.",
      "errorFieldsExplain": "Učitavanje nije uspjelo jer sljedeća potrebna polja nisu pronađena",
      "errorFieldsName": "Moguće vrijednosti za <b>naziv</b>: %VAL%",
      "errorFieldsDesc": "Moguće vrijednosti za <b>opis</b>: %VAL%",
      "errorFieldsUrl": "Moguće vrijednosti za <b>URL slike</b>: %VAL%",
      "errorFieldsThumb": "Moguće vrijednosti za <b>URL sličice</b>: %VAL%",
      "errorFields2Explain": "Učitavanje nije uspjelo jer CSV ne upotrebljava iste atribute kao i sloj za sljedeće atribute",
      "errorFields2Name": "Za <b>naziv</b> upotrijebite %VAL1% umjesto %VAL2%",
      "errorFields2Desc": "Za <b>opis </b> upotrijebite %VAL1% umjesto %VAL2%",
      "errorFields2Url": "Za <b>URL slike</b> upotrijebite %VAL1% umjesto %VAL2%",
      "errorFields2Thumb": "Za <b>URL sličice</b> upotrijebite %VAL1% umjesto %VAL2%",
      "resultFieldsAll": "Uvezeni su svi atributi",
      "resultFieldsNotAll": "Sljedeći atributi nisu uvezeni jer ne postoje u sloju karte",
      "resultFieldsNotAll2": "Uvezeni su sljedeći atributi",
      "footerNextBtnResult": "Uvezi u web-kartu",
      "footerProgress": "Uvoz u tijeku",
      "footerSucceed": "Uspješan uvoz. Učitavanje"
    },
    "viewYoutube": {
      "title": "Uvoz s YouTubea",
      "header": "Unesite korisničko ime za YouTube da biste pronašli javno podijeljene videozapise.",
      "pageInputLbl": "Unesite korisničko ime za YouTube",
      "lookupMsgError": "Korisnik nije pronađen",
      "howToFind": "Kako pronaći YouTube korisničko ime",
      "howToFind2": "Korisničko ime prikazano je ispod videozapisa",
      "found": "Pronađeno",
      "noData": "Nije pronađen nijedan javni videozapis"
    },
    "viewGeoTag": {
      "title": "Odaberite i pronađite svoje slike/videozapise",
      "header": "Kliknite ili dodirnite slike koje želite uvesti da biste ih pronašli.",
      "headerMore": "Zašto moje slike/videozapisi nisu geolocirani?",
      "headerExplain": "Ako vaše slike imaju valjanu geolokaciju, automatski će se locirati na karti i navesti u drugoj kartici.<br /><br />Prema zadanim postavkama Picasa i Flickr ne pohranjuju EXIF metapodatke geolokacije kada uvozite slike. Provjerite postavke privatnosti za Picasa/Flickr kako biste omogućili uvoz geolokacija slika i upotrebu od strane vanjske aplikacije. Možda ćete morati ponovno uvesti postojeće slike u Flickr/Picasa da bi se upotrijebila EXIF geolokacija.<br /><br />Na Facebooku morate doći na svaku sliku, kliknuti na Uredi i odabrati lokaciju.",
      "leftPanelTab1": "Za lociranje",
      "leftPanelTab2": "Locirano",
      "clickOrTap": "kliknite ili dodirnite kartu da biste locirali",
      "clearLoc": "Očisti lokacije",
      "clickDrop": "Nemoj uvesti",
      "footerImport": "Uvezi",
      "footerProgress": "Uvoz u tijeku",
      "footerSucceed": "Uspješan uvoz. Učitavanje...",
      "loading": "Učitavanje",
      "error": "Uvoz geolokacija slika nije uspio, ignoriraju se geolokacije."
    },
    "initPopup": {
      "title": "Dobro došli u sastavljač Map Tour",
      "prevBtn": "Natrag",
      "nextBtn": "Sljedeće"
    },
    "initPopupHome": {
      "header1": "Gdje su vaše slike ili videozapisi?",
      "header2": "Pomoćnik će vam pomoći izraditi Map Tour od medija koji su već pohranjeni na mreži ili će ih uvesti u vaš račun ArcGIS Online za organizacije.",
      "title1": "Već su na mreži",
      "title2": "Trebam učitati slike",
      "hostedFSTooltip": "Učitajte slike i pohranite ih sa slojem Map Tour (ne podržava videozapise)",
      "hostedFsNA": "Morate biti objavljivač ili u drugoj ulozi s privilegijama za objavljivanje hostiranih slojeva geoobjekata. Obratite se administratoru za ArcGIS.",
      "hostedFsNA2": "Dostupno samo s pretplatom na ArcGIS Online. <a href='%LINK%'>Prijavite se za besplatno probno razdoblje</a>",
      "footer1": "Kad ste gotovi, nemojte zaboraviti podijeliti svoj Map Tour sa svojom publikom putem stranice stavke aplikacije.",
      "footer3": "Preuzmi CSV predložak",
      "footer4": "Ako se ne preuzme, kliknite na „Spremi kao”",
      "footer4bis": "Desnim klikom miša kliknite na „Spremi kao” ako se ne pokrene preuzimanje",
      "footer5": "Saznaj više",
      "footerProgress": "Stvaranje u tijeku",
      "footerSucceed": "Uspješno stvaranje. Učitavanje..."
    },
    "helpPopup": {
      "title": "Pomoć",
      "close": "Zatvori",
      "tab1": {
        "title": "Uvod",
        "div1": "Predložak Map Tour osmišljen je za predstavljanje geografskih informacija kada postoji fotografski ili medijski element priče koju želite ispričati.",
        "div2": "Predloškom se daje privlačna web-aplikacija jednostavna za upotrebu koja vam omogućuje da predstavite mali niz mjesta na karti u brojčanom nizu koje korisnici mogu pregledavati. Predložak je osmišljen za upotrebu u svim web-preglednicima na bilo kojem uređaju, uključujući pametne telefone i tablete. <br /><br />",
        "div42": "Da biste vidjeli obilaske po karti koje stvaraju drugi korisnici, <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>posjetite galeriju</a> na <a href='http://storymaps.arcgis.com/' target='_blank'>web-mjestu Story Maps</a>. Možete nas i pratiti na Twitteru na <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Voljeli bismo da nam se javite! Neovisno o tome imate li pitanje, želite zatražiti novu značajku ili mislite da ste pronašli pogrešku, posjetite nas na <a href='http://links.esri.com/storymaps/forum' target='_blank'>Forumu za korisnike Story Mapsa</a>."
      },
      "tab2": {
        "title": "Podaci",
        "div1": "Glavni element koji treba razmotriti pri izradi Map Toura jest odabir gdje ćete pohraniti slike. Map Tour može upotrijebiti slike pohranjene na velikim servisima za dijeljenje fotografija, s bilo kojeg poslužitelja ili kao privitke usluge geoobjekata.",
        "div1a": "Pojedinosti o podržanim formatima slika i videozapisima potražite u posljednjem odjeljku ove kartice.",
        "div2": "Interaktivni sastavljač daje vam dvije opcije za rukovanje slikama u Map Touru:",
        "div3": "<ul><li>Možete upotrijebiti <b>fotografije koje su već na mreži</b>, kao što su slike pohranjene na web-mjestu za dijeljenje fotografija poput servisa Flickr, ili slike pohranjene na vašem web-mjestu. Te će se slike referencirati u vašem  Map Touru putem njihovih URL-ova.</li><li>Možete i <b>učitati fotografije sa svojeg računala</b> izravno u  Map Tour. Za ovu opciju slanja morate imati račun za organizacije za ArcGIS i privilegija izdavača ili administratora jer se automatski stvara hostirana usluga geoobjekata za vas u kojoj se pohranjuju vaše fotografije kao privitci.</li></ul>",
        "div4": "Glavni slučajevi kad se upotrebljava:",
        "div4b": "<b>Vaše fotografije još nisu hostirane</b> i imate račun ArcGIS za organizacije: upotreba hostirane usluge geoobjekata najbolji vam je izbor. Kao javni servis za dijeljenje fotografija optimizirat ćemo vam slike kako bismo stvorili slike koje se brzo učitavaju i imat ćete pristup svim mogućnostima za administraciju i upravljanje podacima platforme ArcGIS.",
        "div5": "<b>Niste član organizacije</b>: prvo morate učitati slike na web-mjesto za dijeljenje fotografija ili na vlastiti web-poslužitelj. Sastavljač će vam pomoći upotrijebiti ove slike koje će se nastaviti hostirati na izvornoj lokaciji.",
        "div6": "<b>Želite ponovno upotrijebiti postojeću uslugu geoobjekata</b> koja pohranjuje vaše slike i privitke ili koja referencira vanjske slike: potražite odjeljak s pojedinostima u nastavku.",
        "div7": "<b>Korisnik ste prethodne verzije</b> predloška Map Toura i već imate CSV koji referencira vaše slike i sličice: moći ćete ga uvesti i pročistiti svoje podatke. Sastavljač podupire samo CSV-ove koji upotrebljavaju polja geografske širine/dužine. CSV-ovi koji se temelje na adresama mogu se nastaviti upotrebljavati putem web-karte (vidi odjeljak u nastavku).",
        "div8": "Uvoz sa servisa za dijeljenje fotografija",
        "div9a": "Prekinuta je podrška za Facebook, ${learn}.",
        "learn": "saznaj više",
        "div9": "Operacija uvoza referencira slike koje su već hostirane tako da pohranjuje njihove URL-ove u kolekciji geoobjekata web-karte. Slike nisu pohranjene na programu ArcGIS Online. Ako se hostiranim slikama ne može pristupiti, neće biti dostupne u Map Touru i vidjet ćete obavijest 'Slika nije dostupna'. Ovisno o pružatelju usluga za fotografije, Map Tour možda neće uvesti naziv, opis i lokaciju slika. Ovi su atributi pohranjeni u web-karti i sva uređivanja usluga na mreži neće se odraziti u Map Touru.",
        "div10": "Pohranjivanje slika na web-poslužitelju",
        "div11": "Ako odaberete sami hostirati slike, morat ćete ručno stvoriti sličice svojih slika. Korištenjem slika s punom razlučivošću za sličice, rezultirati će lošijim performansama. Iz tog razloga preporučujemo da upotrebljavate servise za dijeljenje fotografija na mreži ili uslugu geoobjekata koja će to raditi za vas.",
        "div12": "Upotreba postojeće usluge geoobjekata ili Shapefile",
        "div13": "Bilo koja usluga geoobjekata ili shapefile može se upotrijebiti kao izvor podataka za Map Tour. Samo je morate dodati kao sloj u web-kartu putem preglednika karte na arcgis.com. Ako aplikacija pronađe očekivane atribute u vašem sloju, sve će funkcionalnosti sastavljača biti dostupne.",
        "div14": "Moguće su vrijednosti za naziv polja (velika i mala slova):",
        "div151": "Naziv",
        "div152": "Opis",
        "div153": "Slika",
        "div154": "Sličica",
        "div155": "Boja ",
        "div16": "Ako aplikacija ne pronađe podudarajuća polja prilikom upotrebe usluge geoobjekata, preglednik neće raditi dok ne konfigurirate polja koja će se upotrijebiti putem sastavljača. Slojevi CSV-a i shapefilea dodani na web-kartu moraju imati sva potrebna polja ili sastavljač neće raditi.",
        "div162": "Prilikom upotrebe usluge geoobjekata koja pohranjuje slike kao privitke, <b>upotrijebit će se samo geoobjekti s dva privitka</b>. Prvim se privitkom definira glavna slika, a drugim se privitkom definira sličica.",
        "div17": "Polja slike i sličice su obvezna za usluge geoobjekata bez privitaka, a nisu obvezna (no preporučuju se) za usluge geoobjekata s privicima. Ako vaša usluga ima omogućene privitke, sastavljač će vam dopustiti da učitate slike kao privitke. Ako nema, moći ćete samo urediti URL-ove slike i sličice.",
        "div172": "Kada postoje, polja slike i sličice uvijek će se upotrijebiti i neće biti upita za privicima usluge geoobjekata.",
        "div173": "Primjeri CSV-a i shapefileova mogu se preuzeti s",
        "div18": "Stvaranje hostirane usluge geoobjekata od CSV-a ili shapefile",
        "div19": "Kada stvorite hostiranu uslugu geoobjekata od CSV-a ili shapefilea, privici nisu omogućeni po zadanim postavkama. Da bi ste ih omogućili, otvorite stranicu o pojedinostima značajke usluge geoobjekata, kliknite na malu strelicu na odjeljku sloja i vidjet ćete tu opciju. Map Tour nastavit će upotrebljavati slike i sličice koje ste referencirali atributima. Po želji, ako želite učitati svoje slike kao privitke usluge geoobjekata, moći ćete to napraviti putem dva gumba na ploči slike („Promijeni sliku” i „Promijeni sličicu”).",
        "div20": "Podržani formati slika i videozapisi",
        "div21": "Podržani formati slika jesu: <b>.jpg, .jpeg, .png, .gif i .bmp</b>. Ako vaš medij ne završava s takvim nastavkom, Map Tour smatrat će ga videozapisom, osim prilikom upotrebe usluge geoobjekata (vidi u nastavku).",
        "div22": "Predložak Map Tour ne uključuje reproduktor videozapisa pa morate upotrijebiti vanjski reproduktor videozapisa koji pruža vaš omiljeni servis za hostiranje videozapisa (pronađite opciju za ugrađivanje videozapisa i kopirajte URL u danom kodu). Ako sami želite hostirati videozapis, možete stvoriti HTML stranicu koja sadrži reproduktor videozapisa poput <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Interaktivni sastavljač ne pruža dijalog za uključivanje videozapisa prilikom upotrebe usluge geoobjekata s privicima, no moguće je to napraviti uređivanjem podataka izvan interaktivnog sastavljača. U pregledniku karte na arcgis.com ako izmijenite polja slike da ukazuju na vanjski videozapis i dodate posebne parametre na kraju svojeg URL-a (#isVideo), vaš će se medij smatrati videozapisom.",
        "div24": "Imajte na umu da još uvijek morate imati dva valjana privitka sa slikama ili se točka neće upotrijebiti. Nije moguće upotrijebiti videozapise prilikom upotrebe privitaka usluge geoobjekata bez polja slike i sličice."
      },
      "tab3": {
        "title": "Prilagođavanje",
        "div1": "Sastavljač pruža nekoliko opcija za prilagođavanje koje su dostupne kroz gumb POSTAVKE na gornjoj ploči. Ako ne pronađete opciju koju očekujete pružamo i verziju koja se može preuzeti i koju možete implementirati na svojem web-poslužitelju i poboljšati da odgovara vašim potrebama.",
        "div2": "Preporučujemo da upotrebljavate hostiranu verziju osim sljedećeg:",
        "div3": "<li>Ne pruža prilagođavanje korisničkog sučelja koji želite imati, kao upotreba pozadinske slike zaglavlja.</li><li>Vi ste programer i želite poboljšati aplikaciju.</li>",
        "div4": "Verziju koju je moguće preuzeti može se konfigurirati putem identifikatora aplikacije web-kartiranja ili web-karte. Glavni slučajevi uporabe:",
        "div41": "Izradite obilazak po karti s pomoću interaktivnog sastavljača u hostiranoj okolini i konfigurirajte predložak s identifikatorom aplikacije web-kartiranja. Primijenit će se postavke koje ste definirali s interaktivnim sastavljačem.",
        "div42": "Izradite web-kartu izvan interaktivnog sastavljača i konfigurirajte predložak identifikatorom web-karte. Morat ćete pročitati dokumentaciju da biste naučili kako konfigurirati predložak.",
        "div43": "Imajte na umu da je interaktivni sastavljač dostupan u verziji za preuzimanje, no s nekim tehničkim ograničenjima na preglednicima kao što su verzije preglednika Internet Explorer ranije od verzije 10.",
        "div5": "Da biste preuzeli najnoviju verziju predloška i saznali više o tome kako ga upotrebljavati, posjetite <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>stranicu projekta GitHub</a>."
      },
      "tab4": {
        "title": "Savjeti",
        "div0": "Podržani preglednici",
        "div0a": "Preglednik Map Toura podržava IE8+. Interaktivni sastavljač podržava IE9+. Aktivno smo ga ispitali u svim glavnim preglednicima, ali ako doživite poteškoće, preporučujemo koristiti Chrome.",
        "div0b": "Ako imate poteškoća, obavijestite nas. U međuvremenu, ako izradite Map Tour s pomoću predloška CSV, umanjit ćete interakciju sa sučeljem sastavljača.",
        "div1": "Slike",
        "div2": "Preporučujemo vodoravnu orijentaciju fotografija, a ne okomito. Najbolje će odgovarati fotografije omjera 4:3. Slike okomitog usmjerenja mogu se upotrebljavati, ali bi na manjim zaslonima kao što je iPad većinu slike mogao prekriti natpis (tekst zauzima više prostora kada se prikaže na visokom području u usporedbi sa širokim područjem). Iako se u jednom Map Touru mogu upotrebljavati slike različitih veličina, oblika i usmjerenja, preporučujemo upotrebu jedinstvene veličine i oblika za sve slike. Na taj način korisnika neće omesti slike različitih veličina tijekom obilaska.",
        "div2a": "Preporučujemo maksimalnu veličinu slike od 1000 px širine x 750 px visine za glavnu sliku i 140 x 93 px za sličice.",
        "div3": "Formatiranje teksta natpisa s pomoću HTML oznaka",
        "div4": "Zaglavlje i naslov/natpis slike mogu uključivati HTML oznake za definiranje formatiranja i poveznica. Na primjer, ovim se kodom dodaje žuta poveznica:",
        "div4a": "Napišite dobar podnapis za svoj obilazak",
        "div4b": "Uložite vrijeme kako biste napisali zanimljive podnapise za obilazak. Podnapisi su dobar način za privlačenje ljudi i za obavještavanje o tome što mogu saznati u obilasku. Osim toga, podnapisima možete informirati svoju publiku o državi/županiji u kojoj se nalazi obilazak. Nemojte pretpostaviti da ljudi znaju primjerice gdje se nalazi grad u kojem se odvija vaš obilazak. Vaš podnapis također se može formatirati s pomoću HTML oznaka, npr. tako da uključuje poveznice. Pripazite ipak da podnapis ne bude predug. Možda neće potpuno stati na prozore manjih preglednika ili na iPad pa će biti izrezani. Ako ne možete smisliti dobar podnapis, ostavite polje prazno.",
        "div5": "Dodatni slojevi",
        "div6": "Možete umetnuti dodatne slojeve da prikažu kontekst Map Toura. Ti slojevi mogu sadržavati ostale geoobjekte koje želite prikazati na karti uz točke obilaska, kao što su studijska područja, ruta za šetanje ili vožnju koja povezuje vaše točke obilaska itd. Predložak za Map Tour prikazat će dodatne slojeve s pomoću simbologije koju odredite na web-karti, ali skočni prozori nisu dostupni.",
        "div7": "Neka obilazak bude kratak i sladak",
        "div8": "Postoji ograničenje od 99 točaka po obilasku. Naravno, većina Map Tourova bit će mnogo kraća. Ne očekujte od publike da želi proći kroz previše točaka obilaska. Vama je možda vaša tema iznimno zanimljiva, ali nemojte pretpostaviti da će i njima biti!",
        "div10": "Ugradbeni način",
        "div11": "Ako želite ugraditi svoj predložak u neko drugo web-mjesto s pomoću iFramea, umetanjem dodatnog parametra „&embed” na kraju URL-a, izgubit će se zaglavlje. Taj se način također može postaviti u verziji za preuzimanje kroz konfiguracijsku datoteku.",
        "div12": "Izbjegavajte upotrebu uskog iFramea zbog kojeg će se obilazak po karti prebaciti na izgled za mali zaslon osjetljiv na dodir. Tako će se olakšati upotreba. Kad je obilazak po karti ugrađen, uvijek preporučujemo da svejedno umetnete još i poveznicu pored ugrađenog obilaska te ga tako korisnici mogu pokrenuti na punom zaslonu."
      },
      "tab5": {
        "title": "Objavljivanje",
        "div1": "Kad ste gotovi, ne zaboravite podijeliti svoj Map Tour sa svojom publikom preko gumba PODIJELI ili putem stranice stavke aplikacije na ArcGIS Online.",
        "div2a": "Dijeljenje Toura putem sastavljača",
        "div2b": "Gumb PODIJELI ažurirat će stavke aplikacije i web-karte. Ako su podaci Toura pohranjeni u stavci usluge geoobjekata, također će se ažurirati. Ako ste dodali druge slojeve putem preglednika karata ArcGIS.com, neće se ažurirati. Zbog toga se možda vaš Tour neće podijeliti kako ste očekivali. Stavke koje već imaju potrebne privilegije (ili ih premašuju) neće se ažurirati.",
        "div2c": "Dijeljenje Toura kroz ArcGIS Online",
        "div2d": "Kada dijelite svoju aplikaciju preko programa ArcGIS Online, on će zatražiti od vas, ako je neophodno, da ažurirate sve povezane resurse (web-kartu, uslugu geoobjekata, ukrasni sloj) koji nisu podijeljeni na isti način. Ako je Map Tour javan i neki od vaših resursa nije podijeljen s publikom, korisnici će biti preusmjereni na stranicu za prijavu u ArcGIS Online.",
        "div3t": "Sigurnost za uslugu geoobjekata",
        "div3a": "Ako upotrebljavate hostiranu uslugu geoobjekata izrađenu s pomoću sastavljača za Map Tour, aplikacija će upravljati sigurnošću usluge umjesto vas, a vi ćete biti jedina osoba s uređivačkim privilegijama, čak i ako javno objavite uslugu.",
        "div3t2": "Prije nego što podijelite svoj Tour s publikom",
        "div3": "Provjerite radi li Tour ispravno kada niste prijavljeni svojim računom za ArcGIS.com. URL koji ćete upotrijebiti ne bi trebao preusmjeriti prema stranici za prijavu ili prema načinu sastavljača.",
        "div4": "Dobra je ideja vidjeti kako izgleda vaš obilazak po karti na iPadu u vodoravnom usmjerenju kako biste bili sigurni da izgleda dobro na ovom popularnom uređaju. Ovime možete vidjeti pokrivaju li vaši natpisi preveliki dio slika. Možete i vidjeti odgovaraju li podnaslovi i jesu li toliko veliki da se dio ne vidi.",
        "div5a": "Preporuka za pretraživanje",
        "div5b": "Da biste pomogli ljudima pronaći vaš Map Tour, ako pretražuju u ArcGIS Online, preporučujemo da dodate oznaku 'karta s pričom' u stranicu stavke aplikacije obilaska po karti (ne u stranicu stavke web-karte) uz oznake kao što je naziv županije u kojoj se nalazi obilazak, naziv države i tematske oznake kao što su 'javna umjetnost', 'turistički vodič' ili 'povijesna mjesta'. Te oznake pomažu i nama u tvrtki Esri da pronađemo zgodne nove primjere obilazaka koje možemo pokazati u našim galerijama i promovirati u društvenim medijima. Preporučujemo da učitate lijepu sličicu na stranicu stavke aplikacije, poput male snimke zaslona ili jedne od slika iz nje. Ova slika će se koristiti automatski ako je vaš obilazak po karti dodan u galeriju programa ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Tour spremljen",
      "manageStory": "Upravljajte svojom pričom",
      "manageStoryA1": "Savjet: možete upotrijebiti %LINK1% kako biste provjerili ima li vaša priča pogreške i kako biste promijenili način na koji se dijele komponente priče. Značajka moje priče pomaže vam i u tome da vaša priča izgleda dobro kad se podijeli na društvenim mrežama. Možete saznati o drugim korisnim značajkama mojih priča ovdje %LINK2%.",
      "manageStoryA1V1": "Moje priče",
      "manageStoryA1V2": "objave na blogu",
      "shareTitle": "Podijelite svoj Tour",
      "sharePrivateHeader": "Vaš Tour nije podijeljen, želite li ga podijeliti?",
      "sharePrivateBtn1": "Podijeli javno",
      "sharePrivateBtn2": "Podijeli s mojom organizacijom",
      "sharePrivateProgress": "Dijeljenje u tijeku...",
      "sharePrivateErr": "Dijeljenje nije uspjelo, pokušajte ponovno ili",
      "sharePrivateOk": "Dijeljenje je ažurirano, učitavanje...",
      "sharePreviewAsUser": "Pretpregled",
      "shareHeader1": "Vaš je Tour <strong>javno dostupan</strong>.",
      "shareHeader2": "Vaš Tour dostupan je članovima vaše organizacije (potrebna je prijava)",
      "shareLinkHeader": "Podijelite svoj Tour",
      "shareLinkOpen": "OTVORI",
      "shareA1": "Upotrijebite %SHAREIMG% na <a href='%LINK1%' target='_blank'>stranici stavke aplikacije</a>. Ako želite prekinuti dijeljenje web-karte, upotrijebite <a href='%LINK2%' target='_blank'>stranicu stavke web-karte</a>.",
      "shareWarning": "Onemogućeno je dijeljenje %WITH% jer niste vlasnik <a href='%LINK%' target='_blank'>web-karte</a>.",
      "shareWarningWith1": "javno",
      "shareWarningWith2": "javno i s organizacijom"
    },
    "locator": {
      "error": "Lokacija nije dostupna"
    },
    "saveErrorSocial": {
      "title": "Ažuriranje dijeljenja na društvenim mrežama",
      "panel1": "Poboljšana je prisutnost vaše priče na društvenim medijima, ali naziv stavke u ArcGIS web-aplikaciji nije jednak nazivu vaše priče.",
      "panel1tooltip": "Kada odredite naziv, sažetak i sličicu, vaša će priča izgledati ovako:",
      "panel2": "Koji biste naziv upotrijebili na društvenim medijima:",
      "panel2q1": "Naziv priče (preporučeno)",
      "panel2q1tooltip": "Ako odaberete ovu mogućnost, naziv vaše stavke izmijenit će se kako bi se podudarao s naslovom vaše priče, a dodatne promjene u sastavljaču će se sinkronizirati.",
      "panel2q2": "Naslov stavke",
      "panel3": "Da biste dodatno poboljšali izgled svoje priče na društvenim medijima, upotrijebite ${MYSTORIES} za dodavanje sažetka i sličice.",
      "panel4": "Ne upozoravaj me ponovno za ovu priču",
      "mystories": "Moje priče",
      "btnSave": "Spremi"
    }
  }
});