define({
  "viewer": {
    "loading": {
      "step1": "CARICAMENTO STORIA",
      "step2": "CARICAMENTO DATI",
      "step3": "INIZIALIZZAZIONE DEL TOUR",
      "loadBuilder": "PASSAGGIO A MODALITÀ GENERATORE",
      "redirectSignIn": "REINDIRIZZAMENTO ALLA PAGINA DI ACCESSO",
      "redirectSignIn2": "(pagina alla quale si verrà reindirizzati dopo l'accesso)",
      "fail": "Caricamento Tour mappa non riuscito",
      "failButton": "Riprova"
    },
    "errors": {
      "boxTitle": "Si è verificato un errore",
      "portalSelf": "Errore irreversibile: impossibile ottenere la configurazione del portale",
      "invalidConfig": "Errore irreversibile: configurazione non valida",
      "invalidConfigOwner": "Errore irreversibile: configurazione non valida (richiesto proprietario autorizzato)",
      "invalidConfigNoWebmap": "Errore irreversibile: configurazione non valida (mappa Web o identificatore dell'applicazione non specificati in index.html)",
      "invalidConfigNoAppDev": "Nessun identificatore applicazione mappatura Web o mappa Web specificati nei parametri URL (?appid= o ?webmap=). Nella modalità di sviluppo, la configurazione dell'ID dell'app e della mappa Web in index.html viene ignorata.",
      "createMap": "Impossibile creare la mappa",
      "invalidApp": "Errore irreversibile: impossibile caricare la storia",
      "noLayer": "La mappa Web non contiene un layer dati valido per Tour mappa.",
      "noLayerMobile": "Il generatore di Tour mappa non è supportato per queste dimensioni schermo. Se possibile, ridimensionare il browser per accedere al generatore o creare la storia su un dispositivo con uno schermo più grande.",
      "noLayerMobile2": "Ruotare il dispositivo nell'orientamento orizzontale per utilizzare il generatore Tour mappa.",
      "noLayerView": "Benvenuti all'applicazione Web Tour mappa.<br />La storia non è ancora configurata.",
      "appSave": "Errore durante il salvataggio della storia",
      "mapSave": "Errore durante il salvataggio della mappa Web",
      "featureServiceLoad": "Errore di caricamento del feature service",
      "notAuthorized": "Non si è autorizzati ad accedere alla storia.",
      "notAuthorizedBuilder": "L'utente non è autorizzato a utilizzare il generatore Tour mappa.",
      "oldBrowserTitle": "Browser non completamente supportato",
      "noBuilderIE8": "Il generatore di Tour mappa non è supportato nelle versioni di Internet Explorer precedenti alla versione 9.",
      "ie10Win7Explain": "Il generatore di Tour mappa interattivo non è supportato in Internet Explorer 10 in Windows 7 se l'origine dati è un feature service con allegati. Per utilizzare un feature service con allegati, è necessario <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'> forzare manualmente la modalità documento sugli standard di Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>eseguire il downgrade a Internet Explorer 9</a> o l'aggiornamento a Windows 8.",
      "oldBrowserExplain": "Il browser non supporta la generazione automatica di anteprime dalle immagini caricate nel tour mappa. Per creare un tour mappa utilizzando questo browser, sarà necessario fornire un'immagine di anteprima distinta per ogni immagine caricata.",
      "oldBrowserExplain2": "Per ottimizzare l'esperienza utente, <a href='http://browsehappy.com/' target='_blank'>aggiornare il browser</a> o <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>attivare il Google Chrome Frame per Internet Explorer</a>.",
      "oldBrowserExplain3": "Il generatore di Tour mappa non funziona con Internet Explorer 10 su Windows XP.",
      "oldBrowserClose": "Chiudi",
      "noViewerIE2": "Si sta tentando di visualizzare la storia utilizzando un browser meno recente e non più supportato. Alcune funzioni potrebbero non funzionare o potrebbero verificarsi errori inattesi. Si consiglia di effettuare l'aggiornamento a Internet Explorer 11 o di utilizzare un altro browser, come Chrome.",
      "noViewerIE3": "Verso la fine del 2017, questa storia non sarà più caricata su questo browser e sarà quindi necessario utilizzare un browser supportato per visualizzarla.",
      "attention": "Attenzione."
    },
    "mobileHTML": {
      "showIntro": "MOSTRA TITOLO",
      "hideIntro": "NASCONDI TITOLO",
      "navList": "Elenco",
      "navMap": "Mappa",
      "navInfo": "Supporto",
      "introStartBtn": "Avvia"
    },
    "desktopHTML": {
      "storymapsText": "Una story map",
      "builderButton": "Passa a modalità generatore",
      "facebookTooltip": "Condividi su Facebook",
      "twitterTooltip": "Condividi su Twitter",
      "bitlyTooltip": "Crea un link breve",
      "bitlyStartIndex": "Collegamento alla posizione corrente",
      "tooltipAutoplayDisabled": "Questo non è disponibile nella modalità di riproduzione automatica",
      "autoplayLabel": "Modalità di riproduzione automatica",
      "autoplayExplain1": "La modalità di riproduzione automatica consente di avanzare nella storia a intervalli regolari. Questa soluzione è ideale in un chiosco o monitor pubblico, ma occorre tenere presente che in altre situazioni potrebbe creare problemi di lettura della storia. Questa funzione non è supportata su display di piccole dimensioni.",
      "autoplayExplain2": "Quando questa modalità è attiva, sono disponibili controlli per riprodurre/sospendere la storia e regolare la velocità di navigazione.",
      "takeTourText": "Inizia il tour",
      "backToStart": "Torna all’inizio"
    },
    "builderHTML": {
      "panelHeader": "CONFIGURAZIONE STORIA",
      "buttonSave": "SALVA",
      "buttonSettings": "Impostazioni",
      "buttonShare": "Condividi",
      "buttonView": "Modalità visualizzazione",
      "buttonItem": "Aprire l'elemento dell'applicazione Web",
      "buttonHelp": "Guida",
      "buttonOrganize": "Organizza",
      "buttonOrganizeAndCover": "Organizzare punti del tour e aggiungere una pagina di copertina",
      "buttonAdd": "Aggiungi",
      "buttonImport": "Importa",
      "buttonImportDisabled": "L'importazione non è disponibile quando si utilizza il caricamento dell'immagine. Fare clic su Aggiungi per caricare un'immagine.",
      "dataEditionDisabled": "La modifica dei dati è disabilita in questa origine dati CSV",
      "dataSourceWarning": "Il layer dati del Tour mappa è stato modificato. Se gli ID delle feature non corrispondono, sarà necessario ripristinare l'ordine e i punti nascosti tramite l'opzione <b>Organizza</b>. Se i nomi dei campi non sono gli stessi, sarà necessario ripristinare le impostazioni relative ai campi nella <b>scheda Dati in Impostazioni</b>.",
      "organizeWarning": "Uno o più punti aggiunti all'esterno del generatore interattivo sono nascosti.",
      "dataPicError0a": "Questo tour include <b>%NB%</b> URL immagine non conformi.",
      "dataPicError0b": "Questo tour può includere <b>%NB%</b> URL immagine non conformi.",
      "dataPicError1": "Con Tour mappa è ora necessario che un URL immagine termini con una delle seguenti estensioni: .jp(e)g, .png, .gif o .bmp.",
      "dataPicError2": "Questo requisito non influirà sull'istanza esistente di Tour mappa pubblicata. Tuttavia, per poter utilizzare il generatore interattivo, è prima necessario risolvere il problema relativo all'URL eseguendo una delle seguenti due azioni:",
      "dataPicError3": "Modificare gli URL",
      "dataPicError4": "Ciò aggiungerà <i>#isImage</i> alla fine degli URL immagine non supportati. La maggior parte dei server supporta le appendici URL. Tuttavia, una volta eseguita questa azione, è necessario verificare che gli URL immagine aggiornati funzionino navigando tra i punti. Se si carica ogni immagine, è possibile salvare il Tour mappa. Se le <b>immagini sono danneggiate, non salvare il Tour mappa</b>. Piuttosto, ricaricare il generatore ed eseguire la seconda azione.",
      "dataPicError5": "Limitare il tour alle immagini",
      "dataPicError6": "Con questa opzione tutti gli URL verranno considerati immagini, ma non sarà possibile aggiungere video utilizzando il generatore interattivo. Questa azione è reversibile qualora si decidesse di aggiungere video in futuro.",
      "dataPicError7": "Il Tour mappa è stato limitato alle immagini, i video non possono essere utilizzati. Se si sceglie di rimuovere questa limitazione, controllare che le immagini vengano caricate correttamente prima di salvare il Tour mappa. Sarà possibile quella limitazione in seguito, se necessario.",
      "dataPicError8": "Rimuovi la limitazione per le immagini",
      "dataPicError9": "Se gli URL puntano a video, è possibile ignorare questo avviso; se puntano a immagini, è necessario eseguire una delle seguenti due azioni:",
      "modalCancel": "Annulla",
      "modalApply": "Applica",
      "organizeHeader": "Organizza il tour",
      "organizeGeneralCaption": "Utilizza il trascinamento per ordinare i punti del tour",
      "organizeDelete": "Elimina",
      "organizeHide": "Nascondi",
      "organizeReset": "Ripristina ordine e punti nascosti",
      "addMaxPointReached": "È stato raggiunto il numero massimo di punti del tour autorizzati dalle icone impostate e non è possibile aggiungerne altri.<br /><br />Si noti che eliminando punti esistenti sarà necessario ricaricare la storia.",
      "addMaxPointReachedMobile": "È stato raggiunto il numero massimo di punti autorizzati. Impossibile aggiungere l'immagine.",
      "addClose": "Chiudi",
      "addHeader": "Aggiungi un nuovo punto del tour",
      "addTabPicture": "Supporto",
      "addTabInformation": "Informazioni",
      "addTabLocation": "Posizione",
      "addSelectCaption": "Selezionare o rilasciare l'immagine",
      "addNoteVideo": "Consultare la Guida per istruzioni sull'uso dei video",
      "addSelectCaptionNoFileReader": "Seleziona immagine",
      "addChangePhoto": "Modifica immagine e anteprima",
      "addPictureResolutionIntro": "La risoluzione dell'immagine è maggiore di quella richiesta:",
      "addPictureResolutionOldBrowser": "La risoluzione dell'immagine è maggiore di quella richiesta. Per ottimizzare l'esperienza di Tour mappa, specificare una risoluzione inferiore a %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Cambia la risoluzione immagine in %RESOLUTION%",
      "addPictureResolutionKeep": "Mantieni la risoluzione originale di %RESOLUTION%",
      "addSelectThumbnail": "Seleziona anteprima",
      "addNoThumbSelected": "Nessuna anteprima selezionata",
      "addThumbSelected": "Selezionata",
      "addCameraSettingsHeader": "IMPOSTAZIONI VIDEOCAMERA",
      "addThumbnailHeader": "ANTEPRIMA",
      "addLabelPicUrl": "Immagine",
      "addLabelThumbUrl": "Anteprima",
      "addTextPlaceholderUrl": "Inserire un URL dell'immagine",
      "addTextPlaceholderUrl2": "Immettere l'URL di una pagina YouTube",
      "addTextPlaceholderUrl3": "Inserire un URL della pagina Vimeo",
      "addTextPlaceholderUrl4": "Inserire un URL dell'incorporamento del video",
      "addLabelVideo": "Video",
      "addMediaVideoOther": "Altro",
      "addMediaVideoHelp": "Verificare l'URL e ottenere l'anteprima predefinita",
      "addMediaVideoHelpTooltip1": "Controllo completato",
      "addMediaVideoHelpTooltip2": "Controllo non riuscito",
      "addMediaVideoHelpTooltip4": "Effettuare la ricerca dell'opzione per l'incorporamento del video e copiare l'URL del video contenuto nel codice",
      "addLabelName": "Nome",
      "addLabelDescription": "Didascalia",
      "addTextPlaceholder": "Digitare del testo",
      "addLocatePlaceholder": "Trova un indirizzo o un luogo",
      "addPinColor": "Colore",
      "addLatitude": "Latitudine",
      "addLongitude": "Longitudine",
      "addLatitudePlaceholder": "es. 34.056",
      "addLongitudePlaceholder": "es. -117.195",
      "addUploading": "Caricamento del punto del tour",
      "addSave": "Aggiungi punto tour",
      "addMobileUploading": "Caricamento immagine in corso",
      "addMobileName": "Immettere un nome",
      "addMobileNameMandatory": "Errore. Immettere un nome.",
      "addMobileError": "Si è verificato un errore",
      "settingsHeader": "Impostazioni",
      "settingsTabLayout": "Layout",
      "settingsTabColor": "Colori",
      "settingsTabLogo": "Intestazione",
      "settingsTabFields": "Dati",
      "settingsTabExtent": "Estensione",
      "settingsTabZoom": "Livello zoom",
      "settingsLayoutExplain": "Selezionare il layout desiderato.",
      "settingsLayoutProfessional": "A tre riquadri",
      "settingsLayoutModern": "Integrato",
      "settingsLayoutSidePanel": "Pannello laterale",
      "settingsLayoutSelected": "Layout selezionato",
      "settingsLayoutNew": "Novità!",
      "settingsLayoutSelect": "Seleziona",
      "settingsLayoutNote": "Tenere presente che sui punti che utilizzano i video la didascalia verrà posizionata sempre al di sotto del video, anche se l'opzione non è selezionata.",
      "settingsLayoutLocBtn": "Visualizza un pulsante Trova posizione",
      "settingsLayoutLocBtnHelp": "Supportato su molti browser. Appare solo se si accede alla mappa della storia da HTTPS. Non appare se la storia è incorporata.",
      "settingsColorExplain": "Per modificare l'aspetto, scegliere un tema predefinito o crearne uno personale.",
      "settingsLabelColor": "Colori di intestazione, contenuto e piè di pagina",
      "settingsLogoExplain": "Personalizza il logo dell'intestazione (max 250 x 50 px).",
      "settingsLogoEsri": "Logo Esri",
      "settingsLogoNone": "Nessun logo",
      "settingsLogoCustom": "Logo personalizzato",
      "settingsLogoCustomPlaceholder": "URL immagine",
      "settingsLogoCustomTargetPlaceholder": "Collegamento clickthrough",
      "settingsLogoSocialExplain": "Personalizzare il collegamento in alto a destra nell'intestazione.",
      "settingsLogoSocialText": "Testo",
      "settingsLogoSocialLink": "Collegamento",
      "settingsLogoSocialDisabled": "Questa feature è stata disabilitata dall'amministratore",
      "settingsDataFieldsExplain": "Selezionare i campi per nome foto, didascalia e colore.",
      "settingsDataFieldsError": "L'applicazione non è in grado di determinare i dati appropriati relativi a nome, didascalia o colore. Selezionare qui i campi da utilizzare. Queste impostazioni possono essere modificate in un secondo momento.",
      "settingsFieldsLabelName": "Nome",
      "settingsFieldsLabelDescription": "Didascalia",
      "settingsFieldsLabelColor": "Colore",
      "settingsFieldsReset": "Ripristinare la selezione dei campi",
      "settingsExtentExplain": "Impostare l'estensione iniziale di Tour mappa utilizzando la mappa interattiva seguente.",
      "settingsExtentExplainBottom": "L'estensione definita modificherà l'estensione iniziale della mappa. Questa estensione non viene utilizzata se non si include il primo punto del tour. In tal caso, il tour si apre al centro sul primo punto.",
      "settingsExtentDateLineError": "L'estensione non può attraversare il meridiano per 180° di longitudine",
      "settingsExtentDateLineError2": "Errore di calcolo dell'estensione",
      "settingsExtentDrawBtn": "Disegna una nuova estensione",
      "settingsExtentModifyBtn": "Modifica l'estensione",
      "settingsExtentApplyBtn": "Anteprima in Tour mappa",
      "settingsExtentUseMainMap": "Usa estensione di Tour mappa",
      "settingsZoomExplain": "Impostare lo zoom per i punti della storia (opzionale).",
      "settingsLabelZoom": "Scala/livello",
      "settingsZoomFirstValue": "Nessuno",
      "settingsFieldError": "Selezionare un campo in ogni elenco",
      "dataTitle": "Crea layer tour mappa ospitato",
      "dataExplain": "Un nuovo feature layer verrà creato per le immagini e i punti del tour. Il layer Tour non sarà condiviso con alcun utente a meno che non venga condiviso il proprio tour mappa.",
      "dataExplainPortal": "Se il feature layer non viene creato correttamente, contattare l'amministratore di ArcGIS.",
      "dataNameLbl": "Nome layer",
      "dataFolderListLbl": "Cartella",
      "dataFolderListFetching": "Recupero cartelle...",
      "dataRootFolder": "Radice",
      "dataNameError": "Immetti un nome per il feature service",
      "dataFolderError": "Seleziona un cartella valida",
      "dataSrcContainsInvalidChar": "Il nome del feature service contiene uno o più caratteri non validi (-, <, >, #, %, :, \", ?, &, +, / o ).",
      "dataSrvAlreadyExistsError": "Nell'organizzazione esiste già un servizio con questo nome. Scegliere un nome diverso.",
      "dataBtnSave": "Creare il layer",
      "dataFooterProgress": "Creazione in corso",
      "dataFooterSucceed": "Creazione riuscita. Caricamento in corso",
      "dataFooterError": "Creazione non riuscita. Riprovare",
      "tabError": "Verificare la presenza di errori in tutte le schede",
      "introRecordBtn": "Introduzione",
      "introRecordActivate": "Usa il primo punto come introduzione (non viene visualizzato nel gruppo)",
      "coverRecordActivate": "Usa il primo punto come pagina di copertina",
      "coverBuilder": "Configurazione della pagina di copertina",
      "cover": "Copertina",
      "showCover": "Mostra copertina",
      "editCover": "Modifica copertina",
      "coverNoVideo": "La copertina non supporta i file video. Selezionare un’immagine.",
      "coverPreview": "Per visualizzare la copertina, salvare la storia e poi visualizzare l’anteprima utilizzando il pulsante Visualizza storia.",
      "thirdPartyTerms": "Utilizzando un servizio di terzi, si accettano i termini di servizio relativi: "
    },
    "addPopupJS": {
      "uploadingPicture": "Caricamento immagine in corso",
      "uploadSuccess": "Caricamento riuscito",
      "uploadError": "Errore durante il caricamento dell'immagine",
      "uploadError2": "Errore durante l'aggiunta della feature (tag HTML non valido)",
      "notJpg": "Scegliere una foto JPEG da caricare",
      "errorNoPhoto": "Scegli un'immagine da caricare",
      "errorNoThumbnail": "Scegliere un'anteprima da caricare",
      "errorInvalidPicUrl": "Immettere un URL immagine valido. Inizia con https. Termina con jpg, png, gif or bmp oppure terminare l’URL con '#isImage' per ignorare la regola.",
      "errorInvalidThumbUrl": "Immettere un URL anteprima valido (deve iniziare con https:// e terminare con jpg, png, gif o bmp).",
      "errorInvalidVideoUrl": "Immette un URL del video valido (iniziante con https://)",
      "errorNoName": "Immetti un nome per il punto del tour",
      "errorNoDescription": "Immetti una didascalia per il punto del tour",
      "errorNoLocation": "Imposta una posizione per il punto del tour"
    },
    "builderJS": {
      "noPendingChange": "Nessuna modifica non salvata",
      "unSavedChangeSingular": "1 modifica non salvata",
      "unSavedChangePlural": "modifiche non salvate",
      "shareStatus1": "Tour non salvato",
      "shareStatus2": "Tour condiviso pubblicamente",
      "shareStatus3": "Tour condiviso nell'ambito dell'organizzazione",
      "shareStatus4": "Tour non condiviso",
      "popoverDiscard": "Annullare tutte le modifiche non salvate?",
      "yes": "Sì",
      "no": "No",
      "popoverLoseSave": "Se si apre il viewer, tutte le modifiche non salvate andranno perse",
      "ok": "OK",
      "popoverSaveWhenDone": "Al termine, non dimenticare di salvare",
      "closeWithPendingChange": "Confermare l'azione? Le modifiche andranno perse.",
      "gotIt": "OK",
      "savingApplication": "Salvataggio storia",
      "saveSuccess": "Storia salvata",
      "saveError": "Salvataggio non riuscito. Riprovare",
      "saveError2": "Salvataggio non riuscito a causa di un tag HTML non valido in un nome o in una descrizione",
      "saveError3": "Specificare il titolo",
      "dragColorPicker": "Cambia posizione<br />o colore",
      "dataWarningExtent": "Sono presenti dati esterni all'estensione della mappa Web. Tali dati non verranno utilizzati come punti del tour. Se si desidera utilizzarli, cambiare l'estensione della mappa.",
      "dataWarningVisibi": "Il layer Tour mappa non è attualmente visibile nell'estensione della mappa Web corrente. Verificare che il layer sia visibile con una mappa di dimensioni %MAPSIZE%.",
      "dataWarningEdit": "Modifica la mappa Web",
      "dataWarningClose": "Chiudi",
      "signIn": "Effettuare l'accesso con un account su",
      "signInTwo": "per salvare la storia.",
      "switchBM": "Cambia mappa di base"
    },
    "organizePopupJS": {
      "messageStart": "L'opzione scelta consente di eliminare",
      "messageSinglePoint": "un punto del tour",
      "messageMultiPoint": "punti del tour",
      "messagePermantRemove": "Questa operazione implica la rimozione definitiva",
      "messageRecord": "del record",
      "messageRecordPlural": "dei record",
      "messageConfirm": "dal database. Continuare?",
      "labelButtonShow": "Mostra",
      "labelButtonHide": "Nascondi"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Immagine e anteprima verranno eliminate definitivamente",
      "popoverDeleteWarningThumb": "L'anteprima verrà eliminata definitivamente",
      "popoverUploadingPhoto": "Caricamento di immagine e anteprima",
      "popoverUploadingThumbnail": "Caricamento dell'anteprima",
      "popoverUploadSuccessful": "Caricamento riuscito",
      "popoverUploadError": "Caricamento non riuscito. Riprovare",
      "changePicAndThumb": "Cambia immagine",
      "changeThumb": "Cambia anteprima",
      "selectPic": "Cambia supporto",
      "selectThumb": "Cambia anteprima",
      "uploadPicAndThumb": "Applica"
    },
    "headerJS": {
      "editMe": "Modifica utente",
      "templateTitle": "Imposta titolo",
      "templateSubtitle": "Imposta sottotitolo",
      "edit": "Modifica"
    },
    "crossFaderJS": {
      "setPicture": "Imposta titolo immagine",
      "setCaption": "Imposta didascalia immagine"
    },
    "importPopup": {
      "title": "Importa",
      "prevBtn": "Indietro",
      "nextBtn": "Avanti"
    },
    "importPopupHome": {
      "header": "Dove sono archiviate le immagini?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "immagini",
      "videos": "video",
      "disabled": "Questa feature è stata disabilitata dall'amministratore",
      "disabledPortal": "Questa feature richiede che il portale disponga di un server di hosting. Contattare l'amministratore di Portal for ArcGIS.",
      "header1": "Le immagini devono essere condivise pubblicamente.",
      "header2": "L'importazione sarà limitata ai primi %NB1% %MEDIA%.",
      "emptyDataset": "Errore, nessun'immagine trovata",
      "footerImport": "Importa",
      "selectAlbum": "Seleziona un album pubblico",
      "selectAlbum2": "Seleziona un album",
      "pleaseChoose": "Scegli",
      "userLookup": "Ricerca",
      "userLookingup": "Ricerca in corso",
      "csv": "Si fa riferimento in un CSV",
      "advanced": "Opzioni avanzate",
      "advancedScratchLbl": "Crea un nuovo Tour",
      "advancedScratchTip": "Creare un Tour vuoto in cui aggiungere i punti del Tour. I file multimediali devono già trovarsi online. Questa opzione non supporta il caricamento di immagini.",
      "advancedCSVLbl": "Importa dati del Tour da un file CSV",
      "advancedCSVTip": "Importare i contenuti del Tour da un file CSV contenente i riferimenti ai file multimediali online. Questa opzione non supporta il caricamento di immagini.",
      "advancedCommonTip": "In questo caso immagini e video devono essere già disponibili online.",
      "select": "Crea una selezione",
      "locUse": "Usa geoposizione immagini",
      "locExplain": "Si può selezionare di non utilizzare le posizioni delle immagini perché possono essere ereditate dall'album, quindi tutte le foto sono nella stessa posizione.",
      "locExplain2": "Si può scegliere di non utilizzare le posizioni dei video perché possono essere ereditate dalle impostazioni utente, pertanto tutti i video sono disponibili nella stessa posizione."
    },
    "viewFlickr": {
      "title": "Importazione da Flickr",
      "header": "Immettere il nome utente Flickr e selezionare un album o un tag da importare.",
      "userInputLbl": "Immettere un nome utente",
      "signInMsg2": "Utente non trovato",
      "selectSet": "Seleziona un album",
      "selectTag": "o selezionare un tag",
      "footerImportTag": "Importa il tag selezionato",
      "footerImportSet": "Importa l’album selezionato"
    },
    "viewFacebook": {
      "title": "Importazione da Facebook",
      "header": "È possibile effettuare l'autenticazione con il account utente Facebook o utilizzare una pagina pubblica. Gli album privati possono essere utilizzati per creare Tour mappa pubblici che non richiedono l'autenticazione dell'utente Facebook, consentendo di mantenere privati commenti e apprezzamenti.",
      "leftHeader": "Utente Facebook",
      "rightHeader": "Pagina Facebook",
      "pageExplain": "Una pagina Facebook è un marchio/prodotto pubblico o un personaggio pubblico come <b>esrigis</b>. È possibile ottenere il nome della pagina dopo il primo '/' nell'URL della pagina.",
      "pageInputLbl": "Immettere un nome di pagina",
      "lookupMsgError": "Pagina non trovata"
    },
    "viewPicasa": {
      "title": "Importazione da Google+",
      "header": "Immettere l'indirizzo e-mail o l'ID.",
      "userInputLbl": "E-mail o ID Picasa/Google+",
      "signInMsg2": "Account non trovato",
      "signInMsg3": "Nessun album pubblico",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>Ulteriori informazioni</a>",
      "howToFind2": "Copiare le cifre tra il primo e il secondo \"/\" di qualsiasi pagina Picasa"
    },
    "viewCSV": {
      "title": "Importazione da CSV",
      "uploadBtn": "Selezionare o rilasciare un file CSV",
      "resultHeaderEmpty": "Il CSV è vuoto",
      "resultHeaderSuccess": "Caricati %NB_POINTS% punti",
      "resultHasBeenLimited": "L'importazione è stata limitata ai primi %VAL1% punti su %VAL2% per rispettare il limite di %VAL3% punti per tour",
      "browserSupport": "Il browser non è supportato; per utilizzare un CSV è necessario <a href='http://browsehappy.com/' target='_blank'>aggiornare il browser</a> o utilizzare il map viewer Web di ArcGIS.com (consultare la Guida).",
      "errorLatLng": "Campi Latitudine e Longitudine non trovati. Valori possibili per la latitudine sono: <i>%LAT%</i> e per la longitudine: <i>%LONG%</i>.",
      "errorFieldsExplain": "Il caricamento non è riuscito perché non sono stati trovati i seguenti campi obbligatori",
      "errorFieldsName": "I valori possibili per <b>Nome</b> sono: %VAL%",
      "errorFieldsDesc": "I valori possibili per <b>Descrizione</b> sono: %VAL%",
      "errorFieldsUrl": "I valori possibili per <b>URL immagine</b> sono: %VAL%",
      "errorFieldsThumb": "I valori possibili per <b>URL anteprima</b> sono: %VAL%",
      "errorFields2Explain": "Il caricamento non è riuscito perché il CSV non usa gli stessi attributi del layer per i seguenti attributi",
      "errorFields2Name": "<b>Nome</b> usa %VAL1% invece di %VAL2%",
      "errorFields2Desc": "<b>Descrizione</b> usa %VAL1% invece di %VAL2%",
      "errorFields2Url": "<b>URL immagine</b> usa %VAL1% invece di %VAL2%",
      "errorFields2Thumb": "<b>URL anteprima</b> usa %VAL1% invece di %VAL2%",
      "resultFieldsAll": "Tutti gli attributi sono stati importati",
      "resultFieldsNotAll": "I seguenti attributi non sono stati importati perché non esistono nel layer mappa",
      "resultFieldsNotAll2": "Sono stati importati i seguenti attributi",
      "footerNextBtnResult": "Importa nella mappa Web",
      "footerProgress": "Importazione in corso",
      "footerSucceed": "Importazione riuscita. Caricamento in corso"
    },
    "viewYoutube": {
      "title": "Importazione da YouTube",
      "header": "Immettere un nome utente di YouTube per trovare video condivisi pubblicamente.",
      "pageInputLbl": "Immettere un nome utente di YouTube",
      "lookupMsgError": "Utente non trovato",
      "howToFind": "Come trovare un nome utente di YouTube",
      "howToFind2": "Il nome utente è visualizzato sotto i video",
      "found": "Trovato",
      "noData": "Nessun video pubblico trovato."
    },
    "viewGeoTag": {
      "title": "Seleziona e individua immagini/video",
      "header": "Le voci individuate verranno importate. Fare clic su una delle voci non individuate da importare per individuarle.",
      "headerMore": "Guida",
      "headerExplain": "Facendo clic sul pulsante <b>Importa</b>, verranno importati solo le immagini o i video elencati nella scheda <b>Individuati</b>.<br><br>Le informazioni di geolocalizzazione archiviate con immagini o video vengono importate automaticamente, se è possibile accedervi. Tutte le voci senza una geolocalizzazione sono elencate nella scheda <b>Per individuare</b>. Per individuare una voce elencata in quella scheda, fare clic su di essa, quindi fare clic sulla posizione desiderata sulla mappa.<br><br>Per rimuovere una voce dalla scheda <b>Individuato</b> in modo che non venga importata, fare clic sul pulsante Non importare, che appare quando si sposta il cursore su quella voce.<br><br>Suggerimento: se le informazioni di geolocalizzazione dei file multimediali non vengono importate, controllare le impostazioni sulla privacy dell’account. Ad esempio, nelle impostazioni dell’account Flickr, assicurarsi che i dati EXIF non siano nascosti. Inoltre, se l'opzione della privacy di Flickr per importare i dati EXIF per i nuovi caricamenti è disattivata (impostazione predefinita), le geolocalizzazioni non vengono archiviate in Flickr per le immagini, a meno che non si carichino nuovamente o si specifichino manualmente le relative posizioni in Flickr.",
      "leftPanelTab1": "Per individuare",
      "leftPanelTab2": "Individuato",
      "clickOrTap": "Fare clic sulla mappa per individuare",
      "clearLoc": "Cancella posizioni",
      "clickDrop": "Non importare",
      "footerImport": "Importa",
      "footerProgress": "Importazione in corso",
      "footerSucceed": "Importazione completata. Caricamento in corso...",
      "loading": "Caricamento in corso",
      "error": "Importazione delle geoposizioni immagini non riuscita. Le geoposizioni sono state ignorate."
    },
    "initPopup": {
      "title": "Benvenuti nel Generatore di Tour mappa",
      "prevBtn": "Indietro",
      "nextBtn": "Avanti"
    },
    "initPopupHome": {
      "header1": "Dove si trovano le immagini o i video?",
      "header2": "L'Assistente consente di generare un Tour mappa da immagini già archiviate online o le importerà nell'account ArcGIS Online for Organizations dell'utente.",
      "title1": "Sono già online",
      "title2": "Le immagini devono essere caricate",
      "hostedFSTooltip": "Caricare le immagini e memorizzarle nel Tour (i video non sono supportati).",
      "hostedFsNA": "È necessario essere un Editore o disporre di un altro ruolo con il privilegio per pubblicare feature layer ospitati. Contattare l'amministratore di ArcGIS.",
      "hostedFsNA2": "Disponibile solo con un abbonamento ad ArcGIS Online. <a href='%LINK%'>Richiedi versione di prova gratuita</a>",
      "footer1": "Al termine, non dimenticare di condividere il Tour mappa con il proprio pubblico mediante la pagina di elementi dell'applicazione.",
      "footer3": "Scarica il modello CSV",
      "footer4": "\"Salva come\" se il download non fosse stato completato",
      "footer4bis": "Se il download non si avvia, fare clic con il pulsante destro del mouse e scegliere \"Salva con nome\"",
      "footer5": "Ulteriori informazioni",
      "footerProgress": "Creazione in corso",
      "footerSucceed": "Creazione completata. Caricamento in corso..."
    },
    "helpPopup": {
      "title": "Guida",
      "close": "Chiudi",
      "tab1": {
        "title": "Introduzione",
        "moreInfo": "Ulteriori informazioni",
        "infoSites": "Visita la sezione <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>Tour mappa</a> del sito Web <a href='https://storymaps.arcgis.com' target='_blank'>Esri Story Maps.</a>",
        "mtFAQ": "Consultare le <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Domande frequenti sul Tour mappa.</a>",
        "myStories": "È possibile gestire i Tour mappa e verificare la presenza di eventuali errori in <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>My Stories</a> sul sito Web.",
        "div1": "Il modello di Tour mappa è progettato per presentare informazioni geografiche in cui è presente un elemento fotografico o multimediale interessante per la storia da raccontare.",
        "div2": "Il modello produce un'applicazione Web interessante e di facile utilizzo che consente di presentare una breve serie di luoghi su una mappa in una sequenza numerata accessibile agli utenti. Il modello è progettato per l'utilizzo con qualsiasi browser Web su qualsiasi dispositivo, compresi smartphone e tablet. <br /><br />",
        "div42": "Per visualizzare esempi di Tour mappa creati da altri utenti, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visita la galleria</a> sul sito Web <a href='https://storymaps.arcgis.com/' target='_blank'>Story Maps</a>. Oppure segui su Twitter <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Non esitare a dirci cosa pensi! Facci sapere quali problemi hai riscontrato e le nuove funzionalità di cui avresti bisogno visitando il forum Story Maps su <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet.</a>"
      },
      "tab2": {
        "title": "Dati",
        "div1": "Quando si crea un Tour mappa, l'elemento principale da considerare è la scelta del punto in cui verranno archiviate le immagini. In un Tour mappa si possono utilizzare immagini archiviate in servizi di condivisione di foto, su qualsiasi server Web o caricate dalla propria memoria.",
        "div1a": "Per informazioni dettagliate sui formati immagine e sui video supportati, vedere l'ultima sezione di questa scheda.",
        "div2": "Il generatore interattivo offre due opzioni per la gestione delle immagini in Tour mappa:",
        "div3": "<ul><li>È possibile usare <b>immagini che si trovano già online</b>, come quelle disponibili in Flickr oppure immagini archiviate nel proprio sito Web. Nel Map Tour si farà riferimento a queste immagini attraverso il loro URL.</li><li>Inoltre, è possibile <b>caricare immagini dal proprio computer</b> direttamente nel Map Tour. Per usufruire dell’opzione di caricamento, è necessario disporre di un abbonamento ad ArcGIS e dei privilegi di Editore o Amministratore, in quanto verrà creato automaticamente un feature service hosted nel quale le foto verranno memorizzate come allegati.</li></ul>",
        "div4": "I principali casi d'uso sono:",
        "div4b": "<b>Le foto non sono ancora ospitate</b> e l'utente dispone di un abbonamento ad ArcGIS: l'utilizzo di un Feature Service hosted rappresenta la scelta migliore. Come i servizi di condivisione di foto pubblici, le immagini vengono ottimizzate in modo da creare immagini rapide da caricare e l'utente avrà accesso a tutte le opzioni di amministrazione e di gestione dei dati della piattaforma ArcGIS.",
        "div5": "<b>L'utente non è membro di un'organizzazione</b>: prima è necessario caricare le immagini in un sito Web per la condivisione di foto o sul proprio server Web. Il generatore aiuta l'utente a utilizzare le immagini che continueranno a essere ospitate nella posizione originale.",
        "div6": "<b>Si desidera riutilizzare un feature service esistente</b> che archivia le immagini come allegati o che fa riferimento a immagini esterne: consultare la sezione dettagliata di seguito.",
        "div7": "<b>Utenti di una versione precedente</b> del modello di Tour mappa e già in possesso del CSV che fa riferimento alle immagini e alle anteprime: è possibile importare e ottimizzare i dati. Il generatore supporta solo CSV che utilizzano campi relativi a latitudine/longitudine; è possibile continuare a utilizzare CSV basati su indirizzi mediante la mappa Web (vedere la sezione di seguito)",
        "div8": "Importare da servizi di condivisione di immagini online",
        "div9a": "Il supporto Facebook è stato interrotto, ${learn}.",
        "learn": "ulteriori informazioni",
        "div9": "L'operazione di importazione fa riferimento a immagini già ospitate tramite la memorizzazione dei relativi URL in una raccolta di feature mappa Web. Le immagini non vengono archiviate in ArcGIS Online. Se le immagini ospitate risultano inaccessibili, non saranno disponibili in Tour mappa e verrà utilizzata un'immagine \"Immagine non disponibile\". A seconda del provider di servizi per le foto, il Tour mappa importerà o meno il nome, la descrizione e la posizione delle immagini. Tali attributi sono memorizzati nella mappa Web e le eventuali modifiche ai servizi online non verranno applicate al Tour mappa.",
        "div10": "Archiviare le immagini su un server Web",
        "div11": "Se si sceglie di ospitare le immagini sul proprio server Web (piuttosto che accedere alle immagini in Flickr o caricarle direttamente nel proprio tour), sarà necessario creare manualmente le relative anteprime. Se per le anteprime si utilizzano immagini a piena risoluzione, le prestazioni ne risentiranno. Consultare le <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>Domande frequenti</a> per i suggerimenti sulle dimensioni delle immagini quando si accede ad esse direttamente attraverso un URL.",
        "div12": "Uso di dati luogo esistenti",
        "div13": "Se si dispone di dati luogo esistenti, come un elenco di luoghi in un foglio di calcolo o un layer puntuale GIS, è possibile utilizzare tali dati in formato CSV per creare un Tour mappa. Ciò richiede che le immagini siano accessibili direttamente tramite URL che sono memorizzati come valori nel file CSV. È possibile scaricare il modello CSV dalla finestra di dialogo Opzioni avanzate al primo avvio del generatore di Tour mappa. Il file CSV può essere aggiornato in quella finestra di dialogo.",
        "div14": "I valori supportati per i nomi dei campi sono (senza differenza tra maiuscole e minuscole):",
        "div151": "Nome",
        "div152": "Descrizione",
        "div153": "Immagine",
        "div154": "Anteprima",
        "div155": "Colore ",
        "div16": "Se l'applicazione non trova campi corrispondenti quando si utilizza un feature service, il visualizzatore non funzionerà fino a quando non verranno configurati i campi da utilizzare mediante il generatore. I layer CSV e shapefile aggiunti alla mappa Web devono avere tutti i campi obbligatori; in caso contrario, il generatore non funziona.",
        "div162": "Quando si utilizza un feature service che memorizza le immagini come allegati, <b>verranno utilizzate solo le feature con due allegati</b>. Il primo allegato definisce l'immagine principale, mentre il secondo definisce l'anteprima.",
        "div17": "I campi Immagine e Anteprima sono obbligatori per i feature service senza allegati e facoltativi ma consigliati per i feature service con allegati. Se nel servizio sono abilitati gli allegati, il generatore consente di caricare le immagini come allegati. In caso contrario, è possibile soltanto modificare gli URL dell'immagine e dell'anteprima.",
        "div172": "Quando presenti, verranno sempre utilizzati i campi relativi a immagine e anteprima e gli allegati del feature service non verranno cercati.",
        "div173": "È possibile scaricare CSV e shapefile di esempio da",
        "div174": "Consultare le <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>Domande frequenti</a> per ulteriori informazioni.",
        "div18": "Creazione di un feature service ospitato da CSV o shapefile",
        "div19": "Quando si crea un feature service ospitato da un CSV o shapefile, per impostazione predefinita gli allegati non sono abilitati. Per abilitarli, aprire la pagina dei dettagli del feature service e fare clic sulla piccola freccia sulla sezione Layer per visualizzare l'opzione. Dopo aver effettuato quest'operazione, Tour mappa continuerà a utilizzare le immagini e le anteprime a cui si è fatto riferimento mediante gli attributi. Facoltativamente, se si desidera caricare le immagini come allegati di feature service, utilizzare i due pulsanti sul pannello immagini (\"Cambia immagine\" e \"Cambia anteprima\").",
        "div20": "Formati immagine e video supportati",
        "div21": "Se si accede alle immagini in Flickr, il Tour mappa accede automaticamente a queste immagini come file .jpg. Se si caricano immagini nel generatore di Tour mappa, le immagini devono essere in formato .jpg o .jpeg. Se fai riferimento alle immagini direttamente sul Web tramite i relativi URL, i formati di immagine supportati sono .jpg, .jpeg, .png, .gif e .bmp. I video di YouTube sono supportati direttamente.",
        "div22": "Il modello Tour mappa non include un lettore video, pertanto è necessario utilizzare il lettore esterno fornito dal servizio di hosting video preferito (individuare l'opzione per incorporare il video e copiare l'URL presente nel codice specificato). Se si desidera ospitare il video, è possibile creare una pagina HTML che contiene un lettore video, ad esempio <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Il generatore interattivo non prevede una finestra di dialogo per includere i video quando si utilizzano feature service senza allegati, ma è possibile effettuare questa operazione modificando i dati all'esterno del generatore interattivo. Se in Arcgis.com Map Viewer si modificano i campi delle immagini in modo che puntino a un video esterno e si aggiunge un parametro speciale alla fine dell'URL (#isVideo), il file multimediale verrà considerato come video.",
        "div24": "Si noti che per utilizzare il punto è comunque necessario disporre di due allegati immagine validi. Non è possibile utilizzare video quando si utilizzano allegati di feature service senza i campi immagine e anteprima."
      },
      "tab3": {
        "title": "Personalizzazione",
        "div1": "Il generatore fornisce numerose opzioni di personalizzazione accessibili mediante il pulsante IMPOSTAZIONI nel pannello superiore. Se non si trova l'opzione cercata, è disponibile anche una versione scaricabile che può essere distribuita nel proprio server Web per soddisfare le proprie necessità.",
        "div2": "Si consiglia di utilizzare la versione ospitata, con le seguenti eccezioni:",
        "div3": "<li>Non offre una personalizzazione dell'interfaccia utente desiderata, per esempio l'utilizzo di un'immagine di sfondo per l'intestazione.</li><li>L'utente è uno sviluppatore e desidera migliorare l'applicazione.</li>",
        "div4": "La versione scaricabile può essere configurata attraverso una mappa Web o un identificatore di un'applicazione di mappatura Web. I principali casi d'uso sono:",
        "div41": "Per creare il Tour mappa, si utilizza il generatore interattivo nell'ambiente ospitato e si configura il modello con l'identificatore dell'applicazione di mapping Web. Verranno applicate le impostazioni definite con il generatore interattivo.",
        "div42": "Si crea la mappa Web all'esterno del generatore interattivo e si configura il modello con l'identificatore di mappa Web. Per informazioni su come configurare il modello, sarà necessario leggere la documentazione.",
        "div43": "Si noti che il generatore interattivo è disponibile nella versione scaricabile ma con alcuni limitazioni tecniche in alcuni browser, ad esempio le versioni di Internet Explorer anteriori alla 10.",
        "div5": "Per scaricare la versione più recente del modello e per ulteriori informazioni su come utilizzarla, visitare la <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>pagina di progetto GitHub</a>."
      },
      "tab4": {
        "title": "Suggerimenti",
        "div0": "Browser supportati",
        "div0a": "Il visualizzatore del Tour mappa è supportato in versioni di Internet Explorer successive alla 8. Il generatore interattivo è supportato in versioni di Internet Explorer successive alla 9. Quest'ultimo è stato attivamente testato in tutti i principali browser, ma in caso di problemi si consiglia di utilizzare Chrome.",
        "div0b": "In caso di problemi, informare Esri. Nel frattempo creare il Tour mappa con il modello CSV per ridurre l'interazione con l'interfaccia del generatore.",
        "div1": "Immagini",
        "div2": "Sebbene in un Tour mappa sia possibile usare immagini di diverse dimensioni, forma e orientamento, è consigliabile utilizzare immagini con orientamento orizzontale anziché verticale. Le immagini con rapporto di aspetto 4:3 si adattano meglio. Nel layout a tre riquadri e integrato, in cui la didascalia è sovrapposta all'immagine, se si utilizzano immagini con orientamento verticale è possibile che gran parte dell'immagine venga nascosta dalla didascalia. Nel layout a tre riquadri e integrato, è consigliabile utilizzare immagini con la stessa forma e dimensione, ove possibile. In questo modo, l'utente non sarà distratto da immagini di dimensioni diverse durante il Tour.",
        "div2a": "Per il formato massimo delle immagini si consiglia un massimo di 1000 pixel (larghezza) x 750 pixel (altezza) per le immagini principali e di 140x93 per le anteprime.",
        "div3": "Formattare il testo della didascalia con tag HTML",
        "div4": "È possibile inserire tag HTML nelle didascalie per definirne la formattazione e i link. Ad esempio, questi tag aggiungono un hyperlink verde:",
        "div4aa": "<b>Creare una pagina di copertina per il tour con riquadro laterale</b><br>Il layout con riquadro laterale supporta una pagina di copertina opzionale, in modo da poter attirare l'attenzione del pubblico con un’immagine di impatto a schermo intero. Per configurare la pagina di copertina per il tour con riquadro laterale, prima aggiungere alcuni o tutti i punti nel tour. Quindi, fare clic sul pulsante Organizza e, nella finestra di dialogo visualizzata, assicurarsi che il punto del tour da utilizzare per definire la copertina sia il primo punto del tour. Quindi, fare clic sulla finestra di dialogo 'Usa il primo punto come pagina di copertina'. Il nome del tuo primo punto del tour diventerà il titolo mostrato sulla pagina di copertina, la didascalia per quel punto diventerà il sottotitolo e l'immagine di quel punto verrà utilizzata come immagine della pagina di copertina. Il video non è supportato nella pagina di copertina. Consultare le <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>Domande frequenti</a> per ulteriori informazioni.</a>",
        "div4a": "Scrivere un sottotitolo per il Tour",
        "div4b": "È importante elaborare con cura un sottotitolo avvincente per il tour. Il sottotitolo è il modo migliore per coinvolgere le persone nel tour e raccontare loro cosa scopriranno. Inoltre, è lo spazio adeguato in cui parlare al proprio pubblico del paese nel quale il tour si svolge. Ad esempio, non si deve dare per scontato che le persone sappiano dove si trovano le città e le cittadine del tour. Tuttavia, il sottotitolo non deve essere troppo lungo. Se non si riesce a elaborare un buon sottotitolo, è preferibile non inserirlo. A differenza dei layout a tre riquadri e integrato, il layout con riquadro laterale supporta una sottotitolo nell'intestazione. Se si utilizza l'opzione della pagina di copertina nel layout con riquadro laterale, la didascalia del primo punto del tour viene visualizzata sulla pagina di copertina e funge da sottotitolo per il tour.",
        "div5": "Layer di supporto",
        "div6": "È possibile aggiungere ulteriori layer di supporto per fornire contesto per il Tour mappa. I layer possono contenere altre feature geografiche che si desidera visualizzare nella mappa oltre ai punti del Tour mappa, ad esempio un'area di studio, un percorso a piedi o in auto che collega i punti del tour, ecc. Il modello Tour mappa visualizza i layer di supporto aggiuntivi utilizzando la simbologia specificata nella mappa Web, ma i popup non sono disponibili. Per aggiungere layer di supporto al tour, salvare il lavoro e chiudere il generatore di Tour mappa. In seguito, aprire la mappa Web usata nel tour, che è possibile trovare nella sezione I miei contenuti di ArcGIS o nella sezione My Stories del sito Web Story Maps.",
        "div7": "Mantenere il tour breve e piacevole",
        "div8": "Esiste un limite di 99 punti per tour. Naturalmente, la maggior parte dei Tour mappa sarà molto più breve. Il pubblico non desidera scorrere troppi punti del tour. Il soggetto può essere affascinante, ma non si deve presupporre che lo sarà anche per il pubblico.",
        "div10": "Modalità Incorpora",
        "div11": "Se si desidera incorporare il modello in un altro sito Web tramite un iframe, aggiungere il parametro facoltativo \"&embed” alla fine dell'URL per rimuovere l'intestazione.",
        "div12": "Evitare di specificare una larghezza troppo ridotta per l'iFrame; in caso contrario, per il Tour mappa verrà attivata la visualizzazione su schermo piccolo, ovvero la stessa visualizzazione utilizzata dal tour su dispositivi mobili. Per garantire la massima semplicità d'uso, quando si incorpora un Tour mappa, si consiglia di fornire comunque un collegamento accanto al tour incorporato per consentire agli utenti di avviare il tour a schermo intero."
      },
      "tab5": {
        "title": "Pubblicazione",
        "div1": "Al termine, non dimenticare di condividere il Tour mappa con il proprio pubblico mediante il pulsante CONDIVIDI o la pagina degli elementi dell'applicazione in ArcGIS Online.",
        "div2a": "Condivisione del Tour tramite il generatore",
        "div2b": "Il pulsante CONDIVIDI consente di aggiornare gli elementi dell'applicazione e della mappa Web. Se memorizzati in un elemento feature service, verranno aggiornati anche i dati del Tour. Gli eventuali altri layer aggiunti tramite ArcGIS.com Map Viewer non verranno aggiornati. In questo caso è possibile che il Tour non venga condiviso nel modo previsto. Gli elementi che già dispongono dei privilegi necessari o di privilegi superiori non verranno aggiornati.",
        "div2c": "Condivisione del Tour tramite ArcGIS Online",
        "div2d": "Quando si condivide l'applicazione tramite ArcGIS Online, se necessario verrà chiesto di aggiornare le eventuali risorse dipendenti (mappa Web, feature service, layer decorazioni) non condivise nello stesso modo. Se il Tour mappa è pubblico e una delle risorse non è condivisa con il pubblico, gli utenti verranno reindirizzati alla pagina di accesso di ArcGIS Online.",
        "div3t": "Sicurezza feature service",
        "div3a": "Se si utilizza un feature service ospitato creato mediante il generatore di Tour mappa, l'applicazione gestisce la protezione del servizio e l'utente è il solo con privilegi di modifica, anche se il servizio è condiviso pubblicamente.",
        "div3t2": "Operazioni preliminari alla condivisione del Tour con il pubblico",
        "div3": "Assicurarsi che il Tour funzioni correttamente quando non è stato effettuato l'accesso con l'account ArcGIS.com. L'URL da utilizzare non deve reindirizzare a una pagina di accesso o alla modalità generatore.",
        "div4": "È consigliabile verificare l'aspetto del Tour mappa su un iPad con orientamento orizzontale per controllare se viene visualizzato correttamente su questo popolare dispositivo. In tal modo sarà possibile controllare se le didascalie occupano troppo spazio nelle immagini e se i sottotitoli non sono troppo lunghi e vengono tagliati.",
        "div5a": "Consigli per la ricerca",
        "div5b": "Per consentire agli utenti di individuare il Tour mappa durante le ricerche in ArcGIS Online, si consiglia di aggiungere il tag 'mappa collegata a una storia' nella pagina degli elementi dell'applicazione del Tour mappa (non nella pagina degli elementi della mappa Web), unitamente a tag quali il nome dello stato e della provincia, il nome del paese, oltre a tag tematici quali 'monumento', 'guida turistica' o 'luoghi storici'. Questi tag consentiranno anche a Esri di trovare altri esempi di Tour da includere nelle gallerie e promuovere nei social network. Si consiglia anche di caricare nella pagina degli elementi dell'applicazione un'immagine, ad esempio una schermata del Tour o una fotografia. Tale immagine verrà utilizzata automaticamente se il Tour viene aggiunto alla galleria di ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Tour salvato",
      "manageStory": "Gestisci la storia",
      "manageStoryA1": "Suggerimento: è possibile utilizzare %LINK1% per controllare che la storia non contenga errori, cambiare la modalità di condivisione dei suoi componenti, migliorarne l'aspetto sui social network, ecc. Maggiori informazioni su My Stories %LINK2%.",
      "manageStoryA1V1": "My Stories",
      "manageStoryA1V2": "qui",
      "shareTitle": "Condividi il Tour",
      "sharePrivateHeader": "Il Tour non è condiviso. Condividerlo?",
      "sharePrivateBtn1": "Condividi pubblicamente",
      "sharePrivateBtn2": "Condividi con l'organizzazione",
      "sharePrivateProgress": "Condivisione in corso...",
      "sharePrivateErr": "Condivisione non riuscita. Riprovare o",
      "sharePrivateOk": "Condivisione aggiornata. Caricamento in corso...",
      "sharePreviewAsUser": "Anteprima",
      "shareHeader1": "Il Tour è <strong>accessibile pubblicamente</strong>.",
      "shareHeader2": "Il Tour è accessibile ai membri dell'organizzazione (accesso obbligatorio).",
      "shareLinkHeader": "Condividi il Tour",
      "shareLinkOpen": "APRI",
      "shareA1": "Utilizzare %SHAREIMG% nella <a href='%LINK1%' target='_blank'>pagina degli elementi dell'applicazione</a>. Se si desidera anche annullare la condivisione della mappa Web, utilizzare la <a href='%LINK2%' target='_blank'>pagina degli elementi della mappa Web</a>.",
      "shareWarning": "La condivisione %WITH% è stata disabilitata perché non si è proprietari della <a href='%LINK%' target='_blank'>mappa Web</a>.",
      "shareWarningWith1": "con il pubblico",
      "shareWarningWith2": "con il pubblico e con l'organizzazione",
      "viewStory": "Visualizza storia"
    },
    "locator": {
      "error": "Posizione non disponibile"
    },
    "saveErrorSocial": {
      "title": "Aggiornamento condivisione con social media",
      "panel1": "L'aspetto della storia sui social media è stata migliorata, ma il titolo dell'elemento applicazione Web ArcGIS è diverso dal titolo della storia.",
      "panel1tooltip": "Se si definisce un titolo, un riepilogo e un'immagine di anteprima, l'aspetto della storia sarà:",
      "panel2": "Specificare il titolo che si desidera utilizzare sui social media:",
      "panel2q1": "Titolo della storia (consigliato)",
      "panel2q1tooltip": "Se si sceglie questa opzione, il titolo dell'elemento verrà modificato per corrispondere al titolo della storia e ulteriori modifiche nel generatore verranno sincronizzate.",
      "panel2q2": "Titolo elemento",
      "panel3": "Per migliorare ulteriormente l'aspetto della storia sui social media utilizzare ${MYSTORIES} per aggiungere un riepilogo e un'immagine di anteprima.",
      "panel4": "Non visualizzare più avvisi per questa storia",
      "mystories": "My Stories",
      "btnSave": "Salva"
    },
    "bannerNotification": {
      "learnMore": "Ulteriori informazioni",
      "close": "Chiudi",
      "dontShowAgain": "Non visualizzare più questo messaggio"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Messaggio importante riguardante la sicurezza Web e le Story Map",
      "s1h1": "Esri sta migliorando la sicurezza delle Story Map",
      "s1p1": "Le Story Map vivono nel Web e la comunità Web è costantemente impegnata nella formulazione e nell’implementazione di misure volte a migliorare la sicurezza. Il protocollo HTTPS, che fornisce una connessione sicura per i contenuti trasmessi su Internet, si sta affermando come metodo di accesso più comune ai contenuti Web. Molti dei browser moderni mostrano un messaggio di avviso nei casi in cui viene usato l’HTTP anziché l’HTTPS. A causa di questo standard emergente, consigliamo vivamente di utilizzare i link HTTPS per la creazione e la condivisione di Story Maps e di utilizzare solo gli URL HTTPS per incorporare il contenuto Web o il collegamento a immagini all'interno di una Story Map.",
      "s1p2": "In pratica, ciò significa che una Story Map e tutto il suo contenuto (inclusi immagini, layer, app incorporate e siti Web) devono essere accessibili utilizzando i collegamenti che iniziano con HTTPS anziché con HTTP. Ciò garantisce la migliore esperienza per i lettori perché la maggior parte dei browser Web indica che le tue storie sono al sicuro.",
      "s2h1": "Cosa occorre fare?",
      "s2p1": "Esri sta lavorando per rendere questa transizione facile per autori e lettori di Story Map. I generatori di Story Map e My Stories contengono strumenti che possono essere impiegati per trovare contenuti non sicuri (HTTP) all’interno delle storie e che forniscono indicazioni utili sulla loro gestione. Si prega di verificare la presenza di contenuti non sicuri all’interno delle storie e di aggiornarli all’HTTPS prima possibile.",
      "action1": "Chiudi",
      "action2": "Controlla subito le mie storie",
      "action3": "Ulteriori informazioni"
    },
    "embedBar": {
      "share": "Crea",
      "fullScreen": "Schermo intero",
      "enlarge": "Allarga",
      "newTab": "Apri in una nuova scheda",
      "tagline": "Story Map",
      "exitFullScreen": "Chiudi visualizzazione a schermo intero"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Possiamo fare qualche domanda? Ci consentiranno di plasmare il futuro di Story Maps.",
      "s1h1": "Condividi le tue opinioni, plasma il futuro",
      "s1p1": "Il contributi degli utenti sono la nostra più importante fonte di feedback e ottenere ulteriori informazioni sugli utenti ci consentirà di migliorare Story Maps. Saremmo lieti che i nostri utenti possano partecipare a questa inchiesta di tre minuti.",
      "s2p1": "Come sempre, grazie per aver utilizzato Esri Story Maps!",
      "action1": "Chiudere",
      "action2": "Partecipa all’inchiesta"
    },
    "licenseChange2018": {
      "noAccess": "L’account (%USER_NAME%) non dispone della licenza per aprire una Story Map non pubblica. È necessario richiedere all’amministratore dell'organizzazione l’assegnazione di un tipo di utente che includa le Story Map o una licenza aggiuntiva per le app essenziali."
    },
    "storyTellerUserType": {
      "notCreatorError": "L'account (%USER_NAME%) non possiede la licenza per utilizzare i generatori di Story Map classiche. Richiedere all'amministratore dell'organizzazione di assegnare all'utente corrente un tipo di utente Creator."
    }
  }
});