define({
  "viewer": {
    "loading": {
      "step1": "HİKAYE YÜKLENİYOR",
      "step2": "VERİLER YÜKLENİYOR",
      "step3": "TUR BAŞLATILIYOR",
      "loadBuilder": "DERLEYİCİ MODUNA GEÇİLİYOR",
      "redirectSignIn": "OTURUM AÇMA SAYFASINA YÖNLENDİRİLİYOR",
      "redirectSignIn2": "(oturum açtıktan sonra buraya yeniden yönlendirileceksiniz)",
      "fail": "Üzgünüz, Harita Turu yüklenemedi",
      "failButton": "Tekrar dene"
    },
    "errors": {
      "boxTitle": "Bir hata oluştu",
      "portalSelf": "Onarılamaz hata: Portal yapılandırması alınamadı",
      "invalidConfig": "Onarılamaz: Geçersiz yapılandırma",
      "invalidConfigOwner": "Onarılamaz hata: Geçersiz yapılandırma (yetkili sahip gerekiyor)",
      "invalidConfigNoWebmap": "Onarılamaz hata: Geçersiz yapılandırma (web harita veya uygulama tanımlayıcısı index.html dosyasında belirtilmemiş)",
      "invalidConfigNoAppDev": "Web Haritalama Uygulaması belirteci veya web haritası URL parametrelerinde (?appid= veya ?webmap=) belirtilmemiş. Geliştirme modunda index.html dosyasındaki appid ve web haritası yapılandırması yoksayılır.",
      "createMap": "Harita oluşturulamıyor",
      "invalidApp": "Onarılamaz hata: Hikaye yüklenemiyor",
      "noLayer": "Web haritası Harita Turu için geçerli bir veri katmanı içermiyor.",
      "noLayerMobile": "Harita Turu oluşturucu, bu ekran boyutunda desteklenmez. Mümkünse, oluşturucu erişimi için tarayıcınızı yeniden boyutlandırın veya hikayenizi daha büyük ekranı olan bir cihazda oluşturun.",
      "noLayerMobile2": "Cihazınızı yatay konuma döndürerek Harita Turu oluşturucuyu kullanın.",
      "noLayerView": "Harita Turu web uygulamasına hoş geldiniz.<br />Hikaye henüz yapılandırılmadı.",
      "appSave": "Hikaye kaydetme hatası",
      "mapSave": "Web haritasını kaydederken hata oluştu",
      "featureServiceLoad": "Detay servisi yüklenirken hata oluştu",
      "notAuthorized": "Bu hikayeye erişme yetkiniz yok",
      "notAuthorizedBuilder": "Harita Turu oluşturucuyu kullanma yetkiniz yok.",
      "oldBrowserTitle": "Tarayıcı tam olarak desteklenmiyor",
      "noBuilderIE8": "Harita Turu derleyicisi 9. sürümden önceki Internet Explorer'da desteklenmemektedir.",
      "ie10Win7Explain": "Veri kaynağı ekleri olan bir Detay Servisi olduğunda, Harita Turu etkileşimli derleyicisi Windows 7'de Internet Explorer 10'da desteklenmez. Ekleri olan bir Detay Servisi kullanmak için <a target='_blank' href='http://msdn.microsoft.com/tr-tr/library/ie/hh920756(v=vs.85).aspx'>belge modunu Internet Explorer 9 standartlarına el ile zorlamalı</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>Internet Explorer 9'ı geri yüklemeli</a> veya Windows 8'e yükselmelisiniz.",
      "oldBrowserExplain": "Bu tarayıcı, harita turunuza yüklediğiniz görüntülerden otomatik küçük resim oluşturmayı desteklemiyor. Bu tarayıcıyı kullanarak bir harita turu oluşturabilirsiniz, ancak yüklediğiniz her görüntü için ayrı bir küçük resim görüntüsü sağlamanız gerekir.",
      "oldBrowserExplain2": "Deneyiminizi iyileştirmek için, <a href='http://browsehappy.com/' target='_blank'>tarayıcınızı yükseltin</a> veya <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>Google Chrome Frame for Internet Explorer'ı etkinleştirin</a>.",
      "oldBrowserExplain3": "Harita Turu derleyicisi Windows XP'de Internet Explorer 10 ile çalışmaz.",
      "oldBrowserClose": "Kapat",
      "noViewerIE2": "Bu hikayeyi daha eski ve desteklenmeyen bir tarayıcı kullanarak görüntülemeye çalışıyorsunuz. Çalışmayan özellikler olabilir veya başka beklenmedik sorunlarla karşılaşılabilir. Internet Explorer 11 sürümüne yükseltme yapmanız veya Chrome gibi başka bir tarayıcı kullanmanız önerilir.",
      "noViewerIE3": "2017’nin sonuna doğru bu hikaye artık bu tarayıcıda yüklenemeyecek. Hikayeyi o zaman görüntülemek için desteklenen bir tarayıcı kullanmanız gerekecek.",
      "attention": "Dikkat!"
    },
    "mobileHTML": {
      "showIntro": "BAŞLIĞI GÖSTER",
      "hideIntro": "BAŞLIĞI GİZLE",
      "navList": "Liste",
      "navMap": "Harita",
      "navInfo": "Medya",
      "introStartBtn": "Başlangıç"
    },
    "desktopHTML": {
      "storymapsText": "Bir öykü haritası",
      "builderButton": "Derleyici moduna geç",
      "facebookTooltip": "Facebook'ta Paylaş",
      "twitterTooltip": "Twitter'da Paylaş",
      "bitlyTooltip": "Kısa bağlantı edin",
      "bitlyStartIndex": "Geçerli yere bağlantı kur",
      "tooltipAutoplayDisabled": "Bu özellik otomatik oynatma modunda kullanılamaz",
      "autoplayLabel": "Otomatik oynatma modu",
      "autoplayExplain1": "Otomatik oynatma modu düzenli aralıklarla hikayenizde ilerler. Bu özellik, bir kiosk ya da genel ekran için idealdir, ancak bunun bazı durumlarda hikayenin okunmasını güçleştirebileceğini unutmayın. Bu özellik küçük ekranlarda desteklenmez.",
      "autoplayExplain2": "Bu etkin durumdayken hikayeyi oynatacak/duraklatacak ve gezinme hızını ayarlayacak kontroller vardır.",
      "takeTourText": "Tura başlayın",
      "backToStart": "Başlangıca Geri Dön"
    },
    "builderHTML": {
      "panelHeader": "HİKAYE YAPILANDIRMASI",
      "buttonSave": "KAYDET",
      "buttonSettings": "Ayarlar",
      "buttonShare": "Paylaş",
      "buttonView": "Modu görüntüle",
      "buttonItem": "Web Uygulaması öğesini açın",
      "buttonHelp": "Yardım",
      "buttonOrganize": "Düzenle",
      "buttonAdd": "Ekle",
      "buttonImport": "İçe Aktar",
      "buttonImportDisabled": "Ekleri olan bir Detay Servisi kullanılırken içe aktarma kullanılamaz",
      "dataEditionDisabled": "Veri düzenleme bu CSV veri kaynağında devre dışıdır",
      "dataSourceWarning": "Harita Turu veri katmanı değişmiş. Detay tanımlayıcısı aynı değilse, <b>Düzenle</b> yoluyla sırayı ve gizli noktaları sıfırlamanız gerekir. Alanın adı farklıysa, <b>Ayarlar'daki veri sekmesi</b> altından alanın ayarlarını sıfırlamalısınız.",
      "organizeWarning": "Etkileşimli derleyicinin dışına eklenmiş bir veya daha fazla nokta gizli.",
      "dataPicError0a": "Bu turda <b>%NB%</b> adet uyumsuz resim URL'si bulunur.",
      "dataPicError0b": "Bu turda <b>%NB%</b> adet uyumsuz resim URL'si bulunabilir.",
      "dataPicError1": "Harita Turu artık bir resim URL'sinin şu uzantılardan biriyle bitmesini gerektirmektedir: .jp(e)g, .png, .gif veya .bmp.",
      "dataPicError2": "Bu gereksinim, mevcut yayınlanmış Harita Turunuzu etkilemeyecek. Ancak, etkileşimli derleyiciyi kullanabilmek için, önce şu işlemlerden birini yaparak URL sorununu çözmeniz gerekir:",
      "dataPicError3": "URL'leri Düzenle",
      "dataPicError4": "Bu desteklenmeyen resim URL'lerinin sonuna <i>#isImage</i> ifadesini ekler. Sunucuların çoğu URL eklemelerini destekler. Ancak, bu işlemi bir kez yaptıktan sonra, noktalarınızda gezinerek güncellenmiş resim URL'lerinin çalıştığından emin olmanız gerekir. Resimlerin tümü yükleniyorsa, artık Harita Turu'nu kaydedebilirsiniz. <b>Resimlerin bağlantısı kopuksa, Harita Turu'nu kaydetmeyin</b>. Bunun yerine ikinci işlemi yapmak için derleyiciyi tekrar yükleyin.",
      "dataPicError5": "Turu resimlerle sınırla",
      "dataPicError6": "Bu seçenek tüm URL'lerin görüntü olarak kabul edilmesine neden olur, ancak etkileşimli derleyiciyi kullanarak video ekleyemezsiniz. Bu işlem, gelecekte video eklemeye karar vermeniz durumunda geri alınabilir.",
      "dataPicError7": "Harita Turu resimlerle sınırlandı, video kullanılamaz. Bu sınırlamayı kaldırmayı seçerseniz, Harita Turu'nu kaydetmeden önce resimlerin hala yüklendiğinden emin olun. Gerekirse ileride bu sınırlamayı tekrar devreye sokabilirsiniz.",
      "dataPicError8": "Resim sınırlamasını kaldır",
      "dataPicError9": "Bu URL'ler videolara işaret ediyorsa, bu uyarıyı yoksayabilirsiniz; görüntülere işaret ediyorsa, şu iki işlemden birini yapmanız gerekir:",
      "modalCancel": "İptal",
      "modalApply": "Uygula",
      "organizeHeader": "Turu düzenle",
      "organizeGeneralCaption": "Tur noktalarını düzene sokmak için sürükle-bırak kullan",
      "organizeDelete": "Sil",
      "organizeHide": "Gizle",
      "organizeReset": "Sırayı ve gizli noktaları sıfırla",
      "addMaxPointReached": "Simge setinin izin verdiği maksimum nokta sayısına ulaştınız ve başka bir tur noktası ekleyemezsiniz.<br /><br />Mevcut noktaları silerseniz, hikayeyi yeniden yüklemeniz gerekeceğini unutmayın.",
      "addMaxPointReachedMobile": "Üzgünüz, izin verilen maksimum nokta sayısına ulaştınız ve bu resmi ekleyemezsiniz.",
      "addClose": "Kapat",
      "addHeader": "Yeni bir tur noktası ekle",
      "addTabPicture": "Medya",
      "addTabInformation": "Bilgi",
      "addTabLocation": "Konum",
      "addSelectCaption": "Resim seç veya bırak",
      "addNoteVideo": "Video kullanma hakkında talimatlar için Yardım'a başvurun",
      "addSelectCaptionNoFileReader": "Resim seç",
      "addChangePhoto": "Resmi ve küçük resmi değiştir",
      "addPictureResolutionIntro": "Resim çözünürlüğü gerekenden daha fazla:",
      "addPictureResolutionOldBrowser": "Resim çözünürlüğü gerekenden daha yüksek. %RECOMMENDED_RES% üzerinde bir çözünürlük belirterek Harita Turu deneyimini optimize edin.",
      "addPictureResolutionResize": "Resim çözünürlüğünü %RESOLUTION% olarak değiştir",
      "addPictureResolutionKeep": "%RESOLUTION% olan ilk çözünürlüğü koru",
      "addSelectThumbnail": "Küçük resmi seç",
      "addNoThumbSelected": "Hiçbir küçük resim seçilmedi",
      "addThumbSelected": "Seçildi",
      "addCameraSettingsHeader": "KAMERA AYARLARI",
      "addThumbnailHeader": "KÜÇÜK RESİM",
      "addLabelPicUrl": "Resim",
      "addLabelThumbUrl": "Küçük Resim",
      "addTextPlaceholderUrl": "Görüntü URL'si girin",
      "addTextPlaceholderUrl2": "YouTube sayfa URL'si girin",
      "addTextPlaceholderUrl3": "Vimeo sayfa URL'si girin",
      "addTextPlaceholderUrl4": "Video katıştırma URL'si girin",
      "addLabelVideo": "Video",
      "addMediaVideoOther": "Diğer",
      "addMediaVideoHelp": "URL'yi denetleyin ve varsayılan küçük resmi alın",
      "addMediaVideoHelpTooltip1": "Denetim başarılı",
      "addMediaVideoHelpTooltip2": "Denetim başarısız",
      "addMediaVideoHelpTooltip4": "Videoyu katıştırma seçeneğini bulun ve koddaki video URL'sini kopyalayın",
      "addLabelName": "Ad",
      "addLabelDescription": "Altyazı",
      "addTextPlaceholder": "Birşey yazın",
      "addLocatePlaceholder": "Bir adresi veya yeri bulun",
      "addPinColor": "Renk",
      "addLatitude": "Enlem",
      "addLongitude": "Boylam",
      "addLatitudePlaceholder": "ör. 34.056",
      "addLongitudePlaceholder": "ör. -117.195",
      "addUploading": "Tur noktası yükleniyor",
      "addSave": "Tur noktası ekle",
      "addMobileUploading": "Resim yükleniyor",
      "addMobileName": "Ad girin",
      "addMobileNameMandatory": "Hata; ad girin.",
      "addMobileError": "Üzgünüz, yanlışlık oldu",
      "settingsHeader": "Hikaye ayarları",
      "settingsTabLayout": "Düzen",
      "settingsTabColor": "Renkler",
      "settingsTabLogo": "Üstbilgi",
      "settingsTabFields": "Veri",
      "settingsTabExtent": "Yayılım",
      "settingsTabZoom": "Yakınlaştırma Düzeyi",
      "settingsLayoutExplain": "İstediğiniz yerleşimi seçin.",
      "settingsLayoutProfessional": "Üç panelli",
      "settingsLayoutModern": "Entegre",
      "settingsLayoutSidePanel": "Yan panel",
      "settingsLayoutSelected": "Seçili düzen",
      "settingsLayoutNew": "Yeni!",
      "settingsLayoutSelect": "Seç",
      "settingsLayoutNote": "Video kullanan noktalarda, seçenek işaretlenmese bile döviz her zaman videonun altına yerleştirilir.",
      "settingsLayoutLocBtn": "'Bul' düğmesi ekle",
      "settingsLayoutLocBtnHelp": "Çoğu tarayıcıda desteklenir. Yalnızca hikaye haritasına HTTPS üzerinden erişim sağlandığında görünür. Hikaye gömülü ise görünmez.",
      "settingsColorExplain": "Önceden tanımlı bir tema seçerek veya kendi temanızı oluşturarak görünümü değiştirin.",
      "settingsLabelColor": "Üstbilgi, içerik ve altbilgi renkleri",
      "settingsLogoExplain": "Üstbilgi logosunu özelleştirin. (Maksimum 250 x 50 px'tir.).",
      "settingsLogoEsri": "Esri logosu",
      "settingsLogoNone": "Logo yok",
      "settingsLogoCustom": "Özel logo",
      "settingsLogoCustomPlaceholder": "Görüntü URL'si",
      "settingsLogoCustomTargetPlaceholder": "Tıklanabilir bağlantı",
      "settingsLogoSocialExplain": "Üstbilgi üst sağ bağlantısını özelleştirin.",
      "settingsLogoSocialText": "Metin",
      "settingsLogoSocialLink": "Bağlantı",
      "settingsLogoSocialDisabled": "Bu özellik Yönetici tarafından devre dışı bırakıldı",
      "settingsDataFieldsExplain": "Fotoğraf adını, altyazısını ve renk alanlarını seçin.",
      "settingsDataFieldsError": "Uygulama uygun ad, altyazı veya renk verilerini belirleyemiyor. Kullanılacak alanları burada seçin. Bu ayarlar daha sonra değiştirilebilir.",
      "settingsFieldsLabelName": "Ad",
      "settingsFieldsLabelDescription": "Altyazı",
      "settingsFieldsLabelColor": "Renk",
      "settingsFieldsReset": "Alan seçimini sıfırla",
      "settingsExtentExplain": "Harita Turu ilk yayılımını aşağıdaki etkileşimli haritayla ayarlayın.",
      "settingsExtentExplainBottom": "Tanımladığınız yayılım web haritanızın ilk yayılımını değiştirecek. İlk tur noktasını içermiyorsa, bu yayılımın kullanılmadığına dikkat edin. Bu durumda tur ilk noktayı merkez alarak başlar.",
      "settingsExtentDateLineError": "Yayılım 180Â° boylam meridyeninden geçemez",
      "settingsExtentDateLineError2": "Yayılımı hesaplanırken hata oluştu",
      "settingsExtentDrawBtn": "Yeni bir yayılım çiz",
      "settingsExtentModifyBtn": "Yayılımı düzenle",
      "settingsExtentApplyBtn": "Harita Turunda Önizle",
      "settingsExtentUseMainMap": "Harita Turu yayılımını kullan",
      "settingsZoomExplain": "Hikaye noktaları için yakınlaştırmayı ayarla (isteğe bağlı).",
      "settingsLabelZoom": "Ölçek/düzey",
      "settingsZoomFirstValue": "Hiçbiri",
      "settingsFieldError": "Her listeden bir alan seçin",
      "dataTitle": "Barındırılan Harita Turu katmanı oluştur",
      "dataExplain": "Görüntüleriniz ve tur noktalarınız için yeni bir Detay Katmanı oluşturulacak. Harita Turunuz başkalarıyla paylaşılmadıkça tur katmanı paylaşılmaz.",
      "dataExplainPortal": "Bu detay için Portal for ArcGIS 10.4 gerekir. Detay Katmanını oluşturamazsanız, ArcGIS yöneticinize başvurun.",
      "dataNameLbl": "Katman ismi",
      "dataFolderListLbl": "Klasör",
      "dataFolderListFetching": "Klasörler alınıyor ...",
      "dataRootFolder": "Kök",
      "dataNameError": "Detay servisi için ad girin",
      "dataFolderError": "Geçerli bir klasör seçin",
      "dataSrcContainsInvalidChar": "Detay servisi adı bir veya daha fazla geçersiz karakter (-, <, >, #, %, :, \", ?, &, +, / veya ) içeriyor.",
      "dataSrvAlreadyExistsError": "Bu ada sahip bir servis adı kuruluşunuzda zaten var. Farklı bir ad seçin.",
      "dataBtnSave": "Katman oluştur",
      "dataFooterProgress": "Oluşturma sürüyor",
      "dataFooterSucceed": "Oluşturma başarılı. Yükleniyor",
      "dataFooterError": "Oluşturma başarısız. Tekrar deneyin",
      "tabError": "Tüm sekmelerdeki hataları kontrol etin",
      "introRecordBtn": "Giriş",
      "introRecordActivate": "İlk noktayı giriş olarak kullanın (döner sistemde görünmez)",
      "coverRecordActivate": "Kapak sayfası olarak ilk noktayı kullan",
      "coverBuilder": "Kapak Sayfası Yapılandırması",
      "cover": "Kapak",
      "showCover": "Kapağı Göster",
      "editCover": "Kapağı Düzenle",
      "coverNoVideo": "Kapak ortamı için video desteklenmiyor. Lütfen bir görüntü seçin.",
      "coverPreview": "Kapağı görmek için hikayenizi kaydedin ve ardından Paylaş düğmesini kullanarak inceleyin."
    },
    "addPopupJS": {
      "uploadingPicture": "Resim yükleniyor",
      "uploadSuccess": "Yükleme başarılı",
      "uploadError": "Resim yüklenirken hata oluştu",
      "uploadError2": "Detay eklenirken hata oluştu (geçersiz html etiketi)",
      "notJpg": "Yüklenecek jpeg uzantılı fotoğraf seçin",
      "errorNoPhoto": "Yüklenecek bir görüntü seçin",
      "errorNoThumbnail": "Yüklenecek bir küçük resim seçin",
      "errorInvalidPicUrl": "Geçerli resim girin. (http(s):// ile başlamalı, jpg, png, gif veya bmp ile bitmelidir.) Bu kuralı geçersiz kılmak için URL'yi '#isImage' ile bitirebilirsiniz.",
      "errorInvalidThumbUrl": "Geçerli bir küçük resim girin. (http(s):// ile başlar, jpg, png, gif veya bmp ile biter.)",
      "errorInvalidVideoUrl": "Geçerli bir video URL'si girin (http(s):// ile başlar)",
      "errorNoName": "Bu tur noktası için ad girin",
      "errorNoDescription": "Bu tur noktası için altyazı girin",
      "errorNoLocation": "Bu tur noktası için konum belirleyin"
    },
    "builderJS": {
      "noPendingChange": "Kaydedilmemiş değişiklik yok",
      "unSavedChangeSingular": "Kaydedilmemiş 1 değişiklik var",
      "unSavedChangePlural": "kaydedilmemiş değişiklikler",
      "shareStatus1": "Tur kaydedilmedi",
      "shareStatus2": "Tur herkes ile paylaşılıyor",
      "shareStatus3": "Tur kuruluş ile paylaşılıyor",
      "shareStatus4": "Tur paylaşılmıyor",
      "popoverDiscard": "Kaydedilmemiş değişiklerden vazgeçmek istediğinizden emin misiniz?",
      "yes": "Evet",
      "no": "Hayır",
      "popoverLoseSave": "Görüntüleyiciyi açarsanız, kaydedilmemiş değişiklikleri kaybedeceksiniz",
      "ok": "Tamam",
      "popoverSaveWhenDone": "İşiniz bittiğinde kaydetmeyi unutmayın",
      "closeWithPendingChange": "Eylemi onaylamak istediğinizden emin misiniz? Değişiklikleriniz kaybolacak.",
      "gotIt": "Tamam",
      "savingApplication": "Hikaye kaydediliyor",
      "saveSuccess": "Hikaye kaydedildi",
      "saveError": "Kaydetme başarısız; tekrar deneyin",
      "saveError2": "Addaki veya açıklamadaki geçersiz bir html etiketi nedeniyle kaydetme başarısız oldu",
      "saveError3": "Başlık boş olamaz",
      "dragColorPicker": "Beni gezdirin<br />veya rengimi değiştirin",
      "dataWarningExtent": "Web haritası yayılımının dışında verileriniz var. Bu veriler tur noktaları olarak kullanılmayacak, bunları kullanmak istiyorsanız harita yayılımını değiştirin.",
      "dataWarningVisibi": "Harita Turu katmanınız geçerli web haritası yayılımında görünmüyor. Harita Turu katmanınızın %MAPSIZE% büyüklükte bir haritada görünür olduğunu doğrulayın.",
      "dataWarningEdit": "Web haritasını düzenle",
      "dataWarningClose": "Kapat",
      "signIn": "Uygulamayı kaydetmek için",
      "signInTwo": "hikayeyi kaydetmek için.",
      "switchBM": "Harita Altlığını Değiştir"
    },
    "organizePopupJS": {
      "messageStart": "Silmeyi seçtiniz",
      "messageSinglePoint": "tek tur noktası",
      "messageMultiPoint": "tur noktaları",
      "messagePermantRemove": "Bu işlem, veri tabanınızdan",
      "messageRecord": "kaydı",
      "messageRecordPlural": "kayıtları",
      "messageConfirm": "kalıcı olarak silecek. Devam etmek istiyor musunuz?",
      "labelButtonShow": "Göster",
      "labelButtonHide": "Gizle"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "Bu, resmi veya küçük resmi kalıcı olarak silecek",
      "popoverDeleteWarningThumb": "Bu, küçük resmi kalıcı olarak silecek",
      "popoverUploadingPhoto": "Resim veya küçük resim yükleniyor",
      "popoverUploadingThumbnail": "Küçük resim yükleniyor",
      "popoverUploadSuccessful": "Yükleme başarılı",
      "popoverUploadError": "Yükleme başarısız; tekrar deneyin",
      "changePicAndThumb": "Resmi değiştir",
      "changeThumb": "Küçük resmi değiştir",
      "selectPic": "Medyayı değiştir",
      "selectThumb": "Küçük resmi değiştir",
      "uploadPicAndThumb": "Uygula"
    },
    "headerJS": {
      "editMe": "Beni düzenle!",
      "templateTitle": "Şablon başlığını ayarla",
      "templateSubtitle": "Şablon altyazısını ayarla",
      "edit": "Düzenle"
    },
    "crossFaderJS": {
      "setPicture": "Resim başlığını ayarla",
      "setCaption": "Resim altyazısını ayarla"
    },
    "importPopup": {
      "title": "İçe Aktar",
      "prevBtn": "Geri",
      "nextBtn": "Sonraki"
    },
    "importPopupHome": {
      "header": "Resimleriniz nerede depolanıyor ?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "resimler",
      "videos": "videolar",
      "disabled": "Bu özellik Yönetici tarafından devre dışı bırakıldı",
      "disabledPortal": "Bu detay, portalın bir barındırma sunucusuna sahip olmasını gerektirir. Portal for ArcGIS Yöneticinize başvurun.",
      "header1": "Resimlerinizin herkes ile paylaşılması gerekiyor.",
      "header2": "Bu içe aktarma ilk %NB1% %MEDIA% ile sınırlanacak.",
      "emptyDataset": "Hata, hiçbir resim bulunamadı",
      "footerImport": "İçe Aktar",
      "selectAlbum": "Genel bir albüm seçin",
      "selectAlbum2": "Bir albüm seçin",
      "pleaseChoose": "Seçin",
      "userLookup": "Ara",
      "userLookingup": "Aranıyor",
      "csv": "Bir CSV'de başvuruluyor",
      "advanced": "Gelişmiş seçenekler",
      "advancedScratchLbl": "Yeni bir Tur başlat",
      "advancedScratchTip": "Tur noktaları ekleyebileceğiniz boş bir Tur oluşturun. Ortamınız zaten çevrimiçi olmalıdır. Bu seçenek, görüntülerinizi yüklemeyi desteklemiyor.",
      "advancedCSVLbl": "CSV dosyasından içe Tur verileri aktarın",
      "advancedCSVTip": "Çevrimiçi ortamınıza referans veren bir CSV dosyasından Tur içeriğini içeri aktarın. Bu seçenek, görüntülerinizi yüklemeyi desteklemez.",
      "advancedCommonTip": "Görüntü ve videolarınızın zaten çevrimiçi olmasını gerektirir.",
      "select": "Seçim yap",
      "locUse": "Resimlerin coğrafi konumunu kullan",
      "locExplain": "Resimler albümden devralınabileceği, bu da tüm fotoğrafların aynı konumda olmasına neden olabileceği için resimlerin konumunu kullanmak istemeyebilirsiniz.",
      "locExplain2": "Videolar kullanıcı ayarlarından devralınabileceğinden, bu da tüm videoların aynı konumda olmasına neden olabileceğinden videoların konumunu kullanmak istemeyebilirsiniz."
    },
    "viewFlickr": {
      "title": "Flickr'dan içe aktarma",
      "header": "Flickr kullanıcı adınızı girin ve içe aktarılacak bir Fotoğraf Seti veya Etiket seçin.",
      "userInputLbl": "Kullanıcı Adı Girin",
      "signInMsg2": "Kullanıcı bulunamadı",
      "selectSet": "Fotoğraf Seti Seçin",
      "selectTag": "veya Etiket Seçin",
      "footerImportTag": "Seçili Etiketi içe aktarın",
      "footerImportSet": "Seçili Seti içe aktarın"
    },
    "viewFacebook": {
      "title": "Facebook içe aktarma",
      "header": "Facebook Kullanıcı Hesabınız ile kimlik doğrulayın veya bir Genel Sayfa kullanın. Facebook kullanıcı kimlik doğrulaması gerektirmeyen genel bir Harita Turu oluşturmak için, yorum yapmaya izin veren ve özel kalmayı tercih eden özel albümler kullanılabilir.",
      "leftHeader": "Facebook Kullanıcısı",
      "rightHeader": "Facebook Sayfası",
      "pageExplain": "Facebook sayfası, <b>esrigis</b> gibi genel bir marka/ürün veya ünlü kişiliktir. Sayfa adını sayfa URL'sindeki ilk '/' karakterinden alabilirsiniz.",
      "pageInputLbl": "Sayfa adı girin",
      "lookupMsgError": "Sayfa bulunamadı"
    },
    "viewPicasa": {
      "title": "Picasa aktarımı",
      "header": "E-posta adresinizi veya Picasa kimliğinizi girin.",
      "userInputLbl": "E-posta veya Picasa kimliği",
      "signInMsg2": "Hesap bulunamadı",
      "signInMsg3": "Genel albüm yok",
      "howToFind": "Picasa kimliğini bulma",
      "howToFind2": "Herhangi bir Picasa sayfasının ilk ve ikinci '/' karakteri arasındaki rakamları kopyalayın"
    },
    "viewCSV": {
      "title": "CSV içe aktarma",
      "uploadBtn": "CSV dosyasını seçin veya üstüne bırakın",
      "resultHeaderEmpty": "CSV boş",
      "resultHeaderSuccess": "%NB_POINTS% nokta yüklendi",
      "resultHasBeenLimited": "Tur başına %VAL3% nokta sınırına uymak için içe aktarma %VAL2% noktanın ilk %VAL1% noktasıyla sınırlandı",
      "browserSupport": "Tarayıcınız desteklenmiyor. Bir CSV kullanmak için, <a href='http://browsehappy.com/' target='_blank'>tarayıcınızı yükseltmeli</a> veya ArcGIS.com web haritası görüntüleyiciyi kullanmalısınız. (Yardım'a bakın.)",
      "errorLatLng": "Enlem ve boylam alanları bulunamadı. Olabilecek değerler, enlem için: <i>%LAT%</i>, boylam için: <i>%LONG%</i>.",
      "errorFieldsExplain": "Aşağıdaki zorunlu alanlar bulunamadığından yükleme başarısız oldu",
      "errorFieldsName": "<b>Ad</b> için olabilecek değerler: %VAL%",
      "errorFieldsDesc": "<b>Açıklama</b> için olabilecek değerler: %VAL%",
      "errorFieldsUrl": "<b>Resim URL'si</b> için olabilecek değerler: %VAL%",
      "errorFieldsThumb": "<b>Küçük Resim URL'si</b> için olabilecek değerler: %VAL%",
      "errorFields2Explain": "CSV aşağıdaki özniteliklerin katmanı için aynı öznitelikleri kullanmadığından yükleme başarısız oldu",
      "errorFields2Name": "<b>Ad</b> - %VAL2% yerine %VAL1% kullanın",
      "errorFields2Desc": "<b>Açıklama</b> - %VAL2% yerine %VAL1% kullanın",
      "errorFields2Url": "<b>Resim URL'si</b> - %VAL2% yerine %VAL1% kullanın",
      "errorFields2Thumb": "<b>Küçük Resim URL'si</b> - %VAL2% yerine %VAL1% kullanın",
      "resultFieldsAll": "Tüm öznitelikler içe aktarıldı",
      "resultFieldsNotAll": "Aşağıdaki öznitelikler, harita katmanında olmadıklarından içe aktarılmadı",
      "resultFieldsNotAll2": "Aşağıdaki öznitelikler içe aktarıldı",
      "footerNextBtnResult": "Web haritasına içe aktar",
      "footerProgress": "İçe aktarma sürüyor",
      "footerSucceed": "İçe aktarma başarılı. Yükleniyor"
    },
    "viewYoutube": {
      "title": "YouTube içe aktarma",
      "header": "Herkesle paylaşılan videolar bulmak için bir YouTube kullanıcı adı girin.",
      "pageInputLbl": "YouTube kullanıcı adı girin",
      "lookupMsgError": "Kullanıcı bulunamadı",
      "howToFind": "YouTube kullanıcı adı bulma",
      "howToFind2": "Kullanıcı adı bu videoların altında gösterilir",
      "found": "Bulundu",
      "noData": "Hiçbir genel video bulunamadı"
    },
    "viewGeoTag": {
      "title": "Görüntülerinizi/videolarınızı seçin ve bulun",
      "header": "İçe aktarmak istediğiniz resimleri bulmak için resimlerin üzerine tıklayın veya dokunun.",
      "headerMore": "Görüntülerimin/videolarımın coğrafi konumları neden bulunamıyor?",
      "headerExplain": "Resimlerinizin geçerli bir coğrafi konumu varsa, bunlar otomatik olarak haritaya yerleştirilir ve ikinci sekmede listelenir.<br /><br />Varsayılan olarak, Picasa ve Flickr resimleri içe aktarırken coğrafi konum EXIF meta verilerini saklamaz. Resimlerin coğrafi konumunun içe aktarılmasını ve harici bir uygulama tarafından kullanılmasını sağlamak için Picasa/Flickr gizlilik ayarlarını kontrol edin. EXIF coğrafi konumunun kullanılabilmesi için mevcut resimlerinizi Flickr/Picasa'ya yeniden aktarmanız gerekebilir.",
      "leftPanelTab1": "Bulunacaklar",
      "leftPanelTab2": "Bulunanlar",
      "clickOrTap": "Bulmak için Haritaya tıklayın veya dokunun",
      "clearLoc": "Konumları temizle",
      "clickDrop": "İçe aktarma",
      "footerImport": "İçe Aktar",
      "footerProgress": "İçe aktarma sürüyor",
      "footerSucceed": "İçe aktarma başarılı. Yükleniyor...",
      "loading": "Yükleniyor",
      "error": "Resimlerin coğrafi konumunu içe aktarma başarısız oldu; coğrafi konumlar yoksayıldı."
    },
    "initPopup": {
      "title": "Harita Turu Derleyicisine Hoş Geldiniz",
      "prevBtn": "Geri",
      "nextBtn": "Sonraki"
    },
    "initPopupHome": {
      "header1": "Görüntüleriniz veya videolarınız nerede?",
      "header2": "Bu yardımcı, daha önce çevrimiçi olarak depoladığınız medyadan bir Harita Turu derlemenize yardımcı olacak veya bunları ArcGIS Online for Organizations hesabınıza içe aktaracak.",
      "title1": "Zaten çevirimiçi",
      "title2": "Görüntülerimi yüklemem gerekiyor",
      "hostedFSTooltip": "Görüntülerinizi yükleyin ve Turunuzda saklayın (video desteklenmez).",
      "hostedFsNA": "Yayıncı veya barındırılan Detay Katmanı yayınlama ayrıcalığına sahip başka bir rol sahibi olmalısınız. ArcGIS yöneticinize başvurun.",
      "hostedFsNA2": "Yalnızca ArcGIS Online aboneliğiyle kullanılabilir. <a href='%LINK%'>Ücretsiz deneme sürümüne kaydolun</a>",
      "footer1": "İşiniz bittiğinde, Harita Turunuzu uygulama öğesi sayfasından izleyici kitlenizle paylaşmayı unutmayın.",
      "footer3": "CSV şablonunu indir",
      "footer4": "İnmezse \"Farklı Kaydet\" kullan",
      "footer4bis": "İndirme başlamazsa sağ tıklayıp \"Farklı Kaydet\" seçeneğini kullanın",
      "footer5": "Daha fazla bilgi",
      "footerProgress": "Oluşturma sürüyor",
      "footerSucceed": "Oluşturma başarılı. Yükleniyor..."
    },
    "helpPopup": {
      "title": "Yardım",
      "close": "Kapat",
      "tab1": {
        "title": "Giriş",
        "moreInfo": "Daha fazla bilgi için",
        "infoSites": "<a href='https://storymaps.arcgis.com' target='_blank'>Esri Story Maps web sitesinin</a> <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>Harita Turu bölümünü</a> ziyaret edin.",
        "mtFAQ": "<a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>Harita Turu SSS.</a>",
        "myStories": "Harita Turlarınızı yönetebilir ve web sitesinde <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Hikayelerim</a> bölümünde hatalar için denetleyebilirsiniz.",
        "div1": "Harita Turu şablonu, anlatmak istediğiniz öykü açısından ilgi uyandıracak bir fotoğraf veya medya öğesi olduğunda coğrafi bilgi sunmak için tasarlanmıştır.",
        "div2": "Şablon, az sayıda yeri kullanıcıların içinde gezinebileceği numaralı bir sırada sunmanıza izin veren çekici, kullanımı kolay bir web uygulaması üretir. Şablon, akıllı telefon ve tablet gibi bir cihazdaki web tarayıcısında kullanılmak üzere tasarlanmıştır. <br /><br />",
        "div42": "Diğer kullanıcıların oluşturduğu harita turlarının örneklerini görmek için <a href='https://storymaps.arcgis.com/' target='_blank'>Story Maps web sitesinde</a> <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>galeriyi ziyaret edin</a>. Bizi ayrıca Twitter'da <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a> adresinden takip edebilirsiniz.",
        "div5": "Sizden haber almak bizi çok mutlu eder! Story Maps'i ziyaret ederek sorunlarınızı ve ihtiyaç duyduğunuz yeni özellikleri <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet üzerinden bize bildirin.</a>"
      },
      "tab2": {
        "title": "Veri",
        "div1": "Harita Turu oluştururken dikkate alınacak temel unsur, resimlerin nerede saklanacağını seçmektir. Harita Turunda, fotoğraf paylaşım hizmetleri, herhangi bir web sunucusu veya diskte saklanan resimler kullanabilir.",
        "div1a": "Desteklenen resim formatların ve videoların ayrıntıları için bu sekmenin son bölümüne bakın.",
        "div2": "Etkileşimli derleyici Harita Turunuzdaki görüntüleri yönetmek için iki seçenek sunar:",
        "div3": "<ul><li>Flickr gibi bir fotoğraf paylaşım sitelerinde saklanan veya kendi web sitenizde depolanan görüntüler gibi <b>zaten çevrimiçi olan fotoğrafları</b> kullanabilirsiniz. Bu görüntülere, URL'leri aracılığıyla, Harita Turunuzda referans verilecektir.</li><li>Ayrıca, fotoğrafları bilgisayarınızdan <b>doğrudan Harita Turunuza</b> da yükleyebilirsiniz. Bu yükleme seçeneği, bir ArcGIS aboneliğinizin olmasını ve Yayıncı veya Yönetici ayrıcalıklarınızın olmasını gerektirir; çünkü fotoğraflarınızın ek olarak saklandığı barındırılan bir özellik hizmeti sizin için otomatik olarak oluşturulur.</li></ul>",
        "div4": "Ana kullanım örnekleri şunlardır:",
        "div4b": "<b>Fotoğraflarınız henüz barındırılmıyor</b> ve bir ArcGIS aboneliğine sahipsiniz: Barındırılan detay servisini kullanmak en iyi seçiminizdir. Genel fotoğraf paylaşım hizmetlerinde de olduğu gibi, hızlı yüklenen görüntüler için resimlerinizi optimum hale getireceğiz ve siz de ArcGIS platformunun tüm idari ve veri yönetim becerilerine erişim sağlayabileceksiniz.",
        "div5": "<b>Bir Kuruluşa üye değilsinizdir</b>: Resimlerinizi önce bir fotoğraf paylaşma web sitesine veya kendi web sunucunuza yüklemeniz gerekir. Derleyici, asıl konumlarında barındırılmaya devam edecek olan bu resimleri kullanmanıza yardımcı olur.",
        "div6": "Resimlerinizi ekler olarak depolayan veya harici resimlere başvuran <b>mevcut bir Detay Servisi'ni tekrar kullanmanın yollarını arıyorsunuzdur</b>: Aşağıdaki ayrıntılı bölüme bakın.",
        "div7": "Harita Turu şablonunun <b>önceki bir sürümünün kullanıcısısınızdır</b> ve zaten resimlerinize ve küçük resimlerinize başvuran bir CSV'niz vardır: Bu dosyayı içe aktarıp verilerinizi ayrıntılandırabilirsiniz. Derleyici yalnızca enlem/boylam alanlarını kullanan CSV'leri destekler; adres tabanlı CSV'ler web haritanız yoluyla kullanılmaya devam edebilir. (Aşağıdaki bölüme bakın.)",
        "div8": "Çevrimiçi fotoğraf paylaşma servislerinden içe aktarma",
        "div9a": "Facebook desteği artık verilmemektedir, ${learn}.",
        "learn": "daha fazla bilgi",
        "div9": "İçe aktarma işlemi zaten barındırılmakta olan resimlere bunların URL'lerini bir web haritası detay koleksiyonda depolayarak başvurur. Resimler ArcGIS Online'da depolanamaz. Barındırılan resimlere erişilemiyorsa, bunlar Harita Turu'nda kullanılamaz ve bir 'Resim kullanılamıyor' görüntüsü görürsünüz. Fotoğraf servisi sağlayıcınıza bağlı olarak Harita Turu resimlerini adını, açıklamasını ve konumunu içe aktaramayabilir. Bu öznitelikler web haritasında depolanır ve çevrimiçi servislerde yapılan düzenlemelerin hiçbiri Harita Turuna yansımaz.",
        "div10": "Resimleri bir web sunucusunda depolama",
        "div11": "Fotoğrafları kendiniz saklamayı seçerseniz, resimlerinizin küçük resimlerini manuel olarak oluşturmalısınız. Tam çözünürlükteki resimlerin küçük resim oluşturmak için kullanılması performansın düşmesine neden olur. Görüntülerinize URL'ler aracılığıyla doğrudan web üzerinde erişim sağlıyorsanız, boyutlandırma ipuçları ile ilgili bu <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>SSS</a>'ye bakın.",
        "div12": "Mevcut GIS verilerinin kullanılması",
        "div13": "Herhangi bir detay servisi, CSV dosyası veya noktalar içeren bir shapefile dosyası, uygulamanın beklediği alanlar kümesini içeriyorsa, bir Harita Turu veri kaynağı olarak kullanılabilir. Bunu bir ArcGIS web haritasına katman olarak eklemeli ve ardından Harita Turu oluşturarak haritayı paylaşmalısınız.",
        "div14": "Alan adları için desteklenen değerler (büyük/küçük harfe duyarlı):",
        "div151": "Ad",
        "div152": "Açıklama",
        "div153": "Resim",
        "div154": "Küçük Resim",
        "div155": "Renk ",
        "div16": "Uygulama bir detay servisini kullanırken eşleşen alanlar bulamazsa, kullanılacak alanlar derleyici yoluyla yapılandırılana kadar görüntüleyici çalışmaz. Web haritasına eklenen CSV ve shapefile katmanlarının gerekli tüm alanlara sahip olması gerekir, yoksa derleyici çalışmaz.",
        "div162": "Resimleri ekler olarak depolayan bir detay servisini kullanılırken <b>yalnızca iki eki olan detaylar kullanılır</b>. İlk ek ana resmi, ikinci ek ise küçük resmi tanımlar.",
        "div17": "Ekleri olmayan detay servisleri için resim ve küçük resim alanları zorunlu, ekleri olan detay servisleri içinse isteğe bağlıdır (ancak özellikle önerilir). Serviste ekler etkinleştirilmişse, derleyici resimleri ekler olarak yüklemenize izin verir. Değilse, resmin ve küçük resmin URL'lerini düzenleyebilirsiniz.",
        "div172": "Mevcut olduğunda resim ve küçük resim alanları her zaman kullanılır ve detay servisi ekleri sorgulanmaz.",
        "div173": "Örnek CSV'ler ve shapefile'lar şuradan indirilebilir:",
        "div18": "CSV'den veya shapefile'dan barındırılan bir Detay Servisi oluşturma",
        "div19": "CSV veya shapefile dosyasından barındırılan bir detay servisi oluşturduğunuzda, ekler varsayılan olarak etkinleştirilmez. Bunları etkinleştirmek için detay servisinin sayfasını açıp katman bölümündeki küçük oka tıklarsanız, bu seçeneği görürsünüz. Harita Turu öznitelikler yoluyla başvurduğunuz resimleri ve küçük resimleri kullanmaya devam eder. Resimlerinizi detay servisi ekleri olarak karşıya yüklemek isterseniz, resim panelindeki iki düğme (\"Resmi Değiştir\" ve \"Küçük Resmi Değiştir\") yoluyla bunu yapabilirsiniz.",
        "div20": "Desteklenen resim formatları ve videolar",
        "div21": "Desteklenen resim formatları şunlardır: <b>.jpg, .jpeg, .png, .gif ve .bmp</b>. Medyanız bu uzantıyla bitmiyorsa, Harita Turu bunu, bir detay servisi kullandığı durumlar dışında video olarak kabul eder (aşağıya bakın).",
        "div22": "Harita Turu şablonu bir video oynatıcısı içermez, bu yüzden favori video barındırma servisinizin sağladığı harici video oynatıcısını kullanmanız gerekir. (Videoyu katıştırma seçeneğini bulun ve verili koddaki URL'yi kopyalayın.) Videoyu kendiniz barındırmak isterseniz, <a href='http://www.videojs.com/'>Video.js</a> gibi bir video oynatıcı içeren bir HTML sayfası oluşturabilirsiniz.",
        "div23": "Ekleri olan detay servisleri kullanılırken etkileşimli derleyici video dahil etmek için bir iletişim kutusu sunmaz, ancak verilerinizi etkileşimli derleyicinin dışında düzenleyerek bunu yapabilirsiniz. Arcgis.com harita görüntüleyicisinde, resim alanlarını harici bir videoya işaret edecek şekilde değiştirir ve URL'nizin sonuna özel bir parametre (#isVideo) eklerseniz, medyanızın bir video olduğu kabul edilir.",
        "div24": "İki geçerli resim ekiniz olması gerektiğine, aksi halde noktanın kullanılamayacağına dikkat edin. Resim ve küçük resim alanları olmadan, detay servisi ekleri kullanılırken video kullanmak mümkün değildir."
      },
      "tab3": {
        "title": "Özelleştirme",
        "div1": "Derleyici, üst paneldeki AYARLAR düğmesi ile erişilebilen birkaç özelleştirme seçeneği sunar. Beklediğiniz seçeneği bulamazsanız, web sunucunuza kurabileceğiniz ve ihtiyaçlarınıza uyacak şekilde geliştirebileceğiniz indirilebilir bir sürümünü de sağlıyoruz.",
        "div2": "Şunlar olmadıkça barındırılan sürümü kullanmanızı öneririz:",
        "div3": "<li>Üstbilgi arka plan görüntüsünü kullanma gibi istediğiniz bir kullanıcı arayüzü özelleştirme olanağı sunmuyor.</li><li>Bir geliştiricisiniz ve uygulamayı geliştirmek istiyorsunuz.</li>",
        "div4": "İndirilebilen sürüm bir web haritası veya bir web haritalama uygulaması tanımlayıcısı yoluyla yapılandırılabilir. Ana kullanım örnekleri şunlardır:",
        "div41": "Harita turunuzu barındırmalı ortamdaki etkileşimli derleyiciyi kullanarak derliyor ve şablonu web haritalama uygulaması tanımlayıcısıyla yapılandırıyorsunuz. Etkileşimli derleyici ile tanımladığınız ayarlar uygulanır.",
        "div42": "Web haritanızı etkileşimli derleyici dışında derliyor ve şablonu web harita tanımlayıcısı ile yapılandırıyorsunuz. Şablonun nasıl yapılandırılacağını öğrenmek için belgeleri okumanız gerekir.",
        "div43": "Etkileşimli derleyicinin, 10. sürümden daha eski Internet Explorer gibi tarayıcılarda bazı teknik kısıtlamalar olmak kaydıyla  indirilebilir bir sürümünün bulunduğunu unutmayın.",
        "div5": "Şablonun en son sürümünü indirmek ve nasıl kullanılacağı hakkında daha fazla bilgi almak için <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub proje sayfasını</a> ziyaret edin."
      },
      "tab4": {
        "title": "İpuçları",
        "div0": "Desteklenen tarayıcılar",
        "div0a": "Harita Turu görüntüleyicisi IE8+'da desteklenmektedir. Etkileşimli derleyici IE9+'da desteklenmektedir. Derleyiciyi tüm tarayıcılarda aktif olarak test ediyoruz ancak güçlüklerle karşılaşırsanız, Chrome'u kullanmanızı öneririz.",
        "div0b": "Bazı güçlüklerle karşılaşırsanız, bize bildirin. Bu arada, Harita Turunuzu CSV şablonunu kullanarak derleyerek derleyici arayüzüyle etkileşiminizi en aza indirmiş olursunuz.",
        "div1": "Görüntüler",
        "div2": "Her ne kadar tek bir Harita Turunda farklı boyut, şekil ve yönde görüntüler kullanılabiliyor olsa da dikey yerine yatay görüntüler kullanılmasını tavsiye ediyoruz. 4:3 en boy oranına sahip görüntüler en uygun olanlarıdır. Resim yazısı ile görüntünün üst üste bindiği Üç Panelli ve Entegre şablonlarda dikey görüntüler kullanıldığında, görüntünün bir kısmı resim yazısının altında kalır. Üç Panelli ve Entegre şablonlarda, mümkün olduğunda tüm görüntüler için aynı boyut ve şekli kullanmanızı tavsiye ediyoruz. Böylece farklı boyutlarda görüntüler, tura devam eden kullanıcının dikkatini dağıtmaz.",
        "div2a": "Ana resimlerde maksimum 1000 piksel genişlik x 750 piksel yükseklik, küçük resimlerde 140x93 boyut öneriyoruz.",
        "div3": "Altyazı metninizi HTML etiketleriyle formatlama",
        "div4": "Format ve bağlantıları tanımlamak için resim yazılarınıza HTML etiketlerini girebilirsiniz. Örneğin, bu etiketler yeşil bir köprü bağlantısı ekler:",
        "div4a": "Turunuz için uygun altyazı yazın",
        "div4b": "Turunuza ilgi çekici bir altyazı yazmak için zaman ayırın. Altyazı, insanları turunuza çekmek ve içinde neler keşfedeceklerini anlatmak için iyi bir yoldur. Ayrıca, seyircinize turun yapıldığı bölge veya ülke hakkında bilgi vermek için iyi bir seçenektir. Örneğin, insanların turunuzun gerçekleştiği şehir veya kasabanın yerini bilmediklerini farz edelim. Altyazıyı fazla uzun tutmayın. Aklınıza iyi bir altyazı gelmediğinde, boş bırakın. Yan panel şablonunda kapak sayfasında görünen altyazı, turunuzun ilk noktasının resim yazısıdır (ilk noktanın içeriğini kapak sayfası olarak kullanmak için Düzenle iletişim kutusundaki seçeneği kullanıyorsanız).",
        "div5": "Katmanları Destekleme",
        "div6": "Harita Turuna içerik sağlamak için ek destek katmanları ekleyebilirsiniz. Bu katmanlar, haritanın Harita Turu noktalarına ek olarak göstermesini istediğiniz, bir çalışma alanı, tur noktalarınızı bağlayan bir yürüyüş veya sürüş rotası gibi farklı coğrafi detaylar içerebilir. Harita Turu şablonu, web haritasında belirttiğiniz sembolojiyi kullanan ek destek katmanlarını görüntüler ancak açılır pencereler kullanılmaz. Turunuza destek katmanları eklemek için işinizi kaydedin ve Harita Turu Oluşturucu'yu kapatın. Ardından turunuzda kullanılan web haritasını açın. Bunu ArcGIS My Content'te veya Story Maps web sitesinin Hikayelerim bölümünde bulabilirsiniz.",
        "div7": "Turunuz kısa ve çekici olsun",
        "div8": "Tur başına 99 noktalık bir sınırlama vardır. Çoğu Harita Turu tabii ki bundan önemli ölçüde daha kısa olacaktır. İzleyici kitlenizin bir sürü tur noktasını adım adım gezmesini beklemeyin. Konunuz size çok ilginç gelebilir, ancak izleyicinizin de çok ilginç bulacağını varsaymayın!",
        "div10": "Katıştırma modu",
        "div11": "Şablonu bir iFrame aracılığıyla başka bir web sitesine yerleştirmek isterseniz, URL'nin sonuna ek olarak \"&embed\" parametresini eklemek, başlığı kaldıracaktır.",
        "div12": "Harita turunun hassas küçük ekran dokunmatik düzenine geçmesine neden olacak dar bir iFrame genişliği kullanmaktan kaçının. Bir harita turu oluşturduğunuzda, kullanım kolaylığını en üst düzeye çıkarmak amacıyla kullanıcıların turu tam ekran olarak başlatabilmesi için gömülü turun yanında bir bağlantı sağlamanızı tavsiye ediyoruz."
      },
      "tab5": {
        "title": "Yayınlama",
        "div1": "İşiniz bittiğinde Harita Turunuzu PAYLAŞ düğmesiyle veya ArcGIS Online'daki uygulama öğesi sayfası üzerinden izleyici kitlenizle paylaşmayı unutmayın.",
        "div2a": "Turu derleyici üzerinden paylaşma",
        "div2b": "PAYLAŞ düğmesi uygulamayı ve web haritası öğelerini günceller. Tur verileriniz bir Detay Servisi öğesinde depolanıyorsa, o da güncellenir. ArcGIS.com harita görüntüleyici yoluyla başka katmanlar eklediyseniz, bunlar güncellenmez. Bu, Tur'un beklediğiniz gibi paylaşılmamasıyla sonuçlanabilir. Gerekli (veya daha fazla) ayrıcalıklara zaten sahip olan öğeler güncellenmez.",
        "div2c": "Turu ArcGIS Online yoluyla paylaşma",
        "div2d": "Uygulamayı ArcGIS Online sitesi üzerinden paylaştığınızda, sizden gerekirse aynı şekilde paylaşılmayan bağımlı kaynakları (web haritası, detay servisi, dekorasyon katmanı) güncellemenizi ister. Harita Turu herkese açıksa ve kaynaklarınızdan biri kitlenizle paylaşılmıyorsa, kullanıcılar ArcGIS Online oturum açma sayfasına yönlendirilir.",
        "div3t": "Detay Servisi güvenliği",
        "div3a": "Harita Turu derleyicisi ile oluşturulmuş barındırılan bir detay servisi kullanıyorsanız, uygulama sizin için servis güvenliğini yönetir ve servisi herkesle paylaşsanız bile düzenleme ayrıcalıklarına sahip tek kişi olmayı sürdürürsünüz.",
        "div3t2": "Turunuzu izleyici kitlenizle paylaşmadan önce",
        "div3": "Turunuzun ArcGIS.com hesabınızla oturum açmadığınızda da düzgün çalıştığından emin olun. Kullanacağınız URL izleyiciyi bir oturum açma sayfasına veya derleyici moduna yönlendirmemelidir.",
        "div4": "Turunuzun yatay yönlendirmede tutulan bir iPad'de nasıl göründüğüne bakmak, bu popüler cihazda düzgün göründüğünden emin olmak için iyi bir fikirdir. Bu, altyazılarınızın resimleri çok fazla örtmediğinden emin olmanıza yardımcı olabilir. Ayrıca, altyazınızın ekrana sığıp sığmadığını ve kırpılmasına neden olacak kadar uzun olup olmadığını görmenize izin verir.",
        "div5a": "Arama için öneri",
        "div5b": "İnsanların ArcGIS Online'da arama yaptıklarında Harita Turunuzu bulmasına yardımcı olmak için harita turunuzun uygulama öğesi sayfasına (web haritanızın öğe sayfasına değil) 'story map' etiketini, bunun yanı sıra da turun yapıldığı eyaletin veya ilin adı, ABD dışındaysa ülkenin adı ve 'public art', 'tourist guide' veya 'historic places' gibi tema etiketlerini eklemenizi öneririz. Bu etiketler, ayrıca, Esri'de bize de galerilerimizde gösterebileceğimiz ve sosyal medyada tanıtabileceğimiz güzel yeni tur örnekleri bulmamız için yardımcı olur. Ayrıca, uygulama öğesi sayfanıza turun küçük bir ekran resmi veya içindeki resimlerden biri gibi hoş duran bir küçük resim grafiği yüklemenizi de öneririz. Harita turunuz bir ArcGIS Online galerisine eklenirse, otomatik olarak bu resim kullanılır."
      }
    },
    "share": {
      "firstSaveTitle": "Tur kaydedildi",
      "manageStory": "Hikayenizi yönetin",
      "manageStoryA1": "İpucu: Hikayenizdeki hataları denetlemek için %LINK1% öğesini kullanabilir ve bileşenlerinin paylaşılma durumunu değiştirebilirsiniz. Hikayelerim de sosyal ağlarda paylaşılan hikayenizi daha iyi görüntülemenize yardım edebilir. Hikayelerim özelliğinin diğer yararlı işlevleri hakkında şuradan daha fazla bilgi edinebilirsiniz: %LINK2%.",
      "manageStoryA1V1": "Hikayelerim",
      "manageStoryA1V2": "blog gönderileri",
      "shareTitle": "Turunuzu Paylaşın",
      "sharePrivateHeader": "Turunuz paylaşılmıyor, paylaşmak ister misiniz?",
      "sharePrivateBtn1": "Herkesle paylaş",
      "sharePrivateBtn2": "Kuruluşumla Paylaş",
      "sharePrivateProgress": "Paylaşma sürüyor...",
      "sharePrivateErr": "Paylaşma başarısız, tekrar deneyin veya",
      "sharePrivateOk": "Paylaşma güncellendi, yükleniyor...",
      "sharePreviewAsUser": "Önizleme",
      "shareHeader1": "Turunuza <strong>herkes erişebilir</strong>.",
      "shareHeader2": "Turunuza kuruluşunuzun üyeleri erişebilir. (Oturum açılması gerekir.)",
      "shareLinkHeader": "Turunuzu Paylaşın",
      "shareLinkOpen": "AÇ",
      "shareA1": "<a href='%LINK1%' target='_blank'>uygulama öğesi sayfasındaki %SHAREIMG% öğesini kullanın</a>. Ayrıca, web haritasını paylaşmayı kaldırmak isterseniz, <a href='%LINK2%' target='_blank'>web haritası öğe sayfasını kullanın</a>.",
      "shareWarning": "%WITH% ile paylaşma devre dışı bırakıldı çünkü <a href='%LINK%' target='_blank'>web haritasının</a> sahibi değilsiniz.",
      "shareWarningWith1": "genel ile",
      "shareWarningWith2": "genel ve Kuruluş ile"
    },
    "locator": {
      "error": "Konum kullanılamıyor"
    },
    "saveErrorSocial": {
      "title": "Sosyal medya paylaşma güncellemesi",
      "panel1": "Hikayenizin sosyal medyadaki görünümü iyileştirildi, ancak ArcGIS web uygulaması öğenizin başlığı hikaye başlığınızla aynı değil.",
      "panel1tooltip": "Bir başlık, özet ve küçük resim tanımlandıktan sonra hikayeniz şöyle görüntülenir:",
      "panel2": "Sosyal medyada hangi başlığı kullanmak istersiniz?",
      "panel2q1": "Hikaye başlığı (önerilen)",
      "panel2q1tooltip": "Bu seçeneği tercih ettiğinizde, öğenizin başlığı hikaye başlığınızla eşleşecek biçimde değiştirilir ve oluşturucudaki ilave değişiklikler senkronize edilir.",
      "panel2q2": "Öğe başlığı",
      "panel3": "Hikayenizin sosyal medyada görüntülenme biçimini daha da iyileştirmek için ${MYSTORIES} kullanarak bir özet ve küçük resim ekleyin.",
      "panel4": "Bu hikaye için beni bir daha uyarma",
      "mystories": "Hikayelerim",
      "btnSave": "Kaydet"
    },
    "bannerNotification": {
      "learnMore": "Daha Fazla Bilgi",
      "close": "Kapat",
      "dontShowAgain": "Bu iletiyi tekrar gösterme"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Web Güvenliği ve Story Maps hakkında Önemli İleti",
      "s1h1": "Esri, Story Maps'in güvenliğini geliştiriyor",
      "s1p1": "Story Maps'iniz web'de yayınlanır ve web topluluğu her zaman daha iyi güvenlik sağlamak ve uygulamak için çalışmaktadır. İnternet üzerinden iletilen içerik için güvenli bir bağlantı sağlayan HTTPS, web içeriğine erişmenin birincil yolu olarak kullanılmaktadır. Çoğu modern tarayıcı artık, HTTPS yerine HTTP kullanıldığında uyarı mesajları göstermektedir. Bu yeni geliştirilen standart nedeniyle Haziran 2018 ArcGIS Online güncellemesinden itibaren Story Maps'te HTTPS kullanılması gerekecektir.",
      "s1p2": "Pratik olarak bu, bir Story Map demektir ve tüm içeriğine (görüntüler, katmanlar, gömülü uygulamalar ve web siteleri dahil) HTTP yerine HTTPS ile başlayan bağlantılar kullanılarak erişim sağlanmalıdır. Bu, okuyucularınız için en iyi deneyimi sağlar; çünkü çoğu web tarayıcısında bu, hikayelerinizin güvenli olduğu anlamına gelir.",
      "s2h1": "Ne yapmam gerekiyor?",
      "s2p1": "Esri, Story Map yazarları ve okuyucuları için bu geçişi kolaylaştırmaya çalışmaktadır. Artık Story Map oluşturucuları ve Hikayelerim'de, hikayelerinizdeki güvensiz içeriği (HTTP) bulmanıza yardımcı olacak ve bunları nasıl ele alacağınıza dair tavsiyelerde bulunacak araçlar mevcuttur. Lütfen hikayenizi güvenli olmayan içeriklere karşı kontrol edin ve Haziran 2018'den önce HTTPS'ye güncelleyin.",
      "action1": "Kapat",
      "action2": "Hikayelerimi şimdi kontrol et",
      "action3": "Daha fazla bilgi"
    }
  }
});