define(
	 ({
		viewer: {
			loading: {
				step1: "UYGULAMA YÜKLENİYOR",
				step2: "VERİLER YÜKLENİYOR",
				step3: "TUR BAŞLATILIYOR",
				loadBuilder: "DERLEYİCİ MODUNA GEÇİLİYOR",
				redirectSignIn: "OTURUM AÇMA SAYFASINA YÖNLENDİRİLİYOR",
				redirectSignIn2: "(oturum açtıktan sonra buraya yeniden yönlendirileceksiniz)",
				fail: "Üzgünüz, Harita Turu yüklenemedi",
				failButton: "Tekrar dene"
			},
			errors: {
				boxTitle: "Bir hata oluştu",
				portalSelf: "Onarılamaz hata: Portal yapılandırması alınamadı",
				invalidConfig: "Onarılamaz: Geçersiz yapılandırma",
				invalidConfigOwner: "Onarılamaz hata: Geçersiz yapılandırma (yetkili sahip gerekiyor)",
				invalidConfigNoWebmap: "Onarılamaz hata: Geçersiz yapılandırma (web harita veya uygulama tanımlayıcısı index.html dosyasında belirtilmemiş)",
				createMap: "Harita oluşturulamıyor",
				invalidApp: "Onarılamaz hata: Uygulama yüklenemiyor",
				noLayer: "Web haritası Harita Turu için geçerli bir veri katmanı içermiyor.",
				noLayerMobile: "Harita Turu web uygulamasına hoş geldiniz. Uygulama yapılandırılmadı. Harita Turu derleyicisi mobil cihazlarda desteklenmiyor.",
				noLayerView: "Harita Turu web uygulamasına hoş geldiniz.<br />Uygulama henüz yapılandırılmadı.",
				appSave: "Web uygulamasını kaydederken hata oluştu",
				mapSave: "Web haritasını kaydederken hata oluştu",
				featureServiceLoad: "Detay servisi yüklenirken hata oluştu",
				notAuthorized: "Bu uygulamaya erişim yetkiniz yok",
				oldBrowserTitle: "Tarayıcı tam olarak desteklenmiyor",
				noBuilderIE8: "Harita Turu derleyicisi 9. sürümden önceki Internet Explorer\'da desteklenmemektedir.",
				ie10Win7Explain: "Veri kaynağı ekleri olan bir Detay Servisi olduğunda, Harita Turu etkileşimli derleyicisi Windows 7\'de Internet Explorer 10\'da desteklenmez. Ekleri olan bir Detay Servisi kullanmak için <a target='_blank' href='http://msdn.microsoft.com/tr-tr/library/ie/hh920756(v=vs.85).aspx'>belge modunu Internet Explorer 9 standartlarına el ile zorlamalı</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>Internet Explorer 9\'ı geri yüklemeli</a> veya Windows 8\'e yükselmelisiniz.",
				oldBrowserExplain: "Bu tarayıcı, harita turunuza yüklediğiniz görüntülerden otomatik küçük resim oluşturmayı desteklemiyor. Bu tarayıcıyı kullanarak bir harita turu oluşturabilirsiniz, ancak yüklediğiniz her görüntü için ayrı bir küçük resim görüntüsü sağlamanız gerekir.",
				oldBrowserExplain2: "Deneyiminizi iyileştirmek için, <a href='http://browsehappy.com/' target='_blank'>tarayıcınızı yükseltin</a> veya <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>Google Chrome Frame for Internet Explorer\'ı etkinleştirin</a>.",
				oldBrowserExplain3: "Harita Turu derleyicisi Windows XP\'de Internet Explorer 10 ile çalışmaz.",
				oldBrowserClose: "Kapat"
			},
			mobileHTML: {
				showIntro: "BAŞLIĞI GÖSTER",
				hideIntro: "BAŞLIĞI GİZLE",
				navList: "Liste",
				navMap: "Harita",
				navInfo: "Medya",
				introStartBtn: "Başlangıç"
			},
			desktopHTML: {
				storymapsText: "Bir öykü haritası",
				builderButton: "Derleyici moduna geç",
				bitlyTooltip: "Uygulamaya bir kısa bağlantı alın",
				bitlyStartIndex: "Geçerli yere bağlantı kur"
			},
			builderHTML: {
				panelHeader: "UYGULAMA YAPILANDIRMASI",
				buttonSave: "KAYDET",
				buttonSettings: "Ayarlar",
				buttonShare: "Paylaş",
				buttonView: "Modu görüntüle",
				buttonItem: "Web Uygulaması öğesini açın",
				buttonHelp: "Yardım",
				buttonOrganize: "Düzenle",
				buttonAdd: "Ekle",
				buttonImport: "İçe Aktar",
				buttonImportDisabled: "Ekleri olan bir Detay Servisi kullanılırken içe aktarma kullanılamaz",
				dataEditionDisabled: "Veri düzenleme CSV veri kaynağında devre dışıdır",
				dataSourceWarning: "Harita Turu veri katmanı değişmiş. Detay tanımlayıcısı aynı değilse, <b>Düzenle</b> yoluyla sırayı ve gizli noktaları sıfırlamanız gerekir. Alanın adı farklıysa, <b>Ayarlar\'daki veri sekmesi</b> altından alanın ayarlarını sıfırlamalısınız.",
				organizeWarning: "Etkileşimli derleyicinin dışına eklenmiş bir veya daha fazla nokta gizli.",
				dataPicError0a: "Bu turda <b>%NB%</b> adet uyumsuz resim URL\'si bulunur.",
				dataPicError0b: "Bu turda <b>%NB%</b> adet uyumsuz resim URL\'si bulunabilir.",
				dataPicError1: "Harita Turu artık bir resim URL\'sinin şu uzantılardan biriyle bitmesini gerektirmektedir: .jp(e)g, .png, .gif veya .bmp.",
				dataPicError2: "Bu gereksinim, mevcut yayınlanmış Harita Turunuzu etkilemeyecek. Ancak, etkileşimli derleyiciyi kullanabilmek için, önce şu işlemlerden birini yaparak URL sorununu çözmeniz gerekir:",
				dataPicError3: "URL\'leri Düzenle",
				dataPicError4: "Bu desteklenmeyen resim URL\'lerinin sonuna <i>#isImage</i> ifadesini ekler. Sunucuların çoğu URL eklemelerini destekler. Ancak, bu işlemi bir kez yaptıktan sonra, noktalarınızda gezinerek güncellenmiş resim URL\'lerinin çalıştığından emin olmanız gerekir. Resimlerin tümü yükleniyorsa, artık Harita Turu\'nu kaydedebilirsiniz. <b>Resimlerin bağlantısı kopuksa, Harita Turu\'nu kaydetmeyin</b>. Bunun yerine ikinci işlemi yapmak için derleyiciyi tekrar yükleyin.",
				dataPicError5: "Turu resimlerle sınırla",
				dataPicError6: "Bu seçenek tüm URL\'lerin görüntü olarak kabul edilmesine neden olur, ancak etkileşimli derleyiciyi kullanarak video ekleyemezsiniz. Bu işlem, gelecekte video eklemeye karar vermeniz durumunda geri alınabilir.",
				dataPicError7: "Harita Turu resimlerle sınırlandı, video kullanılamaz. Bu sınırlamayı kaldırmayı seçerseniz, Harita Turu\'nu kaydetmeden önce resimlerin hala yüklendiğinden emin olun. Gerekirse ileride bu sınırlamayı tekrar devreye sokabilirsiniz.",
				dataPicError8: "Resim sınırlamasını kaldır",
				dataPicError9: "Bu URL\'ler videolara işaret ediyorsa, bu uyarıyı yoksayabilirsiniz; görüntülere işaret ediyorsa, şu iki işlemden birini yapmanız gerekir:",
				modalCancel: "İptal",
				modalApply: "Uygula",
				organizeHeader: "Turu düzenle",
				organizeGeneralCaption: "Tur noktalarını düzene sokmak için sürükle-bırak kullan",
				organizeDelete: "Sil",
				organizeHide: "Gizle",
				organizeReset: "Sırayı ve gizli noktaları sıfırla",
				addMaxPointReached: "Simge setinin izin verdiği maksimum nokta sayısına ulaştınız ve başka bir tur noktası ekleyemezsiniz.<br /><br />Mevcut noktaları silerseniz, uygulamayı yeniden yüklemeniz gerekeceğini unutmayın.",
				addMaxPointReachedMobile: "Üzgünüz, izin verilen maksimum nokta sayısına ulaştınız ve bu resmi ekleyemezsiniz.",
				addClose: "Kapat",
				addHeader: "Yeni bir tur noktası ekle",
				addTabPicture: "Medya",
				addTabInformation: "Bilgi",
				addTabLocation: "Konum",
				addSelectCaption: "Resim seç veya bırak",
				addNoteVideo: "Video kullanma hakkında talimatlar için Yardım\'a başvurun",		
				addSelectCaptionNoFileReader: "Resim seç",	
				addChangePhoto: "Resmi ve küçük resmi değiştir",
				addPictureResolutionIntro: "Resim çözünürlüğü gerekenden daha fazla:",
				addPictureResolutionOldBrowser: "Resim çözünürlüğü gerekenden daha yüksek. %RECOMMENDED_RES% üzerinde bir çözünürlük belirterek Harita Turu deneyimini optimize edin.",
				addPictureResolutionResize: "Resim çözünürlüğünü %RESOLUTION% olarak değiştir",
				addPictureResolutionKeep: "%RESOLUTION% olan ilk çözünürlüğü koru",
				addSelectThumbnail: "Küçük resmi seç",
				addNoThumbSelected: "Hiçbir küçük resim seçilmedi",
				addThumbSelected: "Seçildi",
				addCameraSettingsHeader: "KAMERA AYARLARI",
				addThumbnailHeader: "KÜÇÜK RESİM",
				addLabelPicUrl: "Resim",
				addLabelThumbUrl: "Küçük Resim",
				addTextPlaceholderUrl: "Görüntü URL\'si girin",
				addTextPlaceholderUrl2: "YouTube sayfa URL\'si girin",
				addTextPlaceholderUrl3: "Vimeo sayfa URL\'si girin",
				addTextPlaceholderUrl4: "Video katıştırma URL\'si girin",
				addLabelVideo: "Video",
				addMediaVideoOther: "Diğer",
				addMediaVideoHelp: "URL\'yi denetleyin ve varsayılan küçük resmi alın",
				addMediaVideoHelpTooltip1: "Denetim başarılı",
				addMediaVideoHelpTooltip2: "Denetim başarısız",
				addMediaVideoHelpTooltip4: "Videoyu katıştırma seçeneğini bulun ve koddaki video URL\'sini kopyalayın",
				addLabelName: "Ad",
				addLabelDescription: "Altyazı",
				addTextPlaceholder: "Birşey yazın",
				addLocatePlaceholder: "Bir adresi veya yeri bulun",
				addPinColor: "Renk",
				addLatitude: "Enlem",
				addLongitude: "Boylam",
				addLatitudePlaceholder: "ör. 34.056",
				addLongitudePlaceholder: "ör. -117.195",
				addUploading: "Tur noktası yükleniyor",
				addSave: "Tur noktası ekle",
				addMobileUploading: "Resim yükleniyor",
				addMobileName: "Ad girin",
				addMobileNameMandatory: "Hata; ad girin.",
				addMobileError: "Üzgünüz, yanlışlık oldu",
				settingsHeader: "Uygulama ayarları",
				settingsTabLayout: "Düzen",
				settingsTabColor: "Renkler",
				settingsTabLogo: "Üstbilgi",
				settingsTabFields: "Veri",
				settingsTabExtent: "Yayılım",
				settingsTabZoom: "Yakınlaştırma Düzeyi",
				settingsLayoutExplain: "İstediğiniz uygulama düzenini seçin.",
				settingsLayoutProfessional: "Üç Panelli Düzen",
				settingsLayoutModern: "Entegre Düzen",
				settingsLayoutSelected: "Seçili düzen",
				settingsLayoutSelect: "Bu düzeni seç",
				settingsLayoutNote: "Video kullanan noktalarda, seçenek işaretlenmese bile döviz her zaman videonun altına yerleştirilir.",
				settingsLayoutLocBtn: "\'Bul\' düğmesi ekle",
				settingsLayoutLocBtnHelp: "Bu işlevsellik çoğu mobil cihazda ve masaüstü tarayıcıda (Internet Explorer 9) desteklenir.",
				settingsColorExplain: "Önceden tanımlı bir tema seçerek veya kendi temanızı oluşturarak görünümü değiştirin.",
				settingsLabelColor: "Üstbilgi, içerik ve altbilgi renkleri",
				settingsLogoExplain: "Üstbilgi logosunu özelleştirin. (Maksimum 250 x 50 px\'tir.).",
				settingsLogoEsri: "Esri logosu",
				settingsLogoNone: "Logo yok",
				settingsLogoCustom: "Özel logo",
				settingsLogoCustomPlaceholder: "Görüntü URL\'si",
				settingsLogoCustomTargetPlaceholder: "Tıklanabilir bağlantı",
				settingsLogoSocialExplain: "Üstbilgi üst sağ bağlantısını özelleştirin.",
				settingsLogoSocialText: "Metin",
				settingsLogoSocialLink: "Bağlantı",
				settingsLogoSocialDisabled: "Bu özellik Yönetici tarafından devre dışı bırakıldı",
				settingsDataFieldsExplain: "Fotoğraf adını, altyazısını ve renk alanlarını seçin.",
				settingsDataFieldsError: "Uygulama uygun ad, altyazı veya renk verilerini belirleyemiyor. Kullanılacak alanları burada seçin. Bu ayarlar daha sonra değiştirilebilir.",
				settingsFieldsLabelName: "Ad",
				settingsFieldsLabelDescription: "Altyazı",
				settingsFieldsLabelColor: "Renk",
				settingsFieldsReset: "Alan seçimini sıfırla",
				settingsExtentExplain: "Harita Turu ilk yayılımını aşağıdaki etkileşimli haritayla ayarlayın.",
				settingsExtentExplainBottom: "Tanımladığınız yayılım web haritanızın ilk yayılımını değiştirecek. İlk tur noktasını içermiyorsa, bu yayılımın kullanılmadığına dikkat edin. Bu durumda tur ilk noktayı merkez alarak başlar.",
				settingsExtentDateLineError: "Yayılım 180Â° boylam meridyeninden geçemez",
				settingsExtentDateLineError2: "Yayılımı hesaplanırken hata oluştu",
				settingsExtentDrawBtn: "Yeni bir yayılım çiz",
				settingsExtentModifyBtn: "Yayılımı düzenle",
				settingsExtentApplyBtn: "Harita Turunda Önizle",
				settingsExtentUseMainMap: "Harita Turu yayılımını kullan",
				settingsZoomExplain: "Girişten sonraki öykü noktalarının yakınlaştırmasını ayarlayın (isteğe bağlı).",
				settingsLabelZoom: "Ölçek/düzey",
				settingsZoomFirstValue: "Hiçbiri",
				settingsFieldError: "Her listeden bir alan seçin",
				dataTitle: "ArcGIS Online barındırma",
				dataExplain: "Web haritanıza detay servisi eklenecek. Kimseyle paylaşılmayacak ve yalnızca siz ayrıcalık ekleyecek, düzenleyecek ve sileceksiniz.<br /><br />Uygulamayı öğe sayfası üzerinden paylaşırsanız, sistemin Detay Servisi\'ni paylaşmak isteyip istemediğini soracağına dikkat edin. Bu, gerekli bir adımdır. Ayrıcalık düzenleyen tek kişi olmaya devam edeceksiniz.",
				dataNameLbl: "Servis adı",
				dataFolderListLbl: "Klasör",
				dataFolderListFetching: "Klasörler alınıyor ...",
				dataRootFolder: "Kök",
				dataNameError: "Detay servisi için ad girin",
				dataFolderError: "Geçerli bir klasör seçin",
				dataSrcContainsInvalidChar: "Detay servisi adı bir veya daha fazla geçersiz karakter (-, <, >, #, %, :, \", ?, &, +, / veya \) içeriyor.",
				dataSrvAlreadyExistsError: "Bu ada sahip bir servis adı kuruluşunuzda zaten var. Farklı bir ad seçin.",
				dataBtnSave: "Servisi oluştur",
				dataFooterProgress: "Oluşturma sürüyor",
				dataFooterSucceed: "Oluşturma başarılı. Yükleniyor",
				dataFooterError: "Oluşturma başarısız. Tekrar deneyin",
				tabError: "Tüm sekmelerdeki hataları kontrol etin",
				introRecordBtn: "Giriş",
				introRecordActivate: "İlk noktayı giriş olarak kullanın (döner sistemde görünmez)"
			},
			addPopupJS: {
				uploadingPicture: "Resim yükleniyor",
				uploadSuccess: "Yükleme başarılı",
				uploadError: "Resim yüklenirken hata oluştu",
				uploadError2: "Detay eklenirken hata oluştu (geçersiz html etiketi)",
				notJpg: "Yüklenecek jpeg uzantılı fotoğraf seçin",
				errorNoPhoto: "Yüklenecek bir görüntü seçin",
				errorNoThumbnail: "Yüklenecek bir küçük resim seçin",
				errorInvalidPicUrl: "Geçerli resim girin. (http(s):// ile başlamalı, jpg, png, gif veya bmp ile bitmelidir.) Bu kuralı geçersiz kılmak için URL\'yi \'#isImage\' ile bitirebilirsiniz.",
				errorInvalidThumbUrl: "Geçerli bir küçük resim girin. (http(s):// ile başlar, jpg, png, gif veya bmp ile biter.)",
				errorInvalidVideoUrl: "Geçerli bir video URL\'si girin (http(s):// ile başlar)",
				errorNoName: "Bu tur noktası için ad girin",
				errorNoDescription: "Bu tur noktası için altyazı girin",
				errorNoLocation: "Bu tur noktası için konum belirleyin"
			},
			builderJS: {
				noPendingChange: "Kaydedilmemiş değişiklik yok",
				unSavedChangeSingular: "Kaydedilmemiş 1 değişiklik var",
				unSavedChangePlural: "kaydedilmemiş değişiklikler",
				shareStatus1: "Tur kaydedilmedi",
				shareStatus2: "Tur herkes ile paylaşılıyor",
				shareStatus3: "Tur kuruluş ile paylaşılıyor",
				shareStatus4: "Tur paylaşılmıyor",
				popoverDiscard: "Kaydedilmemiş değişiklerden vazgeçmek istediğinizden emin misiniz?",
				yes: "Evet",
				no: "Hayır",
				popoverLoseSave: "Görüntüleyiciyi açarsanız, kaydedilmemiş değişiklikleri kaybedeceksiniz",
				ok: "Tamam",
				popoverSaveWhenDone: "İşiniz bittiğinde kaydetmeyi unutmayın",
				closeWithPendingChange: "Eylemi onaylamak istediğinizden emin misiniz? Değişiklikleriniz kaybolacak.",
				gotIt: "Tamam",
				savingApplication: "Uygulama kaydediliyor",
				saveSuccess: "Uygulama başarıyla kaydedildi",
				saveError: "Kaydetme başarısız; tekrar deneyin",
				saveError2: "Addaki veya açıklamadaki geçersiz bir html etiketi nedeniyle kaydetme başarısız oldu",
				saveError3: "Başlık boş olamaz",
				dragColorPicker: "Beni gezdirin<br />veya rengimi değiştirin",
				dataWarningExtent: "Web haritası yayılımının dışında verileriniz var. Bu veriler tur noktaları olarak kullanılmayacak, bunları kullanmak istiyorsanız harita yayılımını değiştirin.",
				dataWarningVisibi: "Harita Turu katmanınız geçerli web haritası yayılımında görünmüyor. Harita Turu katmanınızın %MAPSIZE% büyüklükte bir haritada görünür olduğunu doğrulayın.",
				dataWarningEdit: "Web haritasını düzenle",
				dataWarningClose: "Kapat",
				signIn: "Uygulamayı kaydetmek için",
				signInTwo: "üzerindeki başka bir hesap ile oturum açın.",
				switchBM: "Harita Altlığını Değiştir"
			},
			organizePopupJS: {
				messageStart: "Silmeyi seçtiniz",
				messageSinglePoint: "tek tur noktası",
				messageMultiPoint: "tur noktaları",
				messagePermantRemove: "Bu işlem, veri tabanınızdan",
				messageRecord: "kaydı",
				messageRecordPlural: "kayıtları",
				messageConfirm: "kalıcı olarak silecek. Devam etmek istiyor musunuz?",
				labelButtonShow: "Göster",
				labelButtonHide: "Gizle"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Bu, resmi veya küçük resmi kalıcı olarak silecek",
				popoverDeleteWarningThumb: "Bu, küçük resmi kalıcı olarak silecek",
				popoverUploadingPhoto: "Resim veya küçük resim yükleniyor",
				popoverUploadingThumbnail: "Küçük resim yükleniyor",
				popoverUploadSuccessful: "Yükleme başarılı",
				popoverUploadError: "Yükleme başarısız; tekrar deneyin",
				changePicAndThumb: "Resmi değiştir",
				changeThumb: "Küçük resmi değiştir",
				selectPic: "Medyayı değiştir",
				selectThumb: "Küçük resmi değiştir",
				uploadPicAndThumb: "Uygula"
			},
			headerJS:{
				editMe: "Beni düzenle!",
				templateTitle: "Şablon başlığını ayarla",
				templateSubtitle: "Şablon altyazısını ayarla"
			},
			crossFaderJS:{
				setPicture: "Resim başlığını ayarla",
				setCaption: "Resim altyazısını ayarla"
			},
			importPopup: {
				title: "İçe Aktar",
				prevBtn: "Geri",
				nextBtn: "Sonraki"
			},
			importPopupHome: {
				header: "Resimleriniz nerede depolanıyor ?"
			},
			onlinePhotoSharingCommon: {
				pictures: "resimler",
				videos: "videolar",
				disabled: "Bu özellik Yönetici tarafından devre dışı bırakıldı",
				disabledPortal: "Bu detay Portal for ArcGIS\'te devre dışıdır",
				header1: "Resimlerinizin herkes ile paylaşılması gerekiyor.",
				header2: "Bu içe aktarma ilk %NB1% %MEDIA% ile sınırlanacak.",
				emptyDataset: "Hata, hiçbir resim bulunamadı",
				footerImport: "İçe Aktar",
				selectAlbum: "Genel bir albüm seçin",
				selectAlbum2: "Bir albüm seçin",
				pleaseChoose: "Seçin",
				userLookup: "Ara",
				userLookingup: "Aranıyor",
				csv: "Bir CSV\'de başvuruluyor",
				advanced: "Gelişmiş seçenekler",
				advancedScratchLbl: "Yeni bir Tur başlat",
				advancedScratchTip: "Sihirbaz kullanarak kendiniz doldurabileceğiniz boş bir Tur oluşturun.",
				advancedCSVLbl: "CSV dosyasından içe Tur verileri aktarın",
				advancedCSVTip: "Tur içeriğinizi bir CSV dosyasından içe aktarın.",
				advancedCommonTip: "Görüntü ve videolarınızın zaten çevrimiçi olmasını gerektirir.",
				select: "Seçim yap",
				locUse: "Resimlerin coğrafi konumunu kullan",
				locExplain: "Resimler albümden devralınabileceği, bu da tüm fotoğrafların aynı konumda olmasına neden olabileceği için resimlerin konumunu kullanmak istemeyebilirsiniz.",
				locExplain2: "Videolar kullanıcı ayarlarından devralınabileceğinden, bu da tüm videoların aynı konumda olmasına neden olabileceğinden videoların konumunu kullanmak istemeyebilirsiniz."
			},
			viewFlickr: {
				title: "Flickr\'dan içe aktarma",
				header: "Flickr kullanıcı adınızı girin ve içe aktarılacak bir Fotoğraf Seti veya Etiket seçin.",
				userInputLbl: "Kullanıcı Adı Girin",
				signInMsg2: "Kullanıcı bulunamadı",
				selectSet: "Fotoğraf Seti Seçin",
				selectTag: "veya Etiket Seçin",
				footerImportTag: "Seçili Etiketi içe aktarın",
				footerImportSet: "Seçili Seti içe aktarın"
			},
			viewFacebook: {
				title: "Facebook içe aktarma",
				header: "Facebook Kullanıcı Hesabınız ile kimlik doğrulayın veya bir Genel Sayfa kullanın. Facebook kullanıcı kimlik doğrulaması gerektirmeyen genel bir Harita Turu oluşturmak için, yorum yapmaya izin veren ve özel kalmayı tercih eden özel albümler kullanılabilir.",
				leftHeader: "Facebook Kullanıcısı",
				rightHeader: "Facebook Sayfası",
				pageExplain: "Facebook sayfası, <b>esrigis</b> gibi genel bir marka/ürün veya ünlü kişiliktir. Sayfa adını sayfa URL\'sindeki ilk \'/\' karakterinden alabilirsiniz.",
				pageInputLbl: "Sayfa adı girin",
				lookupMsgError: "Sayfa bulunamadı"
			},
			viewPicasa: {
				title: "Picasa/Google+ içe aktarma",
				header: "E-posta adresinizi veya Picasa ya da Google+ hesabınızın kimliğini girin.",
				userInputLbl: "E-posta veya kimlik girin",
				signInMsg2: "Hesap bulunamadı",
				signInMsg3: "Genel albüm yok",
				howToFind: "Picasa ya da Google+ hesabı kimliği nasıl bulunur",
				howToFind2: "Herhangi bir Picasa ya da G+ sayfasının ilk ve ikinci \'/\' karakterleri arasındaki rakamları kopyalayın"
			},
			viewCSV: {
				title: "CSV içe aktarma",
				uploadBtn: "CSV dosyasını seçin veya üstüne bırakın",
				resultHeaderEmpty: "CSV boş",
				resultHeaderSuccess: "%NB_POINTS% nokta başarıyla yüklendi",
				resultHasBeenLimited: "Tur başına %VAL3% nokta sınırına uymak için içe aktarma %VAL2% noktanın ilk %VAL1% noktasıyla sınırlandı",
				browserSupport: "Tarayıcınız desteklenmiyor. Bir CSV kullanmak için, <a href='http://browsehappy.com/' target='_blank'>tarayıcınızı yükseltmeli</a> veya ArcGIS.com web haritası görüntüleyiciyi kullanmalısınız. (Yardım\'a bakın.)",
				errorLatLng: "Enlem ve boylam alanları bulunamadı. Olabilecek değerler, enlem için: <i>%LAT%</i>, boylam için: <i>%LONG%</i>.",
				errorFieldsExplain: "Aşağıdaki zorunlu alanlar bulunamadığından yükleme başarısız oldu",
				errorFieldsName: "<b>Ad</b> için olabilecek değerler: %VAL%",
				errorFieldsDesc: "<b>Açıklama</b> için olabilecek değerler: %VAL%",
				errorFieldsUrl: "<b>Resim URL\'si</b> için olabilecek değerler: %VAL%",
				errorFieldsThumb: "<b>Küçük Resim URL\'si</b> için olabilecek değerler: %VAL%",
				errorFields2Explain: "CSV aşağıdaki özniteliklerin katmanı için aynı öznitelikleri kullanmadığından yükleme başarısız oldu",
				errorFields2Name: "<b>Ad</b> - %VAL2% yerine %VAL1% kullanın",
				errorFields2Desc: "<b>Açıklama</b> - %VAL2% yerine %VAL1% kullanın",
				errorFields2Url: "<b>Resim URL\'si</b> - %VAL2% yerine %VAL1% kullanın",
				errorFields2Thumb: "<b>Küçük Resim URL\'si</b> - %VAL2% yerine %VAL1% kullanın",
				resultFieldsAll: "Tüm öznitelikler içe aktarıldı",
				resultFieldsNotAll: "Aşağıdaki öznitelikler, harita katmanında olmadıklarından içe aktarılmadı",
				resultFieldsNotAll2: "Aşağıdaki öznitelikler içe aktarıldı",
				footerNextBtnResult: "Web haritasına içe aktar",
				footerProgress: "İçe aktarma sürüyor",
				footerSucceed: "İçe aktarma başarılı. Yükleniyor"
			},
			viewYoutube: {
				title: "YouTube içe aktarma",
				header: "Herkesle paylaşılan videolar bulmak için bir YouTube kullanıcı adı girin.",
				pageInputLbl: "YouTube kullanıcı adı girin",
				lookupMsgError: "Kullanıcı bulunamadı",
				howToFind: "YouTube kullanıcı adı bulma",
				howToFind2: "Kullanıcı adı bu videoların altında gösterilir",
				found: "Bulundu",
				noData: "Hiçbir genel video bulunamadı"
			},
			viewGeoTag: {
				title: "Görüntülerinizi/videolarınızı seçin ve bulun",
				header: "İçe aktarmak istediğiniz resimleri bulmak için resimlerin üzerine tıklayın veya dokunun.",
				headerMore: "Görüntülerimin/videolarımın coğrafi konumları neden bulunamıyor?",
				headerExplain: "Geçerli bir coğrafi konumları varsa, resimleriniz haritada otomatik olarak bulunur ve ikinci sekmede listelenir.<br /><br />Resim içe aktardığınızda, Picasa ve Flickr varsayılan olarak coğrafi konum EXIF meta verilerini saklamaz. Resimlerin coğrafi içe aktarımını ve harici bir uygulama tarafından kullanılmasını etkinleştirmek için Picasa/Flickr gizlilik ayarlarını işaretleyin. EXIF coğrafi konumunun kullanılması için mevcut resimlerinizi Flickr\'a/Picasa\'ya tekrar içe aktarmanız gerekebilir.<br /><br />Facebook\'ta her resme gitmeniz, Düzenle\'ye tıklamanız ve konumu seçmeniz gerekir.",
				leftPanelTab1: "Bulunacaklar",
				leftPanelTab2: "Bulunanlar",
				clickOrTap: "Bulmak için Haritaya tıklayın veya dokunun",
				clearLoc: "Konumları temizle",
				clickDrop: "İçe aktarma",
				footerImport: "İçe Aktar",
				footerProgress: "İçe aktarma sürüyor",
				footerSucceed: "İçe aktarma başarılı. Yükleniyor...",
				loading: "Yükleniyor",
				error: "Resimlerin coğrafi konumunu içe aktarma başarısız oldu; coğrafi konumlar yoksayıldı."
			},
			initPopup: {
				title: "Harita Turu Derleyicisine Hoş Geldiniz",
				prevBtn: "Geri",
				nextBtn: "Sonraki"
			},
			initPopupHome: {
				header1: "Görüntüleriniz veya videolarınız nerede?",
				header2: "Bu yardımcı, daha önce çevrimiçi olarak depoladığınız medyadan bir Harita Turu derlemenize yardımcı olacak veya bunları ArcGIS Online for Organizations hesabınıza içe aktaracak.",
				title1: "Zaten çevirimiçi",
				title2: "Görüntülerimi yüklemem gerekiyor",
				hostedFSTooltip: "Görüntülerinizi barındırmak için ArcGIS Online kullanın. (Videoları desteklemez.)",
				hostedFsNA: "Yalnızca ArcGIS for Organizations Yayıncı ve Yönetici kullanıcıları içindir",
				footer1: "İşiniz bittiğinde, Harita Turunuzu uygulama öğesi sayfasından izleyici kitlenizle paylaşmayı unutmayın.",
				footer3: "CSV şablonunu indir",
				footer4: "İnmezse \"Farklı Kaydet\" kullan",
				footer4bis: "İndirme başlamazsa sağ tıklayıp \"Farklı Kaydet\" seçeneğini kullanın",
				footer5: "Daha fazla bilgi",
				footerProgress: "Oluşturma sürüyor",
				footerSucceed: "Oluşturma başarılı. Yükleniyor..."
			},
			helpPopup: {
				title: "Yardım",
				close: "Kapat",
				tab1: {
					title: "Giriş",
					div1: "Harita Turu şablonu, anlatmak istediğiniz öykü açısından ilgi uyandıracak bir fotoğraf veya medya öğesi olduğunda coğrafi bilgi sunmak için tasarlanmıştır.",
					div2: "Şablon, az sayıda yeri kullanıcıların içinde gezinebileceği numaralı bir sırada sunmanıza izin veren çekici, kullanımı kolay bir web uygulaması üretir. Şablon, akıllı telefonlar ve tabletler gibi bir cihazdaki bir web tarayıcısında kullanılmak üzere tasarlanmıştır. <br /><br />Oluşturmak istediğiniz türde bir uygulamaya bir örneği şurada bulabilirsiniz:",
					div4: "<a href='http://storymaps.esri.com/stories/maptour-palmsprings' target='_blank'>Palm Springs Harita Turu</a>.",
					div42: "Başka kullanıcıların oluşturmakta olduğu harita turu örneklerini görmek için, <a href='http://storymaps.arcgis.com/' target='_blank'>Anlatı Haritaları web sitesindeki</a> <a href='http://links.esri.com/storymaps/map_tour_gallery' target='_blank'>galeriyi ziyaret edin</a>. Bizi Twitter\'da <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a> adresinden izleyebilirsiniz.",
					div5: "Bize yazmanızı istiyoruz! İster bir soru sormak istiyor, ister yeni bir özellik istiyor, ister bir hata bulduğunuzu düşünüyor olun, <a href='http://links.esri.com/storymaps/forum' target='_blank'>Öykü Haritaları Kullanıcı Forumu</a>\'nu ziyaret edin."
				},
				tab2: {
					title: "Veri",
					div1: "Bir Harita Turu derlerken göz önüne alınacak ana öğe, resimlerinizin nereye depolanacağını seçmektir. Harita Turu önemli fotoğraf paylaşma servislerinde, herhangi bir web sunucusunda veya bir detay servisinin eki olarak depolanmış resimleri kullanabilir.",
					div1a: "Desteklenen resim formatların ve videoların ayrıntıları için bu sekmenin son bölümüne bakın.",
					div2: "Etkileşimli derleyici Harita Turunuzdaki görüntüleri yönetmek için iki seçenek sunar:",
					div3: "<ul><li>Flickr gibi bir fotoğraf paylaşma sitesinde depolanan görüntüler gibi <b>zaten çevrimiçinde olan fotoğrafları</b> veya kendi web sitenizde depolanan görüntüleri kullanabilirsiniz. Harita Turunda bu görüntülere URL\'leri yoluyla başvurulur.</li><li>Ayrıca, Harita Turunuza doğrudan <b>bilgisayarınızdaki fotoğrafları yükleyebilirsiniz</b>. Bu yükleme seçeneği bir ArcGIS for Organizations hesabınız olmasını ve Yayıncı veya Yönetici ayrıcalıklarına sahip olmanızı gerektirir çünkü fotoğraflarınızın ekler olarak depolandığı barındırılan bir detay servisi sizin adınıza otomatik olarak oluşturulur.</li></ul>",
					div4: "Ana kullanım örnekleri şunlardır:",
					div4b: "Henüz <b>fotoğraflarınız barındırılmıyordur</b> ve bir ArcGIS for Organizations hesabınız vardır: Barındırılan bir detay servisi kullanmak en iyi seçeneğinizdir. Genel fotoğraf paylaşma servisleri gibi, hızlı yüklenen görüntüler oluşturmak için resimlerinizi optimize ederiz ve ArcGIS platformunun tüm yönetim ve veri yönetimi imkanlarına erişiminiz olur.",
					div5: "<b>Bir Kuruluşa üye değilsinizdir</b>: Resimlerinizi önce bir fotoğraf paylaşma web sitesine veya kendi web sunucunuza yüklemeniz gerekir. Derleyici, asıl konumlarında barındırılmaya devam edecek olan bu resimleri kullanmanıza yardımcı olur.",
					div6: "Resimlerinizi ekler olarak depolayan veya harici resimlere başvuran <b>mevcut bir Detay Servisi\'ni tekrar kullanmanın yollarını arıyorsunuzdur</b>: Aşağıdaki ayrıntılı bölüme bakın.",
					div7: "Harita Turu şablonunun <b>önceki bir sürümünün kullanıcısısınızdır</b> ve zaten resimlerinize ve küçük resimlerinize başvuran bir CSV\'niz vardır: Bu dosyayı içe aktarıp verilerinizi ayrıntılandırabilirsiniz. Derleyici yalnızca enlem/boylam alanlarını kullanan CSV\'leri destekler; adres tabanlı CSV\'ler web haritanız yoluyla kullanılmaya devam edebilir. (Aşağıdaki bölüme bakın.)",
					div8: "Çevrimiçi fotoğraf paylaşma servislerinden içe aktarma",
					div9: "İçe aktarma işlemi zaten barındırılmakta olan resimlere bunların URL\'lerini bir web haritası detay koleksiyonda depolayarak başvurur. Resimler ArcGIS Online\'da depolanamaz. Barındırılan resimlere erişilemiyorsa, bunlar Harita Turu\'nda kullanılamaz ve bir \'Resim kullanılamıyor\' görüntüsü görürsünüz. Fotoğraf servisi sağlayıcınıza bağlı olarak Harita Turu resimlerini adını, açıklamasını ve konumunu içe aktaramayabilir. Bu öznitelikler web haritasında depolanır ve çevrimiçi servislerde yapılan düzenlemelerin hiçbiri Harita Turuna yansımaz.",
					div10: "Resimleri bir web sunucusunda depolama",
					div11: "Resimleri kendiniz barındırmayı seçerseniz, resimlerinizin küçük resimlerini el ile oluşturmanız gerekir. Küçük resim için tam çözünürlüklü resimleri kullanmak yetersiz performansla sonuçlanır. Bu nedenle bunu sizin için yapacak çevrimiçi bir fotoğraf paylaşma servisi veya bir detay servisi kullanmanızı öneririz.",
					div12: "Mevcut bir Detay Servisi\'ni veya Shapefile\'ı kullanma",
					div13: "Herhangi bir nokta detay servisi veya shapefile bir Harita Turu veri kaynağı olarak kullanılabilir. Bu kaynağı arcgis.com Harita Görüntüleyicisi yoluyla web haritanıza bir katman olarak eklemeniz yeterlidir. Uygulama katmanınızda beklenen öznitelikleri bulursa, tüm derleyici işlevleri kullanılabilir.",
					div14: "Alan adları için olabilecek değerler şunlardır (harf büyüklüğüne duyarlıdır):",
					div151: "Ad",
					div152: "Açıklama",
					div153: "Resim",
					div154: "Küçük Resim",
					div155: "Renk ",
					div16: "Uygulama bir detay servisini kullanırken eşleşen alanlar bulamazsa, kullanılacak alanlar derleyici yoluyla yapılandırılana kadar görüntüleyici çalışmaz. Web haritasına eklenen CSV ve shapefile katmanlarının gerekli tüm alanlara sahip olması gerekir, yoksa derleyici çalışmaz.",
					div162: "Resimleri ekler olarak depolayan bir detay servisini kullanılırken <b>yalnızca iki eki olan detaylar kullanılır</b>. İlk ek ana resmi, ikinci ek ise küçük resmi tanımlar.",
					div17: "Ekleri olmayan detay servisleri için resim ve küçük resim alanları zorunlu, ekleri olan detay servisleri içinse isteğe bağlıdır (ancak özellikle önerilir). Serviste ekler etkinleştirilmişse, derleyici resimleri ekler olarak yüklemenize izin verir. Değilse, resmin ve küçük resmin URL\'lerini düzenleyebilirsiniz.",
					div172: "Mevcut olduğunda resim ve küçük resim alanları her zaman kullanılır ve detay servisi ekleri sorgulanmaz.",
					div173: "Örnek CSV\'ler ve shapefile\'lar şuradan indirilebilir:",
					div18: "CSV\'den veya shapefile\'dan barındırılan bir Detay Servisi oluşturma",
					div19: "CSV veya shapefile dosyasından barındırılan bir detay servisi oluşturduğunuzda, ekler varsayılan olarak etkinleştirilmez. Bunları etkinleştirmek için detay servisinin sayfasını açıp katman bölümündeki küçük oka tıklarsanız, bu seçeneği görürsünüz. Harita Turu öznitelikler yoluyla başvurduğunuz resimleri ve küçük resimleri kullanmaya devam eder. Resimlerinizi detay servisi ekleri olarak karşıya yüklemek isterseniz, resim panelindeki iki düğme (\"Resmi Değiştir\" ve \"Küçük Resmi Değiştir\") yoluyla bunu yapabilirsiniz.",
					div20: "Desteklenen resim formatları ve videolar",
					div21: "Desteklenen resim formatları şunlardır: <b>.jpg, .jpeg, .png, .gif ve .bmp</b>. Medyanız bu uzantıyla bitmiyorsa, Harita Turu bunu, bir detay servisi kullandığı durumlar dışında video olarak kabul eder (aşağıya bakın).",
					div22: "Harita Turu şablonu bir video oynatıcısı içermez, bu yüzden favori video barındırma servisinizin sağladığı harici video oynatıcısını kullanmanız gerekir. (Videoyu katıştırma seçeneğini bulun ve verili koddaki URL\'yi kopyalayın.) Videoyu kendiniz barındırmak isterseniz, <a href='http://www.videojs.com/'>Video.js</a> gibi bir video oynatıcı içeren bir HTML sayfası oluşturabilirsiniz.",
					div23: "Ekleri olan detay servisleri kullanılırken etkileşimli derleyici video dahil etmek için bir iletişim kutusu sunmaz, ancak verilerinizi etkileşimli derleyicinin dışında düzenleyerek bunu yapabilirsiniz. Arcgis.com harita görüntüleyicisinde, resim alanlarını harici bir videoya işaret edecek şekilde değiştirir ve URL\'nizin sonuna özel bir parametre (#isVideo) eklerseniz, medyanızın bir video olduğu kabul edilir.",
					div24: "İki geçerli resim ekiniz olması gerektiğine, aksi halde noktanın kullanılamayacağına dikkat edin. Resim ve küçük resim alanları olmadan, detay servisi ekleri kullanılırken video kullanmak mümkün değildir."
				},
				tab3: {
					title: "Özelleştirme",
					div1: "Derleyici, üst paneldeki AYARLAR düğmesi ile erişilebilen birkaç özelleştirme seçeneği sunar. Beklediğiniz seçeneği bulamazsanız, web sunucunuza kurabileceğiniz ve ihtiyaçlarınıza uyacak şekilde geliştirebileceğiniz indirilebilir bir sürümünü de sağlıyoruz.",
					div2: "Şunlar olmadıkça barındırılan sürümü kullanmanızı öneririz:",
					div3: "<li>Üstbilgi arka plan görüntüsünü kullanma gibi istediğiniz bir kullanıcı arayüzü özelleştirme olanağı sunmuyor.</li><li>Bir geliştiricisiniz ve uygulamayı geliştirmek istiyorsunuz.</li>",
					div4: "İndirilebilen sürüm bir web haritası veya bir web haritalama uygulaması tanımlayıcısı yoluyla yapılandırılabilir. Ana kullanım örnekleri şunlardır:",
					div41: "Harita turunuzu barındırmalı ortamdaki etkileşimli derleyiciyi kullanarak derliyor ve şablonu web haritalama uygulaması tanımlayıcısıyla yapılandırıyorsunuz. Etkileşimli derleyici ile tanımladığınız ayarlar uygulanır.",
					div42: "Web haritanızı etkileşimli derleyici dışında derliyor ve şablonu web harita tanımlayıcısı ile yapılandırıyorsunuz. Şablonun nasıl yapılandırılacağını öğrenmek için belgeleri okumanız gerekir.",
					div43: "Etkileşimli derleyicinin, 10. sürümden daha eski Internet Explorer gibi tarayıcılarda bazı teknik kısıtlamalar olmak kaydıyla  indirilebilir bir sürümünün bulunduğunu unutmayın.",
					div5: "Şablonun en son sürümünü indirmek ve nasıl kullanılacağı hakkında daha fazla bilgi almak için <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub proje sayfasını</a> ziyaret edin."
				},
				tab4: {
					title: "İpuçları",
					div0: "Desteklenen tarayıcılar",
					div0a: "Harita Turu görüntüleyicisi IE8+\'da desteklenmektedir. Etkileşimli derleyici IE9+\'da desteklenmektedir. Derleyiciyi tüm tarayıcılarda aktif olarak test ediyoruz ancak güçlüklerle karşılaşırsanız, Chrome\'u kullanmanızı öneririz.",
					div0b: "Bazı güçlüklerle karşılaşırsanız, bize bildirin. Bu arada, Harita Turunuzu CSV şablonunu kullanarak derleyerek derleyici arayüzüyle etkileşiminizi en aza indirmiş olursunuz.",
					div1: "Resimler",
					div2: "Dikey yönlendirme yerine yatay yönlendirme kullanan fotoğrafları öneriyoruz. 4:3 en boy oranı olan fotoğraflar en uygun olanlarıdır. Dikey yönlendirmeli görüntüler kullanılabilir, ancak iPad gibi küçük ekranlarda fotoğrafın büyük bir kısmı altyazı ile örtülebilir. (Metin, boylamasına gösterildiğinde enlemesine gösterildiğinden daha fazla yer kaplamaktadır.) Harita Turunda farklı boylarda, şekillerde ve yönlendirmelerde görüntüler kullanılabilirse de tüm görüntülerde aynı boyutu ve şekli kullanmayı öneriyoruz. Bu şekilde, turda gezerken kullanıcının dikkati farklı boyda görüntüler nedeniyle dağılmaz.",
					div2a: "Ana resimlerde maksimum 1000 piksel genişlik x 750 piksel yükseklik, küçük resimlerde 140x93 boyut öneriyoruz.",
					div3: "Altyazı metninizi HTML etiketleriyle formatlama",
					div4: "Üstbilgi ve resim başlığı/altyazısı, formatlama ve bağlantılar için HTML etiketleri içerebilir. Örneğin, şu kod sarı bir bağlantı eklemektedir:",
					div4a: "Turunuz için uygun altyazı yazın",
					div4b: "Turunuz için ilgi çekici bir altyazı yazmaya vakit ayırın. Altyazı insanları turunuza çekmenin ve onlara turda neler keşfedeceklerini anlatmanın iyi bir yoludur. Ayrıca, izleyici kitlenize turun yapıldığı eyalet veya ülkeyi söylemek için de uygun yerdir. Örneğin, insanların turunuzun yapıldığı şehri veya kasabayı bildiklerini varsaymayın. Altyazınız, ayrıca, bağlantı gibi HTML etiketleriyle de formatlanabilir. Yalnızca altyazı çok uzun olmamalıdır. Daha küçük tarayıcı pencerelerinde veya iPad\'de tam olarak ekrana sığmayabilir ve kırpılabilir. İyi bir altyazı düşünemiyorsanız, altyazıyı boş bırakın.",
					div5: "Katmanları Destekleme",
					div6: "Harita Turuna içerik sağlamak için destekleyici ilave katmanlar ekleyebilirsiniz. Bu katmanlar, bir inceleme alanı, tur noktalarınızı birbirine bağlayan bir yaya veya taşıt yolu gibi Harita Turu noktalarına ek olarak haritanın göstermesini istediğiniz diğer coğrafi detayları da içerebilir. Harita Turu şablonu bu destekleyici ilave katmanları web haritasında belirttiğiniz simgeleri kullanarak görüntüler, ancak açılan pencereler kullanılamaz.",
					div7: "Turunuz kısa ve çekici olsun",
					div8: "Tur başına 99 noktalık bir sınırlama vardır. Çoğu Harita Turu tabii ki bundan önemli ölçüde daha kısa olacaktır. İzleyici kitlenizin bir sürü tur noktasını adım adım gezmesini beklemeyin. Konunuz size çok ilginç gelebilir, ancak izleyicinizin de çok ilginç bulacağını varsaymayın!",
					div9: "Daha fazla bilgi için <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>ayrıntılı kılavuza</a> bakın.",
					div10: "Katıştırma modu",
					div11: "Şablonu bir iframe yoluyla başka bir web sitesine katıştırmak istiyorsanız, URL\'nin sonuna isteğe bağlı \"&embed\" parametresini eklemek üstbilgiyi sayfadan çıkarır. Bu mod, ayrıca, yapılandırma dosyası yoluyla indirilebilir sürümde de ayarlanabilir.",
					div12: "Harita turunuzun kolay tepki veren dokunmatik küçük ekran yerleşimine geçmesine neden olacak dar bir iFrame genişliği kullanmayın. Bunun amacı kullanım kolaylığını artırmaktır. Bir harita turunuzu bir sayfaya katıştırırken, kullanıcıların turu tam ekranda başlatabilmesi için daima katıştırılmış turun yanına yine de bir bağlantı koymanızı öneririz." 
				},
				tab5: {
					title: "Yayınlama",
					div1: "İşiniz bittiğinde Harita Turunuzu PAYLAŞ düğmesiyle veya ArcGIS Online\'daki uygulama öğesi sayfası üzerinden izleyici kitlenizle paylaşmayı unutmayın.",
					div2a: "Turu derleyici üzerinden paylaşma",
					div2b: "PAYLAŞ düğmesi uygulamayı ve web haritası öğelerini günceller. Tur verileriniz bir Detay Servisi öğesinde depolanıyorsa, o da güncellenir. ArcGIS.com harita görüntüleyici yoluyla başka katmanlar eklediyseniz, bunlar güncellenmez. Bu, Tur\'un beklediğiniz gibi paylaşılmamasıyla sonuçlanabilir. Gerekli (veya daha fazla) ayrıcalıklara zaten sahip olan öğeler güncellenmez.",
					div2c: "Turu ArcGIS Online yoluyla paylaşma",
					div2d: "Uygulamayı ArcGIS Online sitesi üzerinden paylaştığınızda, sizden gerekirse aynı şekilde paylaşılmayan bağımlı kaynakları (web haritası, detay servisi, dekorasyon katmanı) güncellemenizi ister. Harita Turu herkese açıksa ve kaynaklarınızdan biri kitlenizle paylaşılmıyorsa, kullanıcılar ArcGIS Online oturum açma sayfasına yönlendirilir.",
					div3t: "Detay Servisi güvenliği",
					div3a: "Harita Turu derleyicisi ile oluşturulmuş barındırılan bir detay servisi kullanıyorsanız, uygulama sizin için servis güvenliğini yönetir ve servisi herkesle paylaşsanız bile düzenleme ayrıcalıklarına sahip tek kişi olmayı sürdürürsünüz.",
					div3t2: "Turunuzu izleyici kitlenizle paylaşmadan önce",
					div3: "Turunuzun ArcGIS.com hesabınızla oturum açmadığınızda da düzgün çalıştığından emin olun. Kullanacağınız URL izleyiciyi bir oturum açma sayfasına veya derleyici moduna yönlendirmemelidir.",
					div4: "Turunuzun yatay yönlendirmede tutulan bir iPad\'de nasıl göründüğüne bakmak, bu popüler cihazda düzgün göründüğünden emin olmak için iyi bir fikirdir. Bu, altyazılarınızın resimleri çok fazla örtmediğinden emin olmanıza yardımcı olabilir. Ayrıca, altyazınızın ekrana sığıp sığmadığını ve kırpılmasına neden olacak kadar uzun olup olmadığını görmenize izin verir.",
					div5a: "Arama için öneri",
					div5b: "İnsanların ArcGIS Online\'da arama yaptıklarında Harita Turunuzu bulmasına yardımcı olmak için harita turunuzun uygulama öğesi sayfasına (web haritanızın öğe sayfasına değil) \'story map\' etiketini, bunun yanı sıra da turun yapıldığı eyaletin veya ilin adı, ABD dışındaysa ülkenin adı ve \'public art\', \'tourist guide\' veya \'historic places\' gibi tema etiketlerini eklemenizi öneririz. Bu etiketler, ayrıca, Esri\'de bize de galerilerimizde gösterebileceğimiz ve sosyal medyada tanıtabileceğimiz güzel yeni tur örnekleri bulmamız için yardımcı olur. Ayrıca, uygulama öğesi sayfanıza turun küçük bir ekran resmi veya içindeki resimlerden biri gibi hoş duran bir küçük resim grafiği yüklemenizi de öneririz. Harita turunuz bir ArcGIS Online galerisine eklenirse, otomatik olarak bu resim kullanılır."
				}
			},
			share: {
				firstSaveTitle: "Tur başarıyla kaydedildi",
				firstSaveHeader: "Turunuz artık ArcGIS Online\'a kaydedilmiş durumda. Aşağıdaki sık sorulan sorulara cevapları okuyun.",
				firstSaveA1: "ArcGIS Online\'ı iyi bilmiyorsanız veya hazırlama arayüzüne erişmek için bir kısayol istiyorsanız, şu bağlantıyı kaydedebilirsiniz: %LINK1%",
				firstSaveA1bis: "Tur ayrıca <a href='%LINK2%' target='_blank'>ArcGIS Online içerik klasörünüzde</a> de bulunabilir.",
				firstSaveQ2: "Turum paylaşılıyor mu?",
				firstSaveA2: "Turunuz şu anda paylaşılmıyor. Paylaşmak için PAYLAŞ düğmesini kullanın.",
				shareTitle: "Turunuzu Paylaşın",
				sharePrivateHeader: "Turunuz paylaşılmıyor, paylaşmak ister misiniz?",
				sharePrivateBtn1: "Herkesle paylaş",
				sharePrivateBtn2: "Kuruluşumla Paylaş",
				sharePrivateProgress: "Paylaşma sürüyor...",
				sharePrivateErr: "Paylaşma başarısız, tekrar deneyin veya",
				sharePrivateOk: "Paylaşma başarıyla güncellendi, yükleniyor...",
				sharePreviewAsUser: "Önizleme",
				shareHeader1: "Turunuza <strong>herkes erişebilir</strong>.",
				shareHeader2: "Turunuza kuruluşunuzun üyeleri erişebilir. (Oturum açılması gerekir.)",
				shareLinkHeader: "Turu izleyici kitlenizle paylaşın",
				shareLinkOpen: "AÇ",
				shareQ1Opt1: "Turu nasıl özel tutabilirim?",
				shareQ1Opt2: "Turu nasıl özel tutabilir veya herkesle paylaşabilirim?",
				shareA1: "<a href='%LINK1%' target='_blank'>Uygulama öğesi sayfasında</a> %SHAREIMG% kullanın. Web haritasını paylaşmayı iptal etmek istiyorsanız, <a href='%LINK2%' target='_blank'>web harita öğesi sayfasını</a> kullanın.",
				shareA1bis: "Detay Servisi\'ni paylaşmayı iptal etmek istiyorsanız, <a href='%LINK1%' target='_blank'>Detay Servisi öğesi sayfasını</a> kullanın.",
				shareQ2: "Turu daha sonra nasıl düzenlerim?",
				shareQ2bis: "Hazırlama arayüzüne nasıl geri dönerim?",
				shareA2div1: "%LINK1% bağlantısını kaydedip tekrar kullanın veya <a href='%LINK2%' target='_blank'>uygulama öğesi sayfasını</a> kullanın.",
				shareA2div2: "Uygulamanın sahibi olarak ArcGIS.com\'da oturum açtığınızda, uygulamada etkileşimli derleyiciyi açmak için bir düğme bulunur:",				
				shareQ3: "Veriler nerede saklanıyor?",
				shareA3: "Tur yapılandırması <a href='%LINK1%' target='_blank'>bu web haritası öğesinde</a> ve <a href='%LINK2%' target='_blank'>bu web uygulaması öğesinde</a> saklanır. Flickr, Picasa ve Facebook görüntüleri ya da YouTube videoları kendi ilgili sitelerinde referanslı kalır ev ArcGIS Online'a kopyalanmaz.",
				shareWarning: "%WITH% ile paylaşma devre dışı bırakıldı çünkü <a href='%LINK%' target='_blank'>web haritasının</a> sahibi değilsiniz.",
				shareWarningWith1: "genel ile",
				shareWarningWith2: "genel ve Kuruluş ile"
			}
        }
    })
);
