define(
({
		viewer: {
			loading: {
				step1: "LASTER INN APPLIKASJON",
				step2: "LASTER INN DATA",
				step3: "INITIALISERER OMVISNINGEN",
				fail: "Beklager, innlastingen av kartomvisningen mislyktes",
				failButton: "Prøv på nytt"
			},
			errors: {
				boxTitle: "Det har oppstått en feil",
				invalidConfig: "Alvorlig feil: Ugyldig konfigurasjon",
				invalidConfigOwner: "Alvorlig feil: Ugyldig konfigurasjon (autorisert eier kreves)",
				invalidConfigNoWebmap: "Alvorlig feil: Ugyldig konfigurasjon (webkart og autorisert eier kreves)",
				createMap: "Kan ikke opprette kart",
				invalidApp: "Alvorlig feil: Kan ikke laste inn applikasjonen",
				noLayer: "Webkartet inneholder ikke noe gyldig datalag for Map Tour.",
				noLayerNoHostedFS: "Webkartet inneholder ikke noe gyldig datalag for Map Tour, og du har ikke de påkrevde rettighetene til å opprette en vertsbasert geoobjekttjeneste.",
				noLayerMobile: "Velkommen til webapplikasjonen Map Tour. Applikasjonen er ikke konfigurert. Map Tour-byggeren støttes ikke på mobile enheter.",
				noLayerView: "Velkommen til webapplikasjonen Map Tour.<br />Applikasjonen er ikke konfigurert ennå.",
				noBuilderWebmapData: "Map Tour-byggeren støttes ikke i innebygde data på webkart. For å bruke byggeren må du bruke en geoobjekttjeneste. For å bruke et faktisk datalag må du bruke den nedlastbare versjonen av Map Tour.",
				appSave: "Feil under lagring av webapplikasjonen",
				mapSave: "Feil under lagring av webkartet",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "Du har ikke tillatelse til å konfigurere denne applikasjonen",
				oldBrowserTitle: "Webleseren støttes ikke fullt ut",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "Map Tour-byggeren støtter ikke Internet Explorer 10 på Windows 7. Du må <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuelt tvinge dokumentmodusen til å ha Internet Explorer 9-standarder</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>nedgradere til Internet Explorer 9</a> eller oppgradere til Windows 8.",
				oldBrowserExplain: "Denne nettleseren støtter ikke automatisk generering av miniatyrbilder fra bildene du laster inn i map tour. Du kan opprette map tour med denne nettleseren, men du må oppgi et eget miniatyrbilde for hvert av bildene du laster opp.",
				oldBrowserExplain2: "Hvis du vil få en bedre opplevelse, kan du <a href='http://browsehappy.com/' target='_blank'>oppgradere webleseren</a> eller <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivere Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserClose: "Lukk"
			},
			mobileHTML: {
				showIntro: "VIS INTRO",
				hideIntro: "SKJUL INTRO",
				navList: "Liste",
				navMap: "Kart",
				navInfo: "Info"
			},
			desktopHTML: {
				storymapsText: "Et fortellingskart",
				builderButton: "Gå over til byggermodus"
			},
			builderHTML: {
				panelHeader: "KONFIGURASJON AV APPLIKASJON",
				buttonSave: "LAGRE",
				buttonDiscard: "AVBRYT",
				buttonSettings: "Innstillinger",
				buttonView: "Visningsmodus",
				buttonOrganize: "Organiser",
				buttonAdd: "Legg til",
				modalCancel: "Avbryt",
				modalApply: "Bruk",
				organizeHeader: "Organiser omvisningen",
				organizeGeneralCaption: "Bruk dra og slipp for å sortere omvisningspunkter",
				organizeDelete: "Slett",
				organizeHide: "Skjul",
				addMaxPointReached: "Du har nådd maksimalt antall punkter som er tillatt av ikonene som er valgt, og kan ikke legge til flere omvisningspunkter.<br /><br />Vær oppmerksom på at du må laste inn applikasjonen på nytt hvis du sletter eksisterende punkter.",
				addMaxPointReachedMobile: "Beklager, du har nådd det maksimale antallet autoriserte punkter og kan ikke legge til dette bildet.",
				addClose: "Lukk",
				addHeader: "Legg til et nytt omvisningspunkt",
				addTabPicture: "Bilde",
				addTabInformation: "Informasjon",
				addTabLocation: "Plassering",
				addSelectCaption: "Velg eller slipp bilde",
				addSelectCaptionNoFileReader: "Velg bilde",
				addChangePhoto: "Endre bilde og miniatyrbilde",
				addPictureResolutionIntro: "Bildeoppløsningen er høyere enn nødvendig:",
				addPictureResolutionOldBrowser: "Bildeoppløsningen er høyere enn nødvendig. Få mest mulig ut av Map Tour ved å angi en oppløsning som er lavere enn %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Endre bildeoppløsningen til %RESOLUTION%",
				addPictureResolutionKeep: "Behold den opprinnelige bildeoppløsningen på %RESOLUTION%",
				addSelectThumbnail: "Velg miniatyrbilde",
				addNoThumbSelected: "Du har ikke valgt noe miniatyrbilde",
				addThumbSelected: "Valgt",
				addCameraSettingsHeader: "KAMERAINNSTILLINGER",
				addThumbnailHeader: "MINIATYRBILDE",
				addLabelName: "Navn",
				addLabelDescription: "Undertekst",
				addTextPlaceholder: "Skriv noe",
				addLocatePlaceholder: "Finn en adresse eller et sted",
				addPinColor: "Farge",
				addLatitude: "Breddegrad",
				addLongitude: "Lengdegrad",
				addLatitudePlaceholder: "f.eks. 34.056",
				addLongitudePlaceholder: "f.eks. -117.195",
				addUploading: "Laster opp omvisningspunkt",
				addSave: "Legg til omvisningspunkt",
				addMobileUploading: "Laster opp bilde",
				addMobileName: "Angi et navn",
				addMobileNameMandatory: "Feil, angi et navn.",
				addMobileError: "Beklager, noe gikk galt.",
				settingsHeader: "Applikasjonsinnstillinger",
				settingsTabLayout: "Utforming",
				settingsTabColor: "Farger",
				settingsTabLogo: "Overskrift",
				settingsTabFields: "Data",
				settingsTabExtent: "Utstrekning",
				settingsTabZoom: "Zoomnivå",
				settingsLayoutExplain: "Velg applikasjonsutforming blant de to som er oppgitt.",
				settingsLayoutProfessional: "Utforming med tre paneler",
				settingsLayoutModern: "Integrert utforming",
				settingsLayoutSelected: "Valgt utforming",
				settingsLayoutSelect: "Velg denne utformingen",
				settingsColorExplain: "Endre utseende ved å velge et forhåndsdefinert tema eller opprette ditt eget.",
				settingsLabelColor: "Farge på topptekst, innhold og bunntekst",
				settingsLogoExplain: "Tilpass logoen øverst (maks. 250 x 50 piksler).",
				settingsLogoEsri: "Esri-logo",
				settingsLogoNone: "Ingen logo",
				settingsLogoCustom: "Tilpasset logo",
				settingsLogoCustomPlaceholder: "Bilde-URL",
				settingsLogoCustomTargetPlaceholder: "Gjennomklikkingskobling",
				settingsLogoSocialExplain: "Tilpass overskriftkoblingen øverst til høyre.",
				settingsLogoSocialText: "Tekst",
				settingsLogoSocialLink: "Kobling",
				settingsDataFieldsExplain: "Velg bildenavn, tekst og fargefelter.",
				settingsDataFieldsError: "Kan ikke finne riktig navn, tekst eller fargedata. Velg feltene som skal brukes her. Disse innstillingene kan endres senere.",
				settingsFieldsLabelName: "Navn",
				settingsFieldsLabelDescription: "Undertekst",
				settingsFieldsLabelColor: "Farge",
				settingsExtentExplain: "Velg den opprinnelige utstrekningen av Map Tour gjennom det interaktive kartet nedenfor.",
				settingsExtentExplainBottom: "Denne utstrekningen brukes bare hvis den inneholder det første turpunktet. Verdien beholdes gjennom webkartets første utstrekning.",
				settingsExtentDrawBtn: "Tegn en ny utstrekning",
				settingsExtentModifyBtn: "Rediger gjeldende utstrekning",
				settingsExtentApplyBtn: "Bruk på hovedkart",
				settingsZoomExplain: "Angi zoomnivå for fortellingspunkter etter innledningen (valgfritt).",
				settingsLabelZoom: "Målestokk/nivå",
				settingsZoomFirstValue: "Ingen",
				settingsFieldError : "Velg et felt i hver liste",
				dataHeader: "Applikasjonsdata",
				dataExplain: "Webkartet inneholder ingen geoobjektstjeneste. Fullfør denne dialogboksen for å opprette en vertsbasert geoobjektstjeneste i organisasjonskontoen på ArcGIS.com. Geoobjektstjenesten blir lagt til i webkartet ditt og delt med alle, men du må legge til/redigere og slette tilgangsrettigheter.<br /><br />-Applikasjonen blir synlig bare for deg helt til du deler den med andre. <strong>Når Map Tour er klar, deler du applikasjonen gjennom elementsiden.</strong>",
				dataNameLbl: "Tjenestenavn",
				dataFolderListLbl: "Mappe",
				dataFolderListFetching: "Henter mapper...",
				dataRootFolder: "Rot",
				dataNameError: "Angi et navn for geoobjektstjenesten",
				dataFolderError: "Velg en gyldig mappe",
				dataSrcContainsInvalidChar: "Navnet på geoobjektstjenesten inneholder ett eller flere ugyldige tegn (<, >, #, %, :, \", ?, &, +, / eller \).",
				dataSrvAlreadyExistsError: "Det finnes allerede en tjeneste med det navnet i organisasjonen. Velg et annet navn.",
				dataBtnClose: "Avbryt omvisningen",
				dataBtnSave: "Opprett tjenesten",
				dataFooterProgress: "Opprettelse pågår",
				dataFooterSucceed: "Opprettelsen er fullført. Laster inn.",
				dataFooterError: "Opprettelsen mislyktes. Prøv på nytt.",
				tabError: "Se etter feil i alle faner",
				introRecordBtn: "Intro",
				introRecordActivate: "Bruk første punkt som en introduksjon"
			},
			addPopupJS: {
				uploadingPicture: "Laster opp bilde",
				uploadSuccess: "Opplastingen er fullført",
				uploadError: "Feil under opplasting av bildet",
				notJpg: "Velg et JPEG-bilde du vil laste opp",
				errorNoPhoto: "Velg et bilde du vil laste opp",
				errorNoThumbnail: "Velg et miniatyrbilde du vil laste opp",
				errorNoName: "Angi et navn for dette omvisningspunktet",
				errorNoDescription: "Angi en tekst for dette omvisningspunktet",
				errorNoLocation: "Angi et sted for dette omvisningspunktet"
			},
			builderJS: {
				noPendingChange: "Ingen ventende endring",
				unSavedChangeSingular: "1 ulagret endring",
				unSavedChangePlural: "ulagrede endringer",
				popoverDiscard: "Er du sikker på at du vil forkaste endringer som ikke er lagret?",
				yes: "Ja",
				no: "Nei",
				popoverLoseSave: "Dersom du åpner viseren, mister du endringer som ikke er lagret",
				ok: "Ok",
				popoverSaveWhenDone: "Ikke glem å lagre når du er ferdig",
				closeWithPendingChange: "Er du sikker på at du vil bekrefte handlingen? Du mister da endringene du har gjort.",
				gotIt: "Ok",
				savingApplication: "Lagrer applikasjonen",
				saveSuccess: "Applikasjonen er lagret",
				saveError: "Lagringen mislyktes. Prøv på nytt.",
				dragColorPicker: "Flytt på meg<br />eller endre fargen min",
				dataWarningExtent: "Du har data utenfor webkartets utstrekning. Disse dataene blir ikke brukt som omvisningspunkter. Endre kartets utstrekning hvis du vil bruke dem.",
				dataWarningVisibi: "Map Tour-laget er ikke synlig med den gjeldende utstrekningen for webkartet. Bekreft at Map Tour-laget er synlig med et %MAPSIZE% stort kart.",
				dataWarningEdit: "Rediger webkart",
				dataWarningClose: "Lukk",
				signIn: "Logg på med en konto på",
				signInTwo: "for å lagre applikasjonen."
			},
			organizePopupJS: {
				messageStart: "Du har valgt å slette",
				messageSinglePoint: "ett omvisningspunkt",
				messageMultiPoint: "omvisningspunkter",
				messagePermantRemove: "Dette fører til permanent fjerning av",
				messageRecord: "posten",
				messageRecordPlural: "poster",
				messageConfirm: "fra databasen. Vil du fortsette?",
				labelButtonShow: "Vis",
				labelButtonHide: "Skjul"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "Laster opp bilde og miniatyrbilde",
				popoverUploadingThumbnail: "Laster opp miniatyrbilde",
				popoverUploadSuccessful: "Opplastingen er fullført",
				popoverUploadError: "Opplastingen mislyktes, prøv på nytt",
				changePicAndThumb: "Endre bilde",
				changeThumb: "Endre miniatyrbilde",
				selectPic: "Endre bilde",
				selectThumb: "Endre miniatyrbilde",
				uploadPicAndThumb: "Bruk"
			},
			headerJS:{
				editMe: "Rediger meg!",
				templateTitle: "Angi tittel på malen",
				templateSubtitle: "Angi undertittel for malen"
			},
			crossFaderJS:{
				setPicture: "Angi bildetittel",
				setCaption: "Angi bildetekst"
			}
        }
    })
);
