define(
({
		viewer: {
			loading: {
				step1: "LÄSER IN PROGRAM",
				step2: "LÄSER IN DATA",
				step3: "INITIERAR FÄRDEN",
				fail: "Det gick inte att läsa in Map Tour",
				failButton: "Försök igen"
			},
			errors: {
				boxTitle: "Ett fel har inträffat",
				invalidConfig: "Allvarligt fel: ogiltig konfiguration",
				invalidConfigOwner: "Allvarligt fel: ogiltig konfiguration (auktoriserad ägare krävs)",
				invalidConfigNoWebmap: "Allvarligt fel: ogiltig konfiguration (webbkarta och auktoriserad ägare krävs)",
				createMap: "Det går inte att skapa kartan",
				invalidApp: "Allvarligt fel: programmet kunde inte läsas in",
				noLayer: "Webbkartan innehåller inte ett giltigt datalager för Map Tour.",
				noLayerNoHostedFS: "Webbkartan innehåller inte ett giltigt datalager för Map Tour och du har inte den behörighet som krävs för att skapa en värdbaserad geoobjektstjänst.",
				noLayerMobile: "Välkommen till webbprogrammet Map Tour. Programmet har inte konfigurerats. Map Tour-byggverktyget stöds inte på mobila enheter.",
				noLayerView: "Välkommen till webbprogrammet Map Tour.<br />Programmet har inte konfigurerats än.",
				noBuilderWebmapData: "Map Tour-byggverktyget fungerar inte med inbäddade data i webbkartor. Om du vill använda byggverktyget måste du använda en geoobjektstjänst. Om du vill använda ditt befintliga datalager måste du använda den nedladdningsbara versionen av Map Tour.",
				appSave: "Det uppstod ett fel när webbprogrammet skulle sparas",
				mapSave: "Det uppstod ett fel när webbkartan skulle sparas",
				featureServiceLoad: "Error loading feature service",
				notAuthorized: "Du är inte behörig att konfigurera det här programmet",
				oldBrowserTitle: "Webbläsaren stöds inte fullt ut",
				noBuilderIE8: "The Map Tour builder is not supported on Internet Explorer before version 9.",
				ie10Win7Explain: "Map Tour-byggverktyget stöds inte på Internet Explorer 10 på Windows 7. Du måste <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>manuellt tvinga dokumentläget till Internet Explorer 9-standard</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>nedgradera till Internet Explorer 9</a> eller uppgradera till Windows 8.",
				oldBrowserExplain: "Denna webbläsare stöder inte automatisk generering av miniatyrbilder från bilderna som du överför till din karttur. Du kan skapa en karttur med den här webbläsaren, men du måste lägga till en separat miniatyrbild för varje bild som du överför.",
				oldBrowserExplain2: "För att förbättra upplevelsen kan du <a href='http://browsehappy.com/' target='_blank'>uppgradera webbläsaren</a> eller <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktivera Google Chrome Frame for Internet Explorer</a>.",
				oldBrowserClose: "Stäng"
			},
			mobileHTML: {
				showIntro: "VISA INTRODUKTION",
				hideIntro: "DÖLJ INTRODUKTION",
				navList: "Lista",
				navMap: "Karta",
				navInfo: "Info"
			},
			desktopHTML: {
				storymapsText: "En berättelsekarta",
				builderButton: "Växla till byggläget"
			},
			builderHTML: {
				panelHeader: "PROGRAMKONFIGURATION",
				buttonSave: "SPARA",
				buttonDiscard: "AVBRYT",
				buttonSettings: "Inställningar",
				buttonView: "Visningsläge",
				buttonOrganize: "Organisera",
				buttonAdd: "Lägg till",
				modalCancel: "Avbryt",
				modalApply: "Använd",
				organizeHeader: "Organisera färden",
				organizeGeneralCaption: "Sortera färdpunkterna genom att dra och släppa",
				organizeDelete: "Ta bort",
				organizeHide: "Dölj",
				addMaxPointReached: "Du har uppnått det maximala antalet punkter som tillåts av ikonuppsättningen och det går inte att lägga till fler turpunkter.<br /><br />Tänk på att om du tar bort befintliga punkter måste du läsa in programmet igen.",
				addMaxPointReachedMobile: "Du har tyvärr nått det maximala antalet punkter som tillåts och bilden kan inte läggas till.",
				addClose: "Stäng",
				addHeader: "Lägg till en ny turpunkt",
				addTabPicture: "Bild",
				addTabInformation: "Information",
				addTabLocation: "Plats",
				addSelectCaption: "Välj eller släpp bild",
				addSelectCaptionNoFileReader: "Välj bild",
				addChangePhoto: "Ändra bild och miniatyrbild",
				addPictureResolutionIntro: "Bildens upplösning är högre än vad som krävs:",
				addPictureResolutionOldBrowser: "Bildens upplösning är högre än vad som krävs. Optimera Map Tour-upplevelsen genom att ange en lägre upplösning än %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Ändra bildens upplösning till %RESOLUTION%",
				addPictureResolutionKeep: "Behåll den ursprungliga upplösningen, %RESOLUTION%",
				addSelectThumbnail: "Välj miniatyrbild",
				addNoThumbSelected: "Ingen miniatyrbild har valts",
				addThumbSelected: "Vald",
				addCameraSettingsHeader: "KAMERAINSTÄLLNINGAR",
				addThumbnailHeader: "MINIATYRBILD",
				addLabelName: "Namn",
				addLabelDescription: "Bildtext",
				addTextPlaceholder: "Skriv något",
				addLocatePlaceholder: "Hitta en adress eller plats",
				addPinColor: "Färg",
				addLatitude: "Latitud",
				addLongitude: "Longitud",
				addLatitudePlaceholder: "t.ex. 34.056",
				addLongitudePlaceholder: "t.ex. -117.195",
				addUploading: "Laddar upp färdpunkt",
				addSave: "Lägg till färdpunkt",
				addMobileUploading: "Laddar upp bild",
				addMobileName: "Ange ett namn",
				addMobileNameMandatory: "Ett fel har uppstått, ange ett namn.",
				addMobileError: "Något har tyvärr gått fel",
				settingsHeader: "Programinställningar",
				settingsTabLayout: "Layout",
				settingsTabColor: "Färger",
				settingsTabLogo: "Rubrik",
				settingsTabFields: "Data",
				settingsTabExtent: "Utbredning",
				settingsTabZoom: "Zoomnivå",
				settingsLayoutExplain: "Välj en av de två programlayouter som erbjuds.",
				settingsLayoutProfessional: "Trepanelslayout",
				settingsLayoutModern: "Integrerad layout",
				settingsLayoutSelected: "Markerad layout",
				settingsLayoutSelect: "Markera denna layout",
				settingsColorExplain: "Ändra utseende genom att välja ett fördefinierat tema, eller skapa ett eget.",
				settingsLabelColor: "Färger på rubrik, innehåll och sidfot",
				settingsLogoExplain: "Anpassa rubriklogotypen (maxstorlek är 250 x 50 px).",
				settingsLogoEsri: "Esris logotyp",
				settingsLogoNone: "Ingen logotyp",
				settingsLogoCustom: "Egen logotyp",
				settingsLogoCustomPlaceholder: "Bild-URL",
				settingsLogoCustomTargetPlaceholder: "Genomklickningslänkar",
				settingsLogoSocialExplain: "Anpassa den övre högra rubriklänken.",
				settingsLogoSocialText: "Text",
				settingsLogoSocialLink: "Länk",
				settingsDataFieldsExplain: "Välj fotonamn, bildtext och färgfält.",
				settingsDataFieldsError: "Programmet kan inte identifiera rätt namn, bildtext eller färgdata. Välj de fält som ska användas här. Inställningarna kan ändras senare.",
				settingsFieldsLabelName: "Namn",
				settingsFieldsLabelDescription: "Bildtext",
				settingsFieldsLabelColor: "Färg",
				settingsExtentExplain: "Ange ursprungsinnehåll för Map Tour via den interaktiva kartan nedan.",
				settingsExtentExplainBottom: "Denna utbredning används bara om den inkluderar den första färdpunkten. Värdet behålls i webbkartans ursprungsinnehåll.",
				settingsExtentDrawBtn: "Rita en ny utbredning",
				settingsExtentModifyBtn: "Redigera aktuell utbredning",
				settingsExtentApplyBtn: "Använd på huvudkartan",
				settingsZoomExplain: "Ställ in zoom för berättelsepunkter efter introduktionen (valfritt).",
				settingsLabelZoom: "Skala/nivå",
				settingsZoomFirstValue: "Ingen",
				settingsFieldError : "Välj ett fält i varje lista",
				dataHeader: "Programdata",
				dataExplain: "Din webbkarta innehåller ingen geoobjektstjänst. Gör klart dialogrutan och skapa en värdbaserad geoobjektstjänst för ditt ArcGIS.com-organisationskonto. Geoobjektstjänsten kommer att läggas till i webbkartan och delas offentligt, men bara du har behörighet att lägga till/redigera och ta bort.<br /><br />Programmet kan bara visas av dig tills du delar det med andra. <strong>När din Map Tour är klar delar du programmet via objektsidan.</strong>",
				dataNameLbl: "Tjänstnamn",
				dataFolderListLbl: "Mapp",
				dataFolderListFetching: "Hämtar mappar ...",
				dataRootFolder: "Rot",
				dataNameError: "Ange ett namn för den framtida tjänsten",
				dataFolderError: "Välj en giltig mapp",
				dataSrcContainsInvalidChar: "Geoobjektstjänstens namn innehåller ett eller flera ogiltiga tecken (<, >, #, %, :, \", ?, &, +, / eller \).",
				dataSrvAlreadyExistsError: "Det finns redan en tjänst med det namnet inom organisationen. Välj ett annat namn.",
				dataBtnClose: "Avbryt turen",
				dataBtnSave: "Skapa tjänsten",
				dataFooterProgress: "Processen pågår",
				dataFooterSucceed: "Processen lyckades. Objektet laddas",
				dataFooterError: "Processen misslyckades. Försök igen",
				tabError: "Sök efter fel i alla flikar",
				introRecordBtn: "Intro",
				introRecordActivate: "Använd den första punkten som introduktion"
			},
			addPopupJS: {
				uploadingPicture: "Laddar upp bild",
				uploadSuccess: "Uppladdningen lyckades",
				uploadError: "Det uppstod ett fel när bilden skulle laddas upp",
				notJpg: "Välj ett foto i jpeg-format som ska laddas upp",
				errorNoPhoto: "Välj en bild att ladda upp",
				errorNoThumbnail: "Välj en miniatyrbild att ladda upp",
				errorNoName: "Ange ett namn för denna färdpunkt",
				errorNoDescription: "Ange en bildtext för färdpunkten",
				errorNoLocation: "Ange en plats för denna färdpunkt"
			},
			builderJS: {
				noPendingChange: "Ingen väntande ändring",
				unSavedChangeSingular: "1 osparad ändring",
				unSavedChangePlural: "osparade ändringar",
				popoverDiscard: "Vill du kasta alla osparade ändringar?",
				yes: "Ja",
				no: "Nej",
				popoverLoseSave: "Om du öppnar vyn förlorar du alla osparade ändringar",
				ok: "OK",
				popoverSaveWhenDone: "Glöm inte att spara när du är klar",
				closeWithPendingChange: "Vill du bekräfta åtgärden? Du kommer att förlora dina ändringar.",
				gotIt: "OK",
				savingApplication: "Sparar programmet",
				saveSuccess: "Programmet har sparats",
				saveError: "Det gick inte att spara, försök igen",
				dragColorPicker: "Flytta runt mig<br />eller ändra min färg",
				dataWarningExtent: "Det finns data utanför webbkartans utbredning. Dessa data kommer inte att användas som färdpunkter. Ändra kartans utbredning om du vill använda dem.",
				dataWarningVisibi: "Ditt Map Tour-lager är inte synligt med kartans aktuella utbredning. Kontrollera att ditt Map Tour-lager är synligt med en större karta i storleken %MAPSIZE%.",
				dataWarningEdit: "Redigera webbkarta",
				dataWarningClose: "Stäng",
				signIn: "Logga in med ett konto på",
				signInTwo: "och spara programmet."
			},
			organizePopupJS: {
				messageStart: "Du har valt att ta bort",
				messageSinglePoint: "en färdpunkt",
				messageMultiPoint: "färdpunkter",
				messagePermantRemove: "Detta tar för alltid bort",
				messageRecord: "posten",
				messageRecordPlural: "posterna",
				messageConfirm: "från databasen. Vill du fortsätta?",
				labelButtonShow: "Visa",
				labelButtonHide: "Dölj"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "This will permanently delete the picture and thumbnail",
				popoverDeleteWarningThumb: "This will permanently delete the thumbnail",
				popoverUploadingPhoto: "Laddar upp bild och miniatyrbild",
				popoverUploadingThumbnail: "Laddar upp miniatyrbild",
				popoverUploadSuccessful: "Uppladdningen lyckades",
				popoverUploadError: "Uppladdningen misslyckades, försök igen",
				changePicAndThumb: "Byt bild",
				changeThumb: "Byt miniatyrbild",
				selectPic: "Byt bild",
				selectThumb: "Byt miniatyrbild",
				uploadPicAndThumb: "Använd"
			},
			headerJS:{
				editMe: "Redigera mig!",
				templateTitle: "Ange malltitel",
				templateSubtitle: "Ange underrubrik för mallen"
			},
			crossFaderJS:{
				setPicture: "Ange bildens namn",
				setCaption: "Ange bildtext till bilden"
			}
        }
    })
);
