define(
({
		viewer: {
			loading: {
				step1: "ĮKELIAMA APLIKACIJA",
				step2: "ĮKELIAMI DUOMENYS",
				step3: "INICIJUOJAMA KELIONĖ",
				loadBuilder: "PERSIJUNGIAMA Į KŪRIMO REŽIMĄ",
				fail: "Atsiprašome, kelionės žemėlapyje įkėlimas nepavyko",
				failButton: "Bandyti vėl"
			},
			errors: {
				boxTitle: "Įvyko klaida",
				portalSelf: "Kritinė klaida: Nepavyko gauti portalo konfigūracijos",
				invalidConfig: "Kritinė klaida: Neteisinga konfigūracija",
				invalidConfigOwner: "Kritinė klaida: Neteisinga konfigūracija (nenurodytas teisėtas savininkas)",
				invalidConfigNoWebmap: "Kritinė klaida: Neteisinga konfigūracija (index.html nenurodytas internetinis žemėlapio ar aplikacijos identifikatorius)",
				createMap: "Žemėlapio sukurti nepavyko",
				invalidApp: "Kritinė klaida: Negalima įkelti aplikacijos",
				noLayer: "Internetiniame žemėlapyje nėra kelionei žemėlapyje reikalingų duomenų.",
				noLayerMobile: "Sveiki atvykę į Kelionės žemėlapyje aplikaciją. Aplikacija dar nesukonfigūruota. Kelionės žemėlapyje kūrimo būsena mobiliuose įrenginiuose nėra palaikoma.",
				noLayerView: "Sveiki atvykę į Kelionės žemėlapyje aplikaciją.<br />Aplikacija dar nesukonfigūruota.",
				appSave: "Klaida įrašant internetinę aplikaciją",
				mapSave: "Klaida įrašant internetinį žemėlapį",
				featureServiceLoad: "Klaida įkeliant elementų paslaugą",
				notAuthorized: "Neturite teisių pasiekti šią aplikaciją",
				oldBrowserTitle: "Naršyklė nėra pilnai palaikoma",
				noBuilderIE8: "Kelionės žemėlapyje kūrimo įrankis nepalaikomas versijose žemesnėse nei Internet Explorer 9.",
				ie10Win7Explain: "Kelionės žemėlapyje kūrimo būsena nepalaikoma naudojant Internet Explorer 10 su Windows 7. Turite <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>rankiniu būdu nustatyti naudotis Internet Explorer 9 standartu</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>pažeminti į Internet Explorer 9 versiją</a> arba atsinaujinti į Windows 8.",
				oldBrowserExplain: "Ši naršyklė nepalaiko automatinio miniatiūrų iš į kelionės žemėlapyje įkeltų paveikslėlių kūrimo. Galite kurti kelionę žemėlapyje naudojant šią naršyklę, tačiau turėsite kiekvienam įkeltam paveikslėliui nurodyti atskirą miniatiūros paveikslėlį.",
				oldBrowserExplain2: "Naršymo pagerinimui, <a href='http://browsehappy.com/' target='_blank'>atnaujinkite savo naršyklę</a> arba <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>aktyvinkite Google Chrome Frame skirtą Internet Explorer</a>.",
				oldBrowserExplain3: "Kelionės žemėlapyje kūrėjas neveikia naudojant Internet Explorer 10 su Windows XP.",
				oldBrowserClose: "Užverti"
			},
			mobileHTML: {
				showIntro: "RODYTI PAVADINIMĄ",
				hideIntro: "SLĖPTI PAVADINIMĄ",
				navList: "Sąrašas",
				navMap: "Žemėlapis",
				navInfo: "Paveikslai",
				introStartBtn: "Pradėti"
			},
			desktopHTML: {
				storymapsText: "Pristatomasis žemėlapis",
				builderButton: "Perjungti į kūrimo būseną",
				bitlyTooltip: "Gauti sutrumpintą aplikacijos nuorodą"
			},
			builderHTML: {
				panelHeader: "APLIKACIJOS KONFIGŪRACIJA",
				buttonSave: "ĮRAŠYTI",
				buttonDiscard: "ATSISAKYTI",
				buttonSettings: "Nuostatos",
				buttonView: "Peržiūros būsena",
				buttonItem: "Atverti aplikaciją",
				buttonHelp: "Pagalba",
				buttonOrganize: "Tvarkyti",
				buttonAdd: "Pridėti",
				buttonImport: "Importuoti",
				buttonImportDisabled: "Importavimas neįmanomas naudojant elementų paslaugą su priedais",
				dataEditionDisabled: "Duomenų redagavimas neleistas CSV duomenų šaltinyje",
				dataSourceWarning: "Žemėlapio duro duomenų sluoksnis pasikeitė. Tačiau jei elementų ID ne tas pats, turite perkrauti tvarką ir paslėptus taškus <b>Organizuoti</b>. Jei skiriasi lauko pavadinimas, turite perkrauti laukų nustatymus <b>duomenų skiltyje nustatymuose</b>.",
				dataPicError0a: "Šiame ture yra <b>%NB%</b> neatitinkančių vaizdų URL.",
				dataPicError0b: "Šiame ture gali būti <b>%NB%</b> neatitinkančių vaizdų URL.",
				dataPicError1: "Žemėlapio turui dabar privaloma, kad vaizdo URL baigtųsi vienu iš šių plėtinių: .jp(e)g, .png, .gif arba .bmp.",
				dataPicError2: "Reikalavimas neįtakos jūsų esamo publikuoto žemėlapio turo. Tačiau, kad galėtumėt naudoti interaktyvų kūrėją, jums pirmiausiai reikia išspręsti URL klausimą atliekant vieną iš šių dviejų veiksmų:",
				dataPicError3: "Redaguoti URL",
				dataPicError4: "Tai pridės <i>#isPicture</i> į nepalaikomo vaizdo URL pabaigą. Dauguma serverių palaiko URL plėtinius. Tačiau, kai tik atliksite šį veiksmą, turite užtikrinti, kad atnaujinti nuotraukų URL veikia, naviguodami per taškus. Jei pakraunama kiekviena nuotrauka, galite išsaugoti žemėlapio turą. Jei <b>nuotraukos yra pažeistos, nesaugokite žemėlapio turo</b>. Vietoje to, perkraukite kūrėją ir atlikite antrą veiksmą.",
				dataPicError5: "Apribokite turą iki nuotraukų",
				dataPicError6: "Šis pasirinkimas lems tai, kad visi URL bus laikomi nuotraukomis, tačiau tuomet negalėsite pridėti video naudodami interaktyvų kūrėją. Šis veiksmas yra grįžtamas, jei nuspręstumėt pridėti video ateityje.",
				dataPicError7: "Jūsų žemėlapio turas buvo apribotas iki nuotraukų, video negali būti naudojami. Jei pasirinksite pašalinti šį ribojimą, prieš išsaugodami žemėlapio turą patikrinkite ar jūsų nuotraukos dar vis užkraunamos. Jei reikės, jūs galėsite atkurti šį apribojimą.",
				dataPicError8: "Pašalinti nuotraukų apribojimą",
				dataPicError9: "Jei šie URL nurodo į video, galite ignoruoti šį įspėjimą. Jei jie nurodo nuotrauką, galite atlikti vieną iš šių dviejų veiksmų:",
				modalCancel: "Atsisakyti",
				modalApply: "Vykdyti",
				organizeHeader: "Tvarkyti kelionę",
				organizeGeneralCaption: "Kelionės taškų rikiavimui, pertempkite juos",
				organizeDelete: "Pašalinti",
				organizeHide: "Slėpti",
				organizeReset: "Perkrauti tvarką ir paslėptus taškus",
				addMaxPointReached: "Pagal piktogramų rinkinį, pasiekėte maksimalų leistiną taškų skaičių, ir nebegalite pridėti naujų kelionės taškų.<br /><br />Jei pašalinsite esamus taškus, reiks aplikaciją įkelti iš naujo.",
				addMaxPointReachedMobile: "Apgailestaujame, pasiektas maksimalus leistinas taškų skaičius, šio paveikslėlio pridėti negalima.",
				addClose: "Užverti",
				addHeader: "Pridėti naują kelionės tašką",
				addTabPicture: "Daugialypė informacija",
				addTabInformation: "Informacija",
				addTabLocation: "Vieta",
				addSelectCaption: "Pažymėkite arba užtempkite paveikslėlį",
				addNoteVideo: "Norėdami gauti instrukcijas video naudojimui, žiūrėkite Pagalbą",		
				addSelectCaptionNoFileReader: "Pasirinkite nuotrauką",
				addChangePhoto: "Pakeiskite paveikslėlį ir miniatiūrą",
				addPictureResolutionIntro: "Paveikslėlio skiriamoji geba didesnė nei reikalaujama:",
				addPictureResolutionOldBrowser: "Paveikslėlio skiriamoji geba didesnė nei būtina. Optimizuokite Kelionę Žemėlapyje nurodant skiriamąją gebą mažesnę nei būtina %RECOMMENDED_RES%.",
				addPictureResolutionResize: "Pakeisti paveikslėlio skiriamąją gebą į %RESOLUTION%",
				addPictureResolutionKeep: "Išlaikyti originalią skiriamąją gebą %RESOLUTION%",
				addSelectThumbnail: "Parinkite miniatiūrą",
				addNoThumbSelected: "Miniatiūra neparinkta",
				addThumbSelected: "Pažymeta",
				addCameraSettingsHeader: "FOTOAPARATO NUSTATYMAI",
				addThumbnailHeader: "MINIATIŪRA",
				addLabelPicUrl: "Nuotrauka",
				addLabelThumbUrl: "Miniatiūra",
				addTextPlaceholderUrl: "Įveskite vaizdo URL",
				addTextPlaceholderUrl2: "Įveskite Youtube puslapio URL",
				addTextPlaceholderUrl3: "Įveskite Vimeo puslapio URL",
				addTextPlaceholderUrl4: "Įveskite video nuorodos URL",
				addLabelVideo: "Video",
				addMediaVideoOther: "Kita",
				addMediaVideoHelp: "Patikrinti URL ir gauti miniatiūrą",
				addMediaVideoHelpTooltip1: "Pavyko patikrinti",
				addMediaVideoHelpTooltip2: "Nepavyko patikrinti",
				addMediaVideoHelpTooltip4: "Raskite nustatymą įdėti video ir nukopijuokite kode esantį video URL",
				addLabelName: "Pavadinimas",
				addLabelDescription: "Antraštė",
				addTextPlaceholder: "Ką nors įrašykite",
				addLocatePlaceholder: "Nurodykite adresą arba vietą",
				addPinColor: "Spalva",
				addLatitude: "Platuma",
				addLongitude: "Ilguma",
				addLatitudePlaceholder: "pvz. 34.056",
				addLongitudePlaceholder: "pvz. -117.195",
				addUploading: "Įkeliamas kelionės taškas",
				addSave: "Pridėti kelionės tašką",
				addMobileUploading: "Įkeliamas paveikslėlis",
				addMobileName: "Įveskite pavadinimą",
				addMobileNameMandatory: "Klaida, prašome įvesti pavadinimą.",
				addMobileError: "Atsiprašome, įvyko nenumatyta klaida",
				settingsHeader: "Aplikacijos nuostatos",
				settingsTabLayout: "Maketas",
				settingsTabColor: "Spalvos",
				settingsTabLogo: "Antraštė",
				settingsTabFields: "Duomenys",
				settingsTabExtent: "Aprėptis",
				settingsTabZoom: "Didinimo lygis",
				settingsLayoutExplain: "Pasirinkite iš pateiktų aplikacijos šablonų.",
				settingsLayoutProfessional: "Trijų skydelių maketas",
				settingsLayoutModern: "Bendras maketas",
				settingsLayoutSelected: "Pažymėtas maketas",
				settingsLayoutSelect: "Pažymėkite šį maketą",
				settingsLayoutNote: "Turėkite omenyje, kad taškuose su video, plakatai visuomet bus dedami po video, net jei šis pasirinkimas nepažymėtas.",
				settingsColorExplain: "Keisti atvaizdavimą pasirenkant iš anksto paruoštą apipavidalinimą arba sukuriant savą.",
				settingsLabelColor: "Antraštės, turinio, ir poraštės spalvos",
				settingsLogoExplain: "Pritaikyti antraštės logotipą (maksimalus dydis: 250 x 50px).",
				settingsLogoEsri: "Esri logotipas",
				settingsLogoNone: "Logotipo nėra",
				settingsLogoCustom: "Savas logo",
				settingsLogoCustomPlaceholder: "Paveikslėlio URL",
				settingsLogoCustomTargetPlaceholder: "Vieno mygtuko paspaudimo nuoroda",
				settingsLogoSocialExplain: "Priderinkite antraštės viršutinę dešinę nuorodą.",
				settingsLogoSocialText: "Tekstas",
				settingsLogoSocialLink: "Nuoroda",
				settingsLogoSocialDisabled: "Šią funkciją išjungė Administratorius",
				settingsDataFieldsExplain: "Nurodykite nuotraukos pavadinimo, antraštės ir spalvų laukus.",
				settingsDataFieldsError: "Aplikacijai nepavyko nustatyti atitinkamų duomenų apie pavadinimą, antraštę ir spalvas. Nurodykite laukus kuriuos tam naudoti. Šios nuostatos gali būti pakeistos vėliau.",
				settingsFieldsLabelName: "Pavadinimas",
				settingsFieldsLabelDescription: "Antraštė",
				settingsFieldsLabelColor: "Spalva",
				settingsFieldsReset: "Perkrauti laukų pažymėjimą",
				settingsExtentExplain: "Nustatykite kelionės žemėlapyje pradinę aprėptį naudojant žemiau esantį žemėlapį.",
				settingsExtentExplainBottom: "Aprėptis, kurią nustatote pakeis internetinio žemėlapio pradinę aprėptį. Turėkite omenyje, kad ši aprėptis nėra naudojama jei joje nėra pirmo turo taško. Šiuo atveju turas atveriamas turas bus centruojamas į pirmą tašką.",
				settingsExtentDateLineError: "Aprėptis negali būti abipus 180° ilgumos",
				settingsExtentDateLineError2: "Klaida apskaičiuojant aprėptį",
				settingsExtentDrawBtn: "Brėžti naują aprėptį",
				settingsExtentModifyBtn: "Redaguoti aprėptį",
				settingsExtentApplyBtn: "Peržiūrėti žemėlapio ture",
				settingsExtentUseMainMap: "Naudoti žemėlapio turo aprėptį",
				settingsZoomExplain: "Po pristatymo, nurodykite kiek išdidinti pasakojimo taškus  (neprivaloma).",
				settingsLabelZoom: "Mastelis/lygis",
				settingsZoomFirstValue: "Nėra",
				settingsFieldError: "Kiekviename sąraše nurodykite lauką",
				dataExplain: "Į internetinį žemėlapį bus pridėta elementų paslauga. Ji nebus bendrinama su niekuo, ir tik jūs galite pridėti, redaguoti ar trinti teises.<br /><br />Jei pakeisite aplikacijos bendrinimo teises, sistema paklaus, ar norėsite atnaujinti elementų paslaugos bendrinimo konfigūraciją. Tai yra būtina, kad vartotojai galėtų pasiekti jūsų duomenis. Jūs liksite vieninteliu vartotoju su redagavimo teisėmis.",
				dataNameLbl: "Paslaugos pavadinimas",
				dataFolderListLbl: "Katalogas",
				dataFolderListFetching: "Gaunami katalogai ...",
				dataRootFolder: "Šaknis",
				dataNameError: "Įveskite elementų paslaugos pavadinimą",
				dataFolderError: "Nurodykite teisingą katalogą",
				dataSrcContainsInvalidChar: "Elementų paslaugos pavadinime yra neleistinų ženklų (-, <, >, #, %, :, \", ?, &, +, /, arba \).",
				dataSrvAlreadyExistsError: "Paslauga tokiu pavadinimu organizacijoje jau yra. Nurodykite kitą pavadinimą.",
				dataBtnSave: "Sukurti paslaugą",
				dataFooterProgress: "Vyksta kūrimas",
				dataFooterSucceed: "Kūrimas pavyko. Įkeliama",
				dataFooterError: "Kūrimas nepavyko. Pabandykite iš naujo",
				tabError: "Patikrinkite ar naršyklės skirtukuose nėra klaidų",
				introRecordBtn: "Įžanga",
				introRecordActivate: "Pirmą tašką naudoti kaip įžangą"
			},
			addPopupJS: {
				uploadingPicture: "Įkeliamas paveikslėlis",
				uploadSuccess: "Įkėlimas pavyko",
				uploadError: "Klaida įkeliant paveikslėlį",
				notJpg: "Nurodykite kurią jpeg nuotrauką įkelti",
				errorNoPhoto: "Nurodykite kurį įkelti paveikslėlį",
				errorNoThumbnail: "Nurodykite kurią įkelti miniatiūrą",
				errorInvalidPicUrl: "Įveskite veikiančią nuotrauką (pradžioje turi būti http(s)://, pabaigoje - jpg, png, gif arba bmp). Galite URL pabaigoje naudoti '#isPicture', kad nepaisyti šios taisyklės.",
				errorInvalidThumbUrl: "Įveskite veikiančią miniatiūrą (pradžioje turi būti http(s)://, pabaigoje - jpg, png, gif arba bmp).",
				errorInvalidVideoUrl: "Įveskite veikiantį video URL (prasidedantį http(s)://)",
				errorNoName: "Įveskite šio kelionės taško pavadinimą",
				errorNoDescription: "Įveskite šio kelionės taško antraštę",
				errorNoLocation: "Nurodykite šio kelionės taško vietą"
			},
			builderJS: {
				noPendingChange: "Laukiančių pakeitimų nėra",
				unSavedChangeSingular: "1 neišsaugotas pakeitimas",
				unSavedChangePlural: "neišsaugoti pakeitimai",
				popoverDiscard: "Ar tikrai norite atsisakyti neįrašytų pakeitimų?",
				yes: "Taip",
				no: "Ne",
				popoverLoseSave: "Atverdami peržiūros programą, prarasite visus neįrašytus pakeitimus",
				ok: "Gerai",
				popoverSaveWhenDone: "Užbaigus nepamirškite įrašyti",
				closeWithPendingChange: "Ar tikrai patvirtinate šį veiksmą ? Atlikti pakeitimai bus prarasti.",
				gotIt: "Gerai",
				savingApplication: "Aplikacija įrašoma",
				saveSuccess: "Aplikacija įrašyta sėkmingai",
				saveError: "Įrašyti nepavyko, pabandykite iš naujo",
				dragColorPicker: "Traukite aplink<br />arba pakeiskite spalvą",
				dataWarningExtent: "Turite duomenų nepatenkančių į žemėlapio aprėptį. Šie duomenys nebus naudojami kaip kelionės taškai, jei norite juos naudoti - pakeiskite žemėlapio aprėptį.",
				dataWarningVisibi: "Šioje aprėptyje, Kelionės Žemėlapyje sluoksnis nėra matomas. Patvirtinkite, kad Kelionės Žemėlapyje sluoksnis yra matomas naudojant %MAPSIZE% dydžio žemėlapį.",
				dataWarningEdit: "Redaguoti internetinį žemėlapį",
				dataWarningClose: "Užverti",
				signIn: "Prisijunkite su paskyra prie",
				signInTwo: "aplikacijai įrašyti."
			},
			organizePopupJS: {
				messageStart: "Nusprendėte panaikinti",
				messageSinglePoint: "vienas kelionės taškas",
				messageMultiPoint: "kelionės taškai",
				messagePermantRemove: "Tai visam laikui pašalins",
				messageRecord: "įrašą",
				messageRecordPlural: "įrašus",
				messageConfirm: "iš duomenų bazės. Ar norite tęsti?",
				labelButtonShow: "Rodyti",
				labelButtonHide: "Slėpti"
			},
			picturePanelJS: {
				popoverDeleteWarningPicAndThumb: "Šis veiksmas negrįžtamai panaikins paveikslėlį ir miniatiūrą",
				popoverDeleteWarningThumb: "Šis veiksmas negrįžtamai panaikins miniatiūrą",
				popoverUploadingPhoto: "Įkeliamas paveikslėlis ir miniatiūra",
				popoverUploadingThumbnail: "Įkeliama miniatiūra",
				popoverUploadSuccessful: "Įkėlimas pavyko",
				popoverUploadError: "Išsiuntimas nepavyko, pabandykite iš naujo",
				changePicAndThumb: "Pakeisti paveikslėlį",
				changeThumb: "Keisti miniatiūrą",
				selectPic: "Pakeisti mediją",
				selectThumb: "Keisti miniatiūrą",
				uploadPicAndThumb: "Vykdyti"
			},
			headerJS:{
				editMe: "Redaguok !",
				templateTitle: "Nustatyti šablono antraštę",
				templateSubtitle: "Nustatyti šablono poantraštę"
			},
			crossFaderJS:{
				setPicture: "Nustatyti paveikslėlio antraštę",
				setCaption: "Nustatyti paveikslėlio pavadinimą"
			},
			importPopup: {
				title: "Importuoti",
				prevBtn: "Grįžti",
				nextBtn: "Toliau"
			},
			importPopupHome: {
				header: "Kur saugomi jūsų paveikslai?"
			},
			onlinePhotoSharingCommon: {
				disabled: "Šią funkciją išjungė Administratorius",
				disabledPortal: "Šis funkcionalumas išjungtas Portal for ArcGIS",
				header1: "Paveikslai turi būti viešai bendrinami.",
				header2: "Importavimas bus apribotas iki %NB1% paveikslų, atsižvelgiant į %NB2% taškų per valandą apribojimą.",
				emptyDataset: "Klaida, paveikslų nerasta",
				footerImport: "Importuoti",
				selectAlbum: "Pasirinkte viešą albumą",
				selectAlbum2: "Pasirinkite albumą",
				pleaseChoose: "Pasirinkite",
				userLookup: "Ieškoti",
				userLookingup: "Ieškoma",
				csv: "Nuoroda CSV faile",
				fromScratch: "Pradėti iš naujo",
				select: "Pažymėti",
				locUse: "Naudoti paveikslų vietas",
				locExplain: "Jūs galite nenorėti naudoti paveikslų vietų, kadangi jos gali būti paveldėtos iš albumo. Rezultate visos nuotraukos gali atsidurti toje pačioje vietoje."
			},
			viewFlickr: {
				header: "Įveskite Flickr vartotojo vardą ir pasirinkite importuojamą nuotraukų rinkinį ar raktinę frazę.",
				userInputLbl: "Įveskite vartotojo vardą",
				signInMsg2: "Vartotojas nerastas",
				selectSet: "Pasirinkite nuotraukų rinkinį",
				selectTag: "Pasirinkite raktinę frazę",
				footerImportTag: "Importuoti pasirinktą raktinę frazę",
				footerImportSet: "Importuoti pasirinktą rinkinį"
			},
			viewFacebook: {
				header: "Autentifikuokitės su Facebook vartotojo paskyra arba naudokite viešą puslapį. Asmeniniai albumai gali būti naudojami kuriant viešą žemėlapio turą, kuriam nereikalinga Facebook autentifikacija.",
				leftHeader: "Facebook vartotojas",
				rightHeader: "Facebook puslapis",
				pageExplain: "Facebook puslapis yra viešas prekės ženklas, produktas ar įžymybė kaip <b>esrigis</b>. Jūs galite pamatyti puslapio pavadinimą po pirmo '/' puslapio URL.",
				pageInputLbl: "Įveskite puslapio pavadinimą",
				lookupMsgError: "Puslapis nerastas"
			},
			viewPicasa: {
				header: "Įveskite Picasa ar Google+ paskyros elektroninį paštą arba ID.",
				userInputLbl: "Įveskite elektroninį paštą arba ID",
				signInMsg2: "Paskyra nerasta",
				howToFind: "Kaip surasti paskyros ID",
				howToFind2: "Nukopijuokite skaičius tarp pirmo ir antro '/' bet kuriame Picasa ar G+ puslapyje"
			},
			viewCSV: {
				uploadBtn: "Pasirinkite arba nužymėkite CSV failą",
				resultHeaderEmpty: "CSV tuščias",
				resultHeaderSuccess: "Sėkmingai užkrauta %NB_POINTS% taškų",
				resultHasBeenLimited: "Importavimas buvo apribotas iki pirmų %VAL1% taškų iš %VAL2%, kad atitiktų %VAL3% taškų vienoje kelionėje apribojimą",
				browserSupport: "Jūsų naršyklė nepalaikoma. Norėdami naudoti CSV, jūs turite <a href='http://browsehappy.com/' target='_blank'>atnaujinti naršyklę</a> arba naudoti ArcGIS.com internetinę žemėlapių peržiūros aplikaciją (žiūr. Pagalbą).",
				errorLatLng: "Platumos ir ilgumos laukai nesurasti. Galimos reikšmės platumai yra: <i>%LAT%</i>, o ilgumai: <i>%LONG%</i>.",
				errorFieldsExplain: "Įkrovimas nepavyko, kadangi nebuvo rasti šie būtini laukai",
				errorFieldsName: "<b>Name</b> galimos reikšmės yra: %VAL%",
				errorFieldsDesc: "<b>Description</b> galimos reikšmės yra: %VAL%",
				errorFieldsUrl: "<b>Picture URL</b> galimos reikšmės yra: %VAL%",
				errorFieldsThumb: "<b>Thumbnail URL</b> galimos reikšmės yra: %VAL%",
				errorFields2Explain: "Įkrovimas nepavyko, nes CSV nenaudoja tų pačių atributų, kokie yra sluoksnyje:",
				errorFields2Name: "<b>Name</b> naudoja %VAL1% vietoje %VAL2%",
				errorFields2Desc: "<b>Description</b> naudoja %VAL1% vietoje %VAL2%",
				errorFields2Url: "<b>Picture URL</b> naudoja %VAL1% vietoje %VAL2%",
				errorFields2Thumb: "<b>Thumbnail URL</b> naudoja %VAL1% vietoje %VAL2%",
				resultFieldsAll: "Visi atributai buvo importuoti",
				resultFieldsNotAll: "Šie atributai nebuvo importuoti, nes neegzistuoja žemėlapio sluoksnyje:",
				resultFieldsNotAll2: "Šie atributai nebuvo importuoti:",
				footerNextBtnResult: "Importavimas į internetinį žemėlapį",
				footerProgress: "Vyksta importavimas",
				footerSucceed: "Importavimas pavyko. Kraunama"
			},
			viewGeoTag: {
				header: "Spustelkite paveikslus, kuriuos norite importuoti, norėdami juos rasti",
				headerMore: "Kodėl mano paveikslai nerasti?",
				headerExplain: "Jei jūsų paveiklai turi veikiantį adresą, jie bus automatiškai rasti žemėlapyje ir pateikti antroje skiltyje.<br /><br />Pagal nutylėjimą Picasa ir Flickr nenaudoja paveikslų EXIF vietos metaduomenų. Patikrinkite Flickr/Picasa privatumo nustatymų skiltį, kad įgalinti paveikslų vietų naudojimą. Jums gali reikti pilnai perimportuoti paveikslus į Flickr/Picasa.<br /><br />Naudojant Facebook, jūs turite paspausti ant kiekvieno paveikslo, paspausti Redaguoti ir pasirinkti vietą iš siūlomų pasirinkimų, kurie yra sudaryti paveikslų EXIF metaduomenų pagrindu.",
				leftPanelTab1: "Norint rasti",
				leftPanelTab2: "Rasti",
				clickOrTap: "Spustelkite žemėlapį, kurį norite rasti",
				clickDrop: "Neimportuoti",
				footerImport: "Importuoti",
				footerProgress: "Vyksta importavimas",
				footerSucceed: "Importavimas pavyko. Kraunama...",
				loading: "Kraunama",
				error: "Nuotraukos kelio importas nepavyko, vietos ignoruojamos."
			},
			initPopup: {
				title: "Sveiki atvykę į Žemėlapio turo kūrėją",
				prevBtn: "Grįžti",
				nextBtn: "Toliau"
			},
			initPopupHome: {
				header2: "Šis įrankis padės jums sukurti žemėlapio turą iš paveikslų, saugomų internete arba importuos juos į jūsų ArcGIS Online for Organization paskyrą.",
				title1: "Mano nuotraukos jau talpinamos",
				title2: "Man reikia talpinti nuotraukas",
				hostedFsNA: "Galima tik ArcGIS for Organization publikuotojui ir administratoriui",
				footer1: "Kai baigsite, nepamirškite bendrinti žemėlapio turo su vartotojais per aplikacijos elementų puslapį.",
				footer2: "Žemėlapio turo pagalba",
				footer3: "Atsisiųsti CSV šabloną",
				footer4: "\"Išsaugoti\" jei neįmanoma nukrauti",
				footerProgress: "Vyksta kūrimas",
				footerSucceed: "Kūrimas pavyko. Kraunama..."
			},
			helpPopup: {
				title: "Pagalba",
				close: "Užverti",
				tab1: {
					title: "Įvadas",
					div1: "Žemėlapio turo šablonas sukurtas, geografinės informacijos su didele fotografinio elemento reikšme, pateikimui.",
					div2: "Šablonas sukuria patrauklią, lengvą naudoti aplikacija, kuri leidžia pristatyti nedidelį rinkinį vietų žemėlapyje kaip numeruotą seką, kurią vartotojai gali naršyti.Šablonas sukurtas naudojimui bet kurioje naršyklė, bet kokiame prietaise, įskaitant išmaniuosius telefonus ir planšetinius kompiuterius.",
					div3: "Šiame gide rasite žemėlapio turo publikavimo instrukcijas, tokias kaip:",
					div4: "<ul><li><a href='http://storymaps.esri.com/stories/demo/map_tour/?webmap=7190edafe7464cb19c1caf1360cd6ee5' target='_blank'>Palm Springs Žemėlapio turas</a></li><li><a href='http://story.maps.arcgis.com/apps/MapTour/index.html?appid=4d6054b109ce482d88588d5c06a7a478' target='_blank'>Geriausias pasivažinėjimas kalnų dviračiais Nyderlanduose</a></li><li><a href='http://ugis.esri.com/LA_River_Tour/' target='_blank'>Los Andželo upių žemėlapio turas</a></li></ul>",
					div5: "Mes norėtume gauti iš jūsų žinių! Nedvejokite ir bendrinkite žemėlapio turą su mumis:",
					div6: "<ul><li><a href='mailto:storymaps@esri.com' target='_blank'>storymaps@esri.com</a></li><li><a href='http://storymaps.esri.com/home/' target='_blank'>StoryMaps interneto puslapis</a></li><li><a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a></li></ul>",
					div7: "Radote klaidą ar norėtumėt naujo funkcionalumo? Praneškite mums užregistruodami užklausą <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub projekto puslapis</a>."
				},
				tab2: {
					title: "Duomenys",
					div1: "Pagrindinis elementas, į kurį reiktų atsižvelgti kuriant žemėlapio turą - tai pasirinkti kur bus saugomos nuotraukos. Žemėlapio turas gali naudoti nuotraukas, laikomas pagrindiniuose nuotraukų bendrinimo portaluose, internetiniame serveryje ar elementų paslaugose.",
					div1a: "Žiūrėkite paskutinį šios skilties skyrių, kad gautumėt informacijos apie palaikomus nuotraukų ir video formatus.",
					div2: "Interaktyvus kūrėjas suteikia dvi galimybes paveikslų valdymui žemėlapių ture:",
					div3: "<ul><li>Galite naudoti <b>nuotraukas, kurios jau yra internete</b>, pavyzdžiui, vaizdus saugomus nuotraukų bendrinimo puslapyje, tokiame kaip Flickr arba vaizdus saugomus jūsų puslapyje. Šie vaizdai bus pasiekiami žemėlapio ture per nurodytus URL.</li><li>Taip pat galite <b>patalpinti nuotraukas iš jūsų kompiuterio</b> tiesiai į žemėlapio turą. Šiam, talpinimo, pasirinkimui būtina ArcGIS Online prenumerata ir publikuotojo arba administratoriaus teisės (kadangi automatiškai sukuriama paslauga, kurioje jūsų nuotraukos saugomos kaip priedai)</li></ul>",
					div4: "Pagrindiniai naudojimo pavyzdžiai yra:",
					div4b: "<b>Jūsų nuotraukos dar nėra talpinamos</b> ir turite ArcGIS Online prenumeratą: talpinamos elementų paslaugos naudojimas yra geriausias pasirinkimas. Kaip ir viešų nuotraukų talpinimo paslaugų atveju, mes optimizuosime jūsų nuotraukas, kad sukurtume greitai užsikraunančius vaizdus, o jūs turėsite prieigą prie visų ArcGIS platformos administravimo ir duomenų valdymo galimybių.",
					div5: "<b>Jūs nesate organizacijos narys</b>: pirmiausiai turite patalpinti nuotraukas į nuotraukų bendrinimo puslapį arba į savo interneto serverį. Tuomet vedlys padės jums panaudoti šias nuotraukas, kurios ir toliau bus talpinamos pradinėje vietoje.",
					div6: "<b>Jūs norite pernaudoti esamą elementų paslaugą</b>, kurioje saugomos jūsų nuotraukos kaip priedai arba kurios nukreipia į išorines nuotraukas: žiūrėkite detalų aprašymą žemiau.",
					div7: "<b>Esate ankstesnės žemėlapio turo šablono versijos naudotojas</b> ir jau turite CSV, kuris nukreipia į nuotraukas ir miniatiūras: jūs galėsite importuoti ir pakeisti duomenis. Vedlys palaiko tik CSV, naudojančius ilgumos/platumos laukus, adresais paremti CSV gali būti naudojami internetiniame žemėlapyje (žiūrėkite aprašymą žemiau).",
					div8: "Importuojama iš internetinių nuotraukų bendrinimo paslaugų",
					div9: "Importavimo veiksmas nurodo jau talpinamas nuotraukas, saugodamas jų URL internetinių žemėlapio elementų rinkinyje. Šios nuotraukos netalpinamos ArcGIS Online. Jei nuotraukų talpinimas sutrinka, jos nebus matomos žemėlapio ture ir vietoje jų bus naudojamas “Nuotraukos nepasiekiamos” vaizdas. Priklausomai nuo interneto tiekėjo, žemėlapio turas importuos arba neimportuos vaizdų pavadinimo, aprašo ir vietos. Šie atributai saugomi internetiniame žemėlapyje ir bet koks internetinių paslaugų redagavimas neatsispindės žemėlapio ture.",
					div10: "Nuotraukų saugojimas internetiniame serveryje",
					div11: "Jei pasirinkote patys talpinti nuotraukas, turėsite rankiniu būdu sukurti nuotraukų miniatiūras. Naudojant pilnos raiškos nuotraukas kaip miniatiūras neigiamai paveiks greitaveiką. Dėl šios priežasties primygtinai rekomenduojame naudoti internetines nuotraukų talpinimo paslaugas arba elementų paslaugas, kurios tai padarys už jus.",
					div12: "Egzistuojančios elementų paslaugos arba Shape failo naudojimas",
					div13: "Bet kuri taškinė elementų paslauga ar Shape failas gali būti naudojamas kaip žemėlapio turo duomenų šaltinis. Jūs tiesiog turite pridėti jį kaip sluoksnį į internetinį žėmėlapį per ArcGIS.com žemėlapio peržiūros aplikaciją. Jei aplikacija sluoksnyje randa reikiamus atributus, galimas visas kūrėjo funkcionalumas.",
					div14: "Reikiami laukai yra (didžiosios ir mažosios raidės - svarbu):",
					div151: "Pavadinimas",
					div152: "Aprašas",
					div153: "Nuotrauka",
					div154: "Miniatiūra",
					div155: "Spalva (pasirinktinai)",
					div16: "Pavadinimo ir aprašo laukai būtini. Jei aplikacija naudodama elementų paslaugą neranda atitinkamų laukų, peržiūros aplikacija neveiks kol nesukonfigūruosite laukų, naudotinų kūrėjui. CSV ir Shape failo sluoksniai, pridėti į internetinį žemėlapį, turi turėti visus būtinus laukus, arba kūrėjas neveiks.",
					div162: "When using a feature service that stores the pictures as attachments, <b>only the features with two attachments will be used</b>. The first attachment defines the main picture, and the second attachment defines the thumbnail.",
					div17: "Nuotraukos ir miniatiūros laukai yra privalomi elementų paslaugai be priedų. Pasirinktinos, bet primygtinai rekomenduojamos jos yra elementų paslaugoms su priedais. Jei jūsų paslauga turi įgalintus tuos pačius priedus, kūrėjas leis talpinti nuotraukas kaip priedus. Jei ne, jūs galėsite redaguoti tik nuotraukos ir miniatiūros URL.",
					div172: "Kai jie yra, nuotraukos ir miniatiūros laukai visada bus naudojami, o elementų paslaugų priedus galima bus naudoti užklausomis.",
					div173: "CSV ir Shape failų pavyzdžių galima parsisiųsti iš",
					div18: "Talpinamų elementų paslaugų kūrimas iš CSV ar Shape failo",
					div19: "Kai kuriate talpinamą elementų paslaugą iš CSV ar Shape failo, pagal nutylėjimą priedai nėra įgalinti. Kad juos įgalintumėt, atverkite elementų paslaugos elementų puslapį, spustelkite nedidelę rodyklę ties sluoksnio pasirinkimu ir pamatysite šį nustatymą. Tai atlikus Žemėlapio turas ir toliau naudos nuotraukas bei miniatiūrą, kuriuos nurodėte per atributus. Pasirinktinai, jei norite talpinti nuotraukas kaip elementų paslaugų priedus, jūs galite tai padaryti dviem mygtukais nuotraukos panelėje (\"Pakeisti nuotrauką\" ir \"Pakeisti miniatiūrą\").",
					div20: "Palaikomi paveikslų formatai ir video",
					div21: "Palaikomi nuotraukų formatai yra: <b>.jpg, .jpeg, .png, .gif and .bmp</b>. Jei jūsų medija nesibaigia vienu šių plėtinių, žemėlapio turas laikys ją video, išskyrus tuos atvejus kai naudojama elementų paslauga (žiūrėti žemiau).",
					div22: "Žemėlapio turo šablone nėra video grotuvo, todėl turite naudoti išorinį video grotuvą, kurį pateikia jūsų mėgstamas video talpinimo paslaugų tiekėjas (pasirinkite sprendimus video talpinimui ir nukopijuokite URL present, esantį duotame kode). Jei norite talpinti video patys, galite sukurti HTML puslapį, turintį grotuvą, tokį kaip <a href='http://www.videojs.com/'>Video.js</a>.",
					div23: "Interaktyvus vedlys nesuteikia dialogo video pridėjimui, naudojant elementų paslaugas su priedais, bet tai galima padaryti redaguojant jūsų duomenys už interaktyvaus vedlio ribų. Arcgis.com žemėlapių peržiūros aplikacijoje, jei pakeičiate nuotraukos laukus taip, kad jie nurodytų į išorinius video ir pridėtumėt specialų parametrą URL pabaigoje (#isVideo), jūsų medija bus laikoma video.",
					div24: "Atkreipkite dėlmesį, kad jums vis dar reikia turėti du veikiančius nuotraukų priedus arba taškas nebus naudojamas. Neįmanoma naudoti video naudojant elementų paslaugos priedus ir miniatiūrų laukus."
				},
				tab3: {
					title: "Adaptavimas",
					div1: "Kūrėjas pateikia keletą adaptavimo galimybių, kurios yra pasiekiamos per NUSTATYMAI mygtuką viršutinėje panelėje.Jei nerandate norimo pasirinkimo, mes taip pat pateikiame ir parsisiunčiamą versiją, kurią galite įdiegti savo interneto serveryje ir patobulinti, kad atitiktų jūsų poreikį.",
					div2: "Rekomenduojame naudoti talpinamąją versiją, nebent:",
					div3: "<li>Joje nėra vartotojo sąsajos adaptavimo, kurį norėtumėte turėti, pavyzdžiui, naudoti antraštės foninį vaizdą</li><li>Esate programuotojas ir norite patobulinti aplikaciją.</li>",
					div4: "Parsisiunčiama versijoja gali būti konfigūruojama per internetinio žemėlapio ar internetinės kartografavimo aplikacijos identifikatorių. Pagrindiniai panaudos atvejai yra:",
					div41: "Kuriate žemėlapio turą naudodami interaktyvų vedlį talpinamoje aplinkoje ir konfigūruojate šabloną su žemėlapių aplikacijos identifikatoriumi. Galios nustatymai, kuriuos nurodėte interaktyviame vedlyje.",
					div42: "Kuriate internetinį žemėlapį už interaktyvaus vedlio ribų ir konfigūruojate šabloną su internetinio žemėlapio identifikatoriumi. Turėsite perskaityti dokumentaciją, kad išmoktumėt konfigūruoti šabloną.",
					div43: "Atkreipkite dėmesį, kad interaktyvus vedlys galimas parsisiunčiamoje versijoje , tačiau su tam tikrais techniniais apribojimais naršyklėms, tokioms kaip senesnės už 10 versiją Internet Explorer.",
					div5: "Aplankykite <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>GitHub projekto puslapį</a>, kad sužinotumėte daugiau apie parsisiunčiamą versiją."
				},
				tab4: {
					title: "Užuominos",
					div0: "Palaikomos naršyklės",
					div0a: "Žemėlapio turo peržiūros aplikacija palaikoma IE8+. Interaktyvus vedlys palaikomas IE9+. Mes aktyviai testuojame visas naršykles, tačiau jei susiduriate su tam tikrais sunkumais, rekomenduojame naudoti Chrome.",
					div0b: "Jei susiduriate su tam tikrais sunkumais, praneškite mums. Tuo tarpu, kurdami žemėlapio turą naudojant CSV šabloną sumažinsite sąveiką su vedlio vartotojo sąsaja.",
					div1: "Paveikslai",
					div2: "Rekomenduojame gulsčią nuotraukų orientavimą vietoje stataus. Stačiai orientuotos nuotraukos gali būti naudojamos, tačiau mažesniuose ekranuose, pavyzdžiui  iPad, didelę nuotraukų dalį užstos antraštė, nes tekstas užima daugiau vietos kai jis yra atvaizduojamas didelio aukščio plote, lyginant su didelio pločio plotu. Nors žemėlapių ture gali būti naudojami skirtingų dydžių formų ir orientavimo vaizdai, rekomenduojame visiems vaizdams naudoti lygiai tą patį dydį ir formą. Taip vartotojas žiūrėdamas turą nebus blaškomas įvairaus dydžio vaizdų.",
					div2a: "Jai talpinate nuotraukas patys, rekomenduojame maksimalią <b>1090x725</b> raišką pagrindinėms nuotraukoms ir <b>140x93</b> miniatiūroms.",
					div3: "Antraštės teksto formatavimas HTML gairėmis",
					div4: "Antraštės tekste gali būti HTML gairės, nusakančios formatavimą ir nuorodas. Pavyzdžiui, šis kodas prideda nuorodą:",
					div5: "Palaikantys sluoksniai",
					div6: "Į žemėlapį galite pridėti papildomų palaikomųjų sluoksnių. Šie sluoksniai bus atvaizduojami žemėlapio ture, kad suteiktų orientaciją, foną, ir bet kuriuos kitus geografinius elementus, kuriuos tik norėtumėt atvaizduoti be žemėlapio turo elementų, tokius kaip tiriamasis rajonas, pėsčiųjų ar automobilių maršrutas ir pan. Žemėlapio turo šablonas atvaizduoja šiuos papildomus palaikomuosius sluoksnius naudojant jūsų nurodytą simbolizaciją internetiniame žemėlapyje, tačiau iškylantys langai nėra galimi.",
					div7: "Išlaikykite turą trumpą ir mielą",
					div8: "Yra 99 taškų limitas vienam turui. Suprantama, dauguma žemėlapio turų bus gerokai trumpesni. Nemanykite, kad auditorija norės pereiti per daugelį turo taškų. Jūsų sritis jums gali atrodyti įspūdinga, bet ji nebūtinai bus įspūdinga žiūrovams!",
					div9: "Kad sužinotumėt daugiau, vadovaukitės <a href='https://github.com/Esri/map-tour-storytelling-template-js/raw/master/Readme.pdf' target='_blank'>detaliu gidu</a>.",
					div10: "Įterpimo režimas",
					div11: "Jei norite įterpti šabloną į kitą puslapį per iframe, pridėdami papildomą parametrą \"&embed\" URL pabaigoje, pašalinsite antraštę. Šis režimas taip pat gali būti nustatytas parsisunčiamoje versijoje per konfigūracinį failą." 
				},
				tab5: {
					title: "Publikuojama",
					div1: "Kai baigsite, nepamirškite bendrinti žemėlapio turo su auditorija per aplikacijos elementų puslapį ArcGIS Online. Šio proceso metu, ArcGIS Online, jei būtina, pasiūlys atnaujinti priklausomus šaltinius (internetinį žemėlapį, elementų paslaugą), kurie neturi tų pačių bendrinimo teisių. Jei vienas iš jūsų resursų nėra bendrinamas su auditorija, vartotojai bus nukreipti į ArcGIS Online prisijungimo puslapį.",
					div2: "Jei naudojate talpinamą elementų paslaugą, sukurta žemėlapių turo vedlio pagalba, aplikacija už jus sutvarkys paslaugos saugumą, ir jūs išliksite vienintelis vartotojas, turintis redagavimo teises, net jei bendrinsite viešai.",
					div3: "Prieš publikuodami žemėlapių turą viešai, įsitikinkite, kad jis veiks ir jums atsijungus nuo ArcGIS.com paskyros.",
					div4: "Būtų gerai, jei peržiūrėtumėte, kaip žemėlapio turas atrodo naudojant iPad horizontalioje padėtyje. Taip pamatysite, ar užrašai neuždengia didelės vaizdų dalies."
				}
			}
        }
    })
);
