define({
  "viewer": {
    "loading": {
      "step1": "CHARGEMENT DU RECIT",
      "step2": "CHARGEMENT DES DONNEES",
      "step3": "INITIALISATION DE LA VISITE",
      "loadBuilder": "PASSAGE EN MODE DE GENERATEUR",
      "redirectSignIn": "REDIRECTION VERS LA PAGE DE CONNEXION",
      "redirectSignIn2": "(vous serez redirigé vers cette page une fois connecté)",
      "fail": "Le chargement de Map Tour a échoué",
      "failButton": "Réessayez"
    },
    "errors": {
      "boxTitle": "Une erreur s’est produite",
      "portalSelf": "Erreur fatale : échec de l'obtention de la configuration du portail",
      "invalidConfig": "Erreur fatale : configuration non valide",
      "invalidConfigOwner": "Erreur fatale : configuration non valide (propriétaire autorisé requis)",
      "invalidConfigNoWebmap": "Erreur fatale : configuration non valide (identifiant de carte Web ou d'application non spécifié dans index.htm)",
      "invalidConfigNoAppDev": "Aucun identifiant d'application cartographique Web ni aucune carte Web n'est spécifié dans les paramètres de l'URL (?appid= ou ?webmap=). En mode de développement, la configuration d'appid et de webmap dans index.html est ignorée.",
      "createMap": "Impossible de créer la carte",
      "invalidApp": "Erreur fatale : impossible de charger le récit",
      "noLayer": "La carte Web ne contient pas de couche de données valide pour Map Tour.",
      "noLayerMobile": "Le générateur Map Tour n'est pas pris en charge avec cette taille d'affichage. Si possible, redimensionnez votre navigateur pour pouvoir accéder au générateur ou élaborez votre récit sur un appareil doté d'un écran plus grand.",
      "noLayerMobile2": "Veuillez tourner votre appareil en orientation paysage pour utiliser le générateur Map Tour.",
      "noLayerView": "Bienvenue dans l'application Web Map Tour.<br />Le récit n'est pas encore configuré.",
      "appSave": "Erreur d'enregistrement du récit",
      "mapSave": "Erreur d’enregistrement de la carte Web",
      "featureServiceLoad": "Erreur de chargement du service d'entités",
      "notAuthorized": "Vous n'êtes pas autorisé à accéder à ce récit.",
      "notAuthorizedBuilder": "Vous n'êtes pas autorisé à utiliser le générateur Map Tour.",
      "oldBrowserTitle": "Le navigateur n’est pas entièrement pris en charge",
      "noBuilderIE8": "Le générateur Map Tour n'est pas pris en charge avant la version 9 d'Internet Explorer.",
      "ie10Win7Explain": "Le générateur interactif Map Tour n’est pas pris en charge dans Internet Explorer 10 sous Windows 7 lorsque la source de données est un service d’entités comportant des pièces jointes. Pour pouvoir utiliser un service d’entités comportant des pièces jointes, vous devez <a target='_blank' href='http://msdn.microsoft.com/en-us/library/ie/hh920756(v=vs.85).aspx'>définir manuellement le mode de document sur les normes d’Internet Explorer 9</a>, <a target='_blank' href='http://news.softpedia.com/news/How-to-Remove-IE10-and-Get-Back-to-IE9-on-Windows-7-308998.shtml'>utiliser Internet Explore 9</a> ou mettre à niveau vers Windows 8.",
      "oldBrowserExplain": "Ce navigateur ne prend pas en charge la génération automatique des miniatures à partir d’images que vous ajoutez dans votre visite cartographique. Vous pouvez créer une visite cartographique avec ce navigateur, mais vous devez fournir une image miniature distincte pour chacune des images que vous ajoutez.",
      "oldBrowserExplain2": "Pour profiter pleinement de l’application, <a href='http://browsehappy.com/' target='_blank'>mettez votre navigateur à niveau</a> ou <a href='http://www.google.com/chromeframe/?redirect=true' target='_blank'>activez Google Chrome Frame pour Internet Explorer</a>.",
      "oldBrowserExplain3": "Le générateur Map Tour ne fonctionne pas avec Internet Explorer 10 sous Windows XP.",
      "oldBrowserClose": "Fermer",
      "noViewerIE2": "Vous tentez d’afficher ce récit dans un navigateur plus ancien, non pris en charge. Certaines fonctionnalités peuvent ne pas fonctionner ou d’autres problèmes peuvent survenir. Nous vous suggérons d'utiliser Internet Explorer 11 ou un autre navigateur, comme Chrome.",
      "noViewerIE3": "Fin 2017, ce récit ne se chargera plus dans ce navigateur. Vous devrez alors utiliser un navigateur pris en charge pour afficher ce récit.",
      "attention": "Attention !"
    },
    "mobileHTML": {
      "showIntro": "AFFICHER LE TITRE",
      "hideIntro": "MASQUER LE TITRE",
      "navList": "Liste",
      "navMap": "Carte",
      "navInfo": "Multimédia",
      "introStartBtn": "Démarrer"
    },
    "desktopHTML": {
      "storymapsText": "Une Story Map",
      "builderButton": "Mode de générateur",
      "facebookTooltip": "Partager sur Facebook",
      "twitterTooltip": "Partager sur Twitter",
      "bitlyTooltip": "Obtenir un lien court",
      "bitlyStartIndex": "Relier au site actuel",
      "tooltipAutoplayDisabled": "Ceci n'est pas disponible en mode de lecture automatique",
      "autoplayLabel": "Mode de lecture automatique",
      "autoplayExplain1": "Le mode de lecture automatique fait avancer votre récit à intervalle régulier. Il est idéal pour les écrans publics, mais, dans d'autres cas, il peut compliquer la lecture du récit. Cette fonctionnalité n'est pas prise en charge sur les petits écrans.",
      "autoplayExplain2": "Lorsque ce mode est actif, vous disposez de contrôles pour lire le récit ou le mettre en pause, ainsi que régler la vitesse de navigation.",
      "takeTourText": "Suivre la visite",
      "backToStart": "Retour au début"
    },
    "builderHTML": {
      "panelHeader": "CONFIGURATION DU RECIT",
      "buttonSave": "ENREGISTRER",
      "buttonSettings": "Paramètres",
      "buttonShare": "Partager",
      "buttonView": "Mode d’affichage",
      "buttonItem": "Ouvrir l'élément d'application Web",
      "buttonHelp": "Aide",
      "buttonOrganize": "Organiser",
      "buttonOrganizeAndCover": "Organiser les points de visite et ajouter une page de couverture",
      "buttonAdd": "Ajouter",
      "buttonImport": "Importation",
      "buttonImportDisabled": "L’importation n’est pas disponible en cas d’utilisation du chargement d’images. Cliquez sur Ajouter pour charger une image.",
      "dataEditionDisabled": "La mise à jour des données est désactivée sur cette source de données CSV",
      "dataSourceWarning": "La couche de données Map Tour a été modifiée. Si les ID d’entités ne sont pas identiques, vous devez redéfinir l’ordre et les points masqués via l’option <b>Organiser</b>. Si les noms de champ sont différents, vous devez redéfinir les paramètres de champ <b>sous l’onglet Données dans Paramètres</b>.",
      "organizeWarning": "Un ou plusieurs points ajoutés en dehors du générateur interactif sont masqués.",
      "dataPicError0a": "Cette visite comprend des URL d'images non compatibles avec <b>%NB%</b>.",
      "dataPicError0b": "Cette visite peut comprendre des URL d'images non compatibles avec <b>%NB%</b>. <b>%NB%</b>.",
      "dataPicError1": "Map Tour requiert désormais que l'URL d'une image possède une des extensions suivantes : .jp(e)g, .png, .gif ou .bmp.",
      "dataPicError2": "Cela ne concerne pas vos visites cartographiques existantes publiées. Cependant, pour pouvoir utiliser le générateur interactif, vous devez d'abord résoudre le problème de l'URL en effectuant l'une des deux actions suivantes :",
      "dataPicError3": "Modifier les URL",
      "dataPicError4": "Cela aura pour effet d’ajouter <i>#isImage</i> à la fin des URL d’image non prises en charge. La plupart des serveurs prennent en charge les suffixes d’URL. Toutefois, après l’ajout de suffixes, vous devez vérifier que les URL d’image mises à jour fonctionnent en naviguant dans vos points. Si chaque image se charge, vous pouvez alors enregistrer le Map Tour. En revanche, si des <b>images sont endommagées, n’enregistrez pas le Map Tour</b>. Rechargez le générateur, puis effectuez la deuxième action.",
      "dataPicError5": "Limiter la visite aux images",
      "dataPicError6": "Du fait de cette option, toutes les URL sont considérées comme des images. Cela étant, vous ne pourrez pas ajouter des vidéos en utilisant le générateur interactif. Cette action est réversible, au cas où vous décideriez d’ajouter par la suite de la vidéo.",
      "dataPicError7": "Votre Map Tour a été limité aux images, si bien qu’il n’est pas possible d’utiliser des vidéos. Si vous décidez d’annuler cette limitation, vérifiez que vos images se chargent toujours correctement avant d’enregistrer le Map Tour. Vous pourrez rétablir cette limitation par la suite, si nécessaire.",
      "dataPicError8": "Supprimer la limitation des images",
      "dataPicError9": "Si ces URL pointent vers des vidéos, vous pouvez ignorer cet avertissement ; si elles pointent vers des images, vous devez effectuer l’une ou l’autre des actions suivantes :",
      "modalCancel": "Annuler",
      "modalApply": "Appliquer",
      "organizeHeader": "Organiser la visite",
      "organizeGeneralCaption": "Déplacez les points de la visite pour les trier",
      "organizeDelete": "Effacer",
      "organizeHide": "Masquer",
      "organizeReset": "Réinitialiser l'ordre et les points masqués",
      "addMaxPointReached": "Vous avez atteint le nombre maximal de points autorisés par les icônes définies et il est impossible d'en ajouter un autre.<br /><br />Notez que si vous supprimez des points existants, vous devrez recharger le récit.",
      "addMaxPointReachedMobile": "Vous avez atteint le nombre maximal de points autorisés et cette image ne peut pas être ajoutée.",
      "addClose": "Fermer",
      "addHeader": "Ajouter un nouveau point à la visite",
      "addTabPicture": "Elément multimédia",
      "addTabInformation": "Informations",
      "addTabLocation": "Emplacement",
      "addSelectCaption": "Sélectionner ou supprimer une image",
      "addNoteVideo": "Consultez l'aide pour savoir comment utiliser des vidéos",
      "addSelectCaptionNoFileReader": "Sélectionner une image",
      "addChangePhoto": "Modifier l'image et la miniature",
      "addPictureResolutionIntro": "La résolution de l’image est trop élevée :",
      "addPictureResolutionOldBrowser": "La résolution de l’image est trop élevée. Optimisez l’utilisation de Map Tour en spécifiant une résolution inférieure à %RECOMMENDED_RES%.",
      "addPictureResolutionResize": "Définir la résolution de l’image sur %RESOLUTION%",
      "addPictureResolutionKeep": "Conserver la résolution d’origine %RESOLUTION%",
      "addSelectThumbnail": "Sélectionner la miniature",
      "addNoThumbSelected": "Aucune miniature sélectionnée",
      "addThumbSelected": "Sélectionné(e)",
      "addCameraSettingsHeader": "PARAMETRES DE CAMERA",
      "addThumbnailHeader": "MINIATURE",
      "addLabelPicUrl": "Image",
      "addLabelThumbUrl": "Miniature",
      "addTextPlaceholderUrl": "Saisissez l'URL d'une image",
      "addTextPlaceholderUrl2": "Saisissez l'URL d'une page YouTube",
      "addTextPlaceholderUrl3": "Saisissez l'URL d'une page Vimeo",
      "addTextPlaceholderUrl4": "Saisissez l'URL d'incorporation d'une vidéo",
      "addLabelVideo": "Vidéo",
      "addMediaVideoOther": "Autre",
      "addMediaVideoHelp": "Vérifiez l'URL et obtenez la miniature par défaut",
      "addMediaVideoHelpTooltip1": "La vérification a réussi",
      "addMediaVideoHelpTooltip2": "La vérification a échoué",
      "addMediaVideoHelpTooltip4": "Recherchez l'option d'incorporation de la vidéo et copiez l'URL de la vidéo qui se trouve dans le code",
      "addLabelName": "Nom",
      "addLabelDescription": "Légende",
      "addTextPlaceholder": "Entrez des données",
      "addLocatePlaceholder": "Rechercher une adresse ou un lieu",
      "addPinColor": "Couleur",
      "addLatitude": "Latitude",
      "addLongitude": "Longitude",
      "addLatitudePlaceholder": "par ex. 34.056",
      "addLongitudePlaceholder": "par ex. -117.195",
      "addUploading": "Chargement d’un point dans la visite",
      "addSave": "Ajouter un point à la visite",
      "addMobileUploading": "Chargement de l’image",
      "addMobileName": "Entrer un nom",
      "addMobileNameMandatory": "Erreur : entrez un nom.",
      "addMobileError": "Une erreur s’est produite.",
      "settingsHeader": "Réglages",
      "settingsTabLayout": "Mise en page",
      "settingsTabColor": "Couleurs",
      "settingsTabLogo": "En-tête",
      "settingsTabFields": "Données",
      "settingsTabExtent": "Etendue",
      "settingsTabZoom": "Niveau de zoom",
      "settingsLayoutExplain": "Sélectionnez la mise en page de votre choix.",
      "settingsLayoutProfessional": "Trois volets",
      "settingsLayoutModern": "Intégré",
      "settingsLayoutSidePanel": "Volet latéral",
      "settingsLayoutSelected": "Mise en page sélectionnée",
      "settingsLayoutNew": "Nouveau !",
      "settingsLayoutSelect": "Sélectionner",
      "settingsLayoutNote": "Notez que, pour les points utilisant des vidéos, la légende est toujours placée sous la vidéo même si cette option est désélectionnée.",
      "settingsLayoutLocBtn": "Afficher un bouton de localisation",
      "settingsLayoutLocBtnHelp": "Fonctionnalité prise en charge sur la plupart des navigateurs. Apparaît uniquement en cas d’accès à la Story Map via HTTPS. Non visible si le récit est incorporé.",
      "settingsColorExplain": "Modifiez l’apparence en choisissant un thème prédéfini ou créez le vôtre.",
      "settingsLabelColor": "Couleurs d’en-tête, de contenu et de pied de page",
      "settingsLogoExplain": "Personnalisez le logo d’en-tête (250 x 50 px au maximum).",
      "settingsLogoEsri": "Logo Esri",
      "settingsLogoNone": "Aucun logo",
      "settingsLogoCustom": "Logo personnalisé",
      "settingsLogoCustomPlaceholder": "URL de l’image",
      "settingsLogoCustomTargetPlaceholder": "Lien",
      "settingsLogoSocialExplain": "Personnalisez le lien d’en-tête en haut à droite.",
      "settingsLogoSocialText": "Texte",
      "settingsLogoSocialLink": "Lien",
      "settingsLogoSocialDisabled": "Cette entité a été désactivée par l'administrateur",
      "settingsDataFieldsExplain": "Sélectionnez les champs du nom de la photo, de la légende et des couleurs.",
      "settingsDataFieldsError": "L’application ne peut pas déterminer le nom, la légende ou les couleurs appropriés. Sélectionnez les champs à utiliser ici. Ces paramètres peuvent être modifiés ultérieurement.",
      "settingsFieldsLabelName": "Nom",
      "settingsFieldsLabelDescription": "Légende",
      "settingsFieldsLabelColor": "Couleur",
      "settingsFieldsReset": "Réinitialiser la sélection des champs",
      "settingsExtentExplain": "Définissez l’étendue d’accueil du Map Tour sur la carte interactive ci-dessous.",
      "settingsExtentExplainBottom": "L’étendue définie va modifier l’étendue d’accueil de votre carte. Notez que cette étendue n’est pas utilisée si elle exclut le premier point de visite. Dans ce cas, la visite s’ouvre centrée sur le premier point.",
      "settingsExtentDateLineError": "L'étendue ne peut pas traverser le méridien de 180° de longitude",
      "settingsExtentDateLineError2": "Erreur de calcul de l'étendue",
      "settingsExtentDrawBtn": "Tracer une nouvelle étendue",
      "settingsExtentModifyBtn": "Modifier l’étendue",
      "settingsExtentApplyBtn": "Aperçu dans Map Tour",
      "settingsExtentUseMainMap": "Utiliser l'étendue de Map Tour",
      "settingsZoomExplain": "Définir le zoom pour les points du récit (facultatif).",
      "settingsLabelZoom": "Echelle/niveau",
      "settingsZoomFirstValue": "Aucun",
      "settingsFieldError": "Sélectionnez un champ dans chaque liste",
      "dataTitle": "Créer une couche Map Tour hébergée",
      "dataExplain": "Une nouvelle couche d'entités va être créée pour vos images et les points du Map Tour. La couche Map Tour n'est partagée avec personne sauf si vous partagez votre application Map Tour.",
      "dataExplainPortal": "Si la couche d’entités n’est pas créée correctement, contactez votre administrateur ArcGIS.",
      "dataNameLbl": "Nom de la couche",
      "dataFolderListLbl": "Dossier",
      "dataFolderListFetching": "Extraction des dossiers...",
      "dataRootFolder": "Racine",
      "dataNameError": "Attribuez un nom au service d’entités",
      "dataFolderError": "Sélectionnez un dossier valide",
      "dataSrcContainsInvalidChar": "Le nom du service d’entités contient un ou plusieurs caractères non valides (-, <, >, #, %, :, \", ?, &, +, / ou ).",
      "dataSrvAlreadyExistsError": "Un service de ce nom existe déjà au sein de l’organisation. Choisissez un autre nom.",
      "dataBtnSave": "Créer la couche",
      "dataFooterProgress": "Création en cours",
      "dataFooterSucceed": "Création réussie. Chargement en cours",
      "dataFooterError": "La création du service a échoué. Réessayez",
      "tabError": "Recherchez des erreurs dans tous les onglets",
      "introRecordBtn": "Introduction",
      "introRecordActivate": "Utilisez le premier point en introduction (n'apparaît pas dans le vidéorama)",
      "coverRecordActivate": "Utilisez le premier point comme page de couverture",
      "coverBuilder": "Configuration de la page de couverture",
      "cover": "Couverture",
      "showCover": "Afficher la couverture",
      "editCover": "Mettre à jour la couverture",
      "coverNoVideo": "La couverture ne prend pas en charge les vidéos. Sélectionnez une image.",
      "coverPreview": "Pour visualiser la couverture, enregistrez votre récit, puis affichez son aperçu à l’aide du bouton Afficher le récit.",
      "thirdPartyTerms": "En utilisant un service tiers, vous acceptez ses conditions d’utilisation : "
    },
    "addPopupJS": {
      "uploadingPicture": "Chargement de l’image",
      "uploadSuccess": "Chargement réussi",
      "uploadError": "Erreur de chargement de l’image",
      "uploadError2": "Erreur d'ajout de lentité (balise HTML non valide)",
      "notJpg": "Choisissez une photo jpeg à charger",
      "errorNoPhoto": "Choisissez une image à charger",
      "errorNoThumbnail": "Choisissez une miniature à charger",
      "errorInvalidPicUrl": "Saisissez une URL d’image valide. Elle doit commencer par https. Elle doit se terminer par jpg, png, gif ou bmp, ou par '#isImage' pour remplacer cette règle.",
      "errorInvalidThumbUrl": "Saisissez une miniature valide (commençant par https:// et se terminant par jpg, png, gif ou bmp).",
      "errorInvalidVideoUrl": "Saisissez une URL de vidéo valide (commençant par https://).",
      "errorNoName": "Attribuez un nom à ce point de la visite",
      "errorNoDescription": "Attribuez une légende à ce point de la visite",
      "errorNoLocation": "Définissez un emplacement pour ce point de la visite"
    },
    "builderJS": {
      "noPendingChange": "Aucune modification non enregistrée",
      "unSavedChangeSingular": "1 modification non enregistrée",
      "unSavedChangePlural": "modifications non enregistrées",
      "shareStatus1": "La visite n'est pas enregistrée",
      "shareStatus2": "La visite est partagée publiquement",
      "shareStatus3": "La visite est partagée au sein de l'organisation",
      "shareStatus4": "La visite n'est pas partagée",
      "popoverDiscard": "Voulez-vous vraiment ignorer les modifications non enregistrées ?",
      "yes": "Oui",
      "no": "Non",
      "popoverLoseSave": "En ouvrant la visionneuse, vous perdez les modifications non enregistrées",
      "ok": "OK",
      "popoverSaveWhenDone": "N’oubliez pas d’enregistrer lorsque vous avez terminé",
      "closeWithPendingChange": "Voulez-vous vraiment confirmer cette opération ? Vos modifications seront perdues.",
      "gotIt": "OK",
      "savingApplication": "Enregistrement du récit",
      "saveSuccess": "Récit enregistré",
      "saveError": "L’enregistrement a échoué, réessayez",
      "saveError2": "L'enregistrement a échoué en raison d'une balise HTML non valide dans un nom ou une description",
      "saveError3": "Le titre ne peut pas être vide",
      "dragColorPicker": "Me déplacer<br />ou modifier ma couleur",
      "dataWarningExtent": "Des données se trouvent à l’extérieur de l’étendue de la carte Web. Ces données ne seront pas utilisées comme points de la visite. Modifiez l’étendue de la carte si vous souhaitez les utiliser.",
      "dataWarningVisibi": "Votre couche Map Tour n’est pas visible dans l’étendue actuelle de la carte Web. Rendez votre couche Map Tour visible avec une carte de taille %MAPSIZE%.",
      "dataWarningEdit": "Modifier la carte Web",
      "dataWarningClose": "Fermer",
      "signIn": "Connectez-vous avec un compte sur",
      "signInTwo": "pour enregistrer le récit.",
      "switchBM": "Modifier le fond de carte"
    },
    "organizePopupJS": {
      "messageStart": "Vous avez choisi de supprimer",
      "messageSinglePoint": "un point de la visite",
      "messageMultiPoint": "des points de la visite",
      "messagePermantRemove": "Cette opération supprime définitivement",
      "messageRecord": "l’enregistrement",
      "messageRecordPlural": "les enregistrements",
      "messageConfirm": "de votre base de données. Voulez-vous continuer ?",
      "labelButtonShow": "Afficher",
      "labelButtonHide": "Masquer"
    },
    "picturePanelJS": {
      "popoverDeleteWarningPicAndThumb": "L’image et la miniature seront supprimées définitivement",
      "popoverDeleteWarningThumb": "La miniature sera supprimée définitivement",
      "popoverUploadingPhoto": "Chargement de l’image et de la miniature",
      "popoverUploadingThumbnail": "Chargement de la miniature",
      "popoverUploadSuccessful": "Chargement réussi",
      "popoverUploadError": "Le chargement a échoué, réessayez",
      "changePicAndThumb": "Modifier l’image",
      "changeThumb": "Modifier la miniature",
      "selectPic": "Modifier l'élément multimédia",
      "selectThumb": "Modifier la miniature",
      "uploadPicAndThumb": "Appliquer"
    },
    "headerJS": {
      "editMe": "Modifier",
      "templateTitle": "Définir le titre",
      "templateSubtitle": "Définir le sous-titre",
      "edit": "Mise à jour"
    },
    "crossFaderJS": {
      "setPicture": "Définir le titre de l’image",
      "setCaption": "Définir la légende de l’image"
    },
    "importPopup": {
      "title": "Importation",
      "prevBtn": "Retour",
      "nextBtn": "Suivant"
    },
    "importPopupHome": {
      "header": "Où vos images sont-elles stockées ?"
    },
    "onlinePhotoSharingCommon": {
      "pictures": "images",
      "videos": "vidéos",
      "disabled": "Cette entité a été désactivée par l'administrateur",
      "disabledPortal": "Cette entité requiert un serveur d'hébergement sur le portail. Contactez votre administrateur Portal for ArcGIS.",
      "header1": "Vos images doivent être partagées publiquement.",
      "header2": "L'importation sera limitée aux %NB1% premiers %MEDIA%.",
      "emptyDataset": "Erreur, aucune image trouvée",
      "footerImport": "Importation",
      "selectAlbum": "Sélectionner un album public",
      "selectAlbum2": "Sélectionner un album",
      "pleaseChoose": "Sélectionnez",
      "userLookup": "Rechercher",
      "userLookingup": "Recherche",
      "csv": "Référencées dans un fichier CSV",
      "advanced": "Options avancées",
      "advancedScratchLbl": "Démarrer une nouvelle visite",
      "advancedScratchTip": "Créez un Tour vide dans lequel vous pouvez ajouter des points de visite. Votre support doit déjà être en ligne. Cette option ne prend pas en charge le chargement de vos images.",
      "advancedCSVLbl": "Importer les données de la visite à partir d'un fichier CSV",
      "advancedCSVTip": "Importez le contenu de votre Tour à partir d’un fichier CSV qui fait référence à votre support en ligne. Cette option ne prend pas en charge le chargement de vos images.",
      "advancedCommonTip": "Pour cela, vos images et vidéos doivent déjà être en ligne.",
      "select": "Effectuer une sélection",
      "locUse": "Utiliser la géolocalisation des images",
      "locExplain": "Il peut être judicieux de ne pas utiliser des emplacements d’image sachant qu’ils peuvent être hérités de l’album, auquel cas toutes les photos se trouvent au même emplacement.",
      "locExplain2": "Il peut être judicieux de ne pas utiliser des emplacements de vidéo sachant qu’ils peuvent être hérités des paramètres utilisateur, auquel cas toutes les vidéos se trouvent au même emplacement."
    },
    "viewFlickr": {
      "title": "Importation de Flickr",
      "header": "Saisissez un nom d’utilisateur Flickr, puis sélectionnez un album ou une balise à importer.",
      "userInputLbl": "Saisir un nom d'utilisateur",
      "signInMsg2": "Utilisateur introuvable",
      "selectSet": "Sélectionner un album",
      "selectTag": "ou Sélectionner un tag",
      "footerImportTag": "Importer le tag sélectionné",
      "footerImportSet": "Importer l’album sélectionné"
    },
    "viewFacebook": {
      "title": "Importation de Facebook",
      "header": "Identifiez-vous avec votre compte d'utilisateur Facebook ou utilisez une page publique. Vous pouvez utiliser des albums privés pour créer une visite cartographique publique sans authentification d'utilisateur Facebook, ce qui permet de conserver les commentaires et autres éléments privés.",
      "leftHeader": "Utilisateur de Facebook",
      "rightHeader": "Page Facebook",
      "pageExplain": "Une page Facebook est une marque, une célébrité ou un produit public, comme <b>esrigis</b>. Vous pouvez obtenir le nom de la page après la première barre oblique inverse '/' de l'URL de la page.",
      "pageInputLbl": "Saisissez un nom de page",
      "lookupMsgError": "Page introuvable"
    },
    "viewPicasa": {
      "title": "Importation Google+",
      "header": "Saisissez votre adresse électronique ou votre identifiant.",
      "userInputLbl": "Adresse électronique ou identifiant Picasa/Google+",
      "signInMsg2": "Compte introuvable",
      "signInMsg3": "Pas d'album public",
      "howToFind": "<a href='https://links.esri.com/storymaps/google-photos-help' target='_blank'>En savoir plus</a>",
      "howToFind2": "Copier les chiffres situés entre le premier et le deuxième '/' d'une page Picasa"
    },
    "viewCSV": {
      "title": "Importation de CSV",
      "uploadBtn": "Sélectionnez ou supprimer un fichier CSV",
      "resultHeaderEmpty": "Le fichier CSV est vide",
      "resultHeaderSuccess": "%NB_POINTS% points chargés",
      "resultHasBeenLimited": "L'importation a été limitée aux %VAL1% premiers points sur %VAL2%, afin de respecter la limite de %VAL3% points par visite.",
      "browserSupport": "Votre navigateur n'est pas pris en charge. Pour pouvoir utiliser un fichier CSV vous devez <a href='http://browsehappy.com/' target='_blank'>mettre à niveau votre navigateur</a> ou faire appel à la visionneuse de cartes Web d'ArcGIS.com (consultez l'Aide).",
      "errorLatLng": "Les champs Latitude et Longitude sont introuvables. Les valeurs possibles pour la latitude sont : <i>%LAT%</i> et pour la longitude : <i>%LONG%</i>.",
      "errorFieldsExplain": "Le chargement a échoué, car les champs obligatoires suivants sont introuvables.",
      "errorFieldsName": "Les valeurs possibles du champ <b>Nom</b> sont : %VAL%",
      "errorFieldsDesc": "Les valeurs possibles du champ <b>Description</b> sont : %VAL%",
      "errorFieldsUrl": "Les valeurs possibles du champ <b>URL de l'image</b> sont : %VAL%",
      "errorFieldsThumb": "Les valeurs possibles du champ <b>URL de la miniature</b> sont : %VAL%",
      "errorFields2Explain": "Le chargement a échoué car le fichier CSV n'utilise pas les mêmes attributs que la couche pour les attributs suivants",
      "errorFields2Name": "<b>Nom</b> utiliser %VAL1% au lieu de %VAL2%",
      "errorFields2Desc": "<b>Description</b> utiliser %VAL1% au lieu de %VAL2%",
      "errorFields2Url": "<b>URL de l'image</b> utiliser %VAL1% au lieu de %VAL2%",
      "errorFields2Thumb": "<b>URL de la miniature</b> utiliser %VAL1% au lieu de %VAL2%",
      "resultFieldsAll": "Tous les attributs ont été importés",
      "resultFieldsNotAll": "Les attributs suivants n’ont pas été importés, car ils n’existent pas dans la couche de carte.",
      "resultFieldsNotAll2": "Les attributs suivants ont été importés",
      "footerNextBtnResult": "Importer dans la carte Web",
      "footerProgress": "Importation en cours",
      "footerSucceed": "Importation réussie. Chargement en cours"
    },
    "viewYoutube": {
      "title": "Importation de YouTube",
      "header": "Saisissez un nom d'utilisateur YouTube pour chercher des vidéos partagées publiquement.",
      "pageInputLbl": "Entrez un nom d'utilisateur YouTube",
      "lookupMsgError": "Utilisateur introuvable",
      "howToFind": "Comment trouver un nom d'utilisateur YouTube",
      "howToFind2": "Le nom d'utilisateur est affiché sous les vidéos",
      "found": "Trouvés",
      "noData": "Aucune vidéo publique trouvée"
    },
    "viewGeoTag": {
      "title": "Sélectionner et localiser vos images/vidéos",
      "header": "Les éléments localisés seront importés. Cliquez sur des éléments non localisés à importer pour les localiser.",
      "headerMore": "Aide",
      "headerExplain": "Lorsque vous cliquez sur le bouton <b>Importer</b>, seules les images ou les vidéos répertoriées dans l’onglet <b>Localisé</b> sont importées.<br><br>Les informations de géolocalisation stockées avec les images ou les vidéos sont importées automatiquement dès lors qu’elles sont accessibles. Tous les éléments sans géolocalisation sont répertoriés dans l’onglet <b>À localiser</b>. Pour localiser un élément répertorié dans cet onglet, cliquez dessus puis cliquez à l’emplacement souhaité sur la carte.<br><br>Pour supprimer un élément de l’onglet <b>Localisé</b> de sorte qu’il ne soit pas importé, cliquez sur le bouton Ne pas importer qui apparaît lorsque vous placez le curseur sur cet élément.<br><br>Astuce : si les informations de géolocalisation de votre support ne sont pas importées, vérifiez les paramètres de confidentialité de vote compte. Par exemple, assurez-vous que les données EXIF ne sont pas masquées dans les paramètres de votre compte Flickr. Par ailleurs, en cas de désactivation (réglage par défaut) de l’option de confidentialité Flickr associée à l’importation des données EXIF pour les nouveaux téléchargements, les géolocalisations ne sont pas stockées dans Flickr pour vos images tant que vous ne les téléchargez pas à nouveau ou ne spécifiez pas manuellement leurs emplacements.",
      "leftPanelTab1": "Pour localiser",
      "leftPanelTab2": "Localisé",
      "clickOrTap": "Cliquer sur la carte pour une localisation",
      "clearLoc": "Effacer les emplacements",
      "clickDrop": "Ne pas importer",
      "footerImport": "Importation",
      "footerProgress": "Importation en cours",
      "footerSucceed": "Importation réussie. Chargement en cours...",
      "loading": "Chargement en cours",
      "error": "Echec d'importation de la géolocalisation d'images, les géolocalisations ont été ignorées."
    },
    "initPopup": {
      "title": "Bienvenue dans le générateur Map Tour",
      "prevBtn": "Retour",
      "nextBtn": "Suivant"
    },
    "initPopupHome": {
      "header1": "Où sont stockées vos images ou vidéos ?",
      "header2": "Cet assistant va vous aider à créer un Map Tour à partir des images déjà stockées en ligne ou il les importera dans votre compte ArcGIS Online for Organizations.",
      "title1": "Elles sont déjà en ligne",
      "title2": "J'ai besoin de télécharger mes images",
      "hostedFSTooltip": "Chargez vos images et stockez-les dans votre visite (vidéos non prises en charge).",
      "hostedFsNA": "Vous devez être éditeur ou détenir un autre rôle doté du privilège de publication des couches d'entités hébergées. Contactez votre administrateur ArcGIS.",
      "hostedFsNA2": "Uniquement disponible avec un abonnement à ArcGIS Online. <a href='%LINK%'>Inscrivez-vous pour essayer la version d'évaluation gratuite</a>",
      "footer1": "Lorsque vous aurez terminé, n'oubliez pas de partager votre Map Tour avec votre public par le biais de la page d'élément de l'application.",
      "footer3": "Télécharger le modèle CSV",
      "footer4": "\"Enregistrer sous\" si le téléchargement ne fonctionne pas",
      "footer4bis": "Cliquez avec le bouton droit et sélectionnez \"Enregistrer sous\" si le téléchargement ne commence pas",
      "footer5": "En savoir plus",
      "footerProgress": "Création en cours",
      "footerSucceed": "Création réussie. Chargement en cours..."
    },
    "helpPopup": {
      "title": "Aide",
      "close": "Fermer",
      "tab1": {
        "title": "Introduction",
        "moreInfo": "Pour plus d’informations",
        "infoSites": "Consultez la <a href='https://storymaps.arcgis.com/en/app-list/map-tour/' target='_blank'>section Map Tour</a> du <a href='https://storymaps.arcgis.com' target='_blank'>site Web Esri Story Maps.</a>",
        "mtFAQ": "Consultez la <a href='https://storymaps.arcgis.com/en/faq/#category4' target='_blank'>FAQ du Map Tour</a>",
        "myStories": "Vous pouvez gérer vos Map Tours et rechercher les erreurs qui y figurent dans la section <a href='https://storymaps.arcgis.com/en/my-stories/' target='_blank'>Mes récits</a> du site Web.",
        "div1": "Le modèle Map Tour est conçu pour présenter des informations géographiques lorsque vous ne disposez pas d'éléments photographiques ou multimédias intéressants pour agrémenter l'histoire que vous souhaitez raconter.",
        "div2": "Le modèle produit une application Web attractive et conviviale qui vous permet de présenter un ensemble réduit d'emplacements sur une carte au sein d'une séquence numérotée que les utilisateurs peuvent parcourir. Ce modèle est destiné à être utilisé dans tous les navigateurs Web et sur tous les périphériques, dont les smartphones et les tablettes. <br /><br />",
        "div42": "Pour afficher des exemples de Map Tours créés par d’autres utilisateurs, <a href='https://links.esri.com/storymaps/map_tour_gallery' target='_blank'>visitez la bibliothèque</a> sur le <a href='https://storymaps.arcgis.com/' target='_blank'>site Web Story Maps</a>. Vous pouvez également nous suivre sur Twitter à <a href='https://twitter.com/EsriStoryMaps' target='_blank'>@EsriStoryMaps</a>.",
        "div5": "Nous aimerions connaître votre opinion ! Faites-nous part d’éventuels problèmes et de vos suggestions de nouvelles fonctionnalités sur le forum concernant les Story Maps sur <a href='https://links.esri.com/storymaps/forum' target='_blank'>Geonet.</a>"
      },
      "tab2": {
        "title": "Données",
        "div1": "Le principal élément à envisager lorsque vous créez un Map Tour est l’endroit de stockage de vos images. Un Map Tour peut utiliser des images stockées sur des services de partage de photos ou sur un serveur Web, ou des images que vous avez chargées à partir du disque.",
        "div1a": "Consultez la dernière section de cet onglet pour connaître les formats d'image et les vidéos pris en charge.",
        "div2": "Le générateur interactif vous propose deux options de gestion des images dans votre Map Tour :",
        "div3": "<ul><li>Vous pouvez utiliser des <b>photos déjà en ligne</b>, telles que des images dans Flickr ou Google+ ou des images stockées sur votre serveur web. Ces images seront référencées dans votre Map Tour via leurs URL.</li><li>Vous pouvez également <b>charger des photos depuis votre ordinateur</b> directement dans votre Map Tour. Cette option nécessite que vous déteniez un abonnement ArcGIS avec des privilèges d'éditeur ou d'administrateur, car un service d'entités hébergé est créé automatiquement, dans lequel vos photos sont stockées sous la forme de pièces jointes.</li></ul>",
        "div4": "Les principaux cas d'usage sont les suivants :",
        "div4b": "<b>Vos photos ne sont pas hébergées</b> pour l’instant et vous détenez un abonnement à ArcGIS : votre meilleure option consiste à utiliser un service d’entités hébergé. Tout comme les services de partage de photos publics, nous optimiserons vos photos pour créer des images à chargement rapide et vous aurez accès à toutes les fonctionnalités d’administration et de gestion de données de la plateforme ArcGIS.",
        "div5": "<b>Vous n'êtes pas membre d'une organisation</b> : vous devez d'abord charger vos images sur un site Web de partage de photos ou sur votre propre serveur Web. Le générateur vous aidera ensuite à utiliser ces images qui resteront hébergées à l'emplacement d'origine.",
        "div6": "<b>Vous envisagez de réutiliser un service d'entités existant</b>qui stocke vos images sous la forme de pièces jointes ou qui référence des images externes : reportez-vous à la section détaillée ci-après.",
        "div7": "<b>Vous êtes un utilisateur d'une version précédente</b> du modèle de Map Tour et vous possédez déjà votre fichier CSV qui référence vos images et miniatures : vous pourrez l'importer et peaufiner vos données. Le générateur prend en charge uniquement des CSV utilisant des champs de latitude/longitude, mais vous pouvez continuer à utiliser des CSV basés sur des adresses via votre carte Web (voir la section ci-après).",
        "div8": "Importation à partir de services de partage de photos en ligne",
        "div9a": "La prise en charge de Facebook a été interrompue, ${learn}.",
        "learn": "en savoir plus",
        "div9": "L'opération d'importation référence les images déjà hébergées en stockant leurs URL dans une collection d'entités de cartes Web. Les images ne sont pas stockées sur ArcGIS Online. Si les images hébergées sont inaccessibles, elles ne sont pas disponibles dans le Map Tour et une image « Photo non disponible » est utilisée. Selon le fournisseur de services de photos, le Map Tour peut ne pas importer le nom, la description et l'emplacement des images. Ces attributs sont stockés dans la carte Web et les modifications apportées aux services en ligne ne seront pas répercutées dans le Map Tour.",
        "div10": "Stockage des images sur un serveur Web",
        "div11": "Si vous décidez d’héberger vos images sur votre serveur web (au lieu d’accéder aux images depuis Flickr ou Google+ ou de les télécharger directement dans votre visite), vous devez créer manuellement les miniatures correspondantes. L’utilisation d’images à résolution maximale comme miniatures donnera des performances médiocres. Consultez cette <a href='https://links.esri.com/storymaps/faq_maptour_image_size' target='_blank'>FAQ</a> pour avoir des astuces sur le dimensionnement de vos images si vous y avez accès directement sur le web via des URL.",
        "div12": "Utilisation de données SIG existantes",
        "div13": "N’importe quel service d’entités, fichier CSV ou shapefile contenant des points peut être utilisé comme source de données d’un Map Tour s’il contient l’ensemble de champs attendu par l’application. Vous devez l’ajouter en tant que couche dans une carte web ArcGIS, puis partager la carte en créant un Map Tour.",
        "div14": "Les valeurs prises en charge pour le nom des champs sont (ne respectent pas la casse) :",
        "div151": "Nom",
        "div152": "Description",
        "div153": "Image",
        "div154": "Miniature",
        "div155": "Couleur ",
        "div16": "Si l'application ne trouve pas de champs correspondants lors de l'utilisation d'un service d'entités, la visionneuse ne fonctionne pas tant que vous ne configurez pas les champs à utiliser dans le générateur. Les couches CSV et de fichiers de formes ajoutées à la carte Web doivent comporter tous les champs requis, sinon le générateur ne fonctionne pas.",
        "div162": "Si vous utilisez un service d'entités qui stocke les images sous la forme de pièces jointes, <b>seules les entités possédant deux pièces jointes seront utilisées</b>. La première pièce jointe définit la première image et la seconde définit la miniature.",
        "div17": "Les champs d'image et de miniature sont obligatoires pour le service d'entités comportant des pièces jointes. Si votre service a les pièces jointes activées, le générateur vous permet de charger les images en tant que pièces jointes. Dans le cas contraire, vous pourrez seulement modifier l'URL de l'image et de la miniature.",
        "div172": "Lorsqu'ils existent, les champs d'image et de miniature sont toujours utilisés et les pièces jointes au service d'entités ne sont pas interrogées.",
        "div173": "Vous pouvez télécharger des exemples de fichiers CSV et de fichiers de forme sur le site",
        "div174": "Consultez cette <a href='https://links.esri.com/storymaps/faq_map_tour_gis_data' target='_blank'>FAQ</a> pour plus d’informations sur l’utilisation de données SIG existantes.",
        "div18": "Création de services d'entités hébergés à partir d'un CSV ou d'un fichier de forme",
        "div19": "Lorsque vous créez un service d'entités hébergé à partir d'un fichier CSV ou d'un fichier de formes, les pièces jointes ne sont pas activées par défaut. Pour les activer, ouvrez la page de détails du service d'entités, cliquez sur la petite flèche dans la section de la couche et vous verrez cette option. Après cela, le Map Tour continuera d'utiliser les images et les miniatures que vous avez référencées via les attributs. Si vous souhaitez charger vos images en tant que pièces jointes du service d'entités, vous pouvez le faire grâce à deux boutons situés dans le volet d'image (\"Modifier l'image\" et \"Modifier la miniature\").",
        "div20": "Vidéos et formats d'image pris en charge",
        "div21": "Si vous utilisez Flickr ou Google+ pour accéder à des images, le Map Tour y accède automatiquement sous forme de fichiers .jpg. Si vous téléchargez des images dans le générateur de Map Tour, elles doivent être au format JPG ou JPEG. Si vous référencez des images directement sur le web via leur URL, les formats d’image pris en charge sont les suivants : .jpg, .jpeg, .png, .gif et .bmp. Les vidéos YouTube sont prises en charge directement.",
        "div22": "Le modèle Map Tour ne comprenant pas de lecteur vidéo, vous devez utiliser le lecteur vidéo externe fourni par votre service d'hébergement de vidéo favori (trouvez l'option d'incorporation de la vidéo et copiez l'URL présente dans le code donné).Si vous souhaitez héberger la vidéo vous-même, vous pouvez créer une page HTML contenant un lecteur vidéo tel que <a href='http://www.videojs.com/'>Video.js</a>.",
        "div23": "Le générateur interactif ne possède pas de boîte de dialogue permettant d'inclure de la vidéo lors de l'utilisation de services d'entités avec des pièces jointes, mais il est possible de le faire en modifiant vos données en dehors du générateur interactif. Dans la visionneuse de carte arcgis.com, si vous modifiez les champs de l'image de manière à pointer sur une vidéo externe et que vous ajoutez un paramètre spécial à la fin de votre URL (#isVideo), votre support sera considéré comme une vidéo.",
        "div24": "Notez que vous devez tout de même avoir deux pièces jointes d'images valides pour que le point soit utilisé. Il est impossible d'utiliser des vidéos lors de l'utilisation de pièces jointes de service d'entités sans les champs d'image et de miniature."
      },
      "tab3": {
        "title": "Personnalisation",
        "div1": "Le générateur offre plusieurs options de personnalisation, accessibles en cliquant sur le bouton PARAMÈTRES dans le volet supérieur. Si vous ne trouvez pas l'option que vous cherchez, nous proposons également une version à télécharger que vous pouvez déployer sur votre serveur Web et améliorer de manière à correspondre à vos besoins.",
        "div2": "Nous recommandons l'utilisation de la version hébergée, sauf si :",
        "div3": "<li>Elle ne permet pas la personnalisation de l'interface utilisateur que vous recherchez, par exemple utiliser une image d'arrière-plan de l'en-tête</li><li>Vous êtes un développeur et vous souhaitez améliorer l'application</li>",
        "div4": "La version téléchargeable peut être configurée via l'identifiant d'une carte Web ou d'une application cartographique Web. Les principaux cas d'utilisation sont :",
        "div41": "Vous créez votre Map Tour grâce au générateur interactif contenu dans l'environnement hébergé et vous configurez le modèle avec l'identifiant de l'application de cartographie Web.Les paramètres que vous avez définis avec le générateur interactif seront appliqués.",
        "div42": "Vous créez votre carte Web en dehors du générateur interactif et vous configurez le modèle avec l'identifiant de la carte Web. Vous devrez lire la documentation pour savoir comment configurer le modèle.",
        "div43": "Notez que le générateur interactif est disponible dans sa version à télécharger mais avec certaines restrictions techniques sur des navigateurs tels qu'Internet Explorer dans une version ultérieure à la version 10.",
        "div5": "Pour télécharger la dernière version du modèle et en savoir plus sur son utilisation, rendez-vous sur la <a href='https://github.com/Esri/map-tour-storytelling-template-js' target='_blank'>page du projet GitHub</a>."
      },
      "tab4": {
        "title": "Astuces",
        "div0": "Navigateurs pris en charge",
        "div0a": "La visionneuse de Map Tour est prise en charge sous Internet Explorer 8+. Le générateur interactif est pris en charge sous Internet Explorer 9+. Nous testons activement dans tous les principaux navigateurs, mais si vous rencontrez des difficultés quelconques, nous vous recommandons d|'utiliser Chrome.",
        "div0b": "Si vous rencontrez des difficultés, faites-le nous savoir. Dans l'intervalle, en créant votre Map Tour grâce au modèle CSV vous réduisez votre interaction avec l'interface du générateur.",
        "div1": "Images",
        "div2": "Bien que des images de tailles, de formes et d’orientations différentes puissent être utilisées dans un Map Tour, nous vous recommandons d’employer des images en orientation de type paysage et non de type portrait. Les images aux proportions 4:3 sont les mieux adaptées. Dans les mises en page intégrées et à trois volets, dans lesquelles la légende est superposée à l’image, l’utilisation d’images en orientation de type portrait peut entraîner l’obscurcissement d’une grande partie de l’image par la légende. Pour les mises en page intégrées et à trois volets, il est conseillé d’utiliser la même taille et la même forme pour toutes les images dans la mesure du possible. Ainsi, l’utilisateur n’est pas distrait par des images de tailles différentes au fur et à mesure de la visite.",
        "div2a": "Nous recommandons une taille d'image maximale de 1 000 pixels de largeur x 750 pixels de hauteur pour les images principales et de 140x93 pour les miniatures.",
        "div3": "Formatage du texte de votre légende grâce à des balises HTML",
        "div4": "Vous pouvez saisir des balises HTML dans les légendes pour définir la mise en forme et les liens. Par exemple, ces balises permettent d’ajouter un hyperlien vert :",
        "div4aa": "<b>Créer une page de couverture pour la visite Volet latéral</b><br>La mise en page Volet latéral prend en charge une page de couverture facultative, que vous pouvez utiliser pour retenir l’attention de votre public avec une superbe image en plein écran. Pour configurer la page de couverture pour une visite Volet latéral, commencez par ajouter tout ou partie de vos points à votre visite. Cliquez ensuite sur le bouton Organize (Organiser), puis, dans la boîte de dialogue qui s’affiche, assurez-vous que le point de visite à utiliser pour définir la page de couverture est le premier point de votre visite. Cochez ensuite la case 'Utiliser le premier point comme page de couverture' dans cette boîte de dialogue. Le nom de votre premier point de visite devient le titre affiché en page de couverture, la légende de ce point devient le sous-titre, et l’image de ce point est utilisée comme image de page de couverture. La vidéo n’est pas prise en charge sur la page de couverture. Consultez cette <a href='https://links.esri.com/storymaps/faq_map_tour_cover_page_sp' target='_blank'>FAQ</a> pour plus d’informations.</a>",
        "div4a": "Rédigez un sous-titre de qualité pour votre visite",
        "div4b": "Prenez le temps de rédiger un sous-titre percutant pour votre visite. Le sous-titre est un excellent moyen d’attirer l’attention des personnes sur la visite et de leur indiquer ce qu’ils vont y découvrir. Vous pouvez également y préciser le lieu ou le pays dans lequel se déroule la visite. Ne supposez pas que les personnes savent situer la ville qui fait l’objet de la visite. N’indiquez cependant pas un sous-titre trop long. Si aucun sous-titre approprié ne vous vient à l’esprit, n’en indiquez pas. Contrairement aux mises en page intégrées et à trois volets, la mise en page à volet latéral n’accepte pas de sous-titre dans son en-tête. Si vous utilisez l’option de page de couverture de la mise en page à volet latéral, la légende du premier point de la visite est affichée sur la page de couverture et tient lieu de sous-titre pour la visite.",
        "div5": "Couches complémentaires",
        "div6": "Vous pouvez ajouter des couches supplémentaires pour fournir du contexte au Map Tour. Ces couches peuvent contenir d’autres entités géographiques que vous voulez que la carte présente en plus des points du Map Tour, par exemple la zone d’étude, un itinéraire à pied ou en voiture reliant les points de la visite, etc. Le modèle de Map Tour affiche ces couches complémentaires grâce à la symbologie que vous spécifiez dans la carte web, mais les fenêtres contextuelles ne sont pas prises en charge. Pour ajouter des couches supplémentaires à votre visite, enregistrez votre travail et fermez le générateur de Map Tour. Ouvrez ensuite la carte web utilisée dans la visite. Vous la trouverez dans Mon contenu ArcGIS ou dans la section Mes récits du site web Story Maps.",
        "div7": "Faites en sorte que votre visite soit brève et factuelle",
        "div8": "Le nombre de points par visite est limité à 99. La plupart des Map Tours sont bien entendu beaucoup plus courts. Ne vous attendez pas à ce que votre public ait la patience de parcourir un trop grand nombre de points. Vous trouvez probablement votre sujet fascinant, mais ce ne sera peut-être pas le cas de tout le monde !",
        "div10": "Mode d'incorporation",
        "div11": "Si vous souhaitez intégrer le modèle dans un autre site web via un iframe, le fait d'ajouter le paramètre facultatif \"&embed\" à la fin de l'URL supprime l'en-tête.",
        "div12": "Évitez d’utiliser un iFrame de largeur étroite qui fait basculer le Map Tour en affichage réactif pour petits écrans, ce qui correspond à la vue utilisée pour la visite sur les appareils mobiles. Pour une plus grande facilité d’utilisation, lorsque vous intégrez un Map Tour, il est conseillé de toujours fournir un lien en regard de la visite incorporée afin que les utilisateurs puissent le lancer en plein écran."
      },
      "tab5": {
        "title": "Publication",
        "div1": "Lorsque vous aurez terminé, n'oubliez pas de partager votre visite cartographique avec votre public via le bouton PARTAGER ou la page des détails de l'application dans ArcGIS Online.",
        "div2a": "Partage de la visite via le générateur",
        "div2b": "Le bouton PARTAGER met à jour l'application et les éléments de la carte Web. Si les données de votre visite sont stockées dans un élément du service d'entités, elles sont également mises à jour. Si vous avez ajouté d'autres couches via la visionneuse de carte ArcGIS.com, elles ne sont pas mises à jour. Il est possible qu'en conséquence, la visite ne soit pas partagée comme vous le souhaitez. Les éléments qui ont déjà les privilèges requis (ou plus) ne sont pas mis à jour.",
        "div2c": "Partage de la visite via ArcGIS Online",
        "div2d": "Lorsque vous partagez l'application via ArcGIS Online, vous pouvez être invité à mettre à jour les ressources dépendantes (carte Web, service d'entités, couche d'habillage) qui ne sont pas partagées de la même manière. Si la visite cartographique est publique et qu'une de vos ressources n'est pas partagée avec votre public, les utilisateurs seront redirigés vers la page de connexion à ArcGIS Online.",
        "div3t": "Sécurité du service d'entités",
        "div3a": "Si vous utilisez un service d'entités hébergé créé via le générateur de Map Tour, l'application gère la sécurité du service et vous restez la seule personne dotée de privilèges de modification, même si vous partagez le service publiquement.",
        "div3t2": "Avant de partager votre visite avec votre public",
        "div3": "Vérifiez que la visite fonctionne lorsque vous n'êtes pas connecté avec votre compte ArcGIS.com. L'URL que vous allez utiliser ne doit pas rediriger vers une page de connexion ou vers le mode de générateur.",
        "div4": "Il est judicieux de vérifier l'aspect de votre visite cartographique sur un iPad en orientation Paysage. Cela vous permet de voir si vos légendes couvrent une trop grande surface des images. Vous pouvez ainsi également vérifier que la longueur de votre sous-titre est adaptée et qu'il n'est pas coupé.",
        "div5a": "Recommandation pour la recherche",
        "div5b": "Pour aider les utilisateurs à trouver votre visite cartographique s'ils parcourent ArcGIS Online, nous vous recommandons d'ajouter la balise \"Story Map\" sur la page des éléments de l'application Map Tour (pas sur la page des éléments de votre carte Web), ainsi que des balises, telles que le nom de la région où se situe la visite, le nom du pays s'il ne s'agit pas des Etats-Unis, ainsi que des balises thématiques comme \"art public\", \"guide touristique\" ou \"lieux historiques\". Ces balises nous aident également chez Esri à trouver de nouveaux exemples attrayants de visites que nous pouvons mettre en évidence dans nos galeries et promouvoir sur les réseaux sociaux. Nous vous recommandons également d'ajouter une miniature attirante sur la page des éléments de votre application, telle qu'une petite capture d'écran de la visite ou une des images qui la composent. Cette image est utilisée automatiquement si votre visite cartographique est ajoutée dans une galerie ArcGIS Online."
      }
    },
    "share": {
      "firstSaveTitle": "Map Tour enregistré",
      "manageStory": "Gérer votre récit",
      "manageStoryA1": "Astuce : vous pouvez utiliser %LINK1% pour rechercher les éventuelles erreurs présentes dans votre récit, changer son mode de partage, le rendre esthétique sur les réseaux sociaux, etc. Apprenez-en davantage sur Mes récits %LINK2%.",
      "manageStoryA1V1": "Mes récits",
      "manageStoryA1V2": "here",
      "shareTitle": "Partager votre visite",
      "sharePrivateHeader": "Votre visite n'est pas partagée, souhaitez-vous la partager ?",
      "sharePrivateBtn1": "Partager publiquement",
      "sharePrivateBtn2": "Partager avec mon organisation",
      "sharePrivateProgress": "Partage en cours...",
      "sharePrivateErr": "Echec du partage, essayez à nouveau ou",
      "sharePrivateOk": "Partage mis à jour, chargement...",
      "sharePreviewAsUser": "Aperçu",
      "shareHeader1": "Votre visite est <strong>accessible publiquement</strong>.",
      "shareHeader2": "Votre visite est accessible par les membres de votre organisation (une ouverture de session est requise).",
      "shareLinkHeader": "Partager votre visite",
      "shareLinkOpen": "OUVRIR",
      "shareA1": "Utilisez %SHAREIMG% sur <a href='%LINK1%' target='_blank'>la page de l'élément d'application</a>. Si vous voulez annuler le partage de la carte Web, utilisez <a href='%LINK2%' target='_blank'>la page de l'élément de carte Web</a>.",
      "shareWarning": "Le partage %WITH% a été désactivé, car vous ne possédez pas la <a href='%LINK%' target='_blank'>carte Web</a>.",
      "shareWarningWith1": "publiquement",
      "shareWarningWith2": "publiquement et avec l'organisation",
      "viewStory": "Afficher le récit"
    },
    "locator": {
      "error": "Emplacement non disponible"
    },
    "saveErrorSocial": {
      "title": "Mise à jour du partage sur les réseaux sociaux",
      "panel1": "L'apparence de votre récit sur les réseaux sociaux a été améliorée, mais le titre de votre élément d'application Web ArcGIS n'est pas le même que le titre de votre récit.",
      "panel1tooltip": "Si vous définissez un titre, un résumé et une image miniature, votre récit ressemblera à ceci :",
      "panel2": "Quel titre voulez-vous utiliser sur les réseaux sociaux :",
      "panel2q1": "Titre du récit (recommandé)",
      "panel2q1tooltip": "Si vous choisissez cette option, le titre de votre élément sera modifié afin de correspondre au titre de votre récit et les autres modifications apportées dans le générateur seront synchronisées.",
      "panel2q2": "Titre de l'élément",
      "panel3": "Pour encore améliorer l'apparence de votre récit sur les réseaux sociaux, utilisez ${MYSTORIES} pour ajouter un résumé et une image miniature.",
      "panel4": "Ne plus m'avertir pour ce récit",
      "mystories": "Mes récits",
      "btnSave": "Enregistrer"
    },
    "bannerNotification": {
      "learnMore": "En savoir plus",
      "close": "Fermer",
      "dontShowAgain": "Ne plus afficher ce message"
    },
    "httpsTransitionNotification": {
      "bannerMsg": "Message important sur la sécurité web et les Story Maps",
      "s1h1": "Esri améliore la sécurité des Story Maps",
      "s1p1": "Vos Story Maps vivent sur le web, et la communauté web s’efforce en permanence d’établir et de mettre en œuvre une meilleure sécurité. HTTPS, qui offre une connexion sécurisée pour le contenu transmis via Internet, émerge en tant que mode d’accès normal au contenu web. La plupart des navigateurs actuels affichent à présent un avertissement lorsque HTTP est utilisé au lieu de HTTPS. En raison de cette nouvelle norme, nous vous recommandons vivement d’utiliser des liens HTTPS pour la création et le partage de Story Maps, et d’utiliser des URL HTTPS uniquement en cas d’intégration de contenu web ou de lien vers des images avec une Story Map.",
      "s1p2": "Concrètement, cela signifie que l’accès à une Story Map et à la totalité de son contenu (y compris les images, les couches, les applications et les sites web incorporés) doit s’effectuer via des liens qui commencent par HTTPS et non plus par HTTP. Ceci garantit à vos lecteurs la meilleure expérience, car la plupart des navigateurs web indiqueront que vos narrations sont sécurisées.",
      "s2h1": "Que dois-je faire ?",
      "s2p1": "Esri œuvre afin que ceci soit une transition facile pour les auteurs et les lecteurs de Story Map. Les générateurs Story Map et Mes récits proposent maintenant des outils vous aidant à repérer le contenu non sécurisé (HTTP) de vos narrations et vous donnant des conseils sur la manière de traiter ce contenu. Il convient de vérifier le contenu non sécurisé de vos récits et de le mettre à jour vers le protocole HTTPS dès que possible.",
      "action1": "Fermer",
      "action2": "Vérifier mes récits maintenant",
      "action3": "En savoir plus"
    },
    "embedBar": {
      "share": "Partage",
      "fullScreen": "Plein écran",
      "enlarge": "Agrandir",
      "newTab": "Ouvrir dans un nouvel onglet",
      "tagline": "Une Story Map",
      "exitFullScreen": "Quitter le mode Plein écran"
    },
    "june2018SurveyMessage": {
      "bannerMsg": "Pouvons-nous vous poser une question ? C’est pour vous l’occasion de contribuer aux Story Maps de demain.",
      "s1h1": "Donnez-nous votre avis, prenez part à l’avenir",
      "s1p1": "Vos commentaires nous sont précieux. Ils nous permettront de mieux vous connaître, et ainsi d’améliorer nos Story Maps. Nous vous serions reconnaissants de bien vouloir participer à cette enquête qui ne prendra que trois minutes de votre temps.",
      "s2p1": "Encore merci d’utiliser Esri Story Maps !",
      "action1": "Fermer",
      "action2": "Participer à l’enquête"
    },
    "licenseChange2018": {
      "noAccess": "La licence de votre compte (%USER_NAME%) ne permet pas d’ouvrir une Story Map non publique. Demandez à l’administrateur de votre organisation de vous attribuer un type d’utilisateur qui inclut les Story Maps ou une licence Essential Apps sous forme de complément."
    }
  }
});